### PR TITLE
Long task warn to err

### PR DESCRIPTION
**Pull request by jonkeller**
Stop logging attrib.containerSrc to ensure compliance with privacy policy

### CODE REVIEW

**Comment by zhouyx** [comment]
@cramforce. Want to confirm that we are OK to log analytics vendor name to our error report before merge.

**Comment by jonkeller** [comment]
Since #12678 was already merged:
* If we do not merge #12705 before the next canary, vendor+src+duration+occurrences will be logged.
* If we do merge #12705 before the next canary, only vendor will be logged.

Therefore my opinion is we should merge this. If it is not okay to log analytics vendor name, merging this won't make the situation worse (and will make it better due to preventing logging of the other 3)...we'll just need to fix that in a separate PR.

**Comment by jonkeller** [comment]
Thanks @cramforce. Made the change you suggested.

**Comment by jridgewell** [comment]
>  I think you can keep everything else.

Everything else will cause new errors to be logged for every occurrence, for every ms difference.

**Comment by jonkeller** [comment]
> Everything else will cause new errors to be logged for every occurrence, for every ms difference.

Re-removed duration and occurrences in #12740 so that this one (#12705) can be done, and once discussion is resolved, #12740 can be either merged or deleted.

**Pull request merged**
