### PR TITLE
Run visual tests for prod and canary configs

### LINKED ISSUE #10682: Visual diff tests need to include prod/canary config
Visual diff test only test again `gulp build & gulp serve` page, which means it does not test with the experimental flag. 

Discovered through #10656. [percy build link](https://percy.io/ampproject/amphtml/builds/298150)

For example here: A feature with experimental flag 'flag-test' brings a breaking css change. We won't be able to discover that when we launch the feature by toggling 'flag-test' in prod-config. Current test can only discover visual differences after we remove experimental flag 'flag-test' in our code when the feature is stable. This is too late.

Talked to @rsimha-amp. He proposed two ways to fix this. 

1. Serve both configs (canary/prod) from one build and serve cycle, and add tests for both configs
2. Add two separate builds and have two separate percy runs for each PR. (not the best use of resources though)

cc @cramforce

### PR DESCRIPTION
**Pull request by rsimha-amp**
Fixes #10682

### CODE REVIEW

**Comment by erwinmombay** [comment]
would it make sense to just turn every flag on so we don't have to do two snapshots?

**Comment by rsimha-amp** [comment]
> would it make sense to just turn every flag on so we don't have to do two snapshots?

I think the idea is to separately test the prod and canary configs. @zhouyx for comment.

**Comment by rsimha-amp** [comment]
Tested this with a local build to make sure the correct version of the AMP runtime is being served when the `prod` and `canary` snapshots were being generated. This is now ready for review.

**Pull request merged**
