### PR TITLE
Remove display locking experiment from amp-accordion

### PR DESCRIPTION
**Pull request by caroqliu**
This PR removes use of `content-visibility: hidden-matchable` and `beforematch` event from `amp-accordion` versions `0.1` and `1.0`, as well as the `"amp-accordion-display-locking"` flag. The origin trial is set to expire May 18, 2021, with no plans to renew and may be replaced with an alternative [attribute API](https://github.com/w3c/csswg-drafts/issues/5595#issuecomment-776914538).

### CODE REVIEW

**Review by jridgewell — APPROVED** [review]

**Comment by caroqliu** [comment]
@ampproject/wg-stories, can I get a second opinion on this [percy diff](https://percy.io/ampproject/amphtml/builds/9697042)? Looks like one version has a scrollbar and the other doesn't.

**Comment by gmajoulet** [comment]
I approved it, cc @Enriqe who added this test like week FYI

**Comment by caroqliu** [comment]
> I approved it, cc @Enriqe who added this test like week FYI

Thank you!

**Review by krdwan — APPROVED** [review]
Awesome, thanks for doing this!

**Pull request merged**
