### PR TITLE
📖 Fix malformed doc on amp.dev

### PR DESCRIPTION
**Pull request by zhangsu**
Apparently [filter] doesn't really work well in the middle of a bullet
list. Here's how it looks today:

Screenshot_20210129-110834

We'd have to duplicate the content, following prior art here
that wraps the entire list into filter blocks:

https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/0.1/amp-accordion.md#usage

/to @caroqliu @CrystalOnScript

### CODE REVIEW

**Review by caroqliu — APPROVED** [review]

**Review by CrystalOnScript — APPROVED** [review]
Thank you!

**Review by calebcordry — APPROVED** [review]

**Comment by calebcordry** [comment]
@danielrozenberg feels like need for bundle size approval here might be a bug?

**Comment by rsimha** [comment]
> @danielrozenberg feels like need for bundle size approval here might be a bug?

Not Daniel's fault, but my fault. (We were mistakenly executing all runtime tests for a docs-only change. Just merged a fix via #32307.)

**Comment by zhangsu** [comment]
The CircleCI failure also seems like an unrelated infra issue... Is there a way to merge this ignoring that?

**Comment by rsimha** [comment]
> The CircleCI failure also seems like an unrelated infra issue... Is there a way to merge this ignoring that?

CircleCI requires PR branches to be synced past the most recent change to `.circleci/config.yml`. I've reached out to their support team to ask if this restriction can be lifted and they can automatically pull the latest config from `master`.

For now, if you rebase your PR branch on `master`, the failure should go away. Alternatively, you can ignore it (since it's not yet a required check).

**Comment by zhangsu** [comment]
Uhh thanks. Rebased and now it all passes!

**Comment by zhangsu** [comment]
@caroqliu could you help merge this? Thanks!

**Comment by rsimha** [comment]
I can help. (The check name for our cross browser tests were recently changed to drop the `12.x` due to a node update, so I'm first going to update the base branch and re-run test one more time.)

**Comment by caroqliu** [comment]
Thank you @rsimha !

**Comment by rsimha** [comment]
Tests green: https://travis-ci.com/github/ampproject/amphtml/jobs/480141532#L745-L757.

Merging now.

**Pull request merged**
