### PR TITLE
✨Support for MGID | Idealmedia | Lentainform ads network

### PR DESCRIPTION
**Pull request by DenyHF**

### CODE REVIEW

**Comment by torch2424** [comment]
cc @ampproject/wg-ads

**Comment by torch2424** [comment]
@DenyHF 

Hello! Thank you very much for the contribution! 👍 

If I may ask, could we split each vendor into it's own PR? I don't mind reviewing this. But in case something goes wrong, and we have to revert, I wouldn't want to have to revert 3 ad vendors in one.

Been catching up after our AMP Conf, so thank you for your patience on our reply! 😄 

Let me know what you think!

**Comment by DenyHF** [comment]
@torch2424 
Hello!
I divided the request into 3 parts, for convenient review.

https://github.com/ampproject/amphtml/pull/22100
https://github.com/ampproject/amphtml/pull/22101
https://github.com/ampproject/amphtml/pull/22102

**Comment by torch2424** [comment]
@DenyHF Thank you very much! It is very much appreciated splitting this up. Will close this PR, and continue this review on the three separate ones. Thank you! 😄

**Pull request closed without merging**
