### PR TITLE
Restore visibility methods as restricted in the viewer for viewer-integration fixes

### PR DESCRIPTION
**Pull request by dvoytenko**
Ref: b/113673017
Fixes https://github.com/ampproject/amphtml/issues/24914

### CODE REVIEW

**Comment by zhouyx** [comment]
Should we revert the `viewer-interface.js` file as well?

**Comment by dvoytenko** [comment]
> Should we revert the `viewer-interface.js` file as well?

No. I'd rather keep viewer-interface unaffected.

**Comment by zhouyx** [comment]
What does the `viewer-interface.js` file do? I thought that's the API between viewer and AMP doc. If so would the viewer script refer to that file?

**Comment by zhouyx** [comment]
Talked offline. viewer-interface is the internal API.

**Pull request merged**
