### PR TITLE
Intent To Implement: Yengo support for amp-ads

### PR DESCRIPTION
**Pull request by dvdyakonov**
Added support for Yengo widgets to amp-ad elements

### CODE REVIEW

**Comment by dvdyakonov** [comment]
Hi, 
Do I need to fix anything?

**Comment by zhouyx** [comment]
@dvdyakonov Looks great! Please rebase to latest to fix the travis build.

**Comment by dvdyakonov** [comment]
Help me please, how to revert latest push with merge commit?

**Comment by zhouyx** [comment]
@dvdyakonov can you try to rebase off of the upstream master 

```bash
git remote add upstream https://github.com/ampproject/amphtml.git
git fetch upstream
git checkout yengo
git pull --rebase upstream master
git push -f origin yengo
```

**Comment by dvdyakonov** [comment]
@zhouyx done!

**Comment by zhouyx** [comment]
@dvdyakonov Upstream head looks right, however the commit history looks incorrect, that may explain why CLA bot does not respond properly. 
Please fix it. I think one workaround is to reset HEAD to your first commit `7ec44ad` and rebase to master there.

**Comment by dvdyakonov** [comment]
@zhouyx done! 
Thank you for help!

**Pull request merged**
