### PR TITLE
Ramp up A4A experiment to 5% in the AMP canary.

### PR DESCRIPTION
**Pull request by tdrl**

### CODE REVIEW

**Comment by erwinmombay** [comment]
LGTM

**Comment by erwinmombay** [comment]
@tdrl do you need this to go in today? i think we cut a canary yesterday but have not released it yet so can re-do one.

**Comment by tdrl** [comment]
Yes, we would really like it to go in today if possible.  (Sorry for being late -- I didn't realize that the control files for AMP_CONFIG had moved to GitHub 'til this morning.)

**Comment by erwinmombay** [comment]
@tdrl no problem. merging this

**Comment by tdrl** [comment]
Thank you!

**Pull request merged**
