### PR TITLE
ColombiaAnalytics

### PR DESCRIPTION
**Pull request by ColombiaAnalytics**

### CODE REVIEW

**Comment by avimehta** [comment]
Hello, I talked to mukul yesterday and told him that these changes we not really needed. Did the alternative not work?

**Comment by ColombiaAnalytics** [comment]
Squashed the commits and signed the CLA.

**Comment by avimehta** [comment]
@ColombiaAnalytics The PR still shows 42 commits. Please fix.
@jridgewell Do you know to get rid of the extra commits?

**Comment by jridgewell** [comment]
`git remote add ampproject https://github.com/ampproject/amphtml.git && git fetch ampproject && git pull --rebase ampproject master`

**Comment by ColombiaAnalytics** [comment]
Hi,

On executing the above mentioned command I see my git log changes but the latest changes in the files get lost and it shows our previous code that we pushed few days back which was incorrect.
I googled and rebased the commits as in help docs mentioned and  if you see the commit log 
-->   commit 8ad8b3095241453d3085e77279bc6d594d93c70d
It has rebased the logs but doesn't remove other logs from commit. 

Is there any other way to get rid of these extra commits from our list of commits. Or I would delete the Colombia Analytics Repository and recreate it. And Start from fresh.

**Pull request closed without merging**
