### PR TITLE
build: fix z-index

### PR DESCRIPTION
**Pull request by samouri**
**summary**
I created this PR via running `amp get-zindex --fix`.
I do not know why this was able to get out of sync.

### CODE REVIEW

**Review by caroqliu — COMMENTED** [review]
Should we have to include these for files that don't exist permanently in the repo? The ones added in this PR are built only for the npm publishing step. FYI @estherkim

**Comment by samouri** [comment]
See this check that is failing: https://app.circleci.com/pipelines/github/ampproject/amphtml/12352/workflows/f6450e19-40c7-4955-9a49-e1eebc0081cc/jobs/197521/parallel-runs/0/steps/0-111

Should we modify the z-index check to ignore anything in `dist` instead?

**Comment by alanorozco** [comment]
@samouri: Yes, we should ignore `dist`

**Comment by alanorozco** [comment]
https://github.com/alanorozco/amphtml/blob/a7fec792bb128c43a8dde86eb0d544d706c13057/build-system/tasks/get-zindex/index.js#L208-L212

```diff
      getZindexChainsInJs([
        '{3p,src,extensions}/**/*.js',
        '!extensions/**/test/**/*.js',
        '!extensions/**/storybook/**/*.js',
      ]),
```

**Review by alanorozco — APPROVED** [review]

**Review by caroqliu — APPROVED** [review]

**Review by kristoferbaxter — APPROVED** [review]

**Pull request merged**
