### PR TITLE
📖  Update introduction to new amp-render docs

### PR DESCRIPTION
**Pull request by morsssss**
Suggesting a reordering of the first paragraph under "Usage", plus an additional paragraph explaining the philosophy behind this new component and its distinction from `amp-list`.

/cc @nainar , @dmanek , @CrystalOnScript

### CODE REVIEW

**Review by CrystalOnScript — APPROVED** [review]

**Review by dmanek — APPROVED** [review]

**Comment by morsssss** [comment]
@dmanek it looks like the tests stalled a little while ago. Do I have to push a null commit or something to retrigger?

**Comment by dmanek** [comment]
@morsssss yes, you can rebase and push again, it should re-trigger the jobs.

**Comment by rcebulko** [comment]
@morsssss Something about that merge looks...off. GitHub is saying this touches 250+ files for some reason. It looks like maybe a merge commit was applied on top of a rebase or something?

**Comment by morsssss** [comment]
Yes! Sorry. Unfortunately, I just made a mess out of my branch's commit history.

I needed to re-trigger stalled tests. Normally I do so by pushing a null commit. Someone suggested that I rebase and push instead. This seemed like a nice idea!

Unfortunately I lacked the power to do a force push, and now all sorts of irrelevant changes are in this branch.

Can you help clean this up? Or it might be more efficient for me just to drop this and re-do the changes in a clean branch.

**Comment by morsssss** [comment]
Since I can't force push, I can't clean up this branch. Instead, at the very helpful suggestion of @rcebulko , I've cherry-picked the one actual relevant commit from this into https://github.com/ampproject/amphtml/pull/34940 . They're both changes to the same documentation file, so there's a nice logic here.

**Pull request closed without merging**
