### PR TITLE
Added a missing `&` to atinternet analytics config.

### PR DESCRIPTION
**Pull request by avimehta**

### CODE REVIEW

**Comment by avimehta** [comment]
@rudygalfi I'll merge this so that we get in the next cut(this is a very minor change so I think it is safe to do).

**Comment by rudygalfi** [comment]
LGTM

**Comment by rudygalfi** [comment]
@cramforce should do a quick review

**Comment by cramforce** [comment]
I'm puzzled this is green without a change to `vendor-requests.json`

BTW: We should expand `$extraUrlParams` in that test to make this more obvious.

**Comment by avimehta** [comment]
@cramforce there is a change in the vendor-requests.json.  expanding extraUrlParams sgtm #3837.

**Comment by cramforce** [comment]
Ugh. Missed it :)

LGTM

**Pull request merged**
