### PR TITLE
ACS: 18079 - Spelling inconsistencies

### PR DESCRIPTION
**Pull request by juanchaur1**
Change the UK spelling of "behaviour" to US spelling of "behavior"
Closes issue https://github.com/ampproject/amphtml/issues/18079

### CODE REVIEW

**Comment by alanorozco** [comment]
Hi,

Thanks for your contribution.

Would you mind reverting the style changes (i.e. newlines) from the switch statement?

**Comment by torch2424** [comment]
Hello @juanchaur1  😄 Did you make @alanorozco 's changes? If so feel free to mention the person requesting changes in a follow up comment so we know it is ready to go. No worries at all if not.

**Comment by nainar** [comment]
cc @alanorozco

**Comment by juanchaur1** [comment]
@torch2424 thanks.
@alanorozco I've done the changes you requested

**Comment by alanorozco** [comment]
@juanchaur1 

Thanks! Will merge once all checks have passed.

**Pull request merged**
