### PR TITLE
🐛  Chartbeat: Added extraUrlParams before request ending "&_" so that server interprets them

### PR DESCRIPTION
**Pull request by romainst**
In order to add extra parameters such as the "_acct" subscriber status (https://docs.chartbeat.com/cbp/tracking/standard-websites/subscriber-engagement) to the request using "extraUrlParams" in the json config they must be added before the "&_" at the end of the request, otherwise the server does not interpret them.
I tried to use $IF to add the "&" only when extraUrlParams is filled but it gets percent-encoded in the way. I tested successfully that when extraUrlParams is not configured or is empty the && does not create a problem server-side.

Testing configuration :
<script type="application/json">{"vars":{"uid":"123456789","domain":"example.com", [...] },"extraUrlParams":{"_acct":"lgdin"}}</script>

### CODE REVIEW

**Review by lannka — APPROVED** [review]

**Comment by lannka** [comment]
Please fix the unit test.

**Comment by micajuine-ho** [comment]
@romainst Did you check that this worked as intended? I've never seen `${extraUrlParams}` be used in a var substitution, so just double checking :)

**Comment by romainst** [comment]
@micajuine-ho Thanks for your review, I confirm that I tested successfully the code I pushed using AMP playground and the Modheader extension to override the vendor config.
I used https://amp.dev/documentation/components/amp-analytics/#extra-url-parameters as a reference and https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors/atinternet.json as a working example for the var substitution. 
It seems that if `extraUrlParams` are defined in the page but not the vendor module, they get added automatically at the end of each request preceded by `&`. However if `${extraUrlParams}` is detected in the vendor config, the parameters are added without a preceding `&` where the variable is and not at the end of the request.

**Comment by micajuine-ho** [comment]
Alright, sounds good. You'll have to fix the unit tests though in `extensions/amp-analytics/0.1/test/test-vendors.js`

**Comment by romainst** [comment]
@micajuine-ho Everything's fixed and tests all passed :) ready for final review

**Pull request merged**
