### PR TITLE
Story generator meta tag validation.

### PR DESCRIPTION
**Pull request by gmajoulet**
Context at https://github.com/ampproject/amphtml/issues/29991

Fixes https://github.com/ampproject/amphtml/issues/29991

### CODE REVIEW

**Comment by gmajoulet** [comment]
cc @ampproject/wg-caching

**Comment by honeybadgerdontcare** [comment]
please update the `.out` file

**Comment by honeybadgerdontcare** [comment]
@gmajoulet in addition to the updated `.out` file, is there any documentation that should go along with this in the `.md` file or is that tracked in a separate PR?

**Comment by newmuis** [comment]
+1 to documenting in amp-story.md

**Comment by gmajoulet** [comment]
PTAL

**Comment by gmajoulet** [comment]
This should be available on Tuesday Sept 1st.

**Pull request merged**
