### PR TITLE
add support for setCollapseEmptyDiv in doubleclick.js

### PR DESCRIPTION
**Pull request by tyler-g**
Following the documentation for setCollapseEmptyDiv on non-amp pages.  Can someone confirm this will work?

Note this would only support passing true or false,  and not the third option (true, true).

### CODE REVIEW

**Comment by kashyapnitin** [comment]
@michaelkleber 
Michale could you kindly take a look...
tyler could you clarify the use case / behaviour you want to implement. Given the layout is controlled by the AMP runtime.. i am not sure when the div collapsing will be respected or not. Also I think AMP layout already provides a way for collapsing an empty ad slot (or providing a fallback).. so what is the additional thing / user behaviour we are trying to enable here?

**Comment by michaelkleber** [comment]
Tyler: In doubleclick.js lines 166-170 we already have code to call the AMP-provided function global.context.noContentAvailable() when the returned ad is empty.  That's the right UX on an AMP page.

Was this PR inspired by a case where you saw a page not doing the right thing?  If so please file a bug report so that we can figure out whether there's a doubleclick problem (not firing the event even though the ad is empty) or an AMP problem (not collapsing correctly after noContentAvailable is invoked).

**Comment by cramforce** [comment]
Will close this, as this PR should do nothing (as it cannot collapse the container iframe. As Michael explains, this is already implemented (unless I'm missing something). Execution of the collapse operation is subject to AMP's sizing rules (read: it will not happen if the ad slot is in view).

**Comment by tyler-g** [comment]
@kashyapnitin @michaelkleber @cramforce  thanks for looking at this.

I came to this based on a use-case I needed where we actually *don't* want the ad slot to collapse if the ad is empty (which is the default behavior).  As far as I know you can do this with setCollapseEmptyDiv method on a normal doubleclick implementation.  I saw since your doubleclick.js file is loading the gpt.js library, that maybe these methods that are normally available would also be available here  (if exposed).

I do see the global.context.noContentAvailable()  (I didn't initially see it until I went specifically into the readme of the ads folder).  Could you show me an example of how this is used in the context of the <amp-ad> tag?

Much thanks for the help

**Comment by cramforce** [comment]
@tyler-g I see. You could just guard https://github.com/ampproject/amphtml/blob/master/ads/google/doubleclick.js#L111 which the option. An alternative is to wrap the `amp-ad` tag on your page in a container that is sized independently from the ad tag.

**Comment by michaelkleber** [comment]
I see -- is the space taken up by the ad important to your site's layout or something?

I think we can leave doubleclick.js out of this entirely.  I like Malte's suggestion to just put an appropriately-sized <div> around your <amp-ad>.  But if for some reason that does not work, then the option to not collapse should be implemented by changing what global.context.noContentAvailable() does.  That would make the behavior available across all ad networks; there is nothing doubleclick-specific here.

**Comment by tyler-g** [comment]
yes , precisely what is happening is that we have a fixed position masthead, and when the top ad collapses, our heading text is hidden partially by the masthead.

I do like your suggestions to avoid editing doubleclick.js .   I will try the container idea.  Also what about using the _fallback_ tag inside the <amp-ad>  We were thinking about trying to fallback to an identically sized static ad (just an image really), in case no ad is targeted.

**Comment by cramforce** [comment]
@tyler-g That also works. The fallback is shown if present instead of collapsing the slot.

**Comment by tyler-g** [comment]
@cramforce the fallback solution seems to be the way to go.  However since our fallback is an img (<amg-img> tag with width and height specified,  is there any way to have it have no height until it is "used"?  if that makes sense.

In other words, wondering if the behavior is possible where the ad slot is empty by default, and then if filled, it "expands".   But I guess this is against the amp convention of having fixed heights and widths on elements :)

**Comment by cramforce** [comment]
Paging @mkhatib for expert advise :)

**Comment by mkhatib** [comment]
> @cramforce the fallback solution seems to be the way to go. However since our fallback is an img ( tag with width and height specified, is there any way to have it have no height until it is "used"? if that makes sense.

@tyler-g by using no height, are you just trying to not show the fallback until you're sure there is no ad available?

If that's the case, the fallback actually is hidden by default and will only show if something wrong happen with the amp-element rendering. In this case, the fallback will only show when the `noContentAvailable` is triggered. 

AMP implementation of `noContentAvailable` is actually to show fallback if available, it **tries** to collapse the ad only when it can't find a `fallback` element, if one exists then it'll show the fallback element and will NOT collapse the ad. You can see the [behavior in code here](https://github.com/ampproject/amphtml/blob/d8e3068d7090b80cc47bb3b430aa34f53afb1307/builtins/amp-ad.js#L342).

> In other words, wondering if the behavior is possible where the ad slot is empty by default, and then if filled, it "expands". But I guess this is against the amp convention of having fixed heights and widths on elements :)

This is not possible. I think this will only work conditionally. Your `amp-ad` would have `height=0` and then it asks to be expanded, but AMP will ignore that ask if it's in view. So this is not recommended in general. I might be mis-understanding what you're asking here though.

**Comment by tyler-g** [comment]
Thanks @mkhatib this makes sense.   The fallback solution worked for us, and I understand how it is triggered now.

**Pull request closed without merging**
