### PR TITLE
New amp-ad type="aniview"

### PR DESCRIPTION
**Pull request by itaynave**
New amp-ad 
type="aniview"

### CODE REVIEW

**Comment by torch2424** [comment]
Hello,

Thanks for adding your vendor to AMP!

For the CLA, just follow the link provided by the googlebot. And, be sure you sign the CLA with the same email used in your git commits. You can see the email using `git log`, and you can change it by rebasing, or fixing your `git config`.

Once all of this is resolved, I can go ahead and do a review. Feel free to mention me once this is good to go. 

Thanks! 😄

**Comment by itaynave** [comment]
Signed the CLA

**Comment by torch2424** [comment]
@itaynave Thank you, going to mention the google bot to get the check to run again.

@googlebot

**Comment by torch2424** [comment]
Hmm, could you try merging in the latest master @itaynave ? Otherwise, there may be something else going on with the CLA

**Comment by itaynave** [comment]
Anything we can do with the CLA?

**Pull request closed without merging**
