### PR TITLE
amp-script: Add Vue.js TodoMVC example

### PR DESCRIPTION
**Pull request by niutech**
This is a working TodoMVC example made in Vue.js inside `<amp-script>`. You can see it live [here](https://unnaturalcompetentlinks--five-nine.repl.co/) and see its source code [here](https://repl.it/repls/UnnaturalCompetentLinks). You have to open Console, type `AMP.toggleExperiment('amp-script')` and reload the page in order to enable the experimental `<amp-script>` extension.

### CODE REVIEW

**Comment by torch2424** [comment]
Awesome work! Thanks for the contribution! 

Triaging to @kristoferbaxter 😄

**Comment by Antoinebr** [comment]
Hi @kristoferbaxter @torch2424 

This demo amp validation errors

image


Will these errors gonna disappear when ```amp-script``` will be available outside an experiment ?

**Comment by kristoferbaxter** [comment]
We will take a pass on clearing the validation errors for this example following amp conf.

**Comment by Antoinebr** [comment]
@kristoferbaxter Then does it mean the code is wrong or the validator is triggering errors when it shoudn't with amp-script ?

**Comment by niutech** [comment]
The validator should skip HTML inside the `<amp-script>` component, because it contains Vue.js directives (such as `v-model`, `v-for`).

**Comment by honeybadgerdontcare** [comment]
Validator should review all html code present but what @kbax is mentioning
is that amp-script is not valid generally, just for origin trials. Once
generally available you'll see a different response. This is brand new and
we want to work with you on the rollout.

**Comment by Antoinebr** [comment]
This demo doesn't work anymore see

https://amp-script.glitch.me/vue-todomvc


image

**Comment by niutech** [comment]
@Antoinebr Now you have to add `sandbox="allow-forms"` to `<amp-script>` component. Here is the updated [demo](https://BuoyantBarrenThing--five-nine.repl.co) and its [source](https://repl.it/repls/BuoyantBarrenThing).

**Comment by Antoinebr** [comment]
@niutech it works now 👍

image

is there any PR open to edit the demo in this repo ?

**Comment by niutech** [comment]
@Antoinebr Yes, I made a [pull request](https://github.com/ampproject/amphtml/pull/23911).

**Pull request merged**
