### PR TITLE
Change top100 config for amp-analytics

### PR DESCRIPTION
**Pull request by Anaza**
♻️ [amp-analytics] We want to add url param to our config and change ruid on tid

### CODE REVIEW

**Review by micajuine-ho — CHANGES_REQUESTED** [review]
Hi, you will also need to change the `test-vendors.json` file to reflect your changes. 

Please let me know if you need help doing so.

**Comment by Anaza** [comment]
Thank you. I changed test/vendor-requests.json. It's correctly?

**Comment by micajuine-ho** [comment]
Looks correct to me, reruning CircleCi since there looks to be an unrelated unit test failure

**Review by micajuine-ho — APPROVED** [review]

**Comment by micajuine-ho** [comment]
@Anaza have you signed the CLA?

**Comment by Anaza** [comment]
I got it. But I can't to link my name 'Anastasia Zaytseva' with my account 'Anaza'.

I have a warring "Anastasia Zaytseva seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.
You have signed the CLA already but the status is still pending? Let us recheck it."

**Comment by micajuine-ho** [comment]
Did you try here with "Anaza"? 
image

**Comment by Anaza** [comment]
I do it

**Pull request merged**
