### PR TITLE
comply with google style guide to have `.` as same line with property

### PR DESCRIPTION
**Pull request by erwinmombay**

### CODE REVIEW

**Comment by erwinmombay** [comment]
theres a couple of calls here to `getBoundingClientRect` that were previously not caught by the regex presubmits (because it didn't have the dot before it) which should be reviewed. marked them with /*REVIEW*/

**Comment by dvoytenko** [comment]
Thanks! LGTM

**Comment by erwinmombay** [comment]
thanks @dvoytenko . will change /*REVIEW*/ to /*OK*/

**Comment by cramforce** [comment]
The Google style guide was recently changed to allow this form but isn't opinionated about it.

Having said that, this is much better!!!!!!!!

**Comment by erwinmombay** [comment]
woot, thanks for the info @cramforce

**Pull request merged**
