### PR TITLE
✨[amp-ad smartadserver] Include consent data in iframe name

### PR DESCRIPTION
**Pull request by eszponder**

### CODE REVIEW

**Review by powerivq — APPROVED** [review]

**Comment by eszponder** [comment]
Hello @powerivq, thank you for the review and approve. I noticed that some test is failing and I'm not sure why, could you please take a look on it and give me some hint? All ut from our extensions are passing. Thanks in advance for your time.

**Comment by powerivq** [comment]
@eszponder I would suggest rebasing against the latest main branch.

**Comment by powerivq** [comment]
@eszponder I am wondering what we are doing here? The PR is now empty.

**Comment by eszponder** [comment]
Hello @powerivq I was doing rebase as you suggested and I had some conflicts so I removed my commits for a while. Now the PR is updated

**Pull request merged**
