### PR TITLE
Turn on amp-cid-backup experiment in prod

### PR DESCRIPTION
**Pull request by micajuine-ho**
Turn on feature flag in prod for `amp-cid-backup`.

Document changes next and then clean up experiment

For  (#30375) 

EDIT: Wait until after the holidays to merge

### CODE REVIEW

**Review by zhouyx — APPROVED** [review]
Approved provided major partners are aware of the behavior change.

**Comment by micajuine-ho** [comment]
Will wait until after the US Holiday week to confirm.

**Comment by oliverfernandez** [comment]
Hello!

Is this still on track to be merged? It would be very useful to be able to use this in production without manually setting the experiment on

**Comment by micajuine-ho** [comment]
Hi @oliverfernandez, we are still in the midst of talking to some vendors to make sure that they can handle this change on their servers. Should have an update on this later this week.

**Pull request merged**
