### PR TITLE
bump bento-compiler for latest fixes

### PR DESCRIPTION
**Pull request by samouri**
**summary**
Update: https://github.com/ampproject/bento-compiler/pull/31

Supports handling text nodes with no text.

### CODE REVIEW

**Review by rcebulko — COMMENTED** [review]
Make renovate do this for us
https://github.com/ampproject/amphtml/blob/main/.renovaterc.json#L20

**Comment by samouri** [comment]
Done https://github.com/ampproject/amphtml/pull/37001

**Review by rcebulko — APPROVED** [review]
Stellar. Can we enable automerge? We control when bento-compiler is updated on npm, right?

**Comment by samouri** [comment]
Closing in favor of https://github.com/ampproject/amphtml/pull/36998 🎉

**Comment by samouri** [comment]
> Stellar. Can we enable automerge? We control when bento-compiler is updated on npm, right?

We can't, since merging requires at least a single approval.
Unsure if GH allows for per-user branch-protection rule overrides

**Comment by rcebulko** [comment]
I thought we've enabled auto-merge with renovate PRs?

**Pull request closed without merging**
