### PR TITLE
Revert user-agent check in performance-impl

### PR DESCRIPTION
**Pull request by micajuine-ho**
Check [window.PerformancePaintTiming](https://developer.mozilla.org/en-US/docs/Web/API/PerformancePaintTiming) instead of user-agent to see if `first-contentful-paint` and` first-paint` are supported.

[Reverts the installation of platform service](https://github.com/ampproject/amphtml/pull/25259) in some places.

### CODE REVIEW

**Comment by micajuine-ho** [comment]
cc @powerivq for bundle size check

**Comment by powerivq** [comment]
Looking at the code, I don't feel it should increase the bundle size. Ideas?

**Comment by micajuine-ho** [comment]
> Looking at the code, I don't feel it should increase the bundle size. Ideas?

I agree, but not sure why this would happen

**Comment by kristoferbaxter** [comment]
@micajuine-ho Can you post a gist of the output of the before / after? I can take a look.

**Comment by micajuine-ho** [comment]
@kristoferbaxter Here is the [gist](https://gist.github.com/micajuine-ho/77109cec71aa2c178f1b914d6a8b5192)

**Comment by kristoferbaxter** [comment]
The change here is as follows:
1. Raw Output 206,473 -> 206,389
2. Brotli (-Z) 55,873 -> 55,838
2. Prettier 291,438 -> 291,333

I'm not certain why this is reported as an increase.

**Comment by powerivq** [comment]
@danielrozenberg to help debugging this.

**Pull request closed without merging**
