### PR TITLE
tools(presubmit): add globbing for whitelist

### PR DESCRIPTION
**Pull request by erwinmombay**

### CODE REVIEW

**Comment by dvoytenko** [comment]
Thanks @erwinmombay ! Globs are indeed a bit dangerous. Instead I was wondering if we could just automatically whitelist `test/` files for all restrictions. That way we can hold off on globs in the config and not worry about every test file.

**Comment by erwinmombay** [comment]
@dvoytenko gotcha, will fix

**Comment by erwinmombay** [comment]
@dvoytenko updated, please review. thanks

**Comment by cramforce** [comment]
LGTM

**Pull request merged**
