### PR TITLE
Widespace: Amp code version in request url as query param

### PR DESCRIPTION
**Pull request by mizmaar3**
Adding Amp code version in request url as query param

### CODE REVIEW

**Comment by zhouyx** [comment]
@mizmaar3 LGTM. However in our ads example page, the widespace examples are always not filled, would you please take a look at it as well?

**Comment by mizmaar3** [comment]
Sure @zhouyx
let me check

**Comment by mizmaar3** [comment]
@zhouyx Widespace only deliver ads on mobile and tablets (no desktop) So I think you tested it on desktop, you can test it on desktop by changing user agent of browser to any mobile/tablet.

I changed the example page anyway to show a random square ad on widespace ad space integration. Please try it.

**Comment by zhouyx** [comment]
LGTM

**Comment by zhouyx** [comment]
@mizmaar3 travis is failing with some unrelated presubmit check. I'll file a bug for that, but in the meantime, could you rebase to fix it?

**Comment by zhouyx** [comment]
@mizmaar3 Seems travis fails for a reason. Can you sync with master to fix it. 
https://github.com/ampproject/amphtml/issues/9012#issuecomment-297846977

**Comment by mizmaar3** [comment]
@zhouyx  Done

**Comment by zhouyx** [comment]
@mizmaar3 Thanks for the Pull Request. Merged.

**Pull request merged**
