### PR TITLE
:sparkles: Add multi-site support to 'sas' type amp ads

### PR DESCRIPTION
**Pull request by sthilt-sas**
Add multi-site support to 'sas' type amp ads

### CODE REVIEW

**Comment by sthilt-sas** [comment]
This pull request has been outstanding for nearly three months. I have fixed a merge conflict that arose between master this branch in the intervening time. Is there anything I can do to help facilitate review and merging?

**Comment by sthilt-sas** [comment]
This merge request has been open for five months. I'm not sure how to address the "owners-check" problem and the "percy" visual change occurred just today after I merged the master branch into my feature branch without any conflicts. Is there anything I can do to facilitate getting this pull request reviewed and hopefully merged? Thanks for any input.

**Comment by mrjoro** [comment]
Sorry this looks like it slipped through the cracks.

/cc @ampproject/wg-ads @lannka

**Comment by mshiltonj** [comment]
Yay! Thanks!

**Pull request merged**
