### PR TITLE
✨ Analytics: add customMediaEvent to Mapp Intelligence mediatracking

### PR DESCRIPTION
**Pull request by stiegi**
Mapp Intelligence is an Analytics vendor, that allows page-, event- and mediatracking.
This pull request will allow Mapp customers to define their own mediatracking eventname. This is useful for tracking the watchtime of advertisements in videos, for example.

### CODE REVIEW

**Comment by stiegi** [comment]
@zhouyx The CLA is signed by the company Mapp Digital, I am part of the group https://groups.google.com/g/mappdigitalAMP
Please let me know if I can do anything else to solve the CLA issue.
Thanks!

**Comment by stiegi** [comment]
@zhouyx Do you have an update concerning the CLA issue of this PR?
Thank you!

**Comment by zhouyx** [comment]
Re: CLA. AMP has migrated from the Google CLA to the OpenJS Foundation CLA. I believe we no longer receive the signed by the company. 
@rsimha @kristoferbaxter Is the recommendation to have the individual contributor sign the CLA? Thanks

**Comment by rsimha** [comment]
> Re: CLA. AMP has migrated from the Google CLA to the OpenJS Foundation CLA. I believe we no longer receive the signed by the company.

Correct, we no longer use the Google CLA.

> Is the recommendation to have the individual contributor sign the CLA? 

Yes, this is the current recommendation. (Signing the OpenJS CLA once will apply to all `ampproject` repos.)

**Comment by stiegi** [comment]
Thank you very much, I signed with my account.

@zhouyx Can you approve this PR? Unfortunately the percy/amphtml test fails, but I don't see a connection to my new code there. Thank you very much!

**Review by zhouyx — APPROVED** [review]

**Comment by zhouyx** [comment]
You're right the percy failure is unrelated. Approved and merged.

**Pull request merged**
