### PR TITLE
🏗  Fix Renovate property so @storybook/* version is < 6

### PR DESCRIPTION
**Pull request by alanorozco**
[This property was renamed at some point.](https://docs.renovatebot.com/configuration-options/#matchpackagepatterns) 

(Renovate has been spamming updates to 6+: #33347 etc.)

### CODE REVIEW

**Review by rsimha — APPROVED** [review]
This surprises me because the validity check for our renovate config has been passing, which I assume meant that the config is backwards compatible: 

image

That said, I agree with this change. LGTM.

**Comment by alanorozco** [comment]
Interestingly enough:

> ### [Renovate Ignore Notification](https://github.com/ampproject/amphtml/pull/33347#issuecomment-802138534)
>
> As this PR has been closed unmerged, Renovate will ignore this upgrade and you will not receive PRs for *any* future 6.x releases. However, if you upgrade to 6.x manually then Renovate will then reenable updates for minor and patch updates automatically.
>
> If this PR was closed by mistake or you changed your mind, you can simply rename this PR and you will soon get a fresh replacement PR opened.

@rsimha What do you think? Trust that and remove the config? We might add more `@storybook/` packages so maybe not, but I thought I'd bring it up.

**Comment by rsimha** [comment]
> @rsimha What do you think? Trust that and remove the config? We might add more `@storybook/` packages so maybe not, but I thought I'd bring it up.

Removing the entry will make our config file easier to maintain. But it might be worth leaving it in there to ensure we don't get spammed in future (until we're ready to upgrade to v6). Will leave this one to you.

**Comment by alanorozco** [comment]
@rsimha I think I'll leave it as-is. We should be upgrading to 6 ASAP anyway.

**Review by caroqliu — APPROVED** [review]

**Pull request merged**
