### PR TITLE
Remove unnecessary wait of viewer messaging ready promise in story info dialog.

### PR DESCRIPTION
**Pull request by lannka**
For #17679

### CODE REVIEW

**Comment by newmuis** [comment]
What happens if the user is not viewing the document in a viewer?

**Comment by lannka** [comment]
@newmuis that's a good question. The promise gets rejected if doc not in a viewer. I guess that's not what you want. Closing the PR.

**Comment by newmuis** [comment]
I think that's fine, as long as we can tell the difference.  Can you just add a handler for the rejection case to resolve the promise we're returning with an undefined payload?

**Comment by lannka** [comment]
@newmuis done. PTAL

**Pull request merged**
