### PR TITLE
Bento: Turn on media attributes for other carousel components

### PR DESCRIPTION
**Pull request by caroqliu**
Partial for #28284

Allows `amp-inline-gallery-pagination`, `amp-inline-gallery-thumbnails`, and `amp-stream-gallery` attributes to be responsive.

### CODE REVIEW

**Comment by krdwan** [comment]
Seems reasonable.  Not knowing too much about media queries as attributes, should all prop types (boolean, string, number) support the media type attribute?

**Review by krdwan — COMMENTED** [review]
Seems reasonable.  A few questions for my understanding are below (don't necessarily require changes) just wanted to understand:

1. For my understanding, what do media queries as attributes do?
2. Should all prop types (boolean, string, number) support the media type attribute?
3. Are tests needed for this?

**Comment by caroqliu** [comment]
> 1. For my understanding, what do media queries as attributes do?
This is specific to `amp-base-carousel`, `amp-inline-gallery`, and `amp-stream-gallery`, but we have made it configurable in `PreactBaseElement` in case there are additional use cases for it in other components. It's described more thoroughly here: https://amp.dev/documentation/components/amp-base-carousel/#media-queries but essentially it allows publishers to specify different attribute values based on media queries. 

> 2. Should all prop types (boolean, string, number) support the media type attribute?
Yes, there types are already enabled in `amp-base-carousel`: 

> 3. Are tests needed for this?
I don't believe so, given that #30870 introducing this configuration included tests that the attributes would yield the expected values for fully formed "media attribute"-like values, and this PR is only enabling use of that feature. These are manually usable though.

**Review by krdwan — APPROVED** [review]
Thanks for the explanation above.  Looks good to me!

**Pull request merged**
