### PR TITLE
✨ Update Teads ads CDN entry point and prefetch config

### PR DESCRIPTION
**Pull request by github-vincent-mathon**
Update of Teads ads CDN entry point and prefetch config to reflect infrastructure migration

### CODE REVIEW

**Review by calebcordry — APPROVED** [review]
Thanks for maintaining this extension!

**Comment by alanorozco** [comment]
@calebcordry @github-vincent-mathon 

This might have broken a unit test.

https://app.circleci.com/pipelines/github/ampproject/amphtml/22850/workflows/27e01357-051d-45b4-a77d-2d57da0cf6ed/jobs/455841

```
AssertionError: [teads] no need to preconnect if the URL is in prefetch: expected 'https://a.teads.tv/media/format/v3/teads-format.min.js' to not include 'https://a.teads.tv'
    at checkDuplicates (home/circleci/project/test/unit/test-ads-config.js:73:46)
    at Context.<anonymous> (home/circleci/project/test/unit/test-ads-config.js:33:9)
```
---
@rsimha @danielrozenberg

It looks like the CI run did not match this file change to the test target above, allowing it to merge while breaking.

**Comment by calebcordry** [comment]
Thanks for the heads up. Just opened a pr that should fix #37677

**Comment by rsimha** [comment]
> It looks like the CI run did not match this file change to the test target above, allowing it to merge while breaking.

Seems like the local unit tests job [didn't run](https://app.circleci.com/pipelines/github/ampproject/amphtml/22832/workflows/8d979242-6b96-4170-aa96-09c9cdd20dac/jobs/455294) any unit tests for this change.

image

Not sure why this is the case. Is there no test file that imports `ads/_config.js` or `ads/vendors/teads.js`? Or alternatively, could the new `#ads` import prefix be messing with the "which unit test to run" detection logic? 

And additionally, the test should have been run as part of the "all unit tests" job, which appears to have passed. Perhaps it wasn't caught by the regex for all unit tests?

**Pull request merged**
