### PR TITLE
♻️ Rename `hasOwn` to `hasOwnProperty`

### PR DESCRIPTION
**Pull request by danielrozenberg**
\+ set the `no-has-own-property-method` lint rule to produce an error

Related to #6548 and based on https://github.com/ampproject/amphtml/pull/16762#discussion_r202844633

### CODE REVIEW

**Comment by danielrozenberg** [comment]
Turns out we can't do this because "modules" have this property already. Any suggestions on another name for this method?

**Comment by danielrozenberg** [comment]
Ping @rsimha @erwinmombay @jridgewell do you think it's worth renaming this method to something else (given that it cannot be renamed to `hasOwnProperty`) or should I close this PR?

**Comment by jridgewell** [comment]
> Turns out we can't do this because "modules" have this property already. 

Huh?

**Comment by danielrozenberg** [comment]
`src/utils/object.js:63: ERROR - assignment to property hasOwnProperty of module$src$utils$object`
See more:
https://travis-ci.org/ampproject/amphtml/jobs/406014585#L1477-L1482

**Comment by jridgewell** [comment]
Seems like a bug in closure

**Comment by rsimha** [comment]
I think this is https://github.com/google/closure-compiler/issues/866. There appears to be a fix / workaround in the last comment. 

@danielrozenberg @erwinmombay

**Pull request closed without merging**
