### PR TITLE
✨amp-o2-player add handling consent data

### PR DESCRIPTION
**Pull request by lironka**
this is a copy of pr #30858, travis is stuck in that pr.
It is impact on business a lot.

@estherkim  HI! this is a copy.

### CODE REVIEW

**Comment by lironka** [comment]
@estherkim HI! this is a copy pr and the same issue. the pr based on the latest upstream/master

**Comment by estherkim** [comment]
Hi @lironka, this is interesting. Can you try logging into travis-ci.com? Once verified that Travis recognizes your account, push a new commit here to re-trigger the build.

If that doesn't work then I'll contact Travis support.

**Comment by estherkim** [comment]
To explain, I found this in the Requests section on Travis. So your PR is going through but Travis is blocking it for some reason.
image

**Comment by estherkim** [comment]
Same thing :/ I'll send an email. I understand that this is urgent? In order for this to make it into Beta next week, it has to be merged by EOD Friday. @micajuine-ho can help with that in case this isn't resolved by then. Thanks for your patience!

**Comment by lironka** [comment]
@estherkim Hi again. I authorised in Travis and suddenly gat a message `Your account has been flagged for potential abuse. Please contact support.`
maybe this leads to an issue.

**Comment by estherkim** [comment]
Seems like it. I reached out to their support team. You might want to file a ticket with them too.

**Comment by lironka** [comment]
@estherkim Yes. I did, I sent them a ticket.

**Comment by lironka** [comment]
@estherkim  @micajuine-ho hi! Finally pr had passed the Travis checks. Could you please approve it?

**Review by micajuine-ho — APPROVED** [review]
Woohoo!

**Comment by lironka** [comment]
@micajuine-ho hi again! thank you. But I can't merge: `The base branch restricts merging to authorized users.`  Could you do it?

**Comment by lironka** [comment]
@micajuine-ho thanks a lot!!!!!

**Comment by lironka** [comment]
@micajuine-ho do you know how long it takes to appear in https://cdn.ampproject.org/rtv/  ?

**Comment by micajuine-ho** [comment]
2 weeks, but since we are in a release freeze right now, it will take 3 weeks I believe.

**Pull request merged**
