### PR TITLE
Render form state template for amp-form even with unsupported type JSON array

### LINKED ISSUE #22570: amp-form erroneous usage of renderTemplateArray
ssrTemplateHelper was introduced to abstract the work for rendering templates. In amp-form, when the data set returned from a form submission is a JSON array then the template service will try to apply that array data set to the template for rendering. This will cause an error when trying to render the template as the returned type is the unexpected array of elements as opposed to one element.

1. Create a form with an action-xhr that will return return a JSON array. e.g. [null, null]. Also add a submit-success message.
2. Submit form and submit-success msg will not display, along with js console error.

See: https://stackoverflow.com/questions/56342836/amp-mustache-success-error-messages-not-displaying/56345478#56345478

Demo for testing purposes as provided by user: https://www.craigattachments.com/test-form.php

Solution: amp-form should assert that rendered is only 1 element or that the data passed to renderTemplate is always of type json object data {} and not []?

### PR DESCRIPTION
**Pull request by alabiaga**
Fixes #22570

### CODE REVIEW

**Comment by alabiaga** [comment]
@cvializ Hey Carlos, please see #22570 for the details. Let me know if it's not clear.

**Comment by cvializ** [comment]
Commented on the issue accidentally, but I'm not sure this is needed. This PR might  break existing forms https://github.com/ampproject/amphtml/issues/22570#issuecomment-500502086

**Comment by alabiaga** [comment]
Right. I think the right fix is for there to be a rendered template regardless of the response type returned, as currently returning a json array could lead to an error.  I will fix the PR.

**Comment by cvializ** [comment]
What would you think of checking if the result is an array and wrap its items in a single `div` and render that? And maybe warn?

**Comment by alabiaga** [comment]
@cvializ will look into. But yes not a bad idea and definitely a warning rather than an error. Thanks Carlos.

**Comment by alabiaga** [comment]
@cvializ Please take another look. Issued a warning for JSON array data type and passing in an empty JSON object for that case so that the form state msg template will render regardless.

**Pull request merged**
