### PR TITLE
add task for simple auto fix

### PR DESCRIPTION
**Pull request by erwinmombay**
can fix:
semi
eqeqeq
quotes

### CODE REVIEW

**Comment by erwinmombay** [comment]
can fix:
no-multi-spaces
array-bracket-spacing
computed-property-spacing
eol-last
indent
no-spaced-func
no-trailing-spaces
object-curly-spacing
space-after-keywords
space-before-blocks
space-before-function-paren
space-before-keywords
space-infix-ops
space-return-throw-case
space-unary-ops
arrow-spacing
generator-star-spacing

**Comment by erwinmombay** [comment]
will add more autofixes at a later PR

**Comment by erwinmombay** [comment]
@cramforce PTAL. would like to get this in so I can get the other lint autofix PR's through later.

**Comment by cramforce** [comment]
LGTM

**Pull request merged**
