### PR TITLE
✨ [RTC-Config]: add source_url and title to real-time-config global macros allowlist

### PR DESCRIPTION
**Pull request by zshnr**
Implements the changes proposed in #38627 by adding the TITLE and SOURCE_URL global macros to the allowlist for real-time-config

### CODE REVIEW

**Comment by zshnr** [comment]
Hi @calebcordry , could I have some assistance with getting this PR over the line? :)

**Comment by erwinmombay** [comment]
@zshnr apologies for the delay. could you rebase this issue. we'll try and get this over the line

**Review by powerivq — APPROVED** [review]

**Comment by zshnr** [comment]
@erwinmombay Thank you so much! I have rebased off of the main branch, fixed the one conflict, and pushed the changes :)

**Comment by zshnr** [comment]
@erwinmombay I might need help debugging the unit tests. Not sure how I can log the output of the function called in the failing test to see in either the browser console or command line. 

Is there anyone that can assist with this? Thanks!

**Comment by powerivq** [comment]
I would start with generalizing your regex and see at which point would the unit test passes.

**Comment by zshnr** [comment]
@powerivq I have updated the test's regex and it passes.

However, I had to generalize the part of the regex that checks that SOURCE_URL is a valid url with either http or https.

old regex had

`src=https?:\/\/[\w\.\/]+`

generalised this with:

`[^&]*`

Is this testing for the correct behavior of SOURCE_URL substitution or does this point to SOURCE_URL not substituting the correctly formatted url string?

**Comment by powerivq** [comment]
@zshnr I think escaping might have occur and failed your regex.

**Pull request merged**
