### PR TITLE
♻️ Remerge: Resources/Mutator service refactor

### PR DESCRIPTION
**Pull request by powerivq**
This PR would merge back the PR reverted for causing amp-auto-lightbox to fail. Since `.getResources()` call caused type check not be able to find out the type mismatch, I have again searched for all references to this method and found no other use of it.

### CODE REVIEW

**Comment by powerivq** [comment]
Once you are back and able. This PR is ready to be merged. @choumx @estherkim

**Comment by choumx** [comment]
Does this PR contain any changes other than a roll-forward of #26479?

> Since .getResources() call caused type check not be able to find out the type mismatch

Do we know why this was and did we fix the root cause?

**Comment by powerivq** [comment]
@choumx It does not contain anything else.

> Do we know why this was and did we fix the root cause?

The reason is that `element` does not have type declaration. We have changed them to use `Services.mutatorForDoc` which guarantees correct type inference.

**Comment by choumx** [comment]
> The reason is that element does not have type declaration.

So `this.element` in base-element.js has a type of `*`? We should fix this -- please file an issue and reference it in your cherry-pick post-mortem (#26483).

**Comment by powerivq** [comment]
@choumx make sense! created an issue.

**Pull request merged**
