### PR TITLE
Update items in viewport before scheduling layout in carousel

### LINKED ISSUE #2912: renderOutsideViewport => false breaks Carousel rendering
As far as I can tell this is recent behavior but maybe has been there for awhile.

Reproduce:
1. Run local server
2. Open carousel example
3. Navigate the carousel or the slider to jump to the YouTube element
4. Notice that it will never be scheduled for rendering and hence the iframe is never created (You'll only see the thumbnail placeholder).

Tested this with `amp-vine` which seems to have the same behavior when `renderOutsideViewport => false`, i.e. it won't render in the carousel.

Dropping the renderOutsideViewport seems to fix this though haven't done a lot of debugging to pinpoint what is the problem.

### PR DESCRIPTION
**Pull request by mkhatib**
Fixes #2912

### CODE REVIEW

**Comment by cramforce** [comment]
Nice fix! Could this be covered by a test?

**Comment by mkhatib** [comment]
Yes will add some test cases. We don't seem to have test cases currently that covers scheduling.

**Comment by mkhatib** [comment]
Added test cases for these! PTAL: @cramforce @sriramkrish85

**Comment by cramforce** [comment]
LGTM

**Pull request merged**
