### PR TITLE
✨ RushFlow extension

### PR DESCRIPTION
**Pull request by Serzhenka**
✨ New feature
- Implementing RushFlow extension that helps Publishers add more personal and custom content in to AMP pages.

### CODE REVIEW

**Comment by caroqliu** [comment]
Hi @Serzhenka thanks for making a contribution! Can you please point me to an I2I or design document/review where you discussed this component? It would help me to have more resources on the new feature before going through code review.

**Comment by Serzhenka** [comment]
> Hi @Serzhenka thanks for making a contribution! Can you please point me to an I2I or design document/review where you discussed this component? It would help me to have more resources on the new feature before going through code review.

@caroqliu Thanks for shedding some light here) You are right, here is I2I: https://github.com/ampproject/amphtml/issues/30091, please have a look on it, and if you will have any questions fill free to ask in AMP Slack for example, or where you more comfortable)

**Comment by caroqliu** [comment]
Closing [due to recommendation](https://github.com/ampproject/amphtml/issues/30091#issuecomment-698032620).

**Pull request closed without merging**
