### PR TITLE
✨Assist.js: Report available widgets to FrameService so that it can request widget ports to listen on.

### PR DESCRIPTION
**Pull request by ychsieh**
- Add protocol buffer library to generate FrameService protocol.
- Report widget by sending messages to FrameService's RespondingChannel.
- Add necessary endpoints to Closure custom API.

Assist.js AMP integration I2I issue: #30631

@samouri
@jridgewell
/cc @ianba

### CODE REVIEW

**Comment by samouri** [comment]
Is this still a WIP?

**Comment by ianba** [comment]
> Is this still a WIP?

We've been running an experiment for the assist.js project and based on the results have recently decided not to move forward with it. At this point we're starting to turn things down.

@ychsieh I think we can close this PR and remove the assist.js extension from the repo

**Comment by ychsieh** [comment]
Yes agree. Will do. 

@samouri @jridgewell @kristoferbaxter, even though unfortunately we didn't finish it, we are still very grateful for all the help and guidance during the assist.js extension development you guys provided! Thanks again!

**Comment by samouri** [comment]
@ianba / @ychsieh, it was our pleasure :)
Please tag me in the removal PR.

**Pull request closed without merging**
