### PR TITLE
📖 (wip) Add a visualization explaining the release schedule

### PR DESCRIPTION
**Pull request by danielrozenberg**
This PR adds a page that visually shows, on a calendar (non-date-specific), how the release schedule works. For each release channel (e.g., beta, stable, lts) this page answers these two questions:

* By hovering your mouse / tapping on any day in the top row, it answers the question "if I merged a code on this day, when will it be available on <channel>?"
* By hovering your mouse / tapping on any day in the bottom row, it answers the slightly more confusing question: "on this day, when was the code for <channel> merged?"

This page is deployed here for now: https://output.jsbin.com/qovahib/quiet

Things that could use some work:
* ~~I hate the colour scheme (rainbows are fun but not exactly accessible or coherent for this type of visualization 🌈) (help, @ampproject/wg-ui-and-a11y)~~ (fixed)
* ~~Are the instructions clear?~~ (nobody said no so far)
* ~~Should I add more detailed explanations above the calendar?~~ (added a link to the detailed doc)
* ~~Is the hover text clear? (help, @ampproject/wg-outreach)~~ (nobody said no so far)
* Where can we deploy this so that we can link to it from `CONTRIBUTING.md`?
* ~~Improve screen-reader accessibility~~ (@caroqliu approved)
* ~~Verify that the data is correct~~ (doubled checked with @rcebulko and @rsimha)

### CODE REVIEW

**Comment by morsssss** [comment]
I'm glad you're doing this! I think the concept is wonderful, and I agree that the design could use some work. I wish I knew how to make it perfect :)

My thoughts after a quick look:
* All the colors distract me. I might use a single color for backgrounds if they all sort of mean the same kind of thing - if you need more than one, different shades are good. If one of the days is quite different than the rest, I'd let it be different. All that comes to mind for me here is that the day you're hovering over should be distinct from the rest.
* Red and green tend to have quite distinct meanings for many people (stop and go etc) so I'd avoid those.
* I feel like the instructions should go on the top. I wonder whether you need any separation between the first week and the rest.

**Comment by sebastianbenz** [comment]
Why is this page not built with AMP?

We should integrate it here: https://amp.dev/documentation/guides-and-tutorials/learn/spec/release-schedule/

**Comment by jridgewell** [comment]
A few things:

1. Code merged on Monday of Week N is available for beta opt-in on Tuesday of Week N (not N+1).
2. Code merged on Friday of Week N is available for beta opt-in on Tuesday of Week N+1 (not N+2).

I also don't understand the bottom days.

**Comment by caroqliu** [comment]
This is awesome, thanks for working on this Daniel! 

re: color scheme—A heat map would be valuable here to convey the progression of how widely available your feature would be. I'd recommend a single tone sequence for this one so it's both accessible to color-blind folks and has some contextual meaning when the blocks are less visually organized in a meaningful way (Saturday versus Tuesday for example). Maybe something like this [set of blues](https://gka.github.io/palettes/#/9|s|3182bd,9ecae1,deebf7|ffffe0,ff005e,93003a|1|1)? 

Also worth noting that this calendar isn't accessible via screen reader based on the way the elements are structured (the SR will read them in the order they are in, including the eight boxes of vertical ellipses). To make it fully accessible we'd want to change the content to (1) be focusable and toggle on focus rather than hover and (2) provide a verbal summary of the visual information.

**Comment by danielrozenberg** [comment]
Thanks for all the support and feedback! I'm glad this is something folks are excited about 😊

Updated the PR and the [deployed demo](https://output.jsbin.com/qovahib)

---

@morsssss said:
> * All the colors distract me…

Changed to colours to match the [AMP style guide](https://amp.dev/static/files/brand-material/AMP_Mini_Styleguide.pdf). Better? I am not a designer 😅

> * I feel like the instructions should go on the top. I wonder whether you need any separation between the first week and the rest.

Changed the text of the instructions, is this better? Should I replace the instructions or add extra instructions above the calendar?

---

@sebastianbenz said:
> Why is this page not built with AMP?

It is an AMP page! It's using `<amp-script>` because doing it with `<amp-bind>` proved to be a bit too complicated. The reason it doesn't pass validation is because of #26369 and because jsbin adds its own script to output pages. Without those extra scripts the page is valid (modulo #26369)

> We should integrate it here: https://amp.dev/documentation/guides-and-tutorials/learn/spec/release-schedule/

I believe this page is build from `.md` files, so we can't directly put it there. We can certainly link from it and put a static screenshot as a teaser!

---

@jridgewell said:
> 1. Code merged on Monday of Week N is available for beta opt-in on Tuesday of Week N (not N+1).
> 2. Code merged on Friday of Week N is available for beta opt-in on Tuesday of Week N+1 (not N+2).

This is for after we change our release process to include and rely on `nightly` builds. I'm not 100% confident that the data is correct, so I would be happy to go over with you offline on our plans to make this work

> I also don't understand the bottom days.

New text helps?

---

@caroqliu said:
> re: color scheme … Maybe something like this [set of blues](https://gka.github.io/palettes/#/9%7Cs%7C3182bd,9ecae1,deebf7%7Cffffe0,ff005e,93003a%7C1%7C1)?

This is a great tool! I used it to match the [AMP style guide](https://amp.dev/static/files/brand-material/AMP_Mini_Styleguide.pdf) but if you think this doesn't work I can try your colour scheme

> Also worth noting that this calendar isn't accessible via screen reader based on the way the elements are structured (the SR will read them in the order they are in, including the eight boxes of vertical ellipses)

Oh no, I didn't think about this at all 😞
Think you can help me with this offline?

**Comment by jridgewell** [comment]
> The reason it doesn't pass validation is because of #26369 and because jsbin adds its own script to output pages

Append `/quiet` to the URL. 😉 

https://output.jsbin.com/qovahib/quiet

**Comment by sebastianbenz** [comment]
@danielrozenberg Ups! Sorry! amp-script fooled me there 🤦.

Few more comments:

* Please use different colors. The currently used color are associated with the different AMP formats. Ideally, you'd be using [colors already used on amp.dev](https://github.com/ampproject/amp.dev/blob/future/frontend/scss/_variables.scss#L41).
* Can you please make if work on mobile as well. 
* Suggestion: show tap or hover depending on whether the device supports taps.

**Comment by danielrozenberg** [comment]
@jridgewell said:
> Append `/quiet` to the URL. 

Sweet! Updated the link in the PR description.

---

@sebastianbenz said:
> * Please use different colors. The currently used color are associated with the different AMP formats. Ideally, you'd be using [colors already used on amp.dev](https://github.com/ampproject/amp.dev/blob/future/frontend/scss/_variables.scss#L41).

See [new version](https://output.jsbin.com/qovahib/quiet) for updated colour scheme. From the list of colours you linked me to I used:
* `blue-ribbon` for header text
* `silver` for day borders
* A gradient between `pink-flamingo` and `lavender-magenta` for the hovered/tapped day
* A gradient between `robins-egg` and `mountain-meadow` for the instructions row
* A series of gradients between `doger-blue` and `mariner` for the release channels

If you have specific preferences for any of those lmk and I can change it. If you need to see those colours I converted that list of hex codes into a [handy visualization](https://output.jsbin.com/betefum/quiet)

> * Can you please make if work on mobile as well.

It works on mobile (tap instead of mouse hover)

> * Suggestion: show tap or hover depending on whether the device supports taps.

Done!

**Comment by cathyxz** [comment]
I came here to say this is awesome. xD

**Comment by sebastianbenz** [comment]
Awesome! I like the colors! I've noticed two small things on mobile:

1. The nightly is hard to read

Screen Shot 2020-01-17 at 20 19 44

2. Text overflow

Screen Shot 2020-01-17 at 20 19 34

**Comment by danielrozenberg** [comment]
@cathyxz said:
> I came here to say this is awesome. xD

Thanks! 😊

---

@sebastianbenz said:


> Awesome! I like the colors! I've noticed two small things on mobile:

Tried to fix those by making fonts a tiny bit smaller and rotating the release channel names in extra small screens. Tested it on:
* Desktop Chrome 79
* Desktop Firefox 72
* Desktop Chrome 79 simulating Pixel 2 XL, iPad, iPhone X
* Mobile Chrome 79 on Pixel 3 XL
* Mobile Firefox 72 on Pixel 3 XL

All of them look fine to me, but please test it with other real devices!

**Comment by choumx** [comment]
This is cute.

**Comment by morsssss** [comment]
Lookin' good! A few suggestions:

* *"Hover on days above to see when the code merged on that day will be available on each release channel"*: that's clear to me! I think it would be even clearer if I saw a little list of the release channels, since most people out there won't know what those are. That would also help me know why certain text is in the code typeface... though "beta" is in this typeface inconsistently

* *"Hover on days below to see when the latest code merge occurred so as to be included in each release channel"*: so you're trying to say, "if code was released on this date, when did it arrive in each release channel"?

* The row headers under "Week" are very small. Can those be embiggened?

* Seems to me that the blue boxes get a bit darker as we get closer to production. But I only perceive two different shades of blue, though there are five steps. Would you want to make each step a different shade? If so, I might suggest that you get brighter as you lurch toward production, not darker.

**Comment by rcebulko** [comment]
> Lookin' good! A few suggestions:
> 
> * _"Hover on days above to see when the code merged on that day will be available on each release channel"_: that's clear to me! I think it would be even clearer if I saw a little list of the release channels, since most people out there won't know what those are. That would also help me know why certain text is in the code typeface... though "beta" is in this typeface inconsistently

+1 to this, also could allow for adding per-channel icons to make mobile view easier to read :thinking: 

> * The row headers under "Week" are very small. Can those be embiggened?

I'm glad I'm not the only one who uses the word "embiggen"

> * Seems to me that the blue boxes get a bit darker as we get closer to production. But I only perceive two different shades of blue, though there are five steps. Would you want to make each step a different shade? If so, I might suggest that you get brighter as you lurch toward production, not darker.

I also only see two different shades, wasn't sure if my color sk1llz were just too amateur

**Comment by danielrozenberg** [comment]
@morsssss said:
> I think it would be even clearer if I saw a little list of the release channels

I assume that anyone who sees this document would reach it from release-schedule.md or from the upcoming blog post, but nonetheless I added a link to the former.

> so you're trying to say, "if code was released on this date, when did it arrive in each release channel"?

More like "I want to know when the code was merged to have arrived in each release channel" - so for example if you hover on Tuesday, it tells you that the `nightly` channel on that Tuesday has code that came from the day before; the `opt-in` channel on that Tuesday has code that came from Thursday the week before; the `beta` channel has code that came from Thurday two weeks before, and so on

> * The row headers under "Week" are very small. Can those be embiggened?

Done, PTAL

> * Seems to me that the blue boxes get a bit darker as we get closer to production. But I only perceive two different shades of blue, though there are five steps. Would you want to make each step a different shade? If so, I might suggest that you get brighter as you lurch toward production, not darker.

Reversed the colours, PTAL

---

I also added some CSS transition animations to make it more clear what happens when you switch from hovering on the first row to hovering on the last row

**Comment by rcebulko** [comment]
Does the teal explanation bar have some kinda gradient on it?

**Comment by danielrozenberg** [comment]
@rcebulko said:
> Does the teal explanation bar have some kinda gradient on it?

All backgrounds are gradients :)


@caroqliu
> Also worth noting that this calendar isn't accessible via screen reader

I added an alternate version that should be screen-reader accessible! It's hella-ugly now and I'm not sure it really is accessible (dunno how to test it) so please help!
https://output.jsbin.com/lofuxam/quiet

**Comment by danielrozenberg** [comment]
Closing this PR as I have moved it to the https://github.com/ampproject/amp.dev repo: https://github.com/ampproject/amp.dev/pull/3423

**Pull request closed without merging**
