### PR TITLE
✨Denakop AMP Extension

### PR DESCRIPTION
**Pull request by gurodrigues**
New extension that contains features that aim to facilitate content producers day-to-day. It enables the activation and deactivation of advertising formats automatically and instantaneously.

### CODE REVIEW

**Comment by lannka** [comment]
@gurodrigues introducing a new extension in AMP will need an "Intent 2 Implement" and likely a design review. could you please follow [this guide](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#process-for-significant-changes) ?

**Comment by gurodrigues** [comment]
\

**Comment by gurodrigues** [comment]
@lannka I just created the new issue as requested #22916

**Comment by lannka** [comment]
close this in favor of #24404

**Pull request closed without merging**
