### PR TITLE
history-impl: fix local dev server handling of history

### PR DESCRIPTION
**Pull request by samouri**
**summary**
https://github.com/ampproject/amphtml/pull/35823 introduced a bug in history for local dev servers - opting them to always create a virtual history. This PR removes the check for `.test` since `__AMP_TEST_IFRAME` allows us to differentiate between unit tests and dev server.

### CODE REVIEW

**Review by jridgewell — APPROVED** [review]

**Comment by samouri** [comment]
Seeing CI failures. Investigating now

**Comment by samouri** [comment]
I've isolated the issue to being a conflict between `extensions/amp-ad/0.1/test/test-amp-ad-xorigin-iframe-handler.js` and `test/unit/core/window/test-history.js`

**Review by processprocess — APPROVED** [review]

**Comment by processprocess** [comment]
Looking into this more and it looks like it's also effecting the outlink buttons.

When opening an outlink on [this page](https://discovery-ec239.web.app/examples/amp-story/attachment.html#page=outlink-custom-icon-custom-text) of the demo an error is thrown:
Screen Shot 2021-09-01 at 1 50 48 PM
Looks like it's being thrown from [here](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story/1.0/amp-story-page-attachment.js#L344-L346) in the code.

**Comment by processprocess** [comment]
It's also effecting a header with `position: sticky`, it's no longer sticking to the top of the viewport.
Clicking the CTA on [this page](http://localhost:8000/examples/amp-story/attachment.html#page=inline-two-images-dark-theme) of the demo will open a draggable drawer. when scrolling, the header should stick to the top of the viewport.

**Comment by samouri** [comment]
> > @processprocess: are the issues you noticed related to `history-impl` or generically to change in getMode().test value?
> 
> I think it's due generically to the `getMode().test value`.

Do you know why there was an expectation for test/localDev/prod to all be different? Do you know if this would be easy to fix, or is it worth reverting #35823

**Comment by gmajoulet** [comment]
+1 to reverting as we keep uncovering bugs and don't yet understand the full scope of what's broken, or why it's broken

**Pull request closed without merging**
