### PR TITLE
✅ Skip flaky Bind tests

### PR DESCRIPTION
**Pull request by rsimha**
These tests are failing repeatedly on Travis. See https://travis-ci.org/ampproject/amphtml/jobs/365658076#L721-L733

### CODE REVIEW

**Comment by jpettitt** [comment]
The skip part LGTM, my only concern is not knowing why they are failing, I'll leave figuring that out to to @choumx

**Comment by rsimha** [comment]
The same two tests are failing on `master` too (https://travis-ci.org/ampproject/amphtml/jobs/365597632#L666-L678), so let's skip this for now and investigate offline.

**Comment by rsimha** [comment]
Force merging this to unblock the Travis queue.

**Pull request merged**
