### PR TITLE
Detect if a link[rel=stylesheet] has been SSR'd/installed for an extension

### PR DESCRIPTION
**Pull request by erwinmombay**
Some amp optimizers will in the future add a link[rel=stylesheet] for an
extension to improve their performance. We need to be able to detect and
not overwrite the installed styles by the external stylesheet.

### CODE REVIEW

**Review by jridgewell — CHANGES_REQUESTED** [review]
I believe we're going to have some issues with the `styleLoaded` function in this file. At the moment, I don't believe it'll ever resolve?

**Comment by erwinmombay** [comment]
@jridgewell is it because you're saying the css url is incorrect right? so i double checked it and earlier didn't even have an actual css anywhere and it still resolved properly. let me double check everything though

Screen Shot 2021-11-09 at 4 40 21 PM
y.

**Review by jridgewell — APPROVED** [review]
Ha, apparently `stylesheet.ownerNode === link` is perfectly fine.

**Comment by erwinmombay** [comment]
@jridgewell thanks. i'll add a comment on that line that `style` there an refer to both a `style` element and `link` element

**Comment by erwinmombay** [comment]
@jridgewell would you mind approving again when you get a chance was having problems with bundle-size

**Pull request merged**
