### PR TITLE
Allow `amp-autocomplete` in email format by default

### LINKED ISSUE #24881: AMP4Email: Support autocomplete
I am trying to create a search widget in AMP email, below is the code.
but i am getting in promise error in the console when clicking on the submit button. 

@and is there any way to use autosuggest for from and to the field.

```html
<form method="post" action-xhr="https://m.cheapoair.com/remotesearchhandler.aspx"   id="widget-form"  id="widget-form" >
<!-- <span [text]="'formDataVar.originCityCode = ' + formDataVar.originCityCode + 'formDataVar.originCity = ' + formDataVar.originCity  + 'formDataVar.originquery = ' + formDataVar.originquery "></span> -->
	<input type="search" name="from" id="from" class="search-box" required="" pattern="[A-Za-z\s]+">
	<input type="search" name="to" id="to" class="search-box" required="" pattern="[A-Za-z\s]+">
	<input type="submit" value="Search" id="search"> </div>
</form>
```
@nainar @cvializ

### PR DESCRIPTION
**Pull request by caroqliu**
This PR removes the doc-level opt-in flag introduced in #27174, making `amp-autocomplete` fully valid and fully available in the AMP format by default. Closes #24881. This change is being implemented now as prompted by approval in a recent wg-amp4email meeting.

/cc @ampproject/wg-amp4email @nainar

### CODE REVIEW

**Comment by zhangsu** [comment]
I reviewed the recent changes to the working group meeting notes but found no mention of this. Was this only only approved verbally but not taken down in the notes?

I was under the impression that mail.ru and Yahoo! Mail still haven't implemented this feature yet, so this feature would only work in Gmail and the current warning would still make sense.

**Comment by caroqliu** [comment]
> I reviewed the recent changes to the working group meeting notes but found no mention of this. Was this only only approved verbally but not taken down in the notes?
> 
> I was under the impression that mail.ru and Yahoo! Mail still haven't implemented this feature yet, so this feature would only work in Gmail and the current warning would still make sense.

I wasn't in attendance, but let's not do this if we don't have 100% confidence and documented consensus. @nainar will be the point person on bringing this up for the next agenda.

**Comment by caroqliu** [comment]
> > I reviewed the recent changes to the working group meeting notes but found no mention of this. Was this only only approved verbally but not taken down in the notes?
> > I was under the impression that mail.ru and Yahoo! Mail still haven't implemented this feature yet, so this feature would only work in Gmail and the current warning would still make sense.
> 
> I wasn't in attendance, but let's not do this if we don't have 100% confidence and documented consensus. @nainar will be the point person on bringing this up for the next agenda.

This appears to be approved in the July meeting for @ampproject/wg-amp4email, PTAL.

**Review by zhangsu — APPROVED** [review]

**Comment by caroqliu** [comment]
ping @ampproject/wg-caching for review please 🙏

**Review by honeybadgerdontcare — APPROVED** [review]

**Review by samouri — APPROVED** [review]

**Pull request merged**
