### PR TITLE
Drive by PR: Allow new enterkeyhint attribute on input

### PR DESCRIPTION
**Pull request by cramforce**
This should not have security implications.

https://html.spec.whatwg.org/multipage/interaction.html#input-modalities:-the-enterkeyhint-attribute

### CODE REVIEW

**Comment by Gregable** [comment]
@ampproject/wg-amp4email 

Do html mail clients need to do anything here to make sure that these tags don't get sanitized if this attribute is present?

**Comment by fstanis** [comment]
IIRC only the attribute itself would get removed when not whitelisted. Probably a good idea to ban it from email spec until there's consensus on what to do with it.

**Comment by honeybadgerdontcare** [comment]
> IIRC only the attribute itself would get removed when not whitelisted. Probably a good idea to ban it from email spec until there's consensus on what to do with it.

In that case:

`attrs: { name: "enterkeyhint" }`

becomes

```
attrs: {
  disabled_by: "amp4email"
  name: "enterkeyhint"
}
```

**Comment by cramforce** [comment]
Done

**Pull request merged**
