### PR TITLE
Apparently sometimes we do not have an error. Why am I surprised.

### PR DESCRIPTION
**Pull request by cramforce**

### CODE REVIEW

**Comment by dvoytenko** [comment]
LGTM

**Comment by erwinmombay** [comment]
@cramforce do we need to do any clean up after this? (on those using it w/o an actual error?)

**Comment by cramforce** [comment]
We should try to track these down, yeah.

**Comment by jridgewell** [comment]
http://eslint.org/docs/rules/no-throw-literal

**Comment by cramforce** [comment]
@jridgewell Good call, but that is likely not what is going on here.

**Pull request merged**
