### PR TITLE
Revert "Proxying the form to call the prototype methods/properties"

### PR DESCRIPTION
**Pull request by muxin**
Reverts ampproject/amphtml#6720

Saucelabs unit tests running on chrome 45 is failing. Rollback for now.

```
Chrome 45.0.2454 (Linux 0.0.0) installFormProxy   w/o masking inputs should proxy properties FAILED
	AssertionError: expected undefined to equal 'https://example.org/submit'
	    at Context.<anonymous> (/tmp/b5cc8dc2f173411538943ec34a40f77c.browserify:49762:33 <- /home/travis/build/ampproject/amphtml/extensions/amp-form/0.1/test/test-form-proxy.js:42:32)
..
Chrome 45.0.2454 (Linux 0.0.0) installFormProxy   with masking inputs should proxy properties FAILED
	AssertionError: expected undefined to equal 'https://example.org/submit'
	    at Context.<anonymous> (/tmp/b5cc8dc2f173411538943ec34a40f77c.browserify:49811:33 <- /home/travis/build/ampproject/amphtml/extensions/amp-form/0.1/test/test-form-proxy.js:88:32)
```

### CODE REVIEW

**Comment by jridgewell** [comment]
These properties must not be magic getters in old Chrome.

**Comment by dvoytenko** [comment]
LGTM. 

@jridgewell can you please clarify?

> These properties must not be magic getters in old Chrome.

**Comment by jridgewell** [comment]
`#id` is defined as a magic getter/setter:

```js
Object.defineProperty(HTMLFormElement.prototype, 'id', {
  get() { ... },
  set(val) { ... },
});
```

Our form proxy code finds all these getters/setters and creates proxies for them. But it can't do the same for traditional properties, which must be happening in old Chrome.

**Comment by dvoytenko** [comment]
Hmm. `id` actually works fine. For some reason, I only see that `action` is absent...

**Pull request merged**
