### PR TITLE
Update OWNERS for carousel components

### PR DESCRIPTION
**Pull request by sparhami**

### CODE REVIEW

**Comment by rcebulko** [comment]
These files were recently updated to add ampproject/wg-ui-and-a11y as owners in #24714 , so this change may no longer be necessary

**Comment by kristoferbaxter** [comment]
Agree with @rcebulko. Should we close this request and reopen if the updated values don't match expectations?

**Comment by rcebulko** [comment]
> Agree with @rcebulko. Should we close this request and reopen if the updated values don't match expectations?

Since the wg-ui-and-a11y group is a superset of the owners listed here, unless there's some reason these particular directories should *not* be owned by the rest of the working groups, that seems reasonable here.

**Comment by kristoferbaxter** [comment]
Closing based on updated OWNERS from separate PR. Let's revisit if needed.

**Pull request closed without merging**
