### PR TITLE
When scaling down embeds, align them to the top of the available space.

### PR DESCRIPTION
**Pull request by cramforce**
There might be an issue for this, but I cannot find it.

Partial for #29194

### CODE REVIEW

**Comment by gmajoulet** [comment]
For future reference, all known Story bugs are tracked in this dashboard: https://github.com/ampproject/amphtml/projects/106

Here's the ticket you were looking for: https://github.com/ampproject/amphtml/issues/29194

**Comment by cramforce** [comment]
@Enriqe Do you want to fix this for real instead?

**Comment by Enriqe** [comment]
Sure, I'll take a look.

**Comment by gmajoulet** [comment]
Given the usage of the feature, I'd suggest we go with this fix for now and keep the ticket open to fix for real later. All the improvements Enrique is working on for the Web Player are very impactful and much needed 🙏

**Pull request closed without merging**
