### PR TITLE
Skip test on old chrome

### PR DESCRIPTION
**Pull request by zhouyx**
quick fix for #8965

### CODE REVIEW

**Comment by jridgewell** [comment]
I've got a few better fixes coming.

**Comment by jridgewell** [comment]
https://github.com/ampproject/amphtml/pull/8969

**Comment by zhouyx** [comment]
That's good! In that case I'll just leave the `skipOldChrome()` function then. (wanted to have that for long)

**Comment by lannka** [comment]
Seems the #8969 does not solve the issue on travis. We might still need this PR in to unblock release. @jridgewell

**Pull request merged**
