### PR TITLE
✅ amp-next-page: Fix and re-enable flaky tests

### LINKED ISSUE #15234: debug and unskip tests on amp-next-page
Per https://github.com/ampproject/amphtml/pull/15232.

### PR DESCRIPTION
**Pull request by peterjosling**
I *think* this completely de-flakes it (but I can't really check well on Travis).

Fixes #15234

### CODE REVIEW

**Comment by peterjosling** [comment]
@aghassemi

**Comment by aghassemi** [comment]
@peterjosling Thanks for quickly fixing this. let's do 3 reruns on the PR and if all green, I will merged. I just kick off a new run. Could you please 2 more and ping me after?

**Comment by peterjosling** [comment]
Nope, still flaking. Will take another look.

**Comment by peterjosling** [comment]
Ran the analytics test 1000 times on Travis and it passed :tada:

Will clean up and rebase after #15339 is in.

**Comment by peterjosling** [comment]
Good to merge 😄

**Pull request merged**
