### PR TITLE
✨ Add new analytics variables for Navegg vendor

### PR DESCRIPTION
**Pull request by hugocs1**
- Adds new analytics variables for Navegg vendor, using URL variable substitutions.
- Minor URL fix

### CODE REVIEW

**Review by erwinmombay — APPROVED** [review]

**Comment by erwinmombay** [comment]
LGTM

**Comment by erwinmombay** [comment]
@hugocs1 could you get the failing tests to pass. will merge when green:

```
TOTAL: 1 FAILED, 2209 SUCCESS


1) test requests
     amp-analytics   vendor request tests analytics vendor: navegg
     Error: Vendor navegg, request pageview doesn't match. Expected value https://amp.navdmp.com/amp?aid=_client_id(navegg_id)_&url=_canonical_url_&ref=_document_referrer_&tit=_title_&lan=_browser_language_&acc=!account&wst=_wst_&wct=_wct_&wla=_wla_&v=7, last sent out value is https://amp.navdmp.com/amp?aid=_client_id(navegg_id)_&url=_canonical_url_&ref=_document_referrer_&tit=_title_&lan=_browser_language_&acc=!account&wst=!wst&wct=!wct&wla=!wla&v=7.
```

**Comment by hugocs1** [comment]
@erwinmombay done!

**Comment by powerivq** [comment]
@hugocs1 Suggest rebasing against the latest main branch to have the CI build fixed.

**Comment by hugocs1** [comment]
@powerivq you mean [this](https://github.com/hugocs1/amphtml/commit/beea88d125d2e40e8f137cf32ffdf16f74811827) one? I tried but it says "_This branch is not behind the upstream_".

Maybe re-run the CI?

Thanks in advance!

**Comment by powerivq** [comment]
@hugocs1 Sorry, please rebase now! It should have the fix.

**Review by powerivq — APPROVED** [review]

**Pull request merged**
