### PR TITLE
brainy amp-ad:change contact URL

### PR DESCRIPTION
**Pull request by brainyinc**
We changed our contact information because of company split from "OPT, Inc". Could you please check it? We already started offering a service of amp-ad so it would be great if we don't have to re-make our amp-ad codes. We have changed user information of github but haven't signed CLA as our new company "brainy, Inc". So there are two questions, "Can we still keep our rights to make any change on our amp-ad codes that we contributed as "OPT, Inc" before?", and "Is there any problem to use/edit our amp-ad codes without signing new CLA? If so, please tell us what to do next."  Thank you in advance.

Our PR in the past 
#7224
#6435

### CODE REVIEW

**Comment by brainyinc** [comment]
Could someone please tell us what to do about Succession to our CLA upon company split?

**Comment by jridgewell** [comment]
You'll likely have to resign the CLA with the new email addresses.

**Comment by brainyinc** [comment]
So what we should do is to resign the CLA as a new company "brainy", and wrote here " I signed it!", right?
Can we keep using our information on GitHub as before?

**Comment by jridgewell** [comment]
Exactly. And all your Github stuff should remain the same.

**Comment by zhouyx** [comment]
@brainyinc Any update on the CLA?

**Comment by jridgewell** [comment]
@erwinmombay: Please force merge.

**Comment by zhouyx** [comment]
@jridgewell I checked our CLA list, not able to find the new company name. Please do NOT force merge

**Comment by zhouyx** [comment]
@brainyinc have you signed the CLA? I'll close the PR for now. Feel free to reopen it later.

**Pull request closed without merging**
