### PR TITLE
Restore OriginExperiments

### LINKED ISSUE #16183: Undelete OriginExperiments
Per issue #15827 we want to re-add support for "origin trial" experiments.  Support for these had been added in the past but this was removed in #15220 due to lack of use.

Origin experiments have several advantages that are not fully present in any of our other options today:
- We will be able to keep track of who is using these experiments so we can notify them of breaking changes.  By definition experimental features are ones we may need to make breaking changes to, so it is important for us to have a way of notifying these users when there is a problem.  (This is notably absent from document-level experiments.)
- Support for the experiment is enabled by adding a token to the publisher page, so adding a new origin to the experiment does not require a binary push.  (This is currently required in the one-off origin trial support used by amp-story.)

/cc @aghassemi @lannka

### PR DESCRIPTION
**Pull request by choumx**
Fixes #16183.

Follow-ups:
- [x] ~Convert `OriginExperiments` to a doc service.~
- [x] ~Stop using `parseUrlDeprecated`.~
- [ ] Write usage instructions for generating keys etc.

### CODE REVIEW

**Comment by mrjoro** [comment]
Woo!  Is this just a restoration of the code that was there before?

**Comment by choumx** [comment]
@mrjoro There are some minor changes to reflect new code landscape (commits past the first).

**Comment by choumx** [comment]
Looks like this causes a dependency cycle in the `--single_pass` build:

```
AssertionError [ERR_ASSERTION]: Node src/services.js forms circular dependency: extensions/amp-list/0.1/amp-list.js -> src/batched-json.js -> src/services.js -> src/element-service.js -> src/service.js -> src/polyfills.js -> src/experiments.js -> src/services.js
```

**Pull request merged**
