### PR TITLE
roll forward #7750 to fix installCustomElement invocation/declaration

### PR DESCRIPTION
**Pull request by erwinmombay**
cc @WebReflection 

we were also replacing the function declaration, we only need the replace done on the call site

### CODE REVIEW

**Comment by WebReflection** [comment]
I'm not sure whats going on here but FWIW

> Please double check before merge

my previous PR was green, if master went red after is because Travis "lied" to us.

If I can help somehow, let me know.

**Comment by jridgewell** [comment]
Ping.

**Comment by WebReflection** [comment]
hey chaps, stuck beyond tooling ? congrats I guess 😛

**Comment by erwinmombay** [comment]
haha apologies amp conf sorta took all our time. putting this into current sprint!

**Comment by erwinmombay** [comment]
closing in favor of https://github.com/ampproject/amphtml/pull/9840

**Pull request closed without merging**
