### PR TITLE
fix(history): add import to getService to fix errors.

### PR DESCRIPTION
**Pull request by erwinmombay**

### CODE REVIEW

**Comment by cramforce** [comment]
LGTM

**Comment by ampsauce** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 3740cf0d126822f3832b3314623f61736430cf41
Build details: https://travis-ci.org/ampsauce/amphtml/builds/97539895

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by erwinmombay** [comment]
@ampsauce retry

**Comment by ampsauce** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 3740cf0d126822f3832b3314623f61736430cf41
Build details: https://travis-ci.org/ampsauce/amphtml/builds/97544518

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Pull request merged**
