### PR TITLE
Revert "✨ amp-sidebar: support autoscroll "

### PR DESCRIPTION
**Pull request by aghassemi**
Reverts ampproject/amphtml#20524

Reverting due to validation rule being backward incompatible.

### CODE REVIEW

**Comment by aghassemi** [comment]
@Gregable anything we can do short term? Feature is needed as a high priority request. If not, I can switch to `data-autoscroll` and remove just validation rules.

**Comment by aghassemi** [comment]
Or allow 'autoscroll' everywhere but would only work in sidebar for now (and only document in sidebar)

**Comment by Gregable** [comment]
I'll take a look and see if I can figure out something that would accomplish what you want.

**Comment by aghassemi** [comment]
since validation is not tied to Canary cut. I am closing this and will send a different PR that just reverts the validation rule until we figure out a different solution.

**Pull request closed without merging**
