### PR TITLE
✨Added "amp-ad" integration for Anyclip player

### PR DESCRIPTION
**Pull request by ldoroshe**
Hi AMP Team,

this commit adds support for usage of AnyClip video platform for amp-ad tags.

Added:

- Configuration
- Example and documentation
- Video platform logic

Could you please review our contribution?

Thanks

cc @ampproject/wg-ads

### CODE REVIEW

**Comment by ldoroshe** [comment]
@googlebot I signed it!

**Comment by ldoroshe** [comment]
@googlebot I fixed it.

**Comment by ldoroshe** [comment]
@googlebot I fixed it.

**Comment by calebcordry** [comment]
Thanks for contributing! Just a couple of nits: I see the request to `https://player.anyclip.com/anyclip-widget/lre-widget/prod/v1/src/aclre-amp-loader.js` 404, is this expected? 

Also the example ad is blank for me. Is it possible to return an example ad here? It can help us catch regressions etc later.

**Comment by ldoroshe** [comment]
@calebcordry Hi, thanks for reviewing! We have fixed issue with 404, this should fix issue with example as well. Also we have made small change in example tag, just removed attribute for alternative widget source.

**Comment by ldoroshe** [comment]
@calebcordry It seems that this integration test on Travis in pending state for almost 4 days (https://github.com/ampproject/amphtml/pull/28273/checks?check_run_id=677785981). I'm not sure that this is okay. Could you please advise what to do in this case?

**Comment by calebcordry** [comment]
Thanks for contributing!

**Pull request merged**
