### PR TITLE
Fix unsupported browser font sizing, and reenable tests.

### LINKED ISSUE #27185: Story responsive font-sizing seems to be flaky
https://percy.io/ampproject/amphtml/builds/4471771

From the first failure here, it looks like the responsive font sizing might be off.
Tests are currently skipped and need to be re-enabled, cf #27452

cc @ampproject/wg-stories

### PR DESCRIPTION
**Pull request by gmajoulet**
Fix unsupported browser dynamic font sizing, and reenable tests.

Sorry, I know this is super low priority, but I wanted to look into it as I was worried about a bug in the dynamic font sizing code. Fortunately, this was very specific to the unsupported browser page, that set a `display: none;` on all story pages.

This PR pauses the story, instead of hiding the pages. That makes more sense, as we can expect most people to click the "continue anyway" button.

Fixes #27185

### CODE REVIEW

**Comment by gmajoulet** [comment]
Friendly ping

**Comment by gmajoulet** [comment]
Friendly ping, please let me know if you have any questions about this

**Comment by Enriqe** [comment]
is the story unpaused when clicking the "continue anyway" button?

**Comment by gmajoulet** [comment]
Yep: https://github.com/ampproject/amphtml/pull/27487/files#diff-c800be48ffc0b686a96a2c400902e986R2070-R2073

**Pull request merged**
