### PR TITLE
add amp-onerror validation for v0.js or v0.mjs

### LINKED ISSUE #22543: Early styling suggestion on fast failure to load v0.js
**Background**
AMP pages use a clever CSS animation to hide rendering until the AMP runtime has loaded, in order to avoid the dreaded flash of unstyled content:

(Simplified by removing the vendor-prefix variants):
```html
<style amp-boilerplate>
animation:-amp-start 8s steps(1,end) 0s 1 normal both}
@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}
</style>
```

For browsers which don't execute Javascript, there is a fallback:
```html
<noscript>
<style amp-boilerplate>
body {animation:none}
</style>
```

If Javascript is enabled, but the AMP javascript is slow to load, the 8 second animation unblocks the rendering after 8 seconds. A reasonable compromise.

**Problem**
Sometimes Javascript is enabled, and the AMP javascript fails to load in a manner which is detectable much earlier than 8 seconds. For example, if DNS fails to resolve to `cdn.ampproject.org`, a publisher's CORS header prevents loading the cross-origin resource, or an overzealous ad blocker prevents the request.

In these situations, it would be nice to "fail fast" and unblock the visibility of the page faster than 8 seconds.

**Proposal**
We can take advantage of the `onerror` attribute in browsers that have support and we can use this feature to "fail fast". For example:

```html
<script async src="https://cdn.ampproject.org/v0.js"                       
  onerror="document.getElementsByTagName('body')[0].style.cssText += 
           'webkit-animation:none;' +
           '-moz-animation:none;' +
           '-ms-animation:none;' + 
           'animation:none'"></script> 
```

This seems to work, though there is probably a shorter / more elegant version. I could use help in finding that minimal incantation.

I propose that we add this onerror attribute to all v0.js script tags in the AMP Cache and anywhere the AMP transformers run, such as the AMP Packager. We should also allow this exact onerror string in the AMP validator, though not require it.

@ampproject/wg-runtime for thoughts and @cramforce who originally designed the CSS timeout animation.

### PR DESCRIPTION
**Pull request by honeybadgerdontcare**
Fixes #22543

#22543 was to address `v0.js`. With the introduction of `v0.mjs` (module/nomodule) it was reopened for that as well. The CSP and Google AMP Cache transformers already exist for `v0.mjs`. This PR makes those changes valid so other producers can add it to their Transformed AMP.

### CODE REVIEW

**Comment by honeybadgerdontcare** [comment]
//cc @westonruter @sebastianbenz

**Review by jridgewell — APPROVED** [review]

**Comment by westonruter** [comment]
@honeybadgerdontcare There seems to be a problem with the validator change, namely that the old v0.js version being present in a transformed AMP page now causes a validation error: https://testsite.cmsdevrel.com/web-stories/thailand-copy/

Transformed AMP should allow _either_ the new version or the old version, while non-transformed AMP only needs to allow the old version.

**Comment by honeybadgerdontcare** [comment]
So the transformed AMP is not adding module/nomodule here and we want to support that. I'll take a look later today.

**Comment by westonruter** [comment]
@swissspidy can confirm, but I believe ESM was temporarily disabled due to not being compatible with Stories. See https://github.com/google/web-stories-wp/issues/7649.

**Comment by honeybadgerdontcare** [comment]
@swissspidy the work around for now is to use the updated amp-onerror that was introduced in this change

```
<script amp-onerror>[].slice.call(document.querySelectorAll("script[src*='/v0.js'],script[src*='/v0.mjs']")).forEach(function(s){s.onerror=function(){document.querySelector('style[amp-boilerplate]').textContent=''}})</script>
```

**Comment by westonruter** [comment]
That could also be achieved by updating to use the change from https://github.com/ampproject/amp-toolbox-php/pull/211.

**Pull request merged**
