### PR TITLE
📖 Pressboard vendor updates

### PR DESCRIPTION
**Pull request by tiamkorki**
Update Pressboard analytics config and documentation link.

### CODE REVIEW

**Comment by tiamkorki** [comment]
Hi @alanorozco, would you be able to assist, not sure if there is anything else I need to do at this point to get this PR approved. Thanks.

**Comment by alanorozco** [comment]
@tiamkorki Thanks for the update!

@micajuine-ho, would you mind taking a look at the configuration changes?

**Review by powerivq — APPROVED** [review]
Approval for ad changes.

**Comment by tiamkorki** [comment]
> @tiamkorki Thanks for the update!
> 
> @micajuine-ho, would you mind taking a look at the configuration changes?

Hi @alanorozco, looks like it just needs your approval now. Would appreciate if you could look when you have a chance. Thanks.

**Review by alanorozco — COMMENTED** [review]
@tiamkorki No need for my approval. I'll merge.

**Pull request merged**
