### PR TITLE
eliminate dev().assert() and dev().fine() calls from src/log.js module

### PR DESCRIPTION
**Pull request by erwinmombay**
This is in preparation for the changes @jridgewell is doing for us to tree shake the log module better. (remove side effects from a simple module import)

### CODE REVIEW

**Comment by erwinmombay** [comment]
cc @jridgewell just need to add tests

**Comment by erwinmombay** [comment]
will eventually remove the old `dev.assert()`/`dev.fine()` removal code

**Comment by jridgewell** [comment]
LGTM. I'm going to merge this into my branch.

**Comment by erwinmombay** [comment]
tests added @jridgewell let me know when you have your changes pushed to a PR so i can test against it. thanks

**Comment by jridgewell** [comment]
I can confirm they DCE correctly.

**Comment by jridgewell** [comment]
Closed by https://github.com/ampproject/amphtml/pull/4261.

**Pull request closed without merging**
