### PR TITLE
✨Implement AMP analytics linker for Marin Software

### PR DESCRIPTION
**Pull request by jackyjieliu**
Implement AMP analytics linker for Marin Software

### CODE REVIEW

**Comment by mrjoro** [comment]
@jackyjieliu sorry for the delay in reviewing!

@calebcordry or @zhouyx can one of you take a look at this PR?

**Comment by calebcordry** [comment]
@jackyjieliu sorry this slipped through LGTM. Looks like a test flake, I will restart and try to keep an eye on it. Feel free to ping if you see it finish before I do.

**Comment by zhouyx** [comment]
@jackyjieliu we couldn't merge the PR because it fails to build. could you please rebase to the latest master to fix this. Thank you!

**Comment by zhouyx** [comment]
@jackyjieliu No need to rebase. We are able to merge this PR once we get your response. Given this is going to change the default behavior. Please do let us know if you want to proceed and merge the change. Thank you!

**Comment by zhouyx** [comment]
@jackyjieliu we haven't heard back from you. Closing this PR for now. Please let us know if you still want the change. We can reopen and merge the PR once we get back from you. Thanks.

**Pull request closed without merging**
