### PR TITLE
Rename "hidden" trigger to "unload" trigger.

### LINKED ISSUE #5934: [amp-analytics] the "visible" and "hidden" triggers are a bit confusing
By looking at the name, I would think that they're the opposite counterpart to each other. Especially, they share the same `VisibilitySpec` to select an element and specify the conditions to meet.

However, the "visible" trigger fires when the **selected element** enters viewport; but the "hidden" trigger fires when user leaves the **page** (vs selected element leaves viewport).

It will be more self-explained if we rename "hidden" to "pagehidden" (or something similar).

### PR DESCRIPTION
**Pull request by lannka**
Closes #5934

### CODE REVIEW

**Comment by lannka** [comment]
Test

**Comment by jridgewell** [comment]
@lannka: What's the status of this?

**Comment by lannka** [comment]
Still under discussion in #5934

**Comment by lannka** [comment]
decided not to use `unload`

**Pull request closed without merging**
