### PR TITLE
[WIP] Moving viewer.js into own service, still buggy

### PR DESCRIPTION
**Pull request by AaronCritchley**
Moving viewer.js into it's own service in accordance with [Issue #1055](https://github.com/ampproject/amphtml/issues/1055).

As of time of writing, I'm running into the followiung bug when running `gulp test`:

```bash
Chrome 45.0.2454 (Linux 0.0.0) ERROR
  Uncaught Error: Factory not given and service missing viewer
  at /tmp/47145ce937f497c2d26f372086a6259b.browserify:19159 <- /home/aaron/amphtml/src/asserts.js:62:4
```

### CODE REVIEW

**Comment by AaronCritchley** [comment]
Pinging @cramforce and @erwinmombay.

**Comment by cramforce** [comment]
The reason is that history depends on viewer. The easy fix is to swap installation, the better fix is to install the viewer service from the history service (on top of the change to amp.js).

**Comment by erwinmombay** [comment]
@AaronCritchley can you try adding:

```js
import {installViewerService} from '../service/viewer-impl';

installViewerService(window);
```

on `src/service/history-impl.js`, should get rid of the error

**Comment by AaronCritchley** [comment]
Sadly no luck.

```
Chrome 45.0.2454 (Linux 0.0.0) ERROR
  Uncaught Error: Factory not given and service missing viewer
  at /tmp/682779060a57382794543b59095dbda0.browserify:19159 <- /home/aaron/amphtml/src/asserts.js:62:4
```

```
[21:27:16] 'test' errored after 22 s
[21:27:16] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/home/aaron/amphtml/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /home/aaron/amphtml/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/home/aaron/amphtml/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/home/aaron/amphtml/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/home/aaron/amphtml/node_modules/karma/lib/server.js:332:7)
    at Server.<anonymous> (/home/aaron/amphtml/node_modules/karma/lib/server.js:343:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1521:8)
    at doNTCallback1 (node.js:428:9)
    at process._tickCallback (node.js:350:17)
```

**Comment by cramforce** [comment]
Could you try to use Chrome DevTools or another way to get a stack trace for when or from where viewerFor is called?

**Comment by erwinmombay** [comment]
screen shot 2015-12-16 at 2 05 57 pm

still debugging this but heres the `error.stack` output.

**Comment by erwinmombay** [comment]
@AaronCritchley so in viewport.js it looks like we also need to do:

```js

import {installViewerService} from './service/viewer-impl';

installViewerService(window);
```

@cramforce

**Comment by erwinmombay** [comment]
oh and dont forget to add:

```js
import {getElementService} from './service';
```

in history.js

**Comment by AaronCritchley** [comment]
Changes implemented, I've merged master but feeling somewhat unsure if I've screwed something up with my implementation.

I will squash all of the commits when the PR is in good shape, thanks for being so patient with the whole thing!

**Comment by erwinmombay** [comment]
@AaronCritchley yep, just keep the commits for now, they'll be useful for me for debugging until we get everything working. thanks!

**Comment by AaronCritchley** [comment]
Closing as @cramforce has done this work (thanks!) in #1236.

**Pull request closed without merging**
