### PR TITLE
Ibeat analytics domain change

### PR DESCRIPTION
**Pull request by denmark-admin**

### CODE REVIEW

**Comment by zhouyx** [comment]
@denmark-admin Since you're on this : ) Could you also update the ibeat analytics doc here
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vendors-list.md

**Comment by denmark-admin** [comment]
> @denmark-admin Since you're on this : ) Could you also update the ibeat analytics doc here
> https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vendors-list.md

Sure will do.

**Comment by denmark-admin** [comment]
> > @denmark-admin Since you're on this : ) Could you also update the ibeat analytics doc here
> > https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vendors-list.md
> 
> Sure will do.

I have updated the documentation for Ibeat.

**Comment by zhouyx** [comment]
Thank you! LGTM

**Pull request merged**
