### PR TITLE
Revert "Remove old IO file"

### PR DESCRIPTION
**Pull request by zhouyx**
Reverts ampproject/amphtml#6362
Sadly we need to get this back before we have a solution to provide position info to 3p when its element is in viewport. 
See discussion in #5603

### CODE REVIEW

**Comment by lannka** [comment]
Shall we make the change in amp-ad in the same PR for easier check-pick?

**Comment by lannka** [comment]
@muxin @erwinmombay can we cherry pick this PR to the current canary, so we can have it on production this week?

/cc @harquail FYI this PR is going to fix your problem

**Comment by harquail** [comment]
Confirmed this fixes our bug.  Thanks again! 
(fyi @yieldmo-rao)

**Comment by yieldmo-rao** [comment]
Thank you all for resolving this so quickly! Many thanks from all of us here at Yieldmo!

**Pull request merged**
