### PR TITLE
Enable a4a friendly iframe css splitting for prod

### LINKED ISSUE #22418: Having separate CSS for amp4ads runtime
Goals
- prevent bugs caused by AMP's default CSS override ( #22034 #22059)
- share exact same CSS for inabox and FIE. ideally we should make inabox CSS a strict subset of regular doc CSS.
- have clearer file structure & save some bytes 

Tasks
- [x] Split amp.css into 2 files amp-base.css & amp-doc.css , where amp-base.css is used for FIE and inabox, amp-doc.css + amp-shared.css is used for regular AMP doc.
- [x] Run experiment for FIE rendering
- [x] Run experiment for inabox rendering
- [x] Clean up experiment flags after launching

@erwinmombay @dvoytenko @choumx

### PR DESCRIPTION
**Pull request by powerivq**
Remove experiment related code and release the feature.

closes #22418

### CODE REVIEW

**Comment by lannka** [comment]
@powerivq is this launch stable now? We can move forward with this clean up?

**Comment by powerivq** [comment]
@dvoytenko for approval of friendly-iframe-embed.

@lannka Should we change to make ampproject/wg-ads owns that file?

**Comment by lannka** [comment]
Is this PR ready to go?

**Comment by powerivq** [comment]
@lannka Yes. I was waiting for dima's owner approval, but my other PR made wg-ads an owner, so it is unblocked.

**Comment by dvoytenko** [comment]
Sorry, missed this PR. What does it do exactly? Is it simply cleaning up the launched feature?

**Comment by powerivq** [comment]
@dvoytenko Yes.

**Pull request merged**
