### PR TITLE
Change `assert` to `user.assert`.

### PR DESCRIPTION
**Pull request by avimehta**
The bug was introduced in #2684

### CODE REVIEW

**Comment by dvoytenko** [comment]
LGTM

**Comment by avimehta** [comment]
@dvoytenko The tests failed on unrelated change. Can you start them again? 

thanks!

**Comment by erwinmombay** [comment]
restarted

**Comment by erwinmombay** [comment]
@cramforce this currently isnt in canary but fixes a bug that is currently in canary (introduced in https://github.com/ampproject/amphtml/pull/2684). should we go ahead and get this in before prod release thursday?

/cc @querymetrics @avimehta

**Comment by avimehta** [comment]
I support this cherrypick.

**Comment by cramforce** [comment]
I don't understand why this is important enough to warrant a cherry pick.

**Comment by cramforce** [comment]
Talked on Slack. This can go out with the normal canary on Thursday.

**Pull request merged**
