### PR TITLE
:bug: amp-analytics Piwik PRO: Fix for a bug in vendor integration with AMP project

### PR DESCRIPTION
**Pull request by RomanSek**
🐛 [Piwik PRO integration] Fix for a bug in vendor integration with AMP project (https://github.com/ampproject/amphtml/pull/32838)

1. Better detection of the cookie value that doesn't follow Piwik PRO standard. When detected cookie value is transformed to a value following standard used in Piwik PRO.
2. Removed `urlref` parameter from request when it's empty. Currently I'm only replacing the name of the parameter with `ignored`. This fixes the bug, but if you could point out a way to completely remove that parameter under such conditions I would be happy to update this PR.

@ampproject/wg-components
@ampproject/wg-analytics

### CODE REVIEW

**Comment by RomanSek** [comment]
@nainar Hi, can you update me on the status for this fix?
I see that visual tests failed, but it looks like it's not related to my changes.
Please let me know if there is something I can do to expedite the release process.

**Comment by RomanSek** [comment]
Hi @erwinmombay, @alanorozco i sent this PR some time ago and didn't get any response. I looked PRs touching code in similar places and your names popped up. Can you help me with the merge process?

**Comment by RomanSek** [comment]
@ampproject/wg-analytics
@ampproject/wg-approvers
I'm still trying to contact someone regarding this PR. Can anybody help me identify what is blocking review?

**Comment by RomanSek** [comment]
/cc @alanorozco
/cc @dmanek
/cc @nainar 
/cc @caroqliu
/cc @rbeckthomas 

Hi, I'm trying to see if someone is able to review this request. Can you point me to the right person?

**Comment by erwinmombay** [comment]
@powerivq @calebcordry could someone take a look at this please. thanks

**Review by erwinmombay — APPROVED** [review]

**Pull request merged**
