### PR TITLE
🚀 [Story performance] Enable remote localization to 10%

### PR DESCRIPTION
**Pull request by mszylkowski**
Set the experiment `story-remote-localization` to 10% so we can ensure the switch doesn't throw unexpected errors.

Next steps are:
- Check CLS is unaffected, no errors reported due to this
- Set experiment to 100%
- Remove localization strings from bundle (reducing size by 8kB), then remove experiment and make it default.

We should merge this first: https://github.com/ampproject/amphtml/pull/38204 (fixing remote localization for amp-story-subscription extension)

### CODE REVIEW

**Review by gmajoulet — APPROVED** [review]

**Comment by gmajoulet** [comment]
Please make sure the next steps are properly tracked with internal and/or external tickets as needed :))

**Comment by erwinmombay** [comment]
@danielrozenberg would you mind explaining what the difference is between making the config change here vs in https://github.com/ampproject/cdn-configuration/blob/main/configs/client-side-experiments.json ? i wasn't sure which is preferred

**Review by jridgewell — CHANGES_REQUESTED** [review]
Changing here requires a 2week rollout.  Please use https://github.com/ampproject/cdn-configuration/blob/main/configs/client-side-experiments.json

**Comment by danielrozenberg** [comment]
Yep, what @jridgewell said.
Changes to the config file in `cdn-configuration` are rolled out ~immediately (up to 1 hour on cdn.ampproject.org, almost instantly in ampjs.org) and are easy to roll back if there are any issues

**Comment by mszylkowski** [comment]
We will use https://github.com/ampproject/cdn-configuration/pull/353 to deploy the changes with client-side experiments

**Comment by mszylkowski** [comment]
@danielrozenberg if we merge the configuration, do we ever need to worry about these files in this repo? Aka can I close this PR and not merge it?

**Comment by mszylkowski** [comment]
That sounds good, I was mostly wondering if for completeness / cleanup we should maintain both configs equal, but I assume the answer is that we don't care about that.

**Pull request closed without merging**
