### PR TITLE
Use prod AMP config for local development

### LINKED ISSUE #8008: Prepend AMP_CONFIG to local runtime binary
It can fix 2 problems:
- experiments enabled in prod right now are by default disabled in dev mode. sometimes causing confusion. or in worst case, release eng is not testing with the exact setup as prod, hence mis-catch bugs.
- many code relies on `mode.localDev`, which is calculated via [messy logic](https://github.com/ampproject/amphtml/blob/master/src/mode.js#L82) including checking if hostname equals `localhost`, hence failed on our [Heroku nightly server](amphtml-nightly.herokuapp.com/examples/). (/cc @alanorozco this is what you encountered)

**Solution A**
The reason we separate the prepending `AMP_CONFIG` task from the main binary building process, is because we want to change `AMP_CONFIG` without rebuilding the binary (keep the same version number). 

If we know it's for local build (by passing `--fortesting` flag), we automatically do `gulp prepend-global`.

**Solution B**
Let local gulp dev server to handle the prepend logic.

@erwinmombay what you think?

### PR DESCRIPTION
**Pull request by rsimha-amp**
This PR fixes the issues described in #8008, and implements the solutions proposed in 
https://github.com/ampproject/amphtml/issues/8008#issuecomment-320288645.

It also makes `gulp prepend-global` idempotent when called with `--prod`, `--canary`, and `--remove`.

Fixes #8008

### CODE REVIEW

**Comment by rsimha-amp** [comment]
@cramforce @lannka @erwinmombay @choumx Please review and let me know what you think. I'm going to have to do extensive testing of this PR before it can be merged.

**Comment by rsimha-amp** [comment]
Bumping this.

**Comment by cramforce** [comment]
If we had infinite CPU we'd run tests with both prod and canary config.
Is there a flag to switch between modes?

**Comment by rsimha-amp** [comment]
The way to switch modes right now:

```
gulp prepend-global {--prod | --canary | --remove}
```
I can plumb this in to a flag for `gulp dist` and make the config known during a build.

**Comment by rsimha-amp** [comment]
And for automated tests, it's trivially easy to change configs in between tests. Assuming we don't have to do a full rebuild, I believe it'll add about 2-5 mins to a Travis run if we test both configs. I can experiment with this to see what the impact is.

**Comment by rsimha-amp** [comment]
@cramforce @choumx @erwinmombay, I've made several changes to this PR. We now apply the `prod` AMP config by default during `gulp dist --fortesting`. I've also added a `--config` flag (defaults to `prod`) to `gulp dist`.

PTAL.

**Comment by rsimha-amp** [comment]
@cramforce @choumx @erwinmombay Bumping this PR in case any of you want to take another look. I've tested this extensively, and am in the process of updating any tests that rely on the fact that `v0.js` contains no AMP config.

**Pull request merged**
