### PR TITLE
remove windowconfig

### PR DESCRIPTION
**Pull request by erwinmombay**

### CODE REVIEW

**Comment by cramforce** [comment]
Could you give me some context? Is this being added externally?

**Comment by erwinmombay** [comment]
@cramforce correct, we will switch it to the `gulp prepend-global` task

**Comment by erwinmombay** [comment]
the reason this was added original during `dist` was for modifying AMP_CONFIG during test. but that seems to have been solved

**Comment by dvoytenko** [comment]
LGTM from my side. Deferring to @cramforce for the final approval.

**Comment by cramforce** [comment]
LGTM

**Pull request merged**
