### PR TITLE
Update amp-jwplayer validator

### PR DESCRIPTION
**Pull request by nebnitt**
This PR updates the spec file for `amp-jwplayer` to allow `outstream` as a valid data-media-id in addition to the existing regex rule.

### CODE REVIEW

**Review by zetagame — APPROVED** [review]
lgtm

**Review by Gregable — APPROVED** [review]
Validation looks fine.

**Comment by honeybadgerdontcare** [comment]
@zhouyx any issue with merging this?

**Comment by zhouyx** [comment]
No. Looks good to me. Merged

**Pull request merged**
