### PR TITLE
Fix 3p/ OWNERS files

### PR DESCRIPTION
**Pull request by powerivq**

### CODE REVIEW

**Comment by alanorozco** [comment]
source

**Comment by rcebulko** [comment]
@rsimha This was a fix for an owners "bug" where a JSON object unintentionally had duplicate keys, but was treated as valid. Is there any way for Prettier or whatever we're using to validate the format to detect and reject that?

**Comment by rsimha** [comment]
We use Prettier, but I don’t think it cares about duplicate keys. Eslint can check for duplicate keys, but it can’t parse our owners format.

**Comment by rsimha** [comment]
Maybe you could build this into the owners bot api check?

**Comment by rcebulko** [comment]
When JSON is parsed it drops dupe keys, so it's not available to the bot

**Comment by rcebulko** [comment]
The owners bot would have to implement its own JSON parser/linter to detect this, which I'd say is infeasible. I guess this is one kind of error that may not be reasonable to automatically detect

**Pull request merged**
