### PR TITLE
Include Content.ad in Supported ad networks list

### PR DESCRIPTION
**Pull request by jlucero-contentad**

### CODE REVIEW

**Comment by jlucero-contentad** [comment]
@jridgewell ping! :)

**Comment by jridgewell** [comment]
Whoops. 😊

**Comment by jlucero-contentad** [comment]
Thanks @jridgewell!

**Comment by jlucero-contentad** [comment]
@jridgewell I'm not seeing Content.ad in the amp-ad tag documentation today. Was my change rolled back?
https://www.ampproject.org/docs/reference/extended/amp-ad.html

**Comment by jridgewell** [comment]
It takes a few days for it to show up on the actual site, but it's definitely in the codebase.

**Comment by jlucero-contentad** [comment]
Ah ok, I saw it yesterday, so I thought it was all set. I must have hit a server that had the code on it already.

**Comment by lannka** [comment]
Sorry for joining in late. `builtins/amp-ad.md` is deprecated. The changes should have been made to `extensions/amp-ad/amp-ad.md` instead.

We plan to remove the duplicates soon to avoid such confusion, see #4946

**Comment by jlucero-contentad** [comment]
@jridgewell @lannka I'll update the new `extensions/amp-ad/amp-ad.md` now and submit a new pull request soon.

**Comment by jlucero-contentad** [comment]
Pull request submitted #4966

**Pull request merged**
