### PR TITLE
Add EPICA

### LINKED ISSUE #18808: Intent-to-Implement: EPICA
We would love to add [EPICA](https://www.epica.ai/) as an amp-analytics plugin.

A simple example that sends a pageview:
```html
<amp-analytics type="epica">
<script type="application/json">
{
  "vars": {
    "writeKey": "abcde1234",
    "name": "Page title"
  }
}
</script>
</amp-analytics>
```

### PR DESCRIPTION
**Pull request by abiaskosty**
Add EPICA to amp-analytics. Closes #18808.

```html
<amp-analytics type="epica">
<script type="application/json">
{
  "vars": {
    "writeKey": "abcde1234",
    "name": "Page title"
  }
}
</script>
</amp-analytics>
```

### CODE REVIEW

**Comment by torch2424** [comment]
@abiaskosty Once you sign the CLA, feel free to mention me, and I can do the review 😄

**Comment by abiaskosty** [comment]
@torch2424 the CLA is signed. Please review.

**Comment by torch2424** [comment]
Also, The CLA is still having an issue. Try commenting on the PR with "I signed it!". If that doesn't work, make sure you signed the CLA with the same email you used for the commit. You can find it using `git log`.

screen shot 2018-10-25 at 12 57 12 pm

**Comment by abiaskosty** [comment]
I signed it!

**Comment by abiaskosty** [comment]
@torch2424 Posting `I signed it!` worked)
I pushed a fix for incorrect URL it now will return success response. Thank you for spotting!

**Comment by abiaskosty** [comment]
@torch2424 thank you! I already created a pull request https://github.com/ampproject/docs/pull/1273.
Usually how long it takes until a plugin is available publicly after a merge?

**Pull request merged**
