### PR TITLE
♻️ Move localization code from extensions/amp-story/ to src/services/

### PR DESCRIPTION
**Pull request by newmuis**
The localization service is not extension-specific, so moving it to `src/` to better allow/encourage reuse.

### CODE REVIEW

**Comment by newmuis** [comment]
> Move this into `src/services/`, please.

Done

**Comment by newmuis** [comment]
There's a dep check that files matching `extensions/**/*.js` must not depend on `src/service/**/*.js`.  But, I think that's explicitly the point for this service; all of its users would want that.

Should I whitelist stories code for that dependency, or is there a better approach?

**Comment by choumx** [comment]
Use the getter in services.js instead?

**Comment by newmuis** [comment]
They will also need to access constants in that file.  Should I separate out the constants and move them to `src/` directly?

**Comment by choumx** [comment]
Yup, that'll work.

**Comment by jridgewell** [comment]
> Should I separate out the constants and move them to src/ directly?

It's done this way to prevent extensions from accidentally including the entire service code in their binaries.

**Pull request merged**
