### PR TITLE
🐛 Overshooting the borders in interactive-quiz made them disappear on iOS

### LINKED ISSUE #30788: [Story interactive] Borders don't scale well for small values
On smaller screens or when the components are scaled down, the borders might disappear on the corners of the options since they get too thin. Only happens on iOS.

image

### PR DESCRIPTION
**Pull request by mszylkowski**
On iOS the quiz options would overshoot the border-radius property beyond 1/2 of the height of the actual option div, which glitches the shadow renderer and doesn't show the borders on the corners. Does not happen consistently across devices, but is consistent on a single device and story. With this change, the border-radius will be slightly smaller than the height and will not overshoot, therefore fixing the bug.

Tested on iOS with web inspector and was able to fix bug with this change.

Height of options div is 3.3em, so half of it is 1.65ems. Had to set border-radius to 1.649 to get rid of this error.

Example of overshooted borders not rendering properly the inset box-shadow:
image

Fixes #30788

### CODE REVIEW

**Comment by gmajoulet** [comment]
We never allow 2 lines options? How about a 50% border radius?

**Comment by mszylkowski** [comment]
If they have 2 lines it still has the same height of the option element.

Using 50% not only doesn't work (I tried and in order to fix this we'd have to use 49.7% otherwise it glitches), but it's impossible to set an equal border-radius horizontal and vertical based on the height without JS.

This is a weird glitch that we're trying to solve from iOS's web renderer, but from what I tested, only fixing the border-radius to be somewhat smaller than the height solves the problem. I'll add a line explaining the glitch on the CSS file to explain why it's like that

**Comment by gmajoulet** [comment]
If the 50% is not working because of the border, should we change the box sizing to `border-box` and keep 50%?

**Comment by mszylkowski** [comment]
The border is actually being done with inset box-shadows, the box-sizing does not influence much in here. Also anything < 50% of the height would be cool but border-radius can't specify a horizontal radius based on the height so it has to be an absolute value (eg: in ems)

**Review by gmajoulet — APPROVED** [review]

**Pull request merged**
