### PR TITLE
✨ Ads: Resolves support for Opinary Embed integration

### PR DESCRIPTION
**Pull request by torbenbrodt**
Opinary has developed a software solution for online polls.

So far the AMP integration only supported the "automatic matching", where the Opinary algorithm decided what polls to show.

This pull request allows publishers to embed a specific poll to a specific article.
The publisher is also able to subscribe to the poll data using postmessage events.

### CODE REVIEW

**Review by lannka — APPROVED** [review]

**Comment by lannka** [comment]
please run `amp lint --fix` to fix the lint errors.
error logs: https://app.circleci.com/pipelines/github/ampproject/amphtml/5673/workflows/eece03a3-1ac9-49b6-a986-614a82615aa6/jobs/78482

**Review by lannka — APPROVED** [review]

**Comment by lannka** [comment]
Seems you need a rebate to pass the checks.
https://app.circleci.com/pipelines/github/ampproject/amphtml/6095/workflows/cf7da3a4-6d99-49cd-8842-0a1e4f581b77/jobs/86136

```
ERROR: pull/33518 is missing the latest CircleCI config revision 1652b120258d05510e20ec0de732130e2c6358e2.


This can be fixed in three ways:


1. Click the "Update branch" button on GitHub and follow instructions.
   ⤷ It can be found towards the bottom of the PR, after the list of checks.


2. Pull the latest commits from master and re-push the PR branch.
   ⤷ Follow these steps:

      git checkout master
      git pull
      git checkout <PR branch>
      git merge master
      git push origin


3. Rebase on master and re-push the PR branch.
   ⤷ Follow these steps:

      git checkout master
      git pull
      git checkout <PR branch>
      git rebase master
      git push origin --force
```

**Comment by torbenbrodt** [comment]
Thanks for the patience. The last CircleCi build failed with a timeout. Would be great if you can re-run the pipeline.

**Comment by torbenbrodt** [comment]
I tried to re-push changes so CircleCI build runs successfully, but still CircleCI breaks for other reasons. Would be great if you can re-run the jobs. Thanks

**Pull request merged**
