### PR TITLE
✨ amp-auto-ads extension: Denakop

### PR DESCRIPTION
**Pull request by EdmilsonSilva**
We changed the CSS style of the amp-ad tag

### CODE REVIEW

**Comment by powerivq** [comment]
Hi

I wonder why you want to ad this position css. In which case does it render incorrectly?

**Comment by powerivq** [comment]
Please fix the circle failure, but otherwise it's good.

**Comment by EdmilsonSilva** [comment]
> Hi
> 
> I wonder why you want to ad this position css. In which case does it render incorrectly?

Hi, 

When the sizes not provided, the `i-amphtml-layout-awaiting-size` class is added, which has a `position: absolute`

**Comment by EdmilsonSilva** [comment]
> Please fix the circle failure, but otherwise it's good.

What is failure?
I saw it on CircleCI and the same test was canceled
Others test I think they need approval

**Comment by EdmilsonSilva** [comment]
> > > Please fix the circle failure, but otherwise it's good.
> > 
> > 
> > What is failure?
> > I saw it on CircleCI and the same test was canceled
> > Others test I think they need approval
> 
> https://app.circleci.com/pipelines/github/ampproject/amphtml/8447/workflows/e577cfa2-44c4-4ce8-9a80-294b6f6fea24/jobs/127229
> 
> The rest jobs were cancelled because this failed.
> 
> ```
> [22:37:03] 
> extensions/amp-auto-ads/0.1/denakop-network-config.js
>   84:46  error  Insert `,`  prettier/prettier
> 
> ✖ 1 problem (1 error, 0 warnings)
>   1 error and 0 warnings potentially fixable with the `--fix` option.
> 
> [22:39:50] ERROR: Found 1 error(s) and 0 warning(s).
> ```
> 
> It's a simple lint issue. You can fix it with `amp lint --fix`

Ok 

Done

Thanks

**Comment by EdmilsonSilva** [comment]
> Also pls follow that CLA message's instruction to sign the CLA. `Edmilson` has not signed the CLA.

I did, but the CLA check is not working

Screenshot from 2021-05-12 10-23-27

**Comment by powerivq** [comment]
We're close! Last thing is that the test failed. Maybe you could rebase against latest main branch and try again.

**Comment by powerivq** [comment]
@EdmilsonSilva Not sure what you did, but it seems wrong that you introduced a bunch of unrelated commits.

**Comment by EdmilsonSilva** [comment]
> @EdmilsonSilva Not sure what you did, but it seems wrong that you introduced a bunch of unrelated commits.

**Comment by EdmilsonSilva** [comment]
> > @EdmilsonSilva Not sure what you did, but it seems wrong that you introduced a bunch of unrelated commits.
> 
> sorry @powerivq
> I tried to make `pull` and `rebase` from main project `branch main`
> I do not know what happened

I reversed the commits and created another PR (Draft) # 34374 from `main`
I could close this PR and put that for review.

what do think it's better?

**Comment by powerivq** [comment]
I would proceed here. It's in a good shape now so no need for another PR.

**Review by powerivq — APPROVED** [review]

**Comment by EdmilsonSilva** [comment]
> I would proceed here. It's in a good shape now so no need for another PR.

ok thanks, I closed the other PR

**Pull request merged**
