### PR TITLE
🐛 Catch up java validator to Doc Css logic

### PR DESCRIPTION
**Pull request by GeorgeLuo**
- Length check of css moved to Doc Css, clean Css length spec references

### CODE REVIEW

**Comment by nhant01** [comment]
> @googlebot I consent

**Comment by Gregable** [comment]
Let me know if you would like me to make the merge, I don't know if you have merge rights or not.

**Comment by GeorgeLuo** [comment]
don't have merge rights, please merge

**Comment by Gregable** [comment]
I think Nhan's consent isn't getting picked up from the bot because he quoted it, ie: It starts with a `>` symbol. Trying to force the bot to ignore.

**Comment by rsimha** [comment]
Drive-by comment: We had to disable the java validator tests due to #28497. You'll need to re-run the checks for this PR after rebasing on `master` and pulling in #28498.

**Comment by Gregable** [comment]
It looks like we're hitting the keyserver issue reported in another thread now.

**Comment by GeorgeLuo** [comment]
that lessens priority to do as rsimha indicates, correct? rather than raises it?

**Comment by rsimha** [comment]
I'll let Greg comment on the priority of this PR :)

Meanwhile, if you want to be able to merge it, just push a new commit (or rebase), and it should be able to run the other Travis checks while bypassing the keyserver problem.

**Comment by nhant01** [comment]
@googlebot I consent

**Pull request merged**
