### PR TITLE
🚀 ♻️ [amp-story] getPageDistanceMap refactor

### PR DESCRIPTION
**Pull request by processprocess**
In a story with 40 pages this runs about 95% faster. 
`1ms` to `.04ms` on average on a **high** end device (macbook pro).
`19ms` to `1ms` on average on a **low** end device (Galaxy On5).

- Gets distance based on active index and order of DOM nodes.
- Removes recursive algorithm that compares adjacent pages.
- Simplifies code by removing unused arguments.

[Demo](https://stamp-autoplay.web.app/examples/amp-story/ampconf.html)
open console to see logs of time comparison of original and refactored methods.

cc @ampproject/wg-stories

### CODE REVIEW

**Comment by mszylkowski** [comment]
Would be awesome to take this approach but some things would be lost from the current approach, we just need to make sure these are not being used:
- Branching with `[on*="goToPage"]` or `advance-to` (which is an experiment, I don't think people use it)
- `auto-advance-to` (which I haven't seen in the wild)
- `i-amphtml-return-to` (which I also haven't seen)

From what I can tell, those features are the ones that slow down the code the most (and probably the reason why it's so complex), do you know if we can safely remove them? Then we might be able to strip down even more code 🤔

**Comment by gmajoulet** [comment]
Thank you for investigating Matias!
This is the feature we called "branching" and never launched because of some UX concerns (you could make the last page of a story go to the first page, and users would be stuck into a loop).

Could you start a super small doc or issue and document how much we'd gain from removing this (unlaunched/invalid) code, in terms of performance and what it'd allow us to do?

**Comment by mszylkowski** [comment]
Just to clarify, seems like the original time is 1ms not 1s, right? Then it might not be worth it to refactor

**Comment by processprocess** [comment]
> Just to clarify, seems like the original time is 1ms not 1s, right? Then it might not be worth it to refactor

It's ms. I added average times for a low end device where it's much more noticeable.

**Comment by mszylkowski** [comment]
Ok thanks for the update! We can do more research on this, but seems like `advance-on` is used by ads so we'd have to refactor a good amount of code to make this change work, maybe depracating the branching experiment can speed it up a bit, but also for shorter stories (10 pages) it might be a lot less noticeable

**Pull request closed without merging**
