### PR TITLE
Cleanup elements resource property when element is removed.

### LINKED ISSUE #3366: Reset `element[RESOURCE_PROP_]` when the resource is removed from resource manager
`Resources.remove(element)` should reset `element[RESOURCE_PROP_]` since we can consider that resource no longer exists.

### PR DESCRIPTION
**Pull request by mkhatib**
Fixes #3366

### CODE REVIEW

**Comment by dvoytenko** [comment]
LGTM

**Comment by dvoytenko** [comment]
ping?

**Comment by mkhatib** [comment]
Yeah I just wanted to make sure that we're doing the right thing here, I remember there was a discussion with @jridgewell around this so I just want to go back to see that discussion and make sure this is ok.

**Comment by dvoytenko** [comment]
@mkhatib Looking through this again and it actually looks like this is not strictly needed. The `Resource` will be either gc'd with the element itself or it will be overwritten by another resource and gc'd still. Let's close.

**Comment by mkhatib** [comment]
Cool thanks for confirming 👍

**Pull request closed without merging**
