### PR TITLE
deps: bump bento-compiler

### PR DESCRIPTION
**Pull request by samouri**
**summary**
Bumps bento-compiler version number, which includes mem-leak fixes and perf improvements.

### CODE REVIEW

**Review by rcebulko — APPROVED** [review]
Set up renovate to do this automatically

**Comment by samouri** [comment]
> Set up renovate to do this automatically

To do what automatically? Currently it _would_ do it, but on some kind of schedule cadence.

I think you are saying that you want to have renovate create PRs for `@ampproject/bento-compiler` (and potentially all ampproject repos?) immediately when available.

**Comment by rcebulko** [comment]
> To do what automatically? Currently it _would_ do it, but on some kind of weekly cadence.
Create and auto-submit this PR

> I think you are saying that you want to have renovate create PRs for `@ampproject/bento-compiler` (and potentially all ampproject repos?) immediately when available. I think that is a reasonable request.
IIRC renovate should allow for different schedules/policy based on dependency pattern (we currently group things this way).

/cc @ampproject/wg-infra for how much effort this would be to configure. `@ampproject/bento-compiler` on an "every hour" or live schedule with auto-submit enabled

**Comment by rsimha** [comment]
I'd imagine this can be achieved by creating a separate group for `@ampproject/bento-compiler` in https://github.com/ampproject/amphtml/blob/main/.renovaterc.json and overriding the global [`schedule`](https://docs.renovatebot.com/configuration-options/#schedule) option for that group using something like `"extends": ["schedule:<choose your cadence>"]`.

**Comment by rsimha** [comment]
Until then, this is the group that governs `bento-compiler` updates:

https://github.com/ampproject/amphtml/blob/10361c9a4435ff32e5bf908d9ed6328734ffcade/.renovaterc.json#L87-L95

**Comment by samouri** [comment]
I'd imagine this is useful for all of `@ampproject` deps. Its at least true for `worker-dom`

**Comment by rsimha** [comment]
In that case, I'm all for overriding the schedule for the entire `@ampproject/` group.

**Pull request merged**
