### PR TITLE
Add new AD network - Realclick

### PR DESCRIPTION
**Pull request by thacker6**
We have added our ad network "Realclick".

- Add network logic
- Add samples and doc
- Update configuration files

Could you please review our commits? Thank you.

### CODE REVIEW

**Comment by lannka** [comment]
@thacker6 thanks for the PR. can you follow the guideline [here](https://github.com/ampproject/amphtml/blob/master/ads/README.md#developer-announcements-for-ads-related-API-changes) and implement the render-start API

**Comment by thacker6** [comment]
@lannka, Thanks for your review. Update files.

**Comment by thacker6** [comment]
amp-ad.md already updated.
Sorry, but I don't know which part to change.

**Comment by thacker6** [comment]
@lannka 
amp-ad.md already updated.
Sorry, but I don't know which part to change.

**Comment by thacker6** [comment]
@lannka
amp-ad.md already updated.
Is there anything else I need to modify?

**Comment by lannka** [comment]
Looks good. Thanks!

**Pull request merged**
