### PR TITLE
🐛 amp-beopinion: Don't remove the iframe unexpectedly

### PR DESCRIPTION
**Pull request by bloodyowl**
Follow up: this PR fixes the first part of what this PR fixed https://github.com/ampproject/amphtml/pull/26500

### CODE REVIEW

**Comment by bloodyowl** [comment]
@calebcordry should be alright now 😊

**Comment by calebcordry** [comment]
@bloodyowl I don't think I understand the original bug. Do you think `layoutCallback` is being called when it shouldn't be? Maybe this is a bug on our side?

Could you give a test page where you are seeing this behavior? Thanks

**Comment by calebcordry** [comment]
Also has this always been a problem, or did you start to notice it after a certain date?

**Comment by bloodyowl** [comment]
@calebcordry Closing this as we've managed to fix it on our side.

The issue was that when our widget were mounted, we called `requestResize` with an initial height of `0`. That triggered the unload of the tag.

I don't remember seing that behaviour being documented anywhere, could be good if it was.

**Comment by calebcordry** [comment]
Interesting, thanks for the update. Glad you solved your problem. Do you want to continue with #26500 for the renaming, or are you planning on opening another PR?

**Pull request closed without merging**
