### PR TITLE
update document-register-element to 1.4.1

### PR DESCRIPTION
**Pull request by erwinmombay**
Closes https://github.com/ampproject/amphtml/issues/7692

See https://github.com/WebReflection/document-register-element/issues/96

### CODE REVIEW

**Comment by cramforce** [comment]
Compilation error may be relevant.

**Comment by erwinmombay** [comment]
@cramforce looking

**Comment by WebReflection** [comment]
Since I don't use transpilers and the signature is this one
```js
function installCustomElements(window, polyfill)
```

without a `polyfill = 'auto'` default, maybe that's what you should pass, since that's what's used anyway if you don't.

**Comment by WebReflection** [comment]
```
src/polyfills.js:39: ERROR - Function module$document_register_element$build$document_register_element_node.default: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
  installCustomElements(self);
  ^
src/service/extensions-impl.js:608: ERROR - Function module$document_register_element$build$document_register_element_node.default: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
  installCustomElements(childWin);
  ^
2 error(s), 0 warning(s), 91.73528627706526% typed
```

Probably this would fix all the things ?

```js
file = file.replace(
  /installCustomElements\((\w+)\)/g,
  ($0, $1) => `installCustomElements(${
    $1 == 'global' ? 'self' : $1
  }, 'auto')`
)
```

**Comment by erwinmombay** [comment]
@WebReflection thanks! apologies, had to wrap up some other PR and hadn't taken a closer look at this.

**Comment by WebReflection** [comment]
As you can see https://github.com/ampproject/amphtml/issues/7750 fixes the Travis CI issue.

Regards

**Pull request closed without merging**
