### PR TITLE
🖍  [Attachment Forms] Update the style of the attachment header text

### PR DESCRIPTION
**Pull request by coreymasanto**
In accordance with the UX mocks for page attachment forms, make the following changes:
- make the attachment title text bigger and bolder
- make the publisher domain text lighter than the attachment's title text
- move the title and domain text closer together

**Light Theme**

Before:

After:

---

**Dark Theme**
Before:

After:

---

**Desktop**
Before:

After:

---

**Mock example**

issue #35569

### CODE REVIEW

**Comment by coreymasanto** [comment]
@processprocess

**Comment by processprocess** [comment]
Looking nice! Please add a visual test that includes both title and domain text.

**Review by gmajoulet — APPROVED** [review]
Cool! deferring to @processprocess to merge :))

**Comment by coreymasanto** [comment]
> Looking nice! Please add a visual test that includes both title and domain text.

Thanks! It might be tough adding a test for the title because I don't think it's visible unless the attachment is scrolled to 100% of the screen's height. Do you think it would suffice to rely on the existing `amp-story-page-attachment.js` visual tests and the new test being added in #35798, or are you thinking of a different type of test case?

**Pull request merged**
