### PR TITLE
Switch desktop panels to 9:16 format

### PR DESCRIPTION
**Pull request by dvoytenko**
Subject to the final UX approval: https://github.com/ampproject/wg-stories/issues/28

Closes: https://github.com/ampproject/wg-stories/issues/28

### CODE REVIEW

**Comment by gmajoulet** [comment]
The format would also need to be changed for `amp-story-auto-ads` cc @calebcordry 

https://github.com/ampproject/amphtml/blob/b2a5d71eb8dc4079fd682f4d7113829fd46345cf/extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css#L95-L104

**Comment by dvoytenko** [comment]
> The format would also need to be changed for `amp-story-auto-ads` cc @calebcordry

Done and added @calebcordry to the review.

**Comment by hongwei1990** [comment]
wait. I don't think we want to change this. Can someone pause this ticket?

**Comment by newmuis** [comment]
I think this needs to wait for @hongwei1990 to approve.  I've removed myself as an approver and added her.

**Pull request closed without merging**
