### PR TITLE
New Ad Server to join AMP: AdGlare

### PR DESCRIPTION
**Pull request by adglare**
Hello,

Could you please commit these changes in order to add AdGlare? Thanks in advance! :)

/cc @lannka 
/cc @zhouyx

### CODE REVIEW

**Comment by adglare** [comment]
Hi /cc @dvoytenko  

I'm cc-ing you too for reviewing 3p/integration.js.

Thanks!

**Comment by adglare** [comment]
I guess we're there! Please let me know if you need anything else. Thanks! :)

**Comment by adglare** [comment]
Or, do I need to ask @ampproject/ads to review? I appreciate your time.

**Comment by adglare** [comment]
Hi @lannka 

Thanks for merging the commits. Am I correct that we're still waiting for @calebcordry to approve the 3p integration, even though the PR has been closed already?

**Comment by calebcordry** [comment]
@adglare it was approved and merged by @lannka. Should be in this weeks canary cut, and released to prod next week.

**Comment by adglare** [comment]
@calebcordry that's great to hear. Thanks for your time!

**Pull request merged**
