### PR TITLE
Replace canonicalUrl with ampdocUrl in Nielsen analytics

### PR DESCRIPTION
**Pull request by uniquelygeneric**
Updated Nielsen analytics to utilize ampdocUrl in query param.

### CODE REVIEW

**Comment by uniquelygeneric** [comment]
@alanorozco Could you please restart the Travis job? Thanks!

**Comment by alanorozco** [comment]
@uniquelygeneric Restarted shards. Current reviewer @calebcordry also has restart powers FYI

**Comment by calebcordry** [comment]
@uniquelygeneric the test failures are real, can you also update 
https://github.com/ampproject/amphtml/blob/b33830042bd4aaea099bed920378492228f8ee05/extensions/amp-analytics/0.1/test/vendor-requests.json#L283-L286

This should fix the broken test. Thanks!

**Comment by uniquelygeneric** [comment]
@calebcordry whoops, forgot to update there, too. Thanks!

Are we good now?

**Pull request merged**
