### PR TITLE
✨ Allow `importance` attribute on `amp-img` and SSR'ed `amp-img > img`

### PR DESCRIPTION
**Pull request by westonruter**
Currently the `importance` attribute is allowed on `noscript > img`, but it is not allowed on `amp-img > img (transformed)`. This means that this upcoming web platform feature ([Priority Hints](https://wicg.github.io/priority-hints/)) can't be experimented with in the Optimizers to see how it impacts performance. This feature is currently in [origin trial](https://www.chromestatus.com/feature/5273474901737472).

### CODE REVIEW

**Comment by westonruter** [comment]
Once this is merged, I'll open a PR for amp-toolbox-php to “bubble” up the `importance` attribute from `amp-img > noscript > img` to `amp-img[data-hero] > img`, in the same way it's [currently doing for the `loading` attribute](https://github.com/ampproject/amp-toolbox-php/blob/462b562171d3829647cab82e7ed8de4fac84a2ba/src/Optimizer/Transformer/OptimizeHeroImages.php#L559-L564).

**Review by jridgewell — APPROVED** [review]

**Review by honeybadgerdontcare — APPROVED** [review]

**Review by kristoferbaxter — APPROVED** [review]
Approving, but can we also validate that amp-img propagates the attribute correctly?

**Comment by westonruter** [comment]
> Approving, but can we also validate that amp-img propagates the attribute correctly?

I don't believe this is relevant here as the propagation (er, bubbling) would be done in an AMP Optimizer. The `importance` attribute is not being allowed here on `amp-img` but rather on the `img` that is SSR'ed.

**Comment by kristoferbaxter** [comment]
> > Approving, but can we also validate that amp-img propagates the attribute correctly?
> 
> 
> 
> I don't believe this is relevant here as the propagation (er, bubbling) would be done in an AMP Optimizer. The `importance` attribute is not being allowed here on `amp-img` but rather on the `img` that is SSR'ed.

Yes, this makes sense. For consistency purposes, a document that specifies importance on an `amp-img` should propagate it to the internal `img`.

This means caches could also apply the optimization for origins that do not SSR AMP Components.

I'm happy to make the change in a PR on Monday.

**Comment by westonruter** [comment]
Oh, I see. To add it to `amp-img` as well.

**Comment by Gregable** [comment]
@kristoferbaxter @westonruter . It looks like this PR has stalled. Is at least the validator part ready to merge?

**Comment by westonruter** [comment]
Since the merge of #37147 which added native `img` the `importance` attribute has been allowed on non-SSRed `img` elements. I've just amended the PR to then also allow `importance` on:

* `amp-img:not([i-amphtml-ssr])`
* `amp-img[i-amphtml-ssr]`
* `amp-img[i-amphtml-ssr] > img`

What then is remaining is this part from @kristoferbaxter:

> For consistency purposes, a document that specifies importance on an `amp-img` should propagate it to the internal `img`.

And that was already done in #36244.

**Review by jridgewell — APPROVED** [review]
There's still a followup to propagate the `importance` in the `` SSR code internally (and external amppackager).

**Comment by MichaelRybak** [comment]
@westonruter Hi Weston, is this ready to submit?

**Comment by westonruter** [comment]
@MichaelRybak AFAIK yes.

**Comment by twifkak** [comment]
@westonruter Do you have merge rights or need somebody else to merge?

@jridgewell The follow-ups are OK to happen after this is merged?

**Comment by westonruter** [comment]
I have merge access, yes.

**Comment by jridgewell** [comment]
Yes.

**Comment by jridgewell** [comment]
Follow up to SSR: cl/424726340

**Pull request merged**
