### PR TITLE
📖 Adds documentation of new animations

### PR DESCRIPTION
**Pull request by Enriqe**
Adds to amp-story readme the new preset animations introduced in #13910

### CODE REVIEW

**Comment by Enriqe** [comment]
> Had this been added to the validator yet? We don't want to push the documentation until it's actually possible to use the feature.

Didn't realize attribute values were also validated, woops! Will update the PR with the validation rules soon.

**Comment by Enriqe** [comment]
Validation rules are being added in #14157.

**Comment by newmuis** [comment]
Are there additional CSS rules or DOM structure that people need to keep in mind for these animations?  Or can they use it out of the box on any element? :smile:

**Comment by Enriqe** [comment]
> Are there additional CSS rules or DOM structure that people need to keep in mind for these animations? Or can they use it out of the box on any element? 😄

Zoom should work out of the box for any element since it's only scaling. The panning might need some explanation about the sizing though. But maybe it makes more sense to illustrate this in the amp-by-example article? 

Already doing some work in #1202 @sebastianbenz

**Pull request merged**
