### PR TITLE
♻️ 🏗  Update CORE to be imported as an NPM module

### PR DESCRIPTION
**Pull request by rileyajones**
When Bento is moved to its own repository there needs to be a way for it to import CORE. We plan to do this by packaging CORE as an NPM module and adding it as a requirement.

The first step towards publishing CORE is to change bundle it and change the way it is imported by the rest of the repository. This also has the upside of simplifying a later conversion to TypeScript.

It is possible to delay modifying the imports from non Bento related portions of the repository until we are ready for a TS conversion but it seems like an unnecessary step.

#36461

### CODE REVIEW

**Comment by rcebulko** [comment]
It looks like this isn't in a state to be reviewed yet; if you wouldn't mind, please ping me out of GH when it is, since GH notifications on draft PRs can be noisy

**Comment by samouri** [comment]
I'm not convinced that this is a good idea versus alternatives. For example, we could copy/paste over the subset of Core that Bento currently uses. I'm assuming this would be much less code than what is currently in src/core.

**Comment by rcebulko** [comment]
> I'm not convinced that this is a good idea versus alternatives. For example, we could copy/paste over the subset of Core that Bento currently uses. I'm assuming this would be much less code than what is currently in src/core.

I would push back here against copy-pasting code. Having an independent core package could be great, and anything added to it could be required to have higher standards of testing than runtime/component code (which can be harder to test exhaustively). More generally I think separating codebases in this way could keep us honest about not breaking things. Synchronization can be solved automatically with renovate+automerge.

**Comment by samouri** [comment]
> > I'm not convinced that this is a good idea versus alternatives. For example, we could copy/paste over the subset of Core that Bento currently uses. I'm assuming this would be much less code than what is currently in src/core.
> 
> I would push back here against copy-pasting code. Having an independent core package could be great, and anything added to it could be required to have higher standards of testing than runtime/component code (which can be harder to test exhaustively). More generally I think separating codebases in this way could keep us honest about not breaking things. Synchronization can be solved automatically with renovate+automerge.

To counter these points:

- We would only copy/paste once. Would never need to do this again.
- The Bento repo could export src/core as an npm package which could be imported by `amphtml`. I do not think this is necessary.
- A varying "standard of testing" can be enforced within the repo, no need for separate ones.
- What do you mean by honest about not breaking things?

----

We should answer a few questions to guide our decision:
- What does the venn diagram look like between classic/bento re. core usage. Do they use separate parts of it? Is there significant overlap?
- Do we actively change Core to service classic AMP or do we only make new changes for Bento. Do any of these changes apply to both codebases?

---

I want us to prioritize the long-term health of Bento over the short-term benefit of easing classic AMP development.

**Pull request closed without merging**
