### PR TITLE
Proposal: disallow document.head in preference to ampdoc

### PR DESCRIPTION
**Pull request by dvoytenko**
Partial for #25419

Alternative to #25423 is to disallow most of `Document` APIs and eventually disallow `window.document` property as well. Interestingly, this does not catch all issues I expected. In particular, [this head resolution](https://github.com/ampproject/amphtml/blob/1b2bb3a2c9d2e49c349a15b86c1d84470a3fb7a3/src/service/action-impl.js#L803) has not been caught.

Also, combination of both could be good. Compiler for most and multi-tests for the trickiest cases.

Unfortunately, this does not catch any destructuring assignment cases. See google/closure-compiler#3500 for more details.

### CODE REVIEW

**Comment by lannka** [comment]
This looks good.

People can use `describes.ampdocs` only when necessary.

**Comment by dvoytenko** [comment]
Unfortunately, this does not catch any destructuring assignment cases. See https://github.com/google/closure-compiler/issues/3500 for more details.

**Comment by lannka** [comment]
Is this PR still needed?

**Comment by dvoytenko** [comment]
> Is this PR still needed?

it was passed to @kevinkimball

**Comment by lannka** [comment]
Closing it now. @kevinkimball  you can always patch this PR to your own branch once you started work on this.

**Pull request closed without merging**
