### PR TITLE
Add prefetch to config

### PR DESCRIPTION
**Pull request by approslab**

### CODE REVIEW

**Comment by mrjoro** [comment]
@powerivq is this ready to merge in?

/cc @ampproject/wg-ads

**Comment by powerivq** [comment]
@approslab hey! I think this PR is good. Would you mind rebase it against latest master and push?

**Comment by approslab** [comment]
> @approslab hey! I think this PR is good. Would you mind rebase it against latest master and push?

@powerivq done

**Comment by powerivq** [comment]
@approslab sorry! look like this failure has been fixed on master. Can you rebase till tests pass? Thx.

**Comment by powerivq** [comment]
Fliping off and on to trigger rebuilding.

**Pull request merged**
