### PR TITLE
[gulp-amphtml-validator] update dependency to amphtml-validator

### PR DESCRIPTION
**Pull request by sebastianbenz**

### CODE REVIEW

**Comment by mrjoro** [comment]
@sebastianbenz @Gregable is this PR still active?

**Comment by mrjoro** [comment]
@Gregable or @sebastianbenz is this ready to merge?

**Comment by sebastianbenz** [comment]
Yes. I haven't got merge rights though.

**Comment by Gregable** [comment]
It looks like travis is unhappy?

**Comment by sebastianbenz** [comment]
The failure seems unrelated //cc @rsimha:

```
dist-bundle-size.js: Running gulp bundle-size --on_skipped_build...
[07:27:11] Using gulpfile ~/build/ampproject/amphtml/gulpfile.js
[07:27:11] Starting 'bundle-size'...
[07:27:12] Could not report a skipped pull request
[07:27:12] Error: 404 Not Found: a3cbbfca8bba6e6e1bb4265ab84bf6c19f6413fe not in database
[07:27:12] Finished 'bundle-size' after 64 ms
The command "node build-system/pr-check/dist-bundle-size.js" exited with 1.
```

**Comment by rsimha** [comment]
@danielrozenberg can comment on why this failed the bundle-size check.

**Comment by danielrozenberg** [comment]
Can you try rebasing this PR on master? I'm having some trouble accessing the bundle-size logs at the moment, but this issue usually stems from a hiccup in GitHub reporting a new PR to that bot, which is almost always solved by a rebase

**Comment by sebastianbenz** [comment]
@danielrozenberg done

**Pull request merged**
