### PR TITLE
amp-script: Update Vue.js TodoMVC example

### PR DESCRIPTION
**Pull request by niutech**
Add `sandbox="allow-forms"` to `<amp-script>`. The working demo is [here](https://repl.it/repls/BuoyantBarrenThing).

### CODE REVIEW

**Comment by Antoinebr** [comment]
@choumx can you confirm the custom attributes in that demo will be valid after the official release of amp-script ?

image

Otherwise, if this example will never be valid better to remove it from the official example folder to avoid confusion.

**Comment by choumx** [comment]
Oh wow, thanks for pointing that out. Would you mind filing an issue to allow custom Vue attributes in amp-script's sanitizer?

**Comment by ZhuangWeiMian** [comment]
This issue hasn't been solved, right? I meet the same question

**Comment by choumx** [comment]
@ZhuangWeiMian Not yet, filed #25310 for this.

**Pull request merged**
