### PR TITLE
An additional required file was added for Rambler&Co ad network

### PR DESCRIPTION
**Pull request by CrazySquirrel**
An additional required js file was added to amp-ad tag type capirs. It is necessary for some ad types in Rambler&Co ad network.

### CODE REVIEW

**Comment by zhouyx** [comment]
One question. What's the cost of `window.document.write`. If the overhead is expensive, maybe we should consider accepting an array of urls to write?

**Comment by CrazySquirrel** [comment]
I can load the required scripts asynchronously using loadScript method. I think it will be better.

**Comment by zhouyx** [comment]
LGTM

**Comment by zhouyx** [comment]
@CrazySquirrel Thanks for the Pull Request. Merged.

**Pull request merged**
