### PR TITLE
Add support for SlimCut Media ads in amp-ad

### PR DESCRIPTION
**Pull request by m1ck43l**
Hello,

I've followed the guidelines and examples to add support for SlimCut Media ads into amp-ad.

- No error with gulp lint
- Ran & passed tests "test-ads-config.js,test-integration.js"
- Tested locally and on heroku (http://ampscm.herokuapp.com/examples/ads.amp.max.html?type=slimcutmedia)
- Signed Google CLA 

Please review this pull request, thanks!

Implements #7254

### CODE REVIEW

**Comment by m1ck43l** [comment]
Example was limited to the heroku test site, sorry for that.
The example is now running locally.

Thanks

**Comment by lannka** [comment]
@m1ck43l the example works now. But I see a noticeable blank time between the loading indicator and the ad display. Could you confirm you're calling render-start API at the right time?

**Comment by m1ck43l** [comment]
@lannka We plan to add a loading screen to avoid the blank time. Do you need it to be implemented right for the PR? Thanks

**Comment by m1ck43l** [comment]
@lannka We've added the loading screen. The white screen will disappear once we have the ad. Thanks

**Comment by lannka** [comment]
@m1ck43l sorry for the late reply. AMP runtime already provided a loading indicator. Are you able to call render-start at the time you hide your loading screen? If not, I'd prefer no 2nd loading indicator.

**Comment by m1ck43l** [comment]
@lannka We've removed the second loading indicator. Should be good now.

**Pull request merged**
