### PR TITLE
🚮 Remove RRule support from amp-date-picker

### PR DESCRIPTION
**Pull request by jridgewell**
It doesn't work. The RRule code isn't included in the amp-date-picker bundle, so it can never actually be used.

Removing the code allows me to unblock https://github.com/ampproject/amphtml/pull/24284. We can revert this PR later _and_ fix the RRule import at the same time.

Fixes https://github.com/ampproject/amphtml/issues/24297

### CODE REVIEW

**Comment by kristoferbaxter** [comment]
Did we look to see what the usage of this feature was?

**Comment by jridgewell** [comment]
No. I'd hope it's low, because it literally does not work at all.

**Comment by kristoferbaxter** [comment]
@nainar – Do we have a good idea for usage of this feature?

**Comment by jridgewell** [comment]
@kristoferbaxter: a gajillion pages could use the the feature, and it still wouldn't matter:

```js
function ka(a) {
  try {
    return rrulestr$$module$node_modules$rrule$dist$esm$src$rrulestr(a);
  } catch (b) {
    return null;
  }
}
```

`rrulestr$$module$node_modules$rrule$dist$esm$src$rrulestr` is not defined in the [file](https://cdn.ampproject.org/v0/amp-date-picker-0.1.js), because `import {rrulestr} from 'rrule/dist/esm/src/index.js'` has never worked.

The feature is dead, and it's blocking me from merging the lint rule to prevent more bugs like this. We can fix it later.

**Comment by nainar** [comment]
Since no one can use this feature this change should be good to land. 

However, we should file an issue to immediately enable this for amp-date-picker. @caroqliu

**Comment by nainar** [comment]
Also wrote a regex to see if anyone is using it - no one is. So consider this a go ahead.

**Comment by rsimha** [comment]
Of the [dozen](https://github.com/ampproject/amphtml/pulls?utf8=%E2%9C%93&q=is%3Apr+rrule+) or so `amphtml` PRs related to `rrule`, more than half were merely looking for a way to make the code work. I support removing it until we can find a reliable way of using the module with our codebase and compilation toolchain.

**Comment by wassgha** [comment]
So, this is related to #24682 (the reason highlighted / blocked dates were not working is indeed `rrules`). However the usage for that is pretty high although it's already broken.

**Pull request merged**
