### PR TITLE
Add common case variant of x-ua-compatible in validator

### PR DESCRIPTION
**Pull request by yandavid**

### CODE REVIEW

**Comment by cramforce** [comment]
LGTM

**Comment by yandavid** [comment]
For some context, html5-boilerplate has the lowercase version of `x-ua-compatible` and I am hoping amp will consider it valid: https://github.com/h5bp/html5-boilerplate/blob/master/dist/index.html#L5

**Comment by cramforce** [comment]
This should definitely go in!!
@Gregable @powdercloud  Is there a better way to make the matching case insensitive?

**Comment by powdercloud** [comment]
Instead of duplicating the tagspec, you could do value_regex_casei: "^X-UA-Compatible$".
Advantage is it's easier to read; disadvantage is it's less efficient.
We should support value_casei, that'll be best but take a little while to have. So maybe the value_regex_casei is best for now?

**Comment by Gregable** [comment]
Chatted with @powdercloud, the regex will solve this problem but cause others. It's a little hard to explain in the comment thread, but it has to do with how we choose which tagspec to use for generating error messages. Changing this to a regexp will cause worse error messages in the case of actual errors.

Let's commit this change for now, and we may be able to improve the matching of tagspecs to error messages later.

**Pull request merged**
