### PR TITLE
✨ Adds Adnuntius support to amp-ad.

### PR DESCRIPTION
**Pull request by antosarho**
Provides the functionality to allow Adnuntius ads to be served via amp-ad.

### CODE REVIEW

**Review by powerivq — APPROVED** [review]

**Review by lannka — APPROVED** [review]

**Comment by powerivq** [comment]
Adding @Gregable for validator owner approval

**Comment by honeybadgerdontcare** [comment]
Sending to @twifkak for validator since he's on rotation for this instead of Greg.

**Comment by powerivq** [comment]
great thanks. @honeybadgerdontcare

**Review by twifkak — APPROVED** [review]
Validator changes LGTM. I'll merge since we have all needed approvals and no pending comments.

**Pull request merged**
