### PR TITLE
Add a component

### PR DESCRIPTION
**Pull request by 340236524**
Hide too long articles, click the button to display more content.

# Instructions:

- Pick a meaningful title for your pull request. (Use sentence case.)
  - Prefix the title with an emoji to identify what is being done. (Copy-paste from the list below.)
  - Do not overuse punctuation in the title (like `(chore):`).
  - If it is helpful, use a simple prefix (like `ProjectX: Implement some feature`).
- Enter a succinct description that says why the PR is necessary, and what it does.
  - Mention the GitHub issue that is being addressed by the pull request.
  - The keywords `Fixes`, `Closes`, or `Resolves` followed the issue number will automatically close the issue.

# Example of a good description:

- Implements aspect X
- Leaves out feature Y because of A
- Improves performance by B
- Improves accessibility by C

# Emojis for categorizing pull requests:

✨ New feature (`:sparkles:`)  
🐛 Bug fix (`:bug:`)  
🔥 P0 fix (`:fire:`)  
✅ Tests (`:white_check_mark:`)  
🚀 Performance improvements (`:rocket:`)  
🖍 CSS / Styling (`:crayon:`)  
♿ Accessibility (`:wheelchair:`)  
🌐 Internationalization (`:globe_with_meridians:`)  
📖 Documentation (`:book:`)  
🏗 Infrastructure / Tooling / Builds / CI (`:building_construction:`)  
⏪ Reverting a previous change (`:rewind:`)  
♻️ Refactoring (like moving around code w/o any changes) (`:recycle:`)  
🚮 Deleting code (`:put_litter_in_its_place:`)

### CODE REVIEW

**Comment by aghassemi** [comment]
(opening this and closing https://github.com/ampproject/amphtml/pull/15830 instead)

**Comment by 340236524** [comment]
I want this effect.
image
`linkeddb` It's the domain name of our company,Convenience recognition.
Our website has many effects, and amp components can not meet our needs, so I am trying to contribute some component effects that are not yet available.

**Comment by aghassemi** [comment]
Thanks for the details @340236524, it is already possible in AMP in various ways such as using `amp-bind` or `amp-accordion` or `hide(), show()` actions. 

@ericlindley-g Thoughts on having a dedicated `amp-showmore` component that simplifies creation of such UIs? Alternative is ABE samples for various UXs of `show more` using existing primitives.

**Comment by ericlindley-g** [comment]
There's a show-more example in ABE here: https://ampbyexample.com/components/amp-accordion/  @340236524 , is there a reason you'd like a dedicated component versus using the approach outlined in AMP by Example with amp-accordion?

**Comment by aghassemi** [comment]
@ericlindley-g That one is a bit different, button stays on top, initially does not show parts of the text. It is certainly possible to do a show more/less as pictured above (definitely with bind, maybe with accordion as well with some more CSS tricks)

**Comment by ericlindley-g** [comment]
Ah, I see now — I didn't notice some of the details on first glance. The tradeoff here seems to be an easily packaged feature v. maintainability and ease of use for developers (that is, having another component to sift through to find what they need).

@aghassemi , what's the cost of maintainability here? 
I'm not too worried at this point about having another component in the list — though I wonder if a good way to do this would be to have a higher-level component that would include amp-accordion's features and this component's features available through configuration

**Comment by aghassemi** [comment]
@ericlindley-g yeah maybe we can build this behaviour on top of accordion instead of a new component.

Anyway, for the short-term: @340236524 give amp-accordion and/or amp-bind a try to build the experience you need. Let us know if you ran into issues and we can provide a sample.

**Comment by 340236524** [comment]
My boss told me to do this, so I was very upset. I hope AMP can increase or introduce this effect.

**Comment by aghassemi** [comment]
@340236524 I am sorry to hear that. I created a sample for you that does what you need using `amp-bind`.  Hope this helps: https://codepen.io/aghassemi/pen/qKyJQg?editors=1000 (CSS is opinionated but the concept should apply to similar UIs)

@340236524 There are many interactions that are possible in AMP that do not have a dedicated component. If you have questions, please feel free to ask the community on Stackoverflow or Slack. See https://www.ampproject.org/support/developer/get_support for list of places we provide developer support.

**Comment by 340236524** [comment]
I have some other needs，Can I ask you directly?

**Comment by 340236524** [comment]
Thank you for helping me.I have some other needs，Can I ask you directly?

**Comment by aghassemi** [comment]
@340236524 Please start by asking on the Stack channel `#using-amp`, if you did not get an answer from the community, feel free to ping me on Slack (@aghassemi is my handle)

**Pull request closed without merging**
