### PR TITLE
Add finative support to amp-ad

### PR DESCRIPTION
**Pull request by SeedingAllianceTech**
add support to amp-ad for the finative type.

### CODE REVIEW

**Review by powerivq — APPROVED** [review]

**Review by powerivq — CHANGES_REQUESTED** [review]
Plz fix the check failure.

**Comment by sag-marbie** [comment]
> Plz fix the check failure.

@powerivq What exactly can we do here?

**Comment by SeedingAllianceTech** [comment]
> Plz fix the check failure.

@powerivq What exactly can we do here?

**Comment by powerivq** [comment]
See error message here https://app.circleci.com/pipelines/github/ampproject/amphtml/2429/workflows/e382bcd1-6969-4617-8703-50053a97d417/jobs/26859/parallel-runs/0/steps/0-107

In 3p/integration.js, you imported but did not register your network.

**Review by powerivq — APPROVED** [review]

**Pull request merged**
