### PR TITLE
🐛  Ads was missing 'height' attribute

### PR DESCRIPTION
**Pull request by liquidlx**
changed the 'layout' attribute value to 'fluid'.
added 'height' attribute.

### CODE REVIEW

**Review by lannka — APPROVED** [review]

**Comment by liquidlx** [comment]
Hey @lannka, can you check the visual changes? It needs approval too. Thanks˜

**Comment by lannka** [comment]
restarted failing tests.

**Review by rsimha — APPROVED** [review]

**Review by lannka — APPROVED** [review]

**Comment by rsimha** [comment]
@lannka @liquidlx We recently changed our CLA and Travis checks. You can refresh them by adding a new commit, or by closing and reopening the PR. After that, you should be able to merge normally.

**Comment by liquidlx** [comment]
Hey, @lannka @rsimha the bundle size test has failed and I need approval for the visual changes. Thanks!

**Review by rsimha — APPROVED** [review]

**Pull request merged**
