### PR TITLE
✅ Additional carousel v2 end to end tests

### PR DESCRIPTION
**Pull request by sparhami**
Note: This needs changes from #20502 before merging.

- Reduce minimum auto advance interval to 1 second, matching carousel v1
- Support amp-bind for carousel v2
  * Still need to add validation rules
- Add tests for auto advance
- Add tests for slide grouping
- Add tests for a vertical carousel
- Add tests for non-looping carousels
- Add test for amp-bind with responsive attributes

### CODE REVIEW

**Comment by estherkim** [comment]
@sparhami Do these e2e tests pass consistently? I'd like to add them to our CI build but I'm experiencing test timeouts in headless mode, ex. https://travis-ci.org/ampproject/amphtml/jobs/486016310#L777-L807

**Comment by cvializ** [comment]
The `UnhandledPromiseRejectionWarning: NoSuchSessionError: invalid session id` usually means Selenium has cleaned up the element handles' reference to the web driver. I think to find the exact error location we might need to improve the error handling.

**Comment by estherkim** [comment]
@cvializ The `NoSuchSessionError` is because we're trying to do `this.driver_quit()` in the teardown for a session that was already closed. I think it's unrelated to the timeouts errors but I'll try to fix it to clarify.

**Comment by sparhami** [comment]
> @sparhami Do these e2e tests pass consistently? I'd like to add them to our CI build but I'm experiencing test timeouts in headless mode, ex. https://travis-ci.org/ampproject/amphtml/jobs/486016310#L777-L807

The test files use some non-local images, so I could see that as being a problem since I wait for them to load in some of the tests. I'll switch those over to use local images. I haven't run them in headless mode yet, so not sure if there is a problem there.

Not sure what is causing the timeouts, but I made the `.to.include` expect to throw the error message if it times out. I have tried changing the other assertions to use the same pattern as `include`, but have run into some issues. Can take another look at that since it should make figuring out why they are timing out easier.

**Comment by estherkim** [comment]
Honing in on `AMP carousel mixed length slides > no snap` test, it's timing out when trying to locate the slide elements. When I turn headless off, I don't see the slides rendering and there's a 404 error trying to load `dist\v0\amp-carousel-0.2.max.js` but I don't follow how the test page tries to load this.

I'll look at improving debugging by catching and logging our unresolved promises.

**Comment by sparhami** [comment]
> Honing in on `AMP carousel mixed length slides > no snap` test, it's timing out when trying to locate the slide elements. When I turn headless off, I don't see the slides rendering and there's a 404 error trying to load `dist\v0\amp-carousel-0.2.max.js` but I don't follow how the test page tries to load this.
> 
> I'll look at improving debugging by catching and logging our unresolved promises.

One thing I have noticed is that if you do `gulp e2e`, but already have an existing gulp running which did not build the necessary extension (e.g. `gulp --extensions="amp-fit-text"` when you need amp-carousel) , the tests will start running against the existing gulp server, but fail because the extension you needed was never built. It is also pretty confusing when you have an older, already built copy of an extension you need (i.e. you built it at some point, but your latest server is not building it), then you try to run the test and things don't work as expected.

**Comment by estherkim** [comment]
Ah I see, thanks for the info! I'll change `gulp e2e` to build the runtime & all extensions by default, with a `--nobuild` option to skip it.

**Pull request merged**
