### PR TITLE
Introduce video-ad-start/end event

### LINKED ISSUE #13753: expose AD_START and AD_END events in video analytics
1- trigger analytics events for them in video-manager
2- document the new events in video analytics documentation.

/cc @shawnbuso @jasti

### PR DESCRIPTION
**Pull request by zhouyx**
Closes #13753

### CODE REVIEW

**Comment by cvializ** [comment]
Should there be tests for this in `extensions/amp-ima-video/0.1/test/test-amp-ima-video.js`?

**Comment by zhouyx** [comment]
Thank you for the quick review! This is not a feature that's specific to ima video. 
I thought about adding test coverage to `test-video-manager.js` but doesn't seem to find test coverage for other analytics event. Please let me know what's a good place to add generic video analytics test coverage. Thanks.

**Comment by cvializ** [comment]
general video tests should go in video manager, and if possible it should be added to the individual video elements that support it

**Comment by zhouyx** [comment]
@rsimha I noticed one more issue with `gulp watch` while testing the video components. 

`video-manager-impl.js` lives under `src/service` folder. Which means we are not monitoring the file to rebuild the component. However the file is also not built to `v0.js`. 
When I was testing the change locally, a change to `video-manager-impl.js` won't be picked up, and I had to restart the `gulp build` myself multiple times. 

@cvializ wonder how did you test the change to the above file previous. and @rsimha for ideas to fix this. Thanks.

**Comment by rsimha** [comment]
> @rsimha I noticed one more issue with `gulp watch` while testing the video components.
> 
> `video-manager-impl.js` lives under `src/service` folder. Which means we are not monitoring the file to rebuild the component. However the file is also not built to `v0.js`.
> When I was testing the change locally, a change to `video-manager-impl.js` won't be picked up, and I had to restart the `gulp build` myself multiple times.

Currently, we pick up file-level changes for core runtime code, and directory level changes for extensions. This file appears to be violating both conventions. Is it reasonable to move `video-manager-impl.js` into its extension directory?

https://github.com/ampproject/amphtml/blob/27b46b9c8c0fb3711a00376668d808f413d798ed/build-system/tasks/helpers.js#L447-L450
https://github.com/ampproject/amphtml/blob/27b46b9c8c0fb3711a00376668d808f413d798ed/build-system/tasks/extension-helpers.js#L361-L375

**Comment by zhouyx** [comment]
Talked with @cvializ offline. Decided we will not be adding test for 3p code within iframe.

**Comment by zhouyx** [comment]
@rsimha I believe we want to keep the file there because it's shared across all the video components. That those video components will install the video manager. @cvializ to keep me honest. 

>If not, is there a good way to associate an extension with all the files that it uses?

I'm thinking about the same. One easy workaround is to hard code the files when the component is identified as a video component.

**Pull request merged**
