### PR TITLE
Add ValueCommerce support for amp-ad

### LINKED ISSUE #7080: Intent To Implement: ValueCommerce support for amp-ads
I want to contribute to add support to ValueCommerce platform https://www.valuecommerce.ne.jp/en/

I sent pull request  https://github.com/ampproject/amphtml/pull/6962 from MichinaoShimizu/amphtml branch. #6962

### PR DESCRIPTION
**Pull request by MichinaoShimizu**
we want to add ValueCommerce into the supported ad network for amp-ad.

We have signed Google Corporate CLA.

Corporation name: ValueCommerce Co., Ltd.

Thank you very much !

Fixes #7080.

### CODE REVIEW

**Comment by jridgewell** [comment]
Ping @lannka, @zhouyx

**Comment by lannka** [comment]
@MichinaoShimizu did you get the example working locally? 

I got this error:
screenshot from 2017-01-18 12 50 47

Take a look at our [guideline](https://github.com/ampproject/amphtml/blob/master/ads/README.md#developer-guidelines-for-a-pull-request) if you don't know how to run locally.

**Comment by lannka** [comment]
no worry, take your time :-)

**Comment by iwaiwaiwa012g** [comment]
@lannka Our server is ready now again. Could you resume the checking?

**Comment by lannka** [comment]
@iwaiwaiwa012g it works now.
However, I'm seeing a noticeable blank period between the disappear of loading indicator and display of ad. Can you confirm you code is calling the render-start API at the right time?

**Comment by iwaiwaiwa012g** [comment]
@lannka Thank you very much. It seemed that we had render-start API implemented correctly. We were missing preconnect in _config.js, though. Now it is included in the pull request as well. Could you take a look once again?

**Pull request merged**
