### PR TITLE
Auto advance from audio on story cover page.

### PR DESCRIPTION
**Pull request by gmajoulet**
Fixing auto advance from audio on story cover page.

The page advancement class was listening for progress/ended events on the original `audio` element, not the one replaced by the pool. Waiting until the elements are registered (and swapped) fixes the race condition.

Partial for #27291

### CODE REVIEW

**Comment by newmuis** [comment]
I'm not sure I get this... Isn't this basically undoing the promise?  Now, only the first caller of `registerAllMedia` will wait for it to complete, right?  Won't that cause more race conditions?

**Comment by gmajoulet** [comment]
> Now, only the first caller of registerAllMedia will wait for it to complete, right?

Right! Currently we don't wait for `registerAllMedia` to complete at all, which was causing the bug :(
Only starting the advancement once the media are registered fixes all advancement related race conditions. Videos were working around it by resetting the video element and using the video interface rather than a hard reference on the videoEl, but audio still had the bug.

We only need to call `registerAllMedia` once though, and calling it multiple times is a no-op, but just in case I added an early return. I'm okay with removing it though, I might be overly cautious here. (["If the media element is already registered, this is a no-op."](https://github.com/ampproject/amphtml/blob/2d76d6ff74b046d3cc268be6bcaf327bde5ec912/extensions/amp-story/1.0/media-pool.js#L723-L724))

**Comment by newmuis** [comment]
I think I was worried about the case where the second call to the function happens before the promise is resolved (although unlikely).  Should we store the promise and always return it?  Or, what's the risk?

**Comment by gmajoulet** [comment]
You're right, it's super hard to repro but I managed to do it once (!). That's a much better design pattern anyway.

PTAL

**Pull request merged**
