### PR TITLE
Update callout-vendors.js

### PR DESCRIPTION
**Pull request by shreyanschopra**
-Added andbeyond RTC request for header bidding

✨ New feature

### CODE REVIEW

**Review by shreyanschopra — COMMENTED** [review]
formatting changes

**Review by shreyanschopra — COMMENTED** [review]
update

**Review by calebcordry — APPROVED** [review]
Thanks for contributing! Could you edit the PR description please?

**Comment by shreyanschopra** [comment]
Bidder Andbeyond added to support RTC.
This PR request 3 files have been changed and documentation for same is also added with name of bidder Andbeyond

**Comment by shreyanschopra** [comment]
-Added Andbeyond RTC request for header bidding
-Added documentation for same as well with mention of bidder Andbeyond

✨ New feature/partner added
     Documentation

**Comment by calebcordry** [comment]
looks like you have a couple formatting errors in the md files. You can expose these locally using `gulp prettify`. Let me know if you have any questions.

**Comment by shreyanschopra** [comment]
Where do you see .Which MD file .I just added 1 name 'Andbeyond' and nothing else and visually all looks ok.Please suggest
rtc-publisher-implementation-guide.md or rtc-documentation.md where you see errors

**Comment by shreyanschopra** [comment]
Please ignore.I fixed all formatting errors.Kindly please merge the same .Thanks

**Comment by shreyanschopra** [comment]
Thank you but I dont see on RTC its getting called .Does the url on RTC take time to reflect .When just using the vendor name the url is not getting called.Please advise

**Comment by calebcordry** [comment]
@shreyanschopra how are you testing? You should be able to test now by opting into our nightly version at https://cdn.ampproject.org/experiments.html the changes will not hit prod for a couple weeks. You can find more information about our releases at https://amp.dev/documentation/guides-and-tutorials/learn/spec/release-schedule/

**Pull request merged**
