### PR TITLE
🖍amp-image-slider : change cursor to semantic cursor

### PR DESCRIPTION
**Pull request by techhtml**
Related Issues: #18056

* now `amp-image-slider` using default cursor.
* So I changed the cursor to `col-resize`.

PTAL :)

### CODE REVIEW

**Comment by nainar** [comment]
Sending to @cathyxz for review. Thank you for sending this through!

**Comment by techhtml** [comment]
Some CI Issue happens at another point.

**Comment by techhtml** [comment]
retest this please

**Comment by cathyxz** [comment]
The CI tests are flakes and not related to this PR--I've just restarted them. 

What @sparhami meant in the issue description is that we should probably add a little bit of padding to the slider bar so that dragging it is differentiated from the click-to-move-slider-bar experience. It's possible that `cursor: grab` would look better for that, but it depends on how `<amp-image-slider>` treats grabbing the slider bar vs clicking.

**Comment by cathyxz** [comment]
Hmm I just checked, and `<amp-image-slider>` doesn't actually leave a space for grabbing the slider bar--click drag anywhere also just results in the same experience. So I think this is actually fine.

**Comment by kevinkassimo** [comment]
@cathyxz there isn't, otherwise we might want to add an extra element with defined width simply for the hovering cursor.

**Comment by sparhami** [comment]
> @cathyxz there isn't, otherwise we might want to add an extra element with defined width simply for the hovering cursor.

Yeah, I think the right behavior would be to have an element just to give the affordance for dragging (so it does not do anything other than show the cursor), even though you could really click and drag anywhere.

I don't think we want the `col-resize` to show up on the whole element, only where the dragging bar should be. We should make the fake dragging bar a bit wider then the actual bar (which is only a couple of pixels) so that it has a larger area for the mouse to enter.

**Comment by techhtml** [comment]
I don't add DOM, I using exist bar and extend area.

**Comment by cathyxz** [comment]
Thank you @techhtml !

**Pull request merged**
