### PR TITLE
Widespace_amp_demography_data passing demo params as optional argumen…

### PR DESCRIPTION
**Pull request by vgrigory**
Added demographic data support.

Usage example:

```
<amp-ad width="300" height="50"
  type="widespace"
  data-sid="93f1a996-52f5-46b4-8dc8-ccd8886a8fbf"
  layout="responsive"

  data-demo-gender="F"
  data-demo-country="SE"
  data-demo-region="W1U 8EW"
  data-demo-city="Stockholm"
  data-demo-yob="1981"
>
</amp-ad>
```

### CODE REVIEW

**Comment by mizmaar3** [comment]
LGTM

**Comment by zhouyx** [comment]
@vgrigory Please update your documentation to reflect the change.

**Comment by jonasmattsson1** [comment]
I signed it!

**Comment by zhouyx** [comment]
duplicate of #10961, close.

**Pull request closed without merging**
