### PR TITLE
Revert #22812

### PR DESCRIPTION
**Pull request by lannka**
The PR caused side effect on some reporting due to the new "nextTick" behavior in navTiming macro.

/cc @jeffkaufman

### CODE REVIEW

**Comment by zhouyx** [comment]
Revert #22812 to fix #23071 when we are trying to find the root cause.

**Comment by sparhami** [comment]
When cherry-picking this onto production, I ran into a merge conflict. While easy enough to resolve, it does make me concerned that there have been changes to the files since.

How extensively has this been tested on top of the existing production build?

**Comment by lannka** [comment]
@sparhami I got conflict only in test files. Did you get something else?

**Comment by zhouyx** [comment]
@sparhami Can we cherrypick the change to canary first. And only cherrypick to prod once we've verified the fix in inabox RC.

**Comment by sparhami** [comment]
> @sparhami I got conflict only in test files. Did you get something else?

I just want to make sure there aren't any other potentially conflicting changes. The lack of a merge conflict in the non-test files does not guarantee this. Since the original issue wasn't covered by a test, relying on tests seems to not be sufficient. For example, a hypothetical PR submitted after the PR that is being rolled back, that depends on it could run into issues once we rollback.

**Comment by sparhami** [comment]
> @sparhami Can we cherrypick the change to canary first. And only cherrypick to prod once we've verified the fix in inabox RC.

It seems like there might be another cherry-pick request for canary. I'm currently waiting to see if that will happen to combine the two before doing a canary cherry-pick.

**Comment by zhouyx** [comment]
> It seems like there might be another cherry-pick request for canary. I'm currently waiting to see if that will happen to combine the two before doing a canary cherry-pick.

Sounds good. FYI: While the change is in prod already, but it's not affecting ampdoc. The change is still in inabox canary, and we need the canary cherry-pick mainly for inabox RC.

**Comment by sparhami** [comment]
Looks like a test is failing when cherry picking on top of production, in single pass, local tests and sauce lab tests:

https://travis-ci.org/ampproject/amphtml/builds/551509527

```
DESCRIBE => amp-analytics
  DESCRIBE => basic pageview
    DESCRIBE =>  
      IT => should send request
        ✗ Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

This seems to fail every time I try it locally.

Here is the branch with the cherry pick:
https://github.com/ampproject/amphtml/tree/amp-release-2019-06-27-prod

Here is the cherry picked commit on top of prod: https://github.com/ampproject/amphtml/commit/d0eb22b1576071106e23e0f7fbb7e1a843aa356c

The changes should be the same as this PR.

@lannka @zhouyx Any ideas?

**Comment by zhouyx** [comment]
That's weird. Let me try trying it locally

**Comment by zhouyx** [comment]
Hello @sparhami found the reason. 
It's because of invalid JSON 😢
https://github.com/ampproject/amphtml/blob/d0eb22b1576071106e23e0f7fbb7e1a843aa356c/test/integration/test-amp-analytics.js#L49
unexpected comma when we resolve merge conflict.

**Pull request merged**
