### PR TITLE
✨ RevContent new ad code support

### PR DESCRIPTION
**Pull request by oste**
This PR adds support for a new ad code that Revcontent would like to start using within our AMP widgets.

### CODE REVIEW

**Comment by oste** [comment]
@lannka can you provide an ETA on when this might be reviewed/merged? We would like to start testing our new Javascript as soon as possible. Thanks for the heads up!

**Comment by lannka** [comment]
@oste sorry for the delay. you will want to follow the instructions, there are more files need to be changed. https://github.com/ampproject/amphtml/blob/master/ads/README.md#developer-guidelines-for-a-pull-request

**Comment by oste** [comment]
@lannka we are already integrated. This is just so we can have 2 versions of our Javascript. I don't think there are any further changes needed. Can you let me know specifically what you are looking for?

**Comment by oste** [comment]
thanks @lannka for merging. I am pretty sure that I am still seeing the old amp code. I am getting this error 
`log.js:360 Error: Missing attribute for revcontent: wrapper.​​​`

Is there a process for building these changes and getting it live? 

Thanks for the info!

**Comment by lannka** [comment]
It will be in Canary build tmr. and prod next Tuesday. Check our releases here: https://github.com/ampproject/amphtml/releases

**Pull request merged**
