### PR TITLE
babel plugins: remove array destructure since we now allow iterator

### PR DESCRIPTION
**Pull request by samouri**
@jridgewell: lmk if I got this incorrect

### CODE REVIEW

**Comment by samouri** [comment]
🏓  @jridgewell

**Comment by jridgewell** [comment]
I think @rcebulko is superseding this.

**Comment by rcebulko** [comment]
@jridgewell @samouri I got some .eslintrc rules, but not all the plugins. This PR is still worth submitting separately IMO

**Comment by rcebulko** [comment]
Update: cherry-picked these commits into #34282

**Pull request closed without merging**
