### PR TITLE
amp-iframe: allow  attribute

### LINKED ISSUE #11541: FR: amp-iframe allow="geolocation"
## What's the issue?

Currently it's possible to use geolocation within an `amp-iframe`. However, this will soon stop working on cross-origin iframes (i.e. every `amp-iframe`) as per: https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes

This page outlines the solution for regular iframes: 
`<iframe src="https://example.com" allow="geolocation"> </iframe>`

It seems like this would be an easy fix for `amp-iframe`

**Feature request:** 
Support `allow="geolocation"` in `amp-iframe`

### LINKED ISSUE #11937: amp-iframe allow="microphone"
## What's the issue?

There is no `allow="microphone"` option for `amp-iframe`, yet it is going to be a necessary argument to the `iframe` itself soon:

> [Deprecation] getUserMedia (microphone) usage in cross-origin iframes is deprecated and will be disabled in M64, around January 2018. To continue to use this feature, it must be enabled by the embedding document using Feature Policy, e.g. <iframe allow="microphone" ...>. See https://goo.gl/EuHzyv for more details.

## How do we reproduce the issue?

1. access www.accordersaguitare.com with Chrome
2. open the Console and see the message

## What browsers are affected?

Firefox doesn't warn about this. Safari doesn't even support `iframe allow="microphone"` yet, see: https://bugs.webkit.org/show_bug.cgi?id=167430

## Which AMP version is affected?

1508896929494

### LINKED ISSUE #12282: amp-iframe allow="vr"
## What's the issue?

amp validator complains about allow="vr" 

> The attribute 'allow' in tag 'amp-iframe' is set to the invalid value 'vr'

## How do we reproduce the issue?

1. Add allow="vr" to an amp-iframe

## What browsers are affected?

Chrome 62+

## Which AMP version is affected?
1510956201635

### PR DESCRIPTION
**Pull request by aghassemi**
Closes #11937, closes #11541, closes #12282

The syntax for `allow` recently changed and is fairly complicated https://github.com/WICG/feature-policy/issues/78 I suggest propagating as is without validating the value.

### CODE REVIEW

**Comment by dvoytenko** [comment]
Uhh. Kind of scary. Is there a top-level constraint on these? I.e. can the top-level embedder constraint which of these are truly allowed?

**Comment by aghassemi** [comment]
I hope so! At least that's how `allowpayments` worked. Asked for clarification here: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/mG6vL09JMOQ 

If that turns out to be the case (which is likely), which ones do we want viewer to enable? `allow="geolocation"` is the only one set by viewer at the moment. Payments and fullscreen are also specified via the old format (`allowpayments` `allowfullscreen`)

Canonical AMP sites like https://www.accordersaguitare.com/ want `microphone` as well.

It is sort of strange to let origin specify whatever it wants but then restrict them in the viewer.

**Comment by aghassemi** [comment]
@dvoytenko confirmed, child frames can't give away policies their parent hasn't given them. So viewer can strict available policies of all descendant frames.

**Comment by dvoytenko** [comment]
Still, AMP could be given more allowance than would be expected for embeds within AMP. Did we try to run it by security?

**Comment by cramforce** [comment]
So far our policy has been to allow pages to grant all permissions to child
frames. I don't really see how that could not be the right thing to do, but
could be convinced otherwise.

**Comment by aghassemi** [comment]
Chatted offline a bit with Dima yesterday.

Suggestion:
1- AMP does not restrict values of `allow` in the format (i.e. this PR removing validation restrictions)
2- Viewers can add restrictions. (Feature Policy is flexible enough that a viewer can grant more to the top-level page but restrict the page from granting it to other x-origin embeds by specifying domains for each policy)
3- Have our viewer allow `payment` `geolocation` and `microphone` for now. (it is missing `microphone`)

Note that these are not actual permissions, just whether the API is available or not. User still needs to grant permission when API is used.

**Comment by lannka** [comment]
what's the status of this PR? it will unblock #12282

**Comment by aghassemi** [comment]
ready to merge, needs approval :)
1- let's merge this
2- I will ask our viewer to allow `payment` `geolocation`, `microphone` and `vr`.

**Comment by aghassemi** [comment]
b/70231806

**Comment by Gregable** [comment]
The validator changes in here are now live.

**Comment by nightpool** [comment]
allow="encrypted-media" is now also required to use EME apis. Is there a way to get this considered for inclusion in the ampproject viewer?

**Comment by cramforce** [comment]
@nightpool Yes! Would you mind filing a separate issue and we can track inclusion across major viewers.

**Comment by nightpool** [comment]
@cramforce will do

**Comment by nightpool** [comment]
done: https://github.com/ampproject/amphtml/issues/18430

**Pull request merged**
