### PR TITLE
Update vendors.js to add amp-analytics for ÖWA

### PR DESCRIPTION
**Pull request by oewaoffice**
See also #3379

### CODE REVIEW

**Comment by oewaoffice** [comment]
Hi,
we already signed the CLA for ÖWA.
Regards

**Comment by hjanuschka** [comment]
nice one! if you need any help on unit-tests and documentation samples - see my PR https://github.com/ampproject/amphtml/pull/3076

**Comment by avimehta** [comment]
Do you mind putting the changes from #3388 in here? It will be easier to track changes if everything is in a single PR.

**Comment by avimehta** [comment]
the tests also need to be updated.

**Pull request closed without merging**
