### PR TITLE
Add Twitter background SVG to amp-social-share CSS (Issue #2628)

### PR DESCRIPTION
**Pull request by jsit**

### CODE REVIEW

**Comment by paul-matthews** [comment]
The twitter logo now fills too much of the button (on chrome at least)

screen shot 2016-03-22 at 2 36 28 pm

**Comment by jsit** [comment]
Feels a little strange to me to add padding in the SVG itself, rather than around the element's background?

**Comment by jsit** [comment]
The size of the Twitter icon is somewhat addressed in this PR: https://github.com/ampproject/amphtml/pull/2666

screen shot 2016-03-23 at 9 26 53 am

Should the SVG instead have top and bottom padding that would make it the same height as the Pinterest icon?

**Comment by jsit** [comment]
Pushed a new commit that matches the Twitter height to the Pinterest height:

screen shot 2016-03-23 at 9 39 46 am

**Comment by dvoytenko** [comment]
Thanks, @jsit. This looks good. Could you please squash your commits so I can merge?

**Comment by jsit** [comment]
All set, thanks.

**Pull request merged**
