### PR TITLE
🐛 ❄️  Update forbidden terms allow list

### PR DESCRIPTION
**Pull request by rileyajones**
#34887 updated some files to no longer use some forbidden terms leading to failures during the "Checks" phase.

image

### CODE REVIEW

**Review by rcebulko — APPROVED** [review]
FWIW this is included in https://github.com/ampproject/amphtml/pull/34877 now, but I'm guessing your CI will pass first, so approving to unblock

**Comment by rcebulko** [comment]
@rileyajones do we know why the PR didn't fail CI during linting if it touched these files?

**Comment by rileyajones** [comment]
@rcebulko I'm currently investigating why this didn't fail during the checks run for #34887. When I have an answer I'll comment here and post another PR to patch that if possible.
https://app.circleci.com/pipelines/github/ampproject/amphtml/11567/workflows/0c070607-aeb2-4a02-95b4-7aee1739de41/jobs/183019

**Comment by rcebulko** [comment]
> @rcebulko I'm currently investigating why this didn't fail during the checks run for #34887. When I have an answer I'll comment here and post another PR to patch that if possible.
> https://app.circleci.com/pipelines/github/ampproject/amphtml/11567/workflows/0c070607-aeb2-4a02-95b4-7aee1739de41/jobs/183019

Confirmed locally: This fails when `amp lint --files=build-system/test-configs/forbidden-terms.js`, not when the files themselves are being linted. I think this file may need to be special-cased for `--local_changes`

**Comment by rileyajones** [comment]
#34889 got checked in so this is no longer needed

**Comment by alanorozco** [comment]
@rileyajones It looks like the failure was created during #34887, but I'm not sure why the files weren't linted then.

It's likely that our filematch rule excluded `forbidden-terms.js`

**Comment by rileyajones** [comment]
@alanorozco the issue was that the linter got changed to use the `local_changes` flag a while back but those errors are only generated when the `forbidden-terms` file is linted. The issue should be patched now that #34897 is merged.

**Pull request closed without merging**
