### PR TITLE
Added validation rule

### PR DESCRIPTION
**Pull request by buzzdan**
Added the ability to load amp-playbuzz header script without using the actual extension on page

### CODE REVIEW

**Comment by Gregable** [comment]
Hi @buzzdan , for new extensions like this one, we want to use `also_requires_tag` which produces an error rather than `extension_unused_unless_tag_present` which produces a warning.

**Comment by buzzdan** [comment]
@Gregable i see, 
this was a special request from one of our publishers so they can add the playbuzz script easily into the header 
i think that what they do with amp-instagram

if it is a problem, we can discuss with them about another solution

**Comment by maxhartshorn** [comment]
Hi @buzzdan. I would hope this could produce a warning and not an error as is the case for other extensions, at least until there is a clear direction that including a script without a corresponding embed will result in an error. This approach feels inconsistent, especially as there is still discussion as to the best approach: https://groups.google.com/forum/#!topic/amphtml-discuss/txxonN2w6C4

**Comment by Gregable** [comment]
We produce errors for all new extensions. We would like to produce `amp-instagram` errors as well, but we have grandfathered in usage of tags that pre-dated this constraint, emitting a warning instead.

**Comment by Gregable** [comment]
I'm closing this. Please reopen if this is still an outstanding issue.

**Pull request closed without merging**
