### PR TITLE
Move integration tests from test/functional/ to test/integration/

### PR DESCRIPTION
**Pull request by rsimha-amp**
All these tests require the AMP runtime to be built, and need a full `gulp build` before they can run. Therefore, they are integration tests, and should be moved from `test/functional` to `test/integration`, or in the case of extensions, from `test/` to `test/integration`. After this PR is merged, #10792 will make it so that we only run `gulp css` prior to running the unit tests on Travis. The following will now work:

```
gulp clean
gulp css
gulp test --nobuild --unit
```

To be followed by #10792
Partial fix to #10785

### CODE REVIEW

**Comment by rsimha-amp** [comment]
Step 1 successful: All unit tests now run with just `gulp css`. See https://gist.github.com/rsimha-amp/c635de4c8842ba9106b98b759578c148

Coming up: Fix presubmit and integration test errors.

**Comment by rsimha-amp** [comment]
@choumx, yeah, I was surprised. Let's not celebrate too early though.

Step 2 successful: Presubmit errors fixed.

Step 3 is interesting: There are now a bunch of failures in the tests that were moved to `/integration`. https://travis-ci.org/ampproject/amphtml/jobs/261080620 Not sure if these are due to moving the files, or bugs that always existed in the tests that are now being exposed on other browsers due to `--saucelabs`.

**Comment by rsimha-amp** [comment]
Step 3 successful: https://gist.github.com/rsimha-amp/fe64bb089593002207a0c28e6ff4c949

Will merge this as soon as Travis goes green.

**Comment by choumx** [comment]
@rsimha-amp I think there was some miscommunication -- we should still be running these moved integration tests on Chrome at least. After commit 36b70ab, we're now skipping a lot of integration tests that were previously running on Travis (latest Chrome).

**Comment by rsimha-amp** [comment]
Aha, they were previously being run on latest Chrome due to the unqualified `gulp test` but now, they're being filtered out on one shard due to `--unit`, and on the other shard due to `--saucelabs`.

I could remove the `--unit` from the first shard, but that would undo all the speed gains due to not building before the unit tests. Is there an alternative to `skipSauceLabs` that runs an integration test only on latest Chrome?

I'll send you a PR shortly to rectify this.

**Comment by rsimha-amp** [comment]
@choumx, sent you #10825.

**Pull request merged**
