### PR TITLE
♻️ Use alias imports instead of local in src/

### PR DESCRIPTION
**Pull request by rcebulko**
The lint autofix handles most imports automatically, but imports from flatfiles in `src` are still able to use relative `./*` imports of aliased paths. This updates `src/*.js` to use aliased importrs.
Excludes `src/3p-frame-messaging.js` to avoid merge conflicts with https://github.com/ampproject/amphtml/pull/35563

### CODE REVIEW

**Comment by samouri** [comment]
How did you run this? Are you also modifying lint settings anywhere?

**Comment by rcebulko** [comment]
> How did you run this? Are you also modifying lint settings anywhere?

Normally `amp lint --fix --local_changes`; that's how the imports everywhere else were updated. These wouldn't be autofixed though because they are the only files with the ability to reference aliased dirs as submodules via `./*`, which is allowed. These were fixed manually (regex replace)

**Comment by samouri** [comment]
> > How did you run this? Are you also modifying lint settings anywhere?
> 
> Normally `amp lint --fix --local_changes`; that's how the imports everywhere else were updated. These wouldn't be autofixed though because they are the only files with the ability to reference aliased dirs as submodules via `./*`, which is allowed. These were fixed manually (regex replace)

In that case, as long as tests pass I'm happy

**Review by samouri — APPROVED** [review]

**Comment by rcebulko** [comment]
> > > How did you run this? Are you also modifying lint settings anywhere?
> > 
> > 
> > Normally `amp lint --fix --local_changes`; that's how the imports everywhere else were updated. These wouldn't be autofixed though because they are the only files with the ability to reference aliased dirs as submodules via `./*`, which is allowed. These were fixed manually (regex replace)
> 
> In that case, as long as tests pass I'm happy. that said, theres nothing stopping this from heading back to relative imports right?

Not without writing a custom lint plugin. Once the rest of the flatfiles here are cleared out/moved elsewhere, it'll no longer be possible, so the extra lint rule doesn't feel worthwhile.

**Pull request merged**
