### PR TITLE
Content.ad: Utilize sourceUrl for validation

### PR DESCRIPTION
**Pull request by jlucero-contentad**
Updated the Content.ad logic to use the sourceUrl value for publisher domain validation.

### CODE REVIEW

**Comment by jlucero-contentad** [comment]
Travis CI threw the following error:
`The command "node build-system/pr-check.js" exited with 1.`

Please confirm and restart the test.

**Comment by jlucero-contentad** [comment]
@lannka how do I restart the Travis CI test? It failed the first time but I don't think it was my fault.

**Comment by jlucero-contentad** [comment]
@lannka I don't understand why I'm getting the following error in the Travis CI test. I defined my sourceUrl variable, but it looks like 'window.context.sourceUrl' is not defined.
'ads/contentad.js:36: ERROR - Property sourceUrl never defined on window.context
  let sourceUrl = window.context.sourceUrl;
                                 ^'

**Comment by lannka** [comment]
Could you try adding the following line [here](https://github.com/ampproject/amphtml/blob/master/build-system/amp.extern.js#L26)
```
window.context.sourceUrl;
```
And then run `gulp check-types` to see if problem remains.

**Comment by jlucero-contentad** [comment]
@lannka looks like that did the trick. Am I allowed to modify `build-system/amp.extern.js` in this pull request?

**Comment by lannka** [comment]
Definitely. Thanks for the fix.

**Pull request merged**
