### PR TITLE
🏗 Re-enable testing on Sauce Labs on Chrome, Firefox, and Safari (with lower concurrency)

### PR DESCRIPTION
**Pull request by rsimha**
Per communication with Sauce Labs:

> Would it be possible to run the tests in Travis again but with fewer tests in parallel?  I'm concerned the Sauce Connect hardware requirements aren't up to our specifications when running multiple tests through the tunnel.
> 
> Running the tests with a lower concurrency limit or even in Serial may alleviate some of the load on the tunnel.

This PR does the following:
1. Re-enables testing on Sauce Labs on the three main browsers: Chrome, Firefox, and Safari
2. Reduces concurrency to 3 (since we suspect that the higher limit was causing disconnections)
3. Merges platform changes from  #16633 
4. Re-configures all platforms to not use the `latest` version number, since that's suspected as a source of errors

### CODE REVIEW

**Comment by choumx** [comment]
You may need to merge changes from #16633 to dodge the other error.

**Comment by rsimha** [comment]
@choumx Changes merged.

**Comment by choumx** [comment]
Looks like test are running again. 👍

**Comment by rsimha** [comment]
@choumx This is now stable on Chrome, Firefox, and Safari, so I'm going to merge this as is so we regain coverage.

I'll send out separate PRs that enable testing on more browsers. One way to do this might be to run the integration tests in two separate tasks across different sets of browsers.

**Pull request merged**
