### PR TITLE
🔥 P0 fix - encodeURIComponent breaks functionality 

### PR DESCRIPTION
**Pull request by JuliusThms**
This PR requests fixes the use of encoded URL in the iframe src. It fixes a break of the functionality.

### CODE REVIEW

**Comment by JuliusThms** [comment]
@alanorozco 

`return encodeURIComponent(iframeSrc);` this broke the functionality of iframe `src`.
I changed this part and hope you can merge as soon as possible.

**Review by alanorozco — APPROVED** [review]

**Comment by JuliusThms** [comment]
@alanorozco  @kristoferbaxter Thanks for your quick response!

**Comment by JuliusThms** [comment]
@alanorozco Can we get this shortly released?

**Comment by alanorozco** [comment]
@JuliusThms

Please see [release schedule](https://amp.dev/documentation/guides-and-tutorials/learn/spec/release-schedule/). We unfortunately can't make an off-schedule release for a particular change, unless it meets [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#process-for-requesting-a-cherry-pick). Follow the cherry pick process if you'd like to, but I can't say that it will be approved 😕

**Pull request merged**
