### PR TITLE
✨Add support for CAaja ads network

### PR DESCRIPTION
**Pull request by matsuda-takehiro**
Adds support for CAaja ads network.

### CODE REVIEW

**Comment by matsuda-takehiro** [comment]
@torch2424
 Thank you for the other day!
Thanks to you I solved a few problems.
But the bot does not respond... 😭

I would be pleased if you could tell me what to do.

Thank you very much

**Comment by torch2424** [comment]
Adding labels per @erwinmombay suggestion to fix the CLA bot.

**Comment by mrjoro** [comment]
@googlebot rescan.

**Comment by matsuda-takehiro** [comment]
thank you everybody!!

By the way, I changed my address to "AA", but is CLA's consent here?

**Comment by mrjoro** [comment]
Hi @matsuda-takehiro, I don't see a CLA signed for the email address "matsuda_takehiro@aja-kk.co.jp" or your GitHub username.

If you're able to use [Slack](https://amphtml.slack.com) I can help you figure out what might be going wrong.  If you haven't already you'll need to ([sign up](https://bit.ly/amp-slack-signup)) and then you can message me @mrjoro.

**Comment by matsuda-takehiro** [comment]
Thank you @mrjoro 
I will investigate. Would you please wait until next week?
I'm sorry 😭

Is there a name Ogosi belonging to AJA in the CLA list?

**Comment by matsuda-takehiro** [comment]
Thank you @mrjoro　！
I'm glad you say so. 

Even here I consulted with my boss but did not understand eventually.
I apologize for any inconvenience.😭

**Comment by matsuda-takehiro** [comment]
> * decides
I signed it!

**Comment by matsuda-takehiro** [comment]
@torch2424 @mrjoro 
Thank you very much. I was able to proceed!

I'm sorry. What should I next do?😭

Should I commit again with my current e-mail address and issue Plurrique?

I'm sorry for bothering you.

**Comment by torch2424** [comment]
cc @matsuda-takehiro @mrjoro 

So looking at the git log:

screen shot 2019-02-01 at 4 07 17 pm

Seems like you don't currently have an[email set to your `git config`](https://help.github.com/articles/setting-your-commit-email-address-in-git/). See the commit after yours to see what a commit should look like, for example: `My name<myemail@email.com>`. You can also fix this by doing a `git rebase` of your commits to add an email to the appropriate place.

Let me know if this helps. Thanks!

**Comment by matsuda-takehiro** [comment]
https://github.com/ampproject/amphtml/pull/20652

sorry...

**Pull request closed without merging**
