### PR TITLE
🐛Fix the bug that parseLayout ignores case and underscore

### LINKED ISSUE #25320: Validator incorrectly accepts layout=fixed_height
The JS validator at https://validator.amp.dev (incorrectly) considers components with layout `fixed_height` valid. (This should be written `fixed-height`.) The validator used in the Google AMP cache does not.

Example doc with `layout=fixed_height` that is rejected by the Google validator (as expected), but accepted by the JS validator (unexpected): https://brash-grease.glitch.me/

Identical page except with `layout=fixed-height` for comparison: https://picayune-yttrium.glitch.me/

/cc @Gregable

### PR DESCRIPTION
**Pull request by caoboxiao**
Fixes #25320

Fixes the bug that the layout `fixed_height` and `FIXED-HEIGHT` were (incorrectly) parsed as the `fixed-height`.

Now the javascript validator is case-sensitive, and only accepts the exact layout value (such as `fixed-height`).

### CODE REVIEW

**Comment by honeybadgerdontcare** [comment]
Awesome! I looked at this earlier and thought of doing the same thing then thought it might be good to get rid of the layout generation from validator_gen.js as well. However that's a larger refactoring.

**Comment by honeybadgerdontcare** [comment]
Could you add a feature test file as well that covers different permutations?
It'd go into `validator/testdata/feature_tests/`

**Comment by caoboxiao** [comment]
> Could you add a feature test file as well that covers different permutations?
> It'd go into `validator/testdata/feature_tests/`

Done

**Review by honeybadgerdontcare — APPROVED** [review]
Thank you for the test cases!

**Pull request merged**
