### PR TITLE
Support log level experiment

### PR DESCRIPTION
**Pull request by alabiaga**
Fixes: #21201 

log-level-experiment

Changes:

- Modify ExperimentDef to support reuse of experiment ID for experiments that support key/value, such as log
- extract URL related functions in url.js called by cookie.js to url-utils.js to fix circular dependency mode.js -> cookie.js -> url.js -> log.js. As mode.js now depends on cookies to determine if log level experiment is set.

### CODE REVIEW

**Comment by alabiaga** [comment]
cc\ @jpettitt Hey Jon, I added support for this but in the existing AMP_EXP cookie as a new cookie would entail more changes and a security review. This should suffice but obviously I'd like to do this properly and if this existing in AMP_EXP doesn't make sense, then we can do this with a new cookie. thanks 

the AMP_EXP cookie with logging WARN enabled would look like so:

AMP_EXP=log=2;amp-list-load-more;

**Comment by alabiaga** [comment]
@jpettitt Hey John, pls take a look. Note that I have a TODO to fix a cyclic dependency..so there is duplicated code in log.js for getting the cookie and experiment id and value used for the cookie level log.

Still brainstorming on the best way to get around that. Otherwise everything else is up for review.  Thanks

**Comment by alabiaga** [comment]
> * Can we have a single experiment toggle that turns on/off everything instead of 5?
You mentioned this offline and I'll defer to @jpettitt  for an answer. Currently I am mimicking the behavior of the current means to override the log level via hashQuery, which allows only log level to be specified.

> * Need to fix the code dupe due to dep cycle.
Yup, will fix this. The fix wasn't very obvious without having pull out the cookie related code from cookies.js. Thanks

**Comment by jpettitt** [comment]
Logs are really a radio button experience right? Only one level can be selected or did I miss something?

**Comment by alabiaga** [comment]
> Logs are really a radio button experience right? Only one level can be selected or did I miss something?

Yes, only one can be set a time. If log WARN is enabled and then log ERROR is enabled, log WARN will be turned off. So yes, the user experience is different then the other experiments. Perhaps I can follow up with a separate PR to change this.

**Comment by mrjoro** [comment]
Is this PR still active?

**Pull request closed without merging**
