### PR TITLE
quick fix to prep for compiler

### PR DESCRIPTION
**Pull request by erwinmombay**

### CODE REVIEW

**Comment by dvoytenko** [comment]
LGTM!

**Comment by ampsauce** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 87cd6b2ee19a1926b66ee9f1de442f663cc53fb4
Build details: https://travis-ci.org/ampsauce/amphtml/builds/86291205

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by erwinmombay** [comment]
@ampsauce gonna merge anyways, flakey test!

**Comment by cramforce** [comment]
@erwinmombay Just FYI: You can use "at-ampsauce retry" to trigger a rebuild. See https://github.com/ampproject/amphtml/blob/master/DEVELOPING.md#saucelabs

**Comment by erwinmombay** [comment]
@cramforce thanks!

**Pull request merged**
