### PR TITLE
🐛Fix zucks ad return timing

### PR DESCRIPTION
**Pull request by yang-wei**
# Instructions:

- Fix a bug from our pull request (https://github.com/ampproject/amphtml/pull/20206)
- Start using loadScript for tag that supports async load

### CODE REVIEW

**Comment by yang-wei** [comment]
@lannka @torch2424 Can you please look at this ? 🙏

**Comment by torch2424** [comment]
@yang-wei

Before merging this, I went ahead and tested just to make sure things are working, and I got the following:

Screen Shot 2019-06-06 at 4 42 19 PM

Seems like there is an error for the larger ad. If this is expected I'll go ahead and merge.

Thanks! 😄

**Comment by torch2424** [comment]
@yang-wei 

Oh also, seems like the travis check for linting failed. Please run the linter as well and then I can merge this 😄 

Thanks!

**Comment by yang-wei** [comment]
@torch2424 hey I linted my code. Thanks for checking the ad though. Its fine to not show up for larger ad. (Although I fixed it now)

p/s: you have a very nice profile icon

**Comment by torch2424** [comment]
@yang-wei 

> hey I linted my code. Thanks for checking the ad though. Its fine to not show up for larger ad. (Although I fixed it now)

Awesome thanks! 😄 

> p/s: you have a very nice profile icon

Thank you! 👍 I appreciate it! 😄 

Merging this, thank you for the contribution! 👏 🎉

**Pull request merged**
