### PR TITLE
Added support for SimpleReach `article_id` and `ignore_metadata` configuration

### PR DESCRIPTION
**Pull request by highcard**
- Adds support for article_id to the amp-analytics configuration for SimpleReach
- Adds support for ignore_metadata to the amp-analytics configuration for SimpleReach
- Adds above values to SimpleReach network requests

### CODE REVIEW

**Comment by highcard** [comment]
I signed it!

**Comment by zhouyx** [comment]
@highcard LGTM. Tests failure seem unrelated to your PR. Please rebase to fix them.

**Comment by highcard** [comment]
@zhouyx thanks for the approval. Rebased.

**Comment by zhouyx** [comment]
@highcard All tests passed! Thanks for the Pull Request, merged.

**Comment by highcard** [comment]
@jonkeller @zhouyx  -- I noticed this has been included in the pre-release version 1501383761781.

https://github.com/ampproject/amphtml/releases/tag/1501383761781

Is the built file hosted somewhere that I could reference for a map remote to do some follow-up testing for the feature?

Thanks for the guidance!

**Comment by zhouyx** [comment]
@highcard please opt in to our [dev channel](https://cdn.ampproject.org/experiments.html) to test the pre-release version.

**Comment by highcard** [comment]
Thanks @zhouyx -- will do

**Pull request merged**
