### PR TITLE
Adding PubMatic OpenWrap Vendor :sparkles:

### PR DESCRIPTION
**Pull request by pm-harshad-mane**
✨ Adding PubMatic OpenWrap Vendor

### CODE REVIEW

**Comment by pm-harshad-mane** [comment]
Hello @choumx   or @jridgewell  , need your assistance

FAIL  ./dist/v0.js: 79.24KB > maxSize 79.24KB (gzip) 
[18:57:20] ERROR: bundlesize found that ./dist/v0.js has exceeded its size cap of 79.24KB.
[18:57:20] This is part of a new effort to reduce AMP's binary size (#14392).
[18:57:20] Please contact @choumx or @jridgewell for assistance.

**Comment by pm-harshad-mane** [comment]
PubMatic has signed CLA, we faced a similar issue with CLA when we raised https://github.com/ampproject/amphtml/pull/13911 in April 2018.

**Comment by erwinmombay** [comment]
ping @keithwrightbos @bradfrizzell for review

**Comment by pm-harshad-mane** [comment]
Hello @keithwrightbos and @bradfrizzell 
Please review the PR.

**Comment by pm-harshad-mane** [comment]
Hello @bradfrizzell ,
All checks are passed, can you please merge the changes?

**Pull request merged**
