### PR TITLE
✨ Lotame: Change to allow limiting the maximum number of audiences. 

### PR DESCRIPTION
**Pull request by Tonsil**
Also updated the Lotame vendor link.

### CODE REVIEW

**Review by calebcordry — APPROVED** [review]
Thanks for maintaining this extension!

**Comment by calebcordry** [comment]
looks like you have a lint error, you can expose it with `gulp lint` or try `gulp lint --fix` but make sure you are in a recoverable state before you try the fix.

**Comment by Tonsil** [comment]
> looks like you have a lint error, you can expose it with `gulp lint` or try `gulp lint --fix` but make sure you are in a recoverable state before you try the fix.

I'm honestly not sure what you mean. When I try `gulp lint` it complains about a helper.js file (MODULE_NOT_FOUND) that has nothing to do with my changes.

**Comment by calebcordry** [comment]
Here is the link to our failing CI: https://travis-ci.org/github/ampproject/amphtml/jobs/735766000 hopefully you can see it. Not sure whats going on with `helper.js`, you can maybe try rebasing or merging the latest master. Also maybe run yarn to make sure everything is up to date? Let me know if you still have issues.

**Comment by Tonsil** [comment]
> Here is the link to our failing CI: https://travis-ci.org/github/ampproject/amphtml/jobs/735766000 hopefully you can see it. Not sure whats going on with `helper.js`, you can maybe try rebasing or merging the latest master. Also maybe run yarn to make sure everything is up to date? Let me know if you still have issues.

Yeah, that was it. I didn't run lint/prettify before submitting, because it wasn't a thing when I first wrote the extension. I think that should do it.

**Comment by calebcordry** [comment]
Thanks! I think now it failing due to the broken link check in `extensions/amp-analytics/analytics-vendors-list.md` (not your fault) I am working to see what we can do with these links cc/ @ampproject/wg-analytics

**Comment by calebcordry** [comment]
URLs fixed. Thanks for your patience.

**Pull request merged**
