### PR TITLE
✨ Add Relap v7 widget support

### PR DESCRIPTION
**Pull request by advzr**
- Adds `version` data attribute to support new v7 Relap widgets
- Makes `url` data attribute optional

### CODE REVIEW

**Comment by advzr** [comment]
Ping

**Comment by advzr** [comment]
Ping

**Comment by advzr** [comment]
Could anyone review this please?

**Comment by advzr** [comment]
Fixed conflicts. Waiting for review.

**Comment by aghassemi** [comment]
@advzr, apologies for the delay. to @lannka for review.

**Pull request merged**
