### PR TITLE
Report sync errors during 3p iframe loading.

### PR DESCRIPTION
**Pull request by cramforce**

### CODE REVIEW

**Comment by erwinmombay** [comment]
@cramforce LGTM

**Comment by cramforce** [comment]
Shoot. Unfortunately this will not work this way. Too many deps.

**Comment by erwinmombay** [comment]
@cramforce are you talking about the file size?

**Comment by cramforce** [comment]
Yeah, this pulls too much stuff into the 3p binary

**Comment by cramforce** [comment]
PTAL

**Comment by erwinmombay** [comment]
@cramforce LGTM. good catch on file size

**Comment by cramforce** [comment]
@erwinmombay I have a test that forbids the 3p binary to depend on certain things. Such as promises :)

**Comment by erwinmombay** [comment]
"   // This does match dist.3p/current, so we run presubmit checks on the
    // built 3p binary. This is done, so we make sure our special 3p checks
    // run against the entire transitive closure of deps."

:+1:

**Pull request merged**
