### PR TITLE
Eslint: Remove unnecessary semicolons

### LINKED ISSUE #10499: Linter doesn't pick up extra semicolons
Steps to reproduce: 

1. Add a second semicolon at the end of any line. 
2. Run `gulp lint`
3. Observe no lint error.

### PR DESCRIPTION
**Pull request by rsimha-amp**
This PR adds a new `eslint` rule `no-extra-semi` and removes all extra semicolons in the AMP code.

Fixes #10499

### CODE REVIEW

**Comment by jridgewell** [comment]
[Add semicolons everywhere!](https://github.com/tc39/ecma262/pull/1062)

**Comment by rsimha-amp** [comment]
@jridgewell Does this PR violate any of the concerns in the thread? (The semicolons being removed here are either dupes like `;;`, or come after function definitions.)

**Comment by jridgewell** [comment]
Lol, no. I'm making a joke. Semi-colons after every line is the only way to fix ASI.

**Comment by rsimha-amp** [comment]
For posterity, here's why a semicolon after an `export` for a function is unnecessary: https://github.com/eslint/eslint/issues/3184#issuecomment-126019207

**Comment by rsimha-amp** [comment]
@jridgewell Can you review / approve this?

**Pull request merged**
