### PR TITLE
♿ MediaNet : Adding parameters to the MediaNet callout URL.

### PR DESCRIPTION
**Pull request by c3p-0**
Adding cst_type and gdpr_applies  parameters to the MediaNet callout URL.

### CODE REVIEW

**Review by powerivq — APPROVED** [review]

**Comment by powerivq** [comment]
@c3p-0 The PR LGTM, but you need to have Rahul sign the CLA for this PR to be merged (see the comment above). Alternatively, you can force update this commit to be under your name and sign the CLA yourself.

**Comment by c3p-0** [comment]
@powerivq I have done the required changes please have a look.

**Comment by anuragagarwal561994** [comment]
@powerivq we are still receiving some traffic where `cst_type` is not present, any recommendations on how can it be handled.

**Comment by powerivq** [comment]
@anuragagarwal561994 can you tell what is the rough percentage? It is possible some publishers decide to stay on an older release (LTS).

**Comment by anuragagarwal561994** [comment]
Sorry for late reply I was setting up the data, following are the rough data points

Out of 100% traffic:
a. 95.5% times we are not getting cst_type, also we are not getting gdpr string in this case
b. 1.5% times we are not getting cst_type, but we are getting gdpr string in this case
c. Remaining 3% times we are getting correct cst_type and respective string

Currently when we don't get cst_type and we get gdpr_string it becomes difficult to identify.

**Comment by powerivq** [comment]
@anuragagarwal561994 Hi. You will only get these meta tags if the publisher uses amp-consent extension.

**Pull request merged**
