### PR TITLE
fix typo in `running-server-side-experiment.md`

### PR DESCRIPTION
**Pull request by samouri**
declaritions --> declarations

### CODE REVIEW

**Comment by samouri** [comment]
This is comically failing CI right now. Retrying in case of flake, but the error is one I've never seen before.
Invalid GPG for yarn 😱

**Comment by rsimha** [comment]
> Invalid GPG for yarn

GH Actions or Travis? Either way, it's likely flake.

**Comment by samouri** [comment]
> GH Actions or Travis? Either way, it's likely flake.

It was travis and happening to all of my PRs for a few hours. Looks fixed now :)

**Comment by samouri** [comment]
@googlebot

**Pull request merged**
