### PR TITLE
Switch from gulp-closure-compiler to google-closure-compiler

### LINKED ISSUE #11203: AMP runtime build broken on Travis due to new trusty image
Travis tracking bug: https://github.com/travis-ci/travis-ci/issues/8315
Announcement: https://blog.travis-ci.com/2017-08-29-trusty-image-updates
Workaround: Add `group: deprecated-2017Q3` to `.travis.yml`

### LINKED ISSUE #11210: `gulp check-types` broken on Travis due to the presence of `_JAVA_OPTIONS`
This fails on the new trusty machines on Travis.

Steps:
1. `export _JAVA_OPTIONS="-Xmx2048m -Xms512m"` (used on Travis)
2. `gulp clean && gulp check-types`

Result:
```
Error compiling ./3p/iframe-transport-client-lib.js
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
```

EDIT: This is likely due to the old version of `gulp-closure-compiler` we're using. Skip down to https://github.com/ampproject/amphtml/issues/11210#issuecomment-327990926

### LINKED ISSUE #11229: Upgrade to a newer closure compiler
[Recent changes](https://blog.travis-ci.com/2017-08-29-trusty-image-updates) to Travis ([restrictions](https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/) on the JVM memory pool size) have [broken](https://github.com/travis-ci/travis-ci/issues/8315#issuecomment-327951718) `gulp-closure-compiler`, the closure compiler used to build the AMP runtime.

Moreover, the compiler version we use is outdated, and the [npm page](https://www.npmjs.com/package/gulp-closure-compiler) points to a [github repository](https://github.com/steida/gulp-closure-compiler) that was last updated more than 2 years ago and is no longer accessible, with [no fixes imminent](https://webcache.googleusercontent.com/search?q=cache:Ni_GBjMUitQJ:https://github.com/steida/gulp-closure-compiler/issues/33+&cd=3&hl=en&ct=clnk&gl=us).

Since we need to use a custom Java par to build the AMP runtime (to allow for code splitting), and since a pure JS compiler is about 2x slower, we are left with one choice: Migrating to `google-closure-compiler`  (see [npm page](https://www.npmjs.com/package/google-closure-compiler) and [github page](https://github.com/google/closure-compiler-npm)) and using its [gulp plugin](https://www.npmjs.com/package/google-closure-compiler#using-the-gulp-plugin).

This bug is meant to track the migration to the new compiler.

Originally discovered via #11203
Related issues: #11210, https://github.com/travis-ci/travis-ci/issues/8315

### PR DESCRIPTION
**Pull request by rsimha-amp**
Fixes #11229
Fixes #11210
Fixes #11203
Unblocks #11206

### CODE REVIEW

**Comment by rsimha-amp** [comment]
@erwinmombay, when I just swap out the compiler (without changing the format of the options passed in), `gulp build` works, but `gulp dist` and `gulp check-types` do not. I'm seeing errors like `"--compilerPath" is not a valid option`. See https://travis-ci.org/ampproject/amphtml/builds/273367267

Do you think it's feasible to switch to a compiler with a different options format? Also, are you aware of a way to use a custom compiler with `google-closure-compiler`?

**Comment by erwinmombay** [comment]
it looks like it always uses the compiler that it builds https://github.com/google/closure-compiler-npm/blob/master/lib/node/closure-compiler.js#L27 from what i can tell

**Comment by rsimha-amp** [comment]
Hmm. Does that mean we're at a dead end with `google-closure-compiler`?

/cc @cramforce @choumx

**Comment by rsimha-amp** [comment]
This PR is a dead end, due to how `google-closure-compiler` uses a different set of args than `gulp-closure-compiler`. Particularly the fact that we can't use a custom java compiler.

**Pull request closed without merging**
