### PR TITLE
Adjust validator .js paths in whitelist to allow me to merge PR 4306.

### PR DESCRIPTION
**Pull request by powdercloud**
Unfortunately I didn't include the 'document' whitelist in my previous attempt (#4308) so the presubmit still fails.

### CODE REVIEW

**Comment by powdercloud** [comment]
I signed it.

**Comment by powdercloud** [comment]
Oh hold on it looks like there's more. Will say hi again once I've covered them all.

**Comment by powdercloud** [comment]
should be good now

**Comment by dvoytenko** [comment]
LGTM

**Comment by powdercloud** [comment]
@googlebot I signed it!

**Comment by powdercloud** [comment]
@dvoytenko Thanks a lot!

**Comment by powdercloud** [comment]
@dvoytenko Sorry, since I authored this commit with Github's web tool, the cla/google checker basically doesn't work. So I made a new PR, please give me LGTM there again and I'll abandon this one. Sorry about the mess.

https://github.com/ampproject/amphtml/pull/4318

**Pull request closed without merging**
