### PR TITLE
🐛Fix broken cookie writer test

### LINKED ISSUE #22694: test-cookie-writer failing on master
The tests at `extensions/amp-analytics/0.1/test/test-cookie-writer.js` are failing and blocking the canary release.

https://travis-ci.org/ampproject/amphtml/jobs/541467573

The fix should cherry picked before the Canary + 1% are shipped and promoted.

```
amp-analytics.cookie-writer value
     
      ● should write cookie with custom expiration (zero value)
        Chrome 75.0.3770 (Linux 0.0.0)
      AssertionError: expected 'aCookie=testValue; path=/; domain=example.com; expires=Mon, 01 Jan 2018 08:00:00 GMT' to equal 'aCookie=testValue; path=/; expires=Mon, 01 Jan 2018 08:00:00 GMT'
          at [...]/amphtml/extensions/amp-analytics/0.1/test/test-cookie-writer.js:377:48

      ● should write cookie with custom expiration (negative value)
        Chrome 75.0.3770 (Linux 0.0.0)
      AssertionError: expected 'aCookie=testValue; path=/; domain=example.com; expires=Mon, 25 Dec 2017 08:00:00 GMT' to equal 'aCookie=testValue; path=/; expires=Mon, 25 Dec 2017 08:00:00 GMT'
          at [...]/amphtml/extensions/amp-analytics/0.1/test/test-cookie-writer.js:398:48

```

### PR DESCRIPTION
**Pull request by calebcordry**
Test added in #22483.

This appears to be a fix, but I am unsure if it is the correct fix. It is odd that it passed on PR, but now seems to be broken locally and on travis. 
to/ @jonathantyng-amp @zhouyx 

Closes #22694

### CODE REVIEW

**Comment by zhouyx** [comment]
Thank you for the quick fix. I wonder how the tests get passed when we first submit it. 
@jonathantyng-amp could you please take a look. Thanks.

**Comment by calebcordry** [comment]
Added travis fix thanks to @estherkim Please make sure I did the right thing :)

**Comment by zhouyx** [comment]
@estherkim Do you know why the test passed in #22483?

**Comment by estherkim** [comment]
Hmmm whenever this happens, the first thing I think is that something else got into master after #22483's Travis build succeeded, that then broke this commit when it was merged into master. However I don't see anything in this time frame that could have affected the cookie writer test.

But I noticed that Travis started using Chrome 75, which was released yesterday.  #22483's build uses Chrome 74. I think that might have been it!

**Comment by zhouyx** [comment]
Thank you @estherkim. 
The failing test use a Fake window object that we created for testing only. And all the cookie writing logic are faked. Does the Chrome version affect the test result here?

**Comment by estherkim** [comment]
Ohh interesting. Probably not. Maybe my first assumption still stands here.

Do you think this commit https://github.com/ampproject/amphtml/pull/22510 affected the cookie writer test? The timing works out, where 22483's PR passed 2 days ago, then 22510 merged into master, then 22483 merged after that.

**Comment by zhouyx** [comment]
I also suspected that, but I couldn't see anything obvious. Let me run a quick test

**Comment by zhouyx** [comment]
@estherkim You're right! That's exactly what happened. Here's what I found:

Here's what our code looks like before #22510 
```
 for (let i = parts.length - 2; i >= 0; i--) {
      domain = parts[i] + '.' + domain;
      trySetCookie(win, name, value, expirationTime, domain);
      if (getCookie(win, name) == value) {
        return;
      }
    }
  }
  let domain = undefined;
  ...
   trySetCookie(win, name, value, expirationTime, domain);
```

The implementation has an issue, that if the expirationTime is before the current time, we would never be able to use `#getCookie()` to get back the value we just set (It will be regarded by our fake dom [implementation](https://github.com/ampproject/amphtml/blob/master/testing/fake-dom.js#L120-L156)), thus eventually the cookie is written to undefined domain. 

#22510 change the cookie writing implementation to the following
```
if (opt_options && opt_options.highestAvailableDomain) {
    domain = getHighestAvailableDomain(win);
  }
trySetCookie(win, name, value, expirationTime, domain);
```
Where the getHighestAvailableDomain can always be found regardless of the expirationTime. Thus the domain has value `example.com`. 

That said, this is the exact right fix to the issue. Thank you all!

**Comment by zhouyx** [comment]
And lesson learned: rebase before merge commit : )

**Comment by calebcordry** [comment]
Thanks for the summary @zhouyx !

**Pull request merged**
