### PR TITLE
Launch amp-story-branching experiment.

### PR DESCRIPTION
**Pull request by gmajoulet**
Soft launching the `amp-story-branching` experiment, with no public documentation for now.

### CODE REVIEW

**Comment by newmuis** [comment]
Is there something to gain from being in the soft launched state?  Are there specific things we're looking for?  What are the entrance and exit criteria?

**Comment by gmajoulet** [comment]
This is mostly meant to move forward with the branching feature :) @Enriqe will follow up with public documentation

**Comment by gmajoulet** [comment]
Friendly ping

**Comment by newmuis** [comment]
I think @Enriqe is working on a document of what needs to be resolved before launching this experience, right?

**Pull request closed without merging**
