### PR TITLE
Fixed variable names to lowercase for e-planning integration

### PR DESCRIPTION
**Pull request by sebaperez**
E-Planning integration has an error, as variables names for parameters were not in lowercase

### CODE REVIEW

**Comment by sebaperez** [comment]
Please can you take a look? Thanks!

**Comment by cramforce** [comment]
LGTM

**Comment by cramforce** [comment]
@sebaperez: Really quick: What is your relationship to E-Planning? Was this just plain broken before?

**Comment by sebaperez** [comment]
@cramforce I work in E-Planning as front-end developer. Yes, it was. Now it is fixed. Thanks

**Comment by cramforce** [comment]
Thanks!

**Pull request merged**
