### PR TITLE
📦 Upgrade colors dependency in NodeJS validator

### PR DESCRIPTION
**Pull request by benmccann**
`colors` 1.2.5 is three years old. Its inclusion is causing the warnings below in my project. This was fixed in 1.3.1 (https://github.com/Marak/colors.js/issues/233)

>(!) Circular dependencies
../../node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/colors.js -> ../../node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/maps/america.js -> ../../node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/colors.js
../../node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/colors.js -> ../../node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/maps/america.js -> /home/bmccann/src/kit/node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/colors.js?commonjs-proxy -> ../../node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/colors.js
../../node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/colors.js -> ../../node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/maps/zebra.js -> ../../node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/colors.js
...and 3 more

### CODE REVIEW

**Comment by benmccann** [comment]
The CLA tools is currently down. It's getting a 401 when calling https://cla-assistant.io/api/github/call. I've signed numerous Google CLAs in the past. Perhaps you can utilize one of those in its place or fix the CLA Assistant?

**Review by MichaelRybak — APPROVED** [review]

**Comment by benmccann** [comment]
@MichaelRybak @honeybadgerdontcare just checking in on this. Is there anything it's waiting for to be merged since it's been approved? Thanks!

**Comment by honeybadgerdontcare** [comment]
@benmccann It may have been overlooked due to the holidays. Thanks for reminding us!

**Comment by honeybadgerdontcare** [comment]
This has been released as v.1.0.34
https://www.npmjs.com/package/amphtml-validator/v/1.0.34

**Comment by benmccann** [comment]
thanks!!

**Pull request merged**
