### PR TITLE
✅Change domains on tests for ads/analytics

### PR DESCRIPTION
**Pull request by powerivq**
To avoid any inadvertently sending of a request to a real domain.

ICANN guarantees not to register `.test` domains so they can safely be used.

### CODE REVIEW

**Comment by zhouyx** [comment]
I believe that's also the case for example.com, that it can be used as illustrative examples in documents without prior coordination?

**Comment by powerivq** [comment]
@zhouyx example.com is registered and is running by ICANN (click https://www.example.com), and we don't want its behavior to dictate the tests.

**Comment by zhouyx** [comment]
Interesting, does the response fail our tests? I'm good with the change, but you may want to enforce it via the pre-submit check? Otherwise we will still be using `example.com` all over the place.

**Comment by powerivq** [comment]
@zhouyx presubmit is on the radar. There are a ton of these in the codebase, so it will not be solved in a single PR.

**Comment by zhouyx** [comment]
SG

**Pull request merged**
