### PR TITLE
🚮 Update README.md

### PR DESCRIPTION
**Pull request by sudhanemani**
Removed Contributors count tag as the count includes anonymous.

### CODE REVIEW

**Comment by mrjoro** [comment]
@rsimha and @sudhanemani are looking into why they don't line up.

I'm okay removing the badge, though, since it just duplicates info visible elsewhere on the page.

**Comment by rsimha** [comment]
Figured out why. The badge was something I added via http://shields.io. The issue comments at https://github.com/badges/shields/issues/764 describe why the metric is inaccurate.

I too am okay with removing the badge.

**Comment by estherkim** [comment]
Related issue - https://github.com/ampproject/amp-github-apps/issues/475

**Comment by sudhanemani** [comment]
@rsimha I don't have merge access. Can you please merge or let me know what to do?

**Comment by rsimha** [comment]
@sudhanemani Two things left to do:

1. Sign the google CLA to satisfy the `cla/google` check
2. Get a review from an owner who is part of the `reviewers-amphtml` team

/cc @rcebulko who is working on making item 2 happen automatically

**Comment by rcebulko** [comment]
@rsimha Looks like that reviewer is you ;)

**Comment by rsimha** [comment]
> @rsimha Looks like that reviewer is you ;)

From [this](https://github.com/ampproject/amphtml/pull/24964/checks?check_run_id=252598565) check, looks like my approval is insufficient?

**Comment by rcebulko** [comment]
@rsimha your approval would be sufficient for the ''reviewers'' requirement; CrystalOnAScript was added as the owner, and she hasn't approved yet

**Comment by rcebulko** [comment]
@sudhanemani Have you had the chance to sign the CLA yet? That's the only thing blocking this from submitting

**Comment by mrjoro** [comment]
@sudhanemani you should be covered as a Googler, but you'll need to make sure your GitHub account is on the right list.  I'll send you instructions.

**Comment by mrjoro** [comment]
@googlebot rescan please

**Comment by mrjoro** [comment]
CLA is now signed, but it looks like there are some conflicts that need to be resolved.

**Comment by rsimha** [comment]
@sudhanemani a few points:

- There are command-line instructions above for how to resolve branch conflicts. Let @ampproject/wg-infra know if you run into problems.
- The boilerplate text in the description can be deleted.
- The words `Deleting code` in the title can be deleted (the emoji is sufficient).
- Adding the words `Fixes https://github.com/ampproject/amp-github-apps/issues/475` to the PR description will indicate to github that this PR fixes (and closes) https://github.com/ampproject/amp-github-apps/issues/475.

Hope this is helpful.

**Comment by rcebulko** [comment]
@sudhanemani Is this still active?

**Comment by sudhanemani** [comment]
I made a the changes requested to resolve the conflict - removed boilerplate description, updated title. Anything else I need to do to resolve the conflicts?

**Comment by rcebulko** [comment]
> I made a the changes requested to resolve the conflict - removed boilerplate description, updated title. Anything else I need to do to resolve the conflicts?

It's hard to tell from here since I can't see your workspace, but if you push your changes we'll find out :)

**Comment by rcebulko** [comment]
@sudhanemani It looks like there's a merge conflict in `README.md`. You can either resolve via the Web UI or in your local branch, commit, and push the changes.

**Comment by rsimha** [comment]
@sudhanemani, IIRC, this was your first AMP pull request. Glad it got merged, and thanks for persisting through all the comments :)

**Comment by rcebulko** [comment]
Congratulations on closing your first issue!

**Pull request merged**
