### PR TITLE
♻️ springAds: refactoring computeInMasterFrame

### PR DESCRIPTION
**Pull request by renebaudisch**
because computeInMasterFrame is not working as expected and renderAd never get's invoked right now

### CODE REVIEW

**Comment by calebcordry** [comment]
Thanks for maintaining this extension! Would you be willing to open an issue describing your problems with `computeInMasterFrame`?

**Comment by calebcordry** [comment]
cc/ @ampproject/wg-monetization

**Comment by renebaudisch** [comment]
What's left? I hoped to be merged before release freeze...

**Comment by calebcordry** [comment]
@renebaudisch Thanks for creating the issue! Did you see the comment about changing window to global? As long as we get this in by Friday you should make the next cut.

**Comment by renebaudisch** [comment]
No, sorry, did see that, but great I'll commit

**Comment by calebcordry** [comment]
`global` should be the iframe window here. We are just trying to remove any direct access to window, document, etc as sometimes they introduce weird bugs.

**Review by calebcordry — APPROVED** [review]

**Comment by calebcordry** [comment]
Thanks for maintaining this extension!

**Pull request merged**
