### PR TITLE
♻️ Migrate most remaining type helpers to src/core/types

### PR DESCRIPTION
**Pull request by rcebulko**
Don't panic! This may touch 397 files, but almost all of those are just updates to import statements. The actual changes in this PR are:
- `src/{string,types,utils/{object}}.js` are mostly migrated into `src/core/types/{array,string,object,enum,index}.js` with only a couple stragglers remaining
- tests for `src/core` files now live in `test/unit/core`
- all imports of those helpers have been updated
- build system references to those files have been updated

Here is the diff you probably care about reviewing: https://github.com/ampproject/amphtml/compare/b0e7462...594c18e
It excludes 3 rather large commits filled with import updates.

### CODE REVIEW

**Comment by rcebulko** [comment]
Total bundle size reduction of 4.3KB across all binaries 

Bundle-size highlights:
```
Δ -0.13KB : dist/v0.js
Δ -0.09KB : dist/v0/amp-date-picker-0.1.js
Δ -0.08KB : dist/v0/amp-ad-network-adzerk-impl-0.1.mjs
Δ -0.07KB : dist/v0/amp-ad-network-doubleclick-impl-0.1.js
Δ -0.07KB : dist/v0/amp-ad-custom-0.1.js
Δ -0.05KB : dist/v0/amp-twitter-1.0.mjs
Δ -0.05KB : dist/v0/amp-timeago-1.0.mjs
Δ -0.04KB : dist/v0/amp-story-auto-ads-0.1.js
Δ -0.04KB : dist/v0/amp-story-1.0.mjs
Δ -0.04KB : dist/v0/amp-story-0.1.mjs
Δ -0.04KB : dist/v0/amp-mustache-0.2.mjs
Δ -0.04KB : dist/v0/amp-date-display-1.0.js
Δ -0.04KB : dist/v0/amp-base-carousel-1.0.js
Δ -0.04KB : dist/v0/amp-ad-network-doubleclick-impl-0.1.mjs
```

**Comment by samouri** [comment]
@rcebulko: can you explain why the build size goes down?

**Comment by rcebulko** [comment]
> @rcebulko: can you explain why the build size goes down?

I'm quite unsure, I'm in the process of comparing binary output right now lol

**Comment by rcebulko** [comment]
@samouri Looking at the actual v0.js I just built from main and this branch locally, I see almost zero difference (as expected). Wondering if this is a bundle-size bot quirk?

**Review by jridgewell — APPROVED** [review]

**Pull request merged**
