### PR TITLE
⏪ Revcontent ad: make id the only required attribute, add feed

### PR DESCRIPTION
**Pull request by oste**

### CODE REVIEW

**Comment by torch2424** [comment]
Hello! Thanks for contributing. Could you provide an issue, or more context on what this Pull request does? Thanks!

**Comment by torch2424** [comment]
@oste 

Thank you! So could you do the following:

* Fix the travis tests, seems like there are some linting errors
* Update documentation to reflect this for your users.

Then I'll go ahead and do a review. Thanks! 😄

**Comment by mrjoro** [comment]
Hi @oste, is this PR still active?

**Comment by mrjoro** [comment]
Hi @oste; since we haven't heard back from you in a while I'll go ahead and close this PR.  Please reopen it if it's still a change you'd like to make.

**Pull request closed without merging**
