### PR TITLE
Delete bundled ampToolboxCacheUrl in favor of new node_module

### PR DESCRIPTION
**Pull request by Enriqe**
I noticed that the `amp-recaptcha-service.js` is using an outdated bundled version of the [AMP-Toolbox Cache URL](https://github.com/ampproject/amp-toolbox/tree/master/packages/cache-url), and since we just added the `toolbox-cache-url` to the repo as a node_module in #27589, I thought it would be appropriate to delete this outdated bundle so no new components depend on it.

### CODE REVIEW

**Comment by kristoferbaxter** [comment]
Looks like there are errors during the build for this PR.

`[21:46:20] ERROR: Error: Cannot find module '../third_party/amp-toolbox-cache-url/dist/amp-toolbox-cache-url.esm' from '/home/travis/build/ampproject/amphtml/3p'`

**Comment by Enriqe** [comment]
Just sent https://github.com/ampproject/amp-toolbox/pull/701. After it is merged, these errors should go away...

**Comment by kristoferbaxter** [comment]
Did you use `yarn link` and verify the change to `amp-toolbox` eliminates the error locally when checking types? I'd be surprised adding TypeScript types to the package removes the Closure error.

**Comment by Enriqe** [comment]
Ah, didn't know `yarn link` existed, that's pretty cool. 

You're right in that adding types and the Closure errors are different things. Adding types was only needed to address a warning by VSCode, but did not fix the Closure errors.

I'm having a bit of trouble fixing the Closure error:
```
extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js:293: 
Originally at:
extensions/amp-recaptcha-input/0.1/extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js:293: 
ERROR - [JSC_POSSIBLE_INEXISTENT_PROPERTY] Property createCurlsSubdomain never defined on module$$ampproject$toolbox_cache_url
```
It looks like we actually export that property here:
https://github.com/ampproject/amp-toolbox/blob/4661e5ed362d34405ad4a8ea2c5c331bb537f8d5/packages/cache-url/index.js#L28

Interestingly, it's only the `createCurlsSubdomain` that throws an error, when trying to use the other `createCacheUrl` property, there are no errors. 

It looks like the original function has a `@private` annotation, which I thought was causing the issue... https://github.com/ampproject/amp-toolbox/blob/4661e5ed362d34405ad4a8ea2c5c331bb537f8d5/packages/cache-url/lib/AmpCurlUrlGenerator.js#L70

But after fixing that and testing locally I am still getting the error. 

Since the module is exported using the `default` export, I tried importing it like this:
`import * as ampToolboxCacheUrl from '@ampproject/toolbox-cache-url';`
`import AmpUrl from '@ampproject/toolbox-cache-url';`

But none of those options seem to do the trick... Am I doing something wrong? any ideas??

**Comment by Enriqe** [comment]
@jridgewell could you help me find the issue here? 

I'm trying to import `createCurlsSubdomain` which is exported [here](https://github.com/ampproject/amp-toolbox/blob/4661e5ed362d34405ad4a8ea2c5c331bb537f8d5/packages/cache-url/index.js#L27), but I get this error:

```
Error: Unknown dependency createCurlsSubdomain$$module$$ampproject$toolbox_cache_url found in recaptcha.js
```

**Comment by mrjoro** [comment]
Is this PR still active?

**Pull request closed without merging**
