### PR TITLE
♿ amp-accordion: Respect pre-existing role attribute

### PR DESCRIPTION
**Pull request by caroqliu**
Related to #32549

### CODE REVIEW

**Review by krdwan — COMMENTED** [review]
Should we add a unit test for this?

**Comment by caroqliu** [comment]
> Changes look good.
> 
> Should we add a unit test for this?

Good catch, done!

**Review by krdwan — APPROVED** [review]
Great!  LGTM

**Review by jridgewell — APPROVED** [review]
Bundle size bot's borked.

**Pull request merged**
