### PR TITLE
Move service getters to static class functions

### LINKED ISSUE #10128: Testing: Easier stubbing of services
Since this has come up a few times now. Context: https://github.com/ampproject/amphtml/pull/9866#discussion_r123108935

We could do this pretty simply by changing `services.js` to export an object/class instead of `serviceForDoc` functions. Could be nice for classes that need a lot of services stubbed.

### Before
```js
// services.js
actionServiceForDoc(nodeOrDoc) { ... }

// my-class.js
import {actionServiceForDoc} from '../src/services';
class MyClass {
  foo() {
    this.actionService().doSomething();
  }
  actionService() { // This is annoying to do for every service.
    return actionForDoc(this.ampdoc);
  }
}

// my-test.js
import {MyClass} from '../src/my-class.js';
sandbox.stub(MyClass, 'actionService').returns(mockActionService);
```

### After
```js
// services.js
export class Services {
  static actionForDoc(nodeOrDoc) { ... }
}

// my-class.js
import {Services} from '../src/services';
class MyClass {
  foo() {
    Services.actionForDoc(this.ampdoc).doSomething();
  }
}

// my-test.js
import {Services} from '../src/services';
sandbox.stub(Services, 'actionForDoc').returns(mockActionService);
```
It'd be a straightforward (if slightly annoying) refactor. I also checked that this would work with Babel's transpile. 

/cc @lannka @alanorozco @keithwrightbos @taymonbeal @jridgewell

### PR DESCRIPTION
**Pull request by choumx**
Fixes #10128.

- No logic changes. 
- Should be safe since this was done mechanically with find/replace and the methods are type-checked.
- I'm so sorry.

### CODE REVIEW

**Comment by jridgewell** [comment]
Merge conflicts. 😛

**Comment by choumx** [comment]
Fixed (for now)!

**Comment by choumx** [comment]
You da real mvp. 🙏

**Pull request merged**
