### PR TITLE
Pr to merge

### PR DESCRIPTION
**Pull request by erwinmombay**

### CODE REVIEW

**Comment by ampsauce** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: d3e4cc07b6f0100aea24198796ea4eb78acef36c
Build details: https://travis-ci.org/ampsauce/amphtml/builds/86870139

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by erwinmombay** [comment]
@kassyn can you post here with "I authored these commits", and i can have your changes merged in. Thanks!

**Comment by kassyn** [comment]
I authored these commits.

**Comment by ampsauce** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 9c2a5d8a12a8b117a41492de1d463d76e9d97ccf
Build details: https://travis-ci.org/ampsauce/amphtml/builds/86883768

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by ampsauce** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 9f1104338c6856382d7b56bf93f429cddc5a15c2
Build details: https://travis-ci.org/ampsauce/amphtml/builds/86886420

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Pull request closed without merging**
