### PR TITLE
trigger submit event in xhr action

### LINKED ISSUE #7245: amp-form on=submit event not firing
Without any changes to the client side code, this started happening on 1/27/2017.

submit-success -> fires
submit-error -> fires
submit -> does NOT fire,

Code:
`<form method="post" action-xhr="https://www.roboform.com/filling-test-all-fields" target="_top" on="submit:success-lightbox;submit-success:success-lightbox.close;">...</form>`

### PR DESCRIPTION
**Pull request by mkhatib**
Fixes #7245

### CODE REVIEW

**Comment by camelburrito** [comment]
LGTM - @dvoytenko can you take a pass.

**Comment by dvoytenko** [comment]
@mkhatib I'm a bit confused. Do we use "submit" as both "do submit form" and "form has been submitted"? How is this does not cause recursion?

**Comment by mkhatib** [comment]
`trigger(submit)` is just an event notifier to tell action impl to invoke any handler that is listening for that submit even, for example, `on=submit:target.action` calling trigger(submit) will cause the `target.action` to execute, not the actual submission.

This is different from using `execute(submit)`. Which would cause the actual submit event to be triggered and hence would cause a recursion.

So the current flow is the following:

```html
<div id="any-target"></div>
<form id="form" on="submit:any-target.any-action">
   <button on="tap:form.submit"></button>
   <input type="submit">
</form>
```

* User submits a form through normal submit OR throw tapping a button with on="tap:form.submit" 
* In normal submit, `document-submit` would turn that submit event into a `action.execute(submit)` which basically `invoke(form, submit)` to queue this until `amp-form` is loaded.
* In the on="tap:form.submit" method, same thing would happen through the `action-service`
   * `action-impl` -> `trigger(tap)` -> `invoke(form, submit)`

* The action-handler we install inside `amp-form` handles invocations to `form, submit`.
* Inside the xhr-submission handler we `trigger` a `submit` event
  * The `action-impl` translates this to `invoke(any-target, any-action)` (NOT to `invoke(form, submit)`) 

This is slightly confusing I agree, maybe we need better terminology and better differentiation between `trigger` and `execute`. But from my testing and code-walkthrough this wouldn't cause recursion UNLESS users made the mistake of causing a recursion (e.g. `<form id=form on="submit:form.submit">`) which is a different problem that we probably should catch (if we don't already). I can file an issue for us to take a deeper look at this later.

**Comment by dvoytenko** [comment]
@mkhatib so what happens with 
```
<form id="form" on="submit:form.submit">
```

**Comment by mkhatib** [comment]
It would have recursed if we didn't have a `is-submitting` check in the submit handler. So the second time the submit gets called it returns because the form is still submitting - however, yes, there is a duplicate firing event that happens.

Of course this kind of behavior might happen out side of form submission if one is not careful. For example, this [could've been the case for `amp-carousel` if they were firing the event in the action-triggered slide change - I filed a discussion issue here](https://github.com/ampproject/amphtml/issues/7337) - Carousel currently doesn't fire the event in that case - which might be the intended behavior or not.

Any advice how to proceed with this?

**Comment by dvoytenko** [comment]
> however, yes, there is a duplicate firing event that happens.

Can we remove dupe event?

> It would have recursed if we didn't have a is-submitting check in the submit handler.

This is something we need to add to unit tests.

**Comment by mkhatib** [comment]
> Can we remove dupe event?

Sorry. It's not really a dupe. I meant to say that our submit action handler will trigger again (in response to the `on=submit:**form.submit**`. But that submit won't be processed because the form is already being submitted.

Do you think adding tests here is enough?

> This is something we need to add to unit tests.

I can add tests.

**Comment by dvoytenko** [comment]
@mkhatib Ok, got the dup event part. That sounds good.

RE: tests. I'd like to actually define the recursive situation, trigger it and confirm that the submit is not called second time.

**Comment by mkhatib** [comment]
Done. @dvoytenko PTAL 👀

**Pull request merged**
