### PR TITLE
Disallow amp-youtube in amp4ads

### PR DESCRIPTION
**Pull request by powerivq**
I2I sent in March, deprecation notice sent in July

https://github.com/ampproject/amphtml/issues/21340

### CODE REVIEW

**Comment by Gregable** [comment]
@lannka

**Comment by honeybadgerdontcare** [comment]
Please also update [extensions.html](https://github.com/ampproject/amphtml/blob/master/validator/testdata/amp4ads_feature_tests/extensions.html#L117) and run `gulp validator --update-tests` to update the corresponding `.out` file.

**Comment by honeybadgerdontcare** [comment]
And also update [validator_test.js](https://github.com/ampproject/amphtml/blob/master/validator/engine/validator_test.js#L1303)

**Comment by powerivq** [comment]
Test updated.

**Pull request merged**
