### PR TITLE
✨ Update amp-access-laterpay for the new LaterPay API

### PR DESCRIPTION
**Pull request by trodrigues**
This updates amp-access-laterpay to use the new LaterPay Connector 2.0 API, including the new data format.

This branch is based off the branch from #14437

Relates to #11733

### CODE REVIEW

**Comment by trodrigues** [comment]
Pinging @jridgewell @dvoytenko for the possibility of getting a review on this.

**Comment by jridgewell** [comment]
This is failing type checks, which means the tests haven't run either. Can you clean those up?

Also, I've not reviewed this PR in its entirety. Instead, here's the diff from v0.1:

```diff
--- extensions/amp-access-laterpay/0.1/laterpay-impl.js	2018-04-13 14:19:27.000000000 -0400
+++ extensions/amp-access-laterpay/0.2/laterpay-impl.js	2018-04-13 14:19:27.000000000 -0400
@@ -14,7 +14,7 @@
  * limitations under the License.
  */
 
-import {CSS} from '../../../build/amp-access-laterpay-0.1.css';
+import {CSS} from '../../../build/amp-access-laterpay-0.2.css';
 import {Services} from '../../../src/services';
 import {dev, user} from '../../../src/log';
 import {dict} from '../../../src/utils/object';
@@ -38,14 +38,13 @@
 
 const DEFAULT_REGION = 'eu';
 
-const CONFIG_BASE_PATH = '/api/v1/public/amp?' +
+const CONFIG_BASE_PATH = '/api/v2/fetch/amp/?' +
                          'article_url=CANONICAL_URL' +
                          '&amp_reader_id=READER_ID' +
                          '&return_url=RETURN_URL';
 const AUTHORIZATION_TIMEOUT = 3000;
 
 const DEFAULT_MESSAGES = {
-  premiumContentTitle: 'Buy only this article',
   payLaterButton: 'Buy Now, Pay Later',
   payNowButton: 'Buy Now',
   defaultButton: 'Buy Now',
@@ -69,28 +68,50 @@
 
 /**
  * @typedef {{
+ *   "amount": number,
+ *   "currency": string,
+ *   "payment_model": string,
+ * }}
+ */
+let PriceDef;
+
+/**
+ * @typedef {{
+ *   "unit": string,
+ *   "value": number
+ * }}
+ */
+let ExpiryDef;
+
+/**
+ * @typedef {{
+ *   title: string,
  *   description: string,
- *   price: !Object<string, number>,
- *   purchase_type: string,
+ *   sales_model: string,
  *   purchase_url: string,
- *   title: string,
- *   validity_unit: string,
- *   validity_value: number
+ *   price: PriceDef,
+ *   expiry: ExpiryDef
  * }}
  */
 let PurchaseOptionDef;
 
 /**
  * @typedef {{
- *   access: boolean,
- *   apl: string,
- *   premiumcontent: !PurchaseOptionDef,
- *   timepasses: (!Array<PurchaseOptionDef>|undefined),
- *   subscriptions: (!Array<PurchaseOptionDef>|undefined)
+ *   identify_url: string,
+ *   purchase_options: Array<PurchaseOptionDef>
  * }}
  */
 let PurchaseConfigDef;
 
+/**
+ * @typedef {{
+ *   singlePurchases: Array<PurchaseOptionDef>
+ *   timepasses: Array<PurchaseOptionDef>
+ *   subscriptions: Array<PurchaseOptionDef>
+ * }}
+ */
+let PurchaseOptionsDef;
+
 
 /**
  * @implements {../../amp-access/0.1/access-vendor.AccessVendor}
@@ -117,6 +138,9 @@
     /** @private {?JsonObject} For shape see PurchaseConfigDef */
     this.purchaseConfig_ = null;
 
+    /** @private {?Object} For shape see PurchaseOptionsDef */
+    this.purchaseOptions_ = null;
+
     /** @private {?Function} */
     this.purchaseButtonListener_ = null;
 
@@ -152,6 +176,12 @@
       this.purchaseConfigBaseUrl_ +=
         '&article_id=' + encodeURIComponent(articleId);
     }
+    const jwt = this.laterpayConfig_['jwt'];
+    if (jwt) {
+      this.purchaseConfigBaseUrl_ +=
+        '&jwt=' + encodeURIComponent(jwt);
+    }
+
 
     /** @const @private {!../../../src/service/timer-impl.Timer} */
     this.timer_ = Services.timerFor(this.ampdoc.win);
@@ -211,6 +241,8 @@
           }
           return response.json().catch(() => undefined).then(responseJson => {
             this.purchaseConfig_ = responseJson;
+            this.purchaseOptions_ = this.parseConfigIntoOptions_(
+                responseJson.purchase_options);
             // empty before rendering, in case authorization is being called again
             // with the same state
             this.emptyContainer_()
@@ -242,6 +274,28 @@
   }
 
   /**
+   * @param {Array<PurchaseOptionDef>} purchaseOptionsList
+   * @return Object
+   * @private
+   */
+  parseConfigIntoOptions_(purchaseOptionsList) {
+    const articleTitle = this.getArticleTitle_();
+    const purchaseOptions = {};
+    purchaseOptions['singlePurchases'] = purchaseOptionsList.filter(
+        option => option['sales_model'] === 'single_purchase'
+    );
+    purchaseOptions['singlePurchases'].forEach(
+        option => option.description = articleTitle);
+    purchaseOptions['timepasses'] = purchaseOptionsList.filter(
+        option => option['sales_model'] === 'timepass'
+    );
+    purchaseOptions['subscriptions'] = purchaseOptionsList.filter(
+        option => option['sales_model'] === 'subscription'
+    );
+    return purchaseOptions;
+  }
+
+  /**
    * @return {!Element}
    * @private
    */
@@ -315,17 +369,13 @@
     }
     this.renderTextBlock_('header');
     const listContainer = this.createElement_('ul');
-    this.purchaseConfig_['premiumcontent']['title'] =
-      this.i18n_['premiumContentTitle'];
-    this.purchaseConfig_['premiumcontent']['description'] =
-        this.getArticleTitle_();
-    listContainer.appendChild(
-        this.createPurchaseOption_(this.purchaseConfig_['premiumcontent'])
-    );
-    this.purchaseConfig_['timepasses'].forEach(timepass => {
+    this.purchaseOptions_['singlePurchases'].forEach(singlePurchase => {
+      listContainer.appendChild(this.createPurchaseOption_(singlePurchase));
+    });
+    this.purchaseOptions_['timepasses'].forEach(timepass => {
       listContainer.appendChild(this.createPurchaseOption_(timepass));
     });
-    this.purchaseConfig_['subscriptions'].forEach(subscription => {
+    this.purchaseOptions_['subscriptions'].forEach(subscription => {
       listContainer.appendChild(this.createPurchaseOption_(subscription));
     });
     const purchaseButton = this.createElement_('button');
@@ -340,7 +390,7 @@
     this.innerContainer_.appendChild(listContainer);
     this.innerContainer_.appendChild(purchaseButton);
     this.innerContainer_.appendChild(
-        this.createAlreadyPurchasedLink_(this.purchaseConfig_['apl']));
+        this.createAlreadyPurchasedLink_(this.purchaseConfig_['identify_url']));
     this.renderTextBlock_('footer');
     dialogContainer.appendChild(this.innerContainer_);
     dialogContainer.appendChild(this.createLaterpayBadge_());
@@ -425,7 +475,7 @@
     radio.type = 'radio';
     radio.id = option['title'];
     radio.value = option['purchase_url'];
-    const purchaseType = option['purchase_type'] === 'ppu' ?
+    const purchaseType = option['price']['payment_model'] === 'pay_later' ?
       'payLater' :
       'payNow';
     const purchaseActionLabel = this.i18n_[purchaseType + 'Button'];
@@ -443,14 +493,13 @@
    * @private
    */
   createPrice_(price) {
-    const currency = Object.keys(price)[0];
-    const formattedPrice = this.formatPrice_(price[currency]);
+    const formattedPrice = this.formatPrice_(price['amount']);
     const valueEl = this.createElement_('span');
     valueEl.className = TAG + '-price';
     valueEl.textContent = formattedPrice;
     const currencyEl = this.createElement_('sup');
     currencyEl.className = TAG + '-currency';
-    currencyEl.textContent = currency;
+    currencyEl.textContent = price['currency'];
     const priceEl = this.createElement_('p');
     priceEl.className = TAG + '-price-container';
     priceEl.appendChild(valueEl);
```

**Comment by trodrigues** [comment]
Oh apologies, I didn't check these locally because I didn't want to install the separate java package and forget to check again after pushing the PR. I'll clean them up.

**Comment by trodrigues** [comment]
Ok so I've managed to fix the type checking errors but now there is a validator error which I'm not really sure how to fix. Is there something I can do about this?

**Comment by honeybadgerdontcare** [comment]
It's failing because there is no validator protoascii for this new version of amp-access-laterpay.

**Comment by honeybadgerdontcare** [comment]
@trodrigues You'll need to update [validator-amp-access-laterpay.protoascii](https://github.com/ampproject/amphtml/blob/master/extensions/amp-access-laterpay/validator-amp-access-laterpay.protoascii)

**Comment by trodrigues** [comment]
Ok, I fixed the validator. Not sure why percy is failing now but I also seem to not have access to that.

**Comment by trodrigues** [comment]
Thanks! I'm assuming the release cycle is still similar to what it was about a year ago? I haven't made any changes to this since then.

**Comment by jridgewell** [comment]
Yup, it's missed this week's canary, so it'll go out in next weeks (Tuesday). Then, after another week, it'll go into prod.

**Pull request merged**
