### PR TITLE
🐛✨Snowplow Analytics: Fix timezone/timestamp issue and add document size field

### PR DESCRIPTION
**Pull request by max-tgam**
- Address issue with timestamp field being set twice (and last value being set incorrectly to timezone)
- Address issue with timezone field being set to timezone offset instead of IANA time-zone code (as per [Snowplow Canonical Event Model](https://github.com/snowplow/snowplow/wiki/canonical-event-model#date-time) )
- Implement document size field (minor feature)

### CODE REVIEW

**Comment by max-tgam** [comment]
cc. @lannka & @zhouyx
Could you review this PR?

**Comment by zhouyx** [comment]
@max-tgam Looks like the unit test is broken. I couldn't merge the PR because of that. Could you please take a look. Thanks

**Comment by zhouyx** [comment]
@max-tgam Sorry for the delay. I was out of office for a while. I restarted the build and got all tests passed. The PR has been merged. Thank you!

**Comment by max-tgam** [comment]
@zhouyx Thank you!

**Pull request merged**
