### PR TITLE
Removed restriction on universal selector

### PR DESCRIPTION
**Pull request by dvoytenko**
Closes #3375.

/cc @cramforce, @azizhk, @jpettitt.

### CODE REVIEW

**Comment by jridgewell** [comment]
@Gregable, is there any validator changes that need to be made? If so, can you link here?

**Comment by Gregable** [comment]
There are none. This change to the docs is actually to match more closely the validator's behavior.

**Comment by bkniffler** [comment]
You guys should update https://www.ampproject.org/docs/guides/author-develop/responsive/style_pages

**Comment by dvoytenko** [comment]
Filed https://github.com/ampproject/docs/issues/367. 
/cc @bpaduch

**Pull request merged**
