### PR TITLE
Using location.href instead of location.origin for nativo.js AD script

### PR DESCRIPTION
**Pull request by antnativo**
@cramforce Please merge. Only one small change

### CODE REVIEW

**Comment by antnativo** [comment]
I signed it!

**Comment by lannka** [comment]
@antnativo could you help fix the example in `ads.amp.html`? It doesn't load an ad. Because that helps me to check if the PR breaks anything.

**Comment by antnativo** [comment]
@lannka @jridgewell The ad example should work now. Please accept the pull request.

**Comment by antnativo** [comment]
@lannka @jridgewell @cramforce. The ad should be working now. Please accept pull request.

**Comment by jridgewell** [comment]
LGTM.

**Pull request merged**
