### PR TITLE
Allow <amp-story-consent> to have children

### PR DESCRIPTION
**Pull request by choumx**
Stepping stone for moving story consent UI template data to its own child `<script>` tag.

Context: https://github.com/ampproject/amphtml/pull/15366/files/f48b29ca4203dd4cfce001b9555128d307551c7b#r189401119

### CODE REVIEW

**Comment by honeybadgerdontcare** [comment]
@choumx shouldn't this be tied together with restricting the child tag to just one and that one being the script json? I'm not keen on making something more permissive if it's only get more restrictive shortly.

**Comment by choumx** [comment]
@honeybadgerdontcare Ideally, I agree. The thought here was "temporary permissiveness" is better than "temporary invalid AMPs". If we can get the full implementation in before EOD, I'll drop this PR.

**Comment by honeybadgerdontcare** [comment]
@choumx here's what I think full implementation would look like for validation
https://github.com/ampproject/amphtml/pull/15468

**Comment by choumx** [comment]
Closing in favor of #15474.

**Pull request closed without merging**
