### PR TITLE
🐛 Update preconnects in amp-youtube component

### PR DESCRIPTION
**Pull request by westonruter**
I just analyzed the resources which are loaded in a YouTube embed and they include:

* `fonts.gstatic.com` (for the fonts used in the title)
* `yt3.ggpht.com` (for the channel logo)
* `i.ytimg.com` (for the poster image)
* `www.youtube.com` (for JS and CSS assets)
* `www.gstatic.com` (for more JS assets)

Notably, `s.ytimg.com` is _not_ among the domains that resources are loaded from, although it is still being preconnected to:

https://github.com/ampproject/amphtml/blob/dccbba6692d322f9843c856bd21d9dcc693291a1/extensions/amp-youtube/0.1/amp-youtube.js#L117-L121

I suggest removing this preconnect and instead replace it with a preconnect to `fonts.gstatic.com` since it is used to render the title text which is the actual LCP element (since the poster background image is excluded based on the [current LCP heuristics](https://web.dev/articles/lcp#:~:text=Elements%20that%20cover%20the%20full%20viewport%2C%20that%20are%20likely%20to%20be%20background%20elements.)).

### CODE REVIEW

**Review by erwinmombay — APPROVED** [review]

**Comment by erwinmombay** [comment]
thanks @westonruter

**Comment by erwinmombay** [comment]
re-running jobs so we can merge

**Comment by erwinmombay** [comment]
@westonruter do you mind rebasing and re-pushing, ill try and get the tests green but i can seem to retrigger the bundle size to get it to pass

**Comment by westonruter** [comment]
@erwinmombay done, although I've also updated it to just remove the preconnect for fonts.gstatic.com. I found that no assets from that domain are loaded at all when emulating a mobile device. Fonts are only loaded on desktop. Since most AMP pages are served to mobile, it's probably best to just omit the fonts preconnect.

**Comment by erwinmombay** [comment]
@westonruter merged

**Pull request merged**
