### PR TITLE
Launch amp-fx='fade-in'/'fade-in-scroll'

### PR DESCRIPTION
**Pull request by nainar**
This turns on `<amp-fx="fade-in">` and `<amp-fx="fade-in-scroll">`. 

Before landing need the following:
- [x] ABE for fade-in-scroll to land: https://github.com/ampproject/amp-by-example/pull/1263
- [x] Code clean up PR to land: https://github.com/ampproject/amphtml/pull/15246
- [x] UX approval

### CODE REVIEW

**Comment by rsimha** [comment]
Was this supposed to have been landed? Commit log of https://github.com/ampproject/amphtml/commit/324478e900a6cf927f501e0b933f32ffd0121ac3 says `DO NOT LAND`.

**Comment by nainar** [comment]
It is supposed to land - I changed the title to remove that and then clicked merge - it seems to have kept it's old title though :/

**Comment by rsimha** [comment]
Aha, that's a quirk of Github. The commit title can be changed while merging a PR, but it's not obvious.

**Comment by nainar** [comment]
I should have done that. Would you like me to revert and then reland with the commit title changed?

**Comment by rsimha** [comment]
No worries, this is purely cosmetic. Besides, the commit log on `master` won't be rolled back by this :)

**Pull request merged**
