### PR TITLE
request for integrating adman ad-server #2

### PR DESCRIPTION
**Pull request by anmarkom**
This PR provides support for [ADMAN](http://adman.gr/), the most widely used Ad Server in Greece. It is also used by publishers, advertisers and agencies in various other countries and serves many dozens of billions impressions per month.

* I have signed CLA on behalf of Phaistos Networks S.A.

### CODE REVIEW

**Comment by anmarkom** [comment]
I signed it!

**Comment by cramforce** [comment]
Please squash commits and this is good to go!

**Comment by anmarkom** [comment]
I've merged the commits. Thank you!

**Comment by anmarkom** [comment]
@cramforce does it need anything else to be merged to master?

**Comment by jridgewell** [comment]
Assigning to @dvoytenko.

**Comment by dvoytenko** [comment]
@anmarkom You will also need to rebase your branch since it now has conflicts with master. Please do and I should be able to merge then.

**Pull request closed without merging**
