### PR TITLE
using global.context.sourceUrl in PubMatic UAS ad tag

### PR DESCRIPTION
**Pull request by pm-harshad-mane**
# Instructions:
- Using global.context.sourceUrl in PubMatic UAS ad tag

### CODE REVIEW

**Comment by pm-harshad-mane** [comment]
We (PubMatic) have signed the CLA but we always face this issue.

**Comment by pm-harshad-mane** [comment]
Hello @lannka and @zhouyx ,
Can you please help us with this PR?
https://github.com/ampproject/amphtml/pull/18292 shows that we have signed the CLA.

**Comment by lannka** [comment]
yes, I was able to verify that PubMatic is on the signed CLA list.

**Comment by pm-harshad-mane** [comment]
Thank you @lannka

**Pull request merged**
