### PR TITLE
Revcontent AdNetwork Service 1.0 (RELEASE)

### PR DESCRIPTION
**Pull request by e2corporation**
Integrating Revcontent as a Native Ad provider type for AMPHTML. This is a 1.0 release package.

Signed-off-by: Julien Chinapen <j.c@shogun.io>

### CODE REVIEW

**Comment by e2corporation** [comment]
@googlebot CLA Signed on behalf of Corporation "Revcontent, LLC"

**Comment by cramforce** [comment]
LGTM. Thank you!

**Comment by e2corporation** [comment]
Awesome -- Thanks Malte!

**Comment by e2corporation** [comment]
@cramforce Will master get rebuilt to the CDN **0.js** Asset today by chance? ( https://cdn.ampproject.org/v0.js ). We are waiting to publish some demo pages and would like to use your CDN Endpoint.

**Comment by cramforce** [comment]
Most likely not until Wednesday because today is a holiday in the US.

**Pull request merged**
