### PR TITLE
Amp timeline

### PR DESCRIPTION
**Pull request by fcuda**
Implements AMP Timeline feature.
Issue link: [https://github.com/ampproject/amphtml/issues/2604](https://github.com/ampproject/amphtml/issues/2604)

### CODE REVIEW

**Comment by cramforce** [comment]
Neat. Would you mind posting a demo screenshot.

CC @rudygalfi @ericlindley-g

**Comment by fcuda** [comment]
Here is a screenshot of the timeline.
screen shot 2016-05-09 at 10 23 16

**Comment by fcuda** [comment]
I signed it! and the corporation name is Telegraph Media Group.

Thank you

Francesca

**Comment by dvoytenko** [comment]
@fcuda Thanks! This looks very interesting. I'm assigning this to @sriramkrish85 for the initial review.

**Comment by cramforce** [comment]
Nice!

**Comment by sriramkrish85** [comment]
@fcuda - thanks for the PR! i have started taking a look at it will compile my initial feedback and send it out soon. 

Before that couple of points. 
1) You will need to create an experiment for this extension (that has been our practice) - https://github.com/ampproject/amphtml/blob/master/tools/experiments/experiments.js

2) Add outlines (just it statements) (you can add the implementation at the time we agree upon the code) - but it is extremely important that we have tests before we can merge the PR.

**Comment by fcuda** [comment]
@sriramkrish85 thank you for the feedback. We are looking to amends points 1, 2 and 4 as suggested. 
For point 3, we thought about the timeline as a way to allow publishers to list a series of events that have lead up to the article without having to include all of them in the article body. I understand that in the Intent to implement #2604 we mentioned the use of Masonary as a way to deal with the grid layout and to give a nice transition when collapsing the grid. However, during development we realised that the timeline will be targeted for mobile so the logic of grid that responsively collapse will not be used. We decided then to slim-down the code and consider just the case of one column making Masonary not needed. Any thoughts?

**Comment by fcuda** [comment]
@sriramkrish85 and @dvoytenko after pushing the latest changes as requested we are seeing the message "This branch has conflicts that must be resolved". Can you please advice how to proceed? Thanks a lot!

**Comment by dvoytenko** [comment]
@fcuda you can rebase master as described here:
https://help.github.com/articles/about-git-rebase/

**Comment by codecreative** [comment]
I've signed CLA

**Comment by valentinlup** [comment]
I signed it.

**Comment by fcuda** [comment]
@dvoytenko we can see that the cla/google is still waiting for status to be reported even if everyone included in the pull has been signed and notified it. Can you please check on your side if there is anything else missing? Thanks a lot!

**Comment by striff** [comment]
I signed it.

**Comment by dvoytenko** [comment]
@fcuda - yes, sorry. I see that you signed. It's a bit hard to debug because of the number of commits. Do you think you could squash commits as described in http://stackoverflow.com/questions/6934752/combining-multiple-commits-before-pushing-in-git - that should help us get to the bottom of this quicker.

**Comment by ericlindley-g** [comment]
@fcuda Thanks again for submitting! If this component doesn't yet require JS to function or simplify the HTML, it would be good to know what other enhancements are on the roadmap for the feature that make it a good candidate for AMP, as opposed to using it as an example as something possible in AMP.

Do you have plans to extend the functionality (say, to accommodate larger or more complex timelines with collapse/expand mechanics, or to anchor timeline elements at points in the line proportional to the time passed between them)?

**Comment by sriramkrish85** [comment]
Closing this PR due to inactively—please feel free to resume and reopen

**Pull request closed without merging**
