### PR TITLE
put back localhost check for localdev

### PR DESCRIPTION
**Pull request by erwinmombay**
@rsimha-amp do you remember why you removed that line?

### CODE REVIEW

**Comment by rsimha-amp** [comment]
This was part of what @lannka suggested in the original issue. Let me dig in some more.

**Comment by rsimha-amp** [comment]
For posterity, see #11588 for the PR that removed the `localhost` check

**Comment by lannka** [comment]
@erwinmombay @rsimha-amp do you recall what was the test pages got broken?

**Comment by rsimha-amp** [comment]
@lannka the ads in http://localhost:8000/examples/ads.amp.html were 404ing without the `localhost` check

**Comment by lannka** [comment]
All ads broke because removing the localhost check makes `isLocalDev` false. hence all ads start to load 3p bootstrap frame from production with a wrong RTV path.

Let's discuss the solution on this thread: #12054

**Pull request merged**
