### PR TITLE
amp-carousel: unskip another one

### PR DESCRIPTION
**Pull request by samouri**
Addresses https://github.com/ampproject/amphtml/issues/30661#event-3967871527

### CODE REVIEW

**Review by rcebulko — APPROVED** [review]
Thanks for knocking these out so quickly!

**Comment by samouri** [comment]
@erwinmombay: do you know whats up with the failing esm test? Is this expected for now?

**Comment by erwinmombay** [comment]
No definitely not. Ill look into it

**Comment by erwinmombay** [comment]
@samouri merged https://github.com/ampproject/amphtml/pull/31102

**Pull request merged**
