### PR TITLE
🐛: Adding UpScore to Vendor.js

### PR DESCRIPTION
**Pull request by suransandi**
Hi @torch2424, 

How are you? Some time has passed since we last talked, and I hope that you are doing well.

A few days ago, we tested the UpScore AMP analytics with one of our clients and noticed that we have a small issue. So after an investigation and debugging I noticed that I completely missed out one part of AMP integration, and forgot to add the UPSCORE_CONFIG inside vendors.js file. 
I would really appreciate if we could resolve this as soon as possible.

I wish Merry Christmas and Happy and Prosperous New Year, to you and whole Google AMP team. 

Sandi 

Last UpScore pull request#18734

### CODE REVIEW

**Comment by torch2424** [comment]
@suransandi 

Hello! Yes we are all doing well! Hope you are doing well, as well!

Uh oh! My apologies for not catching that during review! Yes we definitely can get this fixed as soon as possible.

We currently have a release freeze for the holidays, but I can reach out to figure out as soon as this can get out once this gets pulled. cc @zhouyx if you know when that will be.

Happy holidays to you too! I wish you a prosperous new years as well! 😄

**Comment by zhouyx** [comment]
There's one more canary cut at 12/26. But I can't merge the PR because there's test failure. 

Once that is fixed, our code freeze ends at 1/2. If we get this merged before 1/2, the fix will be in prod 1/8.

**Comment by torch2424** [comment]
@suransandi

So I re-ran the travis tests, and it seems that they are still failing. They seem to be directly related to the config. After you fix the tests, we can go ahead and do a review, thank you! 😄

**Comment by suransandi** [comment]
Hi @torch2424 ,

I have updated upscore config so now unit tests are not failing anymore. But, I am not sure why one of integration tests failed. Am I missing something?

**Comment by torch2424** [comment]
@suransandi 

The integration tests seemed to all pass, but our `ampproject/bundle-size` did not. We are still working on it, and sometimes it incorrectly fails. No worries, this will not block your PR, and we will handle that. 👍 

However, there is something else I noticed:

Just to be extra sure this time about the changes, I went ahead and tested things myself, and noticed no requests are sent through our examples page:

screen shot 2018-12-27 at 11 27 38 am

I noticed the config in `examples/analytics-vendors.amp.html` does not have any triggers. Could you go ahead and add some for our testing and things, that way we can both manually test if it works? [See another analytics vendor example here](https://github.com/ampproject/amphtml/blob/master/examples/analytics-vendors.amp.html#L1405). Unless you have some default triggers included, then I don't think they are working. Let me know if what I am saying makes sense. 🙃  Thank you! 😄

**Comment by suransandi** [comment]
@torch2424 

When I was testing it locally I used different example page: "analytics.amp.html". I just added the amp script tag with upscore id to the page and it worked like a charm. On another hand, when I used "analytics-vendors.amp.html" page, there was no result at all. If I choose upscore from a drop-down menu and click GO button, it just refreshes the page but doesn't trigger any of the requests that should be called when a page contains amp analytics script tag. If I just click GO button without choosing any of the possible vendors, every vendor amp script that is triggered on "visible" event, is triggered successfully. Others that trigger events on clicking the "Click here to generate an event" button also work. But for some reason upscore requests are not recognized and fail with exceptions: "No request strings defined. Analytics data will not be sent from this page" and "Ignoring request for event. Request string not found:  pageview".

_(For testing purposes and to avoid the mess only upscore and umenganalytics amp scripts are being triggered)_
amp_vendor_issue

 If I add a "config" property to amp script tag that is pointing to a local file that contains the upscore Amp Config everything works just fine.
EXAMPLE SCRIPT:
`
<amp-geo layout="nodisplay"></amp-geo>
<amp-analytics type="upscore" id="upscore" config="./analytics.config.json">
    <script type="application/json">
      {
        "vars": {
          "object_id": "foo",
          "object_type":"bar",
          "section":"sport",
          "author":"john suran",
          "creator":"john suran",
          "domain":"clientDomain",
          "pubdate":"2015-01-01 00:00:00"
        },
        "triggers": {
          "event": {
            "on": "click",
            "selector": "#test1",
            "request": "pageview"
          }
        }
      }
      </script>
</amp-analytics>`

EXAMPLE CONFIG:
`{
  "requests": {
    "host": "https://hit-pool.upscore.com/amp?",
    "basePrefix": "u_id=${clientId(upscore)}&hit_id=${pageViewId}&scTop=${scrollTop}&scHeight=${scrollHeight}&vHeight=${viewportHeight}&domain=${domain}&load=${domInteractiveTime}&timespent=${totalEngagedTime}",
    "initialHit": "author=${author}&creator=${creator}&o_id=${object_id}&o_type=${object_type}&pubdate=${pubdate}&ref=${documentReferrer}&section=${section}&url=${ampdocUrl}&agent=${userAgent}&location=${ampGeo(ISOCountry)}",
    "finalbeat": "${host}${basePrefix}&type=final",
    "heartbeat": "${host}${basePrefix}&type=pulse",
    "pageview": "${host}${basePrefix}&${initialHit}&type=init"
  },
  "transport" : {"beacon": true, "xhrpost": false}
}`
RESULT:
upscore_amp_vendors_success

 Just to point out that this is not happening with "analytics.amp.html" example page.
So why is the upscore recognized and triggered on analytics.amp.html page but not on the analytics-vendors.amp.html page?

**Comment by torch2424** [comment]
@suransandi

Hmmm that is strange.

cc @zhouyx why this might be? 🤔

**Comment by zhouyx** [comment]
Took a quick look. Looks like it is related to ${ampGeo} variable. I'll further investigate and keep you updated. Thanks

**Comment by zhouyx** [comment]
Found the reason: 
`pageview` request includes `location=${ampGeo(ISOCountry)}`. So the request will be waiting for the ampGeo service to be ready. 
However in the special case of `analytics-vendors.amp.html`, local server will remove the `<amp-geo>` component from the response. 
https://github.com/ampproject/amphtml/blob/ed5e1e6be50afb55bd525957c0ae5b3560c38b1a/build-system/app.js#L837-L844

To fix this, please include the `<amp-geo>` component outside the container div. https://github.com/ampproject/amphtml/blob/master/examples/analytics-vendors.amp.html#L116

**Comment by suransandi** [comment]
Hi @torch2424 and @zhouyx ,

I have changed the request in analytics-vendors.amp.html to the "finalbeat". "Finalbeat" does not have amp-geo property, so with that, I also removed the amp-geo tag that was causing trouble as  @zhouyx advised. But even after I have changed the request and completely removed amp-geo tag, I wasn't able to successfully test the upscore vendor. To me, that seems like a minor issue(because with other example pages it is working fine), so if it is ok with you, I would like to suggest that we resolve this pull request. 

Please, let me know what you think,

I hope that today you will have a great time celebrating a New Year, with a bunch of booze and good people around you.

**Comment by zhouyx** [comment]
@suransandi Sounds good to me. I'm fine merging this now before canary cut. The example page can be easily fixed. 

Two reasons why you are not seeing the fix. 
1. There's recently a race condition issue of amp-analytics that has been fixed. You may want to rebase to master.
2. There's still `amp-geo-0.1.js` script included. If so the `${ampGeo}` macro will still be waiting for the non existing `<amp-geo>. (Note: Which makes it not a valid AMP page).

**Pull request merged**
