### PR TITLE
Ad type adverticum 3p script https/http support.

### PR DESCRIPTION
**Pull request by Adverticum**
Our invocation script should be called without protocoll to support sites served through both http and https.

### CODE REVIEW

**Comment by lannka** [comment]
@Adverticum i cannot get the example display an ad. it's blank. can you try to make it work locally? check [this](https://github.com/ampproject/amphtml/blob/master/ads/README.md#developer-guidelines-for-a-pull-request) for how-to.

**Comment by Adverticum** [comment]
@lannka i have a working axample on localhost. See attached screenshot below.
That banner I'm using for example has a bit delay at the start. Give it a few seconds.
screenshot from 2017-01-25 08-59-31

**Comment by Adverticum** [comment]
The main question is that, if I'm includeing our invocation scrit withe the writeScript method and the given url has no protocol will it work on both http and https?

**Comment by Adverticum** [comment]
@lannka  could you check the example again? Are you seeing a blank white square or the "No ad" message from AMP?

**Comment by lannka** [comment]
This is what I got. Did you turn on any user targeting on that slot?

screenshot from 2017-01-26 10 38 18

> The main question is that, if I'm includeing our invocation scrit withe the writeScript method and the given url has no protocol will it work on both http and https?

Yep, it should work for both.

**Comment by Adverticum** [comment]
I just changed the example to a simple image banner. Hope you can see it now.
Also @lannka can you tell me the earliest time this fix can go live? Our clients need it.

**Comment by lannka** [comment]
@Adverticum the change will be rolled out to canary this Tursday.

**Pull request merged**
