### PR TITLE
🐛 [Amp story] Desktop one panel play button

### LINKED ISSUE #35640: Pause button on story player not functional
### Description

Actual results: 
The pause button on the stories player does not pause the story on click.
Clicking space to pause the story does not display the play button.
The pause button does not appear until the space bar has been clicked.

Recording: https://jmp.sh/mIq8KFb 

Expected results:
The play/pause button should display by default and should be functional.

Web Stories v1.10.0
WordPress v5.8

### Reproduction Steps

1. Preview a Web Story
2. Note top right corner > Missing icon
3. Click space bar > Note pause button displays but story does not pause

### Relevant Logs

_No response_

### Browser(s) Affected

Chrome, Firefox, Safari

### OS(s) Affected

_No response_

### Device(s) Affected

macOS

### AMP Version Affected

_No response_

### PR DESCRIPTION
**Pull request by processprocess**
Displays the pause/play controls when in desktop panel mode.

Fixes #35640

### CODE REVIEW

**Comment by mszylkowski** [comment]
High level question: why don't we want the new one-panel desktop to be `[desktop]`? Similar to #35772 where we add the layout to the list of desktop layouts.

**Comment by processprocess** [comment]
> High level question: why don't we want the new one-panel desktop to be `[desktop]`? Similar to #35772 where we add the layout to the list of desktop layouts.

#35772 had no side effects and only effected that one line. The `desktop` attribute will be cleaned up as much as possible once we're ready.

Adding `desktop` here causes visual side effects like chunkier SVGs with different margins.

**Comment by mszylkowski** [comment]
> The `desktop` attribute will be cleaned up as much as possible once we're ready.

Got it, so eventually we want to bring back the desktop attribute, but for now it would introduce back some of the styles we're trying to get rid of?

**Review by mszylkowski — APPROVED** [review]
Do any of the other locations that use `[desktop]` also need this? Still LGTM since this is the only rule we know it's been affected.

**Comment by processprocess** [comment]
> Got it, so eventually we want to bring back the desktop attribute, but for now it would introduce back some of the styles we're trying to get rid of?

It would make more sense for our UI naming conventions to be based on aspect ratio rather than device type. 
I do not think we should bring back `desktop`. Once we clean up all the unused desktop code I think we'll be able to scope a name change more easily and decide if we want to do that.

**Comment by processprocess** [comment]
> Do any of the other locations that use `[desktop]` also need this? Still LGTM since this is the only rule we know it's been affected.

They do not appear to and will be removed during cleanup.

**Pull request merged**
