### PR TITLE
[amp-ad] Add myTarget ad network

### PR DESCRIPTION
**Pull request by vfedoseev**
We have added an extension for myTarget ad network.
Please review and comment with any questions.

Thank you.

### CODE REVIEW

**Comment by vfedoseev** [comment]
Unfortunately, one of the TravisCI jobs failed with the error below:
https://travis-ci.org/ampproject/amphtml/jobs/336129128
> DESCRIBE => user-error
  DESCRIBE => 3p user-error integration test
    IT => "before each" hook for "should ping correct host with 3p error message"
      ✗ Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

I suppose that this error is not related to our amp-ad extension. 
How could we resolve it?

**Comment by vfedoseev** [comment]
Hello, could you please check our PR and CI errors.
Thank you.

**Comment by vfedoseev** [comment]
Hello!
I wonder if our PR was finally approved and when could you merge it?
Thank you!

**Comment by vfedoseev** [comment]
Hello!
We have resolved merge conflicts manually by Github UI.
Travis job for integration tests has failed with the same result as in comments above.

> IT => urls should be configurable
    ✗ Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves

Should we do anything else to merge this PR?
Thank you.

**Comment by vfedoseev** [comment]
Hello!
Just want to clarify if everything is ok and our PR could be merged.
Thank you!

**Comment by vfedoseev** [comment]
Ping=)

**Comment by vfedoseev** [comment]
Hello, @lannka!
Is everything ok here?
We are still waiting for merging=)

**Comment by cathyxz** [comment]
I can merge this when Travis runs green.

**Comment by cathyxz** [comment]
Oh I see what's wrong with Travis now. Sorry, @vfedoseev could you merge master again?

**Comment by vfedoseev** [comment]
Hello, @cathyxz.
I've merged the master, but Travis CI falls with error again:
https://travis-ci.org/ampproject/amphtml/jobs/371051826

**Pull request merged**
