### PR TITLE
✨RE_2:Add support for CAaja ads network

### PR DESCRIPTION
**Pull request by matsuda-takehiro**
Adds support for CAaja ads network.

Hello.
We are A.J.A., a subsidiary of CyberAgent which provides ad-network service in Japan. (https://www.cyberagent.co.jp/) CA
(https://aja-kk.co.jp/) AJA
We'd like to add support to amp-ad.

Thanks.

previous↓
#20652

### CODE REVIEW

**Comment by matsuda-takehiro** [comment]
I forgot to delete the comment out ...

**Comment by matsuda-takehiro** [comment]
Please tell me how to fix travis error...

**Comment by matsuda-takehiro** [comment]
image

**Comment by zhouyx** [comment]
Hello @matsuda-takehiro before I go ahead and review your change, I want to make sure that you don't want to reuse the existing `aja` ad type that you own? I thought we decided to change it based on https://github.com/ampproject/amphtml/pull/20652#issuecomment-465259995

**Comment by matsuda-takehiro** [comment]
Thank you @zhouyx

Well, if possible, I would like to make it with caaja's name, but if I can not do that, I'll do it with aja

**Comment by matsuda-takehiro** [comment]
In that case, I will get permission from hideaki!

**Comment by zhouyx** [comment]
@matsuda-takehiro
I want to reuse the aja ad type because it prevents adding duplicate ad types to the AMP runtime library. Which lowers maintenance effort and helps with performance. However you're the one to make the final call. If the aja ad type is not used by anyone, is there plan to deprecate and have it remove from the AMP runtime? Thank you.

**Comment by matsuda-takehiro** [comment]
Thank you @zhouyx

Certainly, I think you are right!

I think that I will rewrite aja. What kind of procedures should I take?

Change aja.js and aja.md.

**Comment by zhouyx** [comment]
Thank you for helping maintain the health of our codebase @matsuda-takehiro 

I believe you want to follow the current change and make change to the same 6 related files.

**Comment by matsuda-takehiro** [comment]
Thank you @zhouyx

What actions should I take below?

- I close this PR, the previous PR and erase the branch
- I will change aja.js, aja.md, ads.amp.html etc like this PR 6 files
- I will get permission from hideaki

**Comment by matsuda-takehiro** [comment]
Worries about the following
- I will make a new PR
  - I got permission from hideaki, but does hideaki need to login to github and comment on PR?

**Comment by matsuda-takehiro** [comment]
Thank you for the real-time reply.
Sorry that the reply was always behind because there is a time lag
Thank you very much for your support.😀

**Comment by zhouyx** [comment]
@matsuda-takehiro I am fine with you creating a new PR this time because we are going with a new approach. However it would be great if we can stick to modify the change on top of one PR next time. 

It would be great to have hideaki approve the change on Github. This is to ensure that no random change will be made to existing ad vendors. Thank you for understanding.

**Comment by matsuda-takehiro** [comment]
Thank you @zhouyx

I understand.
I will go forward with one PR as much as possible from next!

However, please only let me out the next PR. I'm sorry....

**Comment by matsuda-takehiro** [comment]
#21174

**Comment by zhouyx** [comment]
Tracked in #21174

**Pull request closed without merging**
