### PR TITLE
🐛 Remove gplus from amp-social-share

### LINKED ISSUE #21743: Remove G+ from documentation of amp-social-share
Should the G+ option now be removed from the amp-social-share documentation since G+ close?

https://www.ampproject.org/docs/reference/components/amp-social-share

### PR DESCRIPTION
**Pull request by drewroberts**
Fixes #21743 

Remove Google+ from amp-social-share.

CC: @aghassemi and the other 2 owners from amp-social-share .yaml @ithinkihaveacat @RyanCopley

### CODE REVIEW

**Comment by RyanCopley** [comment]
It may be worth reviewing all instances of `gplus`. https://github.com/ampproject/amphtml/search?utf8=%E2%9C%93&q=gplus

**Comment by DrewRoberts** [comment]
@RyanCopley I removed the other 5 instances of gplus. Let me know if there's anything else you recommend. Thanks for the opportunity to work on the AMP Project.

**Comment by cathyxz** [comment]
We should also remove references to gplus from AMP-By-Example, e.g. https://amp.dev/documentation/examples/components/amp-social-share/?referrer=ampbyexample.com. In fact we should probably remove those first so that those pages don't break. Should we have a deprecation notice out for a bit before actually removing this (to avoid breaking people)?

**Comment by DrewRoberts** [comment]
Good call, @cathyxz. I created an issue for it and working on it now:

- https://github.com/ampproject/amp-by-example/issues/1998

What's the best practice for creating a deprecation notice?

**Comment by RyanCopley** [comment]
I was wondering how it would handle depreciation, thank you @aghassemi for showing a demo. What is the result currently? Do g+ pages fail to load?

What about a depreciation notice in the console, and remove for the documentation, and set a date for removal? Is there any existing workflow established for deprecating functionality?

**Comment by aghassemi** [comment]
For deprecation, probably a `user().warn` when encountering gplus in the config would do.

**Comment by nainar** [comment]
Closing this PR as inactive. Please reopen if that isn't the case (preferably as a new PR).

**Pull request closed without merging**
