### PR TITLE
Cut dependency between many extensions and the core custom elements class

### PR DESCRIPTION
**Pull request by cramforce**
This pulled in a lot of unneeded code leading to major size regression.

### CODE REVIEW

**Comment by erwinmombay** [comment]
@cramforce awesome win

**Comment by cramforce** [comment]
Updated to after `collapseProperties`. Really great to see that there is a much smaller win now, meaning DCE really work. We should still do this change, though.

**Comment by cramforce** [comment]
PTAL

**Comment by jridgewell** [comment]
LGTM.

**Pull request merged**
