### PR TITLE
Run ci tests on latest chrome

### PR DESCRIPTION
**Pull request by estherkim**

### CODE REVIEW

**Review by danielrozenberg — COMMENTED** [review]
Do you recall why we had this pinned behaviour in the first place? I don't remember the details but I remember there were good reasons

**Comment by estherkim** [comment]
Here's where we started pinning - https://github.com/ampproject/amphtml/pull/36348
A new browser version could break CI and the idea was to use renovate PRs to update chromedriver, which would update the chrome version.

But in practice we haven't updated chromedriver since pinning it in Oct '21 so it's been stuck Chrome v95, whereas it's at v101 now.

**Review by danielrozenberg — APPROVED** [review]
Hmm... in that case I can't really say which alternative is preferred. Letting the CI get broken because of an external dependency isn't great either. Saying that, maybe it's worth giving it another try - approving this PR, let's keep an eye over the next few weeks to see if this is a pro or a con

**Review by jridgewell — CHANGES_REQUESTED** [review]
Can we just update the pinned version?

The reason we pinned it is because it's an external change that causes breakages in our release workflow. I don't want to be in the middle of a cherry-pick and have several tests failed because it happens to be Chrome release day.

**Comment by estherkim** [comment]
> Can we just update the pinned version?
> 
> The reason we pinned it is because it's an external change that causes breakages in our release workflow. I don't want to be in the middle of a cherry-pick and have several tests failed because it happens to be Chrome release day.

Ok that's fine. I just want to make sure we keep Chrome up to date. Can keep it pinned and manually update chromedriver for this PR.

**Review by jridgewell — APPROVED** [review]

**Pull request closed without merging**
