### PR TITLE
✅ Remove special casing for tests from amp-mustache extension registration

### PR DESCRIPTION
**Pull request by danielrozenberg**
Unregistering the template causes some visual diff tests to fail (#22047) and we traced the issue here. When this special-cased code was removed the visual diff test started working.

It's possible that our recent work on the testing infrastructure made this special-casing unnecessary, but I would appreciate if you can shed some light on why this was added in the first place

### CODE REVIEW

**Comment by choumx** [comment]
> I would appreciate if you can shed some light on why this was added in the first place

Did you see the long comment? :)

**Comment by danielrozenberg** [comment]
I did, but I'm not sure where that error manifested. If you expect that error to have been caught by automated testing, then that error no longer happens even with that logic removed. I wanted to pass this by you to double-check that I'm not missing anything important!

`unregisterTemplate` is used in two more locations in the codebase, added by @erwinmombay in PR #22064. I can try removing those here and see how they affect tests. Erwin - if the tests pass is this ok to merge?

**Comment by erwinmombay** [comment]
@danielrozenberg the references i had were all in babel transformation tests so they can be removed

**Comment by choumx** [comment]
"Duplicate template type" is thrown in registerTemplate: https://github.com/ampproject/amphtml/blob/c40e637ec6e3f52505cc33aea098a0ca28c72536/src/service/template-impl.js#L371

**Pull request merged**
