### PR TITLE
🚮 Sweep experiments older than 2020-11-29

### PR DESCRIPTION
**Pull request by alanorozco**
Sweep experiments last flipped globally up to 2020-11-29:

- (2020-08-14, 77ced1de0) `expand-json-targeting`: 1

### CODE REVIEW

**Review by calebcordry — APPROVED** [review]
Thanks!

**Comment by alanorozco** [comment]
`-@newmuis`, +@rsimha for `*-config.json`.

**Comment by rsimha** [comment]
> `-@newmuis`, +@rsimha for `*-config.json`.

Config changes do not need infra review. Best to get the experiment maintainers to make sure this is okay.

**Comment by alanorozco** [comment]
@rsimha Was [this check](https://github.com/ampproject/amphtml/pull/34685/checks?check_run_id=2739536371) a fluke?

```
[NEEDS APPROVAL] build-system/global-configs/canary-config.json (requested: newmuis)
[NEEDS APPROVAL] build-system/global-configs/prod-config.json (requested: newmuis)
```

**Comment by rsimha** [comment]
> @rsimha Was [this check](https://github.com/ampproject/amphtml/pull/34685/checks?check_run_id=2739536371) a fluke?

Not a fluke. See owners file: https://github.com/ampproject/amphtml/blob/main/build-system/global-configs/OWNERS

**Comment by alanorozco** [comment]
@rsimha [You are part of `wg-approvers`](https://github.com/orgs/ampproject/teams/wg-approvers/members), but neither @calebcordry or me are.

**Review by rsimha — APPROVED** [review]
LGTM. I think regular maintainers should be added as an owner of these files.

**Pull request merged**
