### PR TITLE
* add support for documentPath

### PR DESCRIPTION
**Pull request by hjanuschka**
add support for documentPath - as in Documenation -> https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#page

we need that, as in our use-case all variations (apps, mobile-web, desktop) - make the same pageview/screen view.:

e.g. on mobile-web - to get the same page path as on Desktop:

```
ga('send', 'pageview', { 'page': '/Oesterreich/Polizei_fasst_Komplizen_des_getoeteten_Raeubers-Knalleffekt-Story-518333'});
```

### CODE REVIEW

**Comment by hjanuschka** [comment]
i don't get the test fixed! - if i do `gulp test` locally it works.... any ideas?

**Comment by avimehta** [comment]
@hjanuschka I somehow missed this PR. Were you able to solve this issue? If not do you want to try using `extraUrlParams` feature to add dp to the requests?

**Comment by hjanuschka** [comment]
@avimehta rebased current master, tests pass now 👍 
i haven't tried the `extraUrlParams` yet.

**Comment by avimehta** [comment]
extraUrlParams should work. I don't think we want to do this for everyone by default. Closing this PR.

**Pull request closed without merging**
