### PR TITLE
✨ Update amp-analytics provider `mpulse.json` to add Core Web Vitals metrics

### PR DESCRIPTION
**Pull request by simonhearne**
This change adds FCP, LCP, CLS and FID as defined here: https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md to the query parameters for the mPulse beacon as defined here: https://developer.akamai.com/mpulse/whats-in-a-beacon/#continuity-metrics

### CODE REVIEW

**Comment by raja-anbazhagan** [comment]
It is not a good idea to place Core web vitals along with the page analytics data. Here is why.

CLS & LCP is only calculated when you move out of the page or go to another tab.
FID is calculated only after the user clicks on the browser.

By that logic, You will get the main analytics data only when the user clicks on the page and decides to hide the current tab or choose to leave.

I guess one of the @ampproject/wg-analytics members can shed some info on this.

**Comment by raja-anbazhagan** [comment]
> It is not a good idea to place Core web vitals along with the page analytics data. Here is why.
> 
> CLS & LCP is only calculated when you move out of the page or go to another tab.
> FID is calculated only after the user clicks on the browser.
> 
> By that logic, You will get the main analytics data only when the user clicks on the page and decides to hide the current tab or choose to leave.
> 
> I guess one of the @ampproject/wg-analytics members can shed some info on this.

Here is a simple demo to test this theory.

https://zany-odd-bacon.glitch.me/

The analytics ping will only happen when the performance metrics macros were satisfied.

**Comment by simonhearne** [comment]
Thanks for that @raja-anbazhagan, I didn't realize that onvisible events were blocked by metrics availability. Agreed that this is not a good change so will close and discuss with the boomerang team.

**Comment by micajuine-ho** [comment]
@raja-anbazhagan  Thanks for your input here. You are correct in this. I would suggest that you create individual analytics triggers for each CWV metric, that still gets immediately fired on pageview `visible`, but won't resolve until the CWV metric is calculated.
Here is any example config you could use:
```
{
  "triggers": {
    "pageviewCls": {
      "on": "visible",
      "request": "endpoint",
      "extraUrlParams": {
        "cls": "${cumulativeLayoutShift}"
      }
    },
    "pageviewLcp": {
      "on": "visible",
      "request": "endpoint",
      "extraUrlParams": {
        "lcp": "${largestContentfulPaint}"
      }
    },
    "pageviewFid": {
      "on": "visible",
      "request": "endpoint",
      "extraUrlParams": {
        "fid": "${firstInputDelay}"
      }
    }
  }
}
```

**Pull request closed without merging**
