### PR TITLE
Add support for multirequest Ads in Sklik SSP amp-ad

### PR DESCRIPTION
**Pull request by jandolezal71**
Hi,

please review my PR for:

- ✨ Edited amp-ad of type `ssp`
- ✨ Added support for multiple ads on page with same type
- ✅ Tests are also implemented

Thank you

### CODE REVIEW

**Comment by jandolezal71** [comment]
TravisCI is somehow blocked in queue. Is there some way how to restart it?

**Comment by jandolezal71** [comment]
Can i ask someone to help? I tried to restart TravicCI but it didn't helped. Travis is queued many for many days now.

**Comment by jeffjose** [comment]
Apologies for the delay here. Over to @lannka for review.

**Comment by jandolezal71** [comment]
@lannka Thanks for approve, but what with TravisCI? It's constantly queued.

**Comment by lannka** [comment]
Please run `gulp check-types` and fix errors

**Comment by jandolezal71** [comment]
> check-types

I don't know what to fix, these errors are not from my code.

```
Type checking failed:
extensions/amp-analytics/0.1/config.js:101: WARNING - [JSC_UNREACHABLE_CODE] unreachable code
    if (!true) {
               ^

extensions/amp-analytics/0.1/vendors.js:276: WARNING - [JSC_UNREACHABLE_CODE] unreachable code
if (!true) {
           ^

src/amp.js:155: WARNING - [JSC_UNREACHABLE_CODE] unreachable code
    if (false) {
               ^

src/custom-element.js:331: WARNING - [JSC_MISPLACED_ANNOTATION] Misplaced typedef annotation. @typedef is not allowed on instance or prototype properties. Did you mean @type?
      return (/** @typedef {!./service/ampdoc-impl.AmpDoc} */this.ampdoc_);
                                                             ^^^^^^^^^^^^

src/custom-element.js:346: WARNING - [JSC_MISPLACED_ANNOTATION] Misplaced typedef annotation. @typedef is not allowed on instance or prototype properties. Did you mean @type?
      return (/** @typedef {!./service/resources-interface.ResourcesInterface} */this.
                                                                                 ^^^^^

src/polyfills/custom-elements.js:843: WARNING - [JSC_UNRECOGNIZED_TYPEOF_ERROR] Missing type for `typeof` value. The value must be declared and const.
   * @param {!typeof SUPER} superClass
                     ^

src/polyfills/custom-elements.js:844: WARNING - [JSC_UNRECOGNIZED_TYPEOF_ERROR] Missing type for `typeof` value. The value must be declared and const.
   * @param {!typeof SUB} subClass
                     ^

ads/ssp.js:31: ERROR - [JSC_TYPE_PARSE_ERROR] Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler for more information.

ads/ssp.js:33: ERROR - [JSC_TYPE_PARSE_ERROR] Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler for more information.

ads/ssp.js:37: ERROR - [JSC_TYPE_PARSE_ERROR] Bad type annotation. expected closing } See https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler for more information.

ads/ssp.js:37: ERROR - [JSC_TYPE_PARSE_ERROR] Bad type annotation. expecting a variable name in a @param tag. See https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler for more information.

4 error(s), 7 warning(s), 93.5% typed

```

**Comment by jandolezal71** [comment]
@lannka Hi, i fixed my JSDoc errors, but there is one more TravisCI error https://travis-ci.org/ampproject/amphtml/jobs/660107656?utm_medium=notification&utm_source=github_status and i don't know what to do.

```
dist-bundle-size.js: Done running dist-bundle-size.js Total time: 6m 3s
The command "unbuffer node build-system/pr-check/dist-bundle-size.js" exited with 1.
$ if [[ $TRAVIS_EVENT_TYPE == pull_request ]] || [[ $TRAVIS_BUILD_STAGE_NAME == experiment ]]; then exit $TRAVIS_TEST_RESULT ; fi
```

**Comment by lannka** [comment]
That might just be a flake. I restarted the job.

**Comment by jandolezal71** [comment]
> That might just be a flake. I restarted the job.

Should i see any change? Job is still in error state with same date.

**Comment by jandolezal71** [comment]
@lannka Ok, i forced pushed same code to restart the process and it worked. But there is some visual change (not my).

**Comment by jandolezal71** [comment]
Thank you.

**Pull request merged**
