### PR TITLE
Launch ANALYTICS_VENDOR_SPLIT experiment

### PR DESCRIPTION
**Pull request by zhouyx**
I'm trying to keep the PR small. However all the tests need to be fixed together, so it's kind of big. 

In this PR, I am
1. pushing all config json file
2. Enabling the ANALYTICS_VENDOR_SPLIT for all, and remove the A/B testing experiment. 
3. Fixing all broken tests

Follow up tasks
1. remove generate-vendor-config tasks
2. vendor js files
3. load unbuilt config for unit tests
4. Change integration instructions

### CODE REVIEW

**Comment by zhouyx** [comment]
Resolving conflicts turned out to be very painful. Let's please not merge any further vendor changes until we launch the experiment, unless they are urgent. Thanks : )

**Comment by lannka** [comment]
I'm thinking of a common process to GA launch a RTV experiment.

As the first step, what about assigning ANALYTICS_VENDOR_SPLIT to true and move `gulp generate-vendor-jsons` to somewhere in the main gulp flow?

This way, we can launch the feature w/o too much code changes, and offer a clean rollback option if things go wrong.

**Comment by zhouyx** [comment]
That's the idea with a few caveats

1.  There's no straightforward way to set experiment flag to true at this moment
2. To launch the experiment, I feel strong that we have the unit test coverage. So these code changes in this PR would still be necessary

Let me know what you think

**Comment by lannka** [comment]
Extra unit test coverage is definitely good to have.

Will this PR launch the experiment to GA? We will need a simpler PR that can be rolled back easily in case of prod issues.

**Comment by zhouyx** [comment]
Would be very difficult unless we are OK with us skipping tests.

**Comment by lannka** [comment]
unit tests should be encapsulated, are we not able to create a separate test set with the flag enabled?

if we have to pick one between unit test and easier rollback, I will pick the latter at the moment.
unit tests are to capture future regressions. we can add them right after a successful landing.

**Comment by zhouyx** [comment]
OK

**Pull request closed without merging**
