### PR TITLE
Adds new presets for amp-story: grow-horizontal and grow-vertical ✨

### PR DESCRIPTION
**Pull request by Enriqe**
Adds animation presets for amp-story: `grow-horizontal` and `grow-vertical`.

### CODE REVIEW

**Comment by gmajoulet** [comment]
Do you have any context on these new animations, and what are the use cases we want to allow?

Using scales only works on full shapes, and look very, very bad on actual content since the said content gets distorded, I wrote a simple example here: https://codepen.io/gmajoulet/pen/bKPygd

I'm actually pretty scared of what publishers could build with this :))

**Comment by newmuis** [comment]
Out of the loop here, but if we have concerns about misuse, it would be good to address them before adding this to documentation and validation.

**Comment by Enriqe** [comment]
@alanorozco @newmuis Made the requested changes and will add an ABE with the recommendations as a follow-up. Is that alright?

**Comment by gmajoulet** [comment]
If we want to use an easing function, we should respect the material guidelines.
For a symmetric animation on an object, they recommend the "standard curve", that is a ease in out: `cubic-bezier(0.4, 0.0, 0.2, 1);`

Also, they recommend never doing any mobile animation last longer than 400ms. Default should be around 300ms, and these symmetric animations a bit faster. Should we do 250ms?

That being said, I still think these animations are very, very, very likely to be misused by publishers... Yes they look good when being chained, but it is a very advanced feature. And they look awful when not chained, which is the most common case we've seen so far.
My biggest worry is that we might be releasing a preset that is hard to use, makes it very easy to produce bad content, and hard to produce good content.

**Comment by newmuis** [comment]
+1 to @gmajoulet's concerns; if the only thing we can do is hope that publishers read the best practices.... "Hope is not a strategy" 🙂

If we can find a way to validate that people use this correctly, that may be a different story

**Comment by alanorozco** [comment]
@newmuis 

What about a runtime assertion?

**Comment by newmuis** [comment]
I think that's sufficient, although I prefer if the assertion actually keeps the animation from working, to draw attention to the fact that something is wrong.

**Pull request closed without merging**
