### PR TITLE
Fix broken shields

### PR DESCRIPTION
**Pull request by afischer**
Seems like issuestats has died :(
Just removed the broken images and changed them to be shield.io shields and link to their respective tabs on github.

### CODE REVIEW

**Comment by afischer** [comment]
I signed it!

**Comment by aghassemi** [comment]
@cramforce @jridgewell Switch from issuestats to shields.io or remove the badges all together? (I prefer removing issues and PR badges and only keeping the Travis build)

**Comment by jridgewell** [comment]
Yah, I think I'd prefer a total removal.

**Comment by cramforce** [comment]
No opinion here :)

**Comment by aghassemi** [comment]
@afischer Thanks for the PR. Do you mind just removing the links instead of switching to shields.io in this PR?

**Comment by afischer** [comment]
@aghassemi sounds good.

**Pull request merged**
