### PR TITLE
🐛  [amp-next-page] fix for duplicate history entry 

### LINKED ISSUE #31795: AMP Next Page creates an unnecessary history
## What's the issue?

When navigation through pages, or to a page with amp-next-page enabled, the browser will create an extra history page for the exact page you are on.

This is frustrating when we are trying to utilise this feature on a news site, requiring multiple back clicks to return to the page you were previously on.

## How do we reproduce the issue?

This can be seen live on the amp official documentation and any other page with amp-next-page enabled.
Go to the below link and then confirm that history pages are exactly the same as the page you are on.

https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-next-page&format=websites

## What browsers are affected?

Notably Firefox and Chrome

## Which AMP version is affected?

Using newest version of AMP

### PR DESCRIPTION
**Pull request by dmanek**
Fixes #31795 

FYI this changes the back button behavior i.e. when a user hits back on from a next page, they go back to the previous page in history (if one exists) and not the host page. This is in line with the v0.1 behavior (although I'm not sure if that was the intended behavior and why it was changed in #25553)

amp-next-page 0.1 behavior: https://user-images.githubusercontent.com/506183/115499855-0b2e3780-a225-11eb-8f68-c4ab5435adb9.mp4

amp-next-page 1.0:
Before: https://user-images.githubusercontent.com/506183/115339840-6d6e3600-a15a-11eb-81c6-ebf730412353.mp4
After: https://user-images.githubusercontent.com/506183/115339861-7959f800-a15a-11eb-8641-19acfc70a29c.mp4

cc @nainar

### CODE REVIEW

**Review by jridgewell — CHANGES_REQUESTED** [review]
It seems like this change was intentional, but it's happening too early? Eg, we should only push history when navigating to the next page, not when the component is initializing.

**Comment by dmanek** [comment]
@jridgewell so the behavior you're suggesting is when user scrolls to next page & hits back, they are returned to the host page?

**Comment by jridgewell** [comment]
Yah, that seems correct to me. What's annoying is that when the component initializes, it adds a redundant history state for the host page, even though I'm still looking at the host page. But if I had moved to the next page, it seems ok to navigate back to host.

**Comment by dmanek** [comment]
Seems like @wassgha was trying to implement the same behavior, which led to this issue. TBH don't think its trivial to implement this behavior. Curious if you have any suggestions?

**Comment by jridgewell** [comment]
I would think we need to change https://github.com/ampproject/amphtml/blob/3367a9d41cb71c2dc27d3bfe89325de38a2384eb/extensions/amp-next-page/1.0/service.js#L471 to use `push` instead?

**Comment by dmanek** [comment]
`push` wont work in case of multiple next pages e.g. when a user navigates from host page to next page 1 to next page 2 and then hits back, in this case they will be on next page 1. Don't think that's the behavior you described.

**Comment by jridgewell** [comment]
> when a user navigates from host page to next page 1 to next page 2 and then hits back, in this case they will be on next page 1.

Honestly, that seems fine to me, too.

If you want to only introduce a single history state, than you can check what the current item is, and what the new item is:

```js
if (current == HOST && new !== HOST) {
  history.push();
}
if (current !== HOST && new == HOST) {
  history.pop();
}
```

**Review by jridgewell — APPROVED** [review]

**Comment by dmanek** [comment]
Based on offline discussion, `history.push` only updates URL fragment. Keeping the original fix where clicking back on host or next page, user will navigate to the previous page in history. This is in line with amp-next-page v0.1 behavior.

**Pull request merged**
