### PR TITLE
Adding Blue Triangle to amp-analytics list ✨

### PR DESCRIPTION
**Pull request by AdrianPerry**
Adds Blue Triangle to the list of amp-analytics vendors

#33673

### CODE REVIEW

**Comment by alanorozco** [comment]
Hi @AdrianPerry.

This PR seems to have an issue in history and marks all files as changed. Could you please rebase your branch?

Once we can look at a clean diff @micajuine-ho and I can take a look. Thanks!

**Comment by micajuine-ho** [comment]
Looks like there wasn't a clean merge :P 

Please rebase with master and then merge the change :)

**Comment by AdrianPerry** [comment]
Am I missing something?

**Comment by micajuine-ho** [comment]
Your PR shouldn't be touching 5000+ files. Maybe try creating a new PR instead

**Pull request closed without merging**
