### PR TITLE
Disallow Ad Slots from A4A if using prefer-viewability-over-views

### PR DESCRIPTION
**Pull request by keithwrightbos**
data-loading-strategy = prefer-viewability-over-views for 3p increase viewability percentage by delaying ad requests (via layoutCallback) until the slot is within 1.25 viewports.  A4A currently has no such constraint given the ad request is sent view onLayoutMeasure.  Will remove A4A carve-out once this feature is supported.

### CODE REVIEW

**Comment by tdrl** [comment]
LGTM.  Over to @lannka for AMP approval and merging.

**Comment by jasti** [comment]
@keithwrightbos "A4A currently has no such constraint given the ad request is sent view onLayoutMeasure". When is the ad rendered in A4A case? Say an A4A ad has been requested early and received, but the ad is 3 viewports down.

**Comment by keithwrightbos** [comment]
Hmm... you may be correct the viewability is views / impressions in which
case the delayed impression will not be fired until we're within 3
viewports.  Even then, this does not currently work correct for AMP
creatives given they are attached to the DOM separately from layoutCallback
which enforces the prefer viewability constraint.  However, I am in the
process of making this work for AMP creatives so perhaps this is moot...

**Comment by keithwrightbos** [comment]
This is being addressed in #6249

**Pull request closed without merging**
