### PR TITLE
🚮 Removes Cxense Display/EAS support, which no longer exists

### PR DESCRIPTION
**Pull request by antosarho**
Cxense Display/EAS no longer exists as an ad server. This removes Cxense Display/EAS.

(EAS was the Emediate ad server before becoming Cxense Display and then being retired).

### CODE REVIEW

**Review by twifkak — COMMENTED** [review]
Thanks for the cleanup! Validator changes LGTM. I defer to @calebcordry for approval.

**Comment by calebcordry** [comment]
Sorry for the delay, I think I lost this one over the holidays.

**Review by calebcordry — APPROVED** [review]

**Comment by calebcordry** [comment]
@twifkak I think we need a proper approval on the validator files.

**Review by twifkak — APPROVED** [review]
My mistake. Merging.

**Pull request merged**
