### PR TITLE
:nth-child(1n) can be used to emulate *

### PR DESCRIPTION
**Pull request by azizhk**
So I was using this in https://github.com/azizhk/spectre-amp/blob/83b4c8f/src/base.less#L9
But I think you guys are open to https://github.com/ampproject/amphtml/pull/3360, so my purpose should get solved.

Please guide what files for validator.

### CODE REVIEW

**Comment by cramforce** [comment]
Nice catch. @Gregable can we disallow this?

**Comment by jridgewell** [comment]
Even if we were to explicitly ban `:nth-child(n)`, could we just get around this with `:nth-child(even), :nth-child(odd)` or numerous `:nth-child(An-b)` equations?

**Comment by cramforce** [comment]
I guess we should really think about how to improve our strategy here.

**Comment by Gregable** [comment]
I don't fully understand what this is trying to do, but there are a bazillion variations as @jridgewell was saying. You could use :not(.foo) for instance.

**Comment by jridgewell** [comment]
I think the most effective solution would be to require a tag, class, or id selector with these types of psuedo-selectors.

```
:nth-child(n) {
  /* invalid */
}
:not(.never-gonna-add-this-dumb-class) {
  /* invalid */
}


p:nth-child(n) {
  /* valid */
}
p:not(.never-gonna-add-this-dumb-class) {
  /* valid */
}
```

Then if you're really dedicated to selecting everything, you'd have to repeat the `nth-child` for every tag. We could even disallow `tag:nth-child(n)` with that, requiring you to type even more.

**Comment by cramforce** [comment]
@jridgewell Good idea. We could also allow `:not` with that. Classes are fine as well, doesn't have to be a tag.

**Comment by azizhk** [comment]
How about something like just `:nth-child` is not allowed.
You need to have some rule along with it.
Based on my understanding of your code in parse-css.js, you need to have some IDENT before FUNCTION_TOKEN nth-child without WHITESPACE in between.

`.abc:nth-child(1n)` allowed.
`.parent :nth-child(2n)` not allowed.

This also fixes the negative n case:
`:nth-child(-n + 10000)` would apply to all elements as long as there are no 10,001 sibling elements.

**Comment by azizhk** [comment]
Late to reply sorry, 👍  @jridgewell

**Comment by Gregable** [comment]
Is the goal to make it impossible to select certain elements or just a pita to write a universal selector? If you control the document, there are a lot of ways you can select any or all elements on the page. More examples:

- `:lang(en)`
- `[data-foo]` and then drop `data-foo` on every element on the page
- `nth-of-type(1)`, `nth-of-type(2)`, `nth-of-type(3)`, ...

There may be more, I'm not a CSS expert.

**Comment by cramforce** [comment]
@Gregable this is about inability to select elements that are off-limits for user CSS (mostly tag names starting with `i-`. That is why it would help to require tag/class in the pseudo selector.

**Comment by dvoytenko** [comment]
I think requiring class name would solve most of these issues. But we should probably review the cases where we think the universal selectors are harmful again - they may no longer be. We may need to add a few more `!important` in AMP's own CSS, but I think it's doable.

**Comment by jpettitt** [comment]
What exactly is the reason for disallowing `*` in the first place?  Mostly it seems to get used for setting box-model which seems legit.

**Comment by azizhk** [comment]
https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#universal-selector

1. https://github.com/ampproject/amphtml/pull/3375#issuecomment-222760705 (Above comment): 
Restrict users from modifying styles of `-amp-` & `i-amp` Elements.

2. `*` is considered slow. But not that slow. `.parent *` is very slow and that should be restricted. Or you can just leave that on (blame it on) the developer.

**Comment by cramforce** [comment]
@dvoytenko Did you put any more thought into whether the restriction can be lifted?

**Comment by dvoytenko** [comment]
@cramforce Yes, I believe that we can.

**Comment by jpettitt** [comment]
So can we get the doc updated to reflect the removal of the restriction?

**Comment by cramforce** [comment]
yes.

**Comment by azizhk** [comment]
You can also close https://github.com/ampproject/amphtml/pull/3360 as developers can implement universal `box-sizing: border-box` on their own now.

**Pull request closed without merging**
