### PR TITLE
♻️ ESLint Rules: Updates name and comment for enforce-private-props rule

### PR DESCRIPTION
**Pull request by ChrisAntaki**
- Adds comment describing the rule
- Updates filename to reflect the scope of the rule

### CODE REVIEW

**Comment by torch2424** [comment]
Triaging to @rsimha , feel free to re-assign 😄

**Comment by ChrisAntaki** [comment]
Sounds good, thanks!

**Comment by ChrisAntaki** [comment]
Just wanted to check in, is this ready to merge? 😄

**Comment by jridgewell** [comment]
Whoops, forgot to hit the merge button

**Comment by ChrisAntaki** [comment]
Thanks!

**Pull request merged**
