### PR TITLE
Disallow controls attribute on amp story video elements.

### PR DESCRIPTION
**Pull request by gmajoulet**
Disallow controls attribute on amp story video elements.

Warning: technically a breaking change

### CODE REVIEW

**Comment by Gregable** [comment]
Can you elaborate more on the risk of the breaking change part. "technically" suggests that maybe you believe the risk is insignificant. If you could explain why here, that would be helpful.

**Comment by gmajoulet** [comment]
Jon ran the numbers (cookbook) and I think the outcome was that we could do outreach to warn these publishers about this change, that would make their stories invalid.

cc @newmuis who knows more :)

**Comment by newmuis** [comment]
Yes, as far as I can tell, this affects 83 URLs from 13 domains, so we can take a more manual approach due to the low scale.  We should still do that before merging this PR, though.

**Comment by Gregable** [comment]
Thanks for adding documentation. Validator change LGTM.

**Comment by gmajoulet** [comment]
I updated this PR so it shows a deprecation warning instead of an error for now, and keeps the AMPHTML valid.

PTAL

**Pull request merged**
