### PR TITLE
🚮 [Story bookend] Add a warning for deprecating the bookend

### PR DESCRIPTION
**Pull request by mszylkowski**
Contributes to #26957

### CODE REVIEW

**Comment by gmajoulet** [comment]
Deprecation warnings need to come from validation, please:
1. Draft an I2R that we can review before posting, as we need to document replacements etc
2. Post the I2R
3. Use `deprecation` and `deprecation_url` validation fields so deprecation warnings link to the I2R

**Comment by mszylkowski** [comment]
@gmajoulet PTAL

**Review by gmajoulet — APPROVED** [review]

**Comment by gmajoulet** [comment]
to @ampproject/wg-caching for approval

**Review by newmuis — APPROVED** [review]

**Comment by gmajoulet** [comment]
Friendly ping @ampproject/wg-caching

**Review by Gregable — APPROVED** [review]

**Review by honeybadgerdontcare — CHANGES_REQUESTED** [review]
The I2D has not received the required three approvals

**Review by honeybadgerdontcare — APPROVED** [review]

**Comment by mszylkowski** [comment]
Bookend will be deprecated without warnings, so closing this PR

**Pull request closed without merging**
