### PR TITLE
✨ Update checkConsentHref for the iubenda <amp-consent> integration

### PR DESCRIPTION
**Pull request by Vasile-Peste**
This PR updates the `checkConsentHref` endpoint for the iubenda integration of the amp consent componet (cmps.js file). Due to internal developments and compatibility issues we decided to change the endpoint again. Thank you.

### CODE REVIEW

**Comment by Vasile-Peste** [comment]
Hi @zhouyx, this one should be very quick. Can we go ahead? Thanks!

**Comment by Vasile-Peste** [comment]
Hi, @micajuine-ho, I know you people at AMP are working on very important things, can we proceed also with this? It's a change on a line, should be quick, thank you all!

**Comment by micajuine-ho** [comment]
Hi @Vasile-Peste, is the test `promptUISrc` (https://cdn.iubenda.com/cs/test/cs-for-amp.html), sending the 'ready' postmessage to the parent AMP doc?

**Comment by Vasile-Peste** [comment]
> Hi @Vasile-Peste, is the test `promptUISrc` (https://cdn.iubenda.com/cs/test/cs-for-amp.html), sending the 'ready' postmessage to the parent AMP doc?

Hi, as we have already discussed here https://github.com/ampproject/amphtml/pull/28667 our "promptUISrc" is going to be overrided by the user custom configuration in the `amp-consent`  component, since we ask them to host the prompt ui. The current promptUiSrc is just a link to your guide on how to use our CMP with AMP.

**Comment by micajuine-ho** [comment]
Ok, thanks for the clarification.

**Review by micajuine-ho — APPROVED** [review]

**Comment by Vasile-Peste** [comment]
> Ok, thanks for the clarification.

Thank you!

**Pull request merged**
