### PR TITLE
don't generate a config if its not the main binary

### PR DESCRIPTION
**Pull request by erwinmombay**

### CODE REVIEW

**Comment by erwinmombay** [comment]
@cramforce PTAL

**Comment by cramforce** [comment]
Does this remove the config from alp.js?

I kind of like it there :)

**Comment by cramforce** [comment]
Maybe special case those 2

**Comment by erwinmombay** [comment]
@cramforce ah ok, wasnt sure if we needed it there. reverting this. i do need to update the promote script  so that it does get switched from canary: true to canary: false on promotion

**Comment by cramforce** [comment]
Would be nice, but low priority.

It is needed to predict the right version rtv prefix for the user. Right now it is hard coded to be stable, which is really good enough, but would be nice to do better.

**Pull request closed without merging**
