### PR TITLE
✨Implementation of runative ad

### PR DESCRIPTION
**Pull request by DErekXx**
Implement native ad of "runative" ads network

### CODE REVIEW

**Comment by DErekXx** [comment]
I signed it!

**Comment by lannka** [comment]
@DErekXx could not find your GitHub account in Google's CLA list. Could you confirm that you signed as individual?

**Comment by DErekXx** [comment]
@lannka ,  yes. I signed Contributor License Agreement (CLA) as individual

**Comment by lannka** [comment]
@DErekXx did you sign under your GH account? I still cannot find it in Google CLA registry.

**Comment by DErekXx** [comment]
@lannka , I'm very sorry, I had a mistake in my GitHub username.

**Pull request closed without merging**
