### PR TITLE
Bento: Enable `npm` for `amp-video`

### PR DESCRIPTION
**Pull request by caroqliu**
Tracker Issue: #34137

### CODE REVIEW

**Review by rcebulko — APPROVED** [review]
LGTM

**Review by alanorozco — APPROVED** [review]
Thanks!

**Comment by estherkim** [comment]
Hii if you want this to be published automatically, `"npm": true` needs to be set here https://github.com/ampproject/amphtml/blob/main/build-system/compile/bundles.config.extensions.json#L1090-L1097

**Comment by caroqliu** [comment]
> Hii if you want this to be published automatically, `"npm": true` needs to be set here https://github.com/ampproject/amphtml/blob/main/build-system/compile/bundles.config.extensions.json#L1090-L1097

🤦 Good catch, missed the one important bit we needed. I'll rename this PR to reflect what actually happened.

**Pull request merged**
