### PR TITLE
Remove "experimental" label from amp-fx-flying-carpet.md

### PR DESCRIPTION
**Pull request by ericlindley-g**
I think the component is now live, so I'm just submitting a tiny update to the docs I noticed while posting the roadmap.  PTAL

/to @jridgewell @jasti

### CODE REVIEW

**Comment by ericlindley-g** [comment]
Thanks @jridgewell ! And FYI, someone with merging rights will have to merge for me : )

**Comment by jridgewell** [comment]
Blocked by removing the actual experiment (and @jasti telling me flying carpet is prod ready).

**Comment by jasti** [comment]
Thanks @ericlindley-g & yes, @jridgewell .

**Comment by jridgewell** [comment]
Superseded by #6286.

**Pull request closed without merging**
