### PR TITLE
Added Bento flag to bento components frontmatter

### PR DESCRIPTION
**Pull request by CrystalOnScript**
Resolves [issue #31609](https://github.com/ampproject/amphtml/issues/31609)

### CODE REVIEW

**Review by caroqliu — APPROVED** [review]
Question: Do we need both `formats: bento` and `bento: true` in the frontmatter?

**Comment by CrystalOnScript** [comment]
Ah, good question - I'll wait for @sebastianbenz to confirm

**Comment by sebastianbenz** [comment]
Good catch @caroqliu! We only need `bento: true`.

**Comment by CrystalOnScript** [comment]
¯\_(ツ)_/¯

**Pull request closed without merging**
