### PR TITLE
Feature / Add render start support for Teads.

### PR DESCRIPTION
**Pull request by slabruyere**
**Description**
Teads now supports render start.

**Link**
https://github.com/ampproject/amphtml/issues/5234

### CODE REVIEW

**Comment by slabruyere** [comment]
@googlebot CLA Signed on behalf of Corporation "Teads"

**Comment by slabruyere** [comment]
@googlebot CLA Signed on behalf of Corporation "Teads"

**Comment by slabruyere** [comment]
@googlebot CLA Signed on behalf of Corporation "Teads"

**Comment by lannka** [comment]
@slabruyere did you make the example in `http://localhost:8000/examples/ads.amp.max.html?type=teads` working? I cannot load an ad.

**Comment by slabruyere** [comment]
@lannka The example doesn't work because of a small difference between the requested size and the accepted one. We need to add some tolerance on those values.

As for the CLA, it was first signed almost a year ago => https://github.com/ampproject/amphtml/pull/2190 . The corp name is Teads indeed.

**Comment by lannka** [comment]
@slabruyere would you fix the example?
@cramforce I don't find "Teads" in our CLA list. Is it an exception?

**Comment by cramforce** [comment]
@slabruyere Could you make sure the CLA process went through?

**Comment by jasti** [comment]
ping @slabruyere

**Comment by lannka** [comment]
closing for now. feel free to reopen.

**Pull request closed without merging**
