### PR TITLE
Validator Roll-up

### PR DESCRIPTION
**Pull request by Gregable**
Changes affecting PASS/FAIL:
 - Validate `<a rel="noopener">`. Github #2641
 - Validate https://fonts.googleapis.com/icon (Material Icons) as fonts. Github #2645
 - Validate template attribute in `<amp-list>`. Github #2517
 - Validate `<amp-social-share>`.
 - Validate <link rel="standout" href="...">. Github #2705
 - Invalidate malformed attributes that start with a `/` but don't form a closing tag.

### CODE REVIEW

**Comment by Gregable** [comment]
@honeybadgerdontcare @powdercloud for review

**Comment by powdercloud** [comment]
@googlebot confirmed

**Comment by honeybadgerdontcare** [comment]
@googlebot confirmed

**Comment by Gregable** [comment]
@erwinmombay as well. googlebot wants you to confirm that you authored the commit that I'm pulling on your behalf. Also, you will want this for release notes.

**Pull request merged**
