### PR TITLE
📖amp-consent: Add Didomi CMP documentation + example

### PR DESCRIPTION
**Pull request by MaximePlancke**
Add Didomi documentation and example to AMP related to this comment: 
https://github.com/ampproject/amphtml/pull/21693#issuecomment-481048450
https://github.com/ampproject/amphtml/pull/21752

### CODE REVIEW

**Comment by torch2424** [comment]
@MaximePlancke 

Per your comment in #21752 Feel free to @ mention me when things are finished up on your side, so I can take a look, review, and get this merged 😄

**Comment by MaximePlancke** [comment]
@torch2424 

We are done with the documentation and the links are now working. It is ready for review on your side :).

Reloading the checks should make travis pass the tests now. Are you able to reload or should I do it on my end? 

Thank you!

**Comment by torch2424** [comment]
Huh, looking at the [travis build](https://travis-ci.org/ampproject/amphtml/jobs/537815390), seems like it is erroring on "dead links"?

Do you know anything about this @zhouyx @erwinmombay @rsimha ? Thanks! 😄

**Comment by MaximePlancke** [comment]
@torch2424 

Just to clarify, this link `https://developers.didomi.io/cmp/amp` was not working when I ran travis. They are now working. Is there a way to reload the travis check without committing again?

**Comment by zhouyx** [comment]
Thank you for your integration. LGTM! 🎉

**Comment by zhouyx** [comment]
I restarted the travis build. See different error
image


@estherkim This looks similar to the error I saw from #22696. Do you think rebase will solve the issue. Thank you!

**Comment by estherkim** [comment]
It looks like that job skipped an important installation step (`pip install --user protobuf` in the `before_install` stage) and I don't know why. Can you try restarting the build again?

**Comment by zhouyx** [comment]
Restarted the build. no luck. @MaximePlancke could you please try rebase? Thank you

**Comment by MaximePlancke** [comment]
@zhouyx Sorry I think I rebase the wrong way I have all the commits (I am not use to work with fork and must have miss one step). I'll most likely close this PR and reopen one with the updated code

**Comment by zhouyx** [comment]
Sounds good. Thanks for letting me know.

**Comment by torch2424** [comment]
@MaximePlancke Thanks for letting us know! 😄

**Pull request closed without merging**
