### PR TITLE
Fix bad set types

### PR DESCRIPTION
**Pull request by erwinmombay**
while trying to switch to maven, it detected these bad/incompatible types

### CODE REVIEW

**Comment by nainar** [comment]
@erwinmombay is this ready to be merged?

**Comment by erwinmombay** [comment]
@nainar yes sorry. ill rebase and rebuild and merge

**Comment by mrjoro** [comment]
@erwinmombay do you still intend to merge this PR?

**Comment by mrjoro** [comment]
Closing this for now since there are no updates; please reopen if needed.

**Pull request closed without merging**
