### PR TITLE
add badges front and center.

### PR DESCRIPTION
**Pull request by erwinmombay**
especially since our builds are failing :(
screen shot 2015-10-08 at 7 24 34 pm

### CODE REVIEW

**Comment by jmadler** [comment]
FYI some are currently in DEVELOPING.md -- If you want to move these to the README, remove from there.

Also, the first badge doesn't horizontally align with other two - kind of annoying :\

**Comment by erwinmombay** [comment]
oh didnt realize we had it on there. yeah i would rather them be in the front page. 

looks like its broken there anyways https://github.com/ampproject/amphtml/blob/master/DEVELOPING.md (guessing since we switched to free for travis?)
will remove on this PR.

**Comment by erwinmombay** [comment]
updated.

/cc @jmadler

**Comment by jmadler** [comment]
LGTM

**Pull request merged**
