### PR TITLE
Experiment turning on splitted vendor integration JS

### PR DESCRIPTION
**Pull request by powerivq**
Use the vendor specific integration js rather than `f.js` that contains all the vendors.

### CODE REVIEW

**Review by lannka — APPROVED** [review]

**Review by micajuine-ho — APPROVED** [review]
Approval for wg-components owned files.

**Comment by estherkim** [comment]
reassigning to @rsimha for build changes :)

**Review by rsimha — APPROVED** [review]
Build changes LGTM.

**Comment by rsimha** [comment]
@powerivq Curious: Were the build changes in this PR reverted? (Looks like the original commit was amended after it was reviewed, which makes it hard to tell if / why something changed.)

**Comment by powerivq** [comment]
@rsimha Yes they are reverted. There was merge conflict and have been reverted during rebasing so there is no history of that.

**Pull request merged**
