### PR TITLE
✨ protocol adapters prototype (warning: do not look at the code)

### PR DESCRIPTION
**Pull request by samouri**
**summary**
Prototypes both https://github.com/ampproject/amphtml/issues/26474 and https://github.com/ampproject/amphtml/issues/25684 (should be delivered separately if we choose to)

This allows you to use js as a datasource for both bind expressions as well as for `amp-list`. For example:

```html
<p [text]="script:getText">
<amp-list src="script:getData()">...</amp-list>

<script target="amp-bind">
  function getData() {
   return { items: [1,2,3,4,5] };
  }

  function getText() { 
    return 'hello, world'
  }
</script>
```

**open question**
- Should this be implemented in `amp-bind` or `amp-script` (worker-dom)? There are many tradeoffs here:
  - only `amp-script` can interact with the DOM. Do we want these functions to be able to as well (beyond what amp-bind allows).
  - Perf difference. If incorporated as part of amp-bind, it is more performant (since it doesn't require including `amp-script`).
  - Do we want these functions to be generic data sources that could be plugged in to any bind expr (https://github.com/ampproject/amphtml/issues/25684)?

### CODE REVIEW

**Comment by samouri** [comment]
Had a discussion with @choumx on this. After some back and forth, we answered the above questions as follow:
- `amp-script` is a better home for this functionality than `amp-bind`.
   - we can create a new "lite" build target for `worker-dom` that doesn't include dom functionality. perfect for those only interested in transforms.
- Still to be determined if we want to open this up to all of amp-bind

**Comment by morsssss** [comment]
this is... my dream! That a mechanism drawn from the realm of <amp-script> could be used to implement both of these ideas.

This prototype also looks shockingly simple.

But you're not sure if you want to allow this in amp-bind as requested in #25684?

**Comment by Gregable** [comment]
This appears to be inactive, so closing. Also, we can't approve a validator change that would allow a `script:` URL protocol.

**Comment by morsssss** [comment]
And, indeed, we already released a different implementation of that feature in https://github.com/ampproject/amphtml/pull/29329!

**Pull request closed without merging**
