### PR TITLE
✨ amp-story-360 extension (base functionality)

### PR DESCRIPTION
**Pull request by t0mg**
Introduces the amp-story-360 element that leverages third_party/zuho to render equirectangular panoramas in WebGL. Includes an example amp-story loading a panorama and animating between 2 points of view.

- TODO next: video support and EAC projection support
- Validator and md are placeholders and will be updated in separate PRs

I2I owned by @gmajoulet

### CODE REVIEW

**Comment by t0mg** [comment]
friendly ping @gmajoulet :)

**Comment by twifkak** [comment]
@rsimha Any idea why owners-bot didn't add @ampproject/wg-caching to this PR? It contains validator changes.

@t0mg Thanks! I'll review the protoascii portion of this PR in a bit. (You may want to update your PR description to reflect it has validator changes.)

**Comment by gmajoulet** [comment]
cc @ampproject/wg-stories

**Comment by t0mg** [comment]
Sorry I messed up this PR - closing and replacing with https://github.com/ampproject/amphtml/pull/29023

**Pull request closed without merging**
