### PR TITLE
Add gdpr_consented_providers configuration for google GDPR

### PR DESCRIPTION
**Pull request by xiaofengC**
Add gdpr_consented_providers configuration for google GDPR

### CODE REVIEW

**Comment by torch2424** [comment]
Hello,

Thanks for the contribution! Please see the CLA advice above, and let us know if you need any help with it. Also, it seems the travis wants you to run our linter `gulp lint --fix --local-changes`. Please see the results from that in order to pass the tests 👍 

cc @loic-sticky Would be nice to get your input here as well since you opened the original PR 😄

**Comment by xiaofengC** [comment]
I signed it!

**Comment by torch2424** [comment]
@xiaofengC Could you try making a small whitespace commit or something of that sort to get it to run again?

**Comment by xiaofengC** [comment]
@torch2424 , just did , sry missed your message earlier.

**Comment by torch2424** [comment]
@xiaofengC Hmm so the CLA seems to still not be working. Are you sure you signed the CLA with the same email address that you used in your `git config`? Or are you under a corporate CLA? 🤔 

Thanks! 😄

**Comment by mrjoro** [comment]
Hi @xiaofengC, were you able to get the CLA issues resolved?  We need to ensure all code that is merged into amphtml is covered by a CLA.

For more information, check out https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#contributor-license-agreement

Let us know if you are still having issues signing it.

**Comment by xiaofengC** [comment]
Hi Joey ,
Sorry , I'm still waiting a response from our legal team , will update once
finalized .

thank you
Xiaofeng Chen

**Comment by mrjoro** [comment]
I'm closing this PR for now; please reopen once the CLA issues are resolved.

/cc @ampproject/wg-ads

**Pull request closed without merging**
