### PR TITLE
<amp-bodymovin-animation> Fix imports in example

### PR DESCRIPTION
**Pull request by nainar**
Fixes a mistake in the import in the examples file.

### CODE REVIEW

**Comment by cathyxz** [comment]
The sidebar focus test that failed is mine. I'll increase the timeout on that one or otherwise investigate.

**Comment by nainar** [comment]
@cathyxz I don't understand your comment? Did I miss something on the bot runs? 

Also please merge this when appropriate? Thank you!

**Comment by cathyxz** [comment]
@nainar I was referring to the failing integration test on Travis. I restarted it so if you didn't see the failed logs you probably don't know what I'm talking about.

**Comment by nainar** [comment]
Aahhh gotcha! Thank you for restarting the bots for me! 😄

**Pull request merged**
