### PR TITLE
Add how amp-live-list works

### PR DESCRIPTION
**Pull request by dandv**
That paragraph from [the blog](https://amphtml.wordpress.com/2016/07/26/live-updating-amps/) explained `amp-live-list` far better for me than the doc and [the amp-by-example sample](https://github.com/ampproject/amp-by-example/pull/457).

Even better - can we also add an image, such as [this one](https://amphtml.files.wordpress.com/2016/07/amp-live-list-flow.png?w=768) and [the animated demo](https://amphtml.files.wordpress.com/2016/07/amp-live-list-demo.gif?w=446&h=630)?

### CODE REVIEW

**Comment by erwinmombay** [comment]
@ericlindley-g i think adding the images is a good idea, wdyt

**Comment by dandv** [comment]
> what do you think about slotting it in after the first paragraph, which describes the larger motivation for using the component?

SGTM, feel free to move accordingly.

**Comment by erwinmombay** [comment]
@ericlindley-g can you review if the move i did makes sense

**Comment by ericlindley-g** [comment]
LGTM—thanks!

**Pull request merged**
