### PR TITLE
✨ Add prebidopenx as a vendor to RTC config

### PR DESCRIPTION
**Pull request by luigi-sayson**
* add prebidopenx as a vendor to RTC config
* add vendor to documentation pages

### CODE REVIEW

**Comment by luigi-sayson** [comment]
@kenan-gillet is out this week. I'll tell him about the CLA when he gets back

**Comment by deivydas** [comment]
Hi @calebcordry,
I hope you are well.
Could you please have a look at this PR ?
Thanks in advance!

**Review by calebcordry — APPROVED** [review]

**Comment by calebcordry** [comment]
Thanks for contributing and getting the CLA sorted out! There appears to be something weird going on with CircleCI, could you please try rebasing latest master? Let me know if you have any issues.

**Comment by luigi-sayson** [comment]
Hi. I rebased but the percy tests failed and I don't think it has anything to do with the changes here. I see similar failures in other open PRs here. Seems like it's a common problem?

**Comment by calebcordry** [comment]
Thanks for the rebase, I can manually approve percy, but the CircleCI check was broken before. Regardless, its merged now :)

**Pull request merged**
