### PR TITLE
Prune unused deps 2

### PR DESCRIPTION
**Pull request by psyrendust**
Submitting again to force travis-ci to re-run.

## Changes
* [6e9357a] chore(package): prune deps that are no longer used in package.json
* [09542af] chore(gulpfile): remove unused var argv in gulpfile
* [51196c3] fix(gulpfile): remove duplicate var declaration for fs in gulpfile

### CODE REVIEW

**Comment by psyrendust** [comment]
@erwinmombay resubmitted

**Comment by psyrendust** [comment]
It's going to fail. I know what the error is. `npm install` is failing. I ran into this issue awhile back with node `@4.0.0`, which is what travis is setup to use. I'll bump this to node `@4.1.2` and run the build again.

**Comment by psyrendust** [comment]
@erwinmombay Hm, well this seemed to have passed. But there is an issue with `npm install` tossing errors like (I counted about 4 of them).

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v4.0.0/bin/node" "/home/travis/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/ampproject/amphtml/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
```

If you are cool with this PR, then I'll submit another one that bumps the version of node to `@4.1` to see if that takes care of the `npm install` errors.

**Comment by erwinmombay** [comment]
@psyrendust LGTM.

the errors already exist on master so this PR isnt a cause of it for sure. :+1: thanks again for cleaning up our gulpfile!

**Pull request merged**
