### PR TITLE
🔥  amp-connatix-player: Update iframe domain and path for our existing amp-connatix-player.js

### PR DESCRIPTION
**Pull request by rares-mihai-preda**
Update iframe domain and path for our existing amp-connatix-player.js component

### CODE REVIEW

**Comment by rares-mihai-preda** [comment]
@alanorozco Thanks for approving the PR.

What would be the next step for having this update in master? Currently, we have a cache issue and we need to update the iframe domain and path in order to solve the problem.

Do you think it would need an I2I or a Design Review?

**Comment by mrjoro** [comment]
@alanorozco @caroqliu is anything else needed here or can we merge it in?

**Comment by alanorozco** [comment]
@rares-mihai-preda I'm rerunning Travis tests and I'll merge once they pass. Thanks!

**Comment by rares-mihai-preda** [comment]
> @rares-mihai-preda I'm rerunning Travis tests and I'll merge once they pass. Thanks!

Thanks @alanorozco ! I see that travis-ci looks like is still pending but if I go to details, it shows that all check passed. It would need a re-run again before merging?

**Comment by alanorozco** [comment]
@rares-mihai-preda Travis was running on degraded service for a while yesterday, so the overall check wasn't reported. I'm running it again, hopefully all goes well this time.

**Comment by rares-mihai-preda** [comment]
> @rares-mihai-preda Travis was running on degraded service for a while yesterday, so the overall check wasn't reported. I'm running it again, hopefully, all goes well this time.

Hi @alanorozco ! Thanks for your support! It seems that travis-ci failed this time. I tried to re-run it but I think it is not possible due to write permissions. Could you re-run the pipeline again, please? Hope this time we'll have luck and it can be merged.

**Comment by rares-mihai-preda** [comment]
> > @rares-mihai-preda Travis was running on degraded service for a while yesterday, so the overall check wasn't reported. I'm running it again, hopefully, all goes well this time.
> 
> Hi @alanorozco ! Thanks for your support! It seems that travis-ci failed this time. I tried to re-run it but I think it is not possible due to write permissions. Could you re-run the pipeline again, please? Hope this time we'll have luck and it can be merged.

Hi @alanorozco ! 

We did a rebase with master today which triggered a new build.
It failed at step Remote (Sauce Labs) Tests. We observed that every build that succeeded on master failed at this step. This already happened to us a couple of times.
Could you help us solve this?
It's very important for us to merge this as soon as possible.
Thank you!

**Comment by alanorozco** [comment]
@rares-mihai-preda Did you rebase from the most recent master?

**Comment by rares-mihai-preda** [comment]
> @rares-mihai-preda Did you rebase from the most recent master?

@alanorozco Yes, it was rebased from the most recent master. I see that the problem still persist on succeeded builds on master https://travis-ci.org/github/ampproject/amphtml/builds

Kevin Kimball (@kevinkimball) told us that "There's a problem with the sauce test right now (documented in github issue) which is causing it to fail, however PRs can be merged with it failing right now" on #contributing channel on Slack.

**Comment by rares-mihai-preda** [comment]
> @rares-mihai-preda Ah, I missed that I could merge it! My bad. It's merged now.

@alanorozco Thanks!

**Pull request merged**
