### PR TITLE
Add validator-amp-sidebar.out

### PR DESCRIPTION
**Pull request by honeybadgerdontcare**
Addressing #9730 brought about with #9805 missing test .out file.

### CODE REVIEW

**Comment by honeybadgerdontcare** [comment]
The actual text matters once PR #9812 is merged. The text says FAIL because the test file is invalid AMP otherwise it would say PASS.

**Comment by rsimha-amp** [comment]
@honeybadgerdontcare: SGTM. Thanks.

**Comment by rsimha-amp** [comment]
Still broken, but due to a different error: https://travis-ci.org/ampproject/amphtml/jobs/241334325

**Comment by Gregable** [comment]
Taking a look now.

**Comment by Gregable** [comment]
See https://github.com/ampproject/amphtml/pull/9834

**Comment by Gregable** [comment]
These validator changes should be live everywhere within an hour.

**Pull request merged**
