### PR TITLE
inabox-lite: setup input mode classes.

### LINKED ISSUE #25402: inabox-lite is missing amp-mode-mouse
This is caught by Percy: https://percy.io/ampproject/amphtml/builds/3002714?utm_campaign=ampproject&utm_content=amphtml&utm_source=github_status_public

Should consider moving the following logic to somewhere shared with inabox and AMP runtime:
https://github.com/ampproject/amphtml/blob/dc8e85a0fd619eaa68c1c59f71b792b10a77a2a2/src/service/resources-impl.js#L321-L345

This will unblock #25293

### PR DESCRIPTION
**Pull request by lannka**
Fixes #25402

### CODE REVIEW

**Comment by lannka** [comment]
The test failure is irrelevant and caused by #25411

**Comment by lannka** [comment]
No tests need to move. But seem reasonable to add a unit test for the new public method in `input` service. While I'm working on that test, I assume the refactoring looks good?

**Comment by dvoytenko** [comment]
@lannka Yep. Otherwise it's LGTM.

**Comment by lannka** [comment]
Tests added. PTAL @dvoytenko

**Pull request merged**
