### PR TITLE
🏗✅ Make visual diff tests hermetic

### PR DESCRIPTION
**Pull request by danielrozenberg**
This PR:
* replaces all* external resources used by visual diff tests with local ones
* replaces images that I don't know where they're from with pictures from Picsum, which are in turn pictures from Unsplash, which are Public Domain pictures
* BLOCKS external (non-localhost) network for access for visual diff tests, unless they are defined with the new flag `allow_external_network_access` set to `true`
  * Currently only one test is using this flag, and I will work with its author to remove external network dependency if possible
  * Some external resources are required by some tests, such as those coming from `cdn.ampproject.org` or `fonts.googleapis.com`. Those are now MOCKED by the test runner (i.e., the test runner returns a local, frozen copy of those external assets)
* Disables a single test that I could not make work. After submitting this PR I will try to fix it

Progress on #21056

*all that are required to make the tests pass

### CODE REVIEW

**Comment by danielrozenberg** [comment]
Literally just sent this PR to review, it didn't even have time to run on Travis 😅

**Comment by zombifier** [comment]
Hi, I wrote the GPT.js test which is the only test remaining that requires external access. The test never loaded AMP locally since there is no support for proxying (I could change GPT itself so it loads AMP locally but didn't find the time to do so), and with your submitted changes it would likely break entirely.
In my opinion you can delete the test completely (and don't add `allow_external_network_access`). In the future I will create more basic AMP creative tests for both AMP and non-AMP pages which wouldn't need external network access at all.
Thanks.

**Comment by danielrozenberg** [comment]
@zombifier done - I removed the optional flag and disabled (but not completely removed) your test. I'll be happy to work with you to modify this test to be hermetic!

**Comment by danielrozenberg** [comment]
@rsimha approve the Percy build for me? Can always use an extra pair of eyes instead of blindly approving mine.

Things to note:
* I'm not sure why some of the images have those tiny pixel shifts, maybe the network cached a different version of them before?
* I swapped the images for amp-consent and amp-according with images from picsum.photos, which are Public Domain images. I'm just not sure where those other images came from, so I prefer to swap them...

**Comment by rsimha** [comment]
Approved diffs. Some images appear to have changed, which seems reasonable given what you're doing in this PR. A good check might be to re-run this and see if the same diffs occur.

**Comment by danielrozenberg** [comment]
I reran this several times locally (I don't want to jinx this successful execution by rerunning it on Travis… there's still #21882 that should help fix the timeouts) and the results are consistent. Merging this now…

**Pull request merged**
