### PR TITLE
Update file with CTN

### PR DESCRIPTION
**Pull request by ColombiaOnline**
Here is my new contribution.
commit updated file link is https://github.com/ColombiaOnline/amphtml/commit/4ad0dae5bf88deb535a0a4c955b6b76b4926f6bf

### CODE REVIEW

**Comment by lannka** [comment]
@ColombiaOnline i guess you were on a very old branch. can you sync to master?

**Comment by ColombiaOnline** [comment]
@lannka Hi I have also sync  to master. i have 15 commits please merge into  ampproject:master from  ColombiaOnline:master.

amp_pull 

Thanks

**Comment by lannka** [comment]
@ColombiaOnline you will need to resolve the merge conflicts.

**Comment by lannka** [comment]
@ColombiaOnline a kind ping, are you still on this?

**Comment by ColombiaOnline** [comment]
@lannka 
Hi , We have resolve the conflicts and push on master. Please marge updated commits.

**Comment by lannka** [comment]
@ColombiaOnline the conflicts are still there

**Comment by ColombiaOnline** [comment]
Hi lannka,
After resolved conflicts i will reopen this tickets.

**Comment by ColombiaOnline** [comment]
Hi lannka,
We have resolved conflicts and execute upstream command. Please verify all commits and share conflicts status. i have also share local repository status. Please merge after reopen tickets.
git_update

**Comment by lannka** [comment]
Reopened, can you push your change?

**Comment by ColombiaOnline** [comment]
@lannka,
I am very confused. i execute git pull but we are not getting conflict files and i have push all local changes on git-hub. please help me how to resolve conflict files or getting in local directory.

**Comment by lannka** [comment]
Can you run `git remote -v` and paste the results (remove any credential from the results) so I can assist you.

**Comment by ColombiaOnline** [comment]
@lannka 
$ git remote -v
origin  https://github.com/ColombiaOnline/amphtml.git (fetch)
origin  https://github.com/ColombiaOnline/amphtml.git (push)

amp_remote

**Comment by lannka** [comment]
@ColombiaOnline can you add AMP repo as "upstream". This is [how-to](https://help.github.com/articles/adding-a-remote/).
After that, you should be able to 
```
git pull upstream master
```

after resolving any conflicts, then you can 
```
git push origin master
```

**Comment by ColombiaOnline** [comment]
@lannka , 
Thanks for help
i have execute following commands
-> git remote add upstream  https://github.com/ColombiaOnline/amphtml.git
-> git pull upstream master
getting response : "From https://github.com/ColombiaOnline/amphtml
 * branch              master     -> FETCH_HEAD
 * [new branch]        master     -> upstream/master
Already up-to-date."
-> git status 
 getting response: "On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean"

git_responce

**Comment by jridgewell** [comment]
Your using the wrong `upstream` repo. Execute:

```bash
git remote remove upstream
git remote add upstream https://github.com/ampproject/amphtml.git
git fetch upstream
```

Then you can do the rebase.

**Pull request closed without merging**
