### PR TITLE
Restart failing `<amp-bodymovin-animation>` integration test

### PR DESCRIPTION
**Pull request by nainar**
This addresses one of the test failures in #14360 

This test doesn't seem to be surfacing any console errors - hence I am just turning it on again.

### CODE REVIEW

**Comment by nainar** [comment]
Hi @rsimha, this test isn't throwing any console errors locally so I tried running the bots which seem happy too! Is it ok for me to unskip this?

**Comment by rsimha** [comment]
@nainar See https://travis-ci.org/ampproject/amphtml/jobs/361934486#L767-L770 for why I had to disable this test. It's an error all right, but it was at a deeper layer than this test, or the component it is testing.

**Comment by nainar** [comment]
@rsimha I see that amp-sidebar had the same test failure - https://travis-ci.org/ampproject/amphtml/jobs/361934486#L775. Should I file an issue for this? 

Also since the error is legit I would assume I should not land this fix until the lower level issue gets fixed?

**Comment by nainar** [comment]
@rsimha - Should I file the issue for the lower level issue causing this failure? I see that `<amp-sidebar>` had the same failure as well. https://travis-ci.org/ampproject/amphtml/jobs/361934486#L775

Also I am guessing in that case I shouldn't land this fix till the lower level issues gets fixed?

**Comment by rsimha** [comment]
Adding @alanorozco who I believe ran into the same error when he was working on video tests. It's possible there's some kind of race or dirty state that's common to all the video tests. Maybe there's a clue in the latest error logs that can help fix a real issue?

**Comment by rsimha** [comment]
@nainar I just saw your observation about `amp-sidebar`. Yeah, might we worth filing a separate issue for the `no resources yet, since element is not attached` error.

**Comment by alanorozco** [comment]
@rsimha 

State of player tests is a little bit tangled at the moment. It's very likely that there is a common cause. I'll investigate further.

Thanks @nainar for enabling the test.

**Pull request merged**
