### PR TITLE
Quick fix for dep ordering issue in closure compiler with promise polyfill.

### LINKED ISSUE #1670: Promise errors observed in IE11
Error when using <amp pixel> with IE11: "Promise" is undefined v0.js (273,395)
Is it possible add "Promise" support with polyfill ?

### PR DESCRIPTION
**Pull request by cramforce**
Fix is not ideal, but it does come with a regression test.

Fixes #1670

### CODE REVIEW

**Comment by cramforce** [comment]
Merging. @erwinmombay Please do a post-review.

**Comment by erwinmombay** [comment]
@cramforce slightly concerned with how big the latest file size became (gzipped) https://github.com/ampproject/amphtml/pull/1678/files

**Comment by cramforce** [comment]
@erwinmombay But that is not this change, right? We should binary search when it happened.

**Comment by erwinmombay** [comment]
@cramforce yeah thats not the exact correct delta, will update in a few minute with exact delta

**Comment by erwinmombay** [comment]
sha: 66ec7f8 (the commit prior to this, in master)

      max   |         min   |       gzip   |   file
      ---   |         ---   |        ---   |   ---
529.51 kB   |   148.77 kB   |    41.9 kB   |   v0.js / amp.js
275.69 kB   |     74.6 kB   |   22.34 kB   |   v0/amp-access-0.1.js
255.43 kB   |    70.47 kB   |    23.2 kB   |   v0/amp-analytics-0.1.js
 38.35 kB   |    10.17 kB   |    3.89 kB   |   v0/amp-anim-0.1.js
 32.86 kB   |     9.34 kB   |    3.64 kB   |   v0/amp-audio-0.1.js
 24.74 kB   |     7.26 kB   |    2.86 kB   |   v0/amp-brightcove-0.1.js
157.25 kB   |    37.97 kB   |    11.3 kB   |   v0/amp-carousel-0.1.js
 43.56 kB   |     8.93 kB   |    3.51 kB   |   v0/amp-dynamic-css-classes-0.1.js
  66.2 kB   |    16.23 kB   |    6.01 kB   |   v0/amp-facebook-0.1.js
 22.15 kB   |     7.24 kB   |    2.84 kB   |   v0/amp-fit-text-0.1.js
 38.44 kB   |    10.03 kB   |     3.5 kB   |   v0/amp-font-0.1.js
 70.81 kB   |    17.82 kB   |    6.28 kB   |   v0/amp-iframe-0.1.js
181.43 kB   |    47.91 kB   |   13.63 kB   |   v0/amp-image-lightbox-0.1.js
 23.69 kB   |     6.59 kB   |    2.68 kB   |   v0/amp-instagram-0.1.js
  20.4 kB   |      6.1 kB   |    2.51 kB   |   v0/amp-install-serviceworker-0.1.js
 89.73 kB   |    18.39 kB   |    5.73 kB   |   v0/amp-lightbox-0.1.js
201.44 kB   |    49.89 kB   |   14.94 kB   |   v0/amp-list-0.1.js
102.97 kB   |    34.06 kB   |   11.72 kB   |   v0/amp-mustache-0.1.js
 62.89 kB   |    24.81 kB   |    7.72 kB   |   v0/amp-pinterest-0.1.js
 76.53 kB   |    19.27 kB   |     6.7 kB   |   v0/amp-slides-0.1.js
 66.31 kB   |    16.24 kB   |    6.01 kB   |   v0/amp-twitter-0.1.js
215.51 kB   |    53.92 kB   |   15.97 kB   |   v0/amp-user-notification-0.1.js
  23.5 kB   |      6.7 kB   |    2.71 kB   |   v0/amp-vine-0.1.js
 23.88 kB   |     6.86 kB   |    2.79 kB   |   v0/amp-youtube-0.1.js
 53.41 kB   |    13.03 kB   |    4.93 kB   |   current-min/f.js / current/integration.js

--

sha: 084eac2 (this commit)

      max   |         min   |       gzip   |   file
      ---   |         ---   |        ---   |   ---
529.55 kB   |   148.77 kB   |   41.79 kB   |   v0.js / amp.js
329.49 kB   |    90.33 kB   |   28.58 kB   |   v0/amp-access-0.1.js
309.22 kB   |    86.23 kB   |   29.33 kB   |   v0/amp-analytics-0.1.js
 92.12 kB   |    25.79 kB   |    9.97 kB   |   v0/amp-anim-0.1.js
 86.63 kB   |    24.96 kB   |    9.76 kB   |   v0/amp-audio-0.1.js
  78.5 kB   |    22.85 kB   |    8.96 kB   |   v0/amp-brightcove-0.1.js
211.04 kB   |     53.7 kB   |   17.42 kB   |   v0/amp-carousel-0.1.js
 97.34 kB   |    24.57 kB   |    9.74 kB   |   v0/amp-dynamic-css-classes-0.1.js
119.98 kB   |    31.92 kB   |   12.13 kB   |   v0/amp-facebook-0.1.js
 22.15 kB   |     7.24 kB   |    2.84 kB   |   v0/amp-fit-text-0.1.js
 92.21 kB   |    25.63 kB   |     9.6 kB   |   v0/amp-font-0.1.js
124.59 kB   |     33.5 kB   |   12.38 kB   |   v0/amp-iframe-0.1.js
235.21 kB   |    63.67 kB   |   19.73 kB   |   v0/amp-image-lightbox-0.1.js
 77.46 kB   |    22.18 kB   |    8.79 kB   |   v0/amp-instagram-0.1.js
  20.4 kB   |      6.1 kB   |    2.51 kB   |   v0/amp-install-serviceworker-0.1.js
143.51 kB   |    34.05 kB   |   11.86 kB   |   v0/amp-lightbox-0.1.js
255.23 kB   |    65.62 kB   |   21.16 kB   |   v0/amp-list-0.1.js
102.97 kB   |    34.06 kB   |   11.72 kB   |   v0/amp-mustache-0.1.js
 62.89 kB   |    24.81 kB   |    7.72 kB   |   v0/amp-pinterest-0.1.js
130.31 kB   |    34.97 kB   |   12.82 kB   |   v0/amp-slides-0.1.js
120.09 kB   |    31.93 kB   |   12.13 kB   |   v0/amp-twitter-0.1.js
 269.3 kB   |    69.66 kB   |   22.16 kB   |   v0/amp-user-notification-0.1.js
 77.27 kB   |    22.28 kB   |    8.81 kB   |   v0/amp-vine-0.1.js
 77.65 kB   |    22.44 kB   |    8.89 kB   |   v0/amp-youtube-0.1.js
 53.41 kB   |    13.03 kB   |    4.93 kB   |   current-min/f.js / current/integration.js

**Comment by erwinmombay** [comment]
@cramforce heres the exact delta compared to 1 commit prior (in master)

https://gist.github.com/erwinmombay/7cba4c4c7ade6c059279/revisions

**Comment by cramforce** [comment]
@erwinmombay Ah, understand why the extension regression happened. I was only looking at the amp.js regression which is also unfortunate, but not caused by this. I can try sending an additional change that would fix this.

**Pull request merged**
