### PR TITLE
📖🐛 Actually render markdown in docs tables

### PR DESCRIPTION
**Pull request by alanorozco**
After #20684, several attribute tables in extension docs are not rendering properly and showing raw markdown instead, at least on Github.

I went ahead and converted every cell content to from markdown to HTML.

### CODE REVIEW

**Comment by pbakaus** [comment]
This seems like a very counter-intuitive solution, if I see it correctly, the commit mostly inserts `<p>` tags? Is that the only way to solve this problem?

@matthiasrohmer: WDYT about this one, would this break us?

**Comment by alanorozco** [comment]
@pbakaus It includes `<p>` tags as a result of the automated markdown parsing. They can be removed if undesired.

The current issue is that markdown inside HTML tags does *not* get parsed, so [documentation, at least on Github](https://github.com/ampproject/amphtml/blob/master/extensions/amp-video/amp-video.md) shows broken link format, etc.

**Comment by pbakaus** [comment]
@alanorozco oh good point. Mhh, yes, I'd say let's definitely kill the `<p>`'s, and otherwise I'm fine with the change. But Curious to hear what @matthiasrohmer thinks, as he's been the main driver here.

**Comment by alanorozco** [comment]
@pbakaus Removed superfluous `<p>` tags.

**Comment by matthiasrohmer** [comment]
Thanks for pinging me! As counterintuitive as this change may seem I fear its required.

Grow (SSG for ampproject.org as well as amp.dev) uses python-markdown internally and as this follows the Markdown spec very closely won't render any markdown inside HTML tags.

The introductionary tables in each reference doc have been using `<a>` for links already before our and now this change. As mentioned to @pbakaus I hadn't had time to do a considerate review on our initial PR that introduced rewritten lists. Therefore we slipped updating the Markdown tags at the same time. So thanks @alanorozco for handling this!

A possible alternative (with other drawbacks though) would possibly be to use [Markdown Extra tables](https://python-markdown.github.io/extensions/tables/) but I find them extremly verbose to write and read.

**Pull request merged**
