### PR TITLE
✨ Add amp-story-subscriptions experiment and turn it to 100%

### PR DESCRIPTION
**Pull request by ychsieh**
This will be pushed only when all the final approvals from all stakeholders are granted.

### CODE REVIEW

**Comment by gmajoulet** [comment]
cc @mszylkowski 

Should we turn on the experiment instead?

**Comment by mszylkowski** [comment]
I'd keep the experiment if we at some point might need to turn it off (eg: adding the component breaks all stories with the component and we have to disable the feature through client-side experiments). So for safety, sounds good to have the experiment.

For reference the experiment can be turned on with `canary-config.json` and `prod-config.json` (you can reference https://github.com/ampproject/amphtml/pull/38285, 0 means it's disabled and 1 means it's enabled).

**Comment by ychsieh** [comment]
Cool thanks for the suggestion! Done.

**Comment by newmuis** [comment]
Let's be sure to coordinate with @raovs before launching this experiment

**Comment by ychsieh** [comment]
Definitely, this and other launch PRs #38179 and #38194 would only be merged once we got all the internal approvals from all the stakeholders.

**Review by mszylkowski — APPROVED** [review]
Approving the changes, feel free to merge when the other conditions are met.

**Review by gmajoulet — APPROVED** [review]
Shouldn't we launch the experiment from the CDN configuration for instant propagation, vs 10+ days with these config changes?

**Comment by ychsieh** [comment]
Good question. I guess the other two PRs would be merged the same time as this one after all approvals are granted, so even though we can make this config in almost instantly, the developers would still need to wait for the other two PRs to be able to play with this new feature?

**Comment by gmajoulet** [comment]
Sounds good! Documentation and validation rollout to production faster. We'll be able to enable the experiment through the CDN configuration a few days after merging validation/doc if we want to save a few days : ))

**Pull request merged**
