### PR TITLE
Tweak validator/nodejs/index_test.js for NodeJs version 6.5 (and above).

### PR DESCRIPTION
**Pull request by powdercloud**
Fix for https://github.com/ampproject/amphtml/issues/4757.

### CODE REVIEW

**Comment by erwinmombay** [comment]
@powdercloud LGTM

**Comment by powdercloud** [comment]
Travis isn't working for the moment, I get: "The repository at ampproject/amphtml was not found."
Will try again later.

**Comment by powdercloud** [comment]
Turns out process.version is a string (this makes sense), so instead of trying to match this version I made a regex that works for both versions. I've tested with v6.4.0 and v6.5.0 using nvm. Crossing my fingers for Travis...

**Comment by erwinmombay** [comment]
@powdercloud thanks!

**Pull request merged**
