### PR TITLE
🐛 Recognize data-amp-bind-src as mandatory_anyof alternative to [src] in amp-list

### LINKED ISSUE #24661: Validation error for mandatory_anyof constraint when using data-amp-bind-src on amp-list
On blog.amp.dev we noticed a validation error starting to happen after https://github.com/ampproject/amp.dev/pull/2934:

> `The tag 'amp-list' is missing a mandatory attribute - pick at least one of ['src','[src]'].`

The markup being introduced included:

```html
<amp-list data-amp-bind-src="query == undefined ? null : '/search/do?q=' + encodeURIComponent(query) + '&amp;locale=en'" binding="no" items="." height="10" layout="fixed-height" data-amp-bind-is-layout-container="query.length" load-more="auto" load-more-bookmark="nextUrl" reset-on-refresh="" single-item="">
	<template type="amp-mustache">...</template>
</amp-list>
```

As of https://github.com/ampproject/amp-wp/pull/2974, the AMP WordPress plugin normalizes the bracketed amp-bind attribute syntax to `data-amp-bind-*`, so the original `[src]` is being converted here to `data-amp-bind-src`. The AMP validator then is flagging this as an error because of this `mandatory_anyof` constraint:

https://github.com/ampproject/amphtml/blob/8c7a61288f841dfaa3781afc1a7bb813e0270212/extensions/amp-list/validator-amp-list.protoascii#L93

A quick fix here would be to just add `data-amp-bind-src` to the list:

```diff
- mandatory_anyof: "['src','[src]']"
+ mandatory_anyof: "['src','[src]','data-amp-bind-src']"
```

However, this seems like a fix for a more fundamental issue where the validator needs to be more aware of the alternate syntax (https://github.com/ampproject/amphtml/issues/11115).

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #24661.

The AMP validator then is flagging use of `data-amp-bind-src` instead of `[src]`, when only the former is being used on `amp-list`. This is marked as an error because of this `mandatory_anyof` constraint:

https://github.com/ampproject/amphtml/blob/8c7a61288f841dfaa3781afc1a7bb813e0270212/extensions/amp-list/validator-amp-list.protoascii#L93

A quick fix here would be to just add `data-amp-bind-src` to the list:

```diff
- mandatory_anyof: "['src','[src]']"
+ mandatory_anyof: "['src','[src]','data-amp-bind-src']"
```

Per @Gregable this is sufficient rather than making the validator aware of the `data-amp-bind-*` alternate attribute syntax.

### CODE REVIEW

**Comment by Gregable** [comment]
It looks like you need to update this one test output file as described here:
https://github.com/ampproject/amphtml/tree/master/validator#usage

**Comment by westonruter** [comment]
Can this be merged?

**Comment by twifkak** [comment]
Yup! Done.

**Comment by westonruter** [comment]
When will this be live? It's been over 2 weeks since merging, so I expected it to be in the validator now.

**Comment by honeybadgerdontcare** [comment]
@westonruter It is live but there is an implementation issue here. I'm looking into why and it may be due to how we special case `data-` attributes.

You can see that it's live by going to validator.amp.dev.

```
  <amp-list width=10 height=10 data-amp-bind-src="https://example.com/foobar"></amp-list>
  The tag 'amp-list' is missing a mandatory attribute - pick at least one of ['src','[src]','data-amp-bind-src']. Learn more.
```

**Comment by honeybadgerdontcare** [comment]
@westonruter a fix has been submitted and should be out within a week.

**Pull request merged**
