### PR TITLE
📖 Update getting-started-e2e.md to use merge instead of rebase

### PR DESCRIPTION
**Pull request by addieachan**
-Changes the Getting Started End to End to use git merge rather than git rebase

### CODE REVIEW

**Comment by bpaduch** [comment]
LGTM. Interesting. I always thought the team preferred `rebase` for cleaner history.

**Comment by cathyxz** [comment]
I think actual history doesn't care since we squash the entire PR into one commit. For purposes of github, I think that if your PR has not yet been reviewed, rebase is cleaner so you don't see a bunch of unrelated commits in the PR. If your PR has been reviewed, rebasing can cause all the review comments to be messed up, so hence merge is preferable.

**Comment by choumx** [comment]
Rebase also can be a foot-gun for the uninitiated.

**Comment by cathyxz** [comment]
(pshhh `rebase -i`!!! yes, more foot-guns for initiation why not)

**Pull request merged**
