### PR TITLE
[amp-story-player] initial isReady event for interacting with player API

### PR DESCRIPTION
**Pull request by Enriqe**
Partial for #27331, #28416

### CODE REVIEW

**Comment by gmajoulet** [comment]
The code LGTM, but let's wait for the full API to be designed (methods, events, and usage examples) before merging to make sure we didn't forget anything

**Comment by Enriqe** [comment]
Sounds good, filed #28416

**Comment by Enriqe** [comment]
Updated after discussions, PTAL

**Comment by Enriqe** [comment]
Friendly ping

**Pull request merged**
