### PR TITLE
✨ amp-ad New integrating ad networks support type: streamrail 

### PR DESCRIPTION
**Pull request by gershman**
Implemented streamrail ad integration

### CODE REVIEW

**Comment by gershman** [comment]
I signed it!

**Comment by gershman** [comment]
@lannka Hi, I see that the Travis check: https://travis-ci.org/ampproject/amphtml/jobs/555752095 failed because of ".then" is forbidden. We take care of this by implementation our on pollyfill so it will support promises.

**Comment by lannka** [comment]
@gershman that sounds good if you have polyfill in your own code, we can make an exemption for your case.

However, to our past experience, it will be better for you to have less logic in AMP repo. I suggest you move code to your own custom JS, and have only code that handles configuration in AMP. That way you have less dependency on our release cycles to update/fix things.

That way, you probably also don't need to use Promise in AMP.

**Comment by gershman** [comment]
@lannka hi, I updated the code so it won't use Promise anymore.
I see that am still getting some tests fails ( tests/e2e), but don't which tests failed or the reason why. Any idea?

**Comment by lannka** [comment]
the e2e test failure was irrelevant

**Pull request merged**
