### PR TITLE
Fix wrong event name amp-carousel-next -> amp-carousel-prev

### PR DESCRIPTION
**Pull request by ruborg**

### CODE REVIEW

**Comment by rsimha-amp** [comment]
That's likely due to the fact that it's a relative link, or due to the page anchor. Try using a full link.

**Comment by mrjoro** [comment]
This is a pretty trivial change; any objection to just merging it?

**Comment by jridgewell** [comment]
It'll fail new builds on master, till fixed.

**Comment by rsimha-amp** [comment]
Test results before and after fixing the problematic link: https://gist.github.com/rsimha-amp/c63b519ab33ecbedd5d0540ba446afcb

**Comment by rsimha-amp** [comment]
@mrjoro, the link checker seems to have found a genuine case of an incorrect link. Fix based on comment above: https://github.com/ampproject/amphtml/pull/10640#pullrequestreview-56144665

**Comment by rsimha-amp** [comment]
Approving based on fix in #10906

**Comment by mrjoro** [comment]
Phew!  It normally doesn't take this much to get a 4 character change in. :)  That's for the fix @ruborg.

**Pull request merged**
