### PR TITLE
Use proper application/json response header instead of arraybuffer.

### LINKED ISSUE #7119: amp-form submission breaks in several browsers, including Edge 13, 14, IE 11, Safari 10
amp-form submission breaks in several browsers.

## How do we reproduce the issue?
Problem noticed on a private website, nevertheless it also exists on other amp-form powered websites, most prominently in the examples provided by the Project itself:
https://ampbyexample.com/components/amp-form/preview/

1. Submit the form in the bottom of the page.
2. Observe an error being thrown in the console:
```
InvalidStateError
v0.js (314,433)
```

## What browsers are affected?
At least Edge 13, 14, IE 11, Safari 10.
Latest Chrome, Firefox, Opera are not affected.

## Which AMP version is affected?
Never tested before, can't say if it's a new issue.
Version 1484769855829

### PR DESCRIPTION
**Pull request by mkhatib**
Fixes #7119

### CODE REVIEW

**Comment by dvoytenko** [comment]
Please fix lint errors.

**Comment by choumx** [comment]
Add a test that headers are properly set for submission?

**Comment by jridgewell** [comment]
Created #7138 and #7139 with what I think is a better solution.

**Comment by mkhatib** [comment]
Closing this for Justin's PRs.

**Comment by choumx** [comment]
@mkhatib @jridgewell It'd be better to get a minimal fix to be cherry-picked into canary. Justin's PRs seem like the better long-term fix, but also has a larger surface area (beyond amp-form) and thus larger risk. How about reopening this PR for cherry-pick and Justin can merge his PR after?

**Pull request merged**
