### PR TITLE
Removing unused experiment config.

### PR DESCRIPTION
**Pull request by riklund**

### CODE REVIEW

**Comment by riklund** [comment]
@lannka @charliereams @keithwrightbos

**Comment by lannka** [comment]
@riklund are you still on this?

**Comment by charliereams** [comment]
Rikard is temporarily locked out of his Github account but will be back to take care of this shortly. Thanks for your patience!

**Comment by riklund** [comment]
Just got my account back, sorry for the delay.
Synced and resolved conflicts.

**Comment by lannka** [comment]
flaky tests. restarting

**Pull request merged**
