### PR TITLE
🚮  Remove examiner.js binary

### PR DESCRIPTION
**Pull request by samouri**
**summary**

🚮  Removes `src/examiner.js` and its associated binary. AFAICT this development mode isn't actually used by anyone.

cc @rcebulko

### CODE REVIEW

**Review by rcebulko — COMMENTED** [review]
This would be awesome 🗑️ ♻️ 🥳

**Comment by kristoferbaxter** [comment]
@samouri Does this need to follow the I2D process?

**Comment by samouri** [comment]
@kristoferbaxter: Good question! We could, but I think that might be overly cautious. This is an undocumented dev-only feature. I'd be incredibly surprised if any non AMP developers ever even found out about this feature let alone used it.

Its purpose was to automatically `console.log` Long Tasks occurring in 3p iframes.

**Comment by rcebulko** [comment]
> @samouri Does this need to follow the I2D process?

I'm unsure about this. AFAICT this isn't documented anywhere and has been broken for quite some time. But could still be useful to I2D for visibility? Just my 2¢

**Comment by kristoferbaxter** [comment]
My take: This is on the border of requiring an I2D given unknown usage. Also, it doesn't significantly slow or hurt the codebase to do so.

I'd lean toward an I2D and following the process.

**Review by rcebulko — APPROVED** [review]
🗑️ ♻️ 🥳

**Review by rsimha — APPROVED** [review]

**Pull request merged**
