### PR TITLE
only run `autoplay` code when `amp-carousel` is in viewport

### PR DESCRIPTION
**Pull request by erwinmombay**

### CODE REVIEW

**Comment by dvoytenko** [comment]
Looks good. Let's see what's up with travis.

**Comment by erwinmombay** [comment]
@dvoytenko just a semi colon, testing on nexus 5 works, i'll wait to merge tomorrow when i get a chance to test on ios

**Comment by dvoytenko** [comment]
LGTM

**Comment by erwinmombay** [comment]
tested on ios. worked fine.

**Pull request merged**
