### PR TITLE
Remove the soon-to-be-deprecated gulp-util

### LINKED ISSUE #12719: Stop using gulp-util in AMP infra
`gulp-util` is deprecated. See https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

### PR DESCRIPTION
**Pull request by rsimha-amp**
This PR does the following:
- Removes the soon-to-be-deprecated `gulp-util` package from AMP's `devDependencies`. 
- Replaces `gulp-util.colors` with `ansi-colors.colors` (https://www.npmjs.com/package/ansi-colors)
- Replaces `gulp-util.log` with `fancy-log.log` (https://www.npmjs.com/package/fancy-log)
- Replaces `gulp-util.PluginError` with `plugin-error.PluginError` (https://www.npmjs.com/package/plugin-error)

See https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5 for a detailed write up on why this is a good idea.

Fixes #12719

### CODE REVIEW

**Comment by rsimha-amp** [comment]
@erwinmombay @choumx Bumping this thread for a review of the non-validator fixes

**Comment by israelfaria** [comment]
Warnings are still being shown with the package published on npm. How to get this fix locally?

**Pull request merged**
