### PR TITLE
✅ Hide the share pill in visual tests, and re-enable tests that were flaky because of this

### LINKED ISSUE #19890: `amp-story` visual tests are flaky due to moving "Share" button
See https://percy.io/ampproject/amphtml/builds/1260087 for example. From what I've noticed, the "Share" button goes back and forth between the two positions across different builds.

Assigning to folks on the stories team to triage.

/cc @danielrozenberg

### PR DESCRIPTION
**Pull request by newmuis**
Filed #20021 to track centralizing these fixes in one place, but this PR should fix the issues to unblock PRs.

Fixes #19890 by hiding this button entirely during tests.

/cc @rsimha

### CODE REVIEW

**Comment by newmuis** [comment]
@gmajoulet can you please also review the Percy diffs?

**Comment by newmuis** [comment]
I think this is also WAI.  Although it looks similar to the diffs we normally see, if you click on the "new" tab, you can see that it's actually just that the entire share pill is gone (which is what this PR intends to do)

**Comment by gmajoulet** [comment]
Oh right, thanks. I got confused because it looked a lot like the previous flakes...

**Comment by rsimha** [comment]
I'm surprised the tests passed for this PR. Pretty sure `.i-amphtml-story-share-pill-label` needs to be removed from `loading_complete_css` for each of these visual tests.

**Comment by gmajoulet** [comment]
You're right it'd be better to remove it. But could it still pass because, even if hidden, the `.i-amphtml-story-share-pill-label` element is still present in the DOM?

**Comment by rsimha** [comment]
`loading_complete_css` is a list of CSS classes that the test runner waits for. If `.i-amphtml-story-share-pill-label` is removed, the test runner will still wait for the other CSS classes in that list.

**Comment by gmajoulet** [comment]
Yes, of course, I meant that the tests still pass because `.i-amphtml-story-share-pill-label` is still present in the DOM.

**Comment by rsimha** [comment]
Aha. Yes. :)

You could add it to the forbidden list if you want to make sure it's not on the page.

**Pull request merged**
