### PR TITLE
Change layout-rect to DOM-rect

### LINKED ISSUE #6131: Change data type LayoutRect to DOMRect
`DOMRect` has two more redundant fields `x` and `y` than `LayoutRect`.
Unifying the data types helps us remove the [data conversions](https://github.com/ampproject/amphtml/blob/master/src/intersection-observer.js#L43).

### PR DESCRIPTION
**Pull request by tiendt**
closes #6131

### CODE REVIEW

**Comment by jridgewell** [comment]
> closes #6361

I don't think that's the right issue number.

**Comment by lannka** [comment]
My original thinking was to use the native data type `DOMRect`, so we can get rid of the custom `LayoutRectDef` or `DOMRectDef`, and together with both data converters `DomRectFromLayoutRect` and `layoutRectFromDomRect`. 

However, @zhouyx pointed out `DOMRect` is not supported in Chrome :-(, so my proposal wasn't feasible.

I saw this PR changed LayoutRectDef to DOMRectDef, which still adds a bit value so that we can get rid of the `DomRectFromLayoutRect` converter. But since we still introduced a custom data type, shall we keep the original name `LayoutRectDef`?

**Comment by zhouyx** [comment]
Honestly I don't like that.. but I can't find a better solution. Or there's no better solution when different browsers are following different standard.... 😭 
I would change our `LayoutRect` to use `ClientRect` and only convert them to `DOMRect` when we output them. But it's basically the same as converting everything to `DOMRect` first.... 

Whatever we do here, we need to name the function and doc them well....

**Comment by tiendt** [comment]
@lannka I'm sorry I misunderstood your proposal :( Should we discuss this further to make a proper change?

**Comment by lannka** [comment]
closing this, in favor of #10028

**Pull request closed without merging**
