### PR TITLE
Updating amp-analytics comScore parameters

### PR DESCRIPTION
**Pull request by acorretti**
* Add pageViewId (cs_pv)
* Add clientId(comScore) (c12)

### CODE REVIEW

**Comment by acorretti** [comment]
Thanks @avimehta, I've updated the tests accordingly.
Do you prefer me to send a new PR or can you squash commits on this one?

**Comment by avimehta** [comment]
@acorretti You don't need to squash the commits but it looks like CLA check is not passing yet. Can you go through the GoogleBot comment and see if you can resolve the CLA issue?

**Comment by acorretti** [comment]
@avimehta I did fulfill the CLA agreement in the name of comScore, Inc. to be signed by my manager Thomas Pottjegort. He signed it earlier this evening, but I don't know how to tell the GoogleBot about that.

**Comment by acorretti** [comment]
Let's see if the CLA bot can find our CLA now.

**Comment by avimehta** [comment]
@acorretti Thanks for the PR!

**Pull request merged**
