### PR TITLE
Fix the position of highlighted text and the scroll animation speed

### PR DESCRIPTION
**Pull request by yunabe**
# Overview
- Place 80px margin above highlighted texts.
- Reset the scroll top before animation to avoid too fast scrolling.
- Change scroll animation height from 1000px to 500px.

### CODE REVIEW

**Comment by yunabe** [comment]
I investigated how easily we can calculate the necessary margin above the highlighted texts to avoid UI conflicts with floating headers. To check the height of floating headers from JavaScript, we need to check the positions of all elements with position=fixed and position=sticky.

Fortunately, we have `fixed-layer.js` and all of fixed elements are supposed to be managed by `FixedLayer`. Thus, we can find all of floating elements with relatively low overhead from documents if `FixedLayer` is working as expected.

But at the same time, I found `FixedLayer` is not working as expected in one of five example sites with floating headers.
Actually, AMP viewer on Google search is not render floating headers on this site (attached screenshots at the end):
https://www.google.com/search?hl=en&q=What%20Does%20It%20Mean%20to%20Hydrolock%20Your%20Motor%20site:carbrain.com

Thus, I would say the dynamic calculate of the value is not very trivial.
In this PR, I would like to keep it hard-coded with `TODO` comment because we can fix the majority of existing UI conflict issue with the simple solution.

android_chrome
ios

**Comment by alanorozco** [comment]
As discussed offline, fine to leave as-is. Thanks for your contribution!

**Comment by yunabe** [comment]
Thank you for the discussion and review, Alan!

**Comment by yunabe** [comment]
Thank you for the discussion and review, Alan!

**Comment by yunabe** [comment]
Thank you for the discussion and review, Alan!

**Pull request merged**
