### PR TITLE
Enable CORS so disable3pfallback works locally as well

### PR DESCRIPTION
**Pull request by aghassemi**

### CODE REVIEW

**Comment by dvoytenko** [comment]
@aghassemi THanks a lot! Could you please also add changes to `app.js` to direct via `ads.localhost`?

**Comment by aghassemi** [comment]
@dvoytenko The change [here](https://github.com/ampproject/amphtml/pull/8753/files#diff-3f91747d1c67c54a132a6720d8ff6120L559) fixes the `ad.localhost` issue.

**Comment by aghassemi** [comment]
(line 509 change)

**Comment by dvoytenko** [comment]
@aghassemi Thanks! Blind...

**Pull request merged**
