### PR TITLE
duplicate docs on `amp-ad` `amp-embed` to extension.

### PR DESCRIPTION
**Pull request by zhouyx**

### CODE REVIEW

**Comment by zhouyx** [comment]
I use `git mv` to move the doc. Can see the move in separate commit. But Files changed view still shows the two doc files in extensions as new added files

**Comment by erwinmombay** [comment]
@zhouyx you mind squashing? maybe that will fix the diff

**Comment by zhouyx** [comment]
😢 did not fix the diff

**Comment by erwinmombay** [comment]
at this point i would suggest to reset hard and do the git mv again, since diff should look like this https://github.com/ampproject/amphtml/pull/3820/files

**Comment by jridgewell** [comment]
@zhouyx, you need to `git rm builtins/amp-ad.md`. Then squash the commits.

**Comment by erwinmombay** [comment]
@zhouyx LGTM

**Comment by zhouyx** [comment]
will open two other pr, one for move docs, one for duplicate doc to ensure git history saved. Close this one.

**Pull request closed without merging**
