### PR TITLE
amp-consent iframe ui 100% height

### LINKED ISSUE #28133: Incorrect height of amp-consent when navigation bar is displayed
## What's the issue?

`amp-consent` is loading an Iframe which takes 100vh when the full screen mode is activated. This 100vh includes the navigation bars on iOS devices and some Android which doesn't let the user scroll down to the bottom of the Iframe. It is a problem for us as we have our action buttons inaccessible. Instead of using 100vh, could you make sure the Iframe takes 100% of the visible height? 

A working solution would be to remove the `height: 100vh` and add 

```
min-height: -webkit-fill-available;
min-height: 100%;
```

It is a blocking issue on our side. Thank you.

## How do we reproduce the issue?

https://sandbox.didomi.io/amp.html

Don't scroll the page, click on Learn More and try to scroll down. You won't be able to reach the bottom buttons. 

## What browsers are affected?

This example is on an iPhone 8 with iOS 13.4 on Safari but you can find this issue on a lot of iOS devices. 

## Which AMP version is affected?

2004240001480

### PR DESCRIPTION
**Pull request by micajuine-ho**
Closes #28133. 

Based on https://developers.google.com/web/updates/2016/12/url-bar-resizing (`This means 100vh will be larger than the visible height when the URL bar is shown...For example, if its height is 100% it will always fill exactly the visible height, whether or not the URL bar is shown.`), we should be using 100% instead of 100vh.

Retains the changes made in #20100
ui_bug2

### CODE REVIEW

**Comment by MaximePlancke** [comment]
@micajuine-ho thank you!

Sure, is this ok? https://jsbin.com/vawekakina/1/edit?html,output

I tried on my end with your changes on Xcode and it seems to fix the issue.

**Comment by micajuine-ho** [comment]
@MaximePlancke 

Tested and it fixes it. Thanks for the jsbin.

**Comment by MaximePlancke** [comment]
Hi @micajuine-ho 

Do you know when this change will be part of the stable release? 

I saw that it was but has been rolled back 23 days ago.

Thank you!

**Comment by micajuine-ho** [comment]
Hi @MaximePlancke this change is in stable. Are you not seeing a fix?

**Comment by MaximePlancke** [comment]
@micajuine-ho 

My bad, I see it now. I got confused with the labels. 
Thank you!

**Pull request merged**
