### PR TITLE
integration: Improve amp-img test reliability

### PR DESCRIPTION
**Pull request by mdmower**
The 'should respect media queries' amp-img integration test fails
intermittently due to a race between setting/getting class
`i-amphtml-hidden-by-media-query` when the window resizes. The race
results because `expect()` is performed immediately after an amp-img
`LOAD_START` event fires without waiting for the other amp-img to fire
its `UNLOAD` event. Remedy this by waiting for both amp-img layout changes
to fire before checking their final classes.

- Add `UNLOAD` event to custom-element test event dispatches
- Fix names of test events `LOAD_START`, `LOAD_END` so that they match the
  corresponding signal names

### CODE REVIEW

**Comment by mdmower** [comment]
@rsimha I'm sort of guessing at how LOAD_START events are fired here. Let me know if the commit message makes no sense at all, or if the commit itself is just. not. right.

**Comment by mdmower** [comment]
@dvoytenko - It's been over four years since your commit (https://github.com/ampproject/amphtml/commit/99b8f718f1711ac9c5d7d7c154a38861640ecb1a), but maybe you can piece together the thought process? I'm guessing the logic was that the newly hidden `amp-img` shouldn't trigger a `LOAD_START` event. Does that sound right?

For some background, a couple of us (user Colm in slack #contributing and me) encounter the following integration test failure:
```
DESCRIBE => Rendering of amp-img
  IT => should respect media queries
    ✗ AssertionError: expected 'i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined i-amphtml-layout' to match /i-amphtml-hidden-by-media-query/
        at http://localhost:9876/home/mdmower/source/amphtml/test/integration/test-amp-img.js:91:46
```
It seems to be resolved by either upping the number of `LOAD_START` events that should be awaited, or by adding a clumsy `setTimeout`. Do you have an opinion on the best approach?

**Comment by colmsnowplow** [comment]
I can confirm that this change resolves the issue I was having with this test failing locally. 👍

**Comment by mdmower** [comment]
The proposed change in https://github.com/ampproject/amphtml/pull/26832/commits/a326a397cd758fa81ed8d01ce928bf4c046f052a is incorrect. The number of `LOAD_START` events only increments once when `amp-img#img3` is hidden and `amp-img#img3_1` is unhidden. The `LOAD_START` event fires at the beginning of `layoutCallback()` but `amp-img#img3` undergoes unlayout, not layout.

The "correct" test would probably be to wait for the number of `LOAD_END` events to increment once and the number of `UNLOAD` events to increment once. I'm not sure that waiting for `LOAD_END` is advised, though (could `LOAD_END` events from other `amp-img`s be mistaken for the event we're waiting for?). So, let's start by simply waiting for both the number of `LOAD_START` events to increment once and the number of `UNLOAD` events to increment once before reading the classes on each element. New commit incoming.

**Pull request merged**
