### PR TITLE
✨ The Ozone Project: Add RTC endpoint to callout-vendors.js

### PR DESCRIPTION
**Pull request by greg-silvermine**
This PR adds The Ozone Project RTC callout URL in callout-vendors.js.

_NOTE:
Our endpoint will be responding with content only to requests from the domains that are whitelisted in our prebid-server setup._

@mrjoro The Ozone Project agreed to the corporate CLA AFAIK but I am not sure what's the status of that at the moment.

@keithwrightbos Could you please review and let me know if anything else is required.

Thanks,
Greg

### CODE REVIEW

**Comment by greg-silvermine** [comment]
@googlebot I signed it!

**Comment by AskRupert-DM** [comment]
@keithwrightbos - are you able to approve this PR and merge it for us please ... if there's any details required to push this through please let us know.

**Comment by AskRupert-DM** [comment]
@rcebulko - do you think you can help us with this error - https://github.com/ampproject/amphtml/pull/26039/checks?check_run_id=398670458 - we've rebased from the master branch but still getting errors.

**Comment by rcebulko** [comment]
> @rcebulko - do you think you can help us with this error - https://github.com/ampproject/amphtml/pull/26039/checks?check_run_id=398670458 - we've rebased from the master branch but still getting errors.

Sauce has been a bit flaky of late. I've just started looking into it, hopefully can get it resolved soon :+1:

**Comment by AskRupert-DM** [comment]
hey @keithwrightbos - all the checks are now passing - would you please be able to approve/merge this PR in or provide a timeframe ?

**Comment by AskRupert-DM** [comment]
Thanks @lannka !

**Pull request merged**
