### PR TITLE
getMode DCE

### PR DESCRIPTION
**Pull request by jridgewell**
It’d be great if we could move `getModeObject` into `mode.js`, but then
I’d have to learn Java to update the DCE code. @erwinmombay?

### CODE REVIEW

**Comment by erwinmombay** [comment]
@jridgewell if we moved getModeObj to mode.js what else would we need to do?
what was the module that was getting implicitly imported even though it wasnt used again?

**Comment by jridgewell** [comment]
> if we moved getModeObj to mode.js what else would we need to do?

We need to update `AmpPass.java` to DCE `getMode().localDev`, not just `$mode.getMode().localDev` (we wouldn't import `getMode`, it's defined in the `mode.js` module where we'd move `getModeObject`).

> what was the module that was getting implicitly imported even though it wasnt used again?

That's separate, and I'm still digging into how to best fix it.

**Comment by erwinmombay** [comment]
@jridgewell thanks for explaining, ill make the change.

**Comment by erwinmombay** [comment]
@jridgewell since this is a prod bug, should we try and get this in ASAP then I can make the change?

**Comment by jridgewell** [comment]
Yah, get around to it whenever. Maybe a `fixit` label? But that part's not important.

**Comment by erwinmombay** [comment]
created https://github.com/ampproject/amphtml/issues/4225, working on it, but thought it was more important to get this in ASAP

**Pull request merged**
