### PR TITLE
:sparkles: Add tracdelight AMP ad integration

### PR DESCRIPTION
**Pull request by thekorn**
The pull request contains implementation for the tracdelight ad-widgets for AMP Ads.
Reference to our closed PR is https://github.com/ampproject/amphtml/pull/13956

### CODE REVIEW

**Comment by torch2424** [comment]
@bhassan6621

Thank you for the contribution! 😄

Please see the intructions given by the CLA bot above if you would like to move forward with this PR 👍

Thank you!

**Comment by daniel-kuhn-burda** [comment]
Dear reviewer: 
* cla has been signed
* Travis-ci seems not to failing with this error: `13 Mar 16:12:16 - error querying from https://saucelabs.com/rest/v1/amphtml/tunnels, error was: {"error": "Too many active user tunnels: 5 >= 5"}. HTTP status: 400 Bad Request`

**Comment by daniel-kuhn-burda** [comment]
OK by me

**Comment by daniel-kuhn-burda** [comment]
@torch2424 can you help us with the CLA message from googleBot (see above)?
All agreements have been signed however we still seem to miss some agreements.
thank you!

**Comment by thekorn** [comment]
superseeded by https://github.com/ampproject/amphtml/pull/23124

**Pull request closed without merging**
