### PR TITLE
Powr player component

### PR DESCRIPTION
**Pull request by chadladensack**
This is an `amp-powr-player` component to implement a Powr player as outlined in #18960.

### CODE REVIEW

**Comment by chadladensack** [comment]
I signed it!

**Comment by chadladensack** [comment]
@alanorozco we signed a CLA for my company email address that was linked to @chadladensack right after the PR was created.

Regarding the failed Travis CI build; seems its related to a timeout when trying to find a build environment. I've created a Sauce Labs account and was able to execute the build locally. How can we trigger this again to get the check to pass?

**Comment by alanorozco** [comment]
@chadladensack There shouldn't be an issue as long as the actual commit was made with the same email address. Would you mind reopening this PR?

**Comment by chadladensack** [comment]
Good catch, the commit was made using an older email. I've amended the commit to use the correct company email and reopened the PR as #19043. The signed CLA was picked up successfully. Thanks for the help, @alanorozco. It's greatly appreciated.

**Pull request closed without merging**
