### PR TITLE
Rename describes.js functions

### PR DESCRIPTION
**Pull request by choumx**
Partial for #10478.

- `describes.fakeWin` -> `describes.unit`
- `describes.realWin` -> `describes.functional`
- Add "tl;dr" section to docs

### CODE REVIEW

**Comment by lannka** [comment]
@choumx after yesterday's discussion, my understanding of fakeWin is that it also provides the whole AMP runtime. I think we should just create a separate clean `.unit`

**Comment by dvoytenko** [comment]
I'm ok with whichever you decide, but for context:

1. Correct, `fakeWin` install runtimes when `amp: true` is provided.
2. Ironically, the reason I created `fakeWin` was b/c I wanted to use `realWin`, but couldn't override either `window.top` (to emulate non-iframe case) or `window.location` to emulate x-origin case or simply get away from `about:srcdoc`. It's possible that I simply didn't try hard enough to accomplish these goals on `realWin`.

So, at this time distinction between `fakeWin` and `realWin` is somewhat superficial. If anything, it's more like:
 - `unit` = `fakeWin/realWin({amp: false})`
 - `functional` = `fakeWin/realWin({amp: true})`

**Comment by lannka** [comment]
@choumx i guess it will be a lot of work to tell if runtime is needed in all those tests. A safe step is to rename all the tests to `functional`:

```
describes.functional('test test', { fakeWin: true, amp: true|false }, () => ...
```

Then we can probably turn those tests that does not provide `{amp: true}` into unit:
```
describes.unit( ...
```

Is that something actionable?

**Comment by lannka** [comment]
For better organizing my PR reviews, I added label "working in progress" to this PR. Please remove the tag once it's ready for review again.

**Comment by lannka** [comment]
given so many conflicts, let me close it for now. you can always reopen :-)

**Pull request closed without merging**
