### PR TITLE
Move validator protoascii out of versioned into extension

### PR DESCRIPTION
**Pull request by honeybadgerdontcare**
With new versions of extensions we'll need to make some changes to how tags are validated so that "things" can be different for different versions. To prepare, this PR pulls out the validator protoascii files from their versioned directories and places them in the root of their extension.

@Gregable @powdercloud 

@ampproject/cloudflare let us know if you have any concerns around this, though I imagine you're using the generated validator.protoascii and not individual protoasciis.

### CODE REVIEW

**Comment by honeybadgerdontcare** [comment]
@rsimha-amp dead link checker not realizing these links are in this pr

**Comment by irtefa** [comment]
We should already be doing this.

**Comment by rsimha-amp** [comment]
@honeybadgerdontcare, good catch. While we do skip links to files that were Added (A) in a PR, but I neglected to include files that were Copied (C), Renamed (R), or had their type changed (T) (as is the case in this PR).

This can be fixed by updating the `diff-filter` args in [isLinkToFileAddedInPR](https://github.com/ampproject/amphtml/blob/master/build-system/tasks/check-links.js#L107) from `--diff-filter=A` to `--diff-filter=ACRT`.

If you'd like you could make the change in this PR and see if it fixes things. If not, I'm happy to send you a separate PR.

**Comment by cferic** [comment]
> @ampproject/cloudflare let us know if you have any concerns around this, though I imagine you're using the generated validator.protoascii and not individual protoasciis.

@honeybadgerdontcare Following this change, is there a recommendation or best practice regarding the number of protoascii files per extension in the extension's root directory?

**Comment by honeybadgerdontcare** [comment]
@cferic for now there should only be one in the root of the extension and the intention is that will cover all extension versions. This is precursor to all extension versions being in that file which is work that will come at a future date.

**Comment by cferic** [comment]
@honeybadgerdontcare Thanks for the quick response. No concern with the change.

**Pull request merged**
