### PR TITLE
Remove the whole statement when stripping asserts/logs when possible.

### PR DESCRIPTION
**Pull request by cramforce**

### CODE REVIEW

**Comment by cramforce** [comment]
0.18KB codesize win :)

**Comment by jridgewell** [comment]
Is this changing `devAssert(expression)` to an empty expression? If so, it's liable to break something if the expression is impure.

**Comment by cramforce** [comment]
@jridgewell YOLO?

**Comment by jridgewell** [comment]
Risky... https://github.com/ampproject/amphtml/issues/14683

**Pull request merged**
