### PR TITLE
🐛 Allow `PreactBaseElement` child def wildcard to match text nodes

### PR DESCRIPTION
**Pull request by rcebulko**
Since `TextNode` doesn't support methods like `match`, `getAttribute`, `setAttribute`, etc. they get dropped when parsing child definitions for components extending `PreactBaseElement`. This PR:
- Adds a text node to the `test-base-element-mapping` tests
- Fixes `BaseElement#matchChild` to support text nodes (should it also support comments?)
- Modifies `createSlot` helper to accept a `Node` instead of an `Element` (ie. don't explode on `setAttribute`)
The resulting text node is wrapped in a `<Slot />` and provided in the `children` array.

### CODE REVIEW

**Review by jridgewell — CHANGES_REQUESTED** [review]
Text nodes can only go into the default slot, so the only thing that makes sense is when they're in the `passthrough`/`passthroughNonEmpty` mode.

**Comment by rcebulko** [comment]
> Text nodes can only go into the default slot, so the only thing that makes sense is when they're in the `passthrough`/`passthroughNonEmpty` mode.

Is it possible to specify both children and passthrough? I think I remember a doc somewhere saying they were mutually exclusive. In the case of amp-truncate-text, I'm trying to extract the three `[slot=...]` buttons from children, and then have the remainder go into the default slot, which should be alongside other slots for those buttons.

**Comment by jridgewell** [comment]
`passthrough` and `children` are mutually exclusive, and there's not currently a way to use the default (unnamed) slot if using `children`. It'd probably simplify this PR a bit if we added default support.

**Comment by samouri** [comment]
> Text nodes can only go into the default slot, so the only thing that makes sense is when they're in the passthrough/passthroughNonEmpty mode.

Is that per custom element spec or an AMP restriction?

**Comment by jridgewell** [comment]
It's the CE spec. You can only assign a node to a slot if by setting `slot="foo"` attribute on the node. Since only Elements have attributes, only Elements can be slotted into a non-default slot. Everything else goes into the default.

**Comment by rcebulko** [comment]
> `passthrough` and `children` are mutually exclusive, and there's not currently a way to use the default (unnamed) slot if using `children`. It'd probably simplify this PR a bit if we added default support.

Would this take the form of something like a `default: true` key in the child def with the `*` selector? Happy to take a pass at this once I can get myself on the right track.

**Pull request closed without merging**
