### PR TITLE
Add missing type annotation

### PR DESCRIPTION
**Pull request by zhangsu**
@choumx

### CODE REVIEW

**Comment by torch2424** [comment]
Triaging to @chenshay 😄 Feel free to re-assign. Would approve myself, but don't want to assume the type enforcement.

**Comment by mrjoro** [comment]
@ericfs can you take a look at this one :)

**Comment by zhangsu** [comment]
Need some help merging this as I don't have permission 😂

**Comment by zhangsu** [comment]
Friendly ping owner @chenshay :)

**Comment by zhangsu** [comment]
Bump for owner approval @chenshay 

It looks like you are the only owner for this...

**Pull request merged**
