### PR TITLE
Updating the amp-story owners file.

### PR DESCRIPTION
**Pull request by gmajoulet**
> Prefixing a user or team with # will @ mention that owner in a comment on any PR which touches those files/directories

### CODE REVIEW

**Comment by newmuis** [comment]
@gmajoulet WDYT about (at least for now):

```
- "#gmajoulet"
- "#newmuis"
- @ampproject/wg-stories
```

(assuming that's not going to automatically ping everyone in that group)

**Comment by rcebulko** [comment]
> @gmajoulet WDYT about (at least for now):
> 
> ```
> - "#gmajoulet"
> - "#newmuis"
> - @ampproject/wg-stories
> ```
> 
> (assuming that's not going to automatically ping everyone in that group)

@newmuis That will not auto-notify the group (unless you added `"#ampproject/wg-stories"`.
Nit: You do not need (read: should not include) the `@` prefix for user or team names

**Comment by gmajoulet** [comment]
PTAL
cc @Enriqe

**Comment by Enriqe** [comment]
Is this case sensitive? Just curious since my GH username is "Enriqe" and not "enriqe"

**Comment by rcebulko** [comment]
@enrique It is currently, but I think it should not be, as that will hide bugs. See https://github.com/ampproject/amp-github-apps/pull/467

**Pull request merged**
