### PR TITLE
Ad example page: add comment on expected error

### PR DESCRIPTION
**Pull request by zhouyx**

### CODE REVIEW

**Comment by zhouyx** [comment]
@pyxarez @CrazySquirrel Could you take a look at the implementation on your side? 
What we found is that the `ampContext` was incorrectly bind to a htmlElement. 

image

**Comment by CrazySquirrel** [comment]
@zhouyx ok, I wrote to current developers, I think something broke in the latest releases

**Comment by zhouyx** [comment]
Thank you @CrazySquirrel for the quick response. Please keep us update on the fix, thanks

**Comment by pyxarez** [comment]
@zhouyx Hi! I have opened PR in order to fix the discussed issue:) Now it should work as expected from our library side

**Comment by zhouyx** [comment]
Thank you @CrazySquirrel @pyxarez for the quick fix. I've merged #18687

**Pull request merged**
