### PR TITLE
♿Add alert role to toast for screen reader support

### LINKED ISSUE #24805: Toast is not read out through screen readers
When toasts are shown (e.g. after copying a link in to the clipboard in a story), the text is not read out through screen readers.

### PR DESCRIPTION
**Pull request by jackbsteinberg**
Adds the `alert` role to toasts so screen readers assertively announce the content when the toast is displayed.
Resolves #24805

### CODE REVIEW

**Comment by jackbsteinberg** [comment]
I've got a few questions I want to answer before I'd be satisfied calling this ready to merge.

First, how should I test this? I ran the `test-amp-story` test suite and nothing seemed to break but I'm not sure if there's an accessibility testing pipeline I should be looking at.

Second, I chose `status` because it announces the content to screen readers politely (i.e. waits for whatever content is currently being read to finish before announcing its content), since I assume the toasts are low priority for the user to get to in this context. If that's not the case let me know and I should change the role to `alert`.

Context: [Toast roles](https://github.com/jackbsteinberg/std-toast/issues/29#issuecomment-505276014), [`status` role](https://www.w3.org/TR/wai-aria-1.2/#status), [`alert` role](https://www.w3.org/TR/wai-aria-1.2/#alert)

**Comment by newmuis** [comment]
I am by no means an expert, but I think we might want to consider `alert` here?  It's quite possible that there's a lot of content in the bookend (the optional last screen of the story used for sharing and related articles), so if all you want is the link, it might be inconvenient to wait for that all to be read out.

The code change LGTM, just wondering about the role itself.

**Comment by jackbsteinberg** [comment]
> I am by no means an expert, but I think we might want to consider `alert` here? It's quite possible that there's a lot of content in the bookend (the optional last screen of the story used for sharing and related articles), so if all you want is the link, it might be inconvenient to wait for that all to be read out.
> 
> The code change LGTM, just wondering about the role itself.

The guidelines for this pretty much allow you to choose which makes more sense in the context. If the toast content is the content we want to call attention to immediately, then `alert` likely makes more sense.

**Comment by jackbsteinberg** [comment]
Update: I tried this with a the macOS VoiceOver screen reader and it seems to be working well

**Pull request merged**
