### PR TITLE
Added policy compliance type attributes

### PR DESCRIPTION
**Pull request by ColombiaOnline**

### CODE REVIEW

**Comment by ColombiaOnline** [comment]
@lannka Please help me how to resolve "ampprojects/owners-check" issues. I have no idea about this. please help

**Comment by ColombiaOnline** [comment]
Hi @lannka ,
Please Review and let me know if any change is required.

**Comment by ColombiaOnline** [comment]
Please let us know what changes are required

**Review by lannka — COMMENTED** [review]
please revert the owner file change. the other changes looks good.

**Comment by ColombiaOnline** [comment]
Hi @lannka ,
Your suggestions have implemented. Please let us know any others changes are required.

**Review by lannka — APPROVED** [review]

**Comment by lannka** [comment]
Seems there is one more thing to fix: https://app.circleci.com/pipelines/github/ampproject/amphtml/6095/workflows/cf7da3a4-6d99-49cd-8842-0a1e4f581b77/jobs/86136

```
ERROR: pull/33379 is missing the latest CircleCI config revision 998fd11b80e420ba18c90f3b4c6a3b3c2f7b37e5.


This can be fixed in three ways:


1. Click the "Update branch" button on GitHub and follow instructions.
   ⤷ It can be found towards the bottom of the PR, after the list of checks.


2. Pull the latest commits from master and re-push the PR branch.
   ⤷ Follow these steps:

      git checkout master
      git pull
      git checkout <PR branch>
      git merge master
      git push origin


3. Rebase on master and re-push the PR branch.
   ⤷ Follow these steps:

      git checkout master
      git pull
      git checkout <PR branch>
      git rebase master
      git push origin --force
```

**Comment by ColombiaOnline** [comment]
Hi  @lannka ,
I am not able to update button as per your suggestion as i am trying to follow point 2 and 3, but i am getting below message.
"Already up to date"

image

**Comment by lannka** [comment]
it's OK to have 'Already up to date'. Then you can just switch to your PR branch and do 
git merge master

**Comment by lannka** [comment]
close for inactivity. feel free to reopen

**Pull request closed without merging**
