### PR TITLE
amp-script: Support setState/getState in worker

### LINKED ISSUE #22410: amp-script: Support AMP.setState in JS
It seems `amp-script` does not support AMP's any of [actions and events](https://amp.dev/documentation/guides-and-tutorials/learn/amp-actions-and-events)—for example, it's not possible to listen for a `select` event from `amp-selector`, to fire the `show` action on arbitrary elements, or to use `AMP.setState(…)` from within a script.

/cc @choumx @kristoferbaxter

### PR DESCRIPTION
**Pull request by choumx**
Fixes #22410.

Also upgrade worker-dom to `0.19.0`. Documentation to follow.

### CODE REVIEW

**Comment by choumx** [comment]
Friendly ping. :)

**Comment by westonruter** [comment]
@choumx is there any event that triggers in the worker context when AMP page state is changed?

**Comment by choumx** [comment]
Currently only polling. Adding an event is the next step.

**Comment by nragan34** [comment]
Most of these amp-script examples do not validate .....

Look at the picture for this example

Capture

The script part is what doesn't validate, is something wrong with amp-script?

**Pull request merged**
