### PR TITLE
Turn on 'ad-loader-v2'

### PR DESCRIPTION
**Pull request by zhouyx**
cc @jasti

### CODE REVIEW

**Comment by zhouyx** [comment]
Also font size change.

**Comment by lannka** [comment]
I hope in future we can avoid this kind of testing in production code. 
If all we want is for us to see the new style on real pages, we can just push local changes to a Heroku instance without submitting it to production code.

It can cut down eng overhead (flags, clean up, etc) and reduce risks of breaking production.

 @jasti @spacedino

**Comment by jasti** [comment]
@lannka The key was to get the two versions as experiments so other people (outside of AMP core) can opine on the two options. 
Happy to proceed however you feel is best.

**Comment by lannka** [comment]
@jasti Heroku build is also public accessible. Unless you're talking about testing with real traffic is necessary. However I don't see the need for such a pure UI comparison, as we're not really collecting any data from real traffic.

**Pull request merged**
