### PR TITLE
fixes squished carousel images

### PR DESCRIPTION
**Pull request by argyleink**

### CODE REVIEW

**Comment by dvoytenko** [comment]
Hi Adam! Thanks a lot for the pull request. Let me review the change and test on devices. I think object-fit is not supported on some of the devices we use. But I do like this idea. In the meantime, do you have a good example where the contents were squished?

**Comment by argyleink** [comment]
Contents were squished when I had my browser at about 720px wide. The css provided will only fix it for browser that support object-fit, correct. It's a harmless solution.

**Comment by dvoytenko** [comment]
Yes, but is there any chance you could share a link?

**Comment by argyleink** [comment]
link to my fork with the solution in place? it's all local right now, but i'm about to take some pics and post them. do you not need the pics?

**Comment by dvoytenko** [comment]
No, I just a link to a document where this happens. I'd just like to be able to reproduce and if needed include in tests.

**Comment by argyleink** [comment]
i saw it in the everything.amp.html file

before:
screen shot 2015-10-08 at 4 21 49 pm

after:
screen shot 2015-10-08 at 4 22 04 pm

**Comment by erwinmombay** [comment]
so i wonder if this should be user optional and they can do:

```css
amp-img img {
  object-fit: cover;
}
```

**Comment by argyleink** [comment]
i like making class modifiers out of `background-size` and `object-fit`, so anyone can change the display behavior between cover and contain.

**Comment by dvoytenko** [comment]
Sorry for the delay. I looked through the change itself. The underlying problem is fixed here: https://github.com/ampproject/amphtml/pull/765

But we would rather avoid `object-fit` at this time. The kind of error that we had in samples is too easy to make and to hard to discover if we had `object-fit`. In other words, it helps, but it also obfuscates the original problem. So we'd rather leave it up to the content publishers themselves.

**Comment by dvoytenko** [comment]
As always, though, thanks a lot for the suggestion!

**Pull request closed without merging**
