### PR TITLE
Revert "Disable prerendering mode for SwG"

### LINKED ISSUE #23102: Restore safe-prerendering mode in SwG
Blocked on #23101.

To resolve, simply rollback #23103 once #23101 is fixed.

### PR DESCRIPTION
**Pull request by jpettitt**
Reverts ampproject/amphtml#23103 fixes #23102 now that #23101 fix is merged.

### CODE REVIEW

**Comment by jpettitt** [comment]
@dvoytenko don't we also need to add a prerenderSafe flag to the fetch in `amp-subscriptions-google` to tell the system it's safe?

**Comment by dvoytenko** [comment]
/to @ChrisAntaki. But I believe Chris has already "reverted" this PR forward.

**Comment by ChrisAntaki** [comment]
Yep, #23269 enables prerendering mode for SwG

**Comment by ChrisAntaki** [comment]
Is #23269 ready for a merge?

**Comment by dvoytenko** [comment]
Yes. I didn't realize it wasn't merged... @ChrisAntaki you should probably apply for committer status.

**Comment by ChrisAntaki** [comment]
Right on, I'll apply today

**Comment by jpettitt** [comment]
OK I'll close this

**Pull request closed without merging**
