### PR TITLE
add advance bidder support for openx amp ad

### PR DESCRIPTION
**Pull request by rjvelicaria**
#7159 
* use advance bidder implementation when both auid and dfpslot are defined

### CODE REVIEW

**Comment by rjvelicaria** [comment]
Company Name: OpenX Technologies, Inc.

**Comment by lannka** [comment]
@rjvelicaria can you fix the type checks? you will want to add the new name to ads.extern.js

To pass the CLA robot check, can you try mention "CLA" together with your exact company name?

**Comment by rjvelicaria** [comment]
Okay, I'll take a look at ads.extern.js

CLA OpenX Technologies, Inc.

**Comment by rjvelicaria** [comment]
@CLA OpenX Technologies, Inc.

Trying to trigger it again since it didn't report back.

**Comment by lannka** [comment]
@erwinmombay seems we're getting trouble with CLA, could you force merge the PR?

**Pull request merged**
