### PR TITLE
[amp-story] Fixing flaky test (vertical rendering)

### LINKED ISSUE #33758: Fix flaky visual diff tests
The following visual diff tests are flaky and have been disabled #33759:
* `amp-story: bot rendering`
* `amp-story-player AMP version`

### PR DESCRIPTION
**Pull request by Enriqe**
Closes  #33758

### CODE REVIEW

**Comment by Enriqe** [comment]
@gmajoulet I couldn't figure out a way to remove the controls inside the video causing the flakiness (they are inside a shadow root (user agent) - which is [not accessible via JS](https://stackoverflow.com/a/38736220) because it's not an `open` shadow DOM).

I didn't delete the `<amp-video>` element directly from the HTML as it tests some functionality coming from the captions and displaying them in the vertical view.

**Comment by gmajoulet** [comment]
The overall direction sounds good, do you think we could render a black CSS rectangle on top of the controls instead? That might an easier fix (no JS) and test more things

**Review by gmajoulet — APPROVED** [review]

**Comment by gmajoulet** [comment]
cc @danielrozenberg who tried to fix it in the past

**Comment by danielrozenberg** [comment]
lol love this hack :D

**Comment by Enriqe** [comment]
62ebee9d44a620406c1beb33d0434a96

**Pull request merged**
