### PR TITLE
✨ Implement rtc-config dotandads for amp-tag

### PR DESCRIPTION
**Pull request by dotandads**

### CODE REVIEW

**Comment by dotandads** [comment]
@googlebot I fixed it

**Comment by scaverio** [comment]
@googlebot I fixed it

**Comment by caroqliu** [comment]
Removing myself from reviewers--OWNERS check doesn't include where I may be useful and the others have better context.

**Comment by dotandads** [comment]
@googlebot I fixed it

**Comment by dotandads** [comment]
NOP

**Pull request closed without merging**
