### PR TITLE
🖍 Allow @page CSS at-rule

### PR DESCRIPTION
**Pull request by westonruter**
When testing the WordPress AMP plugin with the [Genesis Sample Theme](https://github.com/copyblogger/genesis-sample/), the validator was raising an error regrading an [`@page` at-rule appearing in the CSS](https://github.com/copyblogger/genesis-sample/blob/5a51a24c45d16a82b44d5f71c86be7b350d7cc7a/style.css#L1722-L1724):

```css
@media print {
	/* ... */
	@page {
		margin: 2cm 0.5cm;
	}
	/* ... */
}
```

See MDN docs on `@page` rule: https://developer.mozilla.org/en-US/docs/Web/CSS/@page

There doesn't seem to be any reason for why `@page` should be excluded in AMP, other than it was perhaps not included since it is not a commonly-used rule. So this PR allows the rule in the AMP and AMP4EMAIL formats; I didn't include AMP4ADS as it didn't seem to make sense, but maybe it does.

### CODE REVIEW

**Comment by aghassemi** [comment]
Thanks @westonruter 
/to @Gregable for review.

**Comment by Gregable** [comment]
@westonruter Thanks for the contribution. We looked over the at-rules we found in a large sample of documents when making the initial list, so I suspect that this is just an oversight. I'd like @honeybadgerdontcare , who implemented the list to take a look but I see no problem.

**Comment by Gregable** [comment]
I was confused. This was something else. Yes, the at-rule list was defined here:
https://www.ampproject.org/docs/fundamentals/spec#@-rules

I'm not sure who would be best to make this call. Probably @cramforce

**Comment by westonruter** [comment]
> Would be great if you could also update https://www.ampproject.org/docs/fundamentals/spec#@-rules

Done in e472360.

**Comment by ericlindley-g** [comment]
Checking in — @cramforce , @Gregable , does anything else need to be done here in order to merge this PR? Do you have a sense of the timeline until this would become available?

/cc @amedina

**Comment by westonruter** [comment]
Anything else needed here?

**Comment by Gregable** [comment]
Looks good to me.

**Pull request merged**
