### PR TITLE
Content.ad: Improved reliability and security

### PR DESCRIPTION
**Pull request by jlucero-contentad**
Migrated API to a more robust environment.

### CODE REVIEW

**Comment by zhouyx** [comment]
@jlucero-contentad The code looks good. However with your new change in, I am not able to see your ad example in our test page. I get `Error: timeout waiting for ad response​​​`. Could you take a look maybe?

**Comment by jlucero-contentad** [comment]
@zhouyx I'm not able to reproduce that error on my local. Did you get the error for all of the Content.ad ads or just the first one? As mentioned in this merge request, we migrated API to new servers, so it could be an intermittent error.

**Comment by zhouyx** [comment]
@jlucero-contentad it was with all content.ad ads. You're right, able to see them today. LGTM

**Pull request merged**
