### PR TITLE
Add select wg-stories members as /extension OWNERS

### PR DESCRIPTION
**Pull request by newmuis**
Adds @gmajoulet and @newmuis as OWNERS of `/extension`

### CODE REVIEW

**Comment by newmuis** [comment]
Ping @kristoferbaxter (no rush though)

**Comment by newmuis** [comment]
Friendly ping @kristoferbaxter

**Review by kristoferbaxter — APPROVED** [review]

**Comment by gmajoulet** [comment]
@ampproject/wg-infra how can we restart the cross-browser tests?

**Comment by kristoferbaxter** [comment]
@gmajoulet I restarted the test by merging in latest master.

**Comment by estherkim** [comment]
Another option is to use the re-run button in the Checks tab
image

**Pull request merged**
