### PR TITLE
📖 Formats amp-story attributes section as a table.

### PR DESCRIPTION
**Pull request by cpauwels**
- Changes the format of the amp-story attributes section to a table
- Updates the internal anchors referring to the attributes

### CODE REVIEW

**Comment by cpauwels** [comment]
@googlebot I signed it!

**Comment by cpauwels** [comment]
Closes #23648, cc @CrystalOnScript

**Comment by CrystalOnScript** [comment]
Resolves issue [#23648](https://github.com/ampproject/amphtml/issues/23648)

**Comment by estherkim** [comment]
Resolves https://github.com/ampproject/amphtml/issues/23648

**Pull request merged**
