### PR TITLE
Setting ChromeOld to latest-10 instead of 37

### PR DESCRIPTION
**Pull request by aghassemi**
37 seems arbitrary and too old. latest-10 seems more reasonable.

### CODE REVIEW

**Comment by erwinmombay** [comment]
/to @cramforce if he's ok with this

**Comment by cramforce** [comment]
We kind want to keep this as a known old browser we support. Is there an actual problem with it?

**Comment by dvoytenko** [comment]
I think that's the S4 or S5 browser, right?

**Comment by cramforce** [comment]
37 is kinda Chrome. It came from being the version that was preinstalled on Travis before they started updating it regularly.

**Comment by aghassemi** [comment]
well, Master build is failing because of

**Comment by jridgewell** [comment]
The SW core won't run on Chrome 37, which is perfectly fine since SW aren't required. We do polyfill `Fetch` when it's not supported, so we do support 37.

I'll send in a PR to guard the SW core tests.

**Comment by aghassemi** [comment]
N/A per https://github.com/ampproject/amphtml/pull/5470

**Pull request closed without merging**
