### PR TITLE
Make sidebar the highest z-index possible

### LINKED ISSUE #6705: Production bug - amp-sidebar z-index CSS conflicts with fixed layer code.
/extensions/amp-sidebar/0.1/amp-sidebar.css contains

`amp-sidebar { z-index: 9999!important }`

However the fixed layer migration code sets element level CSS on the `amp-sidebar` to 

`style="pointer-events: initial; z-index: 20003; top: calc(54px);"`

Which fails due to the `!important` in the sidebar css.

### PR DESCRIPTION
**Pull request by camelburrito**
Fixes #6705

### CODE REVIEW

**Comment by aghassemi** [comment]
These conflict with lightbox-viewer. I believe they need to be lower than lightbox-viewer's z-index in case the sidebar opens something like an image in the lightbox-viewer. Please see and update `Z_INDEX.md` as well.

**Comment by camelburrito** [comment]
@aghassemi - sidebar should have the highest zindex on the page. when we open a lbv from a sidebar we need to make sure it closes. isn't the z-index file autogenerated?

**Comment by aghassemi** [comment]
@camelburrito created https://github.com/ampproject/amphtml/issues/6712. Z_INDEX.md is not auto-generated AFAIK.

**Comment by camelburrito** [comment]
@aghassemi i think @erwinmombay  has a script that generates it

**Comment by jpettitt** [comment]
Not fixed: see https://www.google.com/amp/cdn.relaymedia.com/amp/www.civilbeat.org/2016/12/ige-hawaiis-food-sustainability-a-priority-in-his-budget-plan/#amph=1 and https://www.google.com/amp/amp.gospelherald.com/articles/68178/20161122/christian-forces-retake-ancient-monastery-from-isis-vow-to-rebuild-we-are-stronger-than-they-imaged.htm#amph=1 for examples of how the sidebar is obscured by the fixed header when in a viewer.  We really need to get the !important removed from the sidebar z-index so we can make this choice ourselves.

**Pull request merged**
