### PR TITLE
🏗Add `gulp browse` task to open browser to URL

### PR DESCRIPTION
**Pull request by rcebulko**
`gulp browse --url <URL>` uses the platforms default browser (or, in the case of Windows, Chrome) to open a specified page. To be used for upcoming changes, including automatically opening a coverage UI after running e2e tests with the `--coverage` and `--browse` flags. Can also add `gulp serve --browse` for the same effect.
  
image

### CODE REVIEW

**Comment by rcebulko** [comment]
@ampproject/build-cop @ampproject/wg-viewers 
Looks like a failing/flaking test in `AmpViewerMessagingIntegration` is blocking a decent number of PRs at the moment

image

**Comment by rcebulko** [comment]
@ampproject/build-cop There also appears to be a failing e2e test: 
image

fails [here](https://travis-ci.org/github/ampproject/amphtml/jobs/723855935) and [this other place]

**Review by kristoferbaxter — APPROVED** [review]
Looks good! Thanks.

**Review by rsimha — COMMENTED** [review]
Reviewing this PR post-merge because I just saw it. Instead of implementing a separate task for opening a browser (and taking on the maintenance burden), why not just use a package like [`open`](https://www.npmjs.com/package/open) (formerly called `opn`)?

We already use it in our testing code to launch the code coverage report in a platform specific browser window when commands like `gulp unit --coverage` or `gulp integration --coverage` are executed during local development.

https://github.com/ampproject/amphtml/blob/b5dea36e0b8bd012585d50839766a084f99a3685/build-system/tasks/runtime-test/helpers.js#L157-L159

**Comment by rcebulko** [comment]
@rsimha That looks great, I'll follow up with that change

**Pull request merged**
