### PR TITLE
Mangle Enums in Terser

### PR DESCRIPTION
**Pull request by jridgewell**

### CODE REVIEW

**Comment by samouri** [comment]
Can you measure the size diff for esbuild output?

**Comment by jridgewell** [comment]
Need to wait for the other PRs to land before I can estimate.

**Review by alanorozco — COMMENTED** [review]
Does this make `build-system/babel-plugins/babel-plugin-mangle-object-values` redundant?

**Comment by jridgewell** [comment]
No, this mangles the keys, not the values.

**Pull request closed without merging**
