### PR TITLE
Change client id substitution to set a fallback cookie if not present.

### PR DESCRIPTION
**Pull request by cramforce**

### CODE REVIEW

**Comment by cramforce** [comment]
CC @btownsend @avimehta @rudygalfi

**Comment by avimehta** [comment]
@cramforce How does this work in relation to #1628? If a person specifies a `data-consent-notification-id` but no `user-consent-id` in client id, will the client id be written? If a person does not specify `data-consent-notification-id` but adds a `user-consent-id`, will the cookie be written? Will analytics tag fire in either of the cases? 

Finally, How are vendors supposed to specify `user-consent-id`? They probably don't have access to the publisher page.

**Comment by cramforce** [comment]
@avimehta I addressed your question in the other thread. CLIENT_ID supports passing in a consent id, but for `amp-analytics` and `amp-ad` (where the users don't touch the CLIENT_ID themselves) there is a special attribute on the tag to guard it based on consent.

**Comment by cramforce** [comment]
@dvoytenko PTAL

**Comment by dvoytenko** [comment]
LGTM

**Pull request merged**
