### PR TITLE
Support dynatrace managed environments

### PR DESCRIPTION
**Pull request by kamtschatka**
Updated the dynatrace amp analytics support to support dynatrace managed environments as well.

The tenantID can not be added as part of the domain for dynatrace managed environments, so it will be part of the URL itself.
This pull request keeps in mind that there are currently customers using amp with dynatrace saas, so we have to be backwards compatible

Renamed the branch to pull from. 
Original PullRequest: https://github.com/ampproject/amphtml/pull/11566

### CODE REVIEW

**Comment by aghassemi** [comment]
@zhouyx added to https://github.com/ampproject/amphtml/projects/16

**Comment by kamtschatka** [comment]
Is there an ETA for the merge of this pull request?

**Comment by zhouyx** [comment]
@kamtschatka Sorry for the delay. PR looks good. Merged.

**Comment by kamtschatka** [comment]
Thanks!

**Pull request merged**
