### PR TITLE
Fix amp-experiment.md formatting to get exported to amp-docs.

### LINKED ISSUE #4350: amp-experiment md file doesn't convert into docs format well
Take a look at https://www.ampproject.org/docs/reference/extended/amp-experiment.html.

There's a couple of issues I spotted:
- The table describing configuration squeezes the initial two columns. (photo below)
- There are validation issues, but the underlying problem is that it seems like the [sourcecode] block being used isn't properly getting escaped, which would cause a real amp-experiment to get run on the page.
- Also, the extended component listing page doesn't have amp-experiment: https://www.ampproject.org/docs/reference/extended.html. I think an entry should live under Analytics.

cc @pbakaus 

screen shot 2016-08-03 at 12 41 25 pm

### PR DESCRIPTION
**Pull request by lannka**
Fixes #4350

### CODE REVIEW

**Comment by pbakaus** [comment]
LGTM!

**Comment by lannka** [comment]
@pbakaus Thanks! Just one thing that I want to double check with you:

At my local, I can't get the code block styling right as on ampproject.org. Not just amp-experiment, but also other extensions. So I assume probably it's missing some kind of plugins at my local, at it will be right once build on ampproject.org?

**Comment by pbakaus** [comment]
@lannka not actually sure what's going on, code block styling works perfectly fine for me on pages like https://ampproject.org/docs/reference/amp-video.html (on a local build too)

**Comment by lannka** [comment]
@pbakaus I'll go ahead and merge this to see if it's just my local problem.

**Pull request merged**
