### PR TITLE
Allow more than one sidebar on the page

### PR DESCRIPTION
**Pull request by aghassemi**
Closes https://github.com/ampproject/amphtml/issues/6104

### CODE REVIEW

**Comment by honeybadgerdontcare** [comment]
Please update the corresponding html file's comment about more than one sidebar: https://github.com/ampproject/amphtml/blob/master/extensions/amp-sidebar/0.1/test/validator-amp-sidebar.html#L49

I remember seeing a discussion about allowing only one left sidebar and one right sidebar, but not two left sidebars or two right sidebars. Is that no longer the case?

**Comment by camelburrito** [comment]
The reason we did not allow this was we did not want to open 2 sidebars and give no means of closing them (unless the author adds a close button on the sidebar). 

We would also need this feature?
https://github.com/ampproject/amphtml/issues/3320

**Comment by aghassemi** [comment]
@camelburrito see comments on #6104 as I have mentioned I like to do this part without waiting for #3320

**Comment by aghassemi** [comment]
@honeybadgerdontcare maybe although considering with `amp-bind` now devs can have complicated logic, I can see use-case of having multiple sidebars on the same-side and using bind to open the one that makes sense given the state of the app.

**Comment by honeybadgerdontcare** [comment]
@aghassemi yeah that makes sense, thanks for clarifying. It would be useful to have this if it was exercised in the right fashion.

**Comment by camelburrito** [comment]
@aghassemi i am okay with this as long as you promise #3320 will make it in soon :)

**Comment by aghassemi** [comment]
@camelburrito I am not yet fully convinced we need https://github.com/ampproject/amphtml/issues/3320, let's discuss on that issue.

**Pull request merged**
