### PR TITLE
 ✨ Allow `scaling=relative` on `amp-story-page`

### PR DESCRIPTION
**Pull request by alanorozco**

### CODE REVIEW

**Comment by alanorozco** [comment]
@honeybadgerdontcare done.

I also moved the rule to `amp-story-page`, minor mistake 🌚

**Comment by alanorozco** [comment]
@newmuis SGTM. If so, then I'll just leave the PR open.

**Comment by aghassemi** [comment]
Thanks for the Pull Request. Since this PR has been stale for a while, I am closing it. Please feel free to reopen as needed.

**Comment by alanorozco** [comment]
@aghassemi Thanks!

@newmuis can re-open or ping me if follow-up is needed.

**Pull request closed without merging**
