### PR TITLE
Horizontal scrolling when embedded as an IFrame

### LINKED ISSUE #1488: Consider disabling horizontal scrolling by default
Most pages that have it are buggy. Could consider supporting explicit opt in to horizontal scrolling.

### PR DESCRIPTION
**Pull request by dvoytenko**
/cc @ericfs @cramforce 

Closes #1488.

### CODE REVIEW

**Comment by ericfs** [comment]
LGTM

**Comment by ericfs** [comment]
LGTM

**Comment by dvoytenko** [comment]
@cramforce Done. PTAL.

**Comment by cramforce** [comment]
LGTM

**Pull request merged**
