### PR TITLE
Document AMP's release schedule.

### PR DESCRIPTION
**Pull request by cramforce**
@Meggin Should this also go somewhere into our main docs?

### CODE REVIEW

**Comment by Meggin** [comment]
Yes, combined with release notes. Basically, a releases section. Sound good?

**Comment by cramforce** [comment]
@Meggin A separate page would be nice but might be a bit overkill. It would need to be generated from the GitHub API.

**Comment by Meggin** [comment]
We could just pull it in from amphtml, no? I could create a template that
pulls in the release schedule content and the release note output into one
page. It should be easy using the existing script in /docs.

But you are right-- it's not worth it if it eats up time. There's so much
to do.

**Comment by cramforce** [comment]
@Meggin The info is available via the Github API. It is not just a markdown file.

**Comment by rudygalfi** [comment]
LGTM

**Comment by erwinmombay** [comment]
if we need it i can probably add it to the code that pulls in the docs repo. shouldnt be too hard since it will just be a gulp task very similar to the `changelog` task we have (i know the api pretty well now lol)

**Pull request merged**
