### PR TITLE
🐛 Fix TrafficStars integration

### PR DESCRIPTION
**Pull request by ishaba**
Fix ads vendor TrafficStars integration script

### CODE REVIEW

**Comment by ishaba** [comment]
Someone with permissions please rerun ⛓️ End-to-End Tests

**Review by powerivq — APPROVED** [review]

**Comment by ishaba** [comment]
@powerivq can be merged now? or ci test needs to be restarted?

**Comment by powerivq** [comment]
@ishaba Can you rebase against latest main branch? It would have fixed the problem./

**Comment by ishaba** [comment]
> @ishaba Can you rebase against latest main branch? It would have fixed the problem./

Done.

**Pull request merged**
