### PR TITLE
Push amp-scrollable-carousel to 100%

### PR DESCRIPTION
**Pull request by sriramkrish85**
CC @ericlindley-g

### CODE REVIEW

**Comment by dvoytenko** [comment]
LGTM pending approval from @ericlindley-g

**Comment by ericlindley-g** [comment]
LGTM

**Comment by sriramkrish85** [comment]
@dvoytenko can you approve using the tool :)

**Comment by muxin** [comment]
Shall we remove the old `AmpSlides` and `AmpCarousel` afterwards?

**Comment by sriramkrish85** [comment]
> Shall we remove the old AmpSlides and AmpCarousel afterwards?

`AmpSlides is already gone`. , `Amp Carousel` should stay till this is 100% on prod and you can delete it.

**Pull request merged**
