### PR TITLE
🐛amp-video-iframe: add additional iframe sandbox attributes allowing video-ad clickthrough

### PR DESCRIPTION
**Pull request by klipstein**
Video ads (Pre-/Mid-/Postrolls) that get rendered inside `amp-video-iframe` currently cannot escape the given iframe sandbox. So that video-ad clickthrough targets can be opened by the embedded video-player the following iframe sandbox attributes were added:

- allow-popups-to-escape-sandbox
- allow-top-navigation-by-user-activation

### CODE REVIEW

**Comment by klipstein** [comment]
I signed it!

**Comment by klipstein** [comment]
@alanorozco do I need to adjust something in this pull so that it can be merged?

**Comment by alanorozco** [comment]
@klipstein Could you merge from the latest `upstream master` and push to this PR?

**Comment by klipstein** [comment]
@alanorozco I've merged latest master. Thanks for your help.

**Comment by alanorozco** [comment]
@klipstein Merged, thanks! Expect your changes to be in the next dev channel release.

**Comment by cramforce** [comment]
Oh hei @klipstein, good to see you on the internetz!

**Comment by klipstein** [comment]
@cramforce ohai! Glad to see you too and that you started this nice little project :)

**Pull request merged**
