### PR TITLE
AMP Validator feature to support disallowed ancestor tags.

### PR DESCRIPTION
**Pull request by Gregable**
First usage is to disallow nested template tags.

### CODE REVIEW

**Comment by Gregable** [comment]
@dvoytenko

**Comment by dvoytenko** [comment]
LGTM. Assuming the red travis is a flake. Perhaps repush to validate?

**Comment by Gregable** [comment]
How does one repush. I tried `git push --set-upstream origin <branchname>`, but travis still seems oblivious.

**Comment by dvoytenko** [comment]
Try git push -f?

**Comment by Gregable** [comment]
That didn't work, but logging into the travis site gave me a button to press.

**Comment by Gregable** [comment]
Travis is green, merging.

**Pull request merged**
