### PR TITLE
🐛  Fix devtools getmode parseQueryString

### PR DESCRIPTION
**Pull request by mszylkowski**
Between #34372 and #34399 the method name `parseQueryString` was changed (underscore removed) and the checks didn't catch the error in time. Removing the underscore to fix the call to `parseQueryString`

### CODE REVIEW

**Review by processprocess — APPROVED** [review]

**Comment by processprocess** [comment]
@rsimha It's interesting that checks didn't catch this 🤔 we want to point it out just in case.
We were able to submit `parseQueryString_` even though it was undefined.

**Comment by mszylkowski** [comment]
Closing in favor of #34420

**Comment by rcebulko** [comment]
> @rsimha It's interesting that checks didn't catch this  we want to point it out just in case.
> We were able to submit `parseQueryString_` even though it was undefined.

@processprocess it looks like they both passed CI and were merged, but since neither touched the same lines it didn't trigger a merge conflict or force an update.

**Comment by rsimha** [comment]
> it looks like they both passed CI and were merged, but since neither touched the same lines it didn't trigger a merge conflict or force an update.

The crux of the issue is what Ryan said here. There's no good way to prevent this other than making sure that two PRs that could affect each other are tested and merged one after the other, and that PRs with older CI runs are rebased before they are merged.

In the case of #34372 and #34399, all the rules were followed, CI was green, and the PRs were merged a short time after running tests. Unfortunately, there was no merge conflict to flag a potential problem. The next line of defense is `main` branch builds, which worked as designed.

**Pull request closed without merging**
