### PR TITLE
Validator Roll-Up

### PR DESCRIPTION
**Pull request by Gregable**
Changes affecting PASS/FAIL:
 * Implement URL Validation for URLs in CSS stylesheets.
 * Correctly parse URLs in `srcset` which contain commas.
 * Allow a large number of new `<link>` and `<a>` `rel=` values
 * Support `ftp` in `<a href` and `cite` attrs. #2441
 * Support font-awesome fonts. #2413
 * Allow `type="text/css"` for `<style amp-custom>`
 * Allow anchor target to be set to default value `_self`.
 * Allow more attributes for a few tags: `<ol>, <ul>, <li>, <video>, <audio>, <button>, <link>`.
 * Allow protocol relative font requests.
 * Allow `align` attribute on `<p>, <div>, <td>, <th>, <h1-6>, <blockquote>`
 * Allow `border` attribute on `<table>, ,  <amp-img>`
 * Allow `width`, `height`, `bgcolor` attributes on `<tr>, <td>, <th>`
 * Allow `cite` attribute in `<blockquote>`, `<q>` tag. Github #2469
 * Require `cite` attribute to be a valid URL, and apply `<a href` protocol
requirements.
 * Allow more html5 attributes on `<a>` tags: `download`, `media`, `type`. Allow target attr value to match case-insensitively.
 * Allow the `base` tag with `target` attribute, but do not yet allow an `href` attribute. Adding comments suggesting that `href` is coming.
 * Allow `dir` attr in `<bdo>` tags.
 * Allow `ismap`, `longdesc` attrs in `` tags (still only allowed inside a `<noscript>` tag.
 * Allow `hreflang`, `media`, `sizes`, `target`, `type`, `charset=utf-8` attrs in `<link>` tags.
 * Allow `chrome=1` for `<meta http-equiv=X-UA-Compatible>` tags.
 * Allow `media` attr on `<source>` tags.
 * Relax rules for meta tags:
    * Any combination of `name`, `content`, `property`, and `itemprop` attrs allowed as long as `name` doesn't have one of the 3 special values`.
    * Allow `http-equiv` attribute values of `pics-label`, `imagetoolbar`, `content-language`, and `resource-type`.
    * Allow `http-equiv` attribute values of `content-style-type` and `content-script-type` with the default values.
  * Allow `<track>` tags inside `<audio>` and `<video>` tags.
  * Allow more non-standard attributes on appropriate `table`, `tr`, `td`, `th` tags: `align`, `border`, `bgcolor`, `cellpadding`, `cellspacing`, `height`, `width`, `valign`.
 * Allow html5 standard `sortable` attribute on `table`.
 * Allow type="text/javascript" on all javascript `<script>` tags (not the json
ones).
 * Allow `<amp-reach-player>`

Changes improving error messages:

 * Allow dispatch keys to include mandatory parents which gives better error messages for `<script>` tags primarily.
 * Tweak error categories for style attributes, `on*` attributes, and `<link rel=stylesheet>.

Also includes some minor refactorings.

### CODE REVIEW

**Comment by Gregable** [comment]
@powdercloud @honeybadgerdontcare for review / googlebot

**Comment by honeybadgerdontcare** [comment]
@googlebot confirmed

**Comment by powdercloud** [comment]
@googlebot confirmed

**Comment by Gregable** [comment]
@erwinmombay for release notes.

**Comment by erwinmombay** [comment]
thanks @Gregable , release notes from the PR body should be pulled in next release.

**Pull request merged**
