### PR TITLE
🐛 Add subid support to TrafficStars Ad

### PR DESCRIPTION
**Pull request by setdream**
Add data attributes(subid) support for analytics reasons
/cc @ishaba

### CODE REVIEW

**Review by calebcordry — APPROVED** [review]
Thanks for maintaining this extension!

**Review by powerivq — APPROVED** [review]

**Comment by powerivq** [comment]
@setdream Do you not want this PR be merged, or should I merge this?

**Comment by setdream** [comment]
@powerivq Please give some time, we should make some preparations on our side)

**Comment by setdream** [comment]
@powerivq Please merge)

**Comment by setdream** [comment]
@calebcordry @powerivq could you merge please?

**Pull request merged**
