### PR TITLE
Identify call origin as an AMP page

### PR DESCRIPTION
**Pull request by nicolastruchi**
This will allow us to monitor AMP initiated calls internally

update to Intent to implement: #2296

### CODE REVIEW

**Comment by lannka** [comment]
There's a lint error. Please run `gulp lint`.
Otherwise LGTM

**Comment by lannka** [comment]
@nicolastruchi Could you also fix the example in `ads.amp.html`? It's currently broken.

**Comment by maurelio1234** [comment]
Hi @lannka, 

I am covered by the CLAs now. I have also committed a fix for the lint problem.
What is the problem with `ads.amp.html` ? It looks fine for me? (and it seems to work when I run it).

Thanks in advance,

Marcos ALMEIDA

**Comment by maurelio1234** [comment]
Hi,

Any news about that?
Do I need to do anything to you can "verify my consent"?
Any information on the problem with` ads.amp.html` ?

Thanks in advance,

Marcos

**Comment by lannka** [comment]
@maurelio1234 I synced to your branch, and cannot get the ad loaded for Criteo, see screenshot below. You can run `gulp` to start a local server to debug. Please refer to [DEVELOPING.md](https://github.com/ampproject/amphtml/blob/master/DEVELOPING.md) for more info.

Meanwhile, I also noticed your branch is quite out of date. Please try to merge with the head.

screenshot from 2016-08-10 09 24 51

**Comment by maurelio1234** [comment]
Hi,

I sync'ed my branch with upstream and I get an ad for criteo. Could you tell me on which branch/commit you put yourself so that you don't get an Ad?

Thanks in advance,

capture d ecran 2016-08-11 a 10 15 22

**Comment by maurelio1234** [comment]
By the way, your bot still tells me that "CLAs are signed, but unable to verify author consent". Do I need to do something in particular so that it "verifies my consent"?

**Comment by jridgewell** [comment]
> By the way, your bot still tells me that "CLAs are signed, but unable to verify author consent".

We need both of you to say "I signed it!"

**Comment by maurelio1234** [comment]
I signed it.

**Comment by nicolastruchi** [comment]
I signed it!

**Comment by jridgewell** [comment]
Ping @erwinmombay, who can merge regardless of CLA verification.

**Comment by maurelio1234** [comment]
Hi,

Any news on that?

Regards,

**Pull request merged**
