### PR TITLE
Ramp "intersect-resources" to 100% (third try)

### LINKED ISSUE #25428: Resource scheduling with IntersectionObserver
Investigate replacing AMP's scroll-event-based resource scheduling system with IntersectionObserver.

Related: https://github.com/w3c/IntersectionObserver/issues/372

New flagged feature in Chromium that enables `rootMargin` on implicit root in x-origin iframes: https://github.com/w3c/IntersectionObserver/issues/372#issuecomment-543938684

### PR DESCRIPTION
**Pull request by choumx**
Fixes #25428. 1% ads regression appears fixed in canary after #29581.

### CODE REVIEW

**Comment by kristoferbaxter** [comment]
Restarted End to End tests, approving.

**Comment by choumx** [comment]
The protocol adapters e2e test failure is actually legitimate. The intersection callback happens before `amp-script.css` is loaded, so it detects the `amp-script` element as having `height: 0`. This means `layoutCallback()` is never called.

I think the core issue is that `amp-script.css` technically causes content jumping by resizing the element.

**Comment by samouri** [comment]
> The protocol adapters e2e test failure is actually legitimate. The intersection callback happens before amp-script.css is loaded, so it detects the amp-script element as having height: 0. This means layoutCallback() is never called.

There's a larger pattern that this exposed regarding a new requirement w/ `intersect-resources`. Before IO, measures were always done after build. With IO, measures will all likely happen pre-build, and therefore we need elements to have correct width/height even before build (for those that don't explicitly mutate).

**Comment by choumx** [comment]
Good catch. This is actually a coincidental invariant since "size change after build" can cause CLS.

**Comment by samouri** [comment]
Different bug but also related to IO. This one about using an outdated premeasure and incorrectly skipping layout:

https://github.com/ampproject/amphtml/pull/30188

**Pull request merged**
