### PR TITLE
🐛 [amp-story-audio-sticker] make grid layer mandatory ancestor, not parent

### PR DESCRIPTION
**Pull request by swissspidy**
Extracting my question at https://github.com/ampproject/amphtml/pull/39184#issuecomment-1880878366 into a PR for more visibility.

Just like `<amp-story-shopping-tag>`, I don't see why this element shouldn't be allowed to have some wrapper elements. This change would make implementation in Google's WordPress Web Stories plugin more straightforward, where we use absolute positioning for elements.

### CODE REVIEW

**Comment by erwinmombay** [comment]
@banaag could you help review tihs one

**Review by ychsieh — APPROVED** [review]
Agree that we should allow wrappers in between. Thanks for the change Pascal!

**Comment by swissspidy** [comment]
@erwinmombay @ychsieh can we merge this?

**Review by erwinmombay — APPROVED** [review]

**Pull request merged**
