### PR TITLE
Extension nexxtv-player update

### PR DESCRIPTION
**Pull request by neko-fire**
See issue here #8264
This PR replaces #12031 due some issues with Travis.

addtional updates:
* renaming of some attributes
* added streaming-filter attribute

### CODE REVIEW

**Comment by aghassemi** [comment]
Thanks @neko-fire, this one got flagged by Travis as well. I will contact their support to see what's going on.

**Comment by aghassemi** [comment]
@neko-fire Heard back from Travis, can you please login https://totravis-ci.org  with your GitHub account? They said they are blocking the PR because no one from your org has ever logged into Travis (seems to be a new thing).

Please let me know after you do that so I can tell them to check again.

Thanks and sorry for the trouble.

**Comment by aghassemi** [comment]
Friendly ping.

**Comment by neko-fire** [comment]
hi @aghassemi ,
sorry for delay. I've connected my github account with travis-ci.org

**Comment by aghassemi** [comment]
Thanks @neko-fire, I emailed Travis support to remove the flag.

**Comment by aghassemi** [comment]
@neko-fire, Travis is good now. Just needs a rebase then we can merge.

**Comment by aghassemi** [comment]
@neko-fire, merged. Thanks!

**Comment by Gregable** [comment]
The validator changes in here are now live.

**Pull request merged**
