### PR TITLE
changelog(tools): add components breakdown for changelog

### PR DESCRIPTION
**Pull request by erwinmombay**
also make canary as `default` and read --branch flag

### CODE REVIEW

**Comment by erwinmombay** [comment]
latest changelog https://github.com/ampproject/amphtml/releases/tag/1457112743399 was generated with this code although the validation section had to be manually edited. (dont have the "read validation commits" code in yet)

**Comment by Meggin** [comment]
just need to update validation docs based on validator section in
breakdown-- right?

**Comment by erwinmombay** [comment]
@Meggin could you link me to that? (the exact validation page)

**Comment by Meggin** [comment]
sure. https://www.ampproject.org/docs/reference/validation_errors.html

**Comment by erwinmombay** [comment]
@Meggin a right, this is probably a good trigger for "when" we would re-build that page. but that wouldn't have enough info i think. Lets meet this week so we can discuss :+1:

**Comment by Meggin** [comment]
sgtm.

**Comment by erwinmombay** [comment]
@cramforce PTAL

**Comment by cramforce** [comment]
Cool.
LGTM

**Pull request merged**
