### PR TITLE
FlexOneELEPHANT amp-ad support

### PR DESCRIPTION
**Pull request by taisuke-oomi**
Could you merge 'FlexOneELEPHANT amp-ad support' into ampproject/amphtml master branch?

We have a Google Corporate CLA.
Our CLA: D.A.Consortium Inc.

Looking forward to hearing from your response!

### CODE REVIEW

**Comment by lannka** [comment]
we recently added new API: [renderStart](https://github.com/ampproject/amphtml/blob/master/ads/README.md#methods-available-to-the-ad)
Could you take a look and implement the APIs (renderStart + noContentAvailable)?
It helps AMP to provide a better ad loading experience.
Let me know if you have any questions regarding that.

**Comment by taisuke-oomi** [comment]
Thank you for your reply.
I will consider the implementation of renderStart, but first of all I want to merge like this.

**Comment by lannka** [comment]
@taisuke-oomi sure you can decide to implement render-start later, but did you try to get your example work locally? See [DEVELOPING.md](https://github.com/ampproject/amphtml/blob/master/DEVELOPING.md) for details, basically you run `gulp` server locally and check `http://localhost:8000/examples/ads.amp.max.html`.
And also, please fix the Travis build errors. 
I'd also suggest you sync to the head of master before you make further changes. Just FYI, #4886 is a good example how to implement the APIs.

**Comment by lannka** [comment]
screenshot from 2016-09-20 10 50 40

@taisuke-oomi seems not working still. Please ping this thread when you're ready for next round of review.

**Comment by taisuke-oomi** [comment]
@lannka Yes, I am aware of the error. I will modify the f1e_amp.min.js. And if through the test of Travis, I will notify you.

**Comment by taisuke-oomi** [comment]
@lannka f1e_amp.min.js fixed, but Travis did not pass. Where is the cause of error?

**Comment by lannka** [comment]
screenshot from 2016-09-21 12 32 19

Still seeing other errors.

**Comment by taisuke-oomi** [comment]
@lannka thank you for sharing the error. I am corresponding to this issue.

**Comment by taisuke-oomi** [comment]
@lannka I passed the test. Please check again.

**Pull request merged**
