### PR TITLE
More smart quote fixes

### PR DESCRIPTION
**Pull request by edendramis**

### CODE REVIEW

**Comment by jridgewell** [comment]
More in:

```
builtins/amp-ad.md
builtins/amp-img.md
builtins/amp-pixel.md
builtins/amp-video.md
CONTRIBUTING.md
docs/include_features.md
extensions/amp-anim/amp-anim.md
extensions/amp-audio/amp-audio.md
extensions/amp-carousel/amp-carousel.md
extensions/amp-fit-text/amp-fit-text.md
extensions/amp-iframe/amp-iframe.md
extensions/amp-image-lightbox/amp-image-lightbox.md
extensions/amp-instagram/amp-instagram.md
extensions/amp-lightbox/amp-lightbox.md
extensions/amp-slides/amp-slides.md
extensions/amp-twitter/amp-twitter.md
extensions/amp-youtube/amp-youtube.md
extensions/README.md
spec/amp-html-components.md
spec/amp-html-format.md
```

**Comment by erwinmombay** [comment]
@jridgewell still in progress?

**Comment by edendramis** [comment]
Not all of the smart quotes are in code. From a typography perspective I think smart quotes are good to have for non-code, but it may be easier to just get rid of them all.

**Comment by edendramis** [comment]
Alright, I fixed the rest of them.

**Comment by erwinmombay** [comment]
awesome. LGTM

**Pull request merged**
