### PR TITLE
🐛 Hide AMP Story audio icon if there is no audio

### LINKED ISSUE #31592: Don't display audio UI in AMP story pages with video if there is no audio
## What's the issue?

When creating an AMP story page without sound, seeing the Mute/Unmute icons felt rather confusing to me. I see this was already improved via #15562, but I'm not sure why they would need to be displayed at all.

More importantly though, I would like to raise the issue that when a video without sound is included in an AMP story page, the animated audio meter icon is still displayed on the bottom of the screen, incorrectly suggesting that there would be audio.

I've noticed this after creating my first story, and it was also brought up by @tomayac on [Twitter e.g. here](https://twitter.com/tomayac/status/1337325440202117121).

## How do we reproduce the issue?

Embed a video without sound in an AMP story to see the audio meters icon showing up despite there being no sound.

Example: page 4 of [this story](https://felix-arntz.me/web-stories/walking-the-san-francisco-crosstown-trail/)

## What browsers are affected?

This affects all browsers.

## Which AMP version is affected?

I assume it affects all AMP versions since stories were added as a feature, but I may be incorrect.

### PR DESCRIPTION
**Pull request by nickFalcone**
AMP Stories shows the mute/unmute audio icon on pages where there is no audio. See the [AMP Stories hello world example](https://amp.dev/documentation/examples/introduction/stories_in_amp/preview/?format=websites). Note the mute/unmute icon appears in two cases:

- Pages with static content (hello world pages 1, 3, 4)
- Pages with video that have no audio (hello world page 2)

To address pages with static content, I relied on checking for the presence of `i-amphtml-current-page-has-audio` attribute before displaying the mute/unmute icon.

To prevent the mute/unmute icon from displaying for `<amp-video>` with no audio, the [noaudio](https://amp.dev/documentation/components/amp-video/#noaudio) attribute should be added.

I would appreciate any advice on adding tests for this change, or impacts I may not be aware of. Thanks! 

Resolves #31592

cc/ @Enriqe & @newmuis

### CODE REVIEW

**Comment by gmajoulet** [comment]
Thank you for sending a PR!

Lmk if this is correct, what you're proposing is:
- Today, all pages have the mute/unmute icon if at least a page has some audio, eg: if only page 3 has audio, page 1 has an audio icon
- With your change, only pages that have audio have the mute/unmute icon, eg: if only page 3 has audio, page 1 has NO audio icon

The two main concerns I have in mind are:
1. Feature discovery, if the icon is not present on the first page, I'm afraid users might not pay attention when it appears on page navigation (+ it might shift all the other icons)
2. You can't mute back a Story if the current page has no audio

cc @newmuis @raovs for more input

**Comment by nickFalcone** [comment]
Hi @gmajoulet - that's an excellent summary of my proposal. Thanks for adding your thoughts.

1. Great point.
2. >You can't mute back a Story if the current page has no audio

Can you help me understand the second concern? Are you thinking about a scenario where the user wants to go back to a page with audio, and reenable mute after unmuting? I see where having a "global" mute could be useful (eg. a user is entering a quiet space and wants to ensure audio is muted on _every_ page in the story).

**Comment by newmuis** [comment]
Glad to see you contributing @nickFalcone!

Definitely want to cc @hongcatlover here since this is a change to the default user experience.

**Comment by nickFalcone** [comment]
Hi @hongcatlover, @newmuis, & @gmajoulet - I wanted to follow up on this PR. If there is a different approach the group wants to take regarding #31592, I'd be happy to help! 😄

**Comment by mszylkowski** [comment]
We've ended up implementing sth like this for the UI redesign that rolled out earlier this year, so I'm closing this PR as it's no longer relevant.

**Pull request closed without merging**
