### PR TITLE
Revert "🏗🚀 Mangle values of specific enum objects (#36935)"

### PR DESCRIPTION
**Pull request by alanorozco**
This reverts commit 5f279739b26f082ddb15d207b61e9c574888d8e1.

### CODE REVIEW

**Review by erwinmombay — APPROVED** [review]

**Review by samouri — APPROVED** [review]

**Comment by samouri** [comment]
Do we know why it passed visdiff tests initially?

**Comment by alanorozco** [comment]
@samouri 🤷

**Review by kristoferbaxter — APPROVED** [review]

**Comment by gmajoulet** [comment]
What are the details for this one? What was breaking, and do we have any plans to bring it back?

**Comment by alanorozco** [comment]
@gmajoulet Visual tests were failing. They seem fine now, restoring on #37480

**Pull request merged**
