### PR TITLE
✨ Allow using amp-install-serviceworker in amp-story

### PR DESCRIPTION
**Pull request by newmuis**
Partial for #18624.

### CODE REVIEW

**Comment by ithinkihaveacat** [comment]
The build errors seem unrelated—?

**Comment by mrjoro** [comment]
This was approved but not merged; was that intentional?

**Comment by mrjoro** [comment]
@newmuis ping :)

**Comment by newmuis** [comment]
The build errors here are not unrelated; I also need to fix the validation test output

**Comment by mrjoro** [comment]
@newmuis is this PR still active?

**Comment by nainar** [comment]
Closing this PR as inactive. Please reopen if that isn't the case (preferably as a new PR).

**Pull request closed without merging**
