### PR TITLE
✨Advanced Snowplow tracker (Closes 24006)

### PR DESCRIPTION
**Pull request by max-tgam**
Adds following functionality:
- Improve visitor tracking
- Improve visit tracking
- Add tracking for Self Describing Events
- Add tracking for Page Pings
- Add  tracking for Link Click (via Self Describing Events) 
- Add Custom Contexts

**Additional Notes:**

1. This PR did not made Page View or Page Ping tracking automatic as it would go in contrary to Snowplow design. The PR shows how to track various interactions but leaves it to people implementing tracking on a specific site to decide what and how to track.
2. Visitor and visit tracking assumes there are cookies with IDs. If cookies are missing then tracking falls back to `AMP client ID` for Visitor ID, `generated UUID` for visit ID and `0` for visit number (both `visit ID` and `visit number` should be adjusted once https://github.com/ampproject/amphtml/issues/18931 is released)
3. Link tracking takes advantage of[`data-vars-`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vars.md) AMP feature to be functional
4. Custom Contexts field is currently required to be present (this is because AMP does not omit empty `extraUrlParams`)  
5. Unit test look for `?` for appending  additional parameters from `extraUrlParams` even though the actual request uses `&` for this this (this could be a unit testing suit bug?)

### CODE REVIEW

**Comment by zhouyx** [comment]
cc @lannka, I remember you worked with a vendor upgrade before? Is there a generic approach that we can follow. 

@max-tgam Can I ask you more about the version upgrade. Can the upgrade be done with the existing  config? Also what's your deprecation plan on the previous version. Thank you!

**Comment by colmsnowplow** [comment]
Hi @zhouyx, I can speak to your questions. 

> Can the upgrade be done with the existing config? Also what's your deprecation plan on the previous version.

This introduces what constitutes a breaking change to modeling processes downstream of sending the events, so it'd be very painful for our userbase to enforce that on them. We're particularly concerned about our open source userbase here.

As far as depreciation goes, we need to communicate it to the community and allow sufficient time for users to upgrade before we fully depreciate - we're happy to work with you guys on doing that, my thoughts are that three months should be enough time.

> I remember you worked with a vendor upgrade before? Is there a generic approach that we can follow.

Please do include me in that too - I'm keen to understand.

Additionally - I'm in the process of testing and QAing these changes for downstream impact, please hold off on merging until I've done that (if you folks would like to hold off on your review until after that's been done I'm happy with that).

I'm not sure what the appropriate channel is for this discussion - but we'd like to enforce something to ensure that a member of the Snowplow team can do the same for any PR raised for this extension. There are a couple of downstream factors that we need to account for. Is there an existing mechanism along these lines? How/where is best to discuss this (slack maybe?).

**Comment by lannka** [comment]
> cc @lannka, I remember you worked with a vendor upgrade before? Is there a generic approach that we can follow.

There wasn't a formal process established. Since we now split vendor config in files, this is less an issue to AMP runtime. But we might provide feature like "console warning for outdated vendor names" to help vendor pushing forward a migration.

for example, add a `deprecated` field to a vendor config:
```js
snowplow: {
  deprecated: true
  ...
}
```
and amp-analytics prints a console user error for all deprecated config.

**Comment by zhouyx** [comment]
>But we might provide feature like "console warning for outdated vendor names" to help vendor pushing forward a migration.

I like that idea. 

@colmsnowplow 
Thank you for the detailed clarification. As @lannka pointed out, we are now moving vendor configs out of the main analytics library. So I'm fine with us creating a new version as a new vendor. Please let me know when this is good for review. I will be out of office starting tomorrow, I'll review it next week. Thanks.

**Comment by colmsnowplow** [comment]
Quick check-in/update on the status of this PR - I've done quite a bit of QA, we're in good shape but there we'll need to push some changes before a final review & merge. 

To explain the delay - there are some design considerations to both doing things the AMP-appropriate way and having the data play nicely with our canonical model downstream, so we've just been working through those. 

We've got a solution that I think satisfies all requirements so once I've got that tested and validated I'll push some commits to this PR and let you know when it's ready for review.

**Comment by micajuine-ho** [comment]
@colmsnowplow I am working on adding a `warningMessage` field in the vendor config to warn developers of possible issues with the config such as deprecation. 

```
snowplow : {
    warningMessage: 'The config you are pulling is deprecated.',
    ...
}
```

This would show up as a developer warning in the console, and it would show the vendor type and/or config url, and and the `warningMessage`.

Is this an adequate solution for helping you migrate?

**Comment by colmsnowplow** [comment]
Yes that'd be great! Thanks

**Comment by micajuine-ho** [comment]
@colmsnowplow  Here is the PR for this: #24777

**Comment by zhouyx** [comment]
@colmsnowplow Could you please apply the new `warningMessage` field @micajuine-ho  introduced. And let us know when the change is ready for review. Thank you.

**Comment by colmsnowplow** [comment]
Thanks @micajuine-ho ! 

@zhouyx yes I will make sure to do so. My updates to this PR have been delayed somewhat but I'll be back working on them in the coming few weeks and will make sure to add this to it!

**Comment by zhouyx** [comment]
Closed by #26059

**Pull request closed without merging**
