### PR TITLE
✨[PubMatic Openwrap] Added curl rtc config in PubMatic openwrap vendor

### PR DESCRIPTION
**Pull request by pm-nikhil-vaidya**
A new parameter _curl_ is added in PubMatic Openwrap RTC config.

### CODE REVIEW

**Review by powerivq — APPROVED** [review]

**Comment by powerivq** [comment]
Hey,

AMP has encountered an infra problem. I believe yours is already on beta and will be, once traffic tests completed, released next week.

**Comment by powerivq** [comment]
@nikunjsureka sorry forgot to tag.

**Comment by nikunjsureka** [comment]
@powerivq Appreciate the quick response. Next week would be great.

**Comment by powerivq** [comment]
@nikunjsureka Spoke too soon, sorry, but the correct timing would be the week after next week. (since there is a production issue last week prevented the latest beta from being tested)./

**Pull request merged**
