### PR TITLE
Use class selector instead of [attr="value"] for amp-social-share.

### LINKED ISSUE #4277: amp-social-share Displaying incorrect SVG icons on iOS8
When using the amp-social-share extension, every button is rendered exactly as the first defined amp-social-share element on the page (in my case, they all appear to be a facebook button).

Making any sort of change to the amp-social-share element using Safari's inspector, causes it to re-render with the correct image and background color.

This appears to be only affecting iOS 8 devices on both Safari & Chrome and running AMP version 1469143772973.

The issue should be reproduceable here: http://www.autoblog.com/amp/2016/07/29/toyota-prius-plug-in-lawsuit-claims-ev-range-false-advertising/

I've also attached a screenshot for reference.

screen shot 2016-07-29 at 2 45 44 pm

### PR DESCRIPTION
**Pull request by mkhatib**
Fixes #4277 

Thanks to @jridgewell for figuring this out! 👍

### CODE REVIEW

**Comment by mkhatib** [comment]
Actually hold off reviewing - not sure if this fixes it. Might be something was cached when I was experimenting...

**Comment by mkhatib** [comment]
Yeah sorry, false positive. That was a cached experiment while I was trying to set `transform` through JS. Fixing the `[type="type"]` didn't fix the problem.

**Comment by mkhatib** [comment]
@jridgewell I don't think there's a reason to keep the old `[attr=val]` selectors so I dropped them all together and switched to class-based. Let me know if this is good or if you can think of a reason to keep them around.

**Comment by jridgewell** [comment]
So does this fix it?

**Comment by mkhatib** [comment]
👍 yes

**Comment by jridgewell** [comment]
LGTM.

**Pull request merged**
