### PR TITLE
🐛 Don't append linker for exact domain match, even if in `domains`.

### PR DESCRIPTION
**Pull request by adamsilverstein**
Fixes https://github.com/ampproject/amphtml/issues/30176

### CODE REVIEW

**Review by micajuine-ho — CHANGES_REQUESTED** [review]
Hi @adamsilverstein, thanks for your contribution. Can we add a test for this use case in `extensions/amp-analytics/0.1/test/test-linker-manager.js`?

Additionally, can we add some documentation in `extensions/amp-analytics/linker-id-forwarding.md`, under `destinationDomains` describing how we won't link if it's an exact match?

**Comment by adamsilverstein** [comment]
@micajuine-ho yes, I will work on those items.

Based on the discussion in the issue, are we going with adding a `noInternalLinking` option to enable this behavior?

**Comment by micajuine-ho** [comment]
> Based on the discussion in the issue, are we going with adding a noInternalLinking option to enable this behavior?

No, right now the only valid use-case seems to be debugging locally. So if there is another use-case, we can consider adding it in.

**Comment by adamsilverstein** [comment]
@micajuine-ho I took a pass at a test and docs. Can you please review and revise or advise how to improve? 

Also, can you tell me the command to run the test file I added the test to?  I'm struggling to figure it out!

**Comment by micajuine-ho** [comment]
Changes LGTM. I've also verified with the ads team that we do not expect Linker to be used in ad environments. 

> Also, can you tell me the command to run the test file I added the test to? 

`gulp unit --local_changes`

Also, before you submit, run: 

`gulp lint --local_changes --fix`

and address any issues that command brings up. You also might want to rebase again, since I know we've been making a lot of infra changes and it doesn't hurt to keep your this branch up to date.

**Comment by adamsilverstein** [comment]
Thanks for the help @micajuine-ho - I have updated the PR:

* Merged master to branch, resolving conflicts.
* Ensured linting and new tests pass, switch to using `windowInterface` mocking like other tests.
* Added a missing return type to `isDomainMatch_` (see https://github.com/ampproject/amphtml/issues/23582)
* Clarify documentation and correct a couple of typos I noticed in `extensions/amp-analytics/linker-id-forwarding.md`

**Review by micajuine-ho — APPROVED** [review]

**Comment by kristoferbaxter** [comment]
This is great news! @micajuine-ho with this work we can now enable a `quicklink` like implementation without a Service Worker.

Can you add this to the list for the @ampproject/wg-components group?

**Comment by micajuine-ho** [comment]
Yup adding it to our sprint planning!

**Comment by westonruter** [comment]
> This is great news! @micajuine-ho with this work we can now enable a `quicklink` like implementation without a Service Worker.

So does this mean #19905 will be brought back?

**Comment by kristoferbaxter** [comment]
@westonruter 

We should consider the design from scratch, perhaps we can partner on an implementation soon?

**Comment by claudiucelfilip** [comment]
> > Based on the discussion in the issue, are we going with adding a noInternalLinking option to enable this behavior?
> 
> No, right now the only valid use-case seems to be debugging locally. So if there is another use-case, we can consider adding it in.

@micajuine-ho In the case of WordPress.com, we relied on internal linking to transition from our AMP Landing Pages to Calypso; which happen to share the same domain. 
We've discovered that these changes have been affecting our AMP analytics, which has been addressed.
Going forward, having more control over the linker would be appreciated, and having a `noInternalLinking` option (or similar) sounds like a good compromise.

**Pull request merged**
