### PR TITLE
✅  Fix 5 failing IE11 tests because of missing argument

### PR DESCRIPTION
**Pull request by rcebulko**
Whenever this code was added (quite a long time ago), the function `createFixtureIframe` was called without the second parameter specifying the desired iframe height, leading to downstream code calling `iframe.height = initialIframHeight` where `initialIframeHeight` was `undefined`. It appears that in most browsers, doing so results is some reasonable fallback. In IE11 (or at least the version of the code output by Browserify) the result of this is an error, which was failing five of the tests under IE11.

Part of broad effort under https://github.com/ampproject/amphtml/issues/28152 to enable IE11 integration tests as blocking 

Example log output of test failures:
image

### CODE REVIEW

**Comment by kristoferbaxter** [comment]
Another option might be changing the `createFixtureIframe` to use a default height if one isn't specified...

```javascript
export function createFixtureIframe(
  fixture,
  initialIframeHeight = 500,
  opt_beforeLoad
) 
```

**Comment by rcebulko** [comment]
> Another option might be changing the `createFixtureIframe` to use a default height if one isn't specified...
> 
> ```js
> export function createFixtureIframe(
>   fixture,
>   initialIframeHeight = 500,
>   opt_beforeLoad
> ) 
> ```

@kristoferbaxter I considered that, on the fence. Looking at the function JSDoc, the height is not listed as optional, nor prefixed with `opt_`.I looked at every other usage throughout the codebase, and it seems this is the only case in which it was called without providing a height. Since the function signature is fairly clear and used mostly correctly, it seems more reasonable to fix this one issue and maybe add a `devAssert` (I think?) verifying the initial height is defined

**Comment by rcebulko** [comment]
Before:
image

After:
image

**Comment by kristoferbaxter** [comment]
If the value is required but not specified by some callers we should consider throwing an error.

LGTM to get this in though! Thanks for the investigation.

**Review by kristoferbaxter — APPROVED** [review]

**Comment by rsimha** [comment]
Late review to say thanks for the investigation and the fix!

**Pull request merged**
