### PR TITLE
🚀 [Analytics Parsely] Update host entry to use the new endpoint

### PR DESCRIPTION
**Pull request by nbetm**
This PR replaces the parsely legacy host endpoint with the new one.

cc: @cwisecarver

### CODE REVIEW

**Review by erwinmombay — APPROVED** [review]

**Comment by nbetm** [comment]
All tests passed. Ready to merge. Thanks, @erwinmombay.

**Review by erwinmombay — APPROVED** [review]

**Comment by erwinmombay** [comment]
approved. waiting on green build

**Comment by nbetm** [comment]
@erwinmombay, the last commit was a green build. Please let me know if there's anything else needed to merge this PR.

**Comment by erwinmombay** [comment]
@nbetm sorry for delay. merged

**Pull request merged**
