### PR TITLE
✨ Implement amp-poool component

### PR DESCRIPTION
**Pull request by dackmin**
Implements a new `amp-poool` component (as well as its needed 3p library) to be able to show a [dynamic paywall](https://dev.poool.fr/) inside amp articles 😄

Please feel free to comment any line of that PR !

### CODE REVIEW

**Comment by dackmin** [comment]
@googlebot 
I signed it!

**Comment by aghassemi** [comment]
Hi @dackmin, 

Thanks for the PR and integrating your service with AMP.

Have you considered using the same approach as `amp-access` and `amp-access-laterpay` since your service is a paywall? 

Unfortunately the pattern of exposing events on a component that are allowed to run `hide`, `show` actions in AMP page is not compatible with AMP's UX principle of not allowing content to shift after page load. Unless there is a guarantee that these events are generated by a user-gesture (which is not possible across iframe boundaries) we can't allow the events you currently have to run AMP actions.

We encourage contributors to file [Intent To Implement](https://github.com/ampproject/amphtml/blob/a8cf35e3908bd8516be58dde4f48f8759c2bac52/contributing/building-an-amp-extension.md#a-word-on-contributing) issue so we could discuss approaches before full implementation takes place.
 
/cc @dvoytenko @jridgewell

**Comment by jpettitt** [comment]
In addition to the comments @aghassemi made all AMP pages are designed to be catchable or one of the amp caches.  This means that every users gets exactly the same basic page so `data-user-is-premium` is going to be meaningless and either all users will be premium or none will.  I haven't dug into the other attributes but any assumption based on serving different pages to disparate users will not work withe AMP.

**Comment by aghassemi** [comment]
@dackmin Closing this PR for house-keeping. Please see comments above. Looking forward to ITI and next PR.

**Pull request closed without merging**
