### PR TITLE
amp-ad: Fix capirs ad initialisation 🐛

### PR DESCRIPTION
**Pull request by pyxarez**
As mentioned in the [docs](https://github.com/ampproject/amphtml/blob/master/ads/README.md#the-iframe-sandbox), we should put ad in ```div[id="c"]``` container in order to avoid bugs.
That pr fixes appending to the body.

### CODE REVIEW

**Comment by pyxarez** [comment]
I signed it!

**Comment by pyxarez** [comment]
I signed it!

**Comment by pyxarez** [comment]
Hey! Is there someone to review PR:)

**Comment by ithinkihaveacat** [comment]
@pyxarez The link to the docs doesn't work for me, is it correct? i.e. https://jira.rambler-co.ru/browse/SUP-36063.

**Comment by pyxarez** [comment]
@ithinkihaveacat, yea sorry that was a wrong link, but I just fixed it

**Pull request merged**
