### PR TITLE
⏪  Revert "build-system: use metafile for smarter watching (#33840)"

### PR DESCRIPTION
**Pull request by dmanek**
This reverts commit 355d437586c3a8b8b441ef8a042f544d47948305.

### CODE REVIEW

**Comment by alanorozco** [comment]
@rsimha FYI the change reverted broke building JSX:

```
 > extensions/amp-render/1.0/component.js:72:4: error: Unexpected "<"
    72 │     <Wrapper {...rest} dangerouslySetInnerHTML={isHtml ? rendered : null}>
       ╵     ^

 > src/preact/base-element.js:691:15: error: Unexpected "<"
    691 │         comp = <Context.Provider value={value}>{comp}</Context.Provider>;
        ╵                ^

(node:14937) UnhandledPromiseRejectionWarning: Error: Build failed with 2 errors:
extensions/amp-render/1.0/component.js:72:4: error: Unexpected "<"
src/preact/base-element.js:691:15: error: Unexpected "<"
```

Do we depend on the change at the moment?

**Review by rsimha — CHANGES_REQUESTED** [review]
@dmanek #33840 fixed some critical dev workflows, and reverting it will have wide reaching effects that go beyond JSX files. Can you provide repro steps for what is broken so we can put in a targeted fix? (I have one such fix already out for review in #33864, which may be what we need.)

I'd like for @samouri to take a closer look at this when he's back, but if there's a quick fix that can be incorporated, I can look into it today.

**Comment by alanorozco** [comment]
I was mistaken that JSX was affected in general. This works fine, and it builds JSX:

```console
amp build --extensions=amp-fit-text --core_runtime_only
```

**Comment by rsimha** [comment]
#33864 (which contains some fixes to #33840) has been merged. Please rebase on the latest `main` branch and provide repro steps if you see any build errors.

**Comment by alanorozco** [comment]
Nope, my bad! This **fails**:

```console
amp build --watch --extensions=amp-fit-text --core_runtime_only
```
```
 > extensions/amp-fit-text/1.0/component.js:73:4: error: Unexpected "<"
    73 │     <ContainWrapper
       ╵     ^

[10:29:41] Compiled amp-fit-text-0.1.max.js → amp-fit-text-latest.max.js (321 ms)
 > src/preact/base-element.js:691:15: error: Unexpected "<"
    691 │         comp = <Context.Provider value={value}>{comp}</Context.Provider>;
        ╵                ^
```

**Comment by rsimha** [comment]
@dmanek @alanorozco Fix has been merged. Please rebase on `main` and let me know if everything looks good.

**Comment by dmanek** [comment]
Fixed by #33875. Closing.

**Pull request closed without merging**
