### PR TITLE
🐛 [amp-story] Only allow media elements to be played and unmuted when they are located on the active story page

### LINKED ISSUE #37071: Multiple story background audios play at the same time
### Description

In a web story, the background audios of different pages might play at the same time.

### Reproduction Steps

1. Create a web story with multiple pages.
2. For each page of the story, set a different background audio using either the `background-audio` attribute or `amp-audio` tag.
3. Open the story.
4. Before the first audio is loaded, quickly navigate through a few pages.

Expected behavior: It should only play the audio for the current page.
Observed behavior: Background audios of the previous pages might also be played at the same time.

This bug can be reproduced using either the `background-audio` attribute or `amp-audio` tag.

It's easier to reproduce the bug when it takes a long time to fetch the audio files. So setting a large audio file as the background audio or the "slow 3g network" option in chrome might help reproduce it.

### Relevant Logs

_No response_

### Browser(s) Affected

_No response_

### OS(s) Affected

All OSs

### Device(s) Affected

All devices

### AMP Version Affected

_No response_

### PR DESCRIPTION
**Pull request by coreymasanto**
- Fixes #37071

---

**Bug cause:**
When the user navigates from Page A to Page B, [amp-story-page.resume_()](https://github.com/ampproject/amphtml/blob/fc739c0d339dbae236fa53a87188f5f7ca58f25c/extensions/amp-story/1.0/amp-story-page.js#L490) is called for Page B, and this asynchronous function eventually calls [amp-story-page.unmuteAllMedia()](https://github.com/ampproject/amphtml/blob/fc739c0d339dbae236fa53a87188f5f7ca58f25c/extensions/amp-story/1.0/amp-story-page.js#L943) for Page B. 

And when the user navigates from Page B to an adjacent page, [amp-story-page.pause_()](https://github.com/ampproject/amphtml/blob/fc739c0d339dbae236fa53a87188f5f7ca58f25c/extensions/amp-story/1.0/amp-story-page.js#L469) is called for Page B, and this asynchronous function eventually calls [amp-story-page.muteAllMedia()](https://github.com/ampproject/amphtml/blob/fc739c0d339dbae236fa53a87188f5f7ca58f25c/extensions/amp-story/1.0/amp-story-page.js#L914) for Page B.  

If the user navigates to Page B and then navigates to an adjacent page, then there will be a `resume_()` call followed by a `pause_()` call. Because of the asynchronous nature of these methods, it is possible for the eventual `muteAllMedia()` call to inadvertently occur before the `unmuteAllMedia()`, particularly when the user rapidly navigates towards and then away from the page.

**Bug fix:**
This PR causes `PlayTask` and `UnmuteTask` executions to be no-ops when applied to media elements that are not on the active story page. During my investigation of this bug, I was able to get up to 3 pages' media elements to simultaneously play. With this fix, I am unable to repro the bug.

### CODE REVIEW

**Comment by gmajoulet** [comment]
Thank you for researching this issue, and documenting the wrong behavior.

I see why you decided to fix this at the "core" level (media tasks) vs the implementation (`amp-story-page.resume_()`), but I think we should fix the implementation in this case.
- The media tasks don't know about Story specific context, they should perform basic operations on `HTMLMediaElement` nodes and not carry extra context about how/where they're used
- The audio playing is just one symptom of the bug, and this fix is only addressing the visible part of the issue. For example, some methods like `startListeningToVideoEvents_()` will still run, and potentially we'll get double events listeners

Wdyt about switching the fix and adding early returns in the `amp-story-page.resume_()` method if the page state switched to `PageState.NOT_ACTIVE`?

e.g.

```
  /**
   * @private
   */
  resume_() {
    const registerAllPromise = this.registerAllMedia_();

    if (this.isActive()) {
      registerAllPromise.then(() => {
->    if (this.state_ === PageState.NOT_ACTIVE) return;
        this.signals()
          .whenSignal(CommonSignals_Enum.LOAD_END)
          .then(() => {
            if (this.state_ == PageState.PLAYING) {
              this.advancement_.start();
            }
          });
->      this.preloadAllMedia_().then(() => {
        if (this.state_ === PageState.NOT_ACTIVE) return;
        ...
```

**Comment by coreymasanto** [comment]
> Wdyt about switching the fix and adding early returns in the amp-story-page.resume_() method if the page state switched to PageState.NOT_ACTIVE?

I think you make great points about why we shouldn't place the fix within `media-tasks.js`, and I agree that early returns in `amp-story-page.js` are a better alternative. However, I think that an early return after `preloadAllMedia_()` may not suffice, since the [playAllMedia_() call](https://github.com/ampproject/amphtml/blob/112742b6c6d8521a4b685e0dea9fad6ca165428a/extensions/amp-story/1.0/amp-story-page.js#L506) below it is asynchronous, which seems like it could still result in an UnmuteTask being unintentionally enqueued after the MuteTask. What are your thoughts on us making the following changes within `amp-story-page.js`?

1. Add your suggested early return in `resume_()` right before the `this.startMeasuringAllVideoPerformance_()` call, in order to ensure that we don't measure video performance or listen to video events for inactive pages
2. Add another early return in `playMedia_()` right before the [mediaPool.play() call](https://github.com/ampproject/amphtml/blob/112742b6c6d8521a4b685e0dea9fad6ca165428a/extensions/amp-story/1.0/amp-story-page.js#L843-L844), in order to guarantee that the media pool doesn't enqueue a PlayTask for a page that is inactive
3. Add a final early return in `unmuteMedia_()` right before the [mediaPool.unmute() call](https://github.com/ampproject/amphtml/blob/112742b6c6d8521a4b685e0dea9fad6ca165428a/extensions/amp-story/1.0/amp-story-page.js#L965-L966), in order to guarantee that the media pool doesn't enqueue an UnmuteTask for a page that is inactive

**Comment by gmajoulet** [comment]
1. I'll trust you with these I didn't look into enough details :)) 
2 and 3. I'd really love if they could all be in the `resume_()` method, happy to justify it more but to keep it super simple: I think the best way to structure a class is to have small methods that do basic operations (e.g. play/pause/mute) and have no business logic. Then have lifecycle methods that use them, and contain the business logic (e.g. resume(), pause()). Then you have a great split of your operations (small easy to test helpers) and business logic (in just one place, easy to find and debug), it makes the code easier to read, test, maintain.

**Comment by coreymasanto** [comment]
>  I'd really love if they could all be in the resume_() method

I've added 3 early returns throughout the `resume_()` method and they seem sufficient for eliminating further occurrences of this issue. Specifically, the early return preventing the `unmuteAllMedia()` call is frequently executed when tapping quickly through a story. When testing locally with just this early return, I can no longer repro the issue. We should still include the other 2 early returns since their absence may cause less obvious issues

**Review by gmajoulet — APPROVED** [review]

**Pull request merged**
