### PR TITLE
Removed CID param from the request

### PR DESCRIPTION
**Pull request by dimitarandonov**
We don't need to pass the cid in the request.

### CODE REVIEW

**Comment by dimitarandonov** [comment]
Hi @alanorozco! Can you please approve the PR? It is a small change.
Cheers!

**Comment by erwinmombay** [comment]
@dimitarandonov just checking, are you associated with gfksensic?

**Comment by oezd** [comment]
Hi @erwinmombay 
yes, @dimitarandonov is part of the GfK SE organization and a team member of GfK SENSIC

**Comment by dimitarandonov** [comment]
> @dimitarandonov just checking, are you associated with gfksensic?

Hi @erwinmombay!
Yes, I am.

**Review by erwinmombay — APPROVED** [review]

**Comment by erwinmombay** [comment]
appreciate the confirmation. merged.

**Pull request merged**
