### PR TITLE
Update amp-ad-template.amp.html

### PR DESCRIPTION
**Pull request by karl1993**

### CODE REVIEW

**Review by karl1993 — COMMENTED** [review]
Thanks

**Review by karl1993 — COMMENTED** [review]
Yes

**Review by karl1993 — COMMENTED** [review]
Yes

**Review by kristoferbaxter — CHANGES_REQUESTED** [review]
This doesn't make much sense:
1. The document isn't valid AMP with the inserted script 
2. I'm missing the value in using a hardcoded client id.

**Pull request closed without merging**
