### PR TITLE
🐛 Amp story 360 - add integration with amp-story and play/pause/resize support

### PR DESCRIPTION
**Pull request by t0mg**
@gmajoulet please review :)

Next: 
- validator
- md
- video support

### CODE REVIEW

**Comment by gmajoulet** [comment]
> With this implementation play/pause works when switching pages but the first page doesn't play on landing. What's missing?

Will check this today, thanks for your work!!

**Comment by t0mg** [comment]
@gmajoulet ping ?

**Comment by gmajoulet** [comment]
Should we close this one in favor of https://github.com/ampproject/amphtml/pull/29235 ?

**Comment by t0mg** [comment]
> Should we close this one in favor of #29235 ?

IDK I was hoping to get this one in first and rebase the other one to keep validator separate from play/pause implementation.

**Pull request closed without merging**
