### PR TITLE
Change the LCP/CLS trade-off in font timeouts

### PR DESCRIPTION
**Pull request by cramforce**
Make it so that the timeout

- Is as late as possible (reduces swaps)
- But still in time to enable a good LCP time (2500ms)

Related to #27776

### CODE REVIEW

**Comment by wassgha** [comment]
This still respects the`font-display` value if set by the developer, not sure if we should override in this case, needs some data

**Comment by cramforce** [comment]
I'd expect it to be set so rarely that this will not make a different in aggregate. Also, setting it will be correlated with good performance.

**Comment by cramforce** [comment]
@wassgha Do you have samples where font-jank leads to bad CLS, and could you test those with this change?

**Comment by wassgha** [comment]
I've tested it on a few websites from the [colab](https://colab.corp.google.com/drive/1fWskqa6gobsh0o4keR58QKsh4WzUTaDH) and it seems to improve things a bit. I'll leave a comment on #27781 to follow up.

**Comment by cramforce** [comment]
This is now ready for review.

**Comment by cramforce** [comment]
Friendly ping.

**Comment by wassgha** [comment]
@cramforce I'd love it if you briefed about this during the design review before we merge it

**Pull request merged**
