### PR TITLE
✨ MovingPlay Component

### PR DESCRIPTION
**Pull request by salmorf**
MovingPlay: create new player extension based on clappr
CC @alanorozco

### CODE REVIEW

**Comment by salmorf** [comment]
I signed it!

**Comment by mrjoro** [comment]
@salmorf is this PR still active?

**Comment by mrjoro** [comment]
Can someone from @ampproject/wg-viewers take a look?

**Comment by ericfs** [comment]
Yes, I can take a look. Is there something AMP Viewer specific that you would like input on?

**Comment by mrjoro** [comment]
@ericfs whoops, I added this comment on the wrong PR; I'll add you to the right one :)

**Comment by ericfs** [comment]
Thanks, this didn't really look relevant to the Viewer. I'll stop looking.

**Comment by mrjoro** [comment]
Closing this this PR no longer seems active.  Please reopen if needed.

**Pull request closed without merging**
