### PR TITLE
added some vars and requests in gfksensic.json

### PR DESCRIPTION
**Pull request by dimitarandonov**

### CODE REVIEW

**Comment by dimitarandonov** [comment]
Hi, I hope someone is able to look at this PR soon. We would like to get this merged as soon as possible. Any feedback is appreciated.

**Comment by dimitarandonov** [comment]
Hi, I hope someone is able to look at this PR soon. We would like to get this merged as soon as possible. Any feedback is appreciated.

**Comment by dimitarandonov** [comment]
Hi, we are currently blocking some of our clients. Can you give some feedback if everything is ok or not with this pull request? We would like to get this merged as soon as possible.

**Comment by dimitarandonov** [comment]
Hi @alanorozco,

We need to have this as soon as possible to enable our clients to use the AMP integration properly.

Can you please let us know if we missed anything to get this PR reviewed?

**Comment by dimitarandonov** [comment]
Hi @alanorozco ,

We need to have this as soon as possible to enable our clients to use the AMP integration properly.

Can you please let us know if we missed anything to get this PR reviewed?

**Comment by dimitarandonov** [comment]
Hi @alanorozco ,

We need to have this as soon as possible to enable our clients to use the AMP integration properly.

Can you please let us know if we missed anything to get this PR reviewed?

**Comment by dimitarandonov** [comment]
Hi @alanorozco ,

We need to have this as soon as possible to enable our clients to use the AMP integration properly.

Can you please let us know if we missed anything to get this PR reviewed?

**Comment by dimitarandonov** [comment]
Hi @alanorozco ,

We need to have this as soon as possible to enable our clients to use the AMP integration properly.

Can you please let us know if we missed anything to get this PR reviewed?

**Comment by dimitarandonov** [comment]
Hi @alanorozco ,

We need to have this as soon as possible to enable our clients to use the AMP integration properly.

Can you please let us know if we missed anything to get this PR reviewed?

**Comment by martinbruntsch** [comment]
Hi @alanorozco, @dmanek, @caroqliu , @rbeckthomas . we are waiting for review and we are totally puzzeled since nothing happens for 2 month now. What are we doing wrong? anything missing?
Thanks for your feedback. Appreciate your  help.
Cheers

**Comment by martinbruntsch** [comment]
Hi @powerivq @processprocess @alanorozco, @dmanek, @caroqliu , @rbeckthomas . we are waiting for review and we are totally puzzeled since nothing happens for 2 month now. What are we doing wrong? anything missing?
Thanks for your feedback. Appreciate your help.
Cheers

**Review by alanorozco — APPROVED** [review]
Thank you for your PR and your patience. Approved.

**Pull request merged**
