### PR TITLE
Stop requiring source origin header for bookend

### LINKED ISSUE #11846: amp-story bookend-config-src should match amp-list src requirements
Currently `bookend-config-src` requires the `Access-Control-Allow-Origin` header, which `amp-list src` does not.  We should reuse whatever mechanism that `amp-list` is using for `amp-story` as well.

### PR DESCRIPTION
**Pull request by newmuis**
Fixes #11846

### CODE REVIEW

**Comment by newmuis** [comment]
ping

**Comment by bpaduch** [comment]
@newmuis @alanorozco - Any eta on this?  I'd like to use this functionality for the AMP Story tutorial sample.

**Comment by newmuis** [comment]
Unfortunately, many of the core reviewers (@alanorozco included) are out for the time being.  This might not get in until next week.

**Comment by alanorozco** [comment]
:)

**Pull request merged**
