### PR TITLE
Run integration tests (uncompiled) with every PR

### LINKED ISSUE #10767: `gulp test` is also running integration tests
See the config [here](https://github.com/ampproject/amphtml/blob/master/build-system/config.js#L54). Shall we make `gulp test` only run unit/functional tests, because that's how we [split the shards](https://github.com/ampproject/amphtml/blob/master/build-system/pr-check.js#L312).

### PR DESCRIPTION
**Pull request by rsimha-amp**
Fixes #10767

### CODE REVIEW

**Comment by rsimha-amp** [comment]
With this PR, for changes that touch the runtime or `test/integration`, the travis build time has now increased from 20 minutes to 30 minutes, which is more reasonable than the previous 45-50 minute duration. It's a good price to pay for better PR coverage. See https://travis-ci.org/ampproject/amphtml/builds/260747129 for an example of a PR run.

There are no changes to what we do on `master` once a PR has been merged. 

This is now ready for review.

**Comment by choumx** [comment]
Is there an easy way to run both unit and integration tests locally?

**Comment by rsimha-amp** [comment]
@choumx, Running integration tests and unit tests will now require two calls to `gulp test` with different sets of flags. One way to run both of them with one command is to leave the default as it is, but add a `--functional` flag to skip integration tests, and then use that flag on Travis in the unit tests shard.

IIRC, the idea was to change the default `gulp test` to not run integration tests because we shouldn't force run the integration tests with the unit tests. I'm planning another PR to enforce unit-test-ness of unit tests by skipping the `gulp build` call before running unit tests.

WDYT?

/cc @lannka

**Comment by lannka** [comment]
@choumx because unit test and integration test has different pre-requisite, i actually now think use one single command to run is not useful, or at least not efficient.

most of time, i run test with `--nobuild`, and most likely I'm running with `--files=`. @choumx do you see a good use case that you typically want to run everything in one command locally?

**Comment by choumx** [comment]
If I'm working on extension amp-foo that has both unit and integration tests, how do I make sure my changes don't cause a regression? 

Seems like we'd have to do this:
```sh
# Run this on every change?
gulp test --files=extensions/amp-foo/0.1/test/* 
    && gulp test --files=extensions/amp-foo/0.1/test/* --integration
```

What I'd want is this:
```sh
gulp test --watch --files=extensions/amp-foo/0.1/test/*
```

**Comment by rsimha-amp** [comment]
After chatting offline with @choumx, I'm moving the new behavior to a `--functional` flag to be passed in to `gulp test` to run just the unit tests. Coming up.

**Pull request merged**
