### PR TITLE
To track analytics vendor's predefined transport overwriting count

### PR DESCRIPTION
**Pull request by zhouyx**
Add user error. To get data for #7096

### CODE REVIEW

**Comment by cramforce** [comment]
This error seems to trigger on basically every page. Is that intended? Please try in canary.

**Comment by zhouyx** [comment]
@cramforce Looking into this. I see all most all errors come from one domain. Shouldn't be triggered on every page

**Comment by cramforce** [comment]
Was swiping through "trump" query carousel and saw a bunch of these
warnings.

**Comment by zhouyx** [comment]
Ah....I see the reason... Will fix. Interesting that I see most errors from demo-google-com.

**Pull request merged**
