### PR TITLE
Merge initialization steps for inabox

### PR DESCRIPTION
**Pull request by powerivq**
This should not alter the behavior. It does not block right now.

### CODE REVIEW

**Comment by lannka** [comment]
@cramforce shall we completely remove chunking in inabox?

**Comment by cramforce** [comment]
Hmm, I'd not do this. Or rather. It is just a micro-task. What you should make really sure is that chunking always runs in fast-mode

**Comment by lannka** [comment]
@cramforce if there is not much difference (fast-mode vs no chunking at all), why not just completely removing them?

**Comment by cramforce** [comment]
Maybe I need to clarify:

If chunking is in fast-mode, then it isn't slower than not-chunking. If chunking is in low-priority mode, then it is slower.

**Comment by lannka** [comment]
my current understanding: (please correct me)
-  "fast-mode" is the use of `startupChunk` (instead of `chunk`)
- `startupChunk` is not slower than non-chunking, the only speed difference is when the document is invisible. 
https://github.com/ampproject/amphtml/blob/8a150b67a847a32fe1d2759dacbee3ad91724c30/src/chunk.js#L50-L63
- For the inabox case, the document is always visible, so `startupChunk` is not slower than non-chunking. if there is no difference, why can't we just remove the code?
- There will be a difference once the `macro-after-long-task` experiment is launched. Is it the only reason that you want to keep the chunking code in inabox?
https://github.com/ampproject/amphtml/blob/8a150b67a847a32fe1d2759dacbee3ad91724c30/tools/experiments/experiments.js#L338-L341

**Comment by cramforce** [comment]
We can't remove the code because it schedules a micro-task and removing
that micro-task would change execution order. You could replace the
implementation of chunk service with a trivial one that just schedules a
micro-task.

macro-after-long-task does change things, but not necessarily for the worse.

**Pull request closed without merging**
