### PR TITLE
 Update callout-vendors.js to add Rubicon Project as a vendor

### PR DESCRIPTION
**Pull request by djsu**

### CODE REVIEW

**Comment by djsu** [comment]
I signed it!

**Comment by djsu** [comment]
Signed CLA

**Comment by djsu** [comment]
Signed

**Comment by sandraleon** [comment]
I signed it!

**Comment by djsu** [comment]
I signed it!

**Comment by alanorozco** [comment]
Looks like CLA check is in a terminal state.

Bad news is that one of you will need to create a new PR with this same content. Sorry about that!

**Pull request closed without merging**
