### PR TITLE
🐛Added Mute/Unmute Controls to <amp-ima-video>

### LINKED ISSUE #18531: amp-ima-video: Missing Mute/Unmute Controls
relates to #8841

# Issue Context

* Issue is visible on the [`amp-ima-video` AMP By Example](https://ampbyexample.com/components/amp-ima-video/).

* Source code for the `<amp-ima-video>` can be found in [ads/google/imaVideo.js](https://github.com/ampproject/amphtml/blob/master/ads/google/imaVideo.js).

* Currently, we are designing/considering a rebuild of video within AMP to use Video.js, so smaller issues will be considered as we don't want to dedicate too much time on the older component version.

# Issue Description

Currently there is no functioning Mute/Unmute button on the `amp-ima-video` extension.

### PR DESCRIPTION
**Pull request by torch2424**
closes #18531

This adds mute/unmute controls to `<amp-ima-video>` 😄 Also, does some updating to the `<amp-ima-video>` that makes it usable on desktop, and offers more context on ima, and it's example implementation.

# Examples

imavideomute

### CODE REVIEW

**Comment by torch2424** [comment]
Going to look for an IMA team member to give this a review 😄

**Comment by zhouyx** [comment]
Should we put the mute button on the left side or right side?

**Comment by torch2424** [comment]
IMA team doesn't have bandwidth, and @spacedino approved of the media button on the right side 😄 

cc @zhouyx

**Comment by zhouyx** [comment]
One more request, can I see the UI in mobile? Otherwise looks awesome! Thank you for digging into the code and let's ship it!

**Comment by torch2424** [comment]
Showed Mobile UI in person to @zhouyx 

Thanks for the LGTM Merging 😄

**Pull request merged**
