### PR TITLE
Support node v10, v12, or v14 for amphtml-validator

### PR DESCRIPTION
**Pull request by estherkim**

### CODE REVIEW

**Comment by rsimha** [comment]
Force merging this to unblock #25188.

**Comment by twifkak** [comment]
This was published as https://www.npmjs.com/package/amphtml-validator version 1.0.28.

**Comment by dmouse** [comment]
any plans to support node 8.x? Next.js use it https://github.com/zeit/next.js/pull/9172

**Comment by rsimha** [comment]
> any plans to support node 8.x? Next.js use it [zeit/next.js#9172](https://github.com/zeit/next.js/pull/9172)

Node 8 support was restored with #25278 and #25279, and should be available with [`amphtml-validator` v1.0.29](https://www.npmjs.com/package/amphtml-validator/v/1.0.29).

**Pull request merged**
