### PR TITLE
Launch flexible-bitrate experiment to 10%.

### PR DESCRIPTION
**Pull request by gmajoulet**
Launch `flexible-bitrate` experiment to 10%.

### CODE REVIEW

**Review by rsimha — COMMENTED** [review]
`@ampproject/wg-approvers` is an owner of these files, perhaps it makes sense to get one of them to review this launch?

(There's no need for an infra review for this directory.)

**Comment by gmajoulet** [comment]
Could you please help me find a reviewer? I thought the OWNERS bot would auto assign someone.
https://amp.dev/community/working-groups/approvers/ and https://github.com/ampproject/wg-approvers did not really help :((

**Review by mszylkowski — APPROVED** [review]
Thanks for helping with this!

**Comment by rsimha** [comment]
> Could you please help me find a reviewer? I thought the OWNERS bot would auto assign someone.

The bot seems to have been configured to not ask them for reviews automatically.

https://github.com/ampproject/amphtml/blob/76c5e724888490763f9355aaeeffdc0663fea40b/build-system/global-configs/OWNERS

> https://amp.dev/community/working-groups/approvers/ and https://github.com/ampproject/wg-approvers did not really help :((

The list of approvers is at https://github.com/orgs/ampproject/teams/wg-approvers/members. I've added a reviewer.

**Review by newmuis — APPROVED** [review]

**Pull request merged**
