### PR TITLE
Live Preview for AMP Validator Web UI 

### PR DESCRIPTION
**Pull request by sebastianbenz**
Extends validator.ampproject.org to show a live preview of the document. The preview is rendered inside an iframe below the validation results.

### CODE REVIEW

**Comment by sebastianbenz** [comment]
This is a first prototype and still work in progress, but I would like to get your feedback before I put too much effort in it. Here is a demo:

amp-playground

**Comment by sebastianbenz** [comment]
OK - here is a first version:

amp-playground-2

* Shows preview right beside editor window
* Renders current AMP doc in iframe
* Updates with every validation run
* Hidden on mobile

Other Changes:

* Renamed button: 'validate' -> 'load'
* Larger code view -> moves error list below the first viewport (OK?)
* Error list no longer has a fixed height

Let me know what you think and whether this makes sense to integrate into the validator UI. My goal would be to link from every ABE sample to an editable version in the playground.

PTAL @powdercloud @cramforce @pbakaus

**Comment by pbakaus** [comment]
Nice one!

**Comment by cramforce** [comment]
Rocking! 💯

**Comment by honeybadgerdontcare** [comment]
Very nice!

One thing to consider is that the preview blocks a fair amount of the editor and where the errors occur. 
Some ideas:
 - make it a tab similar to the `Preview` tab here on github
 - make both editor and preview resizable
 - allow the preview to pop out of the page in a new window

**Comment by sebastianbenz** [comment]
@honeybadgerdontcare I made the editor/preview windows resizable => I like it because it makes it easy to explore responsive behavior of components. 

Here is an online demo: https://amp-demo-1092.appspot.com/

**Comment by sebastianbenz** [comment]
PTAL

**Comment by honeybadgerdontcare** [comment]
That looks great! Thank you. I'll let @powdercloud do the final review. Only thing I noticed with the slider is that moving it all the way right loses the ability to bring it back but that might be a polymer issue.

**Comment by sebastianbenz** [comment]
@honeybadgerdontcare this was caused by me not providing a min-width.

I've also made the code more idiomatic Polymer (at least I hope so) + added support for resizing the window.

**Comment by ericlindley-g** [comment]
Awesome!

@sebastianbenz  — one thing to consider is that previews won't represent transformations done in the Google AMP Cache (or other caches), or effects of AMP Viewers. May be worth adding a note about this so folks aren't surprised if there are any differences when displayed via a platform.

**Comment by sebastianbenz** [comment]
@ericlindley-g AMP viewers usually render AMPs inside an iframe as well - so the experience should be pretty close (@dvoytenko might prove me wrong).

**Comment by ericlindley-g** [comment]
@sebastianbenz Close but not identical — one example is the header bar. Another is the recent issue with z-index on the sidebar (though I'm not sure if that issue is introduced in the cache or in the viewer directly).

**Comment by Gregable** [comment]
The header bar aside, everything else should be a bug in AMP. We don't intend the document to render differently on the cache vs. origin. Many developers are only testing on origin and assuming this transformation is optimizations only. Considering how much of a corner case these issues would be, I'd avoid adding additional warnings that could add confusion.

**Comment by Gregable** [comment]
Another issue to look out for is that it is possible to construct an URL to the validator interface which will fetch and load the contents. As long as we are simply displaying source, we should be fine. However, if we render the contents, which could have javascript, we might be creating an XSS vector.

**Comment by dvoytenko** [comment]
@ericlindley-g @sebastianbenz FYI: indeed few things will be different between a basic iframe and a viewer iframe. There are some things that AMP does to adjust itself to viewer case vs what we now call "in-a-box". I think this case is more of the latter. The set of differences is not big, but some nuances like fixed element treatment are always a source of problems: hence the recent sidebar problem.

/cc @lannka

**Comment by ericlindley-g** [comment]
@rudygalfi  for thoughts on a kind of disclaimer here that this preview does not necessarily represent the view of AMP on platforms

I don't think the scope of the validator page should expand to incorporate the viewer and cache into the actual preview (though another surface for that would be nice), but a disclaimer seems wise.

**Comment by powdercloud** [comment]
Thanks a lot! I think this is a cool thing for amp by example or similar sites. Adding some stuff to think about.
I wonder whether it'd be best to make this into a control which is optimized for ampbyexample and similar usages, rather than trying to do the preview for the general case (any amp site). I think the general case may be too tricky because AMP pages can reference stuff on the host subdomain and so making the preview work requires a proxy or some (fancy?) rewriting. E.g., if I put https://www.ampproject.org/ into the demo, it won't render well even though it's a fine AMP page. 
If you make something that's more tailored to ampbyexample, then it could avoid the URL entry field and the AMP4ADS stuff from the get go - simpler UI, and the ampbyexample instance (installed on ampbyexample.com) could reference the images / css on that host, or perhaps there's some other way that is relatively easy to make it work for the examples.
As for non-amp source entered by a user (with potentially arbitrary javascript etc.), it may be a useful thing to disable the preview if there's an amp error. This would catch some of the mess if there's misplaced arbitrary javascript, but for security it may still be good to run it on a domain which doesn't have interesting cookies to steal or other ways to cause grief. May want to consult with a security engineer for it.
There are some minor unfortunate things with the error messages / warnings below the viewport. Currently, clicking something there doesn't necessarily scroll the error location into view. Also, a user may not notice that there's an error list view below - especially if it's a warning. Even if the scrolling was fixed, it's a bit complex to have two levels of scrolling... multiple tabs (source / errors / preview) might fix that. But note that this error list is primarily useful for lengthy documents - those where the errors can't be easily spotted inline in the editor. For ampbyexample this may be a non-issue, so perhaps such an example viewer is fine with only the inline display of errors.
So I think you can get some better experience by separating what's used for ampbyexample vs. the current use case. Perhaps it can be the same code (useful also if others want to make such example pages), just something that you configure / deploy separately for your needs.

**Comment by powdercloud** [comment]
I had not thought of the similarity to jsbin. Checking it out though, it doesn't have a way to fetch some arbitrary page, so people need to copy/paste it themselves. So I think it's more geared toward the example case in the first place - people may be using it to pare down something / play with it a bit so they can better explain / demo it to others. I can easily agree that a preview is important for this use case.
The few features that validator.ampproject.org handles thus far work on any AMPHTML page, and it's primarily useful for reading the errors and resolving them. A preview is less important here.
I see your point about people wanting to use it more like they use jsbin and fetching an example from elsewhere.
But I think this could be done at a later time so that you don't have as much pressure now smoothing out the UI. E.g., if you don't need a list of errors for your use case, and if validator.ampproject.org doesn't have the preview, no need to worry about adding tabs or similar stuff. :-)

**Comment by sebastianbenz** [comment]
Fair enough. Will move the preview to ABE then. Thanks!

**Comment by tomayac** [comment]
@sebastianbenz We used the Playground at an [event](https://twitter.com/tomayac/status/1012354220484382722) yesterday, and people were **extremely productive** as they had a full AMP development environment at their hands. 👏

* The biggest pain point was advanced debugging. Would it be possible to expose a **console**, where people could debug their code and run things like `AMP.printState()`? This feature alone would be killer.

* Another cool feature to have would be a way to **export code** to GitHub Gists for example, so they could keep their code and not risk losing it by accidentally closing the tab.

* And a final feature request: integrate with **Firebase hosting**, so people can proudly share their code to the external world and take home a real website.

Happy to open individual issues if this makes your life easier. Thanks!

**Pull request closed without merging**
