### PR TITLE
✨ Implement clear action for AMP form

### LINKED ISSUE #7368: amp-form auto submit: option/action to reset form/inputs
Given a form which auto-submits a text input:

```
  <form id="todo"
        method="POST" 
        action-xhr="/advanced/todo/add" 
        target="_blank"
        on="submit-success:todos">
    <input type="text" name="todo" on="change:todo.submit">
  </form>
```
It'd be great if there'd be a way to clear the input field on successful form submit. 

Please also see comments in https://github.com/ampproject/amphtml/issues/7688 regarding possible approaches for this issue.

### PR DESCRIPTION
**Pull request by dev-drprasad**
This feature adds `clear` action for `amp-form`.

When clear action triggered
 * initial form values will be loaded
 * validation classes will be removed
 * any content shown by `submit-success` and `submit-error` events will be hidden

Closes #7368

### CODE REVIEW

**Comment by dev-drprasad** [comment]
Hey guys, I am unable make some test cases pass. can someone help ?

**Comment by aghassemi** [comment]
/to @cvializ: PR for the GFI  #7368

**Comment by aghassemi** [comment]
@dev-drprasad The test is failing due to lint issues and is not an actual test failure.
```
32:3  error  'ShowFirstOnSubmitValidator' is defined but never used. Allowed unused vars must match /AmpElement|Def|Interface$/  no-unused-vars
```

You can run `gulp lint` locally to catch these errors ahead of time

**Comment by dev-drprasad** [comment]
@cvializ @aghassemi In tests, i am unable to mock form validations. i tried for hours but no luck. i added comments in `test-amp-form.js` to describle what i am trying to do. can someone take a look ?

**Comment by aghassemi** [comment]
@dev-drprasad Looking at the other tests that use `checkUserValidityAfterInteraction_`, they also do `setReportValiditySupportedForTesting(false);` at the beginning of the test.

**Comment by cvializ** [comment]
hey @dev-drprasad! were you able to use @aghassemi's suggestion to make the tests work?

**Comment by dev-drprasad** [comment]
@cvializ @aghassemi `setReportValiditySupportedForTesting(false);` didn't have any effect. I used `getFormValidator` function to get validator and `validator.report()` to trigger validity messages.  If you see test cases, i am using `validationMessage` (which is span element) to show message. While I am debugging **ONLY** (breakpoints in browser with `--watch` arg)  `validationMessage` has expected className: `visible`. if i just run plain `gulp test`, `validationMessage` has  
 **NO** className `visible`

**Comment by cvializ** [comment]
I noticed it passes in the normal DOM case, but fails in the Shadow DOM case, but the Shadow DOM  case passes when it is run by itself

**Comment by dev-drprasad** [comment]
I have no idea about why we are doing shadow DOM and normal DOM testing. How should i make shadow DOM tests to pass ?

**Comment by cvializ** [comment]
AMP documents run in more than one context, as standalone documents as well as embedded documents in ShadowDOM. The ShadowDOM case is a little different, but you can debug it the same way, by stepping through and seeing where values don't line up with what they should be.

**Comment by cvializ** [comment]
Excellent investigation, I'm glad you discovered that. Can you change 

https://github.com/ampproject/amphtml/blob/b5a5741e2298a86e878d4ad99095c6134269536a/extensions/amp-form/0.1/form-validators.js#L77-L78

to
```js
/** @const @protected */
this.doc = this.ampdoc.getRootNode();
```

I think that will fix the error in the test.

**Comment by cvializ** [comment]
It turns out that that was only part of the solution. The test also needed to

1. Create the AmpForm instance only after adding the necessary attributes to the form element
2. Use the `createAmpForm` function to attach the form element to the sandbox document instead of the top level document

This was great, @dev-drprasad thanks for your help. We should be able to merge this once the Travis build succeeds!

**Comment by dev-drprasad** [comment]
@cvializ I could not get time to look into it. Thanks for helping me out.

i tried to remove one comment and ended up in conflict. any way i fixed them. i will be good if you once again

**Comment by cvializ** [comment]
Looks good!

**Comment by cvializ** [comment]
Thanks again for implementing and testing this feature! I hope you found contributing to AMP useful and that you'll consider contributing in the future : )

**Pull request merged**
