### PR TITLE
🐛Build scrollbar URL with access source in amp-access-scroll

### PR DESCRIPTION
**Pull request by dbow**
Uses the `buildUrl()` method on access source to construct the scrollbar URL instead of building it manually.

### CODE REVIEW

**Comment by dbow** [comment]
cc @kushal

**Comment by dbow** [comment]
cc @dvoytenko thanks!

**Comment by dvoytenko** [comment]
Looks like this needs to be rebased.

**Comment by dbow** [comment]
@dvoytenko on it!

**Comment by dbow** [comment]
@dvoytenko fixed the merge conflict but can't get this visual test to re-start (seems to be an intermittent failure? though i don't have access to that percy project to see any details...)

**Comment by dbow** [comment]
@dvoytenko i think we're all good to go here!

**Pull request merged**
