### PR TITLE
[amp-story] Fix share link bug

### PR DESCRIPTION
**Pull request by estherkim**
Fixes https://github.com/ampproject/amphtml/issues/24334 and adds an e2e test for Chrome and Firefox (along with the ability to type ctrl+v)

### CODE REVIEW

**Comment by estherkim** [comment]
Thanks! Here you can manually test it too.
https://storage.googleapis.com/amp-test-website-1/amp_dist_63710/examples/amp-story/helloworld.html

**Comment by estherkim** [comment]
@Enriqe are the sharing options in a bookend only visible on mobile?

**Comment by Enriqe** [comment]
Yep!

**Comment by estherkim** [comment]
Phew! Way to sneakily add a tiny feature request :) Added e2e mobile support on Chrome and a bookend e2e test.

FYI mobile emulation is only supported by Chrome for now, so no bookend test on Firefox. I could do something hacky like make the webdriver press the responsive mode shortcut but figured I hold off until geckodriver includes some kind of support. @rsimha can you take another look re: e2e changes?

**Pull request merged**
