### PR TITLE
Resume validator tests by using bazel 5

### LINKED ISSUE #38610: Unskip `validator-cpp` tests
Tests started failing on main after bazel released a new stable version.  We should either
- fix tests to use bazel v6
- install bazel v5

logs from https://app.circleci.com/pipelines/github/ampproject/amphtml/26724/workflows/5c629962-c3da-49fa-9d79-e4eb8bdb3021/jobs/558498
```
validator-tests.js Running amp validator-cpp...
[16:24:35] Using task file project/amp.js
[16:24:35] Starting 'validator-cpp'...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Elapsed time: 6.456s
INFO: 0 processes.

Exited with code exit status 1
```

related - https://github.com/ampproject/amphtml/pull/38608
cc/ @ampproject/wg-caching

### PR DESCRIPTION
**Pull request by antiphoton**
Fix #38610

### CODE REVIEW

**Review by amaltas — APPROVED** [review]

**Review by estherkim — APPROVED** [review]

**Comment by antiphoton** [comment]
@estherkim
The `percy/amphtml` test is flaky and failing. Please review the visual diff. I don't have the permission the review it in `percy.io`.

**Comment by estherkim** [comment]
> @estherkim The `percy/amphtml` test is flaky and failing. Please review the visual diff. I don't have the permission the review it in `percy.io`.

Done!

**Comment by estherkim** [comment]
Hi @antiphoton - looks like validator tests fail on main. Is Bazel installed correctly?

https://app.circleci.com/pipelines/github/ampproject/amphtml/26972/workflows/b06e6a83-8de3-43f4-bd83-e83dd6153bfc/jobs/564933

**Comment by estherkim** [comment]
another ping @antiphoton, @amaltas - a failure on main is blocking nightly cuts, which will prevent a new beta for next week's release cycle.

This possibly wasn't working before merging. I don't see `amp validator-cpp` being run in this PR's checks :/ that's on infra for missing the build target
https://app.circleci.com/pipelines/github/ampproject/amphtml/26964/workflows/78253ef9-8f46-45c2-a6ac-ddd7b8df12f4/jobs/564510

**Pull request merged**
