### PR TITLE
Validator Roll-up

### PR DESCRIPTION
**Pull request by Gregable**
Changes affecting PASS/FAIL:
 - Disallow slashes in data- attribute names, for example `<p data-foo/bar="baz">`.
 - Disallow unparseable URL values in URL() functions inside CSS.
 - Allow upper case data-video-id and data-ui-highlight attr values for `<amp-dailymotion>` 
 - Allow upper case data-color attr values for `<amp-soundcould>` 
 - Allow `<link rel=mask-icon>`, 2nd attempt, requires https URL for href value.
 - Explicitly (rather than implicitly through parser) allow attributes of form "foo=foo" when the spec requires that the attribute value is an empty string. No-op in practice.

Changes improving error messages
 - Emit a deprecation warning for pages using the old boilderplate syntax.
 - Change errors referring to 'author stylesheet' to 'style amp-custom'
 - Reference "tag 'foo' " rather than " 'foo' tag" for easier translations.
 - Many spec URL references moving from github to ampproject.org.
 - Add the tagname to STYLESHEET_TOO_LONG error format strings.
 - invalid CSS at rules now read "@import" instead of "import" in the error messages
 - layouts error messages now distinguish between "implied" and "explicit" layouts.

Also includes some minor refactorings.

### CODE REVIEW

**Comment by Gregable** [comment]
@powdercloud @honeybadgerdontcare for author consent acks.

**Comment by powdercloud** [comment]
@googlebot I consent.

**Comment by honeybadgerdontcare** [comment]
@googlebot I consent.

**Comment by powdercloud** [comment]
@Gregable I checked that new test files were added, so no worries about that.

**Pull request merged**
