### PR TITLE
🗑Remove googleanalytics-alpha

### LINKED ISSUE #13336: Remove googleanalytics-alpha config in vendors.js
It was introduced for a opt-in launch #5761. Since it's now fully launched #9497 we should be able to remove it.

/cc @rudygalfi @jasti

### PR DESCRIPTION
**Pull request by calebcordry**
This was an early version that is now deprecated. `googleanalytics` (non-alpha) is fully launched.

Closes #13336

### CODE REVIEW

**Comment by calebcordry** [comment]
Oops, I had some exclusions on my search. Good catch. I think I got them all now.

**Comment by kyle-wright** [comment]
@calebcordry This PR remove Krux vendor configuration. Can you fix this: https://github.com/ampproject/amphtml/pull/16763/files#diff-43075fef96144a4f898edb8d18aae69aL1066

**Comment by kyle-wright** [comment]
@calebcordry @zhouyx @lannka Would one of you add back in the krux vendor configuration or should I submit a PR?

**Comment by lannka** [comment]
woops, that was a terrible mistake. let me do a quick PR.

**Pull request merged**
