### PR TITLE
✅  Add integration test for placeholder line-height

### PR DESCRIPTION
**Pull request by caroqliu**
Note that this test failed prior to #32280:
image

### CODE REVIEW

**Comment by caroqliu** [comment]
@ampproject/wg-infra Is there a way to restart this hanging part of the build status? 
image

**Comment by estherkim** [comment]
That's strange, I don't recognize those checks. Can you try merging master to restart it?

**Comment by rsimha** [comment]
> That's strange, I don't recognize those checks. Can you try merging master to restart it?

Those are the GitHub Actions checks. I recently cleaned up their names (which used to mention node 12 even though LTS has moved on from 12). And Esther is correct about merging master.

**Comment by caroqliu** [comment]
Merging master worked, thank you @estherkim @rsimha

**Review by kristoferbaxter — APPROVED** [review]

**Review by dvoytenko — APPROVED** [review]

**Pull request merged**
