### PR TITLE
Update csa.md to remove beta language

### PR DESCRIPTION
**Pull request by mmcao**
Removing beta language since this functionality is used broadly and not subject to whitelisting.

### CODE REVIEW

**Comment by nainar** [comment]
Pinging @zhouyx for review.

**Comment by zhouyx** [comment]
@mmcao LGTM. However in order to merge this PR, could you please fix the dead link in the doc.
image

**Comment by nainar** [comment]
Pinging @mmcao for next action.

**Comment by cvializ** [comment]
Updated the docs and deferred the link update for #19207 to fix

**Pull request merged**
