### PR TITLE
🐛 Web push: service worker messenger command typo

### PR DESCRIPTION
**Pull request by gudzdanil**
Fix typo for web push service worker messenger command

### CODE REVIEW

**Comment by sebastianbenz** [comment]
LGTM. Thanks for cc'ing me. Need to fix the typo in ABE as well.

**Comment by prateekbh** [comment]
@sebastianbenz can you actually Approve the PR

**Comment by mrjoro** [comment]
@prateekbh @dvoytenko does this PR need further review or can it be merged?

**Comment by prateekbh** [comment]
I am yet to look into web push stuff so I'll ask @dvoytenko to take a look plz

**Pull request merged**
