### PR TITLE
Fork amp-story to 1.0

### PR DESCRIPTION
**Pull request by newmuis**

### CODE REVIEW

**Comment by gmajoulet** [comment]
If you don't want to ruin your contributions metrics you can specify a fake commit author :)

**Comment by newmuis** [comment]
Yeah, next step is to figure out how to get git to hint this against the original to keep history

**Comment by newmuis** [comment]
Within a single PR, doing a move from 0.1=>1.0 and then copying back from 1.0=>0.1, GitHub is smart enough to still consider this a no-op within 0.1 and a copy from 0.1 to 1.0.

I will do this as two separate PRs:
1. Move 0.1 to 1.0.
2. Copy 1.0 back to 0.1.

**Comment by gmajoulet** [comment]
LGTM!

**Comment by calebcordry** [comment]
Cool! This is a problem I've had with github before. Now I know :)

**Comment by newmuis** [comment]
This branch got both out of date and messed up 😄  it's faster for me to replay these changes in a separate PR, which I will send when ready

**Comment by newmuis** [comment]
See #14420

**Pull request closed without merging**
