### PR TITLE
✅ 🐛 Expect more errors in unit tests

### PR DESCRIPTION
**Pull request by rsimha**
Partial fix for #14406
Partial fix for #16076

### CODE REVIEW

**Comment by rsimha** [comment]
/to @lannka 

This clears up a few dozen console errors.

**Comment by rsimha** [comment]
I don't think this can be committed as is, as some (likely async) tests are not getting executed when run in isolation. See https://travis-ci.org/ampproject/amphtml/jobs/393874465#L702

@lannka @zhouyx Either of you know what's going on here?

**Comment by zhouyx** [comment]
to @lannka who owns the cid api : )

**Comment by rsimha** [comment]
@lannka Ping

**Comment by rsimha** [comment]
Merged this. Other async issues can be fixed in a separate PR.

**Pull request merged**
