### PR TITLE
removed buggy resize option in renderStart-method

### PR DESCRIPTION
**Pull request by adtechnology**
we have to remove this quickly till the bug is fixed

### CODE REVIEW

**Comment by jridgewell** [comment]
Re: https://github.com/ampproject/amphtml/issues/5608. @lannka should be working on the root cause.

**Comment by lannka** [comment]
Working on a global fix.

**Comment by lannka** [comment]
Will be fixed in #5795

**Comment by jridgewell** [comment]
Closed by #5795.

**Pull request closed without merging**
