### PR TITLE
Revert "amp-fit-text: extract buildDom #compiler"

### PR DESCRIPTION
**Pull request by samouri**
Reverts ampproject/amphtml#35101, due to issues found in visual regression tests ([link](https://percy.io/ampproject/real-world-pages/builds/11358899/changed/638244626?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=411&widths=375%2C411)).

### CODE REVIEW

**Comment by processprocess** [comment]
cc @kristoferbaxter for OWNERS

**Comment by processprocess** [comment]
I'm checking this out locally and it looks broken when running [this link](www.axios.com/border-democrats-migrants-vaccinated-44abf3d7-10ad-43b6-82b2-e0443df80db5.html) through the proxy.

I tried git bisect and am finding that [#34770](https://github.com/ampproject/amphtml/pull/34770) could be the problem. Can you double check this?

**Review by kristoferbaxter — APPROVED** [review]

**Review by alanorozco — CHANGES_REQUESTED** [review]
Like @processprocess, I believe the regression is not reverted here, since it was introduced by `10a30ba`.

**Comment by samouri** [comment]
Welp, I totally reverted the wrong commit. I am sorry for all of the lost cycles!
New revert: https://github.com/ampproject/amphtml/pull/35146

**Pull request closed without merging**
