### PR TITLE
Relatively drastically improve FCP for docs with a hidden body.

### PR DESCRIPTION
**Pull request by cramforce**
This change allows AMP to make the body visible before the resource pipeline initializes. This results in a significant improvement in FCP. The change is, however, effectively a no-op when `macro-after-long-task` is off, because without the resource init continues to execute within the same macro as the rest of AMP's initialization.

This change may

- Regress other perf metrics, because certain JS execution and hence network requests are now delayed by a paint
- Should not improve FCP on pages that have their boilerplate removed
- May regress FID because the user may be enticed to click earlier when init code is still running.
- There is a change in how `first-viewport-ready` is calculated. Previously the code relied on resource discovery running early, now it always waits until the discovery code ran at least once.

The actual functional change is:

```js
    // Schedule initial passes. This must happen in a startup task
    // to avoid blocking body visible.
    startupChunk(this.ampdoc, () => {
      this.setupVisibilityStateMachine_(this.visibilityStateMachine_);
      this.schedulePass(0);
    });
```

Everything else are just hacks to get bad assumptions in tests fixed.

Idle-thought: Chunk.js and pass.js need to merge!!! #24109

Before
Screen Shot 2019-08-21 at 7 46 31
After
Screen Shot 2019-08-21 at 7 46 18

Notice how the second screenshots shows a rendered page much earlier

### CODE REVIEW

**Comment by cramforce** [comment]
@dvoytenko @kristoferbaxter Should we do this?

**Comment by cramforce** [comment]
One alternative would be to remove the `1` and instead wrap the call in `startupTask`. That might be better and would effectively guard it by the macro-task experiment.

**Comment by dvoytenko** [comment]
@cramforce this looks good to me.

**Comment by cramforce** [comment]
@kristoferbaxter @choumx Please review

**Comment by cramforce** [comment]
@jridgewell `isInputPending` cannot be polyfilled. But, yeah, we basically want to debounce our work queues if `isInputPending` is true.

**Comment by cramforce** [comment]
@jridgewell #24109

**Comment by rsimha** [comment]
This PR broke unit tests on `master`: https://travis-ci.org/ampproject/amphtml/builds/575034978
PR check from yesterday was green: https://travis-ci.org/ampproject/amphtml/builds/574516335

Perhaps a breaking change was merged in the intervening time?

**Comment by cramforce** [comment]
Yeah, must have been an intervening change. Revert here
https://github.com/ampproject/amphtml/pull/24127

**Pull request merged**
