### PR TITLE
Clarify how amp-anim is different from amp-img

### PR DESCRIPTION
**Pull request by dandv**
The original description was this:

> The `amp-anim` component is very similar to the `amp-img` element, and provides additional functionality to manage loading and playing of animated images such as GIFs.

> The `amp-anim` component can *also* have an optional placeholder child, to display while the src file is loading.

This suggests that `amp-anim` has some other functionality to "manage loading and playing of animated images". However, no other functionality in addition to `amp-img` is documented afterwards, except the placeholder. If the placeholder is indeed the only difference from `amp-img`, then the proposed shortened paragraph should make this clearer.

### CODE REVIEW

**Comment by jridgewell** [comment]
Please rebase to fix Travis.

**Comment by bpaduch** [comment]
After some investigation, it appears that the really distinguishing difference is the "controls" attribute, which is allowable on amp-anim but not amp-img (and isn't documented).  Granted, I have no idea when/how you'd have an animated image with controls (suggestions?).  You can easily display an animated gif using amp-img, and in fact, have a placeholder, so it begs the question, why do we have amp-anim? @dvoytenko - can you provide clarification?

**Comment by cramforce** [comment]
Yes, @dvoytenko is the right person. My understanding is that the main point here is, having a good placeholder that isn't 8MB big and which can be used to avoid showing the anim when the image is off screen.

**Comment by dvoytenko** [comment]
@dandv @cramforce Yes, I'd really like to stress that placeholder should be lightweight, given that the GIFs themselves are usually pretty big.

@bpaduch No idea about `controls` :) No such attribute is supported at this time. Though I suppose something like this could make sense, combined with a possible `autoplay`. But as it stands - no.

Thus, the difference currently is really performance thing. If we could pause animation for GIF, we'd do that. But for now, `amp-anim` allows us to reduce CPU usage and GPU vetoing when it's off screen.

**Comment by dandv** [comment]
If `amp-img` supports a placeholder just as `amp-anim` does, and the only benefit of `amp-anim` is that it can reduce CPU/GPU usage, this suggests that the difference between the two is an implementation detail. 

If `amp-img` could figure out that it's displaying an animation and reduce CPU usage when that animation is off-screen, would that make `amp-anim` unnecesary?

**Comment by dandv** [comment]
Gah, sorry for the [git mess](http://ohshitgit.com/).

**Comment by dvoytenko** [comment]
I'll wait for rebase before reviewing. But to answer the question: being able to tune animated vs non-animated image would definitely make a less case for `amp-anim`. But semantically, it's different enough that I think the separate component may still be desirable. E.g. one could imagine controls or behavior to pause/resume animation, etc.

**Comment by dandv** [comment]
@dvoytenko please see #8493.

**Pull request closed without merging**
