### PR TITLE
Expose computeInMasterFrame to custom ad iframes.

### LINKED ISSUE #1875: Expose 'computeInMasterFrame', so custom JS in remote.html can leverage it.
Publisher or 3rd parties want the ability to do work only once in the master iframe instead of across all ads. e..g Ability to update Krux data when a user is visiting the site for the first time.    #1815 allows to do this within a component but need the ability to do so for 3rd party code in remote.html

### PR DESCRIPTION
**Pull request by cramforce**
Fixes #1875

### CODE REVIEW

**Comment by cramforce** [comment]
@jasti Please take a look!

**Comment by jridgewell** [comment]
:shipit:

**Comment by jasti** [comment]
LGTM, Thank you!

**Comment by jasti** [comment]
cc @kashyapnitin

**Pull request merged**
