### PR TITLE
amp-ad integration - ucfunnel add new parameter

### PR DESCRIPTION
**Pull request by ucfunnel**

### CODE REVIEW

**Comment by ucfunnel** [comment]
@googlebot

**Comment by calebcordry** [comment]
For the CLA, looks like you are approved, but there is also a commit from an author `moonn...@gmail.com` that is not approved.

**Comment by ucfunnel** [comment]
I update the email for the CLA. How to check the CLA again?

**Comment by calebcordry** [comment]
@googlebot

**Comment by calebcordry** [comment]
I still see it failing for the commits authored by the gmail account. You can try changing the author of the commits as outlined [here](https://www.git-tower.com/learn/git/faq/change-author-name-email)

**Comment by ucfunnel** [comment]
CLA is ok. What I need to do next?

**Comment by calebcordry** [comment]
Thanks for the contribution!

**Pull request merged**
