### PR TITLE
📖 Edit teaser text for amp-addthis component

### PR DESCRIPTION
**Pull request by dlemm**
Fixes ampproject/docs#2168
edit the teaser text to "Displays AddThis’ customizable social share buttons."

### CODE REVIEW

**Comment by torch2424** [comment]
@pbakaus Can I merge this? 😄

**Comment by pbakaus** [comment]
Yep!

**Comment by torch2424** [comment]
@pbakaus Thank you! Merged 😄

Thanks for the contribution @dlemm ! 🎉

**Pull request merged**
