### PR TITLE
Run Travis tests on latest Chrome (not Chromium)

### PR DESCRIPTION
**Pull request by aghassemi**

### CODE REVIEW

**Comment by aghassemi** [comment]
Now there are 3 failing tests ( same as local, Yay! ). The form ones are fixed in #5835

I am looking at `'MANDATORY_CDATA_MISSING_OR_INCORRECT head > style[amp-boilerplate]` failure.

**Comment by cramforce** [comment]
If Chrome is available that is definitely better!

**Comment by aghassemi** [comment]
@cramforce This will download and install the latest "stable" Chrome. (adds a few seconds to the whole thing but worth it IMO)

After https://github.com/ampproject/amphtml/pull/5847 and https://github.com/ampproject/amphtml/pull/5835 are merged, all tests should pass and we can switch to this new setup for Travis.

**Comment by cramforce** [comment]
SG. Glad this is now possible on Travis.

**Pull request merged**
