### PR TITLE
Prune unused deps

### PR DESCRIPTION
**Pull request by psyrendust**
* [6e9357a] chore(package): prune deps that are no longer used in package.json
* [09542af] chore(gulpfile): remove unused var argv in gulpfile
* [51196c3] fix(gulpfile): remove duplicate var declaration for fs in gulpfile

### CODE REVIEW

**Comment by erwinmombay** [comment]
@psyrendust awesome, thanks for this.

**Comment by psyrendust** [comment]
@erwinmombay Not sure why the test is failing. I made a fix for the broken `gulp dist` task here #506. I'm not sure if this is related.

**Comment by erwinmombay** [comment]
@psyrendust checking

**Comment by erwinmombay** [comment]
@psyrendust so im farely certain this is a flakey test unfortunately. do you mind submitting again?

**Comment by psyrendust** [comment]
@erwinmombay sure thing

**Comment by psyrendust** [comment]
Resubmitted as #509

**Pull request closed without merging**
