### PR TITLE
✨ ENHANCE: expand widgetOpts/logOpts

### PR DESCRIPTION
**Pull request by Minjiicho**
**Same as #39413.
Posting it again because the circleCI not run and branch name was suspected.** [(related comment)](https://github.com/ampproject/amphtml/pull/39413#issuecomment-1703473871)

- Add new option for special case
- Add backup options to deliver accurate data

### CODE REVIEW

**Review by powerivq — APPROVED** [review]

**Comment by Minjiicho** [comment]
@powerivq Not sure why CircleCI still not work 😢

**Comment by Minjiicho** [comment]
@powerivq I'm waiting for your support 🙏

**Comment by erwinmombay** [comment]
@Minjiicho where you able to rebase and re-push the changes to restart the task and it still failed?

**Comment by powerivq** [comment]
Created one https://github.com/ampproject/amphtml/pull/39442

**Comment by powerivq** [comment]
Already merged there.

**Pull request closed without merging**
