### PR TITLE
Ensure that viewport dimensions are updated when expanding/collapsing iframe

### PR DESCRIPTION
**Pull request by alanorozco**
Uses known information about the frame collapsed state. Invalidates cached rect if the viewport changes.

### CODE REVIEW

**Comment by alanorozco** [comment]
@lannka 

Just doing that would lead to an incorrect state if the viewport changes while the overlay is open. `CANCEL_FULL_OVERLAY_FRAME_REMEASURE` is not an optimization, it actually updates the state in case it's wrong.

**Comment by lannka** [comment]
Any viewport change of the host page should be sent to the iframe, even when overlay is open. Why there will be incorrect state?

**Comment by alanorozco** [comment]
Because the collapsed box rect hasn't been recalculated after the viewport change. We know what the box rect looks like when open, but not what it will look like when being collapsed again.

**Comment by lannka** [comment]
That part makes sense. But I still don't understand why host has to respond 2 separate responses, and upon receiving those responses, client remeasure twice. 

Is that an optimization because most of the time the box won't change (since we freeze the scroll), so the 2nd response is considered as a sanity check adjustment ?

**Comment by alanorozco** [comment]
Yep. If we always remeasure we're always going to skip a frame because recalculation requires a vsync pass. It's not just optimization for optimization sake, it would be bad UX since elements could jump or the change would be laggy.

**Comment by alanorozco** [comment]
@lannka PTAL

Moved the collapsed rect cache logic to host per off-thread discussion. Refactored it so it would be simpler. Even the tests are even simpler with this approach!

**Comment by alanorozco** [comment]
@lannka ping

**Comment by lannka** [comment]
Awesome! Thanks for the change.

**Pull request merged**
