### PR TITLE
amp-o2-player added consent data handling 

### PR DESCRIPTION
**Pull request by lironka**
✨ Added consent data handling to amp-o2-player

### CODE REVIEW

**Review by arielginsburg — APPROVED** [review]

**Comment by lironka** [comment]
@nainar I apologize for the urgency, but could you please merge this pr at your earliest possible convenience?

**Review by micajuine-ho — COMMENTED** [review]
Hi @lironka thank you for your PR. It looks good to me, however, I want to confirm that you did some manual testing before we merge.

**Comment by lironka** [comment]
@micajuine-ho hi! I did manual testing and it worked well.

**Review by micajuine-ho — APPROVED** [review]
Awesome! Sounds great :D.

**Comment by lironka** [comment]
@micajuine-ho  Hi! Could you, please, merge the pr? I haven't permission to do it.

**Comment by micajuine-ho** [comment]
Hi ! @lironka, can you force merge a blank/trivial commit. It seems like the Travis job is stuck/not loading, so we need to trigger it again.

Additionally, the owners check should not be an issue here, since `wg-components` is also listed as an owner, and I have given approval.

**Comment by lironka** [comment]
@micajuine-ho  HI! I updated but travis still looks as waiting. Do you know what could we do?

**Comment by micajuine-ho** [comment]
I'm not sure why this is happening. Maybe best shot is just to close this PR and open a new one...

**Comment by estherkim** [comment]
Hi @lironka, my guess is that Travis is stalling because we migrated from Travis.org to Travis.com on Oct 23, which isn't included in this branch.

Please merge this branch with HEAD for the latest Travis config and let's see how that goes.

**Comment by lironka** [comment]
@estherkim Hi! I have latest master and don't see any brach with name HEAD. What I need to do for "merge this branch with HEAD" ?

**Comment by estherkim** [comment]
Hi, what I meant was to get latest (the HEAD commit) from master and merge it to this branch. It looks like this branch was created on Oct 22 and hasn't been merged with master since. Here are the steps to merge with latest - 

https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#pull-the-latest-changes-from-the-amphtml-repository

**Comment by lironka** [comment]
@estherkim Hi! thank you I updated. But still my upstream/master has travis.org not travis.com as you mentioned

**Comment by estherkim** [comment]
Hmm, can you try creating another copy with this PR? Maybe the GitHub checks are stuck with the stale Travis config.

**Comment by lironka** [comment]
@estherkim Sorry but when I go to https://github.com/ampproject/amphtml/tree/master   I see in `.codecov.yml` the same `travis.org`. May you get a right master link?

**Comment by estherkim** [comment]
Good eye :) that's a bug, but it shouldn't affect the Travis build. Please try creating a fresh PR, thanks!

**Comment by lironka** [comment]
I close this pr due to Travis issue. I reopen  it here https://github.com/ampproject/amphtml/pull/31005

**Pull request closed without merging**
