### PR TITLE
✨Interactive size adapts to screen size with ems

### LINKED ISSUE #29897: [Story interactive] Large prompt doesn't show ellipsis with 4 lines
When using prompt-size=“large” with a text > 3 lines it is exceeding the max-height of 112px but as the line-clamp is equal to 4 it do not have the text-overflow: ellipsis
As you can see on your example: (I just change the prompt-size to large and use iPhone X view)

image

### LINKED ISSUE #29925: [Story interactive] Size components with relative units
Currently components don't scale according to the screen size, but this results in different screen sizes look different. We should scale them with the ems in order to adapt them to all screen sizes and stay more consistent.

The conversion units can be 16px = 1em. The options text in the quizzes is exactly 1em that way.

For aspect-ratio it looks good out of the box, but without aspect-ratio, grid layers increase the em so it's generally a good idea to add a rule with a root em in the components:

```css
amp-story-interactive-quiz {
    font-size: 0.8rem;
}
```

image

### LINKED ISSUE #30035: [Story interactivity] Create public documentation for new sizing strategy
Updating the sizing strategy will break WYSIWYG editors, so there will have to be a doc that can be referenced to properly size the interactive components

Also demos should be updated to match the new sizing strategy

### PR DESCRIPTION
**Pull request by mszylkowski**
Closes #29925 sizes components with ems
Closes #29897 large prompts have 3 lines instead of 4
Closes #30035 adds sizing to README.md

This change might break WYSIWYG editors

> Currently components don't scale according to the screen size, but this results in different screen sizes look different. We should scale them with the ems in order to adapt them to all screen sizes and stay more consistent.
>
> The conversion units can be 16px = 1em. The options text in the quizzes is exactly 1em that way.

The default font-size will be `3*var(--story-page-vmin)` and the width will be by default `100%` so that the component is taking 75% of the page width by default (25em). This default works out of the box, and can be easily overriden with the rules below. The image attached shows the default font-size and max-width (so components can "look" wider or narrower with a smaller font size). 3 vmin is the perfect size for the component to occupy 75% of the width of the page, so the quizzes and polls don't take up all the screen but can be clearly read.

For tool makers: We found that using font-size in ems was more consistent for changes in screen size (for pixel-perfect layouts), but you can use anything, including var(--story-page-vw), rems, px, etc. If using aspect ratio on grid layers, values around 0.8em to 1em will look appropriate. If not using aspect-ratio, values around 0.2-0.4ems will look good, because 1em=10% so that range is similar to 0.8-1rem. Keep in mind the scaling of the component will depend on the font-size value, and the width is restrained by the amp-story CSS rules, so creators have a range of valid widths. Tools should constrain the font-size to the values that will look good, since it's not trivial to understand for users the font-size adjustments in ems (tools can also restrict the component to use the default styles, or make their own size). Showing WYSIWYG components does helpif users can scale the font-size to their liking.

Updated codepens with the em sizing:
https://codepen.io/mszylkowski/pen/abNWzdb <- poll in ems
https://codepen.io/mszylkowski/pen/qBZXmQj <- quiz in ems
https://codepen.io/mszylkowski/pen/abNWzdb <- results in ems
https://codepen.io/mszylkowski/pen/oNxogoV <- binary-poll in ems

### CODE REVIEW

**Comment by newmuis** [comment]
Are `em`s definitely the right unit here?  Or should we use `rem`s?  If a publisher sets a font size on an ancestor of the interactive component, that will cause `em`s to scale according to that font size, while `rem`s will remain the same.

**Comment by mszylkowski** [comment]
From what I tried, in aspect ratio grid-layers, the layer changes the ems to match the layer size. The root ems (rems) don't work like that, which makes it inconsistent. The creators will be able to specify a different "scaling" of the component (by changing the font size), but we need to allow that, because ems are very different if there is a aspect-ratio than if there isn't, so each tool will have to specify a font-size on the components if they want to scale it with the screen.

I tested doing "font-size:1rem" which sets 1em=1rem and it doesn't scale properly.

Check the demo at https://stampinteractivitybackend.web.app/examples/amp-story/interactive_size.html to see how ems work.

**Comment by newmuis** [comment]
Yeah, I think it's almost like we would want `em` if we are setting the font size for aspect ratio layers, but `rem` otherwise, right?

**Comment by gmajoulet** [comment]
I still need to review your documentation and code, but I don't think we should end up expecting publishers to size components in `em`s. I understand how it makes sense from a technical point of view, but we should come up with one more layer of abstraction so publishers don't have to know that internally we're using ems.

Ems are relative to the font-size so if a publisher sets a different default font-size it'll change the sizing of the component and they won't know why.

My suggestion, and it might be naive because I have a lot less context than Matias so correct me if I'm missing something:
- We should let publishers size the component in px or % (or em if they want to)
- We should retrieve the component's dimensions on render (`this.getLayoutBox()` from `buildCallback()`), and set our own `em` size from that, plus override the font-size to 16px to protect our component from publishers defaults

**Comment by mszylkowski** [comment]
Two main issues with it:
- We restrict how people can use the component: Resizing the screen will break the layout if we calculate the font-size from the width, as the width can change depending on how it's calculates. Tools that show previews in different phone sizes will not update properly.
- Creators can't make the components more narrow or wide (within the boundaries of 14em and 25em) because the component will change the font-size based on the width. 

Also, currently the component overrides the font-size to 3% of the vmin, so publishers _need_ to set a class on the component that overrides that in order to customize the font-size, it's not easy to break by default. Can explain more offline

**Comment by gmajoulet** [comment]
> Resizing the screen will break the layout

There's an AMP runtime callback that tells you when your component is resized, so this should be trivial.

I'm sorry but I feel extremely strongly that we should not create a new HTML/CSS standard here, and stick to the way all other AMP components and HTML elements work.

Publishers should be able to do `.quiz {height: 35%; width: 20%;}`, and not have to do hacky maths to derive the height from the font-size, height of the screen and the length of their quiz prompts/options.

**Review by gmajoulet — APPROVED** [review]
Can you add an example in the "sizing" part of the documentation?

**Comment by mszylkowski** [comment]
@gmajoulet 
Updated the Codepen links to the ones that use ems, adding binary-poll and polls.
Also added some content on the Sizing section (+updated what we had), and a code example with a screenshot of how to do the aspect-ratio layer.

**Pull request merged**
