### PR TITLE
🏗 Re-added simple Visual Diff Tests for amp-consent

### PR DESCRIPTION
**Pull request by torch2424**
relates to #20999
relates to #20783

This re-adds visual diff tests for amp-consent. They were reverted due to a PR conflict with changes made by @danielrozenberg that got pulled in before the amp-consent PR got merged. Therefore, this just needed to update the `verifyCssElements` to `verifySelectorsVisible`. 😄

### CODE REVIEW

**Comment by danielrozenberg** [comment]
Looks like the visual diff test run failed on this PR? Did you try running it locally?

**Comment by torch2424** [comment]
@danielrozenberg Yes I did, and it worked then. It is quite odd it is not working now. I will investigate 😄

**Comment by zhouyx** [comment]
@torch2424 I remembered you also did visual test after user hit accept, which I couldn't find in the PR. Can we add that back? Thank you

**Comment by torch2424** [comment]
@zhouyx They should be there! I think it may be the percy interface hiding them? 😄 

@danielrozenberg So I've tried pulling in master a few times, building a few different times, and it's saying it still can't find the selector, even though it works on my machine 😢 I'll ping you Monday (or vice versa) if you have the time to help me figure this out?

**Comment by danielrozenberg** [comment]
I'm not sure exactly what's going on, but it failed for me locally just like it did on Travis. I'm assuming you're on a Mac? Maybe there are browser version differences (on mine the headless browser that executes the tests is is Chromium 71.0.3563.0)

I did however manage to fix the tests, although I don't understand what difference my changes made behind the scenes. Basically, I removed all special handling of `localStorage` from the test's js file - since #20671 there's no need to reset the local storage anymore, because each test runs on a separate subdomain (`1.localhost:3000`, `2.localhost:3000`, etc…) and thus aren't sharing their `localStorage` object.

Here's the simplified fixed version: https://gist.github.com/danielrozenberg/f18f2ce5b6bcc472efbe88bea7e5948e

Feel free to copy & paste it into this PR verbatim :)

**Comment by torch2424** [comment]
@danielrozenberg 

> I'm not sure exactly what's going on, but it failed for me locally just like it did on Travis. I'm assuming you're on a Mac? Maybe there are browser version differences (on mine the headless browser that executes the tests is is Chromium 71.0.3563.0)

Ah, I'm on Chrome 72, maybe that causes an issue? 🤔 

> since #20671 there's no need to reset the local storage anymore, because each test runs on a separate subdomain (1.localhost:3000, 2.localhost:3000, etc…) and thus aren't sharing their localStorage object.

And for the localStorage, I had a feeling that might be causing it. And, I thought that as well, but then I assumed that localstorage would persist through test runs. So in the case that a consent test happens to run on the same `1.localhost:3000` on the next run, I thought this might be carried over. But perhaps chrome headless wipes this before being launched? Is my concern valid?

> Feel free to copy & paste it into this PR verbatim :)

I did exactly that, thanks for doing that. It is much appreciated. Sorry this is taking so long on my end 😂

**Comment by torch2424** [comment]
Oops, forgot this my vidual diff pr. Showed @zhouyx offline, and they approve 😂

**Pull request merged**
