### PR TITLE
🚀 Reduce Development Output in mjs build

### PR DESCRIPTION
**Pull request by kristoferbaxter**
Removes more branches for development codepaths when served as `mjs` output.

### CODE REVIEW

**Comment by kristoferbaxter** [comment]
@jridgewell Similar to before, we are allowing Closure Compiler to perform removal of codepaths instead of adding the functionality to the Babel transform.

Post-Babel, before Closure
```javascript
const test = false;
const localDev = false;
const minified = true;
const development = false;
getMode().development = false;

function foo() {
  if (getMode().development = false) {
    return false;
  }
}

function bar() {
  if (false == false) {
    return false;
  }
}

getMode().development = development;
```

After Closure Compiler (even simple mode)
```javascript
var test = !1,
  localDev = !1,
  minified = !0,
  development = !1;
getMode().development = !1;
function foo() {
  getMode().development = !1;
}
function bar() {
  return !1;
}
getMode().development = development;
```

Closure eliminates the unreachable codepaths.

Would you prefer we add this into the Babel pipeline?

**Comment by jridgewell** [comment]
Raghu's gotten rid of the closure that eliminates the `getMode` calls.

But why are you assigning to `getMode` to begin with? That's not how it's intended to be used. It's a ready-only config object.

**Comment by kristoferbaxter** [comment]
> But why are you assigning to getMode to begin with? That's not how it's intended to be used. It's a ready-only config object.

The codebase uses this, without handling it our babel passes does not execute correctly, it replaces an LVal with a Boolean Literal.

**Comment by erwinmombay** [comment]
@kristoferbaxter this would make `test` and `localDev` false during tests correct? if so i'd need to modify this a little bit so that it takes into account the `--fortesting` flag once this is in so that it can work with esm integration tests

**Comment by kristoferbaxter** [comment]
@jridgewell Updated based on offline conversation. Disabled test that was assigning values to `getMode().development`.

**Comment by kristoferbaxter** [comment]
@erwinmombay This doesn't run on `test` and `localDev` builds, additionally I flagged this to only run on the ESM output with #dc5680f.

**Pull request merged**
