### PR TITLE
Remove experimental flag from amp-access-laterpay

### PR DESCRIPTION
**Pull request by trodrigues**
As mentioned in #9300 this removes the experimental flag for the amp-access-laterpay extension.

### CODE REVIEW

**Comment by dvoytenko** [comment]
@trodrigues  But if you'd like, we can launch much faster via flags.

**Comment by trodrigues** [comment]
@rudygalfi hi there. Not sure what @dvoytenko meant with the launch via flags. Can we possibly get this merged some time this week?

**Comment by jridgewell** [comment]
He means we can turn on the experiment without removing the experiment code. This means it would be testable next week, if you can submit the PR today.

**Comment by trodrigues** [comment]
Ah, right I see.

Well, I don't think that would be really necessary. We've tested this enough that we'd be comfortable with having the experimental flag removed now. Would there be any other conditions necessary to have it removed?

**Comment by jridgewell** [comment]
Just @rudygalfi's approval.

**Comment by trodrigues** [comment]
Thanks! So to be clear this should go into the dev channel next week, and all being well the week after into the live release, correct?

**Comment by jridgewell** [comment]
Yup.

**Pull request merged**
