### PR TITLE
🚀 Appnexus prebid server callout respect multisize

### PR DESCRIPTION
**Pull request by dbemiller**
Adds `data-multi-size` support to the Prebid Server RTC endpoint.

Improves the chance for Prebid ads to match the sizes defined by the `amp-ad` tag.

### CODE REVIEW

**Comment by bradfrizzell** [comment]
Your travis errors look spurious to me, restarting your build. Please ping for merge when everything is green

**Comment by mkendall07** [comment]
@bradfrizzell can you restart them again. Still not passing and I don't think they are related. Do we need to rebase?

**Comment by bradfrizzell** [comment]
boooo!!!! blegh sorry about this. Travis has been a nightmare lately. yea I'd try rebasing against current head and pushing again

**Comment by bradfrizzell** [comment]
please ping me again here or on slack if it doesn't pass after that and I'll handle it

**Comment by mkendall07** [comment]
@dbemiller try a rebase.

**Comment by dbemiller** [comment]
@bradfrizzell no such luck :(. The integration tests failed with some unrelated timeouts.

Also odd: although the unit tests passed, the output includes a section with some errors and instructions to fix...

> Console errors: Expand this section and fix all errors printed by your tests.

...but the test passed anyway. Not sure what that's about... but they don't look likely to be caused by this change either.

**Comment by bradfrizzell** [comment]
Damn this is ridiculous, sorry about this purgatory you are stuck in. Have you recently angered an ancient god? I'm going to restart the tests and see if they pass. They have been very flaky lately and it seems like you're getting the worst of it.

**Comment by bradfrizzell** [comment]
hooray that worked! I'll get this merged.

**Comment by dbemiller** [comment]
@bradfrizzell thanks!

**Pull request merged**
