### PR TITLE
show-tooltip validation

### PR DESCRIPTION
**Pull request by Enriqe**
Partial for #26666

Adds validation for new `has-tooltip` attribute in `<a>` tags.

To be merged after #27752 hits production.

### CODE REVIEW

**Comment by honeybadgerdontcare** [comment]
@Enriqe I'm not a fan of `has-tooltip` as the name of the attribute because that implies a binary value for it, either `true` or `false`. Looking at #26666 it appears it has three possible values: `true`, implicit `false` and `auto`. Were other names considered to differentiate this from being a binary value and what it really is trying to do, e.g. `use-tooltip` or `display-tooltip`?

**Comment by Enriqe** [comment]
@honeybadgerdontcare that is a valid concern. I will make the change for it to be called `show-tooltip`, which was the name @dvoytenko proposed earlier in the discussions.

**Comment by gmajoulet** [comment]
Is this ready to be merged?

**Comment by Enriqe** [comment]
Not yet, since #27752 hasn't hit prod yet.

**Comment by newmuis** [comment]
I don't think we necessarily need to wait for that to hit prod; if it is valid before the code change goes in, it's just a no-op.

**Pull request merged**
