### PR TITLE
[DO NOT SUBMIT] Always use the global sinon instance

### LINKED ISSUE #5570: Why is restore routine not being triggered?
See this PR: https://github.com/ampproject/amphtml/pull/5568

All tests pass...

### PR DESCRIPTION
**Pull request by jridgewell**
This is so we can ensure sandboxes are always cleaned up. Let's see if
there's any flake with this before submitting.

Fixes #5568.
Fixes #5570.
Reverts #3087.

### CODE REVIEW

**Comment by dvoytenko** [comment]
LGTM. I don't remember why we originally had an issue and were importing `* as sinon` everywhere. If tests path - let's do this.

**Comment by mkhatib** [comment]
We sure this wouldn't cause the same problem that the reverted PR was solving? Please force-push to trigger travis to run.

**Comment by jridgewell** [comment]
I can't cause the error the original PR was solving, and there's no linked issue so I don't have any context for what went wrong.

**Comment by mrjoro** [comment]
This was a DNS but marked approved; is it still active?

**Comment by jridgewell** [comment]
I'll update and merge. If the flake comes back, we can revert.

**Comment by dvoytenko** [comment]
Too old. Closing.

**Pull request closed without merging**
