### PR TITLE
Add ability to AB test Sortable <amp-ad> against Google (adsense/dfp).

### PR DESCRIPTION
**Pull request by Rooke**
- Can now AB test sortable against doubleclick and adsense tags.
- Use data-ab-type to specify test type, and data-ab-pct to specify probability of using alternate tags.

### CODE REVIEW

**Comment by lannka** [comment]
@Rooke general question:
so who is the user of this A/B testing thing? is it publisher or sortable? How would they have a A/B side by side report based on your current implementation?

**Comment by Rooke** [comment]
The idea behind this PR is to allow publishers to compare adsense or dfp to our implementation in the most fair manner possible. Doing the split test in our own javascript would incur unavoidable latency.

In most cases Sortable ("we") would be performing the test for the publisher, in the sense that the dfp/adsense account being compared to would be managed by us. Sortable would be doing all the reporting in that case. However, this method allows a pub to traffic an ad unit _not_ controlled by us alongside one of ours - they don't need to rely solely on our reporting in this scenario.

Another reason for the structure of this test is to maintain backwards compatibility with our "normal" `<amp-ad>` specification.

Aside: there's a delay on our end with the CLA signing. Rest assured I know it needs to happen.

**Comment by lannka** [comment]
If you are managing the experiments on behalf of pub, you can also use the [amp-experiment extension](https://github.com/ampproject/amphtml/blob/master/extensions/amp-experiment/amp-experiment.md) for such an A/B experiment, instead of making a temporary code change.

Please take a look and see if that meets your needs.

**Comment by SpLouk** [comment]
@lannka it looks to me like you can only test aesthetic changes with these tags, is this not the case?

**Comment by lannka** [comment]
@SpLouk `amp-experiment` offers the ability to control CSS, which means you can use `display: none` to show one of the competing content.

**Comment by Rooke** [comment]
`<amp-experiment>` works beautifully, thanks bringing it to our attention @lannka

**Pull request closed without merging**
