### PR TITLE
Skip testing for PR builds and non-lockfile push builds on greenkeeper branches

### PR DESCRIPTION
**Pull request by rsimha-amp**
`greenkeeper` branches are currently tested on Travis four times.

1. PR build for `package.json` update
2. Push build for `package.json` update
3. PR build for `yarn.lock` update
4. Push build for `yarn.lock` update

The only case in which we need to run all the AMP tests is case 4 above.

This PR skips testing in cases 1, 2, and 3. The pre and post script steps that actually update the lockfile will be run normally.

This will reduce test time from ~20 min to ~1 min in cases 1, 2, and 3, , thereby reducing the overall Travis CPU usage

### CODE REVIEW

**Comment by cramforce** [comment]
Shouldn't this be possible to configure in .travis.yml / Travis settings? I thought the `branches->only` only option did that.

**Comment by rsimha-amp** [comment]
@cramforce We'd like to run push builds on `greenkeeper/*` branches, but not PR builds. Removing [this entry](https://github.com/ampproject/amphtml/blob/master/.travis.yml#L35) from `branches->only` will stop running push builds on greenkeeper branches. See https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches

The Travis docs do not mention a way to specify that push builds be run for a particular branch, but not PR builds for PRs from that branch to `master`.

**Comment by erwinmombay** [comment]
says in https://docs.travis-ci.com/user/conditional-builds-stages-jobs/ that you can do `if: type IN (push, pull_request)` (we can remove `pull_request` from the IN check)

**Comment by rsimha-amp** [comment]
That's promising, @erwinmombay :)

**Comment by rsimha-amp** [comment]
@erwinmombay @cramforce PTAL.

**Comment by rsimha-amp** [comment]
Bumping this.

**Comment by rsimha-amp** [comment]
@cramforce @erwinmombay From testing, it turns out that if a build is conditionally skipped, `continuous-integration/travis-ci/pr`, which is a required check, fails with the message `The Travis CI build could not complete due to an error`, and blocks the PR from being merged. Therefore, we can't conditionally cancel greenkeeper PR builds. I'm going to have to go back to my `pr-check.js` logic to skip all testing.

**Comment by rsimha-amp** [comment]
Tested this on an actual `greenkeeper` branch with push and PR builds, using lockfile and non-lockfile commits.

**Non-lockfile commits:**
**PR:** https://travis-ci.org/ampproject/amphtml/jobs/334940226#L1656 (skipped)
**Push:** https://travis-ci.org/ampproject/amphtml/jobs/334940209#L1672 (skipped)

**Lockfile commits:**
**PR:** https://travis-ci.org/ampproject/amphtml/jobs/334943871#L1665 (skipped)
**Push:** https://travis-ci.org/ampproject/amphtml/jobs/334943858#L1660 (run)

**Pull request merged**
