### PR TITLE
🚮 Delete mode-object.js

### PR DESCRIPTION
**Pull request by rcebulko**
It looks like `getModeObject` was once DCE'd ([by Java code?](https://github.com/ampproject/amphtml/commit/c648488c6e3041a166b5de540577c833bddd91a6)), but since we now a) DCE some with our own transform and b) use a compiler that DCE's automatically for these boolean functions, `getModeObject` no longer serves much of a purpose.

### CODE REVIEW

**Review by jridgewell — CHANGES_REQUESTED** [review]
The DCE's we've implemented don't perform the same when the property isn't statically known. Eg, `modeObject()` proxies `mode().localDev`. The `mode().localDev` can be replaced easily.

When we change `modeObject()` to `getMode()`, all of the properties have to come along, and none of them will be DCE'd.

**Comment by samouri** [comment]
@jridgewell: mode-object is only used in a single place, and that single place currently uses all of the properties.

**Comment by rcebulko** [comment]
> The DCE's we've implemented don't perform the same when the property isn't statically known. Eg, `modeObject()` proxies `mode().localDev`. The `mode().localDev` can be replaced easily.
> 
> When we change `modeObject()` to `getMode()`, all of the properties have to come along, and none of them will be DCE'd.

@jridgewell I believe you are thinking of `getMode()`. It appears `modeObject` is very old, and originally was the only thing DCE'd, but eventually became `getMode()` and `modeObject` itself isn't used anywhere, as Jake describes above.

**Review by samouri — COMMENTED** [review]
Will give approval when CI is happy

**Comment by jridgewell** [comment]
> It appears modeObject is very old, and originally was the only thing DCE'd, but eventually became getMode() and modeObject itself isn't used anywhere, as Jake describes above.

This isn't correct. `modeObject` was created to prevent people from doing `const mode = getMode(); mode.foo`. Because `mode` was stored as an object, and that object was used as the base of property access, it prevented any DCE from applying. So, we made `modeObject`, which internally was just

```js
return {
  foo: getMode().foo,
  bar: getMode().bar,
}
```

Now, `modeObject`'s property values can be DCE'd into simple `true`/`false`/etc. We expect people to use all the properties of `modeObject`, but its value definitions still need to be DCE'd.

**Comment by rcebulko** [comment]
> > It appears modeObject is very old, and originally was the only thing DCE'd, but eventually became getMode() and modeObject itself isn't used anywhere, as Jake describes above.
> 
> This isn't correct. `modeObject` was created to prevent people from doing `const mode = getMode(); mode.foo`. Because `mode` was stored as an object, and that object was used as the base of property access, it prevented any DCE from applying. So, we made `modeObject`, which internally was just
> 
> ```js
> return {
>   foo: getMode().foo,
>   bar: getMode().bar,
> }
> ```
> 
> Now, `modeObject`'s property values can be DCE'd into simple `true`/`false`/etc. We expect people to use all the properties of `modeObject`, but its value definitions still need to be DCE'd.

@jridgewell `modeObject` is not used anywhere, and we use a lint rule to ban assigning `getMode()` to anything.

**Comment by jridgewell** [comment]
> modeObject is not used anywhere, and we use a lint rule to ban assigning getMode() to anything.

You've done exactly this in this PR:

https://github.com/ampproject/amphtml/pull/35688/files#diff-b1c76d981cd2ede6089ea1fe47fd9775483c750430e6cafe44a337c159c53de2R73

This will drag all the code form `getMode`, without any of the DCE.

**Comment by rcebulko** [comment]
> You've done exactly this in this PR:
> 
> https://github.com/ampproject/amphtml/pull/35688/files#diff-b1c76d981cd2ede6089ea1fe47fd9775483c750430e6cafe44a337c159c53de2R73
> 
> This will drag all the code form `getMode`, without any of the DCE.

So inlining an object with the properties here will suffice?

**Comment by rcebulko** [comment]
> This will drag all the code form `getMode`, without any of the DCE.

Also, curious why this assignment wasn't caught and also why the bundle size didn't meaningfully change anywhere

**Comment by jridgewell** [comment]
> So inlining an object with the properties here will suffice?

Yup.

> also why the bundle size didn't meaningfully change anywhere

🤷

**Comment by samouri** [comment]
> > This will drag all the code form `getMode`, without any of the DCE.
> 
> Also, curious why this assignment wasn't caught and also why the bundle size didn't meaningfully change anywhere

I think its because we do most of our DCE at the function level now instead of the amp-mode-transformer

**Comment by samouri** [comment]
🏓 , I still think this is worth merging

**Review by jridgewell — APPROVED** [review]
Checking the diff, it appears the DCE is working properly at the `getMode()` level, which is probably because of us switching from transforming the object accesses into the extracted static methods.

```diff
--- a	2021-08-31 11:56:19.000000000 -0400
+++ b	2021-08-31 11:56:27.000000000 -0400
@@ -1,23 +1,16 @@
-if (z.__AMP_MODE) var E = z.__AMP_MODE;
+if (z.__AMP_MODE) var O = z.__AMP_MODE;
 else {
   var p = qa(z) || qa(z);
   p =
     ['1', 'actions', 'amp', 'amp4ads', 'amp4email'].includes(
       p.development
     ) || !!z.AMP_DEV_MODE;
-  L || (L = (null == (E = z.AMP_CONFIG) ? void 0 : E.v) || '01' + H());
-  E = z.__AMP_MODE = {
+  K || (K = (null == (O = z.AMP_CONFIG) ? void 0 : O.v) || '01' + E());
+  O = z.__AMP_MODE = {
     localDev: !1,
     development: p,
     esm: !1,
     test: !1,
-    rtvVersion: L,
+    rtvVersion: K,
   };
 }
-E = {
-  localDev: !1,
-  development: !1,
-  esm: !1,
-  test: !1,
-  rtvVersion: E.rtvVersion,
-};
```

**Pull request closed without merging**
