### PR TITLE
[WIP] turn on collapseProperties

### PR DESCRIPTION
**Pull request by erwinmombay**

### CODE REVIEW

**Comment by erwinmombay** [comment]
continuing discussion on this PR. ads.min and everything.min looks good.

**Comment by jridgewell** [comment]
Can you post a gist of v0.js and some random extension?

**Comment by erwinmombay** [comment]
@jridgewell so i didnt run v0.js through the collapseProps since something definitely broke, do you want the version that would have been ran through collapse properties?

**Comment by erwinmombay** [comment]
@jridgewell https://gist.github.com/erwinmombay/75c6e289554b7317728f54673b3bb902

contains amp-audio.js and a v0.js transpiled with collapse properties turned on.

**Comment by erwinmombay** [comment]
really interesting to see in amp-audio, it *looks* like the timer module is duplicated.

**Comment by erwinmombay** [comment]
@jridgewell https://gist.github.com/erwinmombay/f4d47e29bde0d391082b88866c28a2b0 slightly hard to read with the prefixes

**Comment by erwinmombay** [comment]
@jridgewell with labels off https://gist.github.com/erwinmombay/d2eb139399cc6c6a96fbb8545b8534e6

**Comment by cramforce** [comment]
Will be interesting to take a deeper look when I have some time. A page
that has just v0.js in it and nothing else, what is the error message?

**Comment by erwinmombay** [comment]
@cramforce so looking at everything.amp.min.html (and ads.min) with a v0.js that has collaps-props on, i don't see any errors, but its failing on travis consistently with a disconnect (see latest build) and i haven't been able to replicate the same error locally yet but that might also just be because I haven't been able to get a green local test run in a long time now.

**Comment by cramforce** [comment]
Better than expected :)

**Comment by erwinmombay** [comment]
@cramforce closing this in favor of https://github.com/ampproject/amphtml/pull/2972

**Comment by erwinmombay** [comment]
reopening just for travis testing/debugging

**Pull request closed without merging**
