### PR TITLE
🏗 Run unit tests on Firefox

### LINKED ISSUE #6039: Run unit tests on more browsers
Currently unit tests only run on latest Chrome and Chrome 45, we need to run them on more browsers, ideally all the browsers that run integration test. Unfortunately unit tests are so fined tuned to Chrome that making them run on all SauceLabs browsers will be a big task. Instead let's slowly fix them for different browser.

- [x] Remove `--oldchrome` (SL_Chrome_45)
- [x] Introduce `saucelabs-lite`, this will be a subset of SauceLabs browsers where unit test runs are stable and pass (Initially it can just include ~~SL_Chrome_45~~ SL_Chrome_latest)
- [x] Fix unit tests for Safari latest and add it to `saucelabs-lite`
- [ ] Fix unit tests for Chrome Android and add it to `saucelabs-lite`
- etc...

/cc @erwinmombay thoughts?

### PR DESCRIPTION
**Pull request by rsimha**
This PR runs a large number of core runtime unit tests on Firefox (in addition to Safari, where they're already enabled).

Follow up to #11827
Fixes #6039

### CODE REVIEW

**Comment by rsimha** [comment]
@aghassemi I see [numerous failures](https://travis-ci.org/ampproject/amphtml/jobs/535519727#L1987) on Firefox, but [all passing tests](https://travis-ci.org/ampproject/amphtml/jobs/535519727#L2224) on Chrome (Windows).

Do you see any value to running unit tests on Chrome (Windows) in addition to Chrome (Linux)? If not, we should abandon this PR.

**Comment by aghassemi** [comment]
@rsimha I can't think of any benefits in doing both window and linux Chrome.

**Comment by rsimha** [comment]
> @rsimha I can't think of any benefits in doing both window and linux Chrome.

In that case, I'll attempt to enable a subset of unit tests on Firefox.

**Comment by rsimha** [comment]
**Update:** Enabled ~3800 of the core runtime unit tests on Firefox.



Will merge this once Travis is green.

**Pull request merged**
