### PR TITLE
amphtml-validator: Add --user-agent option and default user agent.

### PR DESCRIPTION
**Pull request by JulienPalard**

### CODE REVIEW

**Comment by JulienPalard** [comment]
I signed it!

**Comment by powdercloud** [comment]
Thank you, this is cool.
I do not like the version in there. Reason being, there is already a versioning for amphtml-validator and it's different (https://www.npmjs.com/package/amphtml-validator). So I think this could add confusion. Further, there is some versioning that could make sense for validator.js itself, but we're not yet exporting or using that. This could be meaningful for amphtml-validator users down the road, but it'd be something in the output, not something to include in the user agent, probably. Anyway if we can avoid introducing another version number it'd be nice. If for some reason we must have a version in the user agent string I'd prefer just hard coding it to something that never changes, rather than making it some variable of its own.
Other than this, I think unfortunately I made some conflicting change since you submitted this PR, maybe try to resolve this. It shouldn't be hard. Sorry about this.

**Comment by JulienPalard** [comment]
@powdercloud I removed the version in the user agent, as it's not mandatory to have one, and resolved the conflict.

I won't remove or use the other versionning of amphtml-validator in this pull request, as it's a whole another issue.

**Comment by powdercloud** [comment]
Thanks a lot.

**Comment by powdercloud** [comment]
I will try to merge this as soon as our Travis test passes. I restarted it, I think the failure has nothing to do with your PR so it's likely going to be fine.

**Comment by powdercloud** [comment]
Just wanted to say the NPM package (https://www.npmjs.com/package/amphtml-validator) now has this feature. Thank you.

**Pull request merged**
