### PR TITLE
Renaming toggle to toggleVisibility because it was conflicting with sidebar and breaking it

### PR DESCRIPTION
**Pull request by aghassemi**
Sidebar registers an action named `toggle` therefore we can not register `toggle` as a global action and not break backward compatibility. Renaming to `toggleVisibility`

/to @alanorozco 
/cc @muxin Needs to be merged before Canary Cut

### CODE REVIEW

**Comment by alanorozco** [comment]
Could we potentially consider an implementation that allows elements to override a global action?

**Comment by aghassemi** [comment]
@alanorozco that's a good idea. let me see if I can implement that approach instead.

**Comment by aghassemi** [comment]
@alanorozco @dvoytenko Alright I tried to provide a way for elements to override global actions that work in 99.9% of the cases but has a race condition that is not acceptable IMO. Details and implementation in this PR: https://github.com/ampproject/amphtml/pull/7912

Having a feature to allow overriding global actions by elements aside, I still like to proceed with this PR for a different reason:

Although `toggle` is a nice symmetric name to complement `hide` and `show`, it is still too generic and its meaning is derived based on the element it is acting on. For instance, it makes a lot of sense to add a `toggle` function to `accordion` to `toggle` between expanded/collapsed states, but that nothing to do with toggling visibility. So `toggleVisibility` as the global action is more clear and explicit.

**Comment by alanorozco** [comment]
@aghassemi Makes sense.

**Comment by dvoytenko** [comment]
@aghassemi @alanorozco I think in reality, the risk condition would be triggered much more often. It'd be nice, I agree. But since we can't know whether or not the element overrides an action until it was fully downloaded, this might be too prohibitive.

**Pull request merged**
