### PR TITLE
Moving the story desktop system layer buttons.

### LINKED ISSUE #17631: Desktop share button label overflows
The desktop share button label overflows in some languages.
The container has a fixed width that doesn't work for all languages.

image

### PR DESCRIPTION
**Pull request by gmajoulet**
- Removing the sharing pill
- Moving the system layer buttons to the top right corner of the screen
- Removing the localization ID

[Screenshot](https://user-images.githubusercontent.com/1492044/53057813-d5dc0280-347e-11e9-911e-9888ce8dfb50.png)

Fixes #17631

### CODE REVIEW

**Comment by Enriqe** [comment]
YES

image

**Comment by Enriqe** [comment]
Can you also please remove the parts where we disable the share-pill for the visual tests, since they were flaking?

e.g.

https://github.com/ampproject/amphtml/blob/ef29b1327b723d6d88b49d9fd0ec4cc77ba043c2/examples/visual-tests/amp-story/amp-story-page-attachment.html#L27-L35

**Comment by gmajoulet** [comment]
Oh, thanks! Done.

**Comment by gui-poa** [comment]
Hi, all! Is this feature on production?

Im still seeing the share string instead the icon.

**Comment by gmajoulet** [comment]
This feature is part of this week's release to production, which should happen today or tomorrow.

**Pull request merged**
