### PR TITLE
add tests for expr removal in closure compiler

### PR DESCRIPTION
**Pull request by erwinmombay**

### CODE REVIEW

**Comment by erwinmombay** [comment]
@cramforce this does fail on the `i++` increment case

**Comment by mrjoro** [comment]
@erwinmombay it looks like this was approved but not merged; is that intentional?

**Comment by jridgewell** [comment]
The tests fail, we need to fix the compiler.

**Comment by nainar** [comment]
Closing this PR as inactive. Please reopen if needed.

**Pull request closed without merging**
