### PR TITLE
🏗🚀 Enable concurrency for multi-pass `gulp dist` on Travis

### PR DESCRIPTION
**Pull request by rsimha**
Travis recently upgraded us to premium VMs on a trial basis. This PR experiments with increased concurrency for multi-pass `gulp dist` on Travis. Let's see what performance increase we get as a result of this.

### CODE REVIEW

**Comment by estherkim** [comment]
Just curious, what are premium VMs?

**Comment by rsimha** [comment]
> Just curious, what are premium VMs?

This isn't documented. I had to reach out to Travis to ask :)

**Regular:** 7.5 GB of RAM and 2 cores
**Premium:** 15 GB of RAM and 4 cores

Looks like the combination of premium VMs + increased concurrency has lowered the running time of multi-pass `gulp dist` from [~10 mins](https://travis-ci.org/ampproject/amphtml/jobs/606151505#L513) to [~5 mins](https://travis-ci.org/ampproject/amphtml/jobs/606194747#L543).

I'll ask about making our upgrade permanent before merging this PR.

**Comment by estherkim** [comment]
Nice, that would be awesome.

**Comment by rsimha** [comment]
Yay, we're upgrading to premium. I'll merge this PR once tests are green.

**Pull request merged**
