### PR TITLE
🖍 amp-social-share: update brand colors for facebook and pinterest

### PR DESCRIPTION
**Pull request by Jessman5**

### CODE REVIEW

**Comment by Jessman5** [comment]
I signed it!

**Comment by cathyxz** [comment]
Thanks a lot for this! I think you've branched off a broken build--sorry. Would you mind merging or rebasing latest master?

**Comment by Jessman5** [comment]
damn, sure. Thank you

**Comment by Jessman5** [comment]
Hmm @cathyxz I'm sorry, I'm on master and it seems to be up to date, since there's nothing to pull.
Latest master I can get is Commit 391a43181 and this is where I branched off.

**Comment by Jessman5** [comment]
@cathyxz my branch is now up to date.

**Pull request merged**
