### PR TITLE
[amp-story] ♿ Make pause/play buttons keyboard focusable

### LINKED ISSUE #32508: amp-story: Make play/pause button focusable on mobile UI
# Timing not adjustable

## WCAG Level
Level A

## Priority
High

## Pages/screens/components affected
* [Navigation](https://www.gstatic.com/amphtml/stamp/qa/navigation.html)
* [Video](https://www.gstatic.com/amphtml/stamp/qa/video.html)
* [Audio - amp-story-page background audio](https://www.gstatic.com/amphtml/stamp/qa/audio-page.html)
* [Audio - amp-story using amp-audio](https://www.gstatic.com/amphtml/stamp/qa/amp-audio.html)
* [Prerender - Video](https://www.gstatic.com/amphtml/stamp/qa/prerender-video.html?amp_js_v=0.1#origin=https://www.google.com&prerenderSize=1&visibilityState=prerender&paddingTop=0&p2r=0&horizontalScrolling=0&csi=1&aoh=15526927198732&viewerUrl=https://www.google.com&history=1&storage=1&cid=1&cap=swipe,navigateTo,cid,fragment,replaceUrl)

## Description
Content or functionality that relies on a time limit can be problematic for users, as they may not have sufficient time to read/operate a page or to carry out a specific task.

Any process or functionality that happens without being explicitly triggered by the user, after a set time or on a periodic basis, counts as a time limit. This includes partial or full updates of content (for example, a page refresh, being automatically logged-out of an ongoing session), changes to content, or the expiration of a window of opportunity for a user to react to a request for input. It also includes content that is auto-advancing or updating. In other words, animated, moving or scrolling content can also introduce a time limit on a users ability to read, understand, and operate content.

Whenever there is a time limit, users must be able to turn off, adjust, or extend the timeout (unless the timeout is essential, relates to a real-time event, or is longer than 20 hours).

Authors can define auto-advancing for pages in their AMP stories. After a set amount of time, a story advances to the next page.

On large screen/desktop, the "Pause" control in the top-right corner can be used to pause the auto-advancing.

An AMP story with auto-advancing pages in large-screen/desktop view, with the 'Pause' control highlighted

However, in the small-screen/smartphone sized version, there is no "Pause" control visible. Desktop users that have sized/zoomed their browser window to a small-enough size to trigger the "smartphone" view have no way of pausing the video with their mouse or keyboard. The same problem applies to users on an actual smartphone that are using an external mouse or keyboard.

The same auto-advancing page in small-screen/smartphone view - the 'Pause' button is not present in this view

Touchscreen users are able to pause the auto-advancing in the small-screen/smartphone view by pressing and holding on the page itself. While arguably this passes the requirement of having a method to "turn off" auto-advancing, this is - subjectively - not a good approach, as it forces users to keep their finger pressed on the touchscreen, just to be able to read/view the content without it disappearing from view.

## User impact
Time limits can affect all users, but users with disabilities (including, but not limited to, users of assistive technologies) are likely to find them particularly problematic. User who are blind, have low vision, have mobility or dexterity impairments, and users with cognitive disabilities may require more time to read content or to perform functions such as filling out on-line forms. Time limits may prevent them from successfully reading content or completing tasks, making a site unusable for them.

## Required solution
Make sure that on both large and small screen view, there is a method for users keyboard, mouse, and touch users to pause any auto-advancing behaviour.

This solution must be applied to all instances of the issue identified within the test sample, then applied to all other instances of the same issue identified throughout the rest of the website.

## Test procedure(s)
Use these steps to confirm that the solution has been correctly applied to issues identified within the test sample, and to test the rest of the website for instances of the same issue:
1. Verify if the page contains any auto-advancing behaviour.
2. Verify that there is a mechanism for users (using mouse, keyboard, touch) to pause the auto-advancing.

### Definition of done
Complete all of these tasks before closing this issue or indicating it is ready for retest:
* All issues identified within the test sample have been resolved.
* The rest of the website has been tested for the same issue.
* All issues identified throughout the rest of the website have been resolved or filed as new issues.

## Related standards
* [WCAG 2.1 Success Criterion 2.2.1 Timing Adjustable (Level A)](https://www.w3.org/TR/WCAG21/#timing-adjustable)

## Test data
Test date: January 2021

### PR DESCRIPTION
**Pull request by Enriqe**
Closes #32508

Makes pause/play buttons in the system layer focusable via keyboard.

It uses the `amp-mode-keyboard-active` AMP CSS class to display the button when the keyboard is active.

Outdated comments before 87fed97f4c594e63ccaf0281a238eb02d82fae63:
* Buttons cannot be focused if they are `display: none` or `visibility: hidden`, so we have to render them and hide them another way.
* The other two options to hide the buttons is using `opacity` or `width`. I tried using `opacity: 0` initially, but it would create an empty space between the other buttons in the system layer.
* Modifying the `width` is usually frowned upon since it causes CLS and negatively impacts performance. Alternative would be to use a `transform: scaleX(0)`, but it would still create the space between the other buttons.

### CODE REVIEW

**Review by Samerrr22 — APPROVED** [review]

**Comment by gmajoulet** [comment]
> Modifying the width is usually frowned upon since it causes CLS and negatively impacts performance.

There is no shift if the content is rendered with the correct width, are you saying there's a layout shift with your implementation? We need to get the initial render right.
From reading the code I don't think there's any shift. If there is please look into other ways to get the element out of the CSS flow, such as `position: absolute`.

Deferring to @processprocess for the review

**Comment by processprocess** [comment]
Let's also check `amp-mode-keyboard-active` in addition to focus.
That way it will stay visible after keyboard interaction.

I think using `width` is okay since we're not animating it.

**Comment by Enriqe** [comment]
@processprocess thanks for the suggestion on using `amp-mode-keyboard-active `, it actually simplifies the CSS this way.

I did have to add some code in order for the system layer to be able to read that CSS class in the shadow DOM:
1. Add a mutation observer in amp-story to listen for mutation in classes inside the `<body>` element.
2. Update the store for the relevant state update.
3. If the desired CSS is modified, update the shadow CSS.

PTAL

**Comment by processprocess** [comment]
> I did have to add some code in order for the system layer to be able to read that CSS class in the shadow DOM

Looks good to me. As we discussed, with @newmuis, if we find that we need to pass other classes to the shadow dom element, having a helper that appends classes from an allow list could work. For now I think this is implementation is good though!

**Review by processprocess — APPROVED** [review]

**Comment by gmajoulet** [comment]
Can the play/pause button be focused by a screen reader? If not, can you re-open the ticket please?

**Pull request merged**
