### PR TITLE
update `babel-plugin-transform-amp-asserts` with `devAssert` removal.

### PR DESCRIPTION
**Pull request by erwinmombay**
Currently the transformer does not remove `devAssert` (we should leave `userAssert`'s alone).

### CODE REVIEW

**Comment by erwinmombay** [comment]
@jridgewell @rsimha PTAL

**Comment by rsimha** [comment]
From the single pass [failure logs](https://travis-ci.org/ampproject/amphtml/jobs/560848125#L393), I see two issues:

- Closure is complaining while DCEing the remnants of the `assert` removals
- It appears that paths are being needlessly duplicated. For example, `ads/google/a4a/ads/google/a4a/utils.js`

**Comment by erwinmombay** [comment]
@rsimha could you explain what you mean by "It appears that paths are being needlessly duplicated. For example, ads/google/a4a/ads/google/a4a/utils.js" ?

**Comment by rsimha** [comment]
> @rsimha could you explain what you mean by "It appears that paths are being needlessly duplicated. For example, ads/google/a4a/ads/google/a4a/utils.js" ?

The path should be `ads/google/a4a/utils.js` (the `ads/google/a4a` prefix is duplicated)

**Comment by mrjoro** [comment]
Is this PR still active?

**Comment by rsimha** [comment]
@jridgewell @erwinmombay Today, `AmpPass.java` eliminates all these calls:

https://github.com/ampproject/amphtml/blob/d7f334983a093feef4f59bbc6ee2af33359ec8eb/build-system/runner/src/org/ampproject/AmpCommandLineRunner.java#L43-L56

Does this PR remove all of them? If not, are there plans to do so?

**Comment by jridgewell** [comment]
They're all eliminated.

**Comment by rsimha** [comment]
> They're all eliminated.

When I tried removing `AmpPass.java, the number of instances of `assert` in `v0.js` jumped from 20 to ~80.  I don't think `assertElement`, etc. are being removed.

**Comment by jridgewell** [comment]
Open an issue, please.

**Comment by rsimha** [comment]
> Open an issue, please.

#23960

**Pull request merged**
