### PR TITLE
Add support for Nielsen Analytics

### PR DESCRIPTION
**Pull request by uniquelygeneric**
In reference to ampproject/amphtml issue [#3337.](https://github.com/ampproject/amphtml/issues/3337)

### CODE REVIEW

**Comment by rudygalfi** [comment]
/to @avimehta 

@uniquelygeneric You'll need to squash the commits at some point.

**Comment by erwinmombay** [comment]
@rudygalfi no longer a requirement to squash the commits to get it merged

**Comment by avimehta** [comment]
@erwinmombay can you start the tests again? The failure is unrelated to this PR.

**Comment by erwinmombay** [comment]
@uniquelygeneric can you fetch the latest from our master again and rebase? had a bad test that should be fixed now

**Pull request closed without merging**
