### PR TITLE
🏗Upload Sauce Labs logs when disconnection failures occur (temporary, for debugging)

### PR DESCRIPTION
**Pull request by rsimha**
This PR carries out the debugging instructions in https://github.com/ampproject/amphtml/issues/28343#issuecomment-628083572.

- Enables `extendedDebugging: true` for Chrome VMs on Sauce
- Adds `uploadSauceConnectLog()` to `pr-check/utils.js`
- Uploads `sauce_connect_log` with extended debugging to external storage when a disconnection error is detected

**Next steps:** Let this run for a few days and pull up logs for disconnection failures

/cc @wswebcreation

### CODE REVIEW

**Comment by wswebcreation** [comment]
@rsimha 

Thanks, can you also provide the links of the SL jobs?

Last but not least, I'm trying to find what failed here, but, or I'm missing something, I can't figure out why the job failed

**Comment by rsimha** [comment]
@wswebcreation I've started off a new Travis build [here](https://travis-ci.org/github/ampproject/amphtml/builds/687086199). The Sauce labs job with tunnel ID 74919.10 should start in a few minutes, after which I'll post a link.

> Last but not least, I'm trying to find what failed here, but, or I'm missing something, I can't figure out why the job failed

As mentioned in https://github.com/ampproject/amphtml/issues/28343#issuecomment-628092335, the job failed even though the tests passed because we were printing the verbose sauce connect logs. Travis terminates any job that prints logs larger than a certain size.

**Comment by rsimha** [comment]
@wswebcreation Tests have run. Tunnel ID: `18e5036b46b04feeb574a69883d64ad9`. Identifier `74919.10`. Sauce logs: [here](https://app.saucelabs.com/tests/bae2e216ec8040158d751e2ed69f4dea).

**Comment by wswebcreation** [comment]
Hi @rsimha 

Thanks for the logs, the problem now is that it's hard to debug, because it's not failing, can 
- we trigger this a few times to see when the jobs are failing on Sauce Labs
- get the Sauce Labs job if the job is failing

Thanks!

**Comment by rsimha** [comment]
@wswebcreation I've modified this PR to upload the logs instead of printing them (since printing will fail Travis because the logs are too long).

Once reviewed, I'll merge this PR and keep an eye on future builds and send you a link to an example where the disconnection failure does occur. Stay tuned.

**Comment by rsimha** [comment]
Luckily, the [Travis check](https://travis-ci.org/github/ampproject/amphtml/jobs/687581857#L2448) for this PR failed in the way we were hoping. So I'm going to hold off on merging, and see what @wswebcreation is able to find out from the logs.

**Tunnel info:**

Tunnel ID: `689d7336f79d4deca411382a075bd88a`, Identifier: `75029.10`

image

**Disconnections:**

image

**Sauce connect log:**

[sauce_connect_log_75029.10.zip](https://github.com/ampproject/amphtml/files/4637195/sauce_connect_log_75029.10.zip)

**Comment by wswebcreation** [comment]
@rsimha 

A new version of the karma-sauce-launcher has been released, some stuff under the hood has changed, can you check with that version if all works stable now?

**Comment by rcebulko** [comment]
> A new version of the karma-sauce-launcher has been released, some stuff under the hood has changed, can you check with that version if all works stable now?

I'll put a test PR together

**Pull request closed without merging**
