### PR TITLE
✨ [amp-ad smartadserver] Define type of the call to ad-server(sync or async) 

### PR DESCRIPTION
**Pull request by EmetsAr**
The change allow to define what type of call to ad-server should be executed: sync or async

### CODE REVIEW

**Comment by EmetsAr** [comment]
Hi @powerivq Can you take a look at this pull request? You already reviewed the old one(https://github.com/ampproject/amphtml/pull/38363) with the same changes, but we closed it due to some internal reasons

**Comment by powerivq** [comment]
@EmetsAr looks good. However, IemetsAR also needs to sign the CLA for this PR to be merged.

**Comment by EmetsAr** [comment]
@powerivq I see that PR is approved(CLA is signed as well :)  but I still can't merge it. Should I do something more to do it?

**Comment by powerivq** [comment]
@EmetsAr Can you rebase your PR against the latest main? The build is probably failing for this reason. Once passed we will merge it.

**Comment by EmetsAr** [comment]
> @EmetsAr Can you rebase your PR against the latest main? The build is probably failing for this reason. Once passed we will merge it.

@powerivq done, the PR updated with the latest changes from main

**Pull request merged**
