### PR TITLE
📖 Update amp-brightcove.md document update url Brightcove's support documentation

### LINKED ISSUE #40032: AMP redirect not working (for BRIGHTCOVE)
### Description

To whom it may concern:
I am Shantal Ahumada, a Senior Learning Specialist at Brightcove. 

I have received tickets related to this documentation from you: https://amp.dev/documentation/components/amp-brightcove

Your link, **'Brightcove's support documentation,' leads to a non-existent document** (see the attached image below).

**The correct link is this: https://player.support.brightcove.com/amp/amp-using-video-cloud-video.html**

_Please update your documentation to avoid confusion and streamline both products' operations._

I appreciate any help you can provide. 
I send a cordial greeting, and I am at your disposal in the following mail: s.ahumada@brightcove.com
image

### Reproduction Steps

Page:
https://amp.dev/documentation/components/amp-brightcove 

### Relevant Logs

_No response_

### Browser(s) Affected

Chrome

### OS(s) Affected

_No response_

### Device(s) Affected

_No response_

### AMP Version Affected

_No response_

### PR DESCRIPTION
**Pull request by Shahindavoodicom**
editing the non-existent document url for Brightcove's support documentation
it fixes #40032

### CODE REVIEW

**Comment by erwinmombay** [comment]
thanks @Shahindavoodicom for the fix

**Comment by powerivq** [comment]
@Shahindavoodicom Can you rebase against latest main to fix the build?

**Comment by powerivq** [comment]
@Shahindavoodicom Gentle ping

**Comment by erwinmombay** [comment]
i went ahead and forked this and kept the author intact https://github.com/ampproject/amphtml/pull/40158

**Comment by powerivq** [comment]
Merged https://github.com/ampproject/amphtml/pull/40158

**Pull request closed without merging**
