### PR TITLE
change transport types for top100-analytics

### PR DESCRIPTION
**Pull request by arealit**
Closes https://github.com/ampproject/amphtml/issues/11406

### CODE REVIEW

**Comment by arealit** [comment]
I signed it!

**Comment by arealit** [comment]
Fixed commit's author

**Comment by zhouyx** [comment]
@arealit Is this a bug, or the server deprecate the support for `beacon` and `xhrpost`? Asking because these two are preferred over `image`.

**Comment by arealit** [comment]
@zhouyx there is no bug, just the server doesn't have full support for beacon and posts from amp

**Comment by zhouyx** [comment]
@arealit Please rebase to master to fix the travis and percy failure. Thanks

**Comment by arealit** [comment]
@zhouyx rebased

**Comment by zhouyx** [comment]
@erwinmombay Could you help force merge this PR please? googlebot fail to update the CLA status : (

**Comment by arealit** [comment]
Rebased master

**Pull request merged**
