### PR TITLE
Limit saucelabs concurrent browsers launched

### PR DESCRIPTION
**Pull request by muxin**
related to https://github.com/ampproject/amphtml/issues/9030
trying out solving saucelabs disconnected issue

### CODE REVIEW

**Comment by muxin** [comment]
@jridgewell I'm not sure whether this will help. Do you know how I can trigger the saucelabs test before merging to master?

**Comment by jridgewell** [comment]
What is the default concurrency?

**Comment by muxin** [comment]
infinity

**Comment by muxin** [comment]
FYI https://github.com/karma-runner/karma/pull/1646

**Comment by erwinmombay** [comment]
lol infinity

**Pull request merged**
