### PR TITLE
Add Pinterest extension

### PR DESCRIPTION
**Pull request by kentbrew**
Adding amp-pinterest. This extension should build most variations of the Pin It button and all Pinterest widgets, including embedded pins, boards, and user profiles. Please see docs for important notes about iframe sizing.

### CODE REVIEW

**Comment by kentbrew** [comment]
We have pin counts through CORS. Now considering building at least the embedded pin widget inline.

**Comment by kentbrew** [comment]
Hey, neat. I've forgotten how to use GitHub. Today I pushed two commits to the pinterest branch on pinterest/amphtml:

https://github.com/pinterest/amphtml/tree/pinterest

... and they are not showing up here. Pointers would be welcome.

**Comment by jparise** [comment]
It looks like our `pinterest` fork was orphaned when this repository was made public. This is loosely described here: https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/#changing-a-private-repository-to-a-public-repository

We've recreated our fork, but this PR no longer appears to update automatically. We'll continue iterating in #519 instead.

**Comment by kentbrew** [comment]
Closing in favor of #519. See @jparise's note for explanation.

**Comment by erwinmombay** [comment]
thanks @jparise @kentbrew , unfortunately we all had to through this pain today too :-1: :cry:

**Pull request closed without merging**
