### PR TITLE
✨Implement Linkers for Segment 

### PR DESCRIPTION
**Pull request by misteryeo**
Implement Linkers for Segment analytics vendor.

### CODE REVIEW

**Comment by jeffjose** [comment]
Over to @calebcordry for review.

**Comment by misteryeo** [comment]
Thanks @jeffjose. @calebcordry I noticed there are 8 tests failing but none of them seem related to my change. Any idea what's up?

Working with the team to get the CLA signed as well in the interim.

**Comment by calebcordry** [comment]
Talked offline. Tests were flakes. Sent email trying to track down CLA  point of contact on our end.

**Comment by misteryeo** [comment]
@calebcordry Just added the cookies object + also confirmed with internal contact Calvin French-Owen that he's added me to the authorized group for the CLA. Are we good to merge this PR then?

**Comment by calebcordry** [comment]
Looks like CLA bot is still not satisfied, could you please try verifying the steps from `googlebot` above under the `Corporate Signers` section. Thanks!

**Comment by misteryeo** [comment]
For CLA purposes, created a new PR here: https://github.com/ampproject/amphtml/pull/18878. Can close this @calebcordry.

**Pull request closed without merging**
