### PR TITLE
:sparkles: Add Tealium Collect for amp analytics

### PR DESCRIPTION
**Pull request by tygavin**
Initial add of Tealium Collect for amp analytics.  Tealium Collect HTTP API receives events for Tealium's UDH (Universal Data Hub).

https://community.tealiumiq.com/t5/Universal-Data-Hub/Tealium-Collect-HTTP-API/ta-p/16893

### CODE REVIEW

**Comment by lannka** [comment]
Thanks for the PR.

Please fix linter and sign CLA

**Comment by zhouyx** [comment]
@lannka This PR made master red. Can we fix it?

**Comment by choumx** [comment]
```
DESCRIBE => amp-analytics
  DESCRIBE =>  
    DESCRIBE => vendor request tests
      DESCRIBE => analytics vendor: tealiumcollect
        IT => should produce request: base. If this test fails update vendor-requests.json
          ✗ AssertionError: expected 'https://collect.tealiumiq.com/event?tealium_account=TEALIUM_ACCOUNT&tealium_profile=TEALIUM_PROFILE&tealium_datasource=TEALIUM_DATASOURCE&tealium_visitor_id=_client_id_&url=_source_url_&ampdoc_url=_ampdoc_url_&domain=_source_host_&pathname=_source_path_&amp_hostname=_ampdoc_hostname_&canonical_hostname=_canonical_hostname_&title=_title_&viewport_width=_available_screen_width_&viewport_height=_available_screen_height_&timestamp=_timestamp_&tz=_timezone_&lang=_browser_language_&tealium_event=!tealium_event&amp_version=_amp_version_&amp_request_count=1' to equal 'https://collect.tealiumiq.com/event?tealium_account=TEALIUM_ACCOUNT&tealium_profile=TEALIUM_PROFILE&tealium_datasource=TEALIUM_DATASOURCE&tealium_visitor_id=_client_id_&url=_source_url_&ampdoc_url=_ampdoc_url_&domain=_source_host_&pathname=_source_path_&amp_hostname=_ampdoc_hostname_&canonical_hostname=_canonical_hostname_&title=_title_&viewport_width=_available_screen_width_&viewport_height=_available_screen_height_&timestamp=_timestamp_&tz=_timezone_&lang=_browser_language_&tealium_event=$tealium_event&amp_version=_amp_version_&amp_request_count=1'
```

https://travis-ci.org/ampproject/amphtml/jobs/440378350

**Comment by choumx** [comment]
This was rolled back in #18708.

**Pull request merged**
