### PR TITLE
✨ Intent To Implement: Macaw support for amp-ads

### PR DESCRIPTION
**Pull request by lebedev-alex**
Add support for Macaw widgets to amp-ad elements.

### CODE REVIEW

**Comment by calebcordry** [comment]
@lebedev-alex Looks like the tests keep failing. I don't think it has anything to do with your changes, but could you try rebasing/merging master and see if it helps? Thanks

**Comment by lebedev-alex** [comment]
> @lebedev-alex Looks like the tests keep failing. I don't think it has anything to do with your changes, but could you try rebasing/merging master and see if it helps? Thanks

@calebcordry Hello! Here are the git logs:

Merge attempt
```
git checkout master
Switched to branch 'master'
Your branch is up to date with 'upstream/master'.

git checkout macaw
Switched to branch 'macaw'
Your branch is up to date with 'origin/macaw'.

git merge master
Already up to date.
```
Rebase attempt
```
git checkout master
Switched to branch 'master'
Your branch is up to date with 'upstream/master'.

git fetch
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (5/5), done.
...

git checkout macaw
Switched to branch 'macaw'
Your branch is up to date with 'origin/macaw'.

git rebase origin/master
Current branch macaw is up to date.
```
I'm sorry for the inconvenience.

**Comment by calebcordry** [comment]
can you try 
```sh
git checkout master
git pull upstream master
git checkout mccaw
git rebase master
git push origin mccaw -f
```

I have tried restarting the test a few times but it does not seem to help.

**Comment by calebcordry** [comment]
Looks like the last restart resolved the issue, so don't worry about rebase. Thanks for contributing!

**Pull request merged**
