### PR TITLE
Use same-width dot characters for progress indicators

### PR DESCRIPTION
**Pull request by rsimha-amp**
This is a follow up to #10530, since some platforms display checks and crosses really badly. The color coding should make it plenty clear which tests passed / failed / were skipped.

#10482

### CODE REVIEW

**Comment by rsimha-amp** [comment]
/to @choumx (hopefully the last log-beautification PR!)

**Comment by rsimha-amp** [comment]
Tested this locally on all platforms, and the logs look significantly more readable. This is now ready to be merged.

**Comment by choumx** [comment]
Hmm, success and failure icons look the same to me on OS X. 

image

**Comment by rsimha-amp** [comment]
Are you seeing them in action, or just in source code? There's color coding that gets added to the console when these are printed during test runs. They won't appear black :)

The purpose of using the same sized dot is because of how bad / inconsistent checks and crosses look on various platforms.

**Comment by rsimha-amp** [comment]
@choumx Famous last words :(

While the dots showed up in color during my tests on linux and macos, there are still some places where they show in black and white when you look at travis logs in a browser.

screen shot 2017-07-19 at 9 45 12 pm

Since this is purely cosmetic, I'll revisit this once more tomorrow, in the hope that I don't have to mess with this again :/

**Comment by rsimha-amp** [comment]
For the record, this is what the integration test logs look like on Travis when viewed in a browser window on Linux. It shows that we're skipping the vast majority of our integration tests. Also, Unicode is hard :(

screenshot from 2017-07-20 10 41 01

**Comment by choumx** [comment]
Nice, it's good information to have. 👍

**Comment by rsimha-amp** [comment]
Fixed on all platforms with #10552.

**Pull request merged**
