### PR TITLE
Broadstreet Ads AMP Ad Implementation

### PR DESCRIPTION
**Pull request by katzgrau**
This pull request contains the files for the Broadstreet Ads implementation for AMP Ads.

Please review and comment with any questions or concerns.

Written by: kenny@broadstreetads.com

### CODE REVIEW

**Comment by lannka** [comment]
Sorry for the late response.
can you try to implement render-start API?  See details [here](https://github.com/ampproject/amphtml/blob/master/ads/README.md#developer-guidelines-for-a-pull-request)

**Comment by katzgrau** [comment]
@lannka No worries — looking at quite a few existing 3p ad implementations, they don't implement render-start, but we agree that it's ideal. 

Since it's been a couple of months, could we move this forward and we'll submit a separate PR with render-start immediately following our next release cycle?

**Comment by lannka** [comment]
@katzgrau that sounds reasonable. we can get this running first.

**Comment by westonruter** [comment]
@lannka There are some [questions](https://github.com/broadstreetads/broadstreet-wp/pull/11) from @claudiulodro in regards to integrating the Broadstreet Ads `amp-ad` type with the WordPress plugin. Namely:

> As you can see in the screenshots and [this docblock comment](https://github.com/broadstreetads/broadstreet-wp/compare/master...claudiulodro:master?expand=1#diff-f6e8b291b0f985d67e95ee4a133941ddR116), the AMP-version has issues with the amount of padding on ads that aren't 300:250 ratio.
> 
> Ideally those heights would be dynamic since ads of different sizes can load in the zone. I have some proposed ideas, let me know if any are feasible or please suggest alternate approaches:
> 
> * If there was a way to programmatically get the height and width of the ad zone using PHP, it could just be set with correct values. I didn't see any way to access that information from within the Broadstreet WP plugin, though.
> * Instead of rendering the same zone for both AMP and non-AMP modes, there could be AMP and non-AMP zones, with the AMP zones having a defined height and width. This seems like it would introduce complexity when setting up ad zones, though.
> * Maybe something like [the amp-iframe resizable attribute](https://amp.dev/documentation/examples/components/amp-iframe/#resizable-iframe) is possible for amp-ads, and they could be resized dynamically after the ad has loaded. Perhaps that could be added in the [Broadstreet amp-ad implementation](https://github.com/ampproject/amphtml/blob/master/ads/broadstreetads.md)?
> 
> If the sizing issue can be solved, this would be a great way to add AMP-support to the plugin without changing the workflow of the people managing the ads. Let me know if you have any thoughts or ideas on any of this.

Any insights to share regarding the question of a dynamic ad height?

**Pull request merged**
