### PR TITLE
🐛 amp-delight-player: Guard against missing DeviceMotionEvent info on iOS

### LINKED ISSUE #27448: Error: null is not an object (evaluating 'b.acceleration.x')
First seen Feb 25, recently saw a spike that bumped in into the [top errors](go/ampe/CL6chqbN2-bzBA)

```
Error: null is not an object (evaluating 'b.acceleration.x')
    at x (https://raw.githubusercontent.com/ampproject/amphtml/2003241513590/extensions/amp-delight-player/0.1/amp-delight-player.js:421)
    at event (https://raw.githubusercontent.com/ampproject/amphtml/2003241513590/src/event-helper-listen.js:58)
```

It appears all occurrences are on iPhone on one domain: https://amp-focus-de.cdn.ampproject.org/c/s/amp.focus.de/politik/deutschland/hammer-and-dance-szenario-angestrebt-internes-papier-deutschland-steuert-im-kampf-gegen-corona-auf-suedkorea-strategie-zu_id_11819262.html?usqp=mq331AQDsAEg 

Unclear if the issue is only on that domain, or just that that domain introduced something which triggers the bug, and has high enough traffic that it dominated the error report sampling.

/tryassign @xymw who added the player, might have insight
/cc @ampproject/wg-ui-and-a11y

### PR DESCRIPTION
**Pull request by xymw**
With the release of iOS version 13.4 the DeviceMotionEvent doesn't include the acceleration property any longer. This is most likely a bug on Apple's end. 
The fix now guards against this. 

Fixes #27448

### CODE REVIEW

**Comment by alanorozco** [comment]
@xymw This is [not passing typecheck](https://travis-ci.org/github/ampproject/amphtml/jobs/667759672#L424). I think you might need to restructure how the object is populated.

**Comment by xymw** [comment]
@alanorozco Dou you think a `let payload = { ... }` instead of const is enough to pass this check? Otherwise I would have to init payload all at once with conditional params.

**Comment by alanorozco** [comment]
@xymw `Object.assign` works as you've noticed!

**Comment by xymw** [comment]
@alanorozco Any update on this? Can this be merged to resolve the issue or is there still something we can do on our end?

**Comment by rcebulko** [comment]
@xymw Can you try resolving the merge conflict? A new commit/rebase should re-trigger Travis and hopefully get it un-stuck

**Pull request merged**
