### PR TITLE
appnexus implement renderStart API including resize ad

### PR DESCRIPTION
**Pull request by mkendall07**
# Ads: Implement RenderStart API for AppNexus

- Implements RenderStart API for appnexus.js

### CODE REVIEW

**Comment by mkendall07** [comment]
anyone able to review this?

**Comment by mkendall07** [comment]
You are referring to the "failed to execute `write`" warning? 

the `renderStart` is more about supporting flexible sizing.

**Comment by lannka** [comment]
Was referring to the red GET error.

Can you move the renderStart call to a time point that is closer to the real rendering?

**Comment by mkendall07** [comment]
ok I don't recognize that network request, so it's either something unrelated or possibly the creative is requesting it. I can check. 

The `renderStart` is at the point of render because it's attached to the `adAvailable` event which is fired right before the ad is loaded.

**Comment by lannka** [comment]
so are you able to explain the small gap? actually do you see it at your side? or it's just me?

**Comment by mkendall07** [comment]
@lannka 
I don't see the network error. 
image

Not sure about the gap either. The ad loads quickly for me. Please let me know what else I need to do to get this merged.

**Pull request merged**
