### PR TITLE
Add validation table to amp-accordion.

### LINKED ISSUE #2739: Create validation table for amp-accordion.md doc
cc/ @Gregable 

Hoping to get this into the current sprint (ends this Thursday), but can re-slot if you don't have bandwidth. Thanks!

### PR DESCRIPTION
**Pull request by powdercloud**
Closes #2739

### CODE REVIEW

**Comment by sriramkrish85** [comment]
#2739

**Comment by powdercloud** [comment]
Thank you, will try to merge it.

**Comment by powdercloud** [comment]
Hmm, it doesn't let me. "Merge attempt failed - 2 of 2 required status checks are expected". @sriramkrish85 can you do it?

**Comment by sriramkrish85** [comment]
@powdercloud try rebasing. (i could not either)

**Pull request merged**
