### PR TITLE
Enable CSS scroll snap code across more browsers

### PR DESCRIPTION
**Pull request by nainar**
Safari/Firefox/Edge have scroll-snap enabled. Chrome now has it enabled starting 69. 

This PR enables scroll snap code for all browsers/OSes.

Addresses: #16508

### CODE REVIEW

**Comment by cathyxz** [comment]
This change looks fine, but will probably require very extensive testing on all relevant devices / browsers to see if it breaks anything. Do you mind commenting with a checklist here (or just assigning the PR to me) after that's been done?

**Comment by nainar** [comment]
Tracking manual testing on the following platforms:
- [ ] iOS + Safari
- [ ] iOS + Chrome
- [ ] iOS + Firefox
- [ ] iOS + Edge
- [ ] Android + Opera
- [ ] Android + Chrome
- [ ] Android + Firefox
- [ ] Android + Edge

**Comment by nainar** [comment]
Logging offline discussion:

Turning this into an experiment with following movement:
- 2 weeks: 1% canary
- 2 weeks: 10% prod
- 2 weeks: 50% prod
- 4 weeks: 100% prod
- TURN ON FULL! 🎆 

@cathyxz take a look?

**Comment by cathyxz** [comment]
I think we made a new rule banning creating experiments and flipping flags in the same PR. It makes for easier reverts.

**Comment by nainar** [comment]
@cathyxz - Split up the canar-config change into it's own PR.

**Pull request merged**
