### PR TITLE
🏗🐛 Consolidate the hostname used by `karma` and `gulp serve` to `127.0.0.1`

### LINKED ISSUE #15751: Tests are running on different hostnames
```
hostname: process.platform === 'darwin' ? '127.0.0.1' : 'localhost',
```

This failed some tests (test-amp-analytics.js) locally where string comparison is operated with http://localhost/ .

Having this discrepancy between environments can be a bug hole. Can we unify to 127.0.0.1 for instance?

caused by #15510

### LINKED ISSUE #15801: AMP unit and integration tests should be triggered for build-system changes
See https://github.com/ampproject/amphtml/pull/15799#issuecomment-394443346

### PR DESCRIPTION
**Pull request by rsimha**
We've always used the hostname `localhost` for local testing. This doesn't work well with Safari, so we changed the `karma` hostname to `127.0.0.1` in #15510. However, this didn't work well with some tests that hard-code the hostname as `localhost` during checks. 

In this PR, we consolidate the hostname used for testing to `127.0.0.1` on all platforms. We also trigger unit and integration tests for changes to `build-system/` so that changes like this can be fully tested.

Fixes #15751
Fixes #15801
Follow up to #15510

### CODE REVIEW

**Comment by rsimha** [comment]
/to @lannka 

Commit coming up to fix all tests that fail due to this.

**Comment by lannka** [comment]
The change did not trigger any unit tests. @rsimha we need to add a dependency rule to run all tests for any config change like this.

**Comment by rsimha** [comment]
@lannka Issue filed, fix uploaded in new commit.

**Comment by rsimha** [comment]
Unfortunately, this approach doesn't work for subdomains, like `ads.localhost` or `iframe.localhost`. Will look at trying something else.

**Pull request closed without merging**
