### PR TITLE
Amp-analytics: Adding Nielsen marketing cloud config

### LINKED ISSUE #10012: Intent To Implement: Adding Nielsen marketing cloud analytics config to amp-analytics
## Implement tracking pixel of Nielsen Marketing Cloud for amp-analytics tag

For ease of use for publishers using AMP and Nielsen Marketing Cloud analytics, so the external configuration doesn't have to be used
We'll generate the Patch that can be reviewed then

### PR DESCRIPTION
**Pull request by peterbaran**
Adding Nielsen marketing cloud into amp-analytics configuration so that AMP users can implement it with easy

Issue associated with the Pull Request: #10012 

- Configuration for tracking pageviews
- Configuration for tracking clicks
- Example of usage

Closes #10012.

### CODE REVIEW

**Comment by rudygalfi** [comment]
ping @lannka

**Comment by lannka** [comment]
@rsimha-amp I got no permission to look at the percy error. Can you help?

**Comment by lannka** [comment]
@peterbaran can you follow the robot guide to sign CLA?

**Comment by rsimha-amp** [comment]
@lannka, you should have received an invitation email from Percy a couple of weeks ago at your google email. Let me know if you don't find it, and I can send you another one.

Also, the error has to do with timing, since there's no way for Percy to know when an AMP has fully loaded :/ I'm working on a fix for #10156, which should fix it. Meanwhile, you can manually approve the visual diffs in this PR.

**Comment by lannka** [comment]
> Whoops! This invite has expired or already been used

@rsimha-amp I actually don't remember if I clicked the link. :-( since i got an empty organization list, probably i didn't. Could you send again? thanks

**Comment by lannka** [comment]
@peterbaran got chance to resolve the CLA?

**Comment by peterbaran** [comment]
@lannka I'm sorry for late response, I'll follow internally in Nielsen so we can sign it ASAP. I'll get back to you

**Comment by lannka** [comment]
@peterbaran any update?

**Comment by peterbaran** [comment]
I signed it!

**Comment by lannka** [comment]
@peterbaran did you sign as corp or as person? 

> If your company signed a CLA, they designated a Point of Contact who decides which employees are authorized to participate. You may need to contact the Point of Contact for your company and ask to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the project maintainer to go/cla#troubleshoot.

**Comment by peterbaran** [comment]
@lannka we signed it as a company. I'll let Arik know to add me to authorized contributors.

**Comment by lannka** [comment]
@peterbaran any update?

**Comment by lannka** [comment]
@peterbaran a kind ping.

**Comment by peterbaran** [comment]
@lannka the issues with CLA should be resolved. Can you please verify?

**Comment by cramforce** [comment]
Ping @googlebot to check CLA

**Comment by cramforce** [comment]
Manually verified CLA

**Comment by bpaduch** [comment]
@peterbaran - I'm going to add `nielsen-marketing-cloud` to the [Analytics Vendors List](https://github.com/ampproject/docs/blob/master/content/docs/guides/analytics_amp/analytics-vendors.md).  What supporting documentation URL or site URL for Nielsen Marketing Cloud should we point readers to?

**Pull request merged**
