### PR TITLE
Revert "Launch no center css for ad container"

### PR DESCRIPTION
**Pull request by glevitzky**
Reverts ampproject/amphtml#28551

Looks like this is causing an issue for multi-size creatives :\\.

image

found on:
http://localhost:8000/proxy/s/www.gq.com/story/kanye-west-may-2020-cover-announcement/amp

The plan should be to revert the change here to status quo. After that, I will make a code change to apply centering logic to multi-size creatives only, and then we can re-apply the reverted CL.

**Alternatively** we can unlaunch only the experiment traffic fractions, and then roll-forward a fix (applying the centering logic to multi-size creatives).

### CODE REVIEW

**Comment by powerivq** [comment]
Make sense. I am curiously how it can be caught so quick? Did someone from gq 
complained?

**Comment by glevitzky** [comment]
@keithwrightbos spotted it by coincidence earlier today.

**Comment by glevitzky** [comment]
I specifically tested for this case, but must've missed it. I think on the page that I tested, the slot was already centered, so I must've not noticed that the (smaller) creative was slightly off center.

**Comment by powerivq** [comment]
@glevitzky I think we can simply do a fix forward. I don't think the experiment will give us more helpful insights, because the failure should have been caught but was not.

**Comment by glevitzky** [comment]
Reason I want the experiment back is that it will prevent the bug from going out to 95% of traffic. Agreed that it won't give us any new info, though. My thinking is:

1. Revert PR so that we can prevent uncentered multi-size creatives from appearing on (most) live traffic.
2. Add code change to apply centering to (only) multi-size creatives < than the slot.
3. Wait for #2 to go live.
4. Remove experiment flag.

If we don't do #1 first, and go straight to #2, then we'll "break" multi-size creatives until the next code release.

**Comment by powerivq** [comment]
@glevitzky Yeah I agree we must prevent it from getting out now. I was thinking of your `alternative approach` is good enough.

**Comment by glevitzky** [comment]
Got it. I'll put together a separate PR, then.

**Comment by lannka** [comment]
> Make sense. I am curiously how it can be caught so quick? Did someone from gq
complained?

wasn't this out in last week's release via a flag flip?

**Pull request merged**
