### PR TITLE
✨Add "sulvo" adserver support to amp-ad

### PR DESCRIPTION
**Pull request by careers-sulvo**
This adds "sulvo" adserver support to amp-ad.

### CODE REVIEW

**Comment by careers-sulvo** [comment]
@googlebot I signed it!

**Comment by careers-sulvo** [comment]
@googlebot I signed it!

**Comment by jeffjose** [comment]
Over to @powerivq for review.

**Comment by careers-sulvo** [comment]
@googlebot I signed it!

**Comment by careers-sulvo** [comment]
@googlebot I signed it!

**Comment by careers-sulvo** [comment]
Closing this PR to solve CLA issues. Create this new one in replace #25913

**Pull request closed without merging**
