### PR TITLE
Test on Travis using Node v4

### PR DESCRIPTION
**Pull request by jridgewell**

### CODE REVIEW

**Comment by erwinmombay** [comment]
looks like this is broking validator runs since the validator uses `includes`

**Comment by aghassemi** [comment]
related? 
https://travis-ci.org/ampproject/amphtml/jobs/237592019 
```
pr-check.js: Running node_modules/gulp/bin/gulp.js clean ...
/home/travis/build/ampproject/amphtml/node_modules/require-dir/index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {

TypeError: require.extensions.hasOwnProperty is not a function
```

**Comment by erwinmombay** [comment]
@aghassemi no, that is a node 8 breaking change

**Comment by jridgewell** [comment]
@ampproject/validator is aware.

**Pull request merged**
