### PR TITLE
🚧🚀 Add esbuild+babel caching to tests

### PR DESCRIPTION
**Pull request by jridgewell**
This also sets up the base code needed for file persistence.

### CODE REVIEW

**Review by rsimha — APPROVED** [review]
LGTM, with the same comment as https://github.com/ampproject/amphtml/pull/33118#pullrequestreview-605718873 re: moving this off into its own file.

**Comment by jridgewell** [comment]
Moved the files, deleted  `invalidateUnminifiedBabelCache` (because the cache will hash the contents again).

I noticed while going through, in a lot of the files there's a debounced `watcher` function that takes an argument, and would invalidate the cache of the arg. But, `debounce` only stores the **last** arguments, and forwards that. Meaning if multiple files were modified in the 1s bounce time, only the last file would be invalidated.

**Comment by rsimha** [comment]
> Meaning if multiple files were modified in the 1s bounce time, only the last file would be invalidated.

I introduced debounce when we were watching just the entrypoint file, and double-saving caused a really annoying and racy double build. I'm good with removing it from our esbuild codepaths if there's built-in logic to prevent double builds.

**Comment by jridgewell** [comment]
There's not bug now, since I removed the invalidation logic entirely.

**Pull request merged**
