### PR TITLE
piano analytics support

### PR DESCRIPTION
**Pull request by nathangoulding**
Fixes issue #1769.

### CODE REVIEW

**Comment by avimehta** [comment]
@nathangoulding : Can you update vendor-requests.js to add the requests for piano analytics? The tests are currently failing because of them.

**Comment by nathangoulding** [comment]
@avimehta I updated vendor-requests.json which is passing tests now but still seeing this test failing:

```
amp-youtube renders FAILED
	Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by avimehta** [comment]
No clue. Try pushing out the commit. Sometimes Travis does not see the same
failures as local tests.

**Comment by nathangoulding** [comment]
This is actually from Travis not locally.

**Comment by avimehta** [comment]
sorry about that. That test seems to be failing on master at HEAD. It's probably not related to your change. 

Can you squash all your commits and rebase? Once done, I'll merge.

Thanks for the patience.

**Comment by nathangoulding** [comment]
Closed in favor of https://github.com/ampproject/amphtml/pull/2624.

**Pull request closed without merging**
