### PR TITLE
Add Array support for analytics vars

### PR DESCRIPTION
**Pull request by SmithKevin**
This pull request address issue #1886

### CODE REVIEW

**Comment by SmithKevin** [comment]
The CLA is under the corporation Quantcast.

**Comment by rudygalfi** [comment]
cc @avimehta for review

**Comment by avimehta** [comment]
This looks good to me as a commit.

I am not sure if other vendors might have a different preference on how to serialize arrays. When I built amp-analytics, I did not really intend the values to be arrays so not sure how we feel about blessing arrays as valid values.

**Comment by rudygalfi** [comment]
If we move forward with this, the PR should also cover updating documentation.

@avimehta Are you concerned about breakage in a specific scenario?

**Comment by avimehta** [comment]
nope. Just didn't think of this while creating the spec. I think this should be fine.

**Comment by avimehta** [comment]
btw I am okay with merging this. lgtm.

**Comment by rudygalfi** [comment]
I would like to update the docs.

@SmithKevin I suggest adding a new paragraph after "New variables are commonly used to specify publisher specific information." that says something to the effect that the values can be an array and how that gets transmitted in the request. (It looks like the behavior is that a comma `,` will show up directly in the request string rather than getting encoded to `%2C`.)

Please also update the example near this section to include an array value.

**Comment by SmithKevin** [comment]
Added a line to the docs with an example.  What do you think?

**Comment by rudygalfi** [comment]
LGTM, thanks!

**Pull request merged**
