### PR TITLE
🐛 Restore `dock` on amp-brightcove

### PR DESCRIPTION
**Pull request by mister-ben**
Disables the autoplay setting if configured on the Brightcove Player in `<amp-brightcove>`.
Restores dock functionality on `<amp-brightcove>`, which was disabled in #33137

cc @alanorozco

### CODE REVIEW

**Review by alanorozco — APPROVED** [review]
Awesome, thank you!

**Comment by alanorozco** [comment]
@mister-ben Apologies, we recently migrated CI tooling. It looks like you need to authenticate on CircleCI so that it runs and I can merge this change.

Could you please navigate to https://app.circleci.com/pipelines/github/ampproject/amphtml and ensure you are signed in with your GitHub account? You don't need to grant access to any of your repositories.

**Comment by mister-ben** [comment]
I've authenticated. Does it need another nudge?

**Comment by alanorozco** [comment]
@mister-ben Thanks! I pushed another empty commit and CircleCI was triggered. I will merge this as soon as checks pass.

**Comment by danielmollmorgan-nuk** [comment]
The existence of `autoload=false` in the iframe src request appears to be causing videos to autoplay despite no autoload attribute passed in the player or in the brightcove studio settings:

https://www.thesun.co.uk/tvandshowbiz/14858716/nick-kamen-dead-madonna-levi-advert-model/amp/
image

[iframe request with autoplay=false](https://players.brightcove.net/5067014667001/5z708EYEr9_default/index.html?amp=1&autoplay=false&videoId=6252681021001&ampInitialConsentState=1&ampInitialConsentValue=CPFusr1PFusr1AGABCENBYCkAP_AAH_AAAwIHMtN9H5eSXVjeP59cvt0eYUXwF4dq-gijhMFo6IBSNeUpIwGhGAypEyChigCCR4AIFJAAAFlGGFQAAEQ4IEBgRGMAEAEpAIIJCKECAABQgBAEBgJAIEAEACApEB2kAQAyAoIWR8CYAAAIAEwAAAAACAEAIACBwABZAqTgEBQlhILTBpVCCEAEASEQDgIooRBaAAAAhUFCSMAhRAAgAAgIAgAgkGICAWAAAAQQBJEAAAAGCBAQEQiAAAAAAAAAAiABAAAUAAAAAIAAAAAAAAgCAAQAAEAIAAAAASAkAAAAABIAAAAAAgBASGQDQAKABDACYAFwARwAywB2AD7AIwARwBMQC2AGHjQAgAZgBSADKAP2IgIABWAC4AMgAZYA2QB2AEAAIwAU8A1gB1QD5AIbAQ6Ai8Bh4kAOAD4AKEApAClAPUAfsBYoDGQkBwABAAFAAPAAwABqAEMAIoATAArABvAD0AJcAaoA2QB9gEAAKCAU8A1gBtAD5AIbAQ6Ai8BMQC2AGHgNOCgEwAFAAqABkAEcAKAAUgBWgC-AGEAQgArIBXwDOAG2APEAeoA_YCQQGMhoCIAVgAuADIAGWANkAdgBAACMAFPANYAdUA-QCGwEOgIvAYeAxgOAEAFKAbIBYoDGRUA4ACgAQwAmABcAEcAMsAdgBGACOAJBATEApsBbADDxYAUAMwApABlAH7AWKOgNgAUABcADAAGoAQwAigBMACsAG8APUAlwCYAGiANkAfYBQQCngG0AOmAhsBDoCL4FsAWyAw8BiQDGAGnAOLHgEQAFAAqABkAEcAJoAUAApACkAFaAVkAr4BnADbAHiAPUAfsBjJCAcABQAFwAQwAmABiADeAHoAfYBQQCngG0gWwBbIDDwGJEQBIAKgAmgCkAFaAVkAr4BnADxAH7JQDgAEAAUABgAEwAUYAwgBqgDZAKeAfIBDoCLwFsAMPJgEQAjgBNACgAFIAPAApABWgFNAKyAV8AvwBnADbAHiAP2AkEBjJSAiABQAGAANQAhgBFACYANEAaoA2QB9gFBANoAh0BF4C2AGHgMYKgEAAVAAyAB8AEcAJoAUAA8ACkAFaAVkAr4BnADbAHiAP2Axk.YAAAAAAAAAAA&adunitPath=3048%2Fd.thesun.amp%2Fnews%2Fuknews&playsinline=true)

[iframe request with autoload key/value removed from request](https://players.brightcove.net/5067014667001/5z708EYEr9_default/index.html?amp=1&videoId=6252681021001&ampInitialConsentState=1&ampInitialConsentValue=CPFusr1PFusr1AGABCENBYCkAP_AAH_AAAwIHMtN9H5eSXVjeP59cvt0eYUXwF4dq-gijhMFo6IBSNeUpIwGhGAypEyChigCCR4AIFJAAAFlGGFQAAEQ4IEBgRGMAEAEpAIIJCKECAABQgBAEBgJAIEAEACApEB2kAQAyAoIWR8CYAAAIAEwAAAAACAEAIACBwABZAqTgEBQlhILTBpVCCEAEASEQDgIooRBaAAAAhUFCSMAhRAAgAAgIAgAgkGICAWAAAAQQBJEAAAAGCBAQEQiAAAAAAAAAAiABAAAUAAAAAIAAAAAAAAgCAAQAAEAIAAAAASAkAAAAABIAAAAAAgBASGQDQAKABDACYAFwARwAywB2AD7AIwARwBMQC2AGHjQAgAZgBSADKAP2IgIABWAC4AMgAZYA2QB2AEAAIwAU8A1gB1QD5AIbAQ6Ai8Bh4kAOAD4AKEApAClAPUAfsBYoDGQkBwABAAFAAPAAwABqAEMAIoATAArABvAD0AJcAaoA2QB9gEAAKCAU8A1gBtAD5AIbAQ6Ai8BMQC2AGHgNOCgEwAFAAqABkAEcAKAAUgBWgC-AGEAQgArIBXwDOAG2APEAeoA_YCQQGMhoCIAVgAuADIAGWANkAdgBAACMAFPANYAdUA-QCGwEOgIvAYeAxgOAEAFKAbIBYoDGRUA4ACgAQwAmABcAEcAMsAdgBGACOAJBATEApsBbADDxYAUAMwApABlAH7AWKOgNgAUABcADAAGoAQwAigBMACsAG8APUAlwCYAGiANkAfYBQQCngG0AOmAhsBDoCL4FsAWyAw8BiQDGAGnAOLHgEQAFAAqABkAEcAJoAUAApACkAFaAVkAr4BnADbAHiAPUAfsBjJCAcABQAFwAQwAmABiADeAHoAfYBQQCngG0gWwBbIDDwGJEQBIAKgAmgCkAFaAVkAr4BnADxAH7JQDgAEAAUABgAEwAUYAwgBqgDZAKeAfIBDoCLwFsAMPJgEQAjgBNACgAFIAPAApABWgFNAKyAV8AvwBnADbAHiAP2AkEBjJSAiABQAGAANQAhgBFACYANEAaoA2QB9gFBANoAh0BF4C2AGHgMYKgEAAVAAyAB8AEcAJoAUAA8ACkAFaAVkAr4BnADbAHiAP2Axk.YAAAAAAAAAAA&adunitPath=3048%2Fd.thesun.amp%2Fnews%2Fuknews&playsinline=true)

Are there attributes/settings that need to be updated in our codebase/brightcove studio post this merged feature?

**Comment by alanorozco** [comment]
Hi @danielmollmorgan-nuk 

I can't speak for Brightcove's side (I only work on AMP) but #34207 might be the fix.

**Comment by danielmollmorgan-nuk** [comment]
Thanks @alanorozco - that looks like it'd fix the problem 👍

**Pull request merged**
