### PR TITLE
Validator rollup 523@1126

### PR DESCRIPTION
**Pull request by amaltas**

### CODE REVIEW

**Review by banaag — APPROVED** [review]

**Comment by amaltas** [comment]
@rcebulko Can you approve this similar to previous closed PR https://github.com/ampproject/amphtml/pull/31316

The travis build is failing for:
[19:21:16] Found forbidden: "cdn.ampproject." in validator/js/engine/htmlparser-interface.js:271:33

**Review by rcebulko — APPROVED** [review]

**Comment by amaltas** [comment]
Thanks!

**Comment by amaltas** [comment]
@rsimha @rcebulko How do I re-run the failing presubmit check? Thanks!

**Comment by amaltas** [comment]
I re-ran the travis build but it failed again for same reason:  Found forbidden: "cdn.ampproject." in validator/js/engine/htmlparser-interface.js:271:33

**Pull request merged**
