### PR TITLE
Small changes for Clicky Web Analytics vendor

### PR DESCRIPTION
**Pull request by avclicky**
* Add referer to initial pageview request
* Prevent interval request from firing immediately

### CODE REVIEW

**Comment by avclicky** [comment]
Hi. The changes in this PR are quite minimal and affect only the Clicky/AMP overlap user group. Might I kindly ask that another reviewer give a look for approval? Thank you.

**Review by lannka — APPROVED** [review]

**Review by micajuine-ho — APPROVED** [review]

**Comment by lannka** [comment]
Stuck in the submit queue, rerunning

**Comment by micajuine-ho** [comment]
@avclicky  Can you please rebase and merge? Our testing/submitting infra has been updated recently.

**Comment by avclicky** [comment]
Hi, yes, I've done what you requested. All checks appear to have passed but for one, the percy check.

I'm not sure how to interpret the results of this check, and I'm confused as to why anything visually would have changed from my PR given the extremely small and limited nature of the changes.

**Comment by avclicky** [comment]
Upon further inspection, I'm seeing that the reason for the changes is that some "<style amp-boilerplate>...</style>" content is included *as plaintext* in one screenshot but not the other, for all 21 visual changes. This has the effect of offsetting the two screenshots by about 20px, hence the very red "visual diff" representations. Could this be an issue with the aforementioned new infra?

**Comment by lannka** [comment]
@avclicky thanks for doing that. we can ignore the percy, it's apparently not from your change.

**Comment by avclicky** [comment]
Cheers. Thank you very much!

**Pull request merged**
