### PR TITLE
🐛Lazy generate linker values.

### PR DESCRIPTION
**Pull request by calebcordry**
I realized that we are generating linker values on `init()` instead of lazy generating on event (form-submit, anchor click). This refactor resolves and caches macros on init, but waits to actually create the linker param.

I also tested if this would be a huge perf hit, now the `handleAnchorMutation_` method takes about 1ms on my laptop, as opposed to about 0.3ms before.

### CODE REVIEW

**Comment by zhouyx** [comment]
There's a tradeoff here. Honestly I believe we should generate linker params as early as possible. Because it is blocking a redirection or a form submit and on the critical path. WDYT?

**Comment by calebcordry** [comment]
What about if someone visits a page, reads an article for 5 min, then clicks a link? This would be invalid on ingestion. 

I also thought about generating in the background every minute (could be more). What do you think?

**Comment by calebcordry** [comment]
I also agree that blocking is bad, maybe I should test on lower end devices to see how much impact this actually has.

**Comment by lannka** [comment]
I agree. I think it was actually a bug. We should create linker on event to get the correct timestamp. The fix looks good, as we still try to resolve the IDs as early as possible.

**Comment by zhouyx** [comment]
I see. Do we want to cherry pick the fix then? I'll leave the decision to you two.

**Comment by lannka** [comment]
Yep. I think we should get it to canary this week. This is breaking linkers for page visits that last more than 3min.

**Comment by zhouyx** [comment]
cherry pick to canary or prod?

**Pull request merged**
