### PR TITLE
removed amp-analytics from valid child list of amp-story-grid-layer

### PR DESCRIPTION
**Pull request by CrystalOnScript**
Resolves [issue 3782](https://github.com/ampproject/amp.dev/issues/3782)

### CODE REVIEW

**Comment by CrystalOnScript** [comment]
No need to apologize. This was an unfounded PR. Thanks for clarifying!

**Comment by Enriqe** [comment]
We discussed this offline and decided stories that have `<amp-analytics>` as children of `<amp-story-grid-layer>` will continue to be valid, but we want to discourage publishers from doing it since there are some performance hits when doing this. 

@CrystalOnScript would you mind reopening this PR? Sorry for the confusion!

**Comment by CrystalOnScript** [comment]
You got it ;)

**Comment by Enriqe** [comment]
thanks @CrystalOnScript! @gmajoulet, would you mind approving please?

**Pull request merged**
