### PR TITLE
create extension  amp-aparat

### PR DESCRIPTION
**Pull request by mysamimi**
we create new extension for www.aparat.com player, Aparat used hosted jwplayer and video file hosted in own servers.
we can't used amp-jwpalyer, because it only play videos on jwplayer cloud.

### CODE REVIEW

**Comment by aghassemi** [comment]
@mysamimi Thanks for the component. We will review this soon, meanwhile please sign the CLA (https://cla.developers.google.com/) and provide us with a few other websites that embed aparat videos  other than http://www.aparat.com/ itself.

**Comment by aghassemi** [comment]
@mysamimi Thanks for the component. We will review this soon, meanwhile please sign the CLA (https://cla.developers.google.com/) and provide us with a few other websites that embed aparat videos other than http://www.aparat.com/ itself.

**Comment by mysamimi** [comment]
Hi,
I signed it!

**Comment by aghassemi** [comment]
@mysamimi Could you please confirm that this component can be used by any site other than http://www.aparat.com/ ? If so, please provide a few samples of other sites that have Aparat embeds. We normally do not allow components that are for single-site only use. (`<amp-iframe>` might be enough to cover your case).

**Comment by aghassemi** [comment]
@mysamimi Closing since I haven't heard back in a while. Please feel free to reopen if you like to continue with this PR.

**Pull request closed without merging**
