### PR TITLE
Fix minor URL typo for Collaborators team

### PR DESCRIPTION
**Pull request by mrjoro**
This fixes a minor URL typo for the Collaborators GitHub team.

This also fixes a broken link to enable-git-pre-push.sh that the link checker caught.

### CODE REVIEW

**Comment by mrjoro** [comment]
@rcebulko do you know why this PR didn't get an auto-assigned reviewer?

**Comment by rcebulko** [comment]
> @rcebulko do you know why this PR didn't get an auto-assigned reviewer?

Because you own the files in it, so it has owners coverage :)

**Comment by mrjoro** [comment]
Ohhh... interesting.  Maybe we should assign someone who can cover the Reviewer part as well?  I can file a FR for that if one doesn't already exist.

**Comment by rcebulko** [comment]
> Ohhh... interesting. Maybe we should assign someone who can cover the Reviewer part as well? I can file a FR for that if one doesn't already exist.

I'm not sure if that's really desired behavior? I feel like in most cases the author would rather choose someone they know or someone related rather than having the review bot try to just take a random guess out of all possible reviewers. Thoughts?

**Comment by mrjoro** [comment]
In this case I didn't care too much who reviewed it since it's a minor change and doesn't require specific knowledge, so I was hoping the bot was going to randomly select someone. :)  I suppose that won't often be the case for more significant changes.

**Comment by mrjoro** [comment]
Friendly ping for a review so I can merge this in. :)

**Pull request merged**
