### PR TITLE
Turn on analytics-chunks in canary

### PR DESCRIPTION
**Pull request by zhouyx**

### CODE REVIEW

**Comment by zhouyx** [comment]
cc @choumx 
Is the `intersect-resources` experiment going to affect this?

**Comment by choumx** [comment]
Should be fine, just note that canary metrics now are impacted by three active experiments. Are you planning on enabling it in prod soon?

**Comment by zhouyx** [comment]
Yes, I am hoping to enable it in prod next week.

**Comment by zhouyx** [comment]
Ideally this should help with reducing long tasks. I'm not seeing that. The three experiments could be a reason. 

But I see no major regression. And since the change doesn't apply to inabox, I feel it's safe to enable.

**Comment by choumx** [comment]
Sounds good, thanks.

**Pull request merged**
