### PR TITLE
Revert "Revert "Merge pull request #1909 from BrightcoveOS/amp-brightcove-params""

### PR DESCRIPTION
**Pull request by erwinmombay**
This reverts commit e5ab3f57123e011ff77d5f424fb4ace14684e209.

### CODE REVIEW

**Comment by mstoltenburg** [comment]
Is this an experiment? I thought the `data-player` attribute finally changed to `data-player-id`. Though the _normal_ (not AMP) brightcove player embed code uses `data-player`. And there is still one occurrence/check for `data-player` inside validator.protoascii in `master`.

**Comment by erwinmombay** [comment]
@mstoltenburg really sorry, we had to roll this back as it was causing our builds to fail. will try and get this back in as soon as possible. possibly just skipping the test for now until we figure it out.

**Comment by erwinmombay** [comment]
@cramforce only change i did was the 2nd commit skipping the last test.

**Comment by erwinmombay** [comment]
@mister-ben can you please respond to the google bot with "I confirm", i cherry picked your commit again to give you proper attribution (so that it is your commit). i had to skip the last test to make travis green.

**Comment by mister-ben** [comment]
@googlebot i confirm

**Comment by mister-ben** [comment]
@mstoltenburg I'm very sorry about the changing from `data-player-id` to `data-player`. It really should have been `data-player` all along to match the non-AMP embed, as you note, which caused some understandable confusion. With this change *either* can be used to ensure existing pages continue to work, with `data-player` being preferred in documentation.

**Comment by cramforce** [comment]
LGTM

**Comment by jridgewell** [comment]
Ping @erwinmombay: Are we merging this back in?

**Comment by erwinmombay** [comment]
@jridgewell yep, just waiting on green build again

**Pull request merged**
