### PR TITLE
Update documentation on US Subdivision detection support

### PR DESCRIPTION
**Pull request by erwinmombay**
Update the list of supported states + Washington DC

Fixes https://github.com/ampproject/amphtml/issues/39041

### CODE REVIEW

**Comment by erwinmombay** [comment]
Do not submit until backend deployment is completed

**Review by powerivq — APPROVED** [review]
LGTM, but are we not intending to support Puerto Rico, Virgin Islands, CNMI, Guam and American Samoa for now?

**Comment by erwinmombay** [comment]
@powerivq good question. i tried implementing those as "us subdivisions" but they can also be treated as countries. so if i were to implement them i would do them as country implementations instead

**Comment by powerivq** [comment]
@erwinmombay https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes You are correct that Guam, PR and CNMI have their country code. The only exception is the US Virgin Island, which uses US as the country indicator.

**Comment by powerivq** [comment]
@erwinmombay https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes You are correct that Guam, PR and CNMI have their country code. The only exception is the US Virgin Island, which uses US as the country indicator.

**Comment by erwinmombay** [comment]
Ill follow up and look into the Virgin Islands

**Comment by erwinmombay** [comment]
I've verified that the geo detection for the newly added us subdivisions work

**Pull request merged**
