### PR TITLE
Intent to implement: `amp-ad` type for AdServSolutions #25806

### PR DESCRIPTION
**Pull request by adservsolution**
Here is my implementation and documentation of the amp-ad tag for @AdServSolutions as indicated in [#25806](https://github.com/ampproject/amphtml/issues/25806)

### CODE REVIEW

**Comment by adservsolution** [comment]
@googlebot I consent.

**Comment by adservsolution** [comment]
@googlebot I fixed it

**Comment by tarasmatokhniuk** [comment]
@googlebot I consent.

**Comment by adservsolution** [comment]
> ampproject/pr-deploy: Please click the Create a test site button above to deploy the minified build of this PR along with examples from examples/ and test/manual/. It should only take a minute.

I don't have this "Create a test site" button. http://prntscr.com/q4xovz  Can you help me ?

**Comment by adservsolution** [comment]
@amp-pr-deploy , where is "Create a test site" button located? I don't get http://prntscr.com/q4xovz

**Comment by powerivq** [comment]
Hi @adservsolution 

The test site should have been deployed. Can you try it now?

**Comment by adservsolution** [comment]
> The test site should have been deployed. Can you try it now?
@powerivq  Thanks! Site was created

**Comment by tarasmatokhniuk** [comment]
@lannka , All checks have passed. May you merge this pull request, please

**Comment by tarasmatokhniuk** [comment]
@powerivq  How can we merge my implement? Should I do some?

**Pull request merged**
