### PR TITLE
Change failure mode for unsupported FxTypes & add tests for fade-in-{,scroll} presets

### PR DESCRIPTION
**Pull request by nainar**
This PR changes the failure to not halt and break the page if a particular FxType is not supported. 

This PR also adds integration tests for 
- amp-fx="fade-in"
- amp-fx="fade-in-scroll"

Adding parallax tests in a separate PR

### CODE REVIEW

**Comment by nainar** [comment]
Hi @alanorozco just as a headsup I have made a change to this PR to handle failures caused by unsupported fx types much better.

**Comment by rsimha** [comment]
@nainar Seems like the latest commit on this PR is 182d558967868aaec00976af7193bb53b1f5fffe, but Travis thinks your latest commit is 30f145a. That's why Percy isn't linking to this PR.

You can fast-forward your local `master` branch to `upstream/master`, rebase this branch on `master`, and force push the commits. That should fix things.

**Comment by rsimha** [comment]
Looks like this is documented in https://github.com/travis-ci/travis-ci/issues/7251. The rebase I described above should fix things.

**Comment by nainar** [comment]
@rsimha 
I just executed the following commands:
```
git fetch upstream master
git pull
git push upstream fx_tests
```

Travis (https://travis-ci.org/ampproject/amphtml/builds/371376034?utm_source=github_status&utm_medium=notification) still seems to think that the commit is https://github.com/ampproject/amphtml/commit/73eac1c5da7bfd7fae7d137d3a21b799fe101a59. 

My branch for the record is as follows:
fx_tests         a22a35d90 [upstream/master: ahead 17] Merge branch 'master' of github.com:ampproject/amphtml into fade_in_tests

**Comment by rsimha** [comment]
@nainar Here is how I do it.

First, update your local `master` branch
```
git checkout master
git fetch upstream master
git rebase upstream/master
```
Then rebase your working branch on local `master`
```
git checkout <branch name>
git rebase master
```
Finally push your local branch to `origin`
```
git push origin
```
Note that in this case, you'll have to force push your local branch
```
git push origin --force
```

**Comment by nainar** [comment]
Copied these instructions and uploaded the commits. I think it worked? 

The [build](https://travis-ci.org/ampproject/amphtml/builds/371378585) now points to https://github.com/ampproject/amphtml/commit/1c8b2e3cf7984d9a6d9785912cf33c728a22bf1f which has the correct parents.

**Comment by rsimha** [comment]
Yeah, the commits look right this time. Let's see if this works.

**Pull request merged**
