### PR TITLE
🐛 Fix a race condition that may have caused experiment variants to not be available

### LINKED ISSUE #16036: variant service in amp-experiment might have race condition
See https://github.com/ampproject/amphtml/issues/14841

### PR DESCRIPTION
**Pull request by cramforce**
Fixes #16036

### CODE REVIEW

**Comment by lannka** [comment]
I think the root cause is here:
https://github.com/ampproject/amphtml/blob/master/src/element-service.js#L250

I don't know why we choose to return `nullable` for element provided service. Instead, we could have the caller to get a unresolved promise, just like this PR is doing.

**Comment by cramforce** [comment]
@lannka it is nullable, because it is supposed to not never-resolve if the element isn't around. E.g. GA may decide to always report a certain VARIANT if it exists, but still send the request if it isn't defined.

**Comment by cramforce** [comment]
Done.

**Comment by lannka** [comment]
> @lannka it is nullable, because it is supposed to not never-resolve if the element isn't around. E.g. GA may decide to always report a certain VARIANT if it exists, but still send the request if it isn't defined.

@cramforce my understanding this PR does not solve that. this PR will still hold GA from firing if the page has amp-experiment extension but missing amp-experiment element.

**Comment by cramforce** [comment]
@lannka That is correct. Is that not enforced in the validator?
In any case it is much less of a problem, compared to always waiting forever.
This PR just maintains the status quo without the race condition

**Comment by lannka** [comment]
> In any case it is much less of a problem, compared to always waiting forever.

I get that. But my point is the root fix could be [here](https://github.com/ampproject/amphtml/blob/master/src/element-service.js#L250). 

> Is that not enforced in the validator?

This is one of the "legacy" extensions that validator does not enforce. But we I believe we remove them during SSR.

**Comment by cramforce** [comment]
Not sure, I follow, but maybe send a PR? So, you want the promise to start resolving in the case where there is a script but no element? You'd have to wait at least until the DOM was fully parsed to fail, then.

**Comment by lannka** [comment]
```js
        // If this service is provided by an element, then we can't depend on
        // the service (they may not use the element).
        if (opt_element) {
          return getServicePromiseOrNull(win, id);
        } else if (isElementScheduled(win, extension)) {
          return getServicePromise(win, id);
        }
```

I think it's wrong to return `nullable` here for element provided services, given the element can be late scheduled, or dynamically inserted.

We can simplify the code to
```js
if (isElementScheduled(win, extension)) {
  return getServicePromise(win, id);
}
```

**Comment by jpettitt** [comment]
There are a lot of weird edge cases in that code and be very cautious about changes without a very thorough audit of usage.  I do think we need to define and document the expected behavior of services when other services they depend on fail or don't exist.  We're getting into more and more complex interdependencies as amp evolves, I'm kinda surprised we've not yet had a fatal embrace between dependent extensions.

cc @jridgewell

**Comment by jridgewell** [comment]
If we move everything to the pattern we have in this PR, we could remove the `opt_element` check. But it would lead to possible forever pending promises, which seems bad.

**Comment by lannka** [comment]
Should be safe to remove the check. As @cramforce it "maintains the status quo without the race condition". But I agree we need to check all the existing element services to make sure there is no "nullable" usages.

Seems we have to choose between "race conditions" vs "forever promises". I don't see a good way to solve both. The chances of "forever promises" is mostly a bad configuration, which can be mitigated by validator and SSR/reserialization.

**Pull request merged**
