### PR TITLE
Revert "Clean up: remove copies of CSS files under /build/.  (#22457)"

### LINKED ISSUE #22474: Can't run gulp on master
Running `gulp` on master fails:

```
/usr/local/google/home/gmajoulet/amphtml/build/video-autoplay.css:16
i-amphtml-video-mask {
                     ^
ParseError: Unexpected token
```

### PR DESCRIPTION
**Pull request by gmajoulet**
This reverts commit 6aa1b168146edb46afa24e81f6140336be912e37.

Fixes #22474

### CODE REVIEW

**Comment by lannka** [comment]
did you try gulp clean?

**Comment by rsimha** [comment]
> did you try gulp clean?

I was able to repro this from a clean state. It's possible there's a race.

**Comment by lannka** [comment]
the error msg means it imported `build/video-autoplay.css` instead of `build/video-autoplay.css.js`, 

can you check if you do have `build/video-autoplay.css` and its last modification timestamp?

**Comment by gmajoulet** [comment]
I did have `build/video-autoplay.css`

Running `gulp clean` fixed it, thanks. I don't have enough context to know what to do with this PR now, feel free to close it if it's WAI :)

**Comment by rsimha** [comment]
> Looking at the recent builds, they are all green:
> Screen Shot 2019-05-23 at 2 20 59 PM

That's because:
1. We don't run `gulp` (which includes `watch`) on `master`
2. We only build from a clean state on `master`

It shouldn't be a requirement for developers to always build from a clean state. That said, if this is a one off error that will go away, not reverting SGTM.

**Comment by gmajoulet** [comment]
Thanks both of you for the help :)
Closing

**Comment by lannka** [comment]
> We don't run gulp (which includes watch) on master

 My understanding to the code is that `gulp watch` will not create `build/video-autoplay.css` after that PR. but let me know if you do see a posibility

**Pull request closed without merging**
