### PR TITLE
Disallow height customization for root/body

### LINKED ISSUE #2187: amp-iframe issue
Hi,
Setting up iframes in the document body, AMP throw randomly an error with the content of the iframe:
```
<amp-iframe> elements must be positioned outside the first 75% of the viewport or 600px from the top (whichever is smaller): amp-iframe#AMP_13  Current position -1198. Min: 480Positioning rules don't apply for iframes that use `placeholder`.See https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md#iframe-with-placeholder for details.
```
We cannot understand this, because the iframe itself is more than 600px from the top of the document. And the current position show in the error message is just weird (-1198).
Why this error message is throw? Should we only put a placeholder?
Anyway, I think there is a problem in the position calculation…

### PR DESCRIPTION
**Pull request by dvoytenko**
Closes #2187.

### CODE REVIEW

**Comment by cramforce** [comment]
LGTM

**Comment by katopz** [comment]
Hi,

Let say if I want to fill all background color/image for `html` at height 100%, How can I do that?
I tried add `css` add `html` but I think it always get override because of this.

Thanks.

**Comment by dvoytenko** [comment]
@katopz What do you mean at height 100%? Do you mean minimum height of 100%? You should be able to use `min-height: 100vh` or such CSS.

**Comment by katopz** [comment]
@dvoytenko Thanks! `min-height: 100vh` did the trick! :)

**Comment by demil** [comment]
Is there any possibility for body height 100%, not 100vh because vh has bugs ( intended ) on iphone and it is not precise fullscreen, and i need precise fullscreen because in project i am creating ui that simulates mobile app screens which are full width and height? Every other solution instead of simple body and html 100% is hacky, and i think that this handicap of amp css is really problematic. I am currently using fixed containers and this is anti pattern just to get 100% of height.

**Comment by tobiastromm** [comment]
Hi.

I wondering if anyone find a solution for this. I am migrating my page and come to this and can't find a way to fix.

I tryed height: 100vh; do html and body but seens to not work.

**Pull request merged**
