### PR TITLE
🚮 Remove 'full-size' button from media

### PR DESCRIPTION
**Pull request by andreyYatskov**

### CODE REVIEW

**Comment by erwinmombay** [comment]
@andreyYatskov wanted to check. are you a part of apester media?

**Comment by andreyYatskov** [comment]
>

**Review by powerivq — APPROVED** [review]

**Comment by powerivq** [comment]
Can you rebase against the latest main branch to trigger the tests?

**Comment by andreyYatskov** [comment]
@powerivq rebased to main

**Review by erwinmombay — APPROVED** [review]

**Pull request merged**
