### PR TITLE
🐛 amp-recaptcha-input: Fixed single pass tests

### LINKED ISSUE #21009: Unskip Single Pass Integration tests for `amp-recaptcha-input`
relates to #20541 

This code block proves the issue from `amp-recaptcha-service.js`:

screen shot 2019-02-21 at 4 36 51 pm

And see this build from the related PR: https://travis-ci.org/ampproject/amphtml/jobs/496296327

### PR DESCRIPTION
**Pull request by torch2424**
closes #21009 
relates to #20541

Simple fix, added data to the externs as mentioned by @erwinmombay 😄 

Also, this bumps the amp-mustache version, to then get the test fully working.

screen shot 2019-03-04 at 4 15 31 pm

### CODE REVIEW

**Comment by lannka** [comment]
great, so it caught a real bug for single pass!
instead of lengthening the extern file, should we access the data using `data['id']` & `data['token']`?

**Comment by torch2424** [comment]
@lannka Yeah glad that it did! 

I don't think we should use bracket notation in place of lengthening the extern file. Because in the future if we forget, or decide to use the response from the iframe in another function or context, trying to document that will be difficult to avoid errors. Since it can be used (and probably will) in the future.

**Comment by torch2424** [comment]
@danielrozenberg So for the visual diff. It looks like something is broken for AMP Accordian. Is this expected? This PR definitely does not touch the extension, but I just want you to be aware in case this is an actual bug on master?

**Comment by lannka** [comment]
> I don't think we should use bracket notation in place of lengthening the extern file. Because in the future if we forget, or decide to use the response from the iframe in another function or context, trying to document that will be difficult to avoid errors. Since it can be used (and probably will) in the future.

I will let @erwinmombay speak for this. Should we typedef the `data` to be a `JSONObject`?

**Comment by lannka** [comment]
@torch2424 my experience, it should be just a flake for the percy test. You can go in and approve the change in percy.

**Comment by danielrozenberg** [comment]
I'm not sure which one should be the correct output here for the visual diff test. I think it's the `master` one? Try rerunning the visual diffs shard on Travis and let me know if this fixes it :sweat_smile:

**Comment by erwinmombay** [comment]
i actually prefer bracket notation in this instance just because that data definition is not as formal (as a definition) as i want it to be. (its like a dumping ground of properties that we dont want obfuscated LOL)

**Comment by torch2424** [comment]
@lannka @erwinmombay Made the requested change to go to bracket notation. Let me know what you think! 😄

**Comment by torch2424** [comment]
Just waiting for your approval @lannka 😄

**Comment by torch2424** [comment]
@lannka is on vacation, requesting review from @zhouyx 😄

**Comment by torch2424** [comment]
@zhouyx No worries! 😄 Merged...

**Pull request merged**
