### PR TITLE
✨ Added support for IANA timezone code

### PR DESCRIPTION
**Pull request by Manugal**
Recreated from scratch due to erroneous merge with master branch.

This feature adds support for TIMEZONE_CODE since some publishers would like to collect timezone code, because it provides more precise information about an event's time.

IE11 fails silently replacing TIMEZONE_CODE with an empty string. Moreover, I conducted other tests with some mobile browsers that behave similarly:

Android 4.0-4.3 [Stock Browser]: timeZone is undefined and fails silently.
Android 4.4 [WebView in com.android.browser (Version/4.0 Chrome/30.0.0.0)]: timeZone is equal to 'CET'; the object returned by resolvedOptions() contains a field named timeZoneName but it's undefined.
Samsung Internet 5.x: timeZone is undefined

Fix issue #13044

### CODE REVIEW

**Comment by Manugal** [comment]
@zhouyx sorry but you have to review this again. :cry:

**Comment by zhouyx** [comment]
@Manugal You don't need to create a new Pull Request every time you try to pull the latest change from upstream master. Please rebase instead of merge. 
Please refer to
https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md#pull-the-latest-changes
And let me know if you can fix the old PR. Thanks.

**Comment by Manugal** [comment]
@zhouyx Yes I know, I followed the steps described in the end-to-end guide but maybe I did something wrong. After I rebased master into my branch, I pushed my branch and what happened is that it brought all the changes coming from master on my PR and it created the mess. My question is, do I need to rebase master everytime I have to do a little change on my branch? 

Sorry, but I can't fix the old PR I deleted the old branch and re-created a new one and I can't find a way to fix it.

**Comment by zhouyx** [comment]
@Manugal It's recommended that to sync to upstream master, but not really required unless there's conflict. 

Did you follow? Or what command did you run?
```
git checkout master // your local master
git pull
git checkout <branch name>
git rebase master
```

could you also check your git remote setting with 
```
git remote -v
```
and see that you have `upstream` setting as `git@github.com:ampproject/amphtml.git`

**Comment by zhouyx** [comment]
LGTM

**Comment by Manugal** [comment]
> Did you follow? Or what command did you run?
git checkout master // your local master
git pull
git checkout <branch name>
git rebase master

Yes I run these exact commands. Follows the output of `git remove -v` command:

<pre>
<code>amp_origin      git://github.com/amphtml/amphtml.git (fetch)
amp_origin      git://github.com/amphtml/amphtml.git (push)
origin  git@github.com:Manugal/amphtml.git (fetch)
origin  git@github.com:Manugal/amphtml.git (push)</code>
</pre>

As you can see I named the remote as `amp_origin` instead of `upstream`, but I don't think it makes any difference. Or does it? I want to make sure to not doing mistakes in the future.

Btw, thanks for having merged my PR :+1:

**Comment by zhouyx** [comment]
@Manugal I tested with one of my old branch, I tried removing `upstream` and have `amp_origin` instead. However these commands work fine to me. 

I also tried hard to see what could lead to the case that brought all the changes coming from master to my PR. Running `git pull` on the working branch instead of local master branch could lead to the problem. But that won't be the issue if you run `git checkout master` at first place.

**Pull request merged**
