### PR TITLE
✨  Internet AMP video component - Video Load time Reduction in AMP environment

### PR DESCRIPTION
**Pull request by SlikeTech**
Slike Player is the internal video player which is being used at all Times Internet Business inlcuding the subsidiaries of BCCL. Player provides a comprehensive list of functionalities not limiting to offline podcast, live streaming, Third Party Video embedding. We are targetting an AMP Component as all the businesses are trying to opt for web stories and amp-video to have better engagement and traction.

### CODE REVIEW

**Comment by kristoferbaxter** [comment]
Has this been presented at design review?

**Comment by SlikeTech** [comment]
This is a new contribution. Please review.

**Comment by honeybadgerdontcare** [comment]
@SlikeTech please see [Design Reviews](https://github.com/ampproject/amphtml/blob/main/docs/design-reviews.md) as it's an important process for new contributions.

**Comment by SlikeTech** [comment]
amp-slike component is for Design Review. Please do the needful.

**Comment by honeybadgerdontcare** [comment]
@SlikeTech there are upcoming design reviews which you can sign up for. please sign up for one to get this reviewed there. the design review is different from a code / pull-request review. the times vary to help support everyone who may have different time zones. please find one that works for your timezone so that you can be present and answer questions. reply to the design review thread that this will be presented at.

Design reviews: https://github.com/ampproject/amphtml/blob/main/docs/design-reviews.md
Upcoming reviews: https://github.com/ampproject/amphtml/labels/Type%3A%20Design%20Review

**Comment by Gregable** [comment]
Closing as this doesn't have any new updates in a while. Feel free to reopen if this is still active.

**Pull request closed without merging**
