### PR TITLE
Do not hide A4A Ads in Boilerplate

### LINKED ISSUE #5663: A4A: amp4ads-boilerplate setting hidden and not getting cleared
The [A4A format spec](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/amp-a4a-format.md) calls for an [`amp4ads-boilerplate`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/amp-a4a-format.md#boilerplate) block of the style:

```html
<style amp4ads-boilerplate>body{visibility:hidden}</style>
```

This is currently inserted by A4A code [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/0.1/amp-a4a.js#L667).  The assumption was that the AMP runtime CSS would disable this `hidden` attribute, allowing the ad to display.  However, it appears that the `hidden` styling is _not_ currently being disabled, so A4A-compliant ads are never actually displayed.

Proposed fix is to remove the boilerplate insertion from `amp-a4a.js`, but we should revisit this issue in the format spec and/or runtime.

### PR DESCRIPTION
**Pull request by tdrl**
Fixes #5663

### CODE REVIEW

**Comment by lannka** [comment]
Should the ultimate fix be [here](https://github.com/ampproject/amphtml/blob/master/src/style-installer.js#L112)?

**Comment by tdrl** [comment]
Quite possibly.  I've never learned how the hiding/unhiding logic really works.  This was my stab at a quick fix, before we work on a real one.  I agree that the real fix is to make AMP runtime unhide the ad body at an appropriate time, but I don't know enough to easily make that fix myself.

**Comment by lannka** [comment]
Sure, I can help you get started. The code I pointed should be doing the work for you (setting body visibility to visible). Can you debug through to see why it's not called (or called and ended up with unexpected behavior)?

**Comment by keithwrightbos** [comment]
Let's get this change in for now to ensure we get a fix out ASAP.  I have approved the PR.

**Comment by tdrl** [comment]
Exactly.  We have ads not showing in production this moment because of this bug.  Let's get **A** fix out now and work on getting the **right** fix soon.

**Pull request merged**
