### PR TITLE
adding yieldmo to wait for render start list

### PR DESCRIPTION
**Pull request by harquail**
Yieldmo's next JS release implements renderStart

### CODE REVIEW

**Comment by lannka** [comment]
@harquail I suppose all the work is done in your own JS.
Could you please ping the thread when it is released in production so we can turn it on here?

Meanwhile, could you follow up with the CLA robot's to get its OK? :-)

**Comment by harquail** [comment]
I believe Yieldmo has already signed the CLA — is there anything else I need to do?  

Yep.  We'll be releasing this into production later this week — I'll ping you when that happens.

**Comment by lannka** [comment]
Sorry, we just changed the config file format (to reduce the chance of merge conflicts in future). Could you please sync to head and update your change?

For CLA, can you follow the following to see if we can please the robot.

> If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data and verify that your email is set on your git commits.
> If you signed the CLA as a corporation, please let us know the company's name.

**Comment by harquail** [comment]
will do!

**Comment by harquail** [comment]
@lannka — we pushed renderStart to production on our side, so this should be ready to merge after we resolve the CLA issue for @yieldmo-rao

**Comment by yieldmo-rao** [comment]
I signed the CLA again.

**Comment by yieldmo-rao** [comment]
I'll update the README with a gif of 2 examples of what multi sized ad requests look like. Please hold off on merging until then. Thanks!

**Comment by lannka** [comment]
@yieldmo-rao I saw you've updated the GIF. Is it ready to be merged now?

**Comment by yieldmo-rao** [comment]
@lannka Yes sir! Updated the gifs and ready to be merged in! Thanks!

**Comment by lannka** [comment]
> We found a Contributor License Agreement for you (the sender of this pull request) and all commit authors, but as best as we can tell these commits were authored by someone else. If that's the case, please add them to this pull request and have them confirm that they're okay with these commits being contributed to Google. If we're mistaken and you did author these commits, just reply here to confirm.

@erwinmombay @cramforce the first sentence sounds contradictory itself to me. Do you know what should they do?

@yieldmo-rao did you use the same email in your git commit?

**Comment by yieldmo-rao** [comment]
@lannka Yep - used the same: rao@yieldmo.com.

**Comment by yieldmo-rao** [comment]
@lannka BTW, if an issue persists, in the interest of time, I'm happy to have all the commits squashed and force pushed by @harquail .

**Comment by lannka** [comment]
@yieldmo-rao that probably would help, could you try? thanks

**Comment by harquail** [comment]
squashed!

**Comment by yieldmo-rao** [comment]
@lannka Win! Happy googlebot! Thanks, @harquail

**Comment by lannka** [comment]
i'm restarting the travis test (was flaky). will merge once it's green

**Pull request merged**
