### PR TITLE
Taboola: fixing typo. the Taboola script supports type "other" not "others".

### PR DESCRIPTION
**Pull request by michaeld79**
fixing typo.

The Taboola script supports type "other" not "others".
code with "data-others" will not load the Taboola widget.

### CODE REVIEW

**Comment by michaeld79** [comment]
@ampprojectbot retry! 
we have a customer at taboola that is waiting for this fix.
any chance of expediting in reviewing this pull request? 

thanks ,
michael dragatski

**Comment by nitzanvolman** [comment]
@ampprojectbot retry!

**Comment by zhouyx** [comment]
Hi @michaeld79 The PR looks good. However travis is failing on a unrelated flaky test. The test has been fixed already. Can you rebase and commit again?

**Comment by michaeld79** [comment]
@zhouyx i merged all changes since the PR but i see it messed up the branch with all other commits. 
should i create a new one with just my changes?

**Comment by zhouyx** [comment]
Sure! whichever way you prefer. Please assign the new PR to me.  😄

**Comment by michaeld79** [comment]
@zhouyx created another clean pull request [https://github.com/ampproject/amphtml/pull/8744](https://github.com/ampproject/amphtml/pull/8744) so it can be reviewed and merged easy :)

**Pull request closed without merging**
