### PR TITLE
✅Add visual tests for amp-autocomplete

### PR DESCRIPTION
**Pull request by caroqliu**
Add visual tests for amp-autocomplete rendering and displaying items on focus for two test cases: plain-text inline data and rich text templated remote data. 

Note: Visual tests pass when running `gulp` but not when running `gulp build --fortesting && gulp serve` — there is a discrepancy when rendering list item elements from a template (second test case). Further investigation required.

### CODE REVIEW

**Comment by cvializ** [comment]
@danielrozenberg are you aware of any differences between these? @caroqliu does that test case work as expected and without any console errors when you manually load the document?

**Comment by danielrozenberg** [comment]
Hmm... you shouldn't run `gulp serve` if you intend to run `gulp visual-diff --whatever`, because `gulp visual-diff` runs its own server internally.

Try doing:
```
gulp clean
gulp build --fortesting
gulp visual-diff --no-build --percy_project ampproject/[[YOUR_PERCY_PROJECT]] --percy_token [[YOUR_PERCY_TOKEN]] --grep "amp-autocomplete"
```

And tell me what's happening

**Comment by caroqliu** [comment]
@danielrozenberg Thanks for the advice. The first test passes in any case. When the `--fortesting` flag is present, the second test often fails (flaky at best) both when using `gulp visual-diff ...` or when manually loading the document. The expected behavior is to see additional elements on the page after focusing on the input element, but the actual behavior is that none appear. 

After running the commands you gave me, the test fails with the following:
```
[10:38:51] VERBOSE: Found 1 element(s) matching the CSS selector amp-autocomplete#autocomplete2 > .i-amphtml-autocomplete-results
[10:38:51] VERBOSE: Expecting all element visibilities to be true ; they are false
[10:38:51] ERROR: Error in test amp-autocomplete (tap input2 to focus and display results) 
   Unknown failure in test page 
   Error: amp-autocomplete (tap input2 to focus and display results) | An element with the CSS selector amp-autocomplete#autocomplete2 > .i-amphtml-autocomplete-results is still invisible after 10000 ms
    at verifySelectorsVisible (/Users/carolineliu/amp/amphtml/build-system/tasks/visual-diff/helpers.js:107:13)
[10:38:52] FATAL: Some tests have failed locally.
Percy is now processing. You can view the visual diffs here: https://percy.io/ampproject/caroqliu/builds/1771641
```

For reference, this is an example of a passing-as-expected build: https://percy.io/ampproject/caroqliu/builds/1726382

/cc @cvializ

**Comment by caroqliu** [comment]
Splitting this change up into #22045 and #22047

**Pull request closed without merging**
