### PR TITLE
🐛 Add trailing slash to event endpoint to return gif in response to GET request

### PR DESCRIPTION
**Pull request by tygavin**
Minor update for console warning.

The trailing / included in the collect.tealiumiq.com endpoint will ensure an "image/gif" HTTP response instead of the current "application/json" response.

The current application/json response resulted in console warning messages when the browser is looking for a response that has Content-Length greater than 0.  This fixes the warning message.

### CODE REVIEW

**Comment by tygavin** [comment]
@jeffjose A minor update for Tealium requires review.  Thanks for your help.

**Comment by jeffjose** [comment]
LGTM from my side. Over to @lannka for approvals.

**Comment by avimehta** [comment]
@lannka or @zhouyx: Do you mind merging. I technically can but since you are the owners, I don't want to step on your toes.

**Comment by lannka** [comment]
thanks Avi

**Comment by zhouyx** [comment]
Thank you @avimehta!

@rcebulko another question, can we keep Avi as the owner but not having the owner bot automatically request reviews from them. Otherwise they'll get a lot of review requests 😈

**Comment by rcebulko** [comment]
You can prefix his username in the OWNERS.yaml file with `?`, ie. `- "?avimehta"` and he will never be automatically requested as reviewer.

**Comment by zhouyx** [comment]
Thanks! Will summit a PR.

**Pull request merged**
