### PR TITLE
🐛 Make amp-consent position: fixed !important

### PR DESCRIPTION
**Pull request by alanorozco**
Since this component is always filled asynchronously, not forcing it `fixed` causes content shift.

### CODE REVIEW

**Comment by zhouyx** [comment]
@gmajoulet I wonder why all the visual tests for story consent are all failing. Also FYI the amp.dev [example](https://amp.dev/documentation/examples/user-consent/story_user_consent/?format=websites ) doesn't seem to work

**Comment by zhouyx** [comment]
I'd like to also get @jeffjose opinion on the potential breaking change, and if we want to ship the fix with a notice.

**Comment by gmajoulet** [comment]
> Also FYI the amp.dev example doesn't seem to work

What's broken for you? The playground example seems to work, are you having issues when running the code locally?

**Comment by zhouyx** [comment]
@gmajoulet here's the link
https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fuser-consent%2Fstory_user_consent&format=websites&_gl=1*1s24cds*_ga*YW1wLThhNVdmY3ptbnh6dVBLQjRRZkFVS0E.

**Comment by zhouyx** [comment]
AMP forces !important to avoid any layout shift that's caused by the consent dialog.

To place the optout window at the bottom of the page, one can do that via a regular <div> and then use the <amp-geo> supported feature to toggle the visibility of that div based on users geo location. Please refer to the amp-geo doc for more information.

Thank you.

**Pull request merged**
