### PR TITLE
Cleanup story navigation performance experiment.

### LINKED ISSUE #17017: Story page to page navigation improvements.
Improve the amp-story navigation performance.
We're trying to improve the time between the user tap to navigate to the next page, and the actual moment where the next page is displayed and playing.

There are two areas we should look into:

#### (1) `story.switchTo_` method

Actual method responsible for displaying the next page, performing the play/pause/rewind/mute/unmute/... media operations, preloading the next pages, sending analytics events, etc.

#### (2) Everything that happens in between the user interaction and the `switchTo` method

The code path between the user interaction to navigate to the next page and the `switchTo` method consists in several back and forth of events between the `amp-story-page` and the `amp-story`. We don't really know how fast this is, and should audit it to assess if it's worth refactoring.

### LINKED ISSUE #17018: Clean up amp-story-navigation-performance experiment

### PR DESCRIPTION
**Pull request by gmajoulet**
Cleanup the launched `amp-story-navigation-performance` experiment.

Fixes #17018

### CODE REVIEW

**Comment by gmajoulet** [comment]
cc @choumx 
I'm removing the code using that experiment in #17665, how long should I wait before removing the experiment from the config after the code stops using it?

**Comment by newmuis** [comment]
AFAIK, our configs are actually still just rolled into the same build, so as long as this goes in at the same time or after #17665 this should be okay.  @choumx probably knows more.

**Comment by choumx** [comment]
To be safe, I'd wait until the code guards are in production first. Also, there's a presubmit check that flag flips be separate from any other code changes (including experiments.js).

**Comment by gmajoulet** [comment]
So the process would be:

- Delete the code using the experiment and wait for it to be in prod
- Delete the experiment config
- Delete the experiment from experiments.js

Does that sound correct?

**Comment by choumx** [comment]
Yep.

**Pull request merged**
