### PR TITLE
Improve word choice.

### PR DESCRIPTION
**Pull request by jaepage**
I stumble on the word "only" here. Is it meant as "solely" (exclusively) or "except" (but)?

### CODE REVIEW

**Comment by aghassemi** [comment]
@jaepage Thanks @jaepage. It is meant as solely. Please take a moment to sign the CLA and we can get this merged.

**Comment by jaepage** [comment]
I signed it!

**Comment by aghassemi** [comment]
@jaepage your commit email (username@users.noreply.github.com) may not be matching the email you signed the CLA with. Please check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

**Comment by jaepage** [comment]
Your system isn't letting me change my email address nor get a new CLA.

**Comment by aghassemi** [comment]
@jaepage You should be able to set the default git email address using `git config --global user.email "email_you_signed_CLA_with@example.com"` and then you can do a new commit here or another PR altogether. Sorry for the complicated process, fortunately it is a one-time process and after it you can contribute to all Google OSS projects.

**Comment by jaepage** [comment]
The email address in your CLA is incorrect, not in my Git.

**Comment by aghassemi** [comment]
@jaepage Could you please visit https://cla.developers.google.com/clas and then "Edit Contact Information" and ensure the correct Github username `jaepage` is added there?

**Comment by jaepage** [comment]
Please stop at-pinging me. I'm already subscribed to the thread.

**Comment by jaepage** [comment]
Could you please advise instead how to change the email address in your CLA for me? Thank you.

**Comment by aghassemi** [comment]
The email address for CLA is associated with the Google account you were signed in with and can not be changed. Adding your Github username in Edit Contact Information section of "Manage your agreements" should be enough to unblock this however

**Comment by jaepage** [comment]
Am I not able to sign without associating with a Google Account?

**Comment by aghassemi** [comment]
Yes, https://cla.developers.google.com/  requires you to login to sign the CLA.

**Pull request closed without merging**
