### PR TITLE
Use 'gulp-load-plugins' to load gulp plugins

### PR DESCRIPTION
**Pull request by ataylorme**
Use [gulp-load-plugins](https://www.npmjs.com/package/gulp-load-plugins) to load gulp plugins, reducing the number of variables and require functions for including gulp plugins.

### CODE REVIEW

**Comment by erwinmombay** [comment]
:+1:

**Comment by erwinmombay** [comment]
i usually use `$$` as my alias, @jridgewell do you have a preference?

**Comment by ataylorme** [comment]
> i usually use $$ as my alias, @jridgewell do you have a preference?
@erwinmombay I'm happy to update the variable name to whatever is preferred - just let me know.

**Comment by jridgewell** [comment]
`$$` sounds good to me.

**Comment by erwinmombay** [comment]
@ataylorme if you could replace it with `$$` that would be awesome, thanks so much for this! definitely makes our gulpfile less noisier

**Comment by ataylorme** [comment]
> thanks so much for this! definitely makes our gulpfile less noisier
@erwinmombay my pleasure! thank you for following up and merging so quickly.

**Pull request merged**
