### PR TITLE
Update _config.js

### PR DESCRIPTION
**Pull request by vidyome**

### CODE REVIEW

**Comment by vidyome** [comment]
Hello @newmuis ,
I cannot view the error log. Can you help me?
Best.
https://travis-ci.org/ampproject/amphtml/jobs/648754406

**Comment by powerivq** [comment]
Look like a flaky test to me.

**Comment by vidyome** [comment]
Is there anything we have to do?

**Comment by powerivq** [comment]
@vidyome yeah you can do a rebase and then push.

**Pull request closed without merging**
