### PR TITLE
Revert "Launch inabox-viewport-friendly (#25622)"

### PR DESCRIPTION
**Pull request by zombifier**
This reverts commit e135c18c9460d4834578d6809ae5f77a1e3a231a.

Reason: non-neutral metrics.

### CODE REVIEW

**Comment by lannka** [comment]
Thanks @zombifier . could you file an cherrypick request using this [link](https://github.com/ampproject/amphtml/issues/new?title=%F0%9F%8C%B8%20Cherry%20pick%20request%20for%20%3CYOUR_ISSUE_NUMBER%3E%20into%20%3CRELEASE_ISSUE_NUMBER%3E%20%28Pending%29&template=cherry_pick_template.md)

We don't need to cherrypick prod, only canary/RC is needed.

**Comment by lannka** [comment]
The release to be cherrypicked: https://github.com/ampproject/amphtml/issues/25861

**Comment by zombifier** [comment]
Made #25878. Please assign people since I don't think I can.

**Pull request merged**
