### PR TITLE
Fix src examples

### PR DESCRIPTION
**Pull request by kassyn**
FIles:

* examples/article.amp.html - path the images are incorrect
* examples/everything.amp.html - path the video is incorrect
* examples/released.amp.html - path the video is incorrect

### CODE REVIEW

**Comment by dvoytenko** [comment]
Thanks a lot! Looks great. Could you please sign the CLA?

**Comment by erwinmombay** [comment]
wouldnt this break `examples.build` ? (i can't remember what we use `examples.build/` for)

**Comment by dvoytenko** [comment]
That's right. We do need to have `examples.build` working. Hmm. Should we copy resources from `examples` to `examples.build`?

**Comment by kassyn** [comment]
I signed it CLA, my email kassyntec@gmail.com

**Comment by erwinmombay** [comment]
we certainly could copy it.

@kassyn do you mind explaining when it breaks? (did you start up the webserver etc)

**Comment by dvoytenko** [comment]
Erwin, basically, if you copy the examples in a sub-directory on a webserver - it's broken. I've run into this as well. Just had to do copying/fixing manually...

**Comment by kassyn** [comment]
@dvoytenko that's rigth, it's my case.

**Comment by erwinmombay** [comment]
@kassyn do you mind rebasing?

ill merge once i get in https://github.com/ampproject/amphtml/pull/658.

appreciate it, thanks!

**Comment by kassyn** [comment]
@erwinmombay that's nice. I hope this helps!

**Comment by erwinmombay** [comment]
@kassyn yep, definitely does :+1: thanks again.

make sure to force push to your branch so that the PR turns green :smile:

**Comment by erwinmombay** [comment]
@kassyn do you mind squashing this into 1 commit?

**Comment by erwinmombay** [comment]
oh and pulling in latest again :( sorry bout that

**Comment by kassyn** [comment]
@erwinmombay no.

**Comment by dvoytenko** [comment]
Thanks! LGTM, but please rebase so I can merge.

**Comment by dvoytenko** [comment]
@kassyn Thanks for the PR, but I need it rebased to be able to merge. Could you please rebase?

**Comment by kassyn** [comment]
@dvoytenko rebase my branch with branch master?

**Comment by dvoytenko** [comment]
@kassyn with ampproject/amphtml (upstream) master. This is the only way I can merge.

**Comment by erwinmombay** [comment]
@dvoytenko lets just rebase this ourselves locally and merge/rebase it onto master. probably quicker that way. (this is how we do it on the other github projects i work on since people are less active on PR's etc and we dont want to pollute master with merges)

**Comment by erwinmombay** [comment]
@dvoytenko nevermind, protected branches just stops us from pushing to master =/

**Comment by kassyn** [comment]
@dvoytenko do you want me make or you do?

**Comment by dvoytenko** [comment]
@kassyn  @erwinmombay is looking into it.

**Comment by erwinmombay** [comment]
closing.

landed on https://github.com/ampproject/amphtml/commit/0782b3385b461894c8108a959969cc1ff2cb8f55
and https://github.com/ampproject/amphtml/commit/0782b3385b461894c8108a959969cc1ff2cb8f55

**Pull request closed without merging**
