### PR TITLE
🖍 Increase CSS byte limit from 50000 bytes to 75000 bytes

### PR DESCRIPTION
**Pull request by kristoferbaxter**
Increase allowed css byte_limit in validation. This PR implements #26466

Please note: Haven't made changes in this section of the codebase before, a more thorough review is appreciated.

**Edit**: Incorrect # reference for implementation.

### CODE REVIEW

**Comment by Gregable** [comment]
cc @ampproject/wg-amp4email since this effects the email spec too.

Not sure who to cc on the amp actions side.

**Comment by westonruter** [comment]
> This PR implements #26094

@kristoferbaxter Isn't it actually implementing #26466 (and/or #4555)?

**Comment by kristoferbaxter** [comment]
Updated description, thanks @westonruter.

**Comment by nainar** [comment]
Will raise this as a discussion point at the next @ampproject/wg-amp4email meeting.

**Comment by kristoferbaxter** [comment]
@nainar When is the next meeting? Considering splitting the email spec change to a separate PR.

**Comment by nainar** [comment]
The next meeting is on 13 Feb (PST timezone). We can make the Email change separately if the limits are exposed separately for sure.

**Comment by nainar** [comment]
@ampproject/wg-approvers for approval. 

cc @cramforce @dvoytenko @choumx 

@kristoferbaxter can we pull the Email change out of this PR?

**Comment by dvoytenko** [comment]
👍

**Comment by kristoferbaxter** [comment]
Thanks Raghu. I’ll add the appropriate items into this PR.

**Comment by kristoferbaxter** [comment]
@Crystalonscript

Can you approve the markdown change so we can move forward with this commit?

**Comment by nainar** [comment]
Chatted with @ianba for AMP Actions and they don't have a preference between:

1. Stay the same at 50k OR
2. Increase to 75k.

So feel free to do whichever is easier.

**Comment by kristoferbaxter** [comment]
Thanks Naina!

**Comment by westonruter** [comment]
Now that this has been merged, is it right that the it would be released as stable with changes deployed to the validator on the Tuesday after next? In other words, would this be live on February 18th?

**Comment by Gregable** [comment]
We'll update the thread when it gets released.

**Comment by westonruter** [comment]
OK, just looking to get an idea for when this will be live so that we can ensure the AMP WordPress plugin is updated as soon as possible to take advantage of the increased limit.

**Comment by Gregable** [comment]
Your timeline is the right order of magnitude, but since this constant has never changed, there may be some internal tooling (updating test goldens and so forth) the AMP Cache needs to do when this gets pulled in which could delay release. Therefore, I don't want to commit to that timeline.

**Comment by Gregable** [comment]
This has been rolled out.

**Pull request merged**
