### PR TITLE
Moved cid-impl to src folder (Fixes #9713)

### LINKED ISSUE #9713: Promote CID related code to core (out of amp-analytics)
### First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

### What you will need to know
- Some familiarity with JavaScript

### Background
[What is CID?](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#client-id) 

### Motivation
When introduced, CID was only used in `amp-analytics`. So the corresponding logic is kept inside `amp-analytics` extension.
However, many extensions need CID, hence depend on amp-analyitcs to load. We could remove the dependencies once get CID promoted to core.
- amp-user-notification
- amp-ad
- amp-access
- Any place needs CLIENT_ID in URL substitution

See original issue #4898

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] Move [cid-impl.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/cid-impl.js) to `src/`, and update all the references.
- [ ] You might also move all its dependencies (if any) and tests over to corresponding place.
- [ ] Do some manual test and sanity check.
- [ ] Update the descriptions of those the extension who currently depend on amp-analytics to load. 
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review) and request a code review from me (@lannka).  Mention `Fixes #9713 ` in the description.
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

### PR DESCRIPTION
**Pull request by ui-xp**
@lannka

Moved **cid-impl** into the src folder, and updated the references. Let me know if I missed something!

closes #9713

### CODE REVIEW

**Comment by ui-xp** [comment]
I signed it!

**Comment by cramforce** [comment]
Thanks! @lannka Could you evaluate this in terms of code size impact on main binary? Thanks! Have we started late loading the polyfill for WebCrypto yet?

**Comment by lannka** [comment]
@ui-xp this is awesome! will take a look tmr.

@cramforce yes, the lazy load of crypto polyfill work has been done.

**Comment by jridgewell** [comment]
Was this already in the main binary?

**Comment by ui-xp** [comment]
@lannka Just pushed an update to the branch, in amp-user-notification.md I removed the part saying the amp-analytics script was required, is that what you meant?

https://github.com/ui-xp/amphtml/commit/bbac5773e39a9219b2a6b5eb3d30256685688ae1

**Comment by lannka** [comment]
@jridgewell no, the code was under amp-analytics extension.

**Comment by lannka** [comment]
@ui-xp you will want to rebase to exclude irrelevant files from the PR.
I typically do:
- sync master to head
- go to this branch and merge with master.

Googlebot is flaky, hope it will recognize in your next commit.

**Comment by jridgewell** [comment]
Ooo, bad merge. Hard to tell now, but I couldn't see how this was being included in the main binary (besides just being moved into `/src`, which won't do it on its own).

**Comment by ui-xp** [comment]
@lannka Should be up to date with master now. If there is anything I should do lemme know!

**Comment by lannka** [comment]
@ui-xp did it work? there are still 96 files in the PR.

**Pull request closed without merging**
