### PR TITLE
Disable SauceLab's Chrome 45 Environment

### PR DESCRIPTION
**Pull request by jridgewell**
It's sooooo slow it's killing our Travis builds.

### CODE REVIEW

**Comment by dvoytenko** [comment]
What was the reason for including Chrome 45? Was it b/c of the Chrome's prototype changes? If so, it might be helpful tests. We did run into some bugs with this previously...

**Comment by jridgewell** [comment]
Let's re-enable it next week.

**Comment by dvoytenko** [comment]
Please file a bug to re-enable for next sprint.

**Comment by jridgewell** [comment]
https://github.com/ampproject/amphtml/issues/9030

**Pull request merged**
