### PR TITLE
✨ Enable typeahead with a suggest-first attribute on amp-autocomplete.

### PR DESCRIPTION
**Pull request by caroqliu**
Reads and responds to `suggest-first` attribute to support typeahead. Note: This feature only works when `filter=prefix` is also present on the component. Example below.
- On input, if `suggest-first` is present, the component will update the active item to the first item in the rendered results and highlight the supplemental portion of the completed user input.
- Directly monitors if `Backspace` is pressed so as to allow rejecting the highlighted portion without re-rendering it as a new input. This can be more cleanly replaced with the `inputType` property on the `inputEvent` when it is supported across all browsers.
- Adds examples and unit tests for this change
- Adds the `Backspace` key to common `key-codes.js`

eb4a992b-72ac-4da7-b6a7-b7bdff37d4df

### CODE REVIEW

**Comment by cvializ** [comment]
Awesome! The interaction is really smooth 😎 My only thought is should the non-user-typed portion be highlighted when the user arrows up and down in the list of multiple results? I see that the selection range is cleared and the cursor moves to the end when the user arrows up and down. What do you think?

**Comment by caroqliu** [comment]
> Awesome! The interaction is really smooth 😎 My only thought is should the non-user-typed portion be highlighted when the user arrows up and down in the list of multiple results? I see that the selection range is cleared and the cursor moves to the end when the user arrows up and down. What do you think?

@cvializ - @andrewwatterson and I discussed this some and decided to go with highlighting all options if navigated to. What do you think about enforcing the `prefix` filter? Currently `suggest-first` will silently fail if any other filter type is designated. How do you decide whether to keep this, or error, or ignore other filter types and just enforce `prefix`?

**Comment by cvializ** [comment]
I think this comes down to devx. What will help developers create their component with the least friction. I think adding a runtime error and a validator rule could be effective, since the runtime error will allow developers to see their mistake in the console, and the validator will prevent pages that use broken attribute combinations from being cached.

**Comment by caroqliu** [comment]
I added a `user().error` as well as modified the validator rules to require the presence of the `filter` attribute if `suggest-first` is present. Unfortunately it cannot further specify that the value of `filter` has to be `prefix` without adding an entirely new tag spec that just matches these conditions while also allowing for combinations of the other attributes.

**Pull request merged**
