### PR TITLE
🐛[amp-analytics] Made changes to bluetriangle.json to suppress warnings and to use image transport, fixed an ssl calculation bug

### PR DESCRIPTION
**Pull request by AdrianPerry**
This pull request will now have the JSON config of blue triangle use image transport and suppress any warnings in the console. It also fixes a bug where the SSL time was not being properly calculated.

@ampproject/wg-analytics

### CODE REVIEW

**Comment by AdrianPerry** [comment]
@micajuine-ho

**Comment by micajuine-ho** [comment]
@AdrianPerry tag @ampproject/wg-components for future reviews, @ampproject/wg-analytics  is deprecated :D

**Review by micajuine-ho — CHANGES_REQUESTED** [review]
You will need to make changes to `extensions/amp-analytics/0.1/test/vendor-requests.json` as well (test file that changes when you change the vendor config)

**Comment by AdrianPerry** [comment]
done

**Review by micajuine-ho — APPROVED** [review]

**Pull request merged**
