### PR TITLE
[amp-pan-zoom] Fix bug where zoom breaks after toggling display

### PR DESCRIPTION
**Pull request by cathyxz**
Fixes https://github.com/ampproject/amphtml/issues/17406. The resetContentDimensions in pauseCallback was originally made to reset after swiping between images in lightbox since carousel would call pauseCallback. Not applicable for current use case, though we may want to tweak it once we refactor `image-viewer` to use this.

### CODE REVIEW

**Comment by cathyxz** [comment]
@cvializ yes it is. But strangely only the first time it's toggled.

**Comment by cvializ** [comment]
Weird, I wonder if that behavior is supposed to happen according to the `CustomElement` lifecycle docs. It looks like it should only be called when the ampdoc becomes inactive, not the individual element becoming invisible. @jridgewell can you confirm if this is expected behavior?

https://github.com/ampproject/amphtml/blob/43be5f5cdad2097c5ca56e33fdb625e3dccc81fe/src/custom-element.js#L1172-L1179

**Comment by jridgewell** [comment]
Yes, it's expected.

**Comment by jridgewell** [comment]
It's not a bug. When a component becomes hidden, `pauseCallback` then` unlayoutCallback` is called.

**Comment by cathyxz** [comment]
Oh okay. Cool. Yes, that matches the behavior that I'm observing, so I think all's good.

**Comment by cvializ** [comment]
Is this behavior documented anywhere? That jsdoc comment should be updated to fully describe the lifecycle

**Pull request merged**
