### PR TITLE
amp-ad: add type=adagio ad network implementation

### PR DESCRIPTION
**Pull request by FiR3N3T**
The PR implements support to delivery ad.agio advertising ad.agio is an adserver developed by Neodata (www.neodatagroup.com)

### CODE REVIEW

**Comment by FiR3N3T** [comment]
Just signed as CLA

**Comment by FiR3N3T** [comment]
Can someone review this PR please?

**Comment by erwinmombay** [comment]
@zhouyx @lannka please review

**Comment by FiR3N3T** [comment]
@lannka renderStart implemented

**Comment by lannka** [comment]
@FiR3N3T did you forget upload your commit? I don't see it.

**Comment by FiR3N3T** [comment]
I signed it!

**Comment by FiR3N3T** [comment]
Just signed as CLA

**Comment by FiR3N3T** [comment]
Just signed as CLA

**Comment by kul3r4** [comment]
@lannka  PTAL

**Comment by lannka** [comment]
@erwinmombay can you help to merge?

**Comment by FiR3N3T** [comment]
thank you @all

**Pull request merged**
