### PR TITLE
Turned on 3p-frame-context-in-name experiment flag in prod

### PR DESCRIPTION
**Pull request by bradfrizzell**
This is the flag as in #6498

### CODE REVIEW

**Comment by jridgewell** [comment]
This needs to be tested in canary first.

**Comment by lannka** [comment]
Oh right, we need also change `canary-config.json`.
Since we're in release freeze for prod. Let's just do the `prod-config.json` in a later PR.

**Comment by lannka** [comment]
I found the canary flag change #6858 has not been cut in the previous release. @muxin can you confirm?

**Comment by muxin** [comment]
According to @erwinmombay, when we are doing release, we always pick up master HEAD for configs.

**Comment by muxin** [comment]
The last canary release was Dec 21 and I'm about to do the new canary release. The config flag should be online tomorrow.

**Comment by lannka** [comment]
OK, let's merge this PR later after we verified in canary.

**Comment by bradfrizzell** [comment]
sounds good

**Comment by lannka** [comment]
Verified in canary, no new suspicious errors.

**Comment by aghassemi** [comment]
@lannka @bradfrizzell Okay for this to be in this week's Canary? (cutting a new one)

**Comment by lannka** [comment]
yes please. :-)

**Comment by bradfrizzell** [comment]
thanks!

**Pull request merged**
