### PR TITLE
Validator rollup

### PR DESCRIPTION
**Pull request by banaag**
- cl/343904483 Implements gated module/nomodule validation with test cases
 - cl/343164010 Revision bump for #31241

### CODE REVIEW

**Review by honeybadgerdontcare — APPROVED** [review]
Thanks for pushing this important pr forward

**Comment by honeybadgerdontcare** [comment]
@rsimha we are doing a validation check against `cdn.ampproject.` in our validator code. Travis is complaining about it. Where do we submit an exception for this?

```
[19:21:16] Found forbidden: "cdn.ampproject." in validator/js/engine/htmlparser-interface.js:271:33
```

**Comment by honeybadgerdontcare** [comment]
@rsimha I think I got it right in [this commit](https://github.com/ampproject/amphtml/pull/31316/commits/9f6a4678fff1b726e53a35878869a7eafa3f2fc1).

**Review by rcebulko — APPROVED** [review]
approving `build-system/tasks/presubmit-checks.js`

**Comment by honeybadgerdontcare** [comment]
There was a problem with this PR as it's missing some code that should have been included. That code is in PR #31373. To keep things simple we're closing this and once that PR is merged will do another rollup.

**Pull request closed without merging**
