### PR TITLE
✨ Criteo: Add uid and pid macro to amp endpoint

### PR DESCRIPTION
**Pull request by vraybaud**
Hello, 

We are improving our inventory management and will rely on uid and pid query parameters in the future. But we are still needing the old query parameters during the transition. 

Please could you review this ?
Thanks !

### CODE REVIEW

**Review by powerivq — APPROVED** [review]

**Comment by powerivq** [comment]
Hello @vraybaud can you sign the CLA following the link in the above message? It is required before we can merge the PR.

**Comment by powerivq** [comment]
Furthermore, you need to rebase against the latest main branch. It is why the test has failed.

**Comment by vraybaud** [comment]
@powerivq Thanks a lot for the very fast review ! I did the rebase.

**Comment by powerivq** [comment]
@vraybaud Please fix

```
[11:01:32] src/service/real-time-config/callout-vendors.js
  81:21  error  Insert `,`  prettier/prettier
```

**Pull request merged**
