### PR TITLE
Change admanmedia ssp endpoint url

### PR DESCRIPTION
**Pull request by admanmedia**
- Change the adman ssp subdomain name.
- Remove unnecessary id setting code.
- Change sample test id.

### CODE REVIEW

**Review by calebcordry — APPROVED** [review]
Thanks for maintaining this extension! Let me know if you have any issues with the CLA

**Comment by calebcordry** [comment]
Looks like you also have a couple small lint errors. You can expose them locally by using `gulp lint`

**Comment by admanmedia** [comment]
We've already signed the SLA but the CLA button still shows as 'not signed yet'

**Comment by mkatogi** [comment]
Now it seems to be OK. PR author had to sign the CLA.

**Comment by admanmedia** [comment]
Now it seems to be OK. PR author had to sign the CLA.

**Pull request merged**
