### PR TITLE
🐛 updateInViewport for children in amp-carousel 0.2

### LINKED ISSUE #26936: amp-img inside amp-carousel inside amp-lightbox does only show three images
## What's the issue?

I'm using amp-carousel containing more than three amp-img's. amp-carousel is used inside amp-lightbox. The carousel only shows three images.

## How do we reproduce the issue?

http://amp-img-amp-carousel-amp-lightbox-bug.jelley.fish/

1. Open link
2. Click "open lightbox" click through images
3. Only first three images are visible

## What browsers are affected?

All browsers

## Which AMP version is affected?

Current and maybe all?

### PR DESCRIPTION
**Pull request by alanorozco**
Fixes #26936

### CODE REVIEW

**Comment by j3ll3yfi5h** [comment]
@wassgha How long does it take, until this fix is rolled out? I really need it for a project, which should be released in the next two weeks...

**Comment by j3ll3yfi5h** [comment]
@alanorozco Why is it still blocked?

**Comment by j3ll3yfi5h** [comment]
Hi @wassgha and @alanorozco 
What is wrong with this fix? Why did these tests fail? How can we accelerate the merge?

Or: How can I use/implement this merge in my production project? What is the workaround for using it before it is merged?

**Comment by alanorozco** [comment]
@j3ll3yfi5h This fix doesn't actually work, unfortunately. Closing and triaging the issue.

**Pull request closed without merging**
