### PR TITLE
Include Slack channel in Support page

### PR DESCRIPTION
**Pull request by morsssss**
📖  I figured we should include the Slack channel on [our Support page](https://amp.dev/support)!

If you think we shouldn't, please comment here....

### CODE REVIEW

**Comment by mrjoro** [comment]
We used to have this, but the result was most people were going to Slack to ask questions about using AMP instead of discussing how to build AMP, which made it hard to use Slack for the intended purpose.  The compromise we reached at the time was to not advertise the Slack for questions, but to create the #using-amp channel for questions about using AMP.

**Comment by morsssss** [comment]
Oh, I see! That makes sense, then.

So people currently learn about the Slack channel simply by word of mouth?

**Comment by mrjoro** [comment]
For people contributing to AMP, we link to Slack in a lot of the docs on GitHub.

For people using AMP, the ideal situation would be for them to use StackOverflow, so the #using-amp channel in Slack is more of a backup for people who end up there somehow.

**Comment by morsssss** [comment]
Got it.

I've just removed the Slack channel bit, leaving only the minor grammatical fix to the line above.

(Or is that "grammar fix"? Grammar is hard)

**Pull request merged**
