### PR TITLE
Fix and unskip more tests that were disabled due to lolex upgrade

### PR DESCRIPTION
**Pull request by rsimha-amp**
Follow up to #12486

### CODE REVIEW

**Comment by cathyxz** [comment]
Yay! ty for this, I can take a stab at fixing the `amp-sidebar` tests.

**Comment by rsimha-amp** [comment]
@cathyxz Beat you to it. Already fixed in #12523 :)

**Comment by cathyxz** [comment]
Oh lol. Yay thanks!

**Pull request merged**
