### PR TITLE
🏗 Expose and fix closure compiler type-check warnings

### PR DESCRIPTION
**Pull request by rsimha**
**PR Highlights:**
- ~Add a new flag `--warning_level` to `check-types`. Allowed values are `verbose`, `quiet`, or `default`.~
  - **Edit:** Done as part of #33027.
- Expose and fix a whole lot of warnings.

**Notes:**
- This PR cannot be merged as is.
- The `--warning_level` flag was merged with #33027.
- Warning levels for type checking were made more granular in #33469 and #33696.
- Fixes made by @kristoferbaxter and @dvoytenko will be split off into separate PRs and merged.
- Setting `warning_level` to `DEFAULT` by default (heh!) surfaces several errors that need to be fixed first.

Partial fix for #32868

### CODE REVIEW

**Comment by kristoferbaxter** [comment]
@rsimha what do you think about breaking up this PR like we discussed earlier?

1. Land ability to see errors.
2. Apply fixes for each vendor and src/ independently.
3. Change type-checking to fail builds with updated commands.

**Comment by rsimha** [comment]
> @rsimha what do you think about breaking up this PR like we discussed earlier?
> 
> 1. Land ability to see errors.

This has already landed and is available today on `master`.

https://github.com/ampproject/amphtml/blob/4c06c96205c4a1e617325737d712f409b99a1682/build-system/compile/compile.js#L275-L276

image


> 2. Apply fixes for each vendor and src/ independently.

SGTM.

> 3. Change type-checking to fail builds with updated commands.

Agree. This is exactly what this TODO proposes:

https://github.com/ampproject/amphtml/blob/4c06c96205c4a1e617325737d712f409b99a1682/build-system/compile/compile.js#L275

**Comment by rsimha** [comment]
**Update:** With #33027, #33469, and #33696, we now have the ability to change the warning levels for various parts of the code in a more granular fashion.
- Search for the `warningLevel` option in `check-types.js`
- There's also a "big hammer" approach where you can run `amp check-types --warning_level=DEFAULT` and expose _all_ errors in one go.

The difficult job that lies ahead of us now is to split off groups of commits from this PR and merge them while changing the warning level for that part of code from `QUIET` to `DEFAULT` (or `VERBOSE` if we're feeling lucky). Eventually, we'd like to arrive at a state where all type-checking warning levels are at least `DEFAULT`.

@samouri expressed interest in driving this effort, so I've looped him in for comment. Let me know how I can help.

**Comment by rsimha** [comment]
I initially created this PR to add the `--warning_level` flag, but moved it out into #33027, #33469, and #33696. Since then, the commits that @dvoytenko and @kristoferbaxter added to this PR have gradually started accumulating conflicts with `main`.

@rcebulko @samouri In light of #33957 and #34014, am I correct that y'all are driving forward the effort to gradually fix the type check errors in `src/`, `extensions/`, etc.? If so, I'm going to close this PR since I don't plan on rebasing it or adding any new commits to it. (If you'd like to cherry-pick any still-clean commits from this PR, you can grab them from [here](https://github.com/ampproject/amphtml/pull/32875/commits).)

**Pull request closed without merging**
