### PR TITLE
Initial support for popIn native ads via amp-ad plugin.

### PR DESCRIPTION
**Pull request by popinuser**
Initial support for popIn native ads via amp-ad plugin.

### CODE REVIEW

**Comment by popinuser** [comment]
@lannka Please, review our code.

**Comment by lannka** [comment]
@popinuser Can you please implement render-start and no-content API: https://github.com/ampproject/amphtml/blob/master/ads/README.md#developer-guidelines-for-a-pull-request

**Comment by popinuser** [comment]
@lannka Thank you for review.
We implemented the render-start and no-content APIs.
Please review again.

**Comment by lannka** [comment]
please run `gulp lint` and fix the linter error.

Please also try to follow the CLA robot's instruction and see if you can pass the CLA check.

**Comment by popinuser** [comment]
@lannka Thank you for a polite review. I pushed the code that passed the check of CLA robot.
Please review again.

**Comment by lannka** [comment]
@popinuser I don't see "Oude International Trade Co., Ltd." on our corp CLA list yet. Could you confirm it's already done?

**Comment by popinuser** [comment]
@googlebot We,signed it!

**Comment by popinuser** [comment]
Oude International Trade has nothing to do with us.
We are building our own ad network.

**Comment by popinuser** [comment]
@googlebot We,signed google CLA list.

**Comment by ArcCosine** [comment]
@googlebot I,signed google CLA list.

**Comment by popinuser** [comment]
@lannka  I am sorry I took time.
We signed Google CLA as "**popIn Inc.**"
We signed but we can't pass the CLA check.
How can we pass the CLA check?

In addition, @oude3c is a person who has nothing to do with us.
His page has already become 404.
He commented, "Oude International Trade Co., Ltd." has nothing to do with us either.

Thank you.

**Comment by lannka** [comment]
Ha, that was a spam...

@popinuser the robot is picking that you used different email address in the git commit than the one you used to sign CLA. Can you try to change the git email?

**Comment by popinuser** [comment]
@googlebot we update email's and signed CLA.

**Comment by popinuser** [comment]
@googlebot Hello,Google bot.I signed it.

**Comment by lannka** [comment]
@erwinmombay do you mind force merge the PR. Seems we have some problem to pass the CLA robot.
I manually checked "popIn Inc." is already on the CLA list.

**Comment by popinuser** [comment]
@googlebot We,signed google CLA list.Please check "**popIn Inc.**".

**Comment by erwinmombay** [comment]
@lannka done

**Comment by popinuser** [comment]
@lannka Thank you very much! It was successfully merged. Thank you for your kindness.
@erwinmombay Thank you for the merge.

**Pull request merged**
