### PR TITLE
✨ Add Highfivve as AMP RTC vendor

### PR DESCRIPTION
**Pull request by muuki88**
This pull requests adds AMP RTC vendor [Highfivve](https://highfivve.com) to the list of AMP RTC vendors.

### Example integration

```html
<amp-ad
  width="320"
  height="50"
  type="network-foo"
  data-slot="/1234/5678"
  rtc-config='{
    "vendors": {
      "highfivve": {"TAG_ID": "1", "ACCOUNT_ID":"my-account"}
      },
    "timeoutMillis": 750}'
>
</amp-ad>
```

Follow up of the mess I created in #33203 . Sorry for the inconvenience :bowing_man:

### CODE REVIEW

**Review by calebcordry — APPROVED** [review]

**Comment by calebcordry** [comment]
Sorry we have some flaky tests, could you try rebase or merging latest master. It should fix the tests. Let me know if you run into problems.

**Comment by muuki88** [comment]
Looks fine now :heart: 

When this gets merged, how long will it take to be available on AMP pages?

**Comment by calebcordry** [comment]
Thanks for contributing! You can test using nightly tomorrow. It will hit beta next week, then prod the following week. You can find more details at https://amp.dev/documentation/guides-and-tutorials/learn/spec/release-schedule/

**Comment by muuki88** [comment]
Thanks for your help :heart:

**Pull request merged**
