### PR TITLE
Rename getRootNode to getDocumentOrShadowRoot

### PR DESCRIPTION
**Pull request by jridgewell**
Hopefully a self descriptive name will make this errors like https://github.com/ampproject/error-reporting/issues/57 harder to make in the future.

### CODE REVIEW

**Comment by dvoytenko** [comment]
@jridgewell Not sure this would actually help. For context, the `getRootNode` is named after the https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode. Unlike that API, however, I decided to narrow down the type to what's actually can be there, which is `Document|ShadowRoot` (there are other possibilities, but not applicable to us). 

RE: `getDocumentOrShadowRoot()` - this would probably help somewhat. But the underlying issue is that Closure would still let you call `getDocumentOrShadowRoot().createElement`.

An alternative would be to follow `getRootNode` API and narrow down the type to just `Node`, which has limited APIs.

LMK how you'd like to proceed.

**Comment by jridgewell** [comment]
> An alternative would be to follow getRootNode API and narrow down the type to just Node, which has limited APIs.

I actually tried this, and it _still_ didn't throw an error for https://github.com/ampproject/amphtml/pull/32898. So I decided on the name change instead.

**Comment by dvoytenko** [comment]
> > An alternative would be to follow getRootNode API and narrow down the type to just Node, which has limited APIs.
> 
> I actually tried this, and it _still_ didn't throw an error for #32898. So I decided on the name change instead. Also, the most frequent use for `getRootNode()` is to call `.querySelector()`, which isn't accessible on `Node`, only `Element|DocumentFragment`

One more idea. What if we made `getRootNode()` to just return `!ShadowRoot`. I.e. if the union doesn't work the way we want, we would use the most restricted part of that union. We could even go a step further and return `!DocumentFragment` - it should have the most important APIs that we need. However, type-checking this might need https://github.com/ampproject/amphtml/pull/32875 to be merged.

**Comment by jridgewell** [comment]
Yah, I'll try that once #32875 is merged. Switching this to an WIP PR.

**Pull request closed without merging**
