### PR TITLE
Yieldpro support

### PR DESCRIPTION
**Pull request by tsanders42**
please add support for Yieldpro ad server

### CODE REVIEW

**Comment by tsanders42** [comment]
I signed it!

**Comment by lannka** [comment]
@tsanders42 did you signed as a CORP or did you signed with your email?
In the email case, you will need to use it as the git email.

**Comment by mrjoro** [comment]
@lannka we figured out the CLA issue and it now looks like the [email on the commits in this PR](https://patch-diff.githubusercontent.com/raw/ampproject/amphtml/pull/12773.patch) shows up in the manual CLA verification tool as being covered by a CLA.  The CLA bot hasn't yet updated this issue for some reason, but it can be manually merged if needed.

**Comment by tsanders42** [comment]
the demo page returns a console error "Unknown ad type "yieldpro".
I rebuild on localhost and get the same error there, but can't find what is wrong? is there any way to flag this?

also, when running "yarn global add gulp", there are errors for the .trim() commands in build-system/tasks/update-tasks.js and build-system/tasks/check-package-manager.js
(I removed these checks to proceed with the setup).

**Pull request merged**
