### PR TITLE
Added bhType and all site traffic

### PR DESCRIPTION
**Pull request by ColombiaAnalytics**
modified 2 files

### CODE REVIEW

**Comment by avimehta** [comment]
@ColombiaAnalytics Please resolve the branch conflicts before I can proceed with the review.

The diff should show only the new parts that you are adding in this pull request. Currently the PR shows that you are trying to add colanalytics but that was already added a few months ago.

**Comment by ColombiaAnalytics** [comment]
Hi,


Can you help me in this. Reason I tried to remove it from pull request couldn't find any option. Created a new branch rebased master and cherry-pick but it did not work .


Thanks & Regards,

Mukul Tanwar
9717359710
________________________________

**Comment by avimehta** [comment]
Can you reply here and tell me what you want to add to your config? 

If you want to do it, It might be easier for you to start from beginning and make the changes in a new clone of the repo.

**Comment by ColombiaAnalytics** [comment]
Hi,


My changes are simple need to just introduce t more query parameters in the url.



Thanks & Regards,

Mukul Tanwar
9717359710
________________________________

**Comment by ColombiaAnalytics** [comment]
Hi, 
My changes are just to introduce 2 query Param in the url

**Comment by avimehta** [comment]
i understand, Can you paste the code here? I'll create a pull request for you which you can review and approve.

**Comment by ColombiaAnalytics** [comment]
Thanks , 
The changes are in url as in below file the change is in "pagereview" introduces 
&val_101=$id     and    &val_120=3
 In  file ---> extensions/amp-analytics/0.1/test/vendor-requests.json 

 "colanalytics": {
    "host": "https://ase.clmbtech.com",
    "base": "https://ase.clmbtech.com/message",
    "pageview": "https://ase.clmbtech.com/message?cid=$id**&val_101=$id**&val_101=_canonical_path_&ch=_canonical_host_&uuid=$uid&au=$authors&zo=$zone&sn=$sponsorName&ct=$contentType&st=_scroll_top_&sh=_scroll_height_&dct=$decayTime&tet=_total_engaged_time_&dr=_document_referrer_&plt=_page_load_time_&val_108=_title_**&val_120=3**"
  },

The change here is in "colanalytics" again added 
&val_101=$id     and    &val_120=3
In file ---> extensions/amp-analytics/0.1/vendors.js

'colanalytics': {
    'requests': {
      'host': 'https://ase.clmbtech.com',
      'base': '${host}/message',
      'pageview': '${base}?cid=${id}' +
        '**&val_101=${id}**' +
        '&val_101=${canonicalPath}' +
        '&ch=${canonicalHost}' +
        '&uuid=${uid}' +
        '&au=${authors}' +
        '&zo=${zone}' +
        '&sn=${sponsorName}' +
        '&ct=${contentType}' +
        '&st=${scrollTop}' +
        '&sh=${scrollHeight}' +
        '&dct=${decayTime}' +
        '&tet=${totalEngagedTime}' +
        '&dr=${documentReferrer}' +
        '&plt=${pageLoadTime}' +
        '&val_108=${title}' +
        '**&val_120=3**',

**Comment by ColombiaAnalytics** [comment]
As it is in quotes it did not bold it 
**&val_101=$id**     --->     &val_101=$id
**&val_120=3**     --->     &val_120=3

"colanalytics": {
"host": "https://ase.clmbtech.com",
"base": "https://ase.clmbtech.com/message",
"pageview": "https://ase.clmbtech.com/message?cid=$id&val_101=$id&val_101=_canonical_path_&ch=_canonical_host_&uuid=$uid&au=$authors&zo=$zone&sn=$sponsorName&ct=$contentType&st=_scroll_top_&sh=_scroll_height_&dct=$decayTime&tet=_total_engaged_time_&dr=_document_referrer_&plt=_page_load_time_&val_108=_title_&val_120=3"
},

**Comment by avimehta** [comment]
@ColombiaAnalytics can you review  #3849? I'll merge it once you give your okay.

**Pull request closed without merging**
