### PR TITLE
Use css.js for autoplay styles

### PR DESCRIPTION
**Pull request by cvializ**
A change introduced in PR #22377 was causing errors when I ran `gulp` since it attempts to parse a CSS file as JS. The code no longer produces the error when the `.css.js` file is used instead.

Screen Shot 2019-06-05 at 16 58 29

### CODE REVIEW

**Comment by sparhami** [comment]
Not sure why this doesn't also affect `ampdoc.css` and `ampshared.css`.

**Comment by cvializ** [comment]
I just noticed that there is both a `build/video-autoplay.css` and a `build/video-autoplay.css.js` but there is only a `build/ampdoc.css.js` and  `build/ampshared.css.js`. I think the css file being in the directory changes what file is loaded as the module

**Comment by cvializ** [comment]
Will add the comment in a follow up PR to unblock development

**Pull request merged**
