### PR TITLE
Revert "Add a visual diff test for amp-pinterest"

### PR DESCRIPTION
**Pull request by rsimha-amp**
Reverts ampproject/amphtml#11413

There is some non-static content on the current pinterest page. See https://percy.io/ampproject/amphtml/builds/353938

Reverting and tracking the addition of a new page via #11427.

### CODE REVIEW

**Comment by honeybadgerdontcare** [comment]
Are these going to be rolled forward at some point? We just did a validator release and try to keep the changelog up to date.

**Comment by rsimha-amp** [comment]
@honeybadgerdontcare, I merely clicked the "revert" button on the offending PR, and github automatically generated this commit list for the purpose of testing on Travis. If you look at the actual changes in this PR, it doesn't do anything with any of those other commits. So I'm not sure that anything needs to be rolled forward.

Or am I incorrect about what's going on?

**Comment by rsimha-amp** [comment]
@honeybadgerdontcare I just merged this. From looking at https://github.com/ampproject/amphtml/commits/master, there's nothing to worry about from the point of view of validator. Let me know if I'm wrong.

**Comment by honeybadgerdontcare** [comment]
@rsimha-amp thanks! Interesting that it lists commits that it isn't reverting. Everything looks fine.

**Pull request merged**
