### PR TITLE
🏗 Remove the --nobuild flag from visual diff tests

### PR DESCRIPTION
**Pull request by danielrozenberg**
It's more trouble than it's worth, a forgotten flag shouldn't cost me 10 minutes 😅

### CODE REVIEW

**Comment by samouri** [comment]
@danielrozenberg, how much time is it worth? How much is saved on CI?

**Comment by danielrozenberg** [comment]
Well, forgetting the `--nobuild` runs an entire `amp dist --fortesting`, which is ~10 minutes
It also calls `amp clean`, which immediately removes anything under `dist/`, so you can't just Ctrl+C it

**Comment by samouri** [comment]
Oh I see. In removing the flag you aren't removing the feature. You are making it always on.

**Review by samouri — APPROVED** [review]

**Comment by danielrozenberg** [comment]
Exactly - it will never build the runtime, at most it'll exit telling you you should build it

**Review by rsimha — APPROVED** [review]

**Pull request merged**
