### PR TITLE
✨ Add Amp-Overflow-Button Component

### LINKED ISSUE #33168: I2I: overflow button
## Summary

Create a new component that wraps the html for an overflow snippet and allows customizing the color and text of the included button

## Design document

@TODO

## Motivation

We provide an ad network that serves ads to multiple websites.  As part of our integration we suggest that they include an overflow element to encourage site visitors to engage with and expand our ads to their full size when amp determines that they should not be rendered full size initially.

Our current overflow snippet is:
```html
<div overflow="" tabindex="0" role="button" aria-label="Read more" style="width: 100%; top: 0; height: 100%;">
   <div class="wrapper" style="display: flex; flex-flow: column; height: 100%; background-color: rgba(255,255,255,0.75);">
      <div class="content-show" style="flex: 1 1 auto; background-color: transparent"></div>
      <div class="button-wrapper" style="flex: 0 1 48px; background-color: #fff; justify-content: center; display: flex;">
         <button style="background-color: transparent; color: #0058FF; border: 2px solid #0058FF; border-radius: .25rem;
              font-size: 16px; font-weight: 700; letter-spacing: .1rem; padding: 10px 35px; text-align: center; 
              font-family: 'Roboto', 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;"
         >
            See more
         </button>
      </div>
   </div>
</div>
```

This proposed component would allow calling with a custom **color** and **cta**, but also have a default **color** and **cta**:
```html
<amp-ad height="150" type="myfinance" data-ad-type="widget" data-test="true">
  <amp-overflow-button overflow> </amp-overflow-button>
</amp-ad>
```
default_color_cta

```html
<amp-ad height="150" type="myfinance" data-ad-type="widget" data-test="true">
  <amp-overflow-button overflow color="#B80000" cta="Show more"> </amp-overflow-button>
</amp-ad>_
```
custom_color_cta

/cc @ampproject/wg-approvers
/cc @ampproject/wg-ads

### PR DESCRIPTION
**Pull request by pkolenic**
- Adds the amp-overflow-button component

Use case, replaces:
```html
<amp-ad
  height="150"
  type="myfinance"
  data-ad-type="widget"
  data-test="true"
>
  <div overflow="" tabindex="0" role="button" aria-label="Read more" style="width: 100%; top: 0; height: 100%;">
    <div class="wrapper"
         style="display: flex; flex-flow: column; height: 100%; background-color: rgba(255,255,255,0.75);">
      <div class="content-show" style="flex: 1 1 auto; background-color: transparent"></div>
      <div class="button-wrapper"
           style="flex: 0 1 48px; background-color: #fff; justify-content: center; display: flex;">
        <button
          style="background-color: transparent; color: #0058FF; border: 2px solid #0058FF; border-radius: 5px; 
          font-size: 18px; font-weight: 500; letter-spacing: 1px; padding: 10px 35px;
          font-family: 'Circular Std', 'Roboto', 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;"
        >
          See more
        </button>
      </div>
    </div>
  </div>
</amp-ad>
```

with:
```html
<amp-ad
  height="150"
  type="myfinance"
  data-ad-type="widget"
  data-test="true"
>
  <amp-overflow-button overflow color="#0058FF" cta="See more"/>
</amp-ad>
```
Both ways will produce:
default_color_cta

Closes #33168

### CODE REVIEW

**Review by Gregable — APPROVED** [review]
Validator changes look good.

**Comment by pkolenic** [comment]
@estherkim @newmuis 
Will you be able to review this next week? or can you assign to someone that might be able to?

**Comment by rsimha** [comment]
Can someone from @ampproject/wg-components review this?

**Review by alanorozco — CHANGES_REQUESTED** [review]
@pkolenic 

Did #33168 go [through design review?](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#weekly-design-reviews) The I2I **must be approved before review**.

**Comment by pkolenic** [comment]
Our team ended up using the .catch() and then() chaining on window.context.requestResize() 
https://github.com/ampproject/amphtml/blob/master/ads/README.md#ad-resizing
To handle this from within the ad so this component is no longer needed.

**Pull request closed without merging**
