### PR TITLE
📖 Getting started: Don't suggest NVM for Windows

### PR DESCRIPTION
**Pull request by ChrisAntaki**
- Removes suggestion to use NVM for Windows, for a few reasons.
  - Just for some context, NVM for Windows "...is not the same thing as nvm, which is a completely separate project for Mac/Linux only." ([source](https://github.com/coreybutler/nvm-windows))
  - The suggested command (`nvm install --lts`) doesn't work with NVM for Windows, since the `--lts` flag isn't recognized.
  - There's an issue (https://github.com/coreybutler/nvm-windows/issues/133) that's been open since January 2016 that prevented me from successfully using NVM for Windows on a work-issued laptop, even with temporary admin access.

### CODE REVIEW

**Comment by torch2424** [comment]
@ChrisAntaki

These are all very good points, thank you for bringing this top our attention! 😄 

cc @erwinmombay @rsimha @kristoferbaxter Since ya'll either work in infra, or have done AMP windows development in the past.

Thank you!

**Comment by torch2424** [comment]
Also, @ChrisAntaki I noticed this PR also contains the changes from: #22647

Could you remove them here, that way we can continue these changes on the other PR? 

Thank you!

**Comment by ChrisAntaki** [comment]
Thanks for taking a look! I'll take care of those extra changes soon 😁

**Comment by ChrisAntaki** [comment]
Extra changes have been removed :smile:

**Comment by torch2424** [comment]
@ChrisAntaki Thanks for the contribution! 😄

**Comment by rsimha** [comment]
LGTM. Thanks for the contribution!

**Comment by ChrisAntaki** [comment]
Thanks guys!

**Pull request merged**
