### PR TITLE
✨ AMP Connatix Story Player Extension

### PR DESCRIPTION
**Pull request by rares-mihai-preda**
Implemented our new Connatix Story Player Component (#26593)

### CODE REVIEW

**Comment by rares-mihai-preda** [comment]
@alanorozco What "Blocked" label means in this context? Some changes needed?

**Comment by alanorozco** [comment]
@rares-mihai-preda 

Apologies for lack of more thorough response earlier. I annotated for process and wanted to give a more thorough look for [my comment on the I2I.](https://github.com/ampproject/amphtml/issues/26593)

In this case it means two things:

1. I2I is incomplete (please [see my comment.](https://github.com/ampproject/amphtml/issues/26593))
2. I2I needs to be approved. (will need to go to [design review](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md#bringing-your-design-to-a-design-review) _after_ I2I is complete)

**Comment by rares-mihai-preda** [comment]
> @rares-mihai-preda
> 
> Apologies for lack of more thorough response earlier. I annotated for process and wanted to give a more thorough look for [my comment on the I2I.](https://github.com/ampproject/amphtml/issues/26593)
> 
> In this case it means two things:
> 
> 1. I2I is incomplete (please [see my comment.](https://github.com/ampproject/amphtml/issues/26593))
> 2. I2I needs to be approved. (will need to go to [design review](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md#bringing-your-design-to-a-design-review) _after_ I2I is complete)

@alanorozco We updated the I2I.  Please review it again and let us know if there is any other missing information.

**Comment by rares-mihai-preda** [comment]
@Gregable @alanorozco What "Blocked" label means in this context? Some other changes needed? 

We updated the I2I which was the previous blocker.

Hope to hear from you soon guys! Thanks

**Comment by alanorozco** [comment]
@rares-mihai-preda 

From my previous comment:

> I2I needs to be approved. (**will need to go to design review** after I2I is complete)

Please [book a session](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md#bringing-your-design-to-a-design-review).

**Comment by rares-mihai-preda** [comment]
> @rares-mihai-preda
> 
> From my previous comment:
> 
> > I2I needs to be approved. (**will need to go to design review** after I2I is complete)
> 
> Please [book a session](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md#bringing-your-design-to-a-design-review).

@alanorozco Thanks for your support. 

In upcoming design reviews section we found two upcoming sessions on past date (2020-04-01 and 2020-03-18). Should we wait for a new one to be published or should we book a session on one of them two?

**Comment by Gregable** [comment]
@rares-mihai-preda @alanorozco , what's the status on this from the design review? Is there a condition we are still waiting on to unblock? I'm checking that this isn't blocked on me at this point.

**Comment by rares-mihai-preda** [comment]
PR closed. Details: Design Review 2020-04-08 20:00 UTC (Connatix Story Player, AMP testing & release quality, wg-performance) #27599

**Pull request closed without merging**
