### PR TITLE
Access iframe messaging and handshake implementation

### PR DESCRIPTION
**Pull request by dvoytenko**
Blocked by #14187
Partial for #13287

### CODE REVIEW

**Comment by rsimha** [comment]
@dvoytenko This PR appears to have broken the build on `master`. See https://travis-ci.org/ampproject/amphtml/builds/357088959

Does this build when you run `gulp dist` locally?

**Comment by dvoytenko** [comment]
@rsimha Hmm. It passed the travis successfully before. But, yes, fails at this time. Not clear why.

/cc @erwinmombay

**Comment by rsimha** [comment]
Travis doesn't do a `gulp dist`. Only `master` builds do.

**Comment by dvoytenko** [comment]
I see. Looking.

**Comment by dvoytenko** [comment]
No clear indication what the error is yet. The code references dependencies correctly.

**Comment by rsimha** [comment]
@erwinmombay had a theory.

**Comment by dvoytenko** [comment]
Fix: https://github.com/ampproject/amphtml/pull/14232

**Comment by dvoytenko** [comment]
Should be fixed now.

**Pull request merged**
