### PR TITLE
Add support for MADS platform

### PR DESCRIPTION
**Pull request by Shutnik**
Please review [MADS](http://mads.com/) integration support for Google AMP.

### CODE REVIEW

**Comment by Shutnik** [comment]
CLA signed for MADS company 👍

**Comment by lannka** [comment]
LGTM.

Travis hook failed again. Could you please try push an empty commit to wake it up?
Also, CLA approval should be automatic. Seems it didn't recognize what you said. Could you please rephrase? Maybe just copy what it suggested:
> I signed it!

**Comment by Shutnik** [comment]
I signed it!

**Comment by Shutnik** [comment]
I updated my pull request and fixed problems reported by travis, but CLA still not checked.

**Comment by lannka** [comment]
Hmm.. continuously seeing this problem. Don't worry. I do see `MADS BV` on our CLA list. Is it your company? 
If so, we can force merge it.

P.S. Is your email backed by GMail service? I'm not sure if that's related, but I do see some cases.

**Comment by Shutnik** [comment]
Yes, MADS BV is correct one.
And yes, we are using Google Apps.

**Comment by lannka** [comment]
Ha, the bot woke up.

**Pull request merged**
