### PR TITLE
📖 Change the UK spelling of behaviour to US spelling behaviour

### PR DESCRIPTION
**Pull request by leniquenoralez**
… of behavior

# Instructions:

- Pick a meaningful title for your pull request. (Use sentence case.)
  - Prefix the title with an emoji to identify what is being done. (Copy-paste the emoji itself (not the :code:) from the list below.)
  - Do not overuse punctuation in the title (like `(chore):`).
  - If it is helpful, use a simple prefix (like `ProjectX: Implement some feature`).
- Enter a succinct description that says why the PR is necessary, and what it does.
  - Mention the GitHub issue that is being addressed by the pull request.
  - The keywords `Fixes`, `Closes`, or `Resolves` followed the issue number will automatically close the issue.

# Example of a good description:

- Implement aspect X
- Leave out feature Y because of A
- Improve performance by B
- Improve accessibility by C

# Emojis for categorizing pull requests:

✨ New feature (`:sparkles:`)  
🐛 Bug fix (`:bug:`)  
🔥 P0 fix (`:fire:`)  
✅ Tests (`:white_check_mark:`)  
🚀 Performance improvements (`:rocket:`)  
🖍 CSS / Styling (`:crayon:`)  
♿ Accessibility (`:wheelchair:`)  
🌐 Internationalization (`:globe_with_meridians:`)  
📖 Documentation (`:book:`)  
🏗 Infrastructure / Tooling / Builds / CI (`:building_construction:`)  
⏪ Reverting a previous change (`:rewind:`)  
♻️ Refactoring (like moving around code w/o any changes) (`:recycle:`)  
🚮 Deleting code (`:put_litter_in_its_place:`)

### CODE REVIEW

**Comment by aghassemi** [comment]
Thanks @leniquenoralez! The CLA check failure is due to email address on this commit being different than the one you have signed the CLA with. This PR's commits are from `lnoralez@CPG-HQ-WKL05.local` which means you have not set your `git` email address yet.

Please use `git config --global user.email "email@example.com"` to set that to the email address you use for signing CLA.

After that, you would need to `amend` the commit and `push` again.
`git commit --amend -m "fix spelling"` would do 
followed by normal `git push`

**Comment by leniquenoralez** [comment]
Thanks for the heads up.I'm using a new computer and didn't realize that my git email wasn't set.

**Comment by aghassemi** [comment]
@leniquenoralez A new PR may work best now. I can manually verify CLA and merge this (let me know if you like me to do that) but since this is a `good first issue` there is value in ensuring CLA stuff is all good.

**Comment by aghassemi** [comment]
@leniquenoralez I checked internally and since you have signed the CLA already, I will merge this. Thank you!

**Pull request merged**
