### PR TITLE
AdsLoom AMP Integration

### PR DESCRIPTION
**Pull request by safzal0906**
Hi there,
We'd like to integrate our Ad-Server with AMP. We've contributed to AMP as per documentation. Please check & approve.
Thanks in advance!
Regards,
Shahzaib

### CODE REVIEW

**Comment by safzal0906** [comment]
Any update on this?

**Comment by safzal0906** [comment]
/cc @zhouyx 
@zhouyx could you please review my code?

**Comment by safzal0906** [comment]
> LGTM. Could you please fix the lint check error so that we can merge the PR.
> You could try `gulp lint --local-changes --fix` locally

lint check error fixed

**Comment by safzal0906** [comment]
Hi @zhouyx ,
Can you please merge this PR now, or anything else required on my end?
Thanks!

**Comment by torch2424** [comment]
@safzal0906 @zhouyx 

Went ahead and re-ran the flaking saucelabs test 😄 

I'll take a look at this tomorrow if not already merged. Thanks! 👍

**Comment by safzal0906** [comment]
@torch2424 Thank you for you response. Seems like I don't have required privileges to run individual saucelabs tests. I can only trigger all tests, by doing another commit. Should I go for it, Or is there something else that I can do?

**Comment by torch2424** [comment]
@safzal0906 

Actually, yes, could you pull in the latest master? I re-ran the test for you 3 times. But it seems to keep failing on the same analytics case (which your code does not touch 🤔 )

cc @zhouyx if you see this while travis is still failing, can you take a look?

**Comment by zhouyx** [comment]
I don't have a good answer on why the travis keeps failing. Can we try pull in the latest master

**Comment by safzal0906** [comment]
@torch2424 @zhouyx , Let me pull latest master and try again

**Comment by safzal0906** [comment]
Hurrah! I've pulled latest master and pushed it. All checks have passed now :) @torch2424 @zhouyx guys please merge it now

**Comment by torch2424** [comment]
Awesome! I also did a quick test, and everything looks good on our end:

Screen Shot 2019-06-19 at 1 30 17 PM

Thank you very much for the contribution @safzal0906 ! 😄 🎉

**Pull request merged**
