### PR TITLE
Create RTBExchangeGuide.md

### PR DESCRIPTION
**Pull request by hgaron**
Updated RTB Exchange Guide

Closed https://github.com/ampproject/amphtml/pull/9704 and moved the content to this new pull request.

### CODE REVIEW

**Comment by lannka** [comment]
Seems our Travis tests is not happy about having a backtick on the anchor text, though it is a valid syntax. 

Can you use `<code></code>` instead, or you can wait @rsimha-amp to have the test fixed?

**Comment by rsimha-amp** [comment]
@hgaron, you could try out your changes locally with `gulp check-links --files <your md file>`

**Comment by rsimha-amp** [comment]
From the logs, It's clear that the link checker tool thinks the entire block of text within the angular braces is part of the link. You could add a space after the open angular brace, or put the link + text inside a `<code>` block.

**Comment by hgaron** [comment]
Changed to <code></code> and it seems to have resolved the travis test failure.  Thanks all!

**Comment by hgaron** [comment]
Also, if all looks good, could one of the reviewers with write access please approve the pull request when you get a chance?

**Pull request merged**
