### PR TITLE
Validator Roll-up

### PR DESCRIPTION
**Pull request by Gregable**
Changes affecting PASS/FAIL:

- Implement validation for `<amp-accordion>`
- Implement validation for `<amp-brid-player>`
- Implement validation for `<amp-springboard-player>`
- Implement validation for `<amp-reach-player>`.

### CODE REVIEW

**Comment by Gregable** [comment]
@honeybadgerdontcare @powdercloud

**Comment by honeybadgerdontcare** [comment]
@googlebot confirmed

**Comment by powdercloud** [comment]
@googlebot confirmed

**Comment by Gregable** [comment]
@erwinmombay for the next release notes

**Pull request merged**
