### PR TITLE
✨ [Amp story] [Page attachments] [Inline] Theme pre-tap without images

### LINKED ISSUE #32767: [Page attachments] [Inline] Theme attribute for pre-tap state
Use the theme attribute to switch its color scheme of the pre-tap state

Screen Shot 2021-02-19 at 5 00 48 PM

@ampproject/wg-stories

### PR DESCRIPTION
**Pull request by processprocess**
Context / Fixes #32767

- Adds dark theme support for inline default pre-tap.
- Updates template.
- Removes animation (animation will be added in follow up #33261)

Screen Shot 2021-04-22 at 10 45 31 AM

[demo](https://philipbell-stamp-ui.web.app/examples/amp-story/attachment.html)

### CODE REVIEW

**Review by mszylkowski — APPROVED** [review]
LGTM

**Comment by Enriqe** [comment]
Is the white-ish border on the rounded corners of the top intentional?
image

**Review by gmajoulet — APPROVED** [review]
How confident are you that we are going to actually be able to clean up this experiment and merge all the CSS without keeping all these overrides?

**Comment by gmajoulet** [comment]
image
Also, the handle is invisible, can you update its color?

**Pull request merged**
