### PR TITLE
piano analytics support

### PR DESCRIPTION
**Pull request by nathangoulding**
Fixes issue #1769.

### CODE REVIEW

**Comment by avimehta** [comment]
@nathangoulding While looking at examples today, I realized that [your config](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors.js#L364) does not contain a [client id scope](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vars.md#clientid). Can you Send out a PR to add the scope/cookie name? Without that, the client id value will be empty.    

 ```
'amp_client_id=${clientId}&aid=${aid}',
```

**Comment by nathangoulding** [comment]
Ahh yeah, will do.

**Comment by avimehta** [comment]
Thanks, Please cc me on the pull request.

**Comment by nathangoulding** [comment]
@avimehta Looking over the documentation for this now. It sounds like the `clientId` is tied to a logged-in user - is that correct? I thought the `clientId` was generated by the AMP viewer and was always populated, effectively a unique `viewerId` (equivalent of a `browserId` for mobile browsers). I'm not sure I understand the significance of the `clientId`.

Is there a way to get an automatically generated `viewerId`? There's also mention of reading a fallback cookie, but it's unclear how a 3rd-party analytics provider could set a first-party cookie that could get read by AMP.

Could you point me to the documentation on this?

**Comment by rudygalfi** [comment]
@nathangoulding `clientId` is not tied to authenticated data. Here's the design doc from the ITI (#961): https://docs.google.com/document/d/1f7z3X2GM_ASb3ZCI_7tngglxwS6WoWi1EB3aKzdf6vo/edit

**Comment by avimehta** [comment]
@nathangoulding Someone recently asked about the client id setup for piano analytics configuration. The way it is setup currently, the value of `amp_client_id` is always `''`. Using client id without a parameter also results in an error getting logged in console. Can you find out what the right thing for you here would be?

- You can pass in a cookie name like: `${clientId(cookieName)}` and the viewer will generate an id for you that is persisted per browser.
- You can remove the `${clientId}` from your configuration completely.

**Pull request merged**
