### PR TITLE
✨ Validation for new interactive attribute

### PR DESCRIPTION
**Pull request by Enriqe**
#19213 #16522

Support new `interactive` attribute added in #21402 for dead embeds.

### CODE REVIEW

**Comment by Gregable** [comment]
If it's not too late, can we just use presence of `interactive` rather than `interactive=true`. Mandate in the validator that the attribute value is empty: `""`.

This seems more consistent with typical html. You don't see `<html amp=true>` or `<!doctype html=true>`, etc.

**Comment by Enriqe** [comment]
Sorry, I thought I was doing this already? I'm just allowing the `interactive` attribute, and not forcing it to be `interactive=true`.

**Comment by gmajoulet** [comment]
I think Greg was suggesting we force `interactive` on its own, not `interactive="true"`, like `amp-video` does with `autoplay` for example https://github.com/ampproject/amphtml/blob/master/extensions/amp-video/validator-amp-video.protoascii#L42

**Comment by Gregable** [comment]
Yes, I'm suggesting we disallow any value for `interactive`.

**Comment by Enriqe** [comment]
Got it. I went ahead and made the change to

```
  attrs: {
    name: "interactive"
    value: ""
  }
```

but the test using `interactive="true"` still passes. Am I missing something?

**Comment by gmajoulet** [comment]
How about that selector though? :(( Can you send a followup PR?

**Comment by Enriqe** [comment]
(for anyone else interested)

Selector is being updated in this other PR
https://github.com/ampproject/amphtml/pull/21471#discussion_r266918328

**Pull request merged**
