### PR TITLE
Skip flaky inabox tests

### PR DESCRIPTION
**Pull request by cvializ**
Example flaky test run: https://travis-ci.org/ampproject/amphtml/jobs/488921966

### CODE REVIEW

**Comment by zombifier** [comment]
I have been looking for a while now. Something changed in Firefox 65 that caused it to fail to load the ad.localhost domain during testing on Travis. 64 and prior (along with Safari) works fine for some reason. Friendly and safe frame cases are still fine since they don't need to load from a localhost subdomain.

Subdomaining localhost only works on Chrome out of the box, and requires modifying the hosts file for other browsers to work (you need to do this if you want to run the inabox tests locally on a non-Chrome browser). Maybe something is missing in the Travis environment for Firefox 65? I can't tell at the moment.

**Comment by cvializ** [comment]
@lannka PTAL I disabled the test on Firefox

**Comment by lannka** [comment]
> Firefox 65 on local testing passes if I set `/etc/hosts` so `ads.localhost` is properly redirected. This is the case in prior versions as well.

I think this is the root cause as @torch2424 also found out.

On Travis we did [set hosts names](https://github.com/ampproject/amphtml/blob/master/.travis.yml#L37). Not sure about SauceLabs. @rsimha do you know?

**Comment by rsimha** [comment]
@lannka According to [this](https://wiki.saucelabs.com/display/DOCS/Editing+the+Virtual+Machine%27s+Host+File) article:

> Editing the Host file of the virtual machine will not work if Sauce Connect Proxy is in use. If you are using Sauce Connect Proxy, the Host file of the machine running Sauce Connect Proxy will be referenced and you can make the desired changes there.

We do use Sauce Connect Proxy on Travis, so I'd imagine the host file of the Travis VM will be referenced. Is this what you're observing?

**Comment by cvializ** [comment]
Merging now to unblock other PRs. Can revert when hosts file solution is implemented.

**Comment by rsimha** [comment]
To add, the Travis [documentation](https://docs.travis-ci.com/user/hosts/) for the `hosts` addon says:

> If your build requires custom hostnames, you can specify a single host or a list of them in your `.travis.yml`. Travis CI will automatically configure the hostnames in `/etc/hosts` and resolve them to `127.0.0.1`.

We're already doing this for `ads.localhost` via this line in `.travis.yml`:

https://github.com/ampproject/amphtml/blob/2b833394eb098e001325a4722c423fa4599dbb6d/.travis.yml#L36-L37

Is this sufficient for our purpose? Are we not seeing the desired effect on Firefox 65?

**Comment by lannka** [comment]
I just tested FF64, it also requires `/etc/hosts` to load `ads.localhost`. So not sure what is changed in FF65 that caused `ads.localhost` fail to load on SL.

**Pull request merged**
