### PR TITLE
From the root README.md, link to validator/README.md.

### PR DESCRIPTION
**Pull request by powdercloud**
In validator/README.md:
- Mention #development=1.
- Slap (beta!) onto the three other choices listed here, just to be honest
  for now. :-)

### CODE REVIEW

**Comment by honeybadgerdontcare** [comment]
LGTM

**Comment by cramforce** [comment]
LGTM

Maybe file a bug against https://github.com/ampproject/docs to pick it up over there?

**Comment by powdercloud** [comment]
https://github.com/ampproject/docs/issues/96

Thanks much!

**Pull request merged**
