### PR TITLE
🏗 Move automated test fixtures from manual to fixtures/e2e

### PR DESCRIPTION
**Pull request by rcebulko**
First half of #32177 

These files are the only ones beside `amp-base-carousel` that run automated tests on files under `manual`. This PR moves those test fixtures into `test/fixtures/e2e`. I plan to move `amp-base-carousel` fixtures as well in a follow-up, but there are so many that it made sense to isolate that (plus there may be discussion about duplicating some into both locations, or updating `index.html` to point to the new locations for others). These few are very straightforward

Part of my thinking here is that anything in `manual` should be possible to change, rename, or remove without breaking automated testing. This PR also adds `fixtures/e2e` to the PR Deploy/`gulp serve` directory list. ~Note that these files won't automatically be available as in PR Deploy bot anymore, or anywhere else `test/manual` gets served (if anywhere). Is that a problem for any of these? If so, do you think we should favor duplicating, or give up on splitting them apart?~

### CODE REVIEW

**Review by rsimha — APPROVED** [review]
LGTM!

**Review by caroqliu — APPROVED** [review]
Thank you! Please get a separate approval for `extensions/amp-story/` changes. :) ✅  for the rest.

**Comment by rcebulko** [comment]
> Thank you! Please get a separate approval for `extensions/amp-story/` changes. :)  for the rest.

Added request for @Enriqe for this :+1:

**Review by Enriqe — APPROVED** [review]

**Comment by rcebulko** [comment]
@ampproject/wg-infra I have approval from Raghu, but Bundle Size Bot is still complaining. Could you try bumping approval please?

**Review by estherkim — APPROVED** [review]

**Pull request merged**
