### PR TITLE
Remove unnecesary parameter of rcmwidget extension of amp-ad

### PR DESCRIPTION
**Pull request by Bob-chemist**
Add rcmwidget ads extension parameter.

Closes https://github.com/ampproject/amphtml/issues/39158

cc ampproject/wg-monetization

### CODE REVIEW

**Comment by powerivq** [comment]
Can you remove change to extensions/amp-analytics/0.1/vendors/neodata.json? I know it there is a check error, but it is already in a separate PR being fixed #39161

**Comment by powerivq** [comment]
That PR was merged. You can rebase against the main branch?

**Comment by Bob-chemist** [comment]
@powerivq, sorry, I was offline. Done

**Review by powerivq — APPROVED** [review]

**Comment by Bob-chemist** [comment]
sorry. I have no idea what to do. I can't even log in there.
Could you please try to rerun the workflow manually?

**Comment by Bob-chemist** [comment]
@powerivq, we have updated issue and have opened new PR - https://github.com/ampproject/amphtml/pull/39173

I think we can close this PR.

**Pull request closed without merging**
