### PR TITLE
amp-date-countdown: migrated getAttributes from constructor to buildCallback

### LINKED ISSUE #17596: amp-date-countdown is not working sometimes
`amp-date-countdown` will have issue of getting the attributes from DOM. We should have written 
list of elements which are responsible of getting attributes from DOM, such as `this.element.getAttribute('end-date')` in `buildCallback()` instead of `constructor()`

image

### PR DESCRIPTION
**Pull request by aghassemi**
Clone of https://github.com/ampproject/amphtml/pull/17622 by @leonalicious

Fixes #17596

`amp-date-countdown` will have issue of getting the attributes from DOM. We should have written 
list of elements which are responsible of getting attributes from DOM, such as `this.element.getAttribute('end-date')` in `buildCallback()` instead of `constructor()`

image

### CODE REVIEW

**Comment by leonalicious** [comment]
@aghassemi @cathyxz  may i know when will this PR get merged into master branch please ?

**Comment by leonalicious** [comment]
@aghassemi @cathyxz may i know when will this PR get merged into master branch please ? 
/cc @choumx

**Comment by aghassemi** [comment]
@leonalicious apologies, ran into some lint issue then was our of office. Will merge it today.

**Comment by aghassemi** [comment]
@leonalicious there were some type issues with the PR which I fixed but now unit tests are failing as they are not compatible with the move from `constructor` to `buildCallback`, Could I leave it to you to fix and send another PR?

**Comment by aghassemi** [comment]
Never mind, managed to find a fix for it. Merged. Sorry about the delay

**Pull request merged**
