### PR TITLE
Replace custom no-duplicate-imports rule with an eslint rule

### PR DESCRIPTION
**Pull request by estherkim**
They're the same - https://eslint.org/docs/rules/no-duplicate-imports

### CODE REVIEW

**Comment by jridgewell** [comment]
Mine comes with an auto-fixer, which the original doesn't have. 😉

**Comment by estherkim** [comment]
Ohh I see. Plus it allows stuff like this, which eslint's rule doesn't. Ok nevermind
```
import * as st from './style';
import {assertNotDisplay, setStyle} from './style';
```

**Comment by estherkim** [comment]
Actually @jridgewell does this rule work for you? When I add duplicate imports, it doesn't create a warning.

**Comment by jridgewell** [comment]
It appears to work: https://astexplorer.net/#/gist/85545940462532a7f868b308ce0da81b/93b2158c6c296730cd38c8f7ff8c472f4c948493

**Pull request closed without merging**
