### PR TITLE
📈 Add last-page-visible trigger

### LINKED ISSUE #22901: Add a trigger for when a story is completed
Master issue #12191

Right now, we rely on the bookend trigger to know whether a story was completed or not. This could cause issues in the future if we decide to introduce an option where the bookend is not available in some stories. 

Let's add a specific event for when a story is completed.

### PR DESCRIPTION
**Pull request by Enriqe**
Closes #22901

### CODE REVIEW

**Comment by gmajoulet** [comment]
Quick question: can't we already do that with the `story-page-visible` trigger and the `PAGE_INDEX` + `PAGE_COUNT` variables?

**Comment by Enriqe** [comment]
I believe @jeffjose had an explicit request for it to be a trigger, since a variable would be more expensive for publishers. Is that correct Jeff?

**Comment by Enriqe** [comment]
Oh and also: 

> He wanted to support sending the story end to different request url. Let's still do different event types : ) Because event is one to one match to request.

**Comment by jeffjose** [comment]
> I believe @jeffjose had an explicit request for it to be a trigger, since a variable would be more expensive for publishers. Is that correct Jeff?

AMP Analytics is declarative in nature, with rudimentary support for *some* evaluations. We cannot do `PAGE_INDEX + 1 = PAGE_COUNT`. 

Even if we did that, it'll be hooked into an `enabled` switch, which is evaluted on every event which is dropped everytime except the last page.

In short, a) cannot evaluate expressions b) and even if we did it, it'll be expensive.

**Comment by gmajoulet** [comment]
Awesome, thanks for the context :)

**Pull request merged**
