### PR TITLE
Multi-version: support and requirements for ads

### PR DESCRIPTION
**Pull request by dvoytenko**
Partial for #33001.

### CODE REVIEW

**Review by calebcordry — APPROVED** [review]
Thanks for taking this on! I took a quick look and I don't think we are parsing extension version from non-signing ad metadata object. I might need to add some logic for existing flow/template ads, but I will take a deeper look when working on followup.

**Comment by dvoytenko** [comment]
> Thanks for taking this on! I took a quick look and I don't think we are parsing extension version from non-signing ad metadata object. I might need to add some logic for existing flow/template ads, but I will take a deeper look when working on followup.

Thanks! Let's confirm asap if the data is there. I saw some examples where I saw the whole script src, so my hope is that we can extract it.

**Comment by dvoytenko** [comment]
I know this is [fake data](https://github.com/ampproject/amphtml/blob/bb494666b8bf8c81d3fcf83a24ac847f956fd209/extensions/amp-ad-network-fake-impl/0.1/test/test-amp-ad-metadata-transformer.js#L35), but I hope this might carry over to the real cases. PTAL.

**Comment by calebcordry** [comment]
Yeah sorry when I checked a couple of demo ads the data is there, I just think we aren't extracting it (ie we are only reading `customExtensionElements`) We should be able to parse it out using the url. Read ad response below.
image

**Comment by dvoytenko** [comment]
Yeah. That should work!

**Comment by dvoytenko** [comment]
Also, do you have an example with a template by any chance?

**Comment by calebcordry** [comment]
there are a few @ `test/manual/amp-ad-custom.amp.html`

**Comment by dvoytenko** [comment]
Hmm. I don't see any of those adding the extensions though. So we should be all clear with those?

**Pull request merged**
