### PR TITLE
🏗 Switch name of renovate bot for owners check

### PR DESCRIPTION
**Pull request by rsimha**
In order to get auto-submit working for low-risk package upgrades, we're switching from the `forking-renovate` app (creates PRs from a fork) to the `renovate` app (creates PRs on the main repo).

Since the new app uses a slightly different committer ID, we need an owners config change.

**Example:**

**PR:** https://github.com/ampproject/amphtml/pull/34673
**Owners check run:** https://github.com/ampproject/amphtml/pull/34673/checks?check_run_id=2737953772
**Commit info:** https://github.com/ampproject/amphtml/pull/34673/commits

Partial fix for #33959

### CODE REVIEW

**Review by kristoferbaxter — APPROVED** [review]
Looks good to me, thanks Raghu!

**Comment by rsimha** [comment]
@rcebulko Is there a way to manually trigger a tree refresh for owners bot? I'm still seeing the old name. IIRC, the bot automatically fetches tree changes within a few minutes, right?

image

**Comment by rcebulko** [comment]
@rsimha Pantheon project under Cloud Scheduler > App Engine Cron Jobs. I manually triggered a refresh. Otherwise updates hourly.

**Comment by rsimha** [comment]
Aha, hourly. I now see the change, thank you very much!

**Comment by rcebulko** [comment]
You can update that frequency in `owners/cron.yaml` and push a new deploy-tag if 1 hour is too infrequent; it's not an overly expensive operation, so every 15 minutes wouldn't be likely to cause any issues

**Comment by rsimha** [comment]
Good to know, because we might need to make yet another change. There still appears be a mismatch between the new renovate bot's apparent name and what owners bot thinks it is.

See [this](https://github.com/ampproject/amphtml/pull/34673/checks?check_run_id=2739176166) failing owners check run. The PR [author ID](https://github.com/ampproject/amphtml/pull/34673) shows as `renovate`, while if you look at the [raw commit](https://github.com/ampproject/amphtml/commit/38ea1132d4366ed6a91a5cef88ddeb0693839089.patch), the author shows as `renovate[bot]`.

I tried adding `{name: 'renovate[bot]'}` to the root owners file (see https://github.com/ampproject/amphtml/pull/34676/commits/35b8a8aaa2ba589e39581d238bc51d921f8828a7), but the owners format [didn't allow](https://app.circleci.com/pipelines/github/ampproject/amphtml/10487/workflows/7c6f9b57-0a7f-4b93-bf66-673dbdf9c991/jobs/163834) it. If there's a way for me to pull the logs and investigate this myself, I'd love a pointer.

**Comment by rcebulko** [comment]
There are no logs relevant here, since this is just the schema validation rejecting the name. The `schema.json` currently doesn't allow bots to be owners. Examine the GH API response for [a pull request](https://api.github.com/repos/ampproject/amphtml/pulls/34673) and [pull request reviews](https://api.github.com/repos/ampproject/amphtml/pulls/34673/reviews) and you should be able to see the results you're expecting.

**Comment by rsimha** [comment]
Gotcha. Weirdly, the `forking-renovate` app wasn't being recognized as a bot, so it's probably for the best that we switched to the regular app. 

Since this is a valid case where we do want a bot to be an owner. I'll send out a PR that proposes a schema change to see what you think.

**Comment by rsimha** [comment]
For posterity, this has been resolved and everything looks good. Thanks for the help, @rcebulko!

image

**Pull request merged**
