### PR TITLE
🚀 Use Data URLs instead of Blobs

### PR DESCRIPTION
**Pull request by developit**
Benefits: simpler, smaller, easier CSP, better browser support.

### CODE REVIEW

**Comment by kristoferbaxter** [comment]
@choumx, interesting idea here and worth a look.

**Comment by jridgewell** [comment]
I think we chose `Blob` here because we wanted to explicitly ban `data:` script-srcs in our CSP. `Blob` can't be constructed with just declarative HTML, so it would have to come from our JS.

@choumx will have more context here.

**Comment by developit** [comment]
@jridgewell - might be worth checking if you could use [worker-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src) in your CSP?

**Comment by developit** [comment]
Also, while I'm here - would it be easier to work around the same-origin limitation here by using importScripts?  You could use the `name` option/global to pass the true target URL into the worker, which would result the same lifecycle timings it currently has.

```js
const url = calculateEntryPointScriptUrl(loc, 'ww', useLocal, useRtvVersion);

let blob = new Blob(['importScripts(name)']);
let blobUrl = URL.createObjectUrl(blob);
this._worker = new Worker(blobUrl, { name: url })
```

**Comment by choumx** [comment]
Interesting idea. I'll have to do a bunch of browser and x-origin tests before changing this. Can you elaborate on "easier CSP"?

Also `worker-src` still seems to have spotty support: https://www.chromestatus.com/feature/5922594955984896

**Comment by aghassemi** [comment]
If needs further investigation is needed before merging, please close the PR for house-keeping purposes and reopen when active again. Thanks!

**Comment by nainar** [comment]
Closing as per comment https://github.com/ampproject/amphtml/pull/15357#issuecomment-393246867

**Pull request closed without merging**
