### PR TITLE
🐛Disconnected Intersection Observer Polyfill in Intersection Observer Api Destroy()

### LINKED ISSUE #19252: Error logs in intersection-observer-polyfill
New error in Canary release, please see go/ampe/CKrhq5ni6tjc6AE 

Seems to just be from iOS 12. 

Please investigate as P0 and downgrade priority as needed. /cc @zhouyx @torch2424

### PR DESCRIPTION
**Pull request by torch2424**
closes #19252

Did exactly what the title says, and added tests to make sure this stays fixed 😄 

@zhouyx Not entirely sure how you manually tested this, would be awesome to know your steps so I can also manually make sure this fix works 😄

### CODE REVIEW

**Comment by torch2424** [comment]
cc @aghassemi 😄

**Comment by zhouyx** [comment]
Thank you @torch2424 for the fix! LGTM

I didn't test it : ) But to verify the fix. The idea is to trigger the mutationObserver after `#destory()`

For example: you can create an `<amp-iframe>` and call the `send-intersections` [API](https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md#iframe-viewability). Which will create a `IntersectionObserverApi` class.
Then apply `hidden` class to the doc to trigger the mutationObserver, have runtime unlayout the `<amp-iframe>` (you can mock this step). After that add/remove hidden class to trigger mutationObserver again to test if the error still exists.

**Comment by torch2424** [comment]
cc @zhouyx 

So I tried to do the steps you suggested by doing the following:

1. Add:

```
window.parent.postMessage({
  sentinel: 'amp',
  type: 'send-intersections'
}, '*');
```

to `test/manual/amp-iframe-messaging.embed.html`

2. Open `test/manual/amp-iframe-messaging.amp.html` using our dev server

3. Confirm messaging worked, by scrolling around and viewing intersection evens logged in console

4. add/remove `hidden` from the `amp-iframe` element.

I don't see any errors logged to the console after following these steps. Let me know if I am missing something.

And here's a screenshot of my results:

screen shot 2018-11-21 at 11 20 31 am

**Comment by torch2424** [comment]
You are welcome! @zhouyx Thanks for the help! 😄 Merging...

**Pull request merged**
