### PR TITLE
Update layout=fill CSS

### LINKED ISSUE #4947: amp-fit-text layout=fill breaking parent element
This might be a misunderstanding on my part, but when amp-fit-text is called with layout=fill:

`<amp-fit-text width="300" height="200" layout="fill">foo</amp-fit-text>`

It seems to be exceeding the size of its parent element and filling its grandparent element instead.  My understanding is that it should fit to fill its parent element.

See this [gist](https://gist.github.com/jmadler/71f5a5fd7b822dd456a5c81720ed23ce) for a simple min-reproducible test case.

### PR DESCRIPTION
**Pull request by jridgewell**
Fixes #4947.

### CODE REVIEW

**Comment by aghassemi** [comment]
@dvoytenko @jridgewell we should probably add `box-sizing: border-box;` as well to keep padding and border part of the size. That should make this compatible with the old css.

**Comment by jridgewell** [comment]
> we should probably add box-sizing: border-box;

Sure, will you do the PR.

**Comment by dvoytenko** [comment]
If I understand the proposal right, I'm not sure it'd work. It'd only make it compatible if we update border-box on the parent.

**Comment by dvoytenko** [comment]
Ok, I knew I misunderstood it. So, yeah, `border-box` is a good idea. However, we still loose out on the parent's padding box :)

**Pull request merged**
