### PR TITLE
Move test-bind-integration.js to test/integration.

### PR DESCRIPTION
**Pull request by kmh287**
Partial for #9404.

/to @choumx

### CODE REVIEW

**Comment by choumx** [comment]
Nit: `test-bind.js` since "integrations" is redundant.

**Comment by rsimha-amp** [comment]
Should this PR also move extensions/amp-bind/0.1/test/test-bind-impl.js to test/integration?

**Comment by kmh287** [comment]
No, not yet, though it may be necessary to break some of the tests off of that into this integration test.

**Comment by rsimha-amp** [comment]
@kmh287, @choumx: I saw that many bind integration tests had timed out in https://travis-ci.org/ampproject/amphtml/jobs/235635500. Do we need to go back to giving the tests 10 seconds on Travis? Or do you think there's something else at play?

**Comment by choumx** [comment]
☹️ That's a good first guess. Let's try reverting the timeout reduction?

**Pull request merged**
