### PR TITLE
Remove @suppress in custom-element.js

### PR DESCRIPTION
**Pull request by choumx**
Enables stronger type checking in custom-element.js by removing `@suppress` and `@this` annotations. I think these were originally needed on an older version of Closure compiler.

Fixed a few type errors that this caught and verified that this would've caught #23858.

/to @lannka @powerivq

### CODE REVIEW

**Comment by powerivq** [comment]
Thanks @choumx Scanning through the codebase, there are few other places that suppresses checkType presumably for the same reason. Working on some others.

**Comment by lannka** [comment]
cool! thanks for the quick fix

**Comment by choumx** [comment]
This is causing single-pass build to DCE `elementName()`: https://github.com/ampproject/amphtml/blob/687ea0832f7c9ff5b56dad98d1f5c73fd6f58c41/src/custom-element.js#L121-L125 

Investigating.

**Comment by lannka** [comment]
https://github.com/ampproject/amphtml/blob/b8b12cc5ca718d39d28b20c568a4ef1ea824eac2/extensions/amp-mustache/0.2/amp-mustache.js#L33-L37

@choumx there is usage of this `@suppress {checkType}` in amp-mustache. could you also take a look?

**Pull request merged**
