### PR TITLE
🚮 Remove `dict()`

### PR DESCRIPTION
**Pull request by alanorozco**
It's not necessary since we no longer use Closure Compiler.

### CODE REVIEW

**Comment by samouri** [comment]
@alanorozco, can you include a gist of the jscodeshift you created to generate this diff.

**Review by danielrozenberg — APPROVED** [review]
Approval for `.eslintrc.js`

**Comment by samouri** [comment]
Before anyone else approves, I'd love to see impact on bundle size.
Ideally none since `dict()` is essentially identity fn, but my gut says our build system wasn't smart enough and this could have code size wins.

**Comment by alanorozco** [comment]
> @samouri Can you also include a gist of the jscodeshift you created to generate this diff?

Sure! [On AST Explorer](https://astexplorer.net/#/gist/82bf31e2bcd1e1b7090ccf4e623b97b0/9db285bae9ec22b8729be39a6e43d65964fb91d4)

General note on running `jscodeshift` on our codebase. We require a non-default `--parser-config`, which is included in the repo:

```console
npx jscodeshift \
  -t transform-remove-dict.js \
  --parser=babylon \
  --parser-config=build-system/test-configs/jscodeshift/parser-config.json \
  3p/**/*.js \
  ads/**/*.js \
  extensions/**/*.js \
  src/**/*.js
  ```

**Review by jridgewell — APPROVED** [review]

**Comment by alanorozco** [comment]
@samouri Good call on bundle size issues!

All 3p vendor binaries are expanding by 100-200 B. This is caused by a transformation of `{...spread}` objects.

Originally, we have this line on `3p/frame-metadata.js`:

```js
const data = Object.assign(dict(), allMetadata()['attributes']);
```

By removing `dict`, the rule `prefer-spread-props` kicks in so we get:

```js
const data = {...allMetadata()['attributes'])};
```

This has a different build result than the original `Object.assign` call:

```diff

+ function vt(t, n, e) {
+   return (
+     n in t
+       ? Object.defineProperty(t, n, {
+           value: e,
+           enumerable: !0,
+           configurable: !0,
+           writable: !0,
+         })
+       : (t[n] = e),
+     t
+   );
+ }
+ function bt(t, n) {
+   var e = Object.keys(t);
+   if (Object.getOwnPropertySymbols) {
+     var i = Object.getOwnPropertySymbols(t);
+     n &&
+       (i = i.filter(function (n) {
+         return Object.getOwnPropertyDescriptor(t, n).enumerable;
+       })),
+       e.push.apply(e, i);
+   }
  // ...
- const t = Object.assign(g({}), bt().attributes);
+ const t = (function (t) {
+   for (var n = 1; n < arguments.length; n++) {
+     var e = null != arguments[n] ? arguments[n] : {};
+     n % 2
+       ? bt(Object(e), !0).forEach(function (n) {
+           vt(t, n, e[n]);
+         })
+       : Object.getOwnPropertyDescriptors
+       ? Object.defineProperties(t, Object.getOwnPropertyDescriptors(e))
+       : bt(Object(e)).forEach(function (n) {
+           Object.defineProperty(
+             t,
+             n,
+             Object.getOwnPropertyDescriptor(e, n)
+           );
+         });
+   }
+   return t;
+ })({}, At().attributes);
```

Quick and dirty solution is to disable the rule for this case:

```js
const data = Object.assign(Object.create(null), allMetadata()['attributes']);
```

But this would not prevent the issue from occurring in the future. It would be great if we could somehow ensure that the additional helpers are not added, and the simple spread results in a basic `Object.assign` call. We could also update the rule to allow certain cases.

**Comment by jridgewell** [comment]
I thought we had a transform to optimize spread object into `Object.assign`?

**Comment by samouri** [comment]
Thank you so much @alanorozco for doing all of this digging! Super interesting.
I think its ok to merge as-is now that we understand the root cause of the increase.


A good solution could be to enable the [setSpreadProperties](https://babeljs.io/docs/en/assumptions#setspreadproperties) assumption in all of our babel transforms.

**Review by samouri — APPROVED** [review]
I noticed there are ~10 type issues found in this PR, mostly about implicit any.
Assuming all of these had been the `JsonObject` type, I think its fair to cast the problematic variables to `JsonObject` again. Or given the discussions today...a literal `any`.

**Pull request merged**
