### PR TITLE
🔥 Disable linker by default

### PR DESCRIPTION
**Pull request by mantosik**

### CODE REVIEW

**Comment by zhouyx** [comment]
@mantosik This may be a breaking change, do you mind I ask why we're changing the default behavior? Thanks

**Comment by mantosik** [comment]
> @mantosik This may be a breaking change, do you mind I ask why we're changing the default behavior? Thanks

Hi! Yes, this might be a big change, but at the moment it's not working as expected. Probably some things still should be adjusted. At the moment there is such a string added to url ?deepbi=1%2A17877lo%2Adeepbiampid%2ASmxNaHdjYlg5eHcxNDJsRzVhWVBueEFNOV9RS3pGLTluck52d2pGUERuck9sSTBMUWdsNGZ0MmVYTjBzZlNOVw 
If you could advise me how to get only the cookie value in the link. Also is there a way to test the config especially how the linker would work without going on production?

**Comment by zhouyx** [comment]
Hi @mantosik 
The string added to the url is calculated based on the cookie value and the timestamp. You'll need to parse it on the receiving side. More information can be found here. https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/linker-id-receiving.md

 > Also is there a way to test the config especially how the linker would work without going on production

You could test the config by inlining it directly. Or if you have the amp repro, you should be able to test it using our [local server for development](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md#build-amp--run-a-local-server) and [this](https://github.com/ampproject/amphtml/blob/master/examples/analytics-vendors.amp.html) example file.

**Comment by mantosik** [comment]
Hi @zhouyx! Is it possible to merge that?

**Comment by zhouyx** [comment]
@mantosik Sure! Merged the PR per your request.

Have you tested the behavior, and extracted the correct user ID from the linker value?

**Pull request merged**
