### PR TITLE
Mgid add options field

### PR DESCRIPTION
**Pull request by DenyHF**

### CODE REVIEW

**Comment by powerivq** [comment]
Change LGTM. You might want to rebase again to pass all checks.

**Comment by DenyHF** [comment]
@rsimha Hi!
Please approve this PR.

**Comment by rsimha** [comment]
> @rsimha Hi!
> Please approve this PR.

This no longer needs my approval since the bundle size check has passed.

**Comment by DenyHF** [comment]
@powerivq Hi!
when can you merge this RP?

**Pull request merged**
