### PR TITLE
Updates to colanalytics vendor config for amp-analytics.

### PR DESCRIPTION
**Pull request by avimehta**
Per request from @ColombiaAnalytics in #3828

### CODE REVIEW

**Comment by ColombiaAnalytics** [comment]
Hi,

It perfectly fine. Thanks, once again.

**Comment by ColombiaAnalytics** [comment]
Thanks Bro.


Thanks & Regards,

Mukul Tanwar
9717359710
________________________________

**Comment by ColombiaAnalytics** [comment]
Hi Avi,


I was unable to find t changes in "https://cdn.ampproject.org/v0/amp-analytics-0.1.js".


 Will the changes be visible after some time.


Thanks & Regards,

Mukul Tanwar
9717359710
________________________________

**Comment by ColombiaAnalytics** [comment]
Hi Avi,


I couldn't find changes in "https://cdn.ampproject.org/v0/amp-analytics-0.1.js". Have the Merge been completed.


Thanks & Regards,

Mukul Tanwar
9717359710
________________________________

**Comment by avimehta** [comment]
This seems to be live now. Can you confirm?

Release can take somewhere between 7-13 days for changes to go live. If something is wrong with a build, the delay can be longer.

**Comment by ColombiaAnalytics** [comment]
Hi Avi,


Had a query. We observed hits from amp pages, have canonical path incomplete. The domain name is missing from canonical path. Need to know is this the actual canonical path coming from amp pages. As earlier we observed the canonical path coming to be complete. Example


http://timesofindia/news/something/page.cms


But at present we are getting


/news/something/page.cms


The domain name is missing in the canonical path. Please let me know is this the actual behavior for all amp pages.



Thanks & Regards,

Mukul Tanwar
9717359710
________________________________

**Comment by avimehta** [comment]
In a URL like http://timesofindia.com/news/something/page.cms, the CANONICAL_HOST is timesofindia.com. CANONICAL_PATH is /news/something/page.cms and CANONICAL_URL is http://timesofindia.com/news/something/page.cms.  https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vars.md#page-and-content explains this.


So what you are seeing is expected. If you want the full URL, your vendor config needs to be changed.

**Comment by ColombiaAnalytics** [comment]
Hi Bro.


We need to bring CANONICAL_URL in that case. Please help me in this. Need your help.


Thanks & Regards,

Mukul Tanwar
9717359710
________________________________

**Comment by ColombiaAnalytics** [comment]
Hi Avi,

We need to bring CANONICAL_URL in that case. Please help me in this. Need your help.

Thanks & Regards,

Mukul Tanwar
9717359710



Thanks & Regards,

Mukul Tanwar
9717359710


________________________________

**Comment by rudygalfi** [comment]
@ColombiaAnalytics Can you please submit a new pull request that updates your vendor configuration?

**Pull request merged**
