### PR TITLE
Adding ads network Nativeroll

### PR DESCRIPTION
**Pull request by n-randin**
Adding new ad network "NativeRoll"

### CODE REVIEW

**Comment by n-randin** [comment]
@lannka

**Comment by lannka** [comment]
The PR looks good. Did you try to implement [renderStart API](https://github.com/ampproject/amphtml/blob/master/ads/README.md#other-tips)? That will provide a better loading experience.

**Comment by n-randin** [comment]
@lannka thx for review, we'll sure try this Api later

**Comment by n-randin** [comment]
@lannka Do you need something else for merge pull reqest?

**Comment by lannka** [comment]
@n-randin oh, so you want to merge this and get back to renderstart API later? Can do so.

**Pull request merged**
