### PR TITLE
🐛 Re-enable Safari on Sauce labs

### LINKED ISSUE #14848: Karma tests disconnect when running tests on Safari
When running the tests on Travis for my PR #14679, I'm getting: Test disconnected because Safari 11.0.1 is not generating any test output for 2 minutes. https://travis-ci.org/ampproject/amphtml/jobs/369330113#L725 Note that it eventually reports a success in L728.

Have tried running it several times and the problems seems to persist.

### PR DESCRIPTION
**Pull request by rsimha**
From Sauce Labs Help Center:
> We've done some fixes on our backend that might help with the current behavior you're seeing.
Could you try running your suite again and tell us if you see any improvement on the error rate?
If you don't please send us any console logs and build links so we can have a closer look.

Fixes #14848

### CODE REVIEW

**Comment by rsimha** [comment]
/to @choumx 

I'll re-rerun Travis a few times to see if this is indeed fixed.

**Comment by rsimha** [comment]
Trying the fix in https://support.saucelabs.com/hc/en-us/articles/115010079868

**Comment by rsimha** [comment]
@choumx This has passed three times. Latest run: https://travis-ci.org/ampproject/amphtml/builds/383874710

I've re-enabled Safari for unit tests, and Safari and Android browser for integration tests. Looking good after multiple tries.

Merging (fingers crossed)...

**Comment by lannka** [comment]
```
hostname: process.platform === 'darwin' ? '127.0.0.1' : 'localhost',
```

This change broke `test-amp-analytics.js` when running locally, where some tests are doing URL comparison with `http://localhost/` .

Having this discrepancy between environments can be a bug hole. Can we unify to 127.0.0.1 for instance?

**Comment by choumx** [comment]
This also breaks `test-impression.js` locally.

```
FAILED TESTS:
  impression
    clickUrl
      ● should replace location href only with query params
        HeadlessChrome 0.0.0 (Mac OS X 10.13.4)
      AssertionError: expected 'http://127.0.0.1:9876/context.html?bar=foo&test=4321&gclid=123456&foo=bar&example=123' to equal 'http://localhost:9876/context.html?bar=foo&test=4321&gclid=123456&foo=bar&example=123'
          at /var/folders/xy/zdjxmyvn1vjg75zhtgc5r28h006wch/T/test/functional/test-impression.js:264:40 <- /var/folders/xy/zdjxmyvn1vjg75zhtgc5r28h006wch/T/aa74d3bbeb793a22ab3bc8e8dbdee15b.browserify:73683:41

    replaceUrl
      ● should use init replaceUrl parm if viewer has no capability
        HeadlessChrome 0.0.0 (Mac OS X 10.13.4)
      AssertionError: expected 'http://127.0.0.1:9876/context.html?bar=foo&test=4321&gclid=123456&foo=bar&example=123' to equal 'http://localhost:9876/v/s/f.com/?gclid=1234&amp_js_v=1&init'
          at /var/folders/xy/zdjxmyvn1vjg75zhtgc5r28h006wch/T/test/functional/test-impression.js:291:40 <- /var/folders/xy/zdjxmyvn1vjg75zhtgc5r28h006wch/T/aa74d3bbeb793a22ab3bc8e8dbdee15b.browserify:73721:41

      ● should replace location href with replaceUrl from viewer
        HeadlessChrome 0.0.0 (Mac OS X 10.13.4)
      AssertionError: expected 'http://127.0.0.1:9876/context.html?bar=foo&test=4321&gclid=123456&foo=bar&example=123?bar=foo&test=4321#hash' to equal 'http://localhost:9876/v/s/f.com/?gclid=1234&amp_js_v=1#hash'
          at /var/folders/xy/zdjxmyvn1vjg75zhtgc5r28h006wch/T/test/functional/test-impression.js:339:40 <- /var/folders/xy/zdjxmyvn1vjg75zhtgc5r28h006wch/T/aa74d3bbeb793a22ab3bc8e8dbdee15b.browserify:73779:41
```

**Pull request merged**
