### PR TITLE
Minor fixes and edits to updated RTC documentation

### PR DESCRIPTION
**Pull request by Aerlinger**
Fix some typos and improve some formatting in latest RTC documentation.

### CODE REVIEW

**Comment by Aerlinger** [comment]
Per the CLA requirement, I'm a Google Employee so don't need to sign CLA.

**Comment by Aerlinger** [comment]
Ping on this.

**Comment by Aerlinger** [comment]
I signed it!

**Comment by aghassemi** [comment]
Thanks for the pull request. Since this PR has been stale for a while, I am closing it. Please feel free to reopen as needed.

**Pull request closed without merging**
