### PR TITLE
Add variable substitution to amp-iframe on src

### PR DESCRIPTION
**Pull request by claudiorodriguez**
Related to https://github.com/ampproject/amphtml/issues/6234
- Add variable substitution to amp-iframe's `src`
- Add tests (including manual html)
- Add /examples/iframe.var.substitution.amp.html
- Update amp-iframe and amp-var-substitution docs to reflect change

### CODE REVIEW

**Comment by claudiorodriguez** [comment]
I'll probably modify this to exclude `CLIENT_ID` from this PR, as that seems to be the main point of contention.

**Comment by claudiorodriguez** [comment]
Removed substitutions in `srcdoc`, and added use of a whitelist copied over from amp-analytics, with DOCUMENT_REFERRER added in

**Comment by cramforce** [comment]
As discussed in #6234 I don't think we should do this, as analytics via iframes is not a supported use case in AMP.

**Comment by jridgewell** [comment]
Closing as stale.

**Comment by niutech** [comment]
Any updates on this? I would like to embed an HTML document in an <iframe> with URL based on the search query. Please allow this.

**Pull request closed without merging**
