### PR TITLE
✅Add integration test for amp-list & data-amp-replace

### PR DESCRIPTION
**Pull request by calebcordry**
Another follow up to #19061 & #19069.

This _should_ catch anything similar in the future.

### CODE REVIEW

**Comment by calebcordry** [comment]
It appears that `withdrawRequest` will not work in single pass builds. This is blocking this PR. Issue at #19499

**Comment by mrjoro** [comment]
It looks like the blocking issue referred to above was fixed.  @calebcordry is this PR still active?

**Comment by calebcordry** [comment]
@mrjoro yes, this still needs to be done. I will finish up soon.

**Comment by mrjoro** [comment]
Any updates @calebcordry?

**Comment by nainar** [comment]
Closing this PR as inactive. Please reopen if that isn't the case (preferably as a new PR).

**Pull request closed without merging**
