### PR TITLE
forkmedia amp changes

### PR DESCRIPTION
**Pull request by tanish-fork-media-group**
/cc @zhouyx
/cc @lannka

@zhouyx
@lannka 

Added New Formats Support on AMP via Fork Media Ad Server ContextAds

### CODE REVIEW

**Comment by calebcordry** [comment]
thanks for contributing! It looks like you have a couple of lint errors. You can expose them locally by running `gulp lint`.

**Comment by tanish-fork-media-group** [comment]
/cc @calebcordry

I have fixed es lint errors. Can you please review again. Thanks

**Review by calebcordry — APPROVED** [review]

**Comment by calebcordry** [comment]
Thanks for maintaining this extension!

**Review by Goop-arsh — COMMENTED** [review]
R

**Pull request merged**
