### PR TITLE
amp-script: improve illegal mutation messaging

### PR DESCRIPTION
**Pull request by samouri**
**summary**
In https://github.com/ampproject/amphtml/issues/26511#issuecomment-601937159, @morsssss came up with more helpful message for `<amp-script>` illegal mutations. This PR implements them.

On top of that, I also noticed that the `amp-script terminated due to illegal mutation` message happened before the message about dropped mutations. I thought that was confusing so I flipped the order.

Screenshot of new error:
image

### CODE REVIEW

**Comment by morsssss** [comment]
Coolio! This looks great. I also love that you reversed the two error messages. The new order makes more sense!

Only question: what happens when the script makes more than one type of disallowed mutation?

I'm also curious as to why you used a `switch` statement instead of a mapping of error codes to strings. Just for my own edification, so I understand the code standards here 1% more :)

**Comment by samouri** [comment]
> Only question: what happens when the script makes more than one type of disallowed mutation?

All of the errors are printed one after the other.

> I'm also curious as to why you used a switch statement instead of a mapping of error codes to strings. Just for my own edification, so I understand the code standards here 1% more :)

Ha! That could be a better way. The only awkwardness would be that there are two options with the same value (attributes and properties).

**Comment by samouri** [comment]
Wow. The e2e failures are not flakes.

Before this PR, the case where someone attempted to make mutations duration hydration would not terminate the worker. They correctly ignore the illegal ones, but leave the worker intact. This PR changes it so that attempts at illegal mutations within hydration cause worker termination as well.

Concretely, this used to be fail silently but now will fail loudly.
```
<script>
document.getElementById('foo').textContent = 'bar';
</script>
```

**Comment by morsssss** [comment]
Heh, heh... "fail loudly"...

Personally, I'd err on the side of not breaking code that's out there. You might want instead to get in a better place for the long term

If we don't want to start terminating workers that are already out there, I think it would be fine if we just output the new message as a warning, so developers could discover why their code isn't doing anything.

**Pull request merged**
