### PR TITLE
AdSense responsive ads and links

### PR DESCRIPTION
**Pull request by galeksic**
- AdSense responsive content units (exact size, with `@media` queries)
- AdSense responsive link units

Examples added to `adsense.md` page, and to `examples/ads.amp.html` page.

I believe matched content units could be implemented (`data-ad-format="autorelaxed"`), but I'm not able to provide an example, yet.

### CODE REVIEW

**Comment by michaelkleber** [comment]
Welcome, Goran, nice to see you here.  LGTM.

**Comment by cramforce** [comment]
This looks great! Thanks! Could you create a new file called `adsense.amp.html` and keep only one example in the overall list? It is getting a bit long. Thanks!

**Comment by galeksic** [comment]
Thanks @michaelkleber and @cramforce!

You are right - the example list is already too long, and one AdSense is perfectly enough there.

**Comment by cramforce** [comment]
@galeksic Could you rebase and push again? Thanks!

**Comment by galeksic** [comment]
Oops... I think I'll need a little more time. Sorry.

**Comment by gkteck** [comment]
Can someone provide the code snippet to show the responsive ad ?

**Comment by ssmasads** [comment]
Can anyone provide a working example of responsive adsense ad units links?

**Comment by jridgewell** [comment]
Looks like this stalled. @lannka

**Comment by jasti** [comment]
Ping @lannka for review.
@galeksic What's lacking from adding support for matched content units? https://support.google.com/adsense/answer/6111336?hl=en CC @konakk for prioritization.

**Comment by lannka** [comment]
is anyone still working on this? if so, can we start by resolving the merge conflicts?

**Comment by mrjoro** [comment]
Closing for now since it looks like this is still stalled; please reopen when it's ready to move forward.

**Pull request closed without merging**
