### PR TITLE
Fix broken img path in article example page

### PR DESCRIPTION
**Pull request by stefanjudis**

### CODE REVIEW

**Comment by stefanjudis** [comment]
I signed it!

**Comment by stefanjudis** [comment]
Sh... This error doesn't look related to my changes. How should I proceed with this failing build? :)

**Comment by jridgewell** [comment]
Just kicked the test suite to run again. Unfortunately we get some flake. 😞

**Comment by dvoytenko** [comment]
still flaking out?

**Comment by jridgewell** [comment]
Because https://github.com/ampproject/amphtml/pull/3532 isn't in this PR. @erwinmombay, can you merge regardless?

**Comment by stefanjudis** [comment]
Can rebase and bring it in... if desired. :)

**Comment by erwinmombay** [comment]
thanks @stefanjudis !

**Pull request merged**
