### PR TITLE
Add "What's allowed in AMP" video to spec page

### PR DESCRIPTION
**Pull request by pbakaus**
The spec page is highly trafficked due to mostly people wanting to know what's allowed and what isn't in AMP. This PR embeds the latest Amplify video, which gives an overview over exactly that: https://www.youtube.com/watch?v=Gv8A4CktajQ

### CODE REVIEW

**Comment by pbakaus** [comment]
Don't have to, we could also link to it. Just want to offer an alternative
to scanning the page. Open to suggestions.

**Comment by bpaduch** [comment]
A link might be a better idea.  A lot of people access the spec from the amphtml repo, so they won't be able to see the video.

**Comment by pbakaus** [comment]
How's this? Turned it a note instead. Could also move to another part of the doc, please let me know what you think works best.

**Comment by cramforce** [comment]
@rsimha-amp for the link issue.

**Comment by bpaduch** [comment]
Yep, that's what we do.  If we have "example links",we format them as code to avoid the link checker.

**Comment by rsimha-amp** [comment]
@cramforce @pbakaus, reformatting example links that aren't really expected to work as code is the correct thing to do. I'll add this info to the error message so other committers aren't left scratching their heads :)

**Comment by rsimha-amp** [comment]
@pbakaus, I've created #10615 to suggest the fix to anyone who might run into a failure because of an example link.

**Pull request merged**
