### PR TITLE
🐛 Followup fix from BaseCarousel → BentoBaseCarousel rename

### PR DESCRIPTION
**Pull request by danielrozenberg**
PR #35935 missed two `BaseCarousel`→`BentoBaseCarousel` renames, which are causing the `Checks` job on `main` branch CircleCI to fail: https://app.circleci.com/pipelines/github/ampproject/amphtml/15953/workflows/b28786ee-04d3-494d-b839-ec91cda39fd4/jobs/281461

### CODE REVIEW

**Review by caroqliu — APPROVED** [review]
Thanks for catching and fixing this. Do you know why the PR was mergeable given the bad import?

**Comment by danielrozenberg** [comment]
> Thanks for catching and fixing this. Do you know why the PR was mergeable given the bad import?

I believe `amp lint` doesn't run on all files when it comes to PRs, only on the `main` branch. I believe this is a rare enough fault that it's probably not worth running `amp lint` on every PR

// cc @rsimha for visibility

**Comment by caroqliu** [comment]
> > Thanks for catching and fixing this. Do you know why the PR was mergeable given the bad import?
> 
> I believe `amp lint` doesn't run on all files when it comes to PRs, only on the `main` branch. I believe this is a rare enough fault that it's probably not worth running `amp lint` on every PR
> 
> // cc @rsimha for visibility

We have a few cross cutting PRs of a similar nature this sprint so I asked @ampproject/wg-bento and @ampproject/wg-components folks to run `amp lint` on each of those PRs given we won't be enabling more widely.

@rcebulko asked a great question though -
> Does something need to be updated in build-targets so that `--local_changes` and CI react to changes like this?

**Comment by rsimha** [comment]
Since linting all files during CI is fairly time-consuming and is unnecessary for most PRs, we run a full `amp lint` only when there are changes to lint rules or general linting infrastructure (the `LINT_RULES` build target). The rest of the time, we just run `amp lint --local_changes` (the `LINT` build target).

https://github.com/ampproject/amphtml/blob/1e2c80849657030c90aaae5b8568611148227797/build-system/pr-check/checks.js#L57-L61

https://github.com/ampproject/amphtml/blob/1e2c80849657030c90aaae5b8568611148227797/build-system/pr-check/build-targets.js#L210-L233

Can someone link me to the PR for which we should've linted all files but did not? I can try to spot what's missing.

**Comment by rcebulko** [comment]
The problem is that the linting in this case verifies that all imports in file A actually exist in file B. If file B is changed, there's no obvious way to identify that file B needs to be linted without processing/building the full dependency tree, which we don't do. Looking into it a bit, I don't see an obvious solution here outside of some sort of "lint everything please" CI-hint

**Comment by rsimha** [comment]
In general, linting works best on JS files that can be checked in isolation, and the contents of one file do not affect the correctness of another. AMP has a few exceptions (e.g. `forbidden-terms.js`) where files affect one another. In such cases, we add them to `LINT_RULES` and lint the whole repo when they change. E.g. For failures due to new aliased imports, we can add `tsconfig.json` to `LINT_RULES`.

However, it looks like this case is different. I'm curious about why the bug wasn't caught during other parts of the CI workflow like `check-types` or `dist`.

**Comment by rcebulko** [comment]
> In general, linting works best on JS files that can be checked in isolation, and the contents of one file do not affect the correctness of another. AMP has a few exceptions (e.g. `forbidden-terms.js`) where files affect one another. In such cases, we add them to `LINT_RULES` and lint the whole repo when they change. E.g. To catch failures due to new aliased imports, we can add `tsconfig.json` to `LINT_RULES`.

The import linting is another such exception. When it runs on a file (including during development/in the IDE, where it would indicate an error preemptively), it has to check imported files to verify that the imported identifier is actually exported.

> However, it looks like this case is different. I'm curious about why the bug wasn't caught during other parts of the CI workflow like `check-types` or `dist`.

`check-types` doesn't run on extensions; see `build-system/tasks/check-types.js` for the set of typecheck targets and what is included/silenced. `dist` probably didn't error because technically it can compile, but the dead import of `BaseCarousel` resolved to `undefined` and Preact likely handles that in some way when processing the JSX.

**Pull request merged**
