### PR TITLE
✨ Add scrollWdith and viewportHeight to Chartbeat vendor configuration

### PR DESCRIPTION
**Pull request by joshschwartz**
This PR adds scrollWidth and viewportHeight to the Chartbeat vendor configuration, which keeps the information coming from amp-analytics in sync with standard data coming from Chartbeat implementations outside of AMP.

### CODE REVIEW

**Comment by joshschwartz** [comment]
I signed a corporate CLA just before submitting the PR

**Comment by joshschwartz** [comment]
Tagging @avimehta as an owner of amp-analytics. Let me know if I should tag any additional owners/reviewers.

**Comment by joshschwartz** [comment]
The CLA should've gone through; I received confirmation late last week.

**Comment by lannka** [comment]
@joshschwartz sorry for the delay. you can tag @ampproject/wg-analytics next time

**Comment by joshschwartz** [comment]
@lannka No problem and thanks for the info! LMK if I need to do anything else in the process of getting this merged.

**Comment by lannka** [comment]
nothing from your end. i'm restarting the travis build to get the flaky test passed

**Comment by lannka** [comment]
Travis is failing due to #21880 . sorry for the wait.

**Pull request merged**
