### PR TITLE
🐛Remove mask behavior if user deletes from middle of date

### PR DESCRIPTION
**Pull request by cvializ**
/cc @andrewwatterson This will unbreak the existing weirdness in the date mask. If we decide on a better UX when we meet we can replace this with that.

### CODE REVIEW

**Comment by andrewwatterson** [comment]
Boom. I love proactivity.

**Comment by danielrozenberg** [comment]
Weird, that should have worked :fearful: 
If you're not in a rush, you can do `git commit --amend` and `git push --force-with-lease` to re-trigger all the checks, which should hopefully fix this :)

**Comment by danielrozenberg** [comment]
https://github.com/ampproject/amp-github-apps/pull/56 should fix this for later PRs

**Comment by cvializ** [comment]
Thanks for your help @danielrozenberg!

**Pull request merged**
