### PR TITLE
<amp-apester-media> ChangeHeight request

### PR DESCRIPTION
**Pull request by mrsufgi**
As we discussed in https://github.com/ampproject/amphtml/pull/4291
I've opened a PR to ask for changing the call for 'attemptChangeHeight' to 'changeHeight'.

We know that resizing height might be problematic in AMP environment, but the 'overflow' button isn't something we want to add to our product.

Let me explain why we need this functionality and perhaps we can think of a good solution that satisfy both AMP environment guidelines and our product requirements. 

Apester media units are generated via our editor interface with a height attribute. Then, editors embed the newly created unit in their articles. So far so good, but when an editor (or a different editor) edits the unit, the height attribute may change in the process. In this case a unit which was once 300px high is now 650px high. Now,  the editor must to re-embed the unit. Most of our editors are not tech-savy and we prefer to fix their possible mistakes (by not reembedding) and provide an auto-resizing solution and prevent mismatching of heights. (changeHeight solve this out of the box)

Another case is related to our playlist feature. A playlist is a predefined group of medias that may have different sizes which are picked randomly by our service. An editor doesn't know what height the media unit would really be, so we provide the unit with an average height. In LayoutCallback we query our server and we fetch the actual media and its height, so we would like to change the unit's height if necessary. 

this PR uses 'changeHeight' to solve those two cases, without showing the overflow button.

Here in Apester, we want to provide the best user experience to our consumers. therefore, we know that forcing a resize onload might cause some issues. thus, I wanted to offer a different approach for resolving a failed 'AttemptChangeHeight' request. 

Instead of showing an overflow button, a unit would stay hidden (or with a 'loader') as long as it is in the viewport. then, another AttemptchangeHeight would be scheduled when the viewer leaves the viewport. I assume that attempting to resize an off-the-viewport media will always success and then, if the user scroll back he could see the resized unhidden unit. 

This solution would also come handy for other extensions in the future that would need a resize but don't to show a button on their unit.

of course, we may also advise our editors to never embed a playlist media in the top 30% of the viewport (same as the amp-iframe rules), and encourage editors to re-embed their units with the updated height to prevent units from not showing (or hanging on loader until they leave the viewport) 

I think we can work this issue together, thank you all for your time. :) 
@OmriKeret @mkhatib @dvoytenko @OksanaSemenov @Adirbe

I'll keep this branch updated with our initial PR.

### CODE REVIEW

**Comment by mrsufgi** [comment]
@googlebot @Adirbe has signed it on behalf of Apester

**Comment by ericlindley-g** [comment]
@dvoytenko @mkhatib   Just ping'ing this and the other Apester threads for review

**Comment by mrsufgi** [comment]
@dvoytenko just pinging about my update,

We also need to discuss how to make playlist mode work.

But merging this PR and the loader PR would be sufficient for now

**Comment by mrjoro** [comment]
Looks like #6078 supersedes this one.

**Pull request closed without merging**
