### PR TITLE
Skip failing tests in Experiment C branch

### PR DESCRIPTION
**Pull request by caroqliu**
The tests skipped in this PR are [failing consistently in master.](https://app.circleci.com/pipelines/github/ampproject/amphtml/1632/workflows/b015c46e-7d72-44d2-b858-03d61ce0d6a0/jobs/15686) Investigating now but wanted to unblock master first.

cc build hall monitors @kristoferbaxter @estherkim

### CODE REVIEW

**Review by samouri — APPROVED** [review]

**Comment by caroqliu** [comment]
Looks like this did not successfully skip the tests, as [they ran and failed anyway](https://app.circleci.com/pipelines/github/ampproject/amphtml/1664/workflows/5f24f549-4298-4b35-ae0f-4b78b9598b88/jobs/16021). @ampproject/wg-infra please advise 😅

**Comment by rsimha** [comment]
I think this could work if `skipTest` were called in `beforeEach` instead of `before`.

**Comment by caroqliu** [comment]
> I think this could work if `skipTest` were called in `beforeEach` instead of `before`.
> 
> **Edit:** wait... based on this, I'm probably wrong.
> 
> https://github.com/ampproject/amphtml/blob/4ad19072ea1a06b7f9ab5d7b8bae40041275660c/test/_init_tests.js#L392

Yeah, I used `before` for that reason. I wonder if `beforeEach` may still be advisable, since the error only throws for `beforeAll` blocks.

**Comment by rsimha** [comment]
Could it be that `BENTO_AUTO_UPGRADE` isn't being set to `true` even though you're expecting it to?

**Comment by caroqliu** [comment]
> Could it be that `BENTO_AUTO_UPGRADE` isn't being set to `true` even though you're expecting it to? (I'm not sure if constants set in the runtime during build will propagate to test code.)
> 
> The [other call-sites](https://github.com/ampproject/amphtml/search?utf8=%E2%9C%93&q=%22this.skipTest()%22) of `this.skipTest()` in our tests seem to be running dynamic checks for state.

The recent failure of the build for #32582 [here](https://app.circleci.com/pipelines/github/ampproject/amphtml/1668/workflows/80ca7b8f-6adb-4f0c-b4cd-fc76935aed3b/jobs/16072) seems to bolster this hypothesis, since both of these PRs use `BENTO_AUTO_UPGRADE` to gate the code path change. Could it be that this constant is available in e2e test runner but not the integration test runner?  I ask because we did the same here for e2e tests:
https://github.com/ampproject/amphtml/blob/aace6d63dadc240ed112bc1bd59e9d494fe1f83c/extensions/amp-fit-text/0.1/test-e2e/test-amp-fit-text.js#L30-L33

**Comment by rsimha** [comment]
> Could it be that this constant is available in e2e test runner but not the integration test runner?

I did some sleuthing. The constants are replaced by this `babel` plugin:

https://github.com/ampproject/amphtml/blob/36d86e2c6fb86f95e5f9a6a5225b648b348369b6/build-system/babel-config/helpers.js#L41-L99

During `gulp dist --define_experiment_constant`, replacement is done in the pre-closure babel stage:

https://github.com/ampproject/amphtml/blob/36d86e2c6fb86f95e5f9a6a5225b648b348369b6/build-system/babel-config/pre-closure-config.js#L40

We do use the same plugin while transforming test code as well:

https://github.com/ampproject/amphtml/blob/36d86e2c6fb86f95e5f9a6a5225b648b348369b6/build-system/babel-config/test-config.js#L57

However, replacement is gated on the `--define_experiment_constant` flag, and we're not passing in that flag while invoking tests. I've tried fixing this in #32574, and added you as reviewer. If the approach works, There's nothing more to do here.

> Otherwise, I can add a `i-amphtml-fit-text-bento` class in the runtime that we can look for in the DOM instead of relying on a global state expectation.

If not, this sounds like a worthwhile idea.

**Pull request merged**
