### PR TITLE
Bento: add container to the amp-sidebar 1.0

### PR DESCRIPTION
**Pull request by dvoytenko**
Follow up on #33503 for 1.0 version.

Partial for #31915.
Partial for #31540.

### CODE REVIEW

**Review by caroqliu — APPROVED** [review]

**Review by krdwan — COMMENTED** [review]
The changes make sense to me.  I was wondering though, when the component is `unmounted` when the sidebar is closed, does this mean none of the elements within the component would be rendered?  If so, the functionality with `SidebarToolbar` per the current design would conflict with this.

Here is the PR for Toolbar for reference: https://github.com/ampproject/amphtml/pull/33244

This PR introduces a change that instead of unmounting the Sidebar when it's closed, it hides it with `display:none` instead.  This is because the `Sidebar` component can receive a child called `SidebarToolbar` which must always be rendered.  This is because the `SidebarToolbar` uses a portal to render content outside of the `Sidebar` and does so independently from whether or not the `Sidebar` is opened.

**Comment by dvoytenko** [comment]
> The changes make sense to me. I was wondering though, when the component is unmounted when the sidebar is closed, does this mean none of the elements within the component would be rendered? If so, the functionality with SidebarToolbar per the current design would conflict with this.

Yeah, this is very interesting. I'd like to discuss it and understand it better. I'll look for a time.

**Comment by dvoytenko** [comment]
@krdwan In the meantime I switched to `pauseAll()` instead of `unmountAll()` and added tests for that.

**Review by krdwan — APPROVED** [review]

**Comment by krdwan** [comment]
> @krdwan In the meantime I switched to `pauseAll()` instead of `unmountAll()` and added tests for that.

Sounds good, it appears to be working with `pauseAll()`.  Okay let's discuss when you have time!

**Pull request merged**
