### PR TITLE
Allow amp-mustache in a4a

### PR DESCRIPTION
**Pull request by lannka**
For #12903

### CODE REVIEW

**Comment by honeybadgerdontcare** [comment]
Not sure how this passed tests, but amp-mustache needs to be whitelisted for amp4ads here:
https://github.com/ampproject/amphtml/blob/master/validator/engine/validator_test.js#L670

And the spec file also needs to be updated:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/amp-a4a-format.md#amp-extensions-and-builtins

**Comment by lannka** [comment]
@honeybadgerdontcare ha, the test succeed because `amp-mustache` is not a tagName

**Comment by lannka** [comment]
@honeybadgerdontcare test is fixed. Pls take a look

**Comment by honeybadgerdontcare** [comment]
LOL, you're right! Bad test, bad, lol.

**Pull request merged**
