### PR TITLE
✨ add new configuration for grx 

### PR DESCRIPTION
**Pull request by nikolaospanagopoulos**
Adding some new configuration for the Adman advertising.

### CODE REVIEW

**Comment by nikolaospanagopoulos** [comment]
on behalf of Phaistos Networks for Adman ad-server

**Comment by kornarakis** [comment]
Hello :) could you kindly review and approve this pull request? All tests have passed. Thank you!

**Comment by anmarkom** [comment]
Could you please evaluate the current PR?

This supports the new version of the Adman ad-server, Grxchange.gr, by Phaistos Networks S.A..

**Comment by kornarakis** [comment]
Hi @calebcordry. Could you please review this pull request? Thank you very much in advance.

**Comment by itzagkarakis** [comment]
Hello @calebcordry !
Could you please evaluate the current PR?
This is about, Grxchange.gr, by Phaistos Networks S.A.

**Review by powerivq — APPROVED** [review]

**Pull request merged**
