### PR TITLE
add consentHandlingOverride flag for Teads

### PR DESCRIPTION
**Pull request by RomainGuilmet**
Adding consentHandlingOverride flag to Teads

### CODE REVIEW

**Comment by RomainGuilmet** [comment]
@googlebot CLA already Signed on behalf of "Teads" Corporation

**Comment by RomainGuilmet** [comment]
@googlebot CLA Signed on behalf of "Teads" Corporation

**Comment by RomainGuilmet** [comment]
@googlebot CLA Signed on behalf of "Teads" Corporation

**Comment by RomainGuilmet** [comment]
@googlebot I signed it

**Comment by RomainGuilmet** [comment]
Can someone review this please?

**Comment by RomainGuilmet** [comment]
@Gregable could you or someone else in the team review this PR please?

**Comment by Gregable** [comment]
Added a few folks. I typically only do reviews for validator files and am not familiar enough with these to make a call. Thanks for your patience.

**Pull request merged**
