### PR TITLE
Adding server side filtering to amp-live-list docs

### PR DESCRIPTION
**Pull request by ericlindley-g**
@erwinmombay PTAL

I'm guessing I should change "slots" to "reference points", but want to confirm before running through it—WDYT?

### CODE REVIEW

**Comment by erwinmombay** [comment]
@ericlindley-g yep! definitely want to change

**Comment by ericlindley-g** [comment]
Thanks! Updated

**Comment by ericlindley-g** [comment]
@erwinmombay Updated—PTAL

**Comment by erwinmombay** [comment]
@ericlindley-g apologies on super delay. LGTM

**Comment by ericlindley-g** [comment]
Thanks @erwinmombay , and no worries! Can you merge (I'm not authorized : )

**Comment by erwinmombay** [comment]
cc @dknecht for visibility

**Pull request merged**
