### PR TITLE
📖 amp-access-poool: Update documentation & example

### PR DESCRIPTION
**Pull request by dackmin**
- Updates various phrasing in `amp-access-poool` documentation
- Cleans example code

### CODE REVIEW

**Comment by jpettitt** [comment]
@dackmin please rebase to head and push, it should then pass travis.

**Comment by jpettitt** [comment]
Looks like this didn't rebase cleanly - I can't merge it as is.

**Comment by dackmin** [comment]
seeing this now too, closing this PR to reopen a new one

**Pull request closed without merging**
