### PR TITLE
Sharethrough render-start support added

### PR DESCRIPTION
**Pull request by peterkinmond**
Hi, we've added the "renderStart" and "noContentAvailable" methods (refer to #5234).
Could you please review?

Thanks!

### CODE REVIEW

**Comment by peterkinmond** [comment]
We signed the Google CLA on behalf of my company Sharethrough.

**Comment by lannka** [comment]
CLA: Sharethrough

**Comment by lannka** [comment]
CLA robot didn't recognize. Maybe try to mention your corp again?

**Comment by jridgewell** [comment]
@peterkinmond: When using a Corp CLA, you have to author commits using a corp email address (`@sharethrough.com`).

**Comment by lannka** [comment]
>  When using a Corp CLA, you have to author commits using a corp email address (@sharethrough.com).

@jridgewell oh that's the trick? I have no idea what happened in signing corp CLA, does Google collect the corp email domain?

**Comment by jridgewell** [comment]
I think so.

**Comment by peterkinmond** [comment]
@jridgewell Is needing a corp email address a new rule? I'm a member of the [Sharethrough org on Github](https://github.com/orgs/sharethrough/people) and last time we added to AMP project it [wasn't with a corp email address] (https://github.com/ampproject/amphtml/commit/cfb22ca0cd2e9240e9f770b63d0a415f76949703).

**Comment by peterkinmond** [comment]
@lannka Thanks for the quick response in testing out the PR. I see a Sharethrough ad loading consistently on `http://localhost:8000/examples/ads.amp.max.html` when running it locally on my machine. I looked through the developer guidelines you linked to and everything seems to be correct. Is there something else I can do to confirm it's working correctly?  

screen shot 2016-10-13 at 3 25 25 pm

**Comment by lannka** [comment]
Would that be because of any ad targeting so we fall into different loading path? 

screen shot 2016-10-13 at 5 20 02 pm

**Comment by peterkinmond** [comment]
@lannka Ok we've made an update on our side which should now fix it and fire the events correctly. Can you try again?

**Comment by lannka** [comment]
It works now.

@cramforce could you please force merge. We have CLA problem again.

**Comment by cramforce** [comment]
Happy to :)

**Comment by peterkinmond** [comment]
Thanks!

**Pull request merged**
