### PR TITLE
Changes GA param 'vid' to 'cid' in Fast Fetch flow.

### PR DESCRIPTION
**Pull request by glevitzky**

### CODE REVIEW

**Comment by jridgewell** [comment]
Didn't we just change it to `vid`?

**Comment by glevitzky** [comment]
Other way around: https://github.com/ampproject/amphtml/pull/6895.

**Comment by jridgewell** [comment]
Ahhhh. Are there any other places while we're at it?

**Comment by glevitzky** [comment]
I believe that ought to be it.

**Comment by glevitzky** [comment]
No, I don't think anyone on the CAM team has merge rights.

**Pull request merged**
