### PR TITLE
✨amp-experiment 1.0: Added a 15KB limit on amp-experiment JSON

### PR DESCRIPTION
**Pull request by torch2424**
relates to #20225
relates to #21705
relates to #22168

This adds a 15KB limit to the amp-experiment JSON. See the discussion in #22168 for the reasoning. It Was decided offline to add an additional 5KB, since different variants will be input that don't affect the mutation limit. 😄 

This is done all through the validator, and updated the test file accordingly 👍 

cc @Gregable for the validator review
cc @zhouyx for the "concept" review haha! 😂

### CODE REVIEW

**Comment by Gregable** [comment]
This looks as though it has the potential to break existing pages with >15KB on them already. Has anyone yet looked to see if that's a potential risk, or do you need me to run that analysis? (If the latter, this will be next week).

**Comment by torch2424** [comment]
@Gregable Thank you for bringing this up! 😄 

> Has anyone yet looked to see if that's a potential risk, or do you need me to run that analysis?

Could we run the analysis if you don't mind? This isn't super high priority or anything, so next week is fine 😄 👍 

Thanks!

**Comment by torch2424** [comment]
@Gregable Confirmed this should not break anyone (Data is from last month though). But since the old JSON format wasn't very verbose, I think we are fine.

This is good for another review 😄

**Comment by torch2424** [comment]
@zhouyx Says I don't need their approval as well 😂 

Merging... 😄 👍 

Thanks! @Gregable

**Pull request merged**
