### PR TITLE
MoMAGIC Ad Network - Vendor Registration

### PR DESCRIPTION
**Pull request by powerivq**
Opening on behalf of @mmprebid https://github.com/ampproject/amphtml/pull/39956

They are having difficulty creating a workable PR.

### CODE REVIEW

**Review by erwinmombay — APPROVED** [review]

**Review by erwinmombay — CHANGES_REQUESTED** [review]
@powerivq can we keep the author intact

**Comment by powerivq** [comment]
@erwinmombay changed the commit to mmprebid

**Review by erwinmombay — APPROVED** [review]

**Comment by mmprebid** [comment]
We have checked the commit, Please merge this PR accordingly.

**Comment by mmprebid** [comment]
@powerivq 
Thanks for merging the PR, We would like to know that how much time it will take to release on the Google AMP?

**Comment by powerivq** [comment]
@mmprebid https://amp.dev/documentation/guides-and-tutorials/learn/spec/release-schedule AMP releases weekly, so there will be 2 weeks wait. (meaning this week)

**Comment by mmprebid** [comment]
Hi @powerivq 
Now, We are getting the new release but our Momagic Ad Network details are not showing on the live amp ad js and also no info was updated on the amp website.
We would like to know, when it would be updated? or Is there any other process to do?

**Comment by powerivq** [comment]
@mmprebid Look like the PR is now in experimental/beta, and getting to stable will take another week. The PR did not make the week's cut. Website is a different matter and I do not have a timing since we are upgrading the website itself, but there is nothing you need to do.

**Comment by mmprebid** [comment]
@powerivq, Greetings!!
We need assistance for the process to integrate our ad platform with amp-story-auto-ads tag.  
As we are getting issues on amp validator for using amp-ad tag that it cannot be serve through amp-ad tag directly on web stories. We have found that it can be serve through <amp-story-auto-ads> on web stories and some platforms are already registered. 

Can you please share the any details for integration?

**Comment by powerivq** [comment]
@mmprebid For stories, you need to use story auto ads (see this: https://amp.dev/documentation/guides-and-tutorials/develop/advertise_amp_stories) .

**Comment by mmprebid** [comment]
Hi, @powerivq 
We have seen the shared link, we are not getting the proper steps for integration. It was suggested that to do fast fetch integration but there is not steps found for that integration.

Can you share steps for integrating our platform (directly) with story auto ads or any concern support team?

**Pull request merged**
