### PR TITLE
Clean up `gulp test` logging for local development

### LINKED ISSUE #10482: Reduce verbosity of `gulp test` logs
Several tests run on Travis have extremely verbose logs in the passing case. Reduce the log spew, while retaining the ability to see logging in case of errors.

### PR DESCRIPTION
**Pull request by rsimha-amp**
This PR does the following:

- For local `gulp test` runs, replaces the `progress` reporter with `dots` followed by a `mocha` summary
- For local `gulp test --saucelabs` runs, follows up the run with a `mocha` summary
- Changes the log level for local development from `WARN` to `ERROR` to suppress the numerous karma webserver `WARN [web-server]: 404` messages

Fixes #10482

### CODE REVIEW

**Comment by lannka** [comment]
I like the current reporter for `gulp test --files=".."` a lot, I hope this will not change that to dots reporter?

Also, for `gulp test` will the dots reporter print error message immediately, or we have to wait for the summary at the end?

**Comment by rsimha-amp** [comment]
@lannka 

For `gulp test`, you will no longer see the failures inline with the dots. You will either have to wait for the summary at the end, or point your browser to http://localhost:9876/debug.html to see the tests as they are being run. Let me know if this is a deal breaker.

Also, this won't change the existing behavior for `gulp test --files`. You will see:

**Comment by rsimha-amp** [comment]
We now have inline error logging for local development. Checking this in once tests pass.

**Pull request merged**
