### PR TITLE
please add i-mobile 3p amp-ad support

### PR DESCRIPTION
**Pull request by imobile**
Please add i-mobile 3p amp-ad support

We have a Google Corporate CLA.
Our CLA: i-mobile Co.,Ltd
Our company name: i-mobile Co.,Ltd

Thanks in advance

### CODE REVIEW

**Comment by imobile** [comment]
@cramforce Hi sorry for the inconvenience. We have recreated our new pull req since we messed up something in #2470

We would appreciate it very much if you could have it double checked. Thanks again!

**Comment by cramforce** [comment]
LGTM

**Comment by imobile** [comment]
@cramforce Hi! Would you please let us know when will the next stable revision ("latest release") be released? Our changeset has been in dev-channel for two weeks and we want to figure out a timeline for our amp business. Thanks a lot!!

**Comment by cramforce** [comment]
Probably happened today. CC @erwinm

**Comment by imobile** [comment]
@erwinmombay Hi! Would you please let us know when will the next stable revision ("latest release") be released? Our changeset has been in dev-channel for two weeks and we want to figure out a timeline for our amp business. Thanks a lot!!

**Comment by imobile** [comment]
@cramforce 
Hi sir! We are planning to integrate our ad tracking and targeting features into amp system. We want to dig out a best practice and we have some options now:
1. Add tracking and targeting logic in amp-ad approach
2. Create our own analytics vendor and use built-in amp-analytics tag. (But we don't want to expose our analytics engine to public so we are getting confused)
3. Is there another approach?

We really want to hear from your advises and they will be very important to our business. Thanks in advance!

**Comment by rudygalfi** [comment]
The `amp-analytics` tag is intended to be used directly by the publisher. Therefore, I think if you need this to be working with your ad serving, then it should be integrated with `amp-ad`, which is option 1.

**Comment by avimehta** [comment]
regarding 2): Currently `amp-analytics` only works on the AMP pages. If your ad is going to be in an iframe, it won't work (unless you serve your ad in amp format and include amp-analytics there). As for exposing the analytics engine details, you only need to expose the URL format and use the [config attribute](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#attributes).

**Comment by imobile** [comment]
@avimehta @rudygalfi @dvoytenko Thanks a lot!

**Pull request merged**
