### PR TITLE
✨ `amp-story-desktop-one-panel` Position of ad badge and progress bar in new one-panel UI

### LINKED ISSUE #34785: `amp-story-desktop-one-panel` confirm display of `amp-story-auto-ads`.
Be sure that `amp-story-auto-ads` displays correctly in the `amp-story-desktop-one-panel` UI.

### PR DESCRIPTION
**Pull request by processprocess**
Context / fixes #34785

Positions badge and progress bar based on story panel in new `amp-story-desktop-one-panel` UI.

Screen Shot 2021-06-18 at 1 09 31 PM
 
Screen Shot 2021-06-18 at 1 09 52 PM

Progress bar and badge:
Screen Shot 2021-06-18 at 3 32 59 PM

### CODE REVIEW

**Review by calebcordry — COMMENTED** [review]
Can you please add a test? It should be very similar to this one https://github.com/ampproject/amphtml/blob/96a7224f6a66c6920f392727c2fb8e03a714e5b0/extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js#L328

**Review by gmajoulet — APPROVED** [review]
LGTM pending Caleb's comment : ))

**Comment by processprocess** [comment]
> Can you please add a test? It should be very similar to this one
> 
> https://github.com/ampproject/amphtml/blob/96a7224f6a66c6920f392727c2fb8e03a714e5b0/extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js#L328

Thanks for pointing this out.
It helped me notice that I need to add CSS for positioning the progress bar!

**Review by calebcordry — APPROVED** [review]
Thanks! Please keep me updated on this launch. There is a decent amount of 3 panel code that would be good to clean up when ready.

**Pull request merged**
