### PR TITLE
🏗 Stop reporting gzipped compressed size in the bundle-size task

### LINKED ISSUE #21275: Change bundlesize reporter to use brotli size
The gzip file size is largely irrelevant now, and certain optimizations we make that reduce the size of the gzip output can actually increase the size of the brotli output.

### PR DESCRIPTION
**Pull request by danielrozenberg**
Fixes #21275

Step 3.i. in https://github.com/ampproject/amphtml/issues/21275#issuecomment-518403361

### CODE REVIEW

**Comment by danielrozenberg** [comment]
This is weird. This PR should not change the bundle-size. @rsimha could this be some git/github merge issue?

**Comment by rsimha** [comment]
> This is weird. This PR should not change the bundle-size. @rsimha could this be some git/github merge issue?

Weird indeed. I did a sanity check. The Travis [job](https://travis-ci.org/ampproject/amphtml/jobs/582880109) for this PR uses 2ee0c08 as a baseline (bundle size is [72.18KB](https://github.com/ampproject/amphtml-build-artifacts/blob/master/bundle-size/2ee0c086b591872bca7d3fe9416508b3e978f8ef.br)). The brotli size for this PR is 72.13KB even though there are zero runtime changes.

@jridgewell any way to explain this reduction in brotli size in the absence of runtime code changes?

**Comment by jridgewell** [comment]
Newer brotli installed?

**Comment by danielrozenberg** [comment]
They're two hours apart...

**Comment by jridgewell** [comment]
🤷‍♂️

**Comment by danielrozenberg** [comment]
Oh oh... brotli sizes are consistent at all - they keep changing between master builds, even when two consequtive builds only change extensions or docs.

I should have checked this in advance. I'm going to revert the Bundle-Size bot to use gzip for now, which remains consistent, and investigate tomorrow

**Comment by rsimha** [comment]
> Oh oh... brotli sizes aren't consistent at all - they keep changing between master builds, even when two consecutive builds only change extensions or docs.

This is unfortunate :frowning_face: Are you seeing different sizes when you run `brotli-size` multiple times on the same SHA?

Paging @erwinmombay, author of `brotli-size` to see if there's a way to make it return a consistent size for the same code.

**Comment by rsimha** [comment]
I did some experimentation, and it turns out that changing the RTV string in `v0.js` changes the brotli size, even if there are no other code changes.

In the example below, we're computing the gzipped and brotli bundle size of `v0.js` for two commits, where the only difference is the RTV string. The gzipped size remains unchanged, but the brotli size swings by 0.05KB.

I tried passing `{mode: 1}` to `brotliSize.fileSync()` to indicate that we're compressing a text file, but there was still a size fluctuation when the RTV string changed.

```sh
$ gulp bundle-size --on_local_build
[16:56:26] Using gulpfile ~/src/amphtml/gulpfile.js
[16:56:26] Starting 'bundle-size'...
[16:56:26] Computing bundle size for version 1909102024530 at commit fa43674.
[16:56:26] Running npx bundlesize -f "./dist/v0.js"...
[16:56:31] Bundle size (gzipped) is 84.41KB
[16:56:31] Bundle size (brotli) is 72.09KB
[16:56:31] Finished 'bundle-size' after 4.97 s

$ gulp bundle-size --on_local_build
[16:58:21] Using gulpfile ~/src/amphtml/gulpfile.js
[16:58:21] Starting 'bundle-size'...
[16:58:21] Computing bundle size for version 1909102056380 at commit cc3aa51.
[16:58:21] Running npx bundlesize -f "./dist/v0.js"...
[16:58:25] Bundle size (gzipped) is 84.41KB
[16:58:26] Bundle size (brotli) is 72.14KB
[16:58:26] Finished 'bundle-size' after 4.69 s
```

**Comment by kristoferbaxter** [comment]
This appears correct to me, the size of the resource should change when the contents shift.

If we're looking for an apples - apples comparison, we should inject the same values into the resulting files.

**Comment by rsimha** [comment]
> we should inject the same values into the resulting files.

Chatted offline with @jridgewell, and came up with the idea of making a copy of `v0.js`, normalizing it by replacing the RTV with a constant string, and computing the brotli size. There will still be size fluctuations due to other changes that shouldn't change the size, say if someone fixes a typo in an error string, but these should be under the size increase threshold.

@danielrozenberg how easy will it be to retrofit this into `gulp bundle-size`?

**Comment by kristoferbaxter** [comment]
`say, if someone fixes a typo in an error string` 

@alanorozco how close are we to replacing all error strings with integer representations?

Once this is resolved, error strings shouldn't be included in production output.

**Comment by rsimha** [comment]
> Once this is resolved, error strings shouldn't be included in production output.

Good to know. My original point still remains though. For instance, I just discovered that changing a single instance of the number `42` in `v0.js` to `41` causes a 50 byte swing in brotli size.

I'm concerned that this will be annoying when (if? :smiley:) we deploy brotli as the default means of verifying bundle size increases.

**Comment by danielrozenberg** [comment]
> > we should inject the same values into the resulting files.
> 
> Chatted offline with @jridgewell and came up with the idea of making a copy of `v0.js`, normalizing it by replacing the RTV with a constant string, and computing the brotli size. There will still be size fluctuations due to other changes that ideally shouldn't change the reported size (say, if someone fixes a typo in an error string), but the hope is that these are rare, and will be under the size increase threshold.
> 
> One invariant we can guarantee by doing this is that if the code is the same, the size is the same.
> 
> @danielrozenberg how easy will it be to retrofit this into `gulp bundle-size`?

This seems like a semi-reasonable idea. There still remains the issue that the real served size will fluctuate because the RTV number will be different in reality, but this check isn't about absolute sizes, it's about relative sizes.

I think it shouldn't be a big deal to make this happen, I'll give it a quick attempt today and report back. Other than the RTV, are there any other values that change based on unpredictable factors? Once we start collecting data about extension files as well that could become a relevant question

**Comment by rsimha** [comment]
Right now, it's just the RTV. Thanks for making the change.

**Comment by rsimha** [comment]
@danielrozenberg Seems like this is breaking master?

https://travis-ci.org/ampproject/amphtml/jobs/592809416#L519

**Comment by danielrozenberg** [comment]
Oops, another data migration plan gone wrong... @rsimha can you please
revert this for me and I'll fix it later today?

**Pull request merged**
