### PR TITLE
Adds support for AdPlugg ads. Implements #13345.

### PR DESCRIPTION
**Pull request by collinkrawll**
Adds support to amp-ad for the AdPlugg type. Implements #13345.

### CODE REVIEW

**Comment by lannka** [comment]
@collinkrawll thanks for the PR.

Could you implement render-start API? 
https://github.com/ampproject/amphtml/blob/master/ads/README.md#developer-guidelines-for-a-pull-request

**Comment by collinkrawll** [comment]
@lannka Will do.

**Comment by collinkrawll** [comment]
@lannka Can you see what the errors are in percy and saucelabs? Is there a way for me to get at that info or can you forward it to me? Thanks!

**Comment by lannka** [comment]
@collinkrawll 
Re-running travis test. I don't think the percy test is your fault either. @rsimha-amp

**Comment by lannka** [comment]
I saw @rsimha-amp is suggesting in another thread to sync your branch to master head to solve the percy failure. Can you give it a try?

**Comment by collinkrawll** [comment]
@lannka Thanks, that worked!

**Pull request merged**
