### PR TITLE
Simplify isLocalDev logic in mode.js

### PR DESCRIPTION
**Pull request by rsimha-amp**
Now that `gulp`, `gulp watch`, `gulp build`, and `gulp dist --fortesting` all enable `localDev` by default, this PR simplifies the logic behind `isLocalDev` in `src/mode.js` based on the suggestion presented in https://github.com/ampproject/amphtml/issues/12054#issuecomment-355133769.

Tested by making sure that `localDev` is set to true in the locally served `AMP_CONFIG` after each of the following:
- [x] `gulp`
- [x] `gulp watch`
- [x] `gulp build && gulp serve`
- [x] `export AMP_TESTING_HOST=<hostname> && gulp build && gulp serve --host=<hostname>`
- [x] `gulp dist --fortesting && gulp serve --compiled`
- [x] `export AMP_TESTING_HOST=<hostname> && gulp dist --fortesting && gulp serve  --compiled --host=<hostname>`

Partial fix for #12054

### CODE REVIEW

**Comment by rsimha-amp** [comment]
@lannka Some unit tests are failing because they expect `localhost` URLs. See https://travis-ci.org/ampproject/amphtml/jobs/325212583

I'm looking at them one by one, but let me know if you are aware of a wholesale fix for tests.

**Comment by rsimha-amp** [comment]
Just one failure remains to be debugged.

@bradfrizzell, any idea why [this](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/0.1/test/test-real-time-config-manager.js#L336) test sets `env.win.AMP_MODE.test` to false even though we are in a unit test? The test is [failing](https://travis-ci.org/ampproject/amphtml/jobs/325254998#L733) with the new simplified `isLocalDev` logic that's being introduced in this PR. Any idea why this is happening?

**Comment by rsimha-amp** [comment]
@bradfrizzell never mind, I figured out the issue. With the simplified `localDev` logic, we no longer need the `getMode` workarounds in [real-time-config-manager.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/0.1/real-time-config-manager.js#L154) and [test-real-time-config-manager.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/0.1/test/test-real-time-config-manager.js#L336).

**Comment by bradfrizzell** [comment]
Hey Raghu, I think this PR or another one related to the same thing may have broken localDev behavior. I am currently trying to run local examples, but they are improperly requesting scripts from the cdn instead of the local builds. 

https://github.com/ampproject/amphtml/blob/master/src/service/extensions-impl.js#L651 is the line that breaks, it is returning that localDev is false in the call to getMode

**Comment by rsimha-amp** [comment]
@bradfrizzell  If you're building locally via `gulp`, `localDev` should be true. Could you send me repro steps? Are you synced to `master`? What do you see when you type `AMP_CONFIG` in the chrome dev console?

**Comment by rsimha-amp** [comment]
I'm working on a fix for ads in #12673. I'll try to fix this issue too.

**Comment by bradfrizzell** [comment]
Hey Raghu, I posted my above comment after checking out master, and running gulp clean, gulp build, gulp. However, now I tried those steps again, and this time something has seemed to click for my browser and the issue has disappeared. So hopefully this was just some weird caching problem in my browser and can be ignored.

**Pull request merged**
