### PR TITLE
fix(playbuzz): Parent url and host which passed to the Playbuzz iframe was not correct

### LINKED ISSUE #13432: amp-playbuzz iframe parent url is not correct
## amp-playbuzz iframe parent url is not correct

The parent URL and the parent host are not correct and the amp-playbuzz iframe can't make customization for sites who use amp-playbuzz

## It happens always for any amp page, reprodusing:
1. go to https://amp-elmundo-es.cdn.ampproject.org/v/s/amp.elmundo.es/f5/comparte/2017/08/08/597b652146163f3f458b461a.html?amp_js_v=0.1&usqp=mq331AQECAEYAQ%3D%3D
2. inspect amp-playbuzz iframe
3.  Playbuzz iframe URL parameters parentUrl and parentHost are from the cdn and not http://www.elmundo.es/f5/comparte/2017/08/08/597b652146163f3f458b461a.html

### PR DESCRIPTION
**Pull request by shaibo10**
# Playbuzz: fixing the parent url and parent host for the Playbuzz iframe

This fix will help the iframe to know where it embedded and to add specifications to some sites
:bug:
fix #13432

### CODE REVIEW

**Comment by aghassemi** [comment]
@buzzdan, as the owner of the component, could you please take a look to make sure this is fine?

**Comment by buzzdan** [comment]
@aghassemi @shaibo10 
Thanks for the PR!
All together, the solution looks good to me, 

i would feel more comfortable to see it covered with tests 
i'm not sure the current tests are covering this scenario

**Comment by shaibo10** [comment]
I signed it!

**Comment by shaibo10** [comment]
@buzzdan it complicated to add this test, 
because I need to change the URL to the cdn URL and I can't

**Comment by buzzdan** [comment]
I see,
since its an internal change and users are not effected by it , 
i'd say we should go ahead and merge it

@shaibo10 @aghassemi

**Pull request merged**
