### PR TITLE
fixSmallTypoIn3pCompanyName

### PR DESCRIPTION
**Pull request by amoad-amoe**
I found a trivial typo of our company name.
Could you merge this? thanks.

Amoad -> AMoAd

### CODE REVIEW

**Comment by amoad-amoe** [comment]
I intend to submit this PR under the AMoAd CLA.

**Comment by erwinmombay** [comment]
@amoad-amoe LGTM! thanks again

**Comment by amoad-amoe** [comment]
@erwinmombay Thanks! I'm afraid I have no valid CLA? googlebot always ask me to sign it, but I can't sign the way he indicates...

**Comment by erwinmombay** [comment]
@amoad-amoe should be fine, i can merge it. I know you've contributed before and i see amoad already registered. just waiting for a green build

**Pull request merged**
