### PR TITLE
Fix typos in docs

### PR DESCRIPTION
**Pull request by mrngoitall**

### CODE REVIEW

**Comment by mrngoitall** [comment]
The `CONTRIBUTING.md` file says 
>"Please mark pull requests that are ready for review with the "NEEDS REVIEW" label."

but we don't have access to add labels. Should that sentence be revised to ask contributors to leave a comment on the PR to confirm that it's ready to be reviewed?

**Comment by erwinmombay** [comment]
@mrngoitall good point :P

**Comment by erwinmombay** [comment]
@mrngoitall you fixed more than i pointed out! noooooooo more workkkk lol

**Comment by erwinmombay** [comment]
LGTM

**Comment by mrngoitall** [comment]
:grin:

**Pull request merged**
