### PR TITLE
🧪 Enable build-in-chunks experiment in canary-config.json

### PR DESCRIPTION
**Pull request by kevinkimball**
Enables experiment from https://github.com/ampproject/amphtml/pull/28553 to limit number of elements that can be built in a single pass. This issue is affecting amp.dev and causing a long task .

### CODE REVIEW

**Review by jridgewell — APPROVED** [review]

**Comment by samouri** [comment]
I think you could test on amp.dev today with `AMP.toggleExperiment`

**Comment by kevinkimball** [comment]
@samouri Yes, tested some locally and it seems to be a big improvement. Want to get data so we can feel comfortable rolling out completely.

**Comment by kevinkimball** [comment]
@ampproject/build-cop can we skip the Percy test here? Seems erroneous

**Comment by samouri** [comment]
> @samouri Yes, tested some locally and it seems to be a big improvement. Want to get data so we can feel comfortable rolling out completely.

One of our hypotheses was that this would drastically improve `fid`, but at a potential cost to lcp/fcp. I'm excited to see experimental data 🚀

**Comment by danielrozenberg** [comment]
> @ampproject/build-cop can we skip the Percy test here? Seems erroneous

Yep, this is a familiar flaky page. Approved it!

**Pull request merged**
