### PR TITLE
✨Implement rtc-config dotandads for amp-tag

### PR DESCRIPTION
**Pull request by dotandads**
fixs check lint

OWNERS

prettify

fix presubmit

fix dep-check

fix check-types

fixs test

fixs test

### CODE REVIEW

**Comment by dotandads** [comment]
Hi @jridgewell ,
we've a problem with the test.
It,s filed for "✗ sinon is not defined", but we've found this issue:
https://github.com/ampproject/amphtml/issues/25371

how can we proceed?

Thanks

**Comment by dotandads** [comment]
Hi @zhouyx ,
we'he a problem with the Travis tests.
Can you help us?

Thanks

**Comment by rcebulko** [comment]
> Hi @jridgewell ,
> we've a problem with the test.
> It,s filed for "✗ sinon is not defined", but we've found this issue:
> #25371
> 
> how can we proceed?
> 
> Thanks

@rsimha Is this related to some of the recent sinon upgrade/cleanup stuff, or is that all still in PR?

**Comment by rsimha** [comment]
> @rsimha Is this related to some of the recent sinon upgrade/cleanup stuff, or is that all still in PR?

I'm still investigating this via #23726. Right now, it's an occasional flake, so maybe you can retry the PR jobs that failed?

**Comment by zhouyx** [comment]
to @ampproject/wg-ads @lannka

**Comment by lannka** [comment]
@dotandads I saw this is mostly a copy of the `amp-ad-network-fake-impl`, which contains many unwanted pieces.

Have you looked at our template ad solution to do faster ad? https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-custom/amp-ad-custom.md

**Comment by scaverio** [comment]
> @dotandads I saw this is mostly a copy of the `amp-ad-network-fake-impl`, which contains many unwanted pieces.
> 
> Have you looked at our template ad solution to do faster ad? https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-custom/amp-ad-custom.md

Hi @lannka ,
thanks for your response.
We've used _amp-ad-network-fake-impl_  as a starting point and removed what we thought was unnecessary. Is the removal of these **unwanted pieces** mandatory for the approval?

Thanks

**Comment by dotandads** [comment]
Hi to all,
can you give us a feedback?
@lannka @zhouyx @jridgewell 

Thanks

**Comment by jridgewell** [comment]
Ping @ampproject/wg-ads

**Comment by lannka** [comment]
sorry for the delay. For easier communication, we can move the conversation to [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels). Please join the wg-ads channel. 

Basically we want to understand better what you plan to do. Do you want RTC? Or do you want to do fast fetch ads? Or do you plan to support AMPHTML ads.

**Comment by lannka** [comment]
feel free to reopen if this is still needed.

**Pull request closed without merging**
