### PR TITLE
Launch `svg-in-mustache` as amp-mustache-0.2.js

### LINKED ISSUE #15123: SVG support in mustache templates
Track the effort to support SVG in amp mustache templates. As mentioned and discussed in this issue #1156 

- assess DOMPurify integration or adopt similar logic in amp mustache. This is just usage in templates
- assess future work to integrate similar logic into the validator for usage outside of templates.

### PR DESCRIPTION
**Pull request by choumx**
Fixes #15123.

- Add version 0.2 for `amp-mustache` with DOMPurify instead of Caja
- Remove `svg-in-mustache` experiment in version 0.1
- Split off non-Caja code from `sanitizer.js` to `purifier.js` (DCE wasn't working otherwise 🤷‍♂️ )
- Upgrade `dompurify` from 1.0.4 to 1.0.5

Binary size savings!
```
willchou$ ls -al dist/v0 | grep mustache
-rw-r--r--   1 willchou  eng   20531 Jun 14 15:58 amp-mustache-0.1.js.gz
-rw-r--r--   1 willchou  eng   12244 Jun 14 15:58 amp-mustache-0.2.js.gz
```

TODO in follow-up: 
- Validator changes
- Documentation updates

### CODE REVIEW

**Comment by honeybadgerdontcare** [comment]
@choumx @Gregable will the rules between version 0.1 and 0.2 eventually become different? We currently don't support that in validation so it will be something we'll need to prioritize.

**Comment by choumx** [comment]
No plans yet. Version bump is due to using a different runtime sanitizer which could cause breaking changes.

I would like to deprecate 0.1 eventually and start sending validator warnings. At the moment it looks like that would require duping the tag spec. Is that right?

**Comment by honeybadgerdontcare** [comment]
It'd require changes to the engine. AFAIK (not looking at the code), we don't have a way to require one extension spec and not another based on version alone.

**Comment by choumx** [comment]
Splitting validator changes into separate PR to make sure new files are released first.

**Pull request merged**
