### PR TITLE
Add the AMP Cache SW's experiment configs

### PR DESCRIPTION
**Pull request by jridgewell**

### CODE REVIEW

**Comment by erwinmombay** [comment]
@jridgewell do we want these here now? we probably only want this when we turn it on so that these aren't prefixed all the time. although i guess we could also have the build system prune any falsey or empty values but we don't really have that convention established

**Comment by jridgewell** [comment]
"Aren't prefixed"?

**Comment by erwinmombay** [comment]
@jridgewell sorry, meant prepended.

**Comment by jridgewell** [comment]
I dunno.

**Comment by erwinmombay** [comment]
so we prepend this json at the beginning of v0.js, alp.js and soon sw.js, just adds a few bytes thats all instead of when we actually have one of those flags on.

was also going to ask if we could shorten it to something like `c-sw-kill` too lol (since now is the best time to ask)

**Comment by jridgewell** [comment]
Can we build a `sw-config.json`?

**Comment by erwinmombay** [comment]
@jridgewell yep. do want a canary/prod set up too?

**Comment by jridgewell** [comment]
Nah, I think just a prod for now is fine.

**Comment by erwinmombay** [comment]
sgtm

**Pull request closed without merging**
