### PR TITLE
amp-iframely validation update

### PR DESCRIPTION
**Pull request by honeybadgerdontcare**
add also_requires_attr to data-url for data-key

### CODE REVIEW

**Comment by honeybadgerdontcare** [comment]
@iparamonau for your consideration on adding this check for amp-iframely, see the last invalid test in the test .out file

**Comment by iparamonau** [comment]
Thanks, @garmoncheg will take a look tomorrow.

**Review by alanorozco — APPROVED** [review]

**Comment by garmoncheg** [comment]
Thanks, this is looking great now. Perhaps, these lines:
https://github.com/ampproject/amphtml/blob/main/extensions/amp-iframely/0.1/amp-iframely.js#L225-L265
are now a little redundant and obsolete with the validation trigger.
Shall we remove these checks and associated tests in a separare PR or it’s fine with you to keep them? Feel free to delete the checks and test in this PR yourself too, if it’s faster.

**Comment by honeybadgerdontcare** [comment]
It's fine with me to keep them.

**Pull request merged**
