### PR TITLE
Remove unused variable in the colombia js

### PR DESCRIPTION
**Pull request by ColombiaOnline**
Hi 

We have removed following unused variables in the script.
1: clmb_divid
2: loadingStrategy

commit id  : 7e3dd2d79d90665c8f62128472a8a5c749e16b07

### CODE REVIEW

**Comment by lannka** [comment]
@ColombiaOnline could you sync to latest master branch?

**Comment by ColombiaOnline** [comment]
@lannka we have sync to latest master branch.

**Comment by lannka** [comment]
@ColombiaOnline can you confirm it's synced to master head? As you can see, Github is still reporting conflicts.

**Comment by ColombiaOnline** [comment]
create new pull request

**Pull request closed without merging**
