### PR TITLE
Add trailing newlines to validator files to ensure they work well with tools that process text files.

### PR DESCRIPTION
**Pull request by Gregable**
A number of validator .out files have accrued with no newline on the final line of text. This can cause issues for some text processing utilities, so this small CL cleans this up.

### CODE REVIEW

**Comment by Gregable** [comment]
Wrong rotation reviewer, fixed.

**Comment by newmuis** [comment]
Quick question: does the script that outputs these `.out` files also append a newline to the end of the file? (I admit, I haven't run it myself in a while)

**Comment by twifkak** [comment]
Just a guess (vague memory), but there may be a discrepancy between the JS one run by `amp validator` and the C++ one run in Google.

**Comment by Gregable** [comment]
> Quick question: does the script that outputs these `.out` files also append a newline to the end of the file? (I admit, I haven't run it myself in a while)

It's been a while since I last dug into this, but if I recall correctly (not confident): 

It doesn't append a newline. However, if the `.html` file has it's last line ended with a newline, then the `.out` file should too. Folks create the `.html` files in a variety of ways. The tests try to not break based on this newline / non-newline, so it's pretty much diffs only in the sync'ing between these codebases. I don't particularly care, but they are making it harder for me to see if there are any real diffs.

If you see a reason to believe the above recollection is incorrect, I'm happy to research further.

**Pull request merged**
