### PR TITLE
amp-ad implementation for ezoic

### PR DESCRIPTION
**Pull request by superbaddude**
add support to amp-ad for the Ezoic type

### CODE REVIEW

**Comment by lannka** [comment]
@superbaddude please add an example to `examples/ads.amp.html` and get it working locally by [running a local gulp server](https://github.com/ampproject/amphtml/blob/master/DEVELOPING.md).

**Comment by lannka** [comment]
@superbaddude pls also resolve merge conflict

**Comment by lannka** [comment]
Well done. LGTM

**Comment by lannka** [comment]
Let me know if you've done with all the changes, and then I will merge it.

**Comment by dynes** [comment]
Yes, we are finished with the changes.

**Pull request merged**
