### PR TITLE
Revert promise polyfill related changes

### PR DESCRIPTION
**Pull request by cramforce**
They didn't pass tests on browsers that used them.

### CODE REVIEW

**Comment by cramforce** [comment]
CC @jridgewell

**Comment by dvoytenko** [comment]
I recently used `Promise.all` in a couple of places. I think it was mostly within `test-viewer.js`, but not 100% that was it.

**Comment by cramforce** [comment]
Fails lint :)

Will fix

**Comment by cramforce** [comment]
Fixing, but because we run those only in Chrome it didn't fail

**Comment by jridgewell** [comment]
Damn, what was failing?

**Comment by cramforce** [comment]
Somehow we had a broken process.nextTick in AMP (which is weird in itself) that your code called. And then there was a reference error in the uncaught handling.
https://github.com/jridgewell/PJs/blob/master/promise.js#L173

**Comment by cramforce** [comment]
Its also worth investigating why the test that kills promises in did not fail in Chrome. It did fail in Safari 9

**Comment by cramforce** [comment]
@jridgewell haven't yet figured out why the test succeeded in Chrome. I'm also puzzled by it seemingly passing on SauceLabs, but I think that was because that `process.nextTick` thing is not included in our closure based builds and we run SL with `--compiled`. With that our production impact was likely also very limited, since that unhandled exception error didn't break anything per se.

**Comment by jridgewell** [comment]
Yah, it probably just broke proper error reporting since the error changes from the unhandled promise rejection to a reference error. I've pushed a new version to PJs to fix the issues (and tested them!), so I'll start digging into the Safari issue.

PS. `git revert -m 1 7394ae4551201f68226a86db1f4a8bf833438137` (7394ae4551201f68226a86db1f4a8bf833438137 is my merge commit) will roll back a PR in a single commit.

**Comment by jridgewell** [comment]
Re: #2079

**Pull request merged**
