### PR TITLE
Fix boolean logic in throttling and take throttling back a little.

### PR DESCRIPTION
**Pull request by cramforce**
The initial values were too low.

We will now see 10x less CDN errors. Canary is unchanged, but 10x less across the board for user errors.

### CODE REVIEW

**Comment by cramforce** [comment]
This is already in prod.

**Comment by erwinmombay** [comment]
@cramforce thats 100% canary, 3p and cdn is 10%? correct?

**Comment by erwinmombay** [comment]
LGTM

**Comment by cramforce** [comment]
Correct

**Comment by cramforce** [comment]
Should be easy to make changes now.

**Comment by erwinmombay** [comment]
@cramforce that's if we know how to deploy it 😸

**Comment by erwinmombay** [comment]
@cramforce deploying new code should just be as easy as changing the version though right? i know you mentioned about some weird go setup and that is already in place correct?

**Comment by cramforce** [comment]
LOL. Basically every time we launched something the version should be incremented.

But then one has to go into GAE console and actually switch serving.

**Comment by erwinmombay** [comment]
@cramforce right. guess i was expecting one had to do the whole Go setup all over again. but if not then yeah, easy

**Pull request merged**
