### PR TITLE
Assert valid URL

### PR DESCRIPTION
**Pull request by alanorozco**
/cc @erwinmombay @jridgewell

### CODE REVIEW

**Comment by jridgewell** [comment]
Please rebase once #8049 is in.

**Comment by alanorozco** [comment]
PTAL

**Comment by honeybadgerdontcare** [comment]
@alanorozco This assert prevents the URL from being relative, correct? Currently the validation rules explicitly allow it to be relative and I'd like to remove that if the runtime won't allow it.

**Comment by alanorozco** [comment]
@honeybadgerdontcare Yes, thanks for catching that. Created #8086

**Pull request merged**
