### PR TITLE
🏗Test generated extension

### PR DESCRIPTION
**Pull request by alanorozco**
DO NOT SUBMIT

### CODE REVIEW

**Comment by rcebulko** [comment]
@alanorozco FYI if you make a Draft PR, or include "DO NOT SUBMIT" in the title, Owners Bot won't try to assign/notify people :)

**Comment by alanorozco** [comment]
Thanks @rcebulko! I was under the impression that Travis doesn't run on drafts.

**Comment by rcebulko** [comment]
> Thanks @rcebulko! I was under the impression that Travis doesn't run on drafts.

I _think_ it does, but I'm not certain. Any title matching `/(WIP|work in progress|DO NOT (MERGE|SUBMIT|REVIEW))/i` will not be auto-assigned reviewers by owners.

**Comment by rsimha** [comment]
> I was under the impression that Travis doesn't run on drafts.

Travis does build draft PRs: https://changelog.travis-ci.com/draft-pull-requests-support-105121

**Pull request closed without merging**
