### PR TITLE
✨ RTC vendors: add ConsentMetadata fields to Prebid Server

### PR DESCRIPTION
**Pull request by bretg**
Adds gdpr_applies, consent_type, and addtl_consent to Rubicon and AppNexus Prebid Server RTC strings as followup to https://github.com/ampproject/amphtml/issues/30006.

Am assuming we don't have to add CONSENT_METADATA to the `macros` field since it seems to behavior similarly to the ATTR macro. There's only one other example of this macro in the file though, so wanted to confirm.

Adding @syntaxnode as FYI for AppNexus.

### CODE REVIEW

**Comment by calebcordry** [comment]
Thanks for the update. to/ @micajuine-ho to double check the macros are correct.

**Review by micajuine-ho — APPROVED** [review]
Changes LGTM

**Comment by bretg** [comment]
not sure why this wasn't merged, bu fixed the conflicts that have arisen since April.

**Comment by bretg** [comment]
the tests timed out... please re-run?

**Comment by bretg** [comment]
@micajuine-ho - could you help drive this one home?

**Comment by calebcordry** [comment]
Sorry for the delay here, Mica has left the team. I just restarted the tests and will try to keep an eye on them.

**Comment by calebcordry** [comment]
Sorry an unrelated test keeps failing, could you sync to head one more time please? Feel free to ping me here as well

**Comment by bretg** [comment]
thanks @calebcordry

**Pull request merged**
