### PR TITLE
Ad type for Nokta Ad Server is added for amp-ad

### PR DESCRIPTION
**Pull request by ferrerodbgm**
Nokta Ad Server serves 100M ads per day. We are a big internet company at Turkey. This server is used by some high volume sites such izlesene.com, sinemalar.com, blogcu.com, alkislarlasiyorum.com, and some other sites that reach %70 of Turkey's internet traffic. 

We want to integrate our sites with AMP. For a quick and clean integration; we want Nokta Ad Server as a supported network for AMP ad component.

### CODE REVIEW

**Comment by ferrerodbgm** [comment]
I signed it!

**Comment by ferrerodbgm** [comment]
I signed it!

**Comment by merty** [comment]
I signed it!

**Comment by jridgewell** [comment]
@ferrerodbgm: are you having some troubles with the PR?

/to @lannka

**Comment by ferrerodbgm** [comment]
@lannka: We signed  Google CLA. But here it say we don't. ,We will send PR after solving this issue. My colleague opened another pull request; but it also didnt see the CLA. Do you have any suggestions?

**Comment by ferrerodbgm** [comment]
@jridgewell @lannka: We signed Google CLA. But here it say we don't. ,We will send PR after solving this issue. My colleague opened another pull request; but it also didnt see the CLA. Do you have any suggestions?

**Comment by erwinmombay** [comment]
was it a corporate CLA?

**Comment by jridgewell** [comment]
Moving this over to https://github.com/ampproject/amphtml/pull/5550.

**Comment by ferrerodbgm** [comment]
Yes, it was. The CLA belongs to Noktacom Medya İnternet Hizmetleri San. ve Tic. A.Ş..

**Pull request closed without merging**
