### PR TITLE
Use get a4a request width and height from parameters

### PR DESCRIPTION
**Pull request by bobcassels**
Use get a4a request width and height from parameters, rather than window size.

Border, margins, etc. can change window size, but should be ignored for request sizes.

### CODE REVIEW

**Comment by lannka** [comment]
would this work for responsive layout?

**Comment by lannka** [comment]
Seems a rebase is needed.

**Comment by lannka** [comment]
@bobcassels are you still on this?

**Comment by tdrl** [comment]
Bob has left the A4A team.  I suspect that this one will not get pushed as is, but it's closely related to work that @keithwrightbos and @glevitzky are doing.  Responsive is, as you say, a tricky problem.  We're _probably_ safe to close this one now.

**Pull request closed without merging**
