### PR TITLE
🐛 Update Scroll UI to reference new url

### PR DESCRIPTION
**Pull request by emmarm**
Update source url for Scroll scrollbar iframe to new endpoint

### CODE REVIEW

**Comment by emmarm** [comment]
@googlebot I signed it!

**Comment by kushal** [comment]
Test failure is unrelated, looks like. 
@dvoytenko this is a quick one-line change if you have a second!

**Comment by dvoytenko** [comment]
@emmarm Thanks! Would you mind rebasing? We're hitting some unrelated bad state in the repo.

**Comment by emmarm** [comment]
Hi @dvoytenko it's rebased and tests are passing, appreciate a bump on this!

**Comment by dvoytenko** [comment]
Thanks! Merged. This should be in tomorrow's canary.

**Pull request merged**
