### PR TITLE
make sure extension extern is included when compiling extensions

### PR DESCRIPTION
**Pull request by erwinmombay**
closure is renaming `this.layout_` into `this.F` then in carousel it is also renaming `AmpCarousel.prototype.withinLayout_` into `AmpCarousel.prototype.F`

### CODE REVIEW

**Comment by erwinmombay** [comment]
@cramforce PTAL

**Comment by cramforce** [comment]
Please update the PR title and description. I don't complete understand why this is being done.

**Comment by erwinmombay** [comment]
@cramforce Im not sure why we moved the declarations out of the original externs. right now closure is renaming `this.layout_` into `this.F` then in carousel it is also renaming `AmpCarousel.prototype.withinLayout_` into `this.F`

**Comment by erwinmombay** [comment]
the collision happens because `super()` is called and this is when in the base element from the v0.js binary it assigns the instance property with the same symbol as a function in amp carousel

**Comment by cramforce** [comment]
Oh, sorry. I was misreading the diff. So, this compiles? Can you put them back into one file then?

I was having trouble with referencing the superclass symbol (`@extends`) from within the extern.

Please give it a shot to just merge them again. Maybe I was chasing a red herring.

**Comment by erwinmombay** [comment]
honestly i'm not 100% sure if its working now because its just using a new symbol or it actually is trying to avoid collision because of the extern. The reason why I'm unsure is because the property declarations in extensions.extern are on `SomeBaseElementLikeClass` and not on `AMP.BaseElement`

**Comment by cramforce** [comment]
My (possibly broken) understanding is that all properties in externs are subject to non-obfuscation.

**Comment by erwinmombay** [comment]
@cramforce got it, if that's the case should be good then. I'll move the declarations over back into the main amp extern

**Comment by erwinmombay** [comment]
@cramforce PTAL

**Pull request merged**
