### PR TITLE
AMP-analytics: fix some params in Yandex.Metrika vendor

### PR DESCRIPTION
**Pull request by rifler**
Fixes https://github.com/ampproject/amphtml/issues/6050

### CODE REVIEW

**Comment by rifler** [comment]
CLA was signed in https://github.com/ampproject/amphtml/pull/4565

**Comment by aghassemi** [comment]
@avimehta Github does't allow me to merge without the CLA pass
@rifler Can you reply with `I signed it!` to see if it gets picked up?

**Comment by aghassemi** [comment]
@erwinmombay might be able to merge without the CLA check passing.

**Comment by rifler** [comment]
I signed it!

**Comment by jridgewell** [comment]
It's because you're authoring commits using an email that's not in Yandex's authorized Google Group.

**Comment by aghassemi** [comment]
@rifler See https://github.com/ampproject/amphtml/pull/6051#issuecomment-259225242 
Can you please get your email address added to that group or resubmit with an email that belongs to that group? Thanks!

**Comment by aghassemi** [comment]
@rifler Please see https://github.com/ampproject/amphtml/pull/6051#issuecomment-259226997. Thank you.

**Comment by rifler** [comment]
Sorry for waiting.

```It's because you're authoring commits using an email that's not in Yandex's authorized Google Group.```
Screenshot

**Comment by aghassemi** [comment]
@rifler The commits seem to be from `steve111@yandex.ru` however. That's probably why the CLA check is not passing.

**Comment by rifler** [comment]
@aghassemi You are right, sorry

**Comment by aghassemi** [comment]
@rifler Thanks, CLA is good now. I will merge your PR today.

**Pull request merged**
