### PR TITLE
✨ Added new ad network vlyby

### PR DESCRIPTION
**Pull request by damjan25**
✨Implements vlyby ad network

### CODE REVIEW

**Comment by powerivq** [comment]
Hi

Please fix the CLA issue. There are commits in this PR authored by non-CLA'ed person.

**Comment by damjan25** [comment]
@googlebot I fixed it.

**Comment by powerivq** [comment]
@damjan25 

It is not about you, but about `Martin Schwager` (as you can see in the commit list).

**Comment by vlybymschwage** [comment]
@googlebot I fixed it.

**Comment by powerivq** [comment]
I don't see an email on `Martin Schwager`'s commit. You will need to fix that commit in order for CLA test to pass.

**Comment by vlybymschwage** [comment]
@googlebot I fixed it.

**Comment by vlybymschwage** [comment]
@googlebot I consent.

**Comment by mschwage** [comment]
@googlebot I consent.

**Comment by MartinSchwager** [comment]
@googlebot I consent.

**Comment by damjan25** [comment]
@googlebot I consent.

**Comment by damjan25** [comment]
It keeps failing at this karma test. @powerivq Could this be caused by our code or is this general issue? Because I see few latest pull requests that have this error. It is a bit weird because earlier I did only linter change and all the tests passed
```
DESCRIBE => AmpViewerMessagingIntegration
  DESCRIBE =>  
    DESCRIBE => Handshake
      IT => should perform polling handshake
        ✗ Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

https://travis-ci.org/github/ampproject/amphtml/builds/726790200

**Review by powerivq — APPROVED** [review]

**Pull request merged**
