### PR TITLE
Clean up runtime code for launched exps

### PR DESCRIPTION
**Pull request by choumx**
Remove runtime checks for launched experiments:
- amp-live-list-sorting
- amp-playbuzz
- version-locking
- pump-early-frame

Remove experiments.js config for a bunch of launched experiments.

### CODE REVIEW

**Comment by choumx** [comment]
Looks like a bunch of tests need to be reworked.

**Comment by erwinmombay** [comment]
thanks for this

**Comment by nainar** [comment]
@choumx could you rebase and merge this in please?

**Pull request closed without merging**
