### PR TITLE
 🐛 load mraid.js from a url that won't normally resolve.

### PR DESCRIPTION
**Pull request by jeffkaufman**
In cases where there is no SDK to intercept the load for mraid.js we want the load to fail, as opposed to potentially opening us up to running arbitrary code.  Load from a URL that we will ensure 404s.

Replacement for #21737

### CODE REVIEW

**Comment by lannka** [comment]
> Platforms just check if the URL ends with /mraid.js 

Interesting API. I assumed you tested and it worked?

**Comment by lannka** [comment]
What about loading it from cdn.ampproject.org?. That way we can track the misuse of the MRAID.

**Comment by jeffkaufman** [comment]
> Interesting API. I assumed you tested and it worked?

I've tested it, and I've also confirmed that this is what the code in GMA SDK does.

> What about loading it from cdn.ampproject.org?. That way we can track the misuse of the MRAID.

Good idea.  Done in 459f9f8f5.  It should be about equally efficient in the non-mApp case: round trip to cdn.ampproject.org to get the 404 instead of a round trip to DNS.

**Comment by jeffkaufman** [comment]
@lannka I think this is ready to be merged

**Comment by jeffkaufman** [comment]
> https://cdn.ampproject.org is better to be imported from config.js

done in 4cecc8993

read for review @lannka

**Comment by lannka** [comment]
lint is failing. pls address

**Comment by anuragagarwal561994** [comment]
@lannka @jeffkaufman A question regarding this change as far as I understand this was done because mraid.js was calling the relative url of the `vendor.js` for fetching mraid.js when it was not available on SDK.

But what if the vendor adcode itself contains `<script src="mraid.js"></script>`

Then still the vendor will receive relative calls for `mraid.js`.

I am highlighting this because on our servers we are receiving `/mraid.js` calls, I checked further to realise that the adcodes that we are receiving contain mraid.js script tags.

Also what should be the right approach in this scenario, because at this relative endpoint we are right now serving mraid.js. Should we keep serving it or should we just send 404.

**Comment by jeffkaufman** [comment]
amp-mraid never launched, so I think you're probably in the wrong place?

**Comment by anuragagarwal561994** [comment]
Should I create another thread to discuss the same?

My doubt here is if the ad-code contains `<script src="mraid.js"></script>` how will it be treated?

Both in case there exists a MRAID sdk and not.

**Comment by jeffkaufman** [comment]
Is this related to AMP?

**Comment by anuragagarwal561994** [comment]
Yes, because I can see that the calls are coming for amp traffic only.

**Pull request merged**
