### PR TITLE
Testing @ampsauce

### PR DESCRIPTION
**Pull request by cramforce**

### CODE REVIEW

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by ampsauce** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 7175832e0db26afafb8520461595604e595bcdd8
Build details: https://travis-ci.org/ampsauce/amphtml/builds/85961683

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by ampsauce** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 0acbc6a3f613b26076b5f8ecdb747881371dfc6d
Build details: https://travis-ci.org/ampsauce/amphtml/builds/85963086

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by ampsauce** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: b1d333a80491f77096a1aecfc3c59bd466504b14
Build details: https://travis-ci.org/ampsauce/amphtml/builds/85987959

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by ampsauce** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: b1d333a80491f77096a1aecfc3c59bd466504b14
Build details: https://travis-ci.org/ampsauce/amphtml/builds/86118904

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by ampsauce** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: b1d333a80491f77096a1aecfc3c59bd466504b14
Build details: https://travis-ci.org/ampsauce/amphtml/builds/86120137

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by ampsauce** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: b1d333a80491f77096a1aecfc3c59bd466504b14
Build details: https://travis-ci.org/ampsauce/amphtml/builds/86120714

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Pull request closed without merging**
