### PR TITLE
🐛 Snowplow Extension: Patch Page Pings

### PR DESCRIPTION
**Pull request by colmsnowplow**
- Adds new method to track Page Pings as their own distinct context 
- Adds linker to harden persistence of AMP client ID across domains

### CODE REVIEW

**Comment by colmsnowplow** [comment]
@zhouyx - a patch the the Snowplow extension which you recently reviewed & merged! Is ready for review whenever's convenient for someone on your side! :)

**Comment by colmsnowplow** [comment]
Hi @micajuine-ho, I rebased to master just before creating the PR - there is a chance I did it wrong, here's what I did:

```
git checkout master
git fetch upstream
git rebase upstream/master
git push # just keeping my fork's master up to date here
git checkout snowplow/patch-page-pings
git rebase master
```

The only diff between my branch and master I can see are the changes I intentionally made. Would you mind taking a quick look and telling me if I should change something (perhaps `git merge master` should have been used rather than `git rebase master`)?

**Comment by colmsnowplow** [comment]
Oh - also I meant to ask, the old `.js` config files don't seem to do anything anymore so I didn't spend time updating it with these changes. Is this acceptable?

**Comment by micajuine-ho** [comment]
@colmsnowplow did you make changes to `vendor-requests.json`?

**Comment by colmsnowplow** [comment]
Sorry @micajuine-ho I mistyped above. 

Yes, I changed `vendor-requests.json` to update the snowplow_v2 tests.

The question I was asking was related to the fact that I didn't update the old `snowplow_v2.js` file - looks in the time since I began this work, those files have been removed anyway, so ignore the question. Apologies for confusion.

Let me know if I need to take any action regarding `vendor-requests.json`.

**Comment by micajuine-ho** [comment]
> Let me know if I need to take any action regarding vendor-requests.json.

Yeah, it looks like `vendor-requests.json` is out of sync with master. I understand you made changes to `snowplow_v2.json`, which could change `vendor-requests.json`, but after testing, it doesn't change it. So you can sync `vendor-requests.json` back to master and the tests will pass.  

As for how to sync, you can try `git merge master`, or just copy and paste from master :)

**Comment by zhouyx** [comment]
Hi @colmsnowplow since you're on it : ) Any update on applying `warningMessage` to snowplow v1, and its deprecation plan? Thanks!

**Comment by colmsnowplow** [comment]
Ah, @micajuine-ho, I follow now, I overlooked the [failing Travis build](https://travis-ci.org/ampproject/amphtml/jobs/658654024?utm_medium=notification&utm_source=github_status).

I've rebased and fixed it now. Looks the tests have all passed. 🎉 

@zhouyx - [my last pr had added this for the `.js` file](https://github.com/snowplow-incubator/amphtml/blob/090d05db95f66f705834889b17650e1c49444266/extensions/amp-analytics/0.1/vendors/snowplow.js#L48-L51), but looks like it didn't make it into the `.json` file for some reason (probably an oversight on my part!). I've added a commit to fix that, thanks for flagging! :)

**Pull request merged**
