### PR TITLE
🐛 Optimize Relap widget loading

### LINKED ISSUE #38474: amp-ad: Relap ad uses sub-optimal way of installation
### Description

Relap ad uses an older way of installing itself in `<amp-ad>` which causes it to load `https://relap.io/v7/relap.js` twice.

### Reproduction Steps

Go to a [demo page](https://codepen.io/advzr/pen/qBYyVJW) with a network tab in developer tools

### Relevant Logs

_No response_

### Browser(s) Affected

_No response_

### OS(s) Affected

_No response_

### Device(s) Affected

_No response_

### AMP Version Affected

_No response_

### PR DESCRIPTION
**Pull request by advzr**
🐛 Fixes #38474

Also fixed widget examples

### CODE REVIEW

**Review by MichaelRybak — COMMENTED** [review]
Approving validator changes in validator/testdata/feature_tests/*. Please wait for approvals for the rest of PR.

**Review by MichaelRybak — COMMENTED** [review]
Approving validator changes in validator/testdata/feature_tests/.*. Please wait for approvals for the rest of the PR.

**Review by powerivq — APPROVED** [review]

**Comment by erwinmombay** [comment]
you might want to rebase this and push the code to the PR again cause it seems circle CI got stuck

**Comment by powerivq** [comment]
Look like the validator error is real. Can you fix? @advzr

**Comment by advzr** [comment]
Fixed validation errors. Failing tests probably caused by the upstream code. I will wait for a new nightly build and rebase my code on it.

**Comment by powerivq** [comment]
Adding @erwinmombay for bundle size approval.

**Comment by advzr** [comment]
Ping. @erwinmombay will you approve bundle size and owners check?

**Review by erwinmombay — APPROVED** [review]

**Review by powerivq — APPROVED** [review]

**Review by antiphoton — APPROVED** [review]
Approving changes in `validator/testdata/feature_tests`

**Pull request merged**
