### PR TITLE
🐛Propagate the amp-video poster attribute on layout

### LINKED ISSUE #14257: [amp-video] media queries do not filter poster images
This is bad: poster images ignore the media attribute and are always downloaded. 

Example:
```
<amp-video layout="responsive" width=640 height=480 media="(max-width: 767px)" src="https://ampbyexample.com/video/tokyo.mp4?video=10" poster="https://unsplash.it/640/480?image=10"></amp-video>
<amp-video layout="responsive" width=640 height=480 media="(min-width: 768px)"  src="https://ampbyexample.com/video/tokyo.mp4?video=12" poster="https://unsplash.it/1024/768?image=11"></amp-video>
```

Expected behavior: 1 poster image and 1 video will be downloaded depending on screen width.
Actual behavior: 2 poster images and 1 video are downloaded depending on screen width.

Live sample:  https://jsbin.com/powatilomu/edit?html,output

Both poster images are downloaded:

screen shot 2018-03-27 at 10 55 10

//cc @aghassemi

### PR DESCRIPTION
**Pull request by cvializ**
Fixes #14257 

This should be all that's needed as long as there aren't any downsides to propagating this on layout.

/to @sebastianbenz @choumx 
/cc @aghassemi

### CODE REVIEW

**Comment by choumx** [comment]
Thanks for taking this on Carlos. Looks like we may need to propagate on build for prerender (see unit tests).

**Comment by cvializ** [comment]
Ah I see. I'll look at another angle, or see if this bug is expected behavior given the requirements.

**Comment by cvializ** [comment]
More investigation is needed.

**Comment by choumx** [comment]
@cvializ After some thought, I think this is actually ok. Just test it with on a page with videos using `#visibilityState=prerender`.

**Comment by aghassemi** [comment]
@choumx @cvializ @sebastianbenz `amp-video` is not pre-renderable in most cases (only cached videos in Stories are pre-renderable). That being said, we have already broken pre-rendering of `poster` image when `buildCallback` started using `isPrerenderAllowed` few months ago.

@choumx  To properly handle the case where `poster` is propagated during prerender but `video` is not, we would need to introduce a 2-stage prerendering mechanism where a component can optin to `build` but not `layout` during prerendering.

**Comment by mrjoro** [comment]
Is this PR still active?

**Comment by cvializ** [comment]
Let's close it and reopen if needed

**Pull request closed without merging**
