### PR TITLE
Fixed little typo in de-locale

### PR DESCRIPTION
**Pull request by Svenmay**
s/diese/dieses/

# Instructions:

- Pick a meaningful title for your pull request. (Use sentence case.)
  - Prefix the title with an emoji to identify what is being done. (Copy-paste the emoji itself (not the :code:) from the list below.)
  - Do not overuse punctuation in the title (like `(chore):`).
  - If it is helpful, use a simple prefix (like `ProjectX: Implement some feature`).
- Enter a succinct description that says why the PR is necessary, and what it does.
  - Mention the GitHub issue that is being addressed by the pull request.
  - The keywords `Fixes`, `Closes`, or `Resolves` followed the issue number will automatically close the issue.

# Example of a good description:

- Implement aspect X
- Leave out feature Y because of A
- Improve performance by B
- Improve accessibility by C

# Emojis for categorizing pull requests:

✨ New feature (`:sparkles:`)  
🐛 Bug fix (`:bug:`)  
🔥 P0 fix (`:fire:`)  
✅ Tests (`:white_check_mark:`)  
🚀 Performance improvements (`:rocket:`)  
🖍 CSS / Styling (`:crayon:`)  
♿ Accessibility (`:wheelchair:`)  
🌐 Internationalization (`:globe_with_meridians:`)  
📖 Documentation (`:book:`)  
🏗 Infrastructure / Tooling / Builds / CI (`:building_construction:`)  
⏪ Reverting a previous change (`:rewind:`)  
♻️ Refactoring (like moving around code w/o any changes) (`:recycle:`)  
🚮 Deleting code (`:put_litter_in_its_place:`)

### CODE REVIEW

**Comment by Svenmay** [comment]
Hmmm, the "continuous-integration/travis-ci/pr" failed with the following error message (see below).
Anything I can do to fix that?

https://travis-ci.org/ampproject/amphtml/jobs/443214028

DESCRIBE => AmpSubscriptions Dialog
  DESCRIBE =>  
    IT => should re-open content when visible
      ✗ AssertionError: expected 'matrix(1, 0, 0, 1, 0, 20.5621)' to not include '21'
          at /tmp/extensions/amp-subscriptions/0.1/test/test-dialog.js:92:39
HeadlessChrome 0.0.0 (Linux 0.0.0) AmpSubscriptions Dialog   should re-open content when visible FAILED
	AssertionError: expected 'matrix(1, 0, 0, 1, 0, 20.5621)' to not include '21'
	    at /tmp/extensions/amp-subscriptions/0.1/test/test-dialog.js:92:39
●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●○●●○○○○●●●●●●●●●●●●●●●●●●●●●●○●○○○●●●●●●●●●●●●●●●○●●●●●○●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
HeadlessChrome 0.0.0 (Linux 0.0.0): Executed 8125 of 8255 (1 FAILED) (skipped 130) (4 mins 51.341 secs / 2 mins 21.845 secs)
TOTAL: 1 FAILED, 8124 SUCCESS
TOTAL: 1 FAILED, 8124 SUCCESS
[14:46:30] Shutting down test responses server on localhost:31862
[14:46:30] ERROR: Karma test failed with exit code 1
[14:46:30] INFO: Uploading code coverage report to https://codecov.io/gh/ampproject/amphtml by running ./node_modules/.bin/codecov --file=test/coverage/lcov.info --flags=unit_tests...
[14:46:35] INFO: View report at: https://codecov.io/github/ampproject/amphtml/commit/1187e1de59bc156323cd798a40d1d370df52d7ea
[14:46:35] Finished 'test' after 11 min

**Comment by newmuis** [comment]
@Svenmay you can ignore this error; it's likely just a flaky test.  I can rerun the tests after the PR is approved.

**Comment by Svenmay** [comment]
Cool stuff!

Thanks Alex, thanks Jon

cheers,
  Sven

Mobile sent. Short answer because I hate long typing

Am Do., 18. Okt. 2018, 17:58 hat Jon Newmuis <notifications@github.com>
geschrieben:

**Comment by torch2424** [comment]
Restarted travis again, I think this time around, travis may have ran during the sauce labs outage.

Once it turns green I think this will be good to go 👍

**Pull request merged**
