### PR TITLE
♻️ Remove intro tables from extension files

### PR DESCRIPTION
**Pull request by robinvanopstal**
Remove intro tables from extension files to prevent duplication since they now will be generated dynamically (ampproject/amp.dev#3168) using data from @ampproject/amp-toolbox/validator-rules (ampproject/amp.dev#3344). 

Moreover, deprecated `[TOC]`s are removed and minor refactorings improve the `.md`s readability.

### CODE REVIEW

**Comment by sebastianbenz** [comment]
@robinvanopstal can you also please run prettier over the updated files.

**Comment by robinvanopstal** [comment]
@googlebot I consent.

**Comment by matthiasrohmer** [comment]
@sebastianbenz, do you have an idea why the check fails: https://travis-ci.org/ampproject/amphtml/jobs/654296625#L610-L614? I can't get the connection to the changes.

**Comment by twifkak** [comment]
@robinvanopstal Looks like you accidentally moved the amp-google-document-embed directory inside amp-gist? I think if you revert those changes, you'll no longer need wg-caching review.

**Comment by matthiasrohmer** [comment]
Thanks, @twifkak for looking into this! 🙂 This would then be good to go.

**Comment by matthiasrohmer** [comment]
@sebastianbenz, @CrystalOnScript who can merge this?

**Pull request merged**
