### PR TITLE
Fix z_index.md

### PR DESCRIPTION
**Pull request by caroqliu**
This PR is the result of running `amp get-zindex --fix` due to failures on `main`: https://app.circleci.com/pipelines/github/ampproject/amphtml/13207/workflows/3789638d-da1c-4f1f-a9a3-cdcbd0f4953b/jobs/212097

### CODE REVIEW

**Comment by samouri** [comment]
This change is much larger than I'd expect. Is it possible the dependency used to do the formatting has been updated?

**Review by samouri — APPROVED** [review]

**Comment by caroqliu** [comment]
Merging for now to unblock other PRs, but @alanorozco can you advise? Not sure how this file gets out of sync, and not seeing any recent package updates in our commit history.

**Comment by danielrozenberg** [comment]
@alanorozco and I discovered recently that `amp get-zindex` had a race-condition issue that only started manifesting when we [switched our CircleCI jobs from VMs to Docker containers](https://github.com/ampproject/amphtml/pull/35176) (which have less predictable CPU cycles, that can go up and down during the job execution)

Alan [fixed this task](https://github.com/ampproject/amphtml/pull/35291), so it's possible that the results _before_ were incorrect

**Comment by alanorozco** [comment]
What @danielrozenberg said seems like the most likely explanation.

> This change is much larger than I'd expect. Is it possible the dependency used to do the formatting has been updated?

The formatter did not change, but some entries were out of date. Markdown table columns are formatted to match the widest cell, so when that changes all rows are re-formatted.

**Pull request merged**
