### PR TITLE
📖 Adding Google Tag Manager doc links

### PR DESCRIPTION
**Pull request by philkrie**
More justification in issue 17435. 

Makes it easier for someone to discover GTM's integration with AMP. 

Completely open to edits, this is just to get a conversation rolling about what it might look like. Not sure if this is the right file even to put it in.

### CODE REVIEW

**Comment by jeffjose** [comment]
Since this is Analytics related, I can take this on from Vamsee.

**Comment by jeffjose** [comment]
Thanks for the changes, Philip. Unfortunately this isnt the right file. The file you edited is our documentation for 3P providers to integrate with AMP (think Adobe or comScore integrating with AMP) and not for end users trying to use amp-analytics.

The end-user documentation typically resides with the vendor. So for GA, it is [here](https://developers.google.com/analytics/devguides/collection/amp-analytics/), for Adobe it is [here](https://marketing.adobe.com/resources/help/en_US/sc/implement/accelerated-mobile-pages.html) and for GTM it is [here](https://developers.google.com/gtagjs/devguide/amp).

If GTM is what endusers are searching for, then it makes sense to change the doc at https://developers.google.com/gtagjs/devguide/amp.

**Comment by philkrie** [comment]
That makes sense.

Should it be implemented as a Note section? This page is the only page on amproject.org that mentions tag managers, which is why I felt it made sense to add some sort of guidance. 

Would it make more sense to add to the [analytics vendor page](https://www.ampproject.org/docs/analytics/analytics-vendors) instead? GTM is configured as an endpoint for amp-analytics, so it would make sense in that page. We have Google Analytics and Google AdWords listed (which btw should be changed to Google Ads). I think it would make sense to include Google Tag Manager.

**Comment by jeffjose** [comment]
Yup, [analytics vendor page](https://www.ampproject.org/docs/analytics/analytics-vendors) would be the right place.

Please feel free to open a PR for [this file](https://github.com/ampproject/docs/blob/cc5d3fdde3dc7597971b89e5f22d943de8ddad7d/content/docs/analytics/analytics-vendors.md) in amphtml/docs and we'll get this sorted.

**Comment by philkrie** [comment]
Sounds good, I will open a PR for that document.

**Pull request closed without merging**
