### PR TITLE
♻️ docs/bento-stream-gallery

### PR DESCRIPTION
**Pull request by kvchari**
Rename all stream-gallery-related Preact components to prefix `Bento`

update Readme.md in a separate PR

### CODE REVIEW

**Review by caroqliu — APPROVED** [review]

**Comment by kvchari** [comment]
@caroqliu do you know why this PR is failing the `license/cla` check? I've already signed it and the other PRs passed this check

**Comment by caroqliu** [comment]
> @caroqliu do you know why this PR is failing the `license/cla` check? I've already signed it and the other PRs passed this check

Not sure :/ maybe @ampproject/wg-infra could advise?

**Comment by danielrozenberg** [comment]
It looks like the CLA app is not reporting success or failure, @rsimha who owns this app?

**Comment by rsimha** [comment]
@kvchari Looks like this PR needs a fresh commit to bump the CLA bot. Could you rebase or push a blank commit and see if that works?

**Comment by kvchari** [comment]
@rsimha looks like that seems to have worked, thanks for the help

**Pull request merged**
