### PR TITLE
🚀 Use native CSS.escape in ESM build

### LINKED ISSUE #27394: Remove Polyfill for CSS.escape() in module build
## Describe the new feature or change to an existing feature you'd like to see

Remove Polyfill for CSS.escape() in module build, since it appears to be supported by module capable browsers.

### PR DESCRIPTION
**Pull request by kevinkimball**
Closes #27394

### CODE REVIEW

**Comment by kevinkimball** [comment]
63.11 kb -> 63.03 kb

**Comment by kristoferbaxter** [comment]
Approved Percy changes (Percy has been unreliable this week) and restarted unit tests (now passing).

**Comment by kristoferbaxter** [comment]
@choumx Can you look at `src/css.js`. Your approval is required.

**Comment by kristoferbaxter** [comment]
Restarted Travis tests due to outage.

**Pull request merged**
