### PR TITLE
✨amp-consent: Add Chandago's AppConsent to CMPs list (#25834)

### PR DESCRIPTION
**Pull request by dav-m85**
- Add a new configuration object to amp-consent component
- Provide an example and additionnal documentation for AppConsent

I2I opened issue [can be found here](https://github.com/ampproject/amphtml/issues/25834).

/cc @ampproject/wg-monetization

### CODE REVIEW

**Comment by dav-m85** [comment]
@googlebot I signed it!

**Comment by dav-m85** [comment]
Hi @zhouyx , don't hesitate if you have any question on this one :)

**Comment by zhouyx** [comment]
Hello @dav-m85. Thanks for integrating with AMP! 

I ran your example locally, but got the following error. Could you please take a look
image
Thanks. 

Also FYI we've recently changed our fullScreen API, and it's only supported with user interaction. please refer to #26197 for more information on that change. Thank you

**Comment by dav-m85** [comment]
@zhouyx fair enough, we were fixing server endpoints. It should be good now :)

I think we are already complying with the new fullscreen api, we call it only when the user interacts with the controls inside the iframe. Should be good, but don't hesitate to ping me if I'm wrong.

**Comment by zhouyx** [comment]
@dav-m85 thanks for the PR. Looks great, PR merged. The change should ship in pre-release next week, and in prod a week after that. more information on the release schedule https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md

**Comment by rcebulko** [comment]
Also, this PR should be automatically updating with labels "In Release: Experimental/Beta/Stable/LTS" as it makes it into various release builds.

**Comment by dav-m85** [comment]
Joly good! Thanks for this quick review and update 🥇

**Comment by zhouyx** [comment]
I am wondering why the `check-links` check didn't catch the dead link https://github.com/ampproject/amphtml/master/extensions/amp-consent/cmps/appconsent.md

cc @rsimha @estherkim idea? Thanks!

**Comment by estherkim** [comment]
@zhouyx Filed an issue to track. Thanks for reporting!

**Pull request merged**
