### PR TITLE
Heroku config

### PR DESCRIPTION
**Pull request by sriramkrish85**
Adding heroku confing to help make pushing to heroku easier

### CODE REVIEW

**Comment by erwinmombay** [comment]
this isnt going to work straight out of the box w/o `heroku config:set NPM_CONFIG_PRODUCTION=false`

also i think we should have a Procfile so that its obvious that this is the way to start it up on heroku.

i also tested "heroku-postbuild" and that works, the serving should be done on the procfile or through the "start" script.

```js
"scripts": {
   "heroku-postbuild": "gulp clean && gulp build --fortesting && gulp dist --fortesting"
}
```

and added a Procfile with:
`web: gulp serve`

**Comment by sriramkrish85** [comment]
>> this isnt going to work straight out of the box w/o heroku config:set NPM_CONFIG_PRODUCTION=false

Yes we could instruct this in the doc? 

i also tested "heroku-postbuild" and that works (will still need either a "start" script or a Procfile)
```
"scripts": {
   "heroku-postbuild": "gulp clean && gulp build --fortesting && gulp dist --fortesting"
}
```
We can sync up on this on monday and figure it out - it did not seem to work for me

**Comment by sriramkrish85** [comment]
PTAL

**Comment by erwinmombay** [comment]
LGTM

**Pull request merged**
