### PR TITLE
🚀 Update cmps.js for new consentmanager domain

### PR DESCRIPTION
**Pull request by janwinkler**
Updated consentmanager domain to delivery.consentmanager.net. consensu.org domain will soon be deprecated by the IAB and all CMPs must switch to new domains.

### CODE REVIEW

**Review by alanorozco — APPROVED** [review]

**Comment by alanorozco** [comment]
@janwinkler Thanks for the update. Could you please merge from `main`, and push?

**Comment by janwinkler** [comment]
Not 100% sure what you mean or what to do. Can you do it for me please?

**Comment by alanorozco** [comment]
I can't do it for you.

```
git pull upstream main
git push
```

**Comment by janwinkler** [comment]
@alanorozco was that correct now?

**Comment by mikebrickl-google** [comment]
@alanorozco can you please advise on how Jan should proceed?

**Comment by alanorozco** [comment]
Please try again, looks like something else is failing

**Comment by alanorozco** [comment]
Please try again, looks like something else is failing

**Comment by janwinkler** [comment]
second try :-)

**Comment by janwinkler** [comment]
@alanorozco Can you check?

**Comment by janwinkler** [comment]
@alanorozco @mikebrickl-google
Please note that the IAB is removing the old domain. We need to get the files updated on time. Can someone help please?

**Comment by erwinmombay** [comment]
@janwinkler we apologize for not responding timely here, as some folks had left the team and I didn't catch this open PR. Would y'all mind rebasing the Pull Request so i can merge it? I can also branch off this PR and do it myself if you would like me to.

**Comment by erwinmombay** [comment]
hello i branched off this Pull Request so i can rebase it and merge the changes quickly. The branch can be found at https://github.com/ampproject/amphtml/pull/38700

**Comment by erwinmombay** [comment]
Resolved through https://github.com/ampproject/amphtml/pull/38700

**Pull request closed without merging**
