### PR TITLE
Revert "Update to Index Exchange amp-ad adapter to no longer depend on window.context"

### PR DESCRIPTION
**Pull request by alanorozco**
Reverts ampproject/amphtml#10306

/cc @chrisdrexlerlemire-indexexchange

### CODE REVIEW

**Comment by jridgewell** [comment]
Why are we reverting?

**Comment by alanorozco** [comment]
@jridgewell On request of the ad network that made the change.

**Comment by cramforce** [comment]
The diff is fine, but the commit history looks weird.

**Comment by chrisdrexlerlemire-indexexchange** [comment]
Revert looks good to me.

**Pull request merged**
