### PR TITLE
🐛 Adapt dynatrace vendor parameter in amp-analytics to the new URL format #18739

### PR DESCRIPTION
**Pull request by kamtschatka**
Updated the URL parameter from referer to url
Fix for https://github.com/ampproject/amphtml/issues/18739

### CODE REVIEW

**Comment by kamtschatka** [comment]
cla/google is telling me "CLAs are signed, but unable to verify author consent". It also sent an email which shows that the CLA has been signed in March last year.

**Comment by aghassemi** [comment]
to @zhouyx

**Comment by kamtschatka** [comment]
CLA is still showing this:
cla/google — CLAs are signed, but unable to verify author consent

What should I do to fix this? When i go to the linked page https://cla.developers.google.com/, i can see my company agreement.

**Comment by kamtschatka** [comment]
CLA is still showing this:
cla/google — CLAs are signed, but unable to verify author consent

What should I do to fix this? When i go to the linked page https://cla.developers.google.com/, i can see my company agreement.

**Comment by kamtschatka** [comment]
CLA is still showing this:
cla/google — CLAs are signed, but unable to verify author consent

What should I do to fix this? When i go to the linked page https://cla.developers.google.com/, i can see my company agreement.

**Comment by zhouyx** [comment]
@kamtschatka Could you please let me know if the CLA is signed an individual or as a company?  And if it is a company can I know the company name? Thank you. 
I suspect the bot does not recognize your email address, Do you have another email associated with your github account?

**Comment by kamtschatka** [comment]
Hi
The company is called "Dynatrace LLC". I have checked, my github email address(=my company email address) is showing as member of this group.

**Comment by zhouyx** [comment]
Manually verified that the Dynatrace LLC is in the list.

**Comment by zhouyx** [comment]
@kamtschatka Thanks for the PR, merged.

**Pull request merged**
