### PR TITLE
❄️ [amp-date-picker] Skip flaky integration test

### PR DESCRIPTION
**Pull request by krdwan**
Part of: https://github.com/ampproject/amphtml/issues/31103

More info for flaky tests here

### CODE REVIEW

**Review by caroqliu — APPROVED** [review]

**Review by kristoferbaxter — APPROVED** [review]

**Comment by krdwan** [comment]
@rsimha - Hi Raghu, I'm trying to skip this flaky test, but repeatedly get a failure on Travis for ESM Tests.  The failure is a little cryptic to me.  Could you help me with this Travis failure or point me toward the right person?  I've tried rebasing to the latest master as well, but seems like the problem persists.  Thanks in advance!

Here's a link to the Travis failure.
https://travis-ci.com/github/ampproject/amphtml/jobs/434661405

**Comment by rsimha** [comment]
ESM code should've been built for integration-test-only changes, but wasn't. @erwinmombay can help you fix this.

**Comment by erwinmombay** [comment]
howdy @krdwan i should merge https://github.com/ampproject/amphtml/pull/31102 in a few minutes, once its in. just rebase/pull and re-push. apologies for the blocker!

**Comment by krdwan** [comment]
Thanks @erwinmombay and no trouble at all!!

Thanks @rsimha !!

**Comment by erwinmombay** [comment]
@krdwan merged https://github.com/ampproject/amphtml/pull/31102

**Comment by krdwan** [comment]
> @krdwan merged #31102

Thank you @erwinmombay !!

**Pull request merged**
