### PR TITLE
🐛 Lock chromedriver to 2.35 to avoid intermittent errors

### PR DESCRIPTION
**Pull request by timhaines**
Addresses https://github.com/ampproject/amphtml/issues/13700

`gulp visual-diff` uses capybara and selenium to drive Chrome to take DOM snapshots.  Recently this has been intermittently failing.

In my testing, I haven't been able to reproduce the error since locking chromedriver back to the previous 2.35 version.

### CODE REVIEW

**Comment by timhaines** [comment]
@rsimha Pushed the re-ordering change you were requesting.

**Comment by rsimha** [comment]
I'll merge this as soon as tests pass, after making sure the correct version shows up in the Travis logs.

**Comment by timhaines** [comment]
@rsimha All tests passed, and correct version showing in the build log:

image

**Comment by rsimha** [comment]
@timhaines, this PR did reduce the odds of the failure, but it's still happening. 

https://travis-ci.org/ampproject/amphtml/jobs/354998024#L657

**Pull request merged**
