### PR TITLE
✅ [bento][amp-social-share][fixit] Add e2e tests for social-share

### PR DESCRIPTION
**Pull request by krdwan**
Add e2e tests for amp-social-share

Related to: https://github.com/ampproject/amphtml/issues/25284

### CODE REVIEW

**Review by caroqliu — COMMENTED** [review]
Is it possible to add a test where the controller clicks the button? Or does the pop up mess things up in the testing environment?

**Comment by krdwan** [comment]
> Is it possible to add a test where the controller clicks the button? Or does the pop up mess things up in the testing environment?

It's definitely possible to click the button, but I haven't been able to find a way to test for the pop up since it opens up a new tab or browser.  Open to suggestions!

Just a side note, the clicking is tested in the unit tests so we do get coverage there.

**Review by caroqliu — APPROVED** [review]

**Comment by caroqliu** [comment]
@ampproject/wg-infra Would it be feasible to add support for popups in the e2e test environment? It is pretty important for this component and needed for #25284

**Comment by estherkim** [comment]
hiya, e2e already supports switching windows :) see [`getAllWindows`](https://github.com/ampproject/amphtml/blob/master/build-system/tasks/e2e/selenium-webdriver-controller.js#L455) and [`switchToWindow`](https://github.com/ampproject/amphtml/blob/master/build-system/tasks/e2e/selenium-webdriver-controller.js#L634)

**Comment by krdwan** [comment]
Thanks all @caroqliu @rcebulko @estherkim !

I've added in two more tests using `getAllWindows` and `switchToWindow`!!

**Review by caroqliu — APPROVED** [review]
This is awesome! I think we eventually want a click case for all pre-configured types, but feel free to spread that out across other PRs as you see fit.

**Review by dvoytenko — APPROVED** [review]

**Comment by krdwan** [comment]
> This is awesome! I think we eventually want a click case for all pre-configured types, but feel free to spread that out across other PRs as you see fit.

Thanks for the feedback, I will add this in follow up PR(s).  Tracking here for now: https://github.com/ampproject/amphtml/issues/28283

**Pull request merged**
