### PR TITLE
✨ Resize image if too big to make GPU texture

### LINKED ISSUE #29738: [Story 360] Scale down image if too large for device GPU
If the image is too large for the GPU to safely create a texture out of, an error is thrown:
Screen Shot 2020-08-07 at 10 32 57 AM

Max texture size can be be determined by calling `gl.getParameter(gl.MAX_TEXTURE_SIZE)`

This feature aims to give the best experience and support spanning low-end or old devices to the newest and most powerful.

cc @ampproject/wg-stories

### PR DESCRIPTION
**Pull request by processprocess**
Resizes image to the maximum dimension that the GPU can handle.

It does not preserve aspect ratio but that seems to be okay since the shader processes the pixels to simulate a consistent shape (a sphere).

Context / fixes #29738

Comparison of the two methods, simulating a low `MAX_TEXTURE_SIZE`.
H3vgZeB1nEk

Same image but with different aspect ratios:
JqzNi6MNVMY

### CODE REVIEW

**Comment by processprocess** [comment]
@t0mg What do you think about this approach?

**Comment by gmajoulet** [comment]
Deferring this one to @t0mg :))

**Comment by gmajoulet** [comment]
@ampproject/wg-stories for visibility

**Comment by t0mg** [comment]
> @t0mg What do you think about this approach?
> I put it in it's own PR so I can get any additional feedback :)

looks good to me, thanks for the ping :)

**Pull request merged**
