### PR TITLE
Run FIE init chunking experiment on prod

### PR DESCRIPTION
**Pull request by powerivq**
The canary numbers are looking fine (all neutral). We should push this to prod.

### CODE REVIEW

**Comment by powerivq** [comment]
I want to run on a larger traffic before release. Agree it probably makes no practical difference between 50% and 100%.

**Comment by zhouyx** [comment]
Do you want to turn it on instead? 
From what I can tell, the experiment will be divided to 50% 50% exp and control group even if you turn it on 100%.
Is there a need to set aside some traffic as control group aside from that.

**Comment by powerivq** [comment]
@zhouyx Actually I changed the percentage to 0.1 for now.

**Comment by zhouyx** [comment]
SG. LGTM

**Pull request merged**
