### PR TITLE
♻️ Refactor: Rename strip-prefix to xssi-prefix

### PR DESCRIPTION
**Pull request by samouri**
**summary**
Rename the `strip-prefix` attribute to the more specific `xssi-prefix` as suggested by @lannka.

### CODE REVIEW

**Comment by honeybadgerdontcare** [comment]
@lannka have these been verified to not be in use? otherwise we need an i2d.

**Comment by lannka** [comment]
@samouri correct me. seems like it's a new feature that is not launched / announced yet?

**Comment by samouri** [comment]
Poll! 
React with a 👍 if you like this name change and 👎  if you preferred `strip-prefix`

**Comment by lannka** [comment]
The reason I prefer `xssi-prefix` is that it explains itself. 
`strip-prefix` only explains its behavior, I felt it's too generic. That is not how we normally write a config.

**Comment by lannka** [comment]
To back up my argument, I give a real world analogy

If a frying pan is configurable, this will be a more readable config to regular users:
```
nonSticky: true
```

instead of

```
coatWithTeflon: true
```

**Comment by samouri** [comment]
@lannka: I tend to agree with you, as long as `xssi-prefix` would never have a different use

**Comment by samouri** [comment]
Yeah, lets do it this way. @jridgewell  / @lannka: if you have the chance can you submit this? I still don't have merge access.

**Comment by choumx** [comment]
I think either name is fine, but I actually read `nonSticky` as mapping to `stripPrefix` since they're less specific. :)

**Comment by lannka** [comment]
@choumx my bad try :-(

**Comment by samouri** [comment]
It might be more like a frying pan that was specifically meant for eggs, but could technically cook anything. Would you want your frying pan to have the function `cookFood` or `cookEggs`?

**Pull request merged**
