### PR TITLE
bug found!: remove carousel from builder map

### PR DESCRIPTION
**Pull request by samouri**
Bug found and will address in https://github.com/ampproject/amphtml/pull/37358

### CODE REVIEW

**Review by rcebulko — APPROVED** [review]

**Comment by samouri** [comment]
Jeez. There was no bug. In the manual test I had forgotten to add `i-amphtml-ssr` leading to buildDom being called twice 😬 . Overall good news!

**Comment by rcebulko** [comment]
So does this need to be reverted, and then CP'd now?

**Comment by samouri** [comment]
No, I think its ok to be slower with the roll forward until we have a little bit of testing in place. Specifically https://github.com/ampproject/amphtml/pull/37389

**Comment by rcebulko** [comment]
SGTM

**Pull request merged**
