### PR TITLE
Add Automatad to RTC Callout Vendors

### PR DESCRIPTION
**Pull request by kanchika**
This pull request adds Automatad to rtc callout vendors list

### CODE REVIEW

**Comment by kanchika** [comment]
@googlebot I signed it!

**Comment by lannka** [comment]
> It's possible we don't have your GitHub username or you're using a different email address on your commit. Check your existing CLA data and verify that your email is set on your git commits.

For the CLA bot issue, is this the case here?

**Comment by kanchika** [comment]
It seems the email was private. Made it public now. Will be triggering googlebot again

**Comment by kanchika** [comment]
@googlebot I signed it!

**Comment by kanchika** [comment]
@lannka cla issue is resolved

**Pull request merged**
