### PR TITLE
🐛Update loadPromise to this.baseInstance_.loadPromise

### PR DESCRIPTION
**Pull request by atl-love**
Update loadPromise to this.baseInstance_.loadPromise in the amp iframe handler.  Closes Issue #5294.

### CODE REVIEW

**Comment by zhouyx** [comment]
Thank you @atl-love LGTM. 
However you want to fix the linter error before I can merge the change. The line is exceeding 80 characters now.

**Comment by atl-love** [comment]
Thanks for letting me know. I'm trying to run gulp lint tests locally and get the following error:

```
Error: No registered module found called "eslint-plugin-amphtml-internal".
      at new MessageError (/usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:186:110)
      at Object.<anonymous> (/usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:87795:15)
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:98:30)
      at /usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:109:13
      at <anonymous>
```

My yarn version is 1.10 and i'm using 'lts'. Have any of you come across this issue when setting up gulp lint? Is this because I need to handle the private module differently?

**Comment by erwinmombay** [comment]
@rsimha any ideas on how to fix the issue?

**Comment by rsimha** [comment]
@atl-love, it's possible that your yarn version is incompatible with the custom eslint plugin. We recommend the latest stable version of yarn. Can you try updating yarn to see if the problem goes away?

**Comment by atl-love** [comment]
I found the issue…My other dev environment was conflicting with the amp env. I had to do two things: (1) I had an old version of yarn that was installed globally via npm (a while ago) and updated via brew, which caused conflicts, and (2) a number of eslint -dev dependencies had to be manually added.

**Comment by atl-love** [comment]
After fixing the issue, I get a failing test saying "if render-start is implemented...should not resolve on bootstrap load," which I see locally and as an error on Travis (above failed test)...i'll look into why.

**Comment by erwinmombay** [comment]
@atl-love looking!

**Comment by erwinmombay** [comment]
@atl-love looks like it was just flakey.  LGTM. merged!

**Pull request merged**
