### PR TITLE
Add endpoints to get public keys to verify Cloudflare signatures.

### PR DESCRIPTION
**Pull request by oliy**
Closes https://github.com/ampproject/amphtml/issues/6674

### CODE REVIEW

**Comment by oliy** [comment]
I've signed this already.

**Comment by oliy** [comment]
I signed it!

**Comment by dknecht** [comment]
@taymonbeal can you review?

**Comment by jasti** [comment]
@michaelkleber @cramforce for review as well.

**Comment by oliy** [comment]
I signed it!

**Comment by cramforce** [comment]
Happy to merge, but will let @ampproject/a4a team do the review.

**Pull request merged**
