### PR TITLE
Remove virtual viewport code

### LINKED ISSUE #3515: Resources Performance
I'm doing some profiling for iOS scrolling. On some frames, we spend around 5.3ms running the [`Resource doPass`](https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L1456-L1476).

25% of that time is [spent](https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L1472) (1.4ms) trying to determine if the [`Body#scrollHeight`](https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L320-L330) has changed. What's worse, on iOS, that won't even work!

Why are we doing this, and do we need to keep doing it? If we do, this needs to call [`Viewport#getScrollHeight`](https://github.com/ampproject/amphtml/blob/master/src/service/viewport-impl.js#L235-L242).

### PR DESCRIPTION
**Pull request by dvoytenko**
Closes #3515.

### CODE REVIEW

**Comment by jridgewell** [comment]
LGTM.

**Comment by cramforce** [comment]
AWESOME!

**Comment by ericfs** [comment]
Can the viewer stop setting the viewportType hash parameter?

**Comment by jridgewell** [comment]
> Can the viewer stop setting the viewportType hash parameter?

If so, we could simplify https://github.com/dvoytenko/amphtml/blob/adfb3f954b492d4aef2d73b1c7549182730e2339/src/service/viewer-impl.js#L200-L213.

**Comment by dvoytenko** [comment]
@ericfs @jridgewell : yes to both. The `viewer-impl.js` already assumes that `viewportType` not needed. Thus we can remove it from hash parameters in viewers right away. And we can also simplify the code that initializes the viewport.

**Pull request merged**
