### PR TITLE
[WIP] Output size as part of travis run.

### PR DESCRIPTION
**Pull request by cramforce**

### CODE REVIEW

**Comment by erwinmombay** [comment]
good idea

**Comment by erwinmombay** [comment]
we can probably have another task or script that checks for increase tolerance/threshold?

**Comment by cramforce** [comment]
There are some issues with such tests as they typically blame the 1000th of a 1000 cuts without that change being at fault. It would also require checking it in after every change.

I just felt this was kind of useful at basically zero extra cost since we build the output anyway. There is an issue with non-removal of test only code that might be a bit annoying.

**Comment by cramforce** [comment]
Can you check the travis output. Do you have an idea why gulp size doesn't appear to find all files?

**Comment by erwinmombay** [comment]
@cramforce yeah threshold probably is bad, but i was thinking more of tolerance of delta's. like in ad's case if it was 2x size increase probably something went wrong. would also just like it as a warning

**Comment by erwinmombay** [comment]
@cramforce on master? can you confirm the files are actually there?

**Comment by cramforce** [comment]
Is there a way to tell on travis? Why would only some files be there.

**Comment by erwinmombay** [comment]
@cramforce only think i can think of is race which is why we never chained gulp task dependencies like:

`gulp.task('size', ['build', 'dist']);`

because a`build` and `dist` never return promises/stream or call the task `done` callback correctly.

**Comment by cramforce** [comment]
Here it definitely runs after. Its own lie in travis config. Really weird.

**Comment by mrjoro** [comment]
Closing since this hasn't been updated in a while; reopen if needed.

**Pull request closed without merging**
