### PR TITLE
🐛  [Story autoanalytics] Use pageview to trigger story_page_count

### LINKED ISSUE #33784: Story auto analytics send a lot of story page count pings
While investigating #33783 I noticed that we send a `story_page_count` ping on every story page view. Is this the desired behavior?

It might be that this is intentional in case the story changes length? If so please close as WAI, if not switching to something like the `pageview` (note: not `story-page-view`) should fix.

Repro @ `examples/amp-story/auto-analytics.html` 

to/ @ampproject/wg-stories

### PR DESCRIPTION
**Pull request by mszylkowski**
Fixes #33784

We send a story_page_count ping on every story page view, but we should only send it once.

Live stories change the number of pages but:
1) This happens intentionally, and you can currently track see the pages viewed

### CODE REVIEW

**Comment by Enriqe** [comment]
Thanks! Just making sure: did you test it by checking the network tab and only seeing one ping for `storyPageCount` when navigating through the pages?

**Comment by mszylkowski** [comment]
It sent this request only once: `https://www.google-analytics.com/r/collect?v=1&_v=a1&ds=AMP&aip&_s=1&dt=My%20Story&sr=2560x1440&cid=amp-i04A-ja_J8MaJ2JAfZ3idw&tid=UA-174125188-1&dl=http%3A%2F%2Flocalhost%3A8000%2Fexamples%2Famp-story%2Fauto-analytics.html&dr=&sd=24&ul=en-us&de=UTF-8&t=pageview&jid=0.13074233740852503&gjid=0.6781689193424292&_r=1&a=6364&z=0.9204057936947161&gtm=2pu000`

**Review by calebcordry — CHANGES_REQUESTED** [review]
Sorry I think I was wrong about the trigger name here. I think it should be `visible`. I am a bit confused how the ping was working here, please double check.

**Comment by Enriqe** [comment]
Yep, I just tried and `story-page-visible` doesn't send a ping with a url containing the `story_page_count` (`event_action` in the config that belongs to the `storyPageCount` trigger.

Also verified that using `visible` actually triggers it one time.

**Comment by mszylkowski** [comment]
Agree with Enrique, updated. Thanks both for the insights

**Review by Enriqe — APPROVED** [review]

**Review by calebcordry — APPROVED** [review]

**Comment by Enriqe** [comment]
Btw @mszylkowski you should add an OWNERS file to the `amp-story-auto-analytics/*` extension folder (like [this one](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story-dev-tools/OWNERS)) so that we have owners approval.

**Comment by mszylkowski** [comment]
@Enriqe added OWNERS file

**Comment by mszylkowski** [comment]
@kristoferbaxter for owners approval

**Review by Enriqe — APPROVED** [review]

**Review by kristoferbaxter — APPROVED** [review]

**Pull request merged**
