### PR TITLE
#AJA re-PR

### PR DESCRIPTION
**Pull request by hideaki0817**
Add support for new `AJA` network.

### CODE REVIEW

**Comment by hideaki0817** [comment]
@calebcordry I look forward to ur merging. thank you.

**Comment by hideaki0817** [comment]
@calebcordry ?!

**Comment by calebcordry** [comment]
Hello, this pr still contains the `yarn.lock` file. I tried to remove it but was unsuccessful. I will try again when I get a bit of time to come back to this. If you are able to do it on your side that would be great.

**Comment by hideaki0817** [comment]
@calebcordry thank you. seems good so far;)

**Pull request merged**
