### PR TITLE
Rename a4a-v0.js to amp4ads-v0.js

### PR DESCRIPTION
**Pull request by lannka**
As suggested by @Gregable, this is to be consistent with the `<html amp4ads>` tag.

### CODE REVIEW

**Comment by erwinmombay** [comment]
can you also please rename https://github.com/ampproject/amphtml/blob/master/build-system/tasks/size.js#L108

**Comment by lannka** [comment]
@erwinmombay already did. unless you are thinking about something else.

**Comment by erwinmombay** [comment]
@lannka ah, apologies. didn't see it. LGTM

**Comment by lannka** [comment]
nope, thanks for your double check :-)

**Pull request merged**
