### PR TITLE
Upgrade dompurify to 1.0.9

### LINKED ISSUE #19977: amp-mustache: "alert(1)" popup on Opera Mini
## What's the issue?

When opening any AMP page in opera mini, you are confronted on page load with an alert - `javascript alert: 1`

img_1439
img_1438

## How do we reproduce the issue?

Go to any AMP page (I tried news publishers) in opera mini (opera mini proper, not opera turbo) and load any AMP page. The JS alert box seems to appear immediately and doesn't provide any context to the user. 

## What browsers are affected?

Tested on opera mini on iOS

### PR DESCRIPTION
**Pull request by choumx**
Fixes #19977.

### CODE REVIEW

**Comment by kristoferbaxter** [comment]
Looks like a few errors are showing up regarding purification in the test results. I'd hold off merging until they can be looked at.

**Comment by choumx** [comment]
Currently causes a bunch of tests to fail, e.g.:
```
● should output basic text
Chrome 71.0.3578 (Mac OS X 10.13.6)
TypeError: Cannot assign to read only property '22' of object '[object Array]'
  at addToSet (/var/folders/xy/zdjxmyvn1vjg75zhtgc5r28h006wch/T/7b8e652b7220f99299500c29de9f2677.browserify.js:10359:18)
  at _parseConfig (/var/folders/xy/zdjxmyvn1vjg75zhtgc5r28h006wch/T/7b8e652b7220f99299500c29de9f2677.browserify.js:10725:9)
  at Function.DOMPurify.sanitize (/var/folders/xy/zdjxmyvn1vjg75zhtgc5r28h006wch/T/7b8e652b7220f99299500c29de9f2677.browserify.js:11344:7)
  at purifyHtml (Users/willchou/amphtml/src/purifier.js:257:26)
  at purify (Users/willchou/amphtml/test/unit/test-purifier.js:31:16)
  at Context.<anonymous> (Users/willchou/amphtml/test/unit/test-purifier.js:168:14)
```

Looks like there's a dompurify bug in 1.0.9 related to `Object.freeze` on config files. I'll file it upstream.

**Comment by choumx** [comment]
Filed https://github.com/cure53/DOMPurify/issues/314.

**Comment by choumx** [comment]
Will need to wait for 1.0.10 for https://github.com/cure53/DOMPurify/pull/315.

**Comment by kul3r4** [comment]
@choumx It seems that has been merged, are we still blocked on this? @eagerterrier FYI

**Comment by choumx** [comment]
Merged but not yet released: https://github.com/cure53/DOMPurify/releases

**Comment by kul3r4** [comment]
Thanks! will keep an eye on that then.

**Comment by choumx** [comment]
Closing in favor of #20301.

**Pull request closed without merging**
