### PR TITLE
Remove listeners from <amp-facebook*> components when they aren't visible

### PR DESCRIPTION
**Pull request by nainar**
Part of #14761

### CODE REVIEW

**Comment by nainar** [comment]
Removed the later assignments as well.

**Comment by cvializ** [comment]
Shouldn't we be calling the method in `unlayoutCallback`, like amp-3q-player does, instead of deleting it?

https://github.com/ampproject/amphtml/blob/ab76625554673c84568d2267076ce3f09a435f5a/extensions/amp-3q-player/0.1/amp-3q-player.js#L110-L117

**Comment by nainar** [comment]
Hmm yeah, all other components follow the same pattern, what value does calling it add though? We are already listening for messages.

**Comment by cvializ** [comment]
`unlayoutCallback` is a hook so components can free up any expensive browser resources when they aren't visible. Listeners are one kind of resource that isn't needed when the component isn't visible. The iframe message callbacks here don't need to run if e.g. the user swipes to another document in the viewer, and calling `this.unlistenMessage_` will cleanup that listener.

https://github.com/ampproject/amphtml/blob/08c581fbe432398b3919b1129e25be8a7b064499/src/base-element.js#L503-L511

I think it is a case-by-case decision which resources to clean up though. If you decide that cleaning up this particular listener is unnecessary when the document is not visible, then feel free to disregard.

**Comment by nainar** [comment]
@cvializ,
Your suggestion definitely makes sense. Thanks for the explainer :) Made the changes and edited the title of the PR as well. PTAL?

**Pull request merged**
