### PR TITLE
Update Yandex ads script URL

### PR DESCRIPTION
**Pull request by smakhl**
Updating the URL to Yandex ads script

### CODE REVIEW

**Comment by smakhl** [comment]
/cc @mrjoro 
Hello Joye! Could you please advise who owns the Google Group in Yandex?

**Comment by calebcordry** [comment]
We will need the google CLA to be signed before we can merge this PR. Feel free to ping me once you have signed.

**Comment by smakhl** [comment]
@googlebot I signed it!

**Comment by smakhl** [comment]
@googlebot I fixed it.

**Comment by smakhl** [comment]
@calebcordry Hi! I have the signed the CLA now

**Pull request merged**
