### PR TITLE
Add an extensive integration test for DoubleClick ads.

### PR DESCRIPTION
**Pull request by cramforce**
Also provides some additional end-to-end coverage for the 3p embed system.

CC @kashyapnitin

### CODE REVIEW

**Comment by dvoytenko** [comment]
LGTM

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by erwinmombay** [comment]
tests and ads are in whitelist i think https://github.com/ampsauce/amphtml

**Comment by erwinmombay** [comment]
@cramforce tests and ads are in whitelist i think https://github.com/ampsauce/amphtml so ampsauce wont run

**Comment by cramforce** [comment]
@erwinmombay Yeah, it really should have build this. I'll investigate next week, need to update the whitelist anyway. Unfortunately I haven't been able to log the bots output to a file, because I don't know how to use computers.

**Pull request merged**
