### PR TITLE
✨ Change hostname of fluct, 3rd party advertiser

### PR DESCRIPTION
**Pull request by rail44**
A change because we have migrated hostname of ad delivering server into `sh.adingo.jp` .

* Change hostname from s.sh.adingo.jp to sh.adingo.jp

### CODE REVIEW

**Comment by rail44** [comment]
Sorry but I could not found reason that made test fail on travis 😩

**Comment by mrjoro** [comment]
Sorry this was missed!

/cc @ampproject/wg-ads @lannka

**Comment by calebcordry** [comment]
@rail44 sorry again for the very long delay, I tried restarting these tests but this PR was made so long ago they all bork. Could you please rebase or merge the latest master

**Comment by lannka** [comment]
Feel free to reopen if this PR is still needed.

**Pull request closed without merging**
