### PR TITLE
📖 Change the UK spelling of behaviour to US spelling of behavior

### PR DESCRIPTION
**Pull request by curseagain**
Change the UK spelling of "behaviour" to US spelling of "behavior"

Closes issue https://github.com/ampproject/amphtml/issues/18082

### CODE REVIEW

**Comment by curseagain** [comment]
@nainar this is ready for review, thanks!!

**Comment by alanorozco** [comment]
Already taken in #18306.

**Comment by curseagain** [comment]
@alanorozco it looks like that change affects a different file (extensions/amp-bind/0.1/bind-expr-impl.js)

**Comment by alanorozco** [comment]
My bad, thanks!

**Pull request merged**
