### PR TITLE
Set aside 10% of canary traffic for fie-init-chunking experiment

### PR DESCRIPTION
**Pull request by powerivq**

### CODE REVIEW

**Comment by choumx** [comment]
Good flag. Yea, the converse is true too. 

@ampproject/wg-ads FYI `intersect-resources` is currently enabled in canary, which is a very big change and probably conflating. What metrics are you planning on checking for `fie-init-chunking`?

**Comment by powerivq** [comment]
@jridgewell thanks for pointing that out.

@choumx We are mostly looking at Google Ad performance metrics. Look like `intersect-resources` is enabled for everyone on canary. What are you measuring on?

**Comment by choumx** [comment]
Yea same. :) I believe canary is served to .5% of traffic, so can you consider enabling this for .05% of prod instead?

**Pull request merged**
