### PR TITLE
Add documentation for `gulp test --testnames`

### PR DESCRIPTION
**Pull request by rsimha-amp**
#10482

### CODE REVIEW

**Comment by rsimha-amp** [comment]
Sample output of `gulp test --testnames`: https://gist.github.com/rsimha-amp/704ec6913f4ae76169edf821223170d3

Note that this is very verbose, but can help if you're searching the logs for a particular test name / failure cause. Also, it's not the default way we run tests :)

**Comment by rsimha-amp** [comment]
There is already a `--verbose` flag that prints every piece of debug spew possible, so I had to choose `--testnames`.

**Comment by lannka** [comment]
ah, that's fine

**Pull request merged**
