### PR TITLE
CSP changes for adding new font

### PR DESCRIPTION
**Pull request by camelburrito**
Add https://use.typekit.net https://p.typekit.net to AMP CSP

CC - @dknecht

### CODE REVIEW

**Comment by camelburrito** [comment]
@Gregable - We need a validator change for this please :)

**Comment by honeybadgerdontcare** [comment]
The validator change will come in a separate PR. Sending back to @camelburrito

**Comment by jridgewell** [comment]
Closes https://github.com/ampproject/amphtml/issues/2820? 🙌

**Comment by honeybadgerdontcare** [comment]
The validator change is now in production.

**Pull request merged**
