### PR TITLE
Updating path to Yahoo ad script 

### PR DESCRIPTION
**Pull request by src-code**
Minor change to the path for the script loaded by `yahoo` amp-ad plugin.

### CODE REVIEW

**Comment by src-code** [comment]
Looks like the test failures are Saucelabs timeouts in unrelated components.

**Comment by src-code** [comment]
Hi @keithwrightbos, is there anything needed from my end to get this resolved?

**Comment by src-code** [comment]
@lannka Any chance I can get your help with this one?  (You were the original approver for #5727 which introduced this amp-ad embed type long ago.)

**Comment by calebcordry** [comment]
Thanks for maintaining this extension!

**Comment by src-code** [comment]
Thank you @calebcordry!

**Pull request merged**
