### PR TITLE
Just for testing bot

### PR DESCRIPTION
**Pull request by cramforce**

### CODE REVIEW

**Comment by cramforce** [comment]
@amphtml-savage retry

**Comment by cramforce** [comment]
@amphtml-savage retry

**Comment by cramforce** [comment]
@amphtml-savage retry

**Comment by cramforce** [comment]
@amphtml-savage retry

**Comment by amphtml-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: fa6dd98f3c90e1d502fbc9b45e3dc1d1b84840f2
Build details: https://travis-ci.org/amphtml-savage/amphtml/builds/85872163

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by cramforce** [comment]
@ampsauce retry

**Comment by cramforce** [comment]
@ampsauce retry

**Pull request merged**
