### PR TITLE
🐛Fix call on undefined property forEach

### LINKED ISSUE #21098: amp-form not submitting in Edge 14
## What's the issue?
amp-form via xhr not submitting at least in Edge 14.

## How do we reproduce the issue?
Problem noticed on a private website, nevertheless it also exists on other amp-form powered websites, most prominently in the examples provided by the Project itself:
https://ampbyexample.com/components/amp-form/#form-submission-with-client-side-rendering

## What browsers are affected?
At least Edge 14, IE11.
Latest Chrome, Firefox, Opera  and Safari seems not affected

## Which AMP version is affected?
Version 1902151859190
Not quite sure, never realized it before, I'm guessing it's a new issue.

### PR DESCRIPTION
**Pull request by cvializ**
Fixes #21098

### CODE REVIEW

**Comment by cvializ** [comment]
np, I LGTMed it so double-oops haha

**Comment by aghassemi** [comment]
@cvializ @choumx I suggest patching current Canary that is about to go release with this, given it is both Edge and IE11 and form submission is big for ALP.

**Comment by cramforce** [comment]
Please file an issue to disallow the bad pattern via https://github.com/ampproject/amphtml/blob/master/build-system/conformance-config.textproto

**Comment by jridgewell** [comment]
> Please file an issue to disallow the bad pattern

Already done in https://github.com/ampproject/amphtml/issues/21234, although it's [impossible](https://github.com/ampproject/amphtml/issues/21254) due to our crappy type information.

**Pull request merged**
