### PR TITLE
Export per-user sauce credentials so they're visible to sauce connect

### LINKED ISSUE #10086: Per-committer Sauce Tokens
We might be able to alleviate the SauceLabs strain by using per-committer (at least per-core-committer) Sauce tokens.

When it's a PR build, based on who commits, we use their tokens to run integration tests. When it's a branch build, we can use the official tokens, etc.

### PR DESCRIPTION
**Pull request by rsimha-amp**
Earlier, we were extracting per-user creds from within a `node` process, and this was invisible to sauce connect. In this PR, we extract credentials and export them from within the parent shell in `.travis.yml`

Fixes #10086

### CODE REVIEW

**Comment by rsimha-amp** [comment]
Update: I've gotten to the point where I've successfully set the correct env vars for `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY_ENCRYPTED`. I'm trying to pass in `SAUCE_ACCESS_KEY_ENCRYPTED` to the JWT addon, but it's not picking up the value, even though debugging console logs suggest that the env vars are correctly being set before JWT initialization is supposed to take place.

I've filed https://github.com/travis-ci/travis-ci/issues/8007 in the Travis CI repository to get some help from the Travis folks.

**Comment by choumx** [comment]
Hack hack hack. 💻

**Comment by rsimha-amp** [comment]
Abandoning this approach, given the lack of support from Travis. See https://github.com/travis-ci/travis-ci/issues/8007#issuecomment-313196927

Rolling back partial changes in #10268

**Comment by rsimha-amp** [comment]
Reopening this PR to see if https://blog.travis-ci.com/2017-09-12-build-stages-order-and-conditions lets us do what we want.

**Comment by rsimha-amp** [comment]
Rebasing this PR is a lost cause given the number of commits. Continuing this in #11296, and leaving the commits in this PR for posterity.

**Pull request closed without merging**
