### PR TITLE
Layers: Support AMP elements inside an FIE

### PR DESCRIPTION
**Pull request by jridgewell**
Layers will now traverse friendly iframe boundaries to get the correct scrolled position of elements inside the FIE.

I've verified locally, too.

### CODE REVIEW

**Comment by jridgewell** [comment]
Tests added.

**Comment by dvoytenko** [comment]
LG on my side, but please also allow @lannka to complete the review.

**Comment by jridgewell** [comment]
Ping. I added tests (and fixed flaws those tests revealed 😃).

**Comment by lannka** [comment]
@zhouyx can you help take a look?

**Comment by jridgewell** [comment]
To make manual testing easier:

1. Build this branch
2. Go to `examples/fake-ad.amp.html`
  - I'd recommend editing it to add content before and after the ad, so you can scroll
3. Open dev tools
4. Toggle layers `AMP.toggleExperiment('layers', true);`
5. Refresh
6. Scroll around
7. `$0.__AMP_LAYOUT.getScrolledPosition()` on any AMP element inside the ad's FIE

**Pull request merged**
