### PR TITLE
allow dollar in amp pixel to be escaped

### PR DESCRIPTION
**Pull request by johnduffell**
potential fix for https://github.com/ampproject/amphtml/issues/832

### CODE REVIEW

**Comment by dvoytenko** [comment]
@ampsauce retry

**Comment by johnduffell** [comment]
I've merged in your changes @dvoytenko

**Comment by cramforce** [comment]
I think it would be better to make the $ optional. For me URL encoding is a strong signal that substitution is **not** intended.

**Comment by johnduffell** [comment]
@cramforce true that's why I was only saying potential fix - actually I just checked this minute and realised our code is doing the encoding of urls, so I will bypass that and the problem will go away.  However jettisoning the dollar sounds nice.

**Comment by johnduffell** [comment]
if we're going to make the dollar optional, can we get rid of it completely?

**Comment by dvoytenko** [comment]
I think at this point we will have to think about backward compatibility. So, let's make it optional but update documentation that it's not needed.

**Comment by johnduffell** [comment]
sure ok I'll update my branch

**Comment by cramforce** [comment]
+1

**Comment by johnduffell** [comment]
I've pushed an update but I'm not sure whether the test issues are something I've done - they pass locally though.  Can anyone help?

**Comment by erwinmombay** [comment]
@johnduffell looks like a flakey test, could you push again? we'll try and fix the test.

for reference: 
screen shot 2015-11-02 at 9 10 51 am

**Comment by johnduffell** [comment]
push what again @erwinmombay ?  I've tried respinning it from travis but nothing happens when I hit the spinning arrow symbol

**Comment by erwinmombay** [comment]
@johnduffell ive tried restarting it :+1: , hopefully its green this time around :D

**Comment by dvoytenko** [comment]
Similar problem I fixed earlier today. I will fix this one too, but it should pass even without fix. You're right - it's just flaky.

**Comment by dvoytenko** [comment]
Thanks! Looks great.

**Comment by johnduffell** [comment]
Thanks all, let me know when this is deployed so I can ship our changes.

**Comment by erwinmombay** [comment]
@johnduffell will do a new one here shortly. will ping you here when its out.

**Comment by erwinmombay** [comment]
@johnduffell new version is out https://cdn.ampproject.org/v0/version.txt

**Comment by johnduffell** [comment]
Thanks @erwinmombay !

**Comment by johnduffell** [comment]
hi guys, sorry for the delay reporting back but this is working fine. Thanks!

**Comment by erwinmombay** [comment]
no worries, thanks for confirming @johnduffell !

**Pull request merged**
