### PR TITLE
Allow custom var setting/reading

### PR DESCRIPTION
**Pull request by dvoytenko**

### CODE REVIEW

**Comment by dvoytenko** [comment]
Heads up: I'm expecting a fair amount of tests to fail - the tests that use "fake" element mocks. I will fix them all.

**Comment by dvoytenko** [comment]
So, tests worked as intended and I realized that `style[x] =y` and `style.setProperty(x, y)` are not equivalent in one important aspect. Style accessor accepts dashed and camel-case property names. I.e. both `style['background-color']` and `style['backgroundColor']` are ok. The `setProperty('backgroundColor')` however is not ok. In our code we by far prefer and use camel-case names. Thus this transition is harder to achieve.

**Comment by choumx** [comment]
Ah, good find.

**Comment by dvoytenko** [comment]
Unfortunately have to close this per the issue described above.

**Pull request closed without merging**
