### PR TITLE
add release for branches to build on push

### PR DESCRIPTION
**Pull request by erwinmombay**
ref https://github.com/ampproject/amphtml/pull/1611

### CODE REVIEW

**Comment by jeromemacias** [comment]
:+1:

**Comment by erwinmombay** [comment]
@jeromemacias you dont happen to know how to build a branch w/o needing this do you?

**Comment by erwinmombay** [comment]
looks like i can do it through the cli https://docs.travis-ci.com/user/triggering-builds/

**Comment by erwinmombay** [comment]
screen shot 2016-02-01 at 5 47 16 pm

adding release and canary shouldnt affect the number of builds on the PR as the PR branch is still excluded. I think this is still exactly what we want.

/cc @jeromemacias

**Pull request merged**
