### PR TITLE
Fixes inconsistencies in the indentation of help options

### PR DESCRIPTION
**Pull request by jaboc83**
2015-10-28 08_45_54-10 10 151 98 - remote desktop connection

### CODE REVIEW

**Comment by jmadler** [comment]
Good catch!

Is there anyway to, within the Gulp framework, prepend the spaces centrally?  A cursory review suggests not.

**Comment by erwinmombay** [comment]
we could wrap the already wrapped task lol

**Comment by jaboc83** [comment]
hmm, yeah wrapping the wrapper or possibly running a scan over the files as part of the `gulp presubmit` I suppose would be options.

**Comment by jmadler** [comment]
Let's not over-engineer -- create a ticket for it so it's tracked, and leave this PR as-is.  Make sure to reference this PR in that Issue.

LGTM.

**Comment by jmadler** [comment]
Assigning to Tech Lead for final review

**Comment by cramforce** [comment]
LGTM

**Pull request merged**
