### PR TITLE
📖 Fix formatting issues in extension docs and add missing front-matter

### PR DESCRIPTION
**Pull request by matthiasrohmer**
Fixes ampproject/docs#2113, ampproject/docs#2110.

/cc @sebastianbenz

### CODE REVIEW

**Comment by matthiasrohmer** [comment]
Did now, @sebastianbenz. `amp-inputmask` had been missing it as well. All others were surprisingly in good shape.

**Comment by sebastianbenz** [comment]
Thanks for checking! Can you please fix the broken link reported in the build checks.

**Comment by matthiasrohmer** [comment]
The link check in this repo more and more feels like Russian roulette 😅 https://en.wikipedia.org/wiki/Cross-site_request_forgery is marked as faulty by the check but there haven't been any recent changes to the site which could have been a reason for the link to be broken nor did I find any information about an incident with the Wikipedia infrastructure.

**Comment by sebastianbenz** [comment]
@rsimha have you got an idea why the link check is failing?

**Comment by rsimha** [comment]
I'm stumped by this one. The only reason I can think of that caused the wikipedia link to fail is Travis' VMs weren't able to reach them. I just re-ran the check. If it's a recurring problem, we can whitelist the link and move on. 

Our whitelisting logic is ancient and could do with a clean up, but for now, it lives here:
https://github.com/ampproject/amphtml/blob/c4a663d0ba13d0488c6fe73c55dc8c971ac6ec0d/build-system/tasks/check-links.js#L127-L169

**Comment by sebastianbenz** [comment]
@rsimha can you please approve and merge

**Pull request merged**
