### PR TITLE
handle preconnect that has no adConfig for type

### PR DESCRIPTION
**Pull request by erwinmombay**

### CODE REVIEW

**Comment by jridgewell** [comment]
Adding @lannka. I believe he made it so every ad has a configuration.

**Comment by lannka** [comment]
Hi Erwin, I intentionally made ad config a must have for all the ad networks. 
see #5084

The benefits:

- Force all ad network to take a look at the config file to see if they can take advantage of features like preconnect and render-start API.
- So we can print user error if publisher has mis-used an unknown `type` in `amp-ad`.
- Simplifies code a little bit (avoid null check in multiple places).

Sorry for the late reply btw.

**Comment by erwinmombay** [comment]
@lannka you have an explanation why the check is failing for the fake ad type @zhouyx had put in?

**Comment by zhouyx** [comment]
@erwinmombay I saw all checks passes. it's solved?

**Comment by lannka** [comment]
The earlier changes I made may expose some more user errors: user is using an ad type that we don't support. Was that the case?

**Comment by erwinmombay** [comment]
@lannka that possibly was the case, although i thought it was also the case for the fake ad type which i can't replicate now. I'll go ahead and close this unless i can replicate

**Pull request closed without merging**
