### PR TITLE
Fixes spelling of "strictly" in the amp-access and amp-subscriptions docs. 

### PR DESCRIPTION
**Pull request by dcmoore-gd**

### CODE REVIEW

**Comment by aghassemi** [comment]
Thanks and sorry for the delay in getting back to you. Could you please sign the CLA so we could merge it?

**Comment by mrjoro** [comment]
Hi @dcmoore-gd, thanks for helping clean up these typos.  Please [sign the Contributor License Agreement](https://cla.developers.google.com/) so we can merge this in.

**Comment by dcmoore-gd** [comment]
Working on getting appropriate approval for me to sign that now.  Thanks!

**Comment by mrjoro** [comment]
Hi @dcmoore-gd, were you able to make progress on the CLA?  I know it's a small change, but we need to make sure all code merged into amphtml is covered by a CLA.

Since the change is just a typo fix I'm happy to make this fix in a separate PR if you aren't able to get the CLA signed.

**Comment by mrjoro** [comment]
This is a trivial fix, I've gone ahead and made the change in PR #22363 instead.

**Pull request closed without merging**
