### PR TITLE
Owned resources may render to left or right of viewport

### LINKED ISSUE #5549: Carousel is not preloading next slide
Example https://www.google.com/amp/s/www.washingtonpost.com/amphtml/business/clinton-proposes-closing-real-estate-loophole-not-trump/2016/10/12/5698d66a-9052-11e6-bc00-1a9756d4111b_story.html

When advancing in the carousel in Chrome, loading the next slide does not happen until after the animation is complete.

It should 

- most likely preload +1 (and -1 in case of non-default start or loop) whenever the current slide is done or just do it right away
- at the very least start loading when initiating an advance

### PR DESCRIPTION
**Pull request by jridgewell**
This allows owned resources to render when outside the viewport on the
x-axis (only). This works because owned resources will never be
prerendered until the owner explicitly allows it. So, the owner knows
better than Resources does at this point.

Fixes #5549.

### CODE REVIEW

**Comment by jridgewell** [comment]
For reference, this was introduced in https://github.com/ampproject/amphtml/pull/4081. Working on tests.

**Comment by jridgewell** [comment]
> Also why should we get this far at all when an owner explicitly says prerender this child?

1. https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L550-L555
2. https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L1393-L1410
3. https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L1353-L1383
  - Notice https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L1369
4. https://github.com/ampproject/amphtml/blob/master/src/service/resource.js#L505-L563
  - Notice https://github.com/ampproject/amphtml/blob/master/src/service/resource.js#L526

> Carousel still needs to honor renderOutsideViewport value instead of just preloading +/- 1.

Carousel knows better than Resources does. Resources [intentionally skips](https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L1072) anything owned when doing it's [own preloading](https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L1069-L1082). So any of Carousel's slides won't be preloaded by Resources.

But Carousel only tries to preload the next (or previous) slide, so no issue with trusting the preload call when the are owned.

**Comment by aghassemi** [comment]
@jridgewell  The owner check can't just be on the horizontal case though. If a vertical element (e.g. say sidebar) takes ownership of its children and calls `schedulePreload` on an item that it not visible, it may still fail to preload if the `distance < viewportBox.height * multipler / scrollPenalty;` returns false.

**Comment by dvoytenko** [comment]
@aghassemi This is a temporary fix. We can't yet manage the composite elements properly.

**Comment by cramforce** [comment]
@zhouyx Could we merge this into canary?

**Comment by zhouyx** [comment]
👌

**Pull request merged**
