### PR TITLE
Add consentHandlingOverride flag to ezoic ampad

### PR DESCRIPTION
**Pull request by dynes**
Adding consentHandlingOverride flag so Ezoic amp-ad can handle consent itself.

### CODE REVIEW

**Comment by dynes** [comment]
The pull request is a one line change to the ads/_config.js file.  I don't see how this change could cause the build to fail.  Let me know if there's something I need to change if that is not the case.

**Comment by zhouyx** [comment]
@dynes Please add documentation, that you support customize consent behaviors, and describe the corresponding behaviors with different consent states.

**Comment by dynes** [comment]
Documentation added.

**Comment by dynes** [comment]
It's been 7 days since requested documentation has been added.  Is there something else that needs to be included?

**Comment by zhouyx** [comment]
@dynes The team is working on a documentation template to best document the consent blocking behaviors. Sorry for the delay, I'll merge this PR first.

**Pull request merged**
