### PR TITLE
amp-layout: extract buildDOM #compiler

### PR DESCRIPTION
**Pull request by samouri**
**summary**
Extracts `buildDOM` from `buildCallback` so that it can be called separate from the rest of init (for server render).

### CODE REVIEW

**Comment by samouri** [comment]
Blocked on https://github.com/ampproject/amphtml/pull/34681

**Comment by rcebulko** [comment]
> Blocked on #34681. Not because this is actually blocked...but just to save Ryan the hassle of dealing with merge conflicts on that jumbo PR

That PR is unblocked. Thank you for saving the headache 😃

**Review by rcebulko — APPROVED** [review]
It's cool that this is so straightforward now

**Comment by samouri** [comment]
@jridgewell for OWNERS approval

**Comment by samouri** [comment]
ping @jridgewell

**Comment by rcebulko** [comment]
@samouri isn't Justin OOO today?

**Review by jridgewell — APPROVED** [review]

**Pull request merged**
