### PR TITLE
amp-list: Attempt to resize to fit placeholder, if it exists

### PR DESCRIPTION
**Pull request by choumx**
Verified manually that this fixes `b/113880891`.

I'm wondering if this is a breaking change and needs to be guarded by yet another attribute. Can't think of any, WDYT?

### CODE REVIEW

**Comment by cathyxz** [comment]
Your implementation logic here is: if a placeholder exists, adjust the size of amp list upwards if necessary. 

<amp-list>'s default behavior is that it only increases the height and never decreases it. So we could have a case where the placeholder is larger than the list content and after loading, the amp-list height is too tall. I can think of UIs that this could break, but I'm not sure how severe or common that case is.

**Comment by aghassemi** [comment]
@choumx Should we put this under the same `resizable` attribute we have? I think we should recommend `resizable` to be used by everyone and any sizing related fix would go under that flag. (including this and allowing amp-resize to shrink as well). That would reduce the regression impact

**Comment by choumx** [comment]
Works for me. You didn't mean `auto-resize` that Cathy added right? 

Looks like amp-iframe is the only component that uses `resizable` today: https://www.ampproject.org/docs/reference/components/amp-iframe#iframe-resizing

**Comment by aghassemi** [comment]
@choumx sorry yes I meant `auto-resize` that Cathy did.

**Comment by cathyxz** [comment]
@choumx are you going to gate this under `auto-resize` per @aghassemi 's comment? Otherwise looks good.

**Comment by aghassemi** [comment]
@choumx LGTM , on a side note, this is how I'd expect `layout=container` for amp-list would work (by containing the placeholder item)

**Comment by choumx** [comment]
Thanks for the reviews!

**Pull request merged**
