### PR TITLE
AdGlare Ad Server: Added a cache buster to the URL.

### PR DESCRIPTION
**Pull request by adglare**

### CODE REVIEW

**Comment by adglare** [comment]
Hi @lannka and @calebcordry 

I've updated the URL to include a cache buster. Thanks for committing the change!

**Comment by adglare** [comment]
Also, could you please let me know how AdGlare can be added to this page?

https://amp.dev/support/faq/platform-and-vendor-partners/

Thanks again for your help - appreciated!

**Comment by calebcordry** [comment]
As far as adding adGlare to amp.dev -- you should be able to make a PR to this file https://github.com/ampproject/amp.dev/blob/da0fbee9d4387a10d72703665ff506e3e812150f/pages/shared/data/faq.yaml#L73

Feel free to ping me on the PR and I will add a maintainer of that site to review. 

Also it seems like a weird bundle-size flake on this PR. Could you rebase? That should reset the check. Thanks!

**Comment by adglare** [comment]
Hi @calebcordry 

I've changed a word to reset the checks. Hope the bundle size check will not timeout this time. I've also pinged you on https://github.com/ampproject/amp.dev/pull/3070 as indicated. Thanks for your time!

**Pull request merged**
