### PR TITLE
add opt_attrValue option to childElementByAttr

### PR DESCRIPTION
**Pull request by erwinmombay**

### CODE REVIEW

**Comment by erwinmombay** [comment]
@dvoytenko PTAL

**Comment by dvoytenko** [comment]
@erwinmombay Hmm. Where do we need this? Asking because we just removed it :)

**Comment by erwinmombay** [comment]
@dvoytenko actually dont need it anymore. where/when did we remove it?

**Comment by dvoytenko** [comment]
@cramforce removed it when supporting faster lookups via `:scope` query selectors. The reason is that you'd have to re-escape attribute values otherwise before injecting into `querySelector('[attr="value"]')`. Here, value has to be sanitized.

**Comment by cramforce** [comment]
If we need this, this can land. If we do it for real, we should implement escaping for values which would be easy.

**Comment by erwinmombay** [comment]
closing

**Pull request closed without merging**
