### PR TITLE
adds support for Eulerian Analytics

### PR DESCRIPTION
**Pull request by guillaumef**

### CODE REVIEW

**Comment by guillaumef** [comment]
I signed it!

**Comment by guillaumef** [comment]
Should I do something else here? quite disturbed by the "To be deprecated - 3P" 
Thanks

**Comment by avimehta** [comment]
@guillaumef This should go out in next or the the release after that. 

"To be deprecated - 3P" is actually indicating that the "3P" label is getting deprecated. Nothing to do with your PR.

**Pull request merged**
