### PR TITLE
Remove the inabox-rov check for renderOutsideViewport

### PR DESCRIPTION
**Pull request by zombifier**
The experiment inabox-rov has been enabled globally for all config. This small commit removes the flag check for renderOutsideViewport entirely.

### CODE REVIEW

**Comment by jeffkaufman** [comment]
@zombifier could you add a description to your pull request, explaining why we should make these changes?

**Comment by zombifier** [comment]
One of the tests within test/functional/test-custom-element.js is failing (usually "should apply heights condition", "should apply media condition", etc.), which is causing Travis to fail. This is the same on the master branch as well, so it has nothing to do with this commit.

**Comment by jeffkaufman** [comment]
@zombifier is this ready to go in?  Is the Travis failure fixed if you sync?

**Comment by zombifier** [comment]
still extremely flaky even on a clean master branch. reference on another PR: https://travis-ci.org/ampproject/amphtml/jobs/443461683

**Comment by jeffkaufman** [comment]
@zombifier on your branch is it 100% failing, or does it sometimes pass?

(Trying ti figure out whether your change makes it worse.  I don't see why it would, but it could)

**Comment by zombifier** [comment]
100% fails, but a different one every time (so individually speaking tests do pass occasionally). This is the case for a clean branch as well.

**Pull request merged**
