### PR TITLE
Changing ibeatAnalytics tracking API URL domain name chang

### PR DESCRIPTION
**Pull request by NitendraKumar**
There is a requirement to change the domain name from ibeats to ibeat. changed it in all files

### CODE REVIEW

**Comment by NitendraKumar** [comment]
Hi @jridgewell ,
Thank you so much for your quick reply on my issue.
As per your suggestion I have delete the old repository, forked new from master project and finally push my changes.
Your suggestion is really helpful.
Please review my changes.
Thank

**Comment by NitendraKumar** [comment]
I signed it! 
with mail id : nitinjnumca09@gmail.com

**Comment by NitendraKumar** [comment]
Hi @lannka @jridgewell ,

Please review the code change of Analytics API.
We are about to enable analytics tracking in AMP pages on our website and waiting for final URL integration.

Please Review and merge above change in master project.
Thanks

**Comment by jridgewell** [comment]
We have an issue with the CLA. Seems the commit was authored with nitendra.kumar@timesinternet.in, but that's not the email used in the CLA.

**Comment by NitendraKumar** [comment]
Hi @jridgewell ,
Thank you so much for review and approved my pull request.
I have logged in GITHUB using nitinjnumca09@gmail.com, created repository and committed the code using my gmail id.
I did not used nitendra.kumar@timesinternet.in any where in integration process.
After clicking on https://cla.developers.google.com/  CLA page says I am already sign the CLA.
Please have a look on attached image of my CLA agreement page. 
cla
Please guide to resolve the CLA issue.

**Comment by jridgewell** [comment]
> I did not used nitendra.kumar@timesinternet.in any where in integration process.

This is from Github's interface: 
screen shot 2017-04-26 at 1 48 23 pm


@erwinmombay: Can you force merge?

**Comment by NitendraKumar** [comment]
Hi @jridgewell @erwinmombay ,

Thanks for your guidance and support throughout the integration process of ibeatAnalytics.
You guys make this process really simple simple.

Thanks once again.

**Pull request merged**
