### PR TITLE
📖 Fix broken tables in components

### PR DESCRIPTION
**Pull request by dlemm**
Fixes ampproject/docs#1763 
Fixes ampproject/docs#2324  

- for #1763 there has been an unnecessary p-tag.
- for #2324 there has been a missing line

### CODE REVIEW

**Comment by torch2424** [comment]
@pbakaus Can I merge this? 😄

**Comment by pbakaus** [comment]
Yes!

**Comment by torch2424** [comment]
@pbakaus Thank you! Merged 😄 

Thanks for the contribution @dlemm ! 🎉

**Pull request merged**
