### PR TITLE
✨ amp-a4a: declare Future Plc as a new vendor

### PR DESCRIPTION
**Pull request by lgiraudel**
Purch has been acquired by Future Plc 2 years ago. We plan to slightly move from our legacy "purch" vendor to a new one "future".

### CODE REVIEW

**Comment by powerivq** [comment]
Hi @lgiraudel thanks for your contribution! Please see the above CLA bot message.

**Comment by lgiraudel** [comment]
Hello @powerivq 

I'm currently looking for my People Of Contact who signed the CLA but due to summer holidays I got some troubles to figure out who's this person is, in order to be approved as part of Future Plc org :D

**Comment by lgiraudel** [comment]
I signed it!

**Comment by lgiraudel** [comment]
Hello, do I need to do something more on my side?

Thanks :)

**Comment by powerivq** [comment]
Hi @lgiraudel 

Could you also update the documentation at 

 https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/rtc-documentation.md
 https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/rtc-publisher-implementation-guide.md

**Comment by lgiraudel** [comment]
Hello @powerivq 

I think I already did, except if I missed some parts to update in those two files.

Thanks

**Comment by powerivq** [comment]
@lgiraudel I was looking at "Supported Vendors" in https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/rtc-publisher-implementation-guide.md, you can add future plc into the list (or replace your existing one, that's your call)

**Comment by lgiraudel** [comment]
@powerivq it's part of my merge request: https://github.com/ampproject/amphtml/pull/29985/files#diff-c328b670346cff4cb088a7c156d202c1R29

**Review by powerivq — APPROVED** [review]

**Pull request merged**
