### PR TITLE
Refactor amp / bento classes

### PR DESCRIPTION
**Pull request by kvchari**
blocked by: https://github.com/ampproject/amphtml/pull/37156

### CODE REVIEW

**Comment by kvchari** [comment]
regarding the video elements: I'm refactoring the hierarchy like this:

// old hierarchy
bentovideo > pbe > ...
ampvideobase > bentovideo > ...
ampvideo > ampvideobase > ...
bentobrightcove > ampvideobase > ...
ampbrightcove > bentobrightcove > ...
**^^ bento-video/brightcove extends amp video stuff which isn't ideal**

// new hierarchy
bentovideo > pbe > ...
ampvideobase > pbe > ...
ampvideo > ampvideobase > ...
bentobrightcove > bentovideo > ...
ampbrightcove > ampvideobase > ...

bentovideo: is a shared base class for all bento video components. It is also the class for <bento-video>. (its name is staying BaseElement so that the autogenerated web-component.js still works, but can be imported as BentoVideoBaseElement)
ampvideobase: is a shared base class for all amp video components  (VideoBaseElement is changing to AmpVideoBaseElement)
bentovideo and ampvideo will share common video component utilities in extensions/amp-video/element.js

**Comment by kvchari** [comment]
splitting out prelim commits here: https://github.com/ampproject/amphtml/pull/37181

**Comment by samouri** [comment]
Is there any way to split this into smaller PRs?

**Comment by kvchari** [comment]
> Is there any way to split this into smaller PRs?

I can split this into 1 PR for each commit (I tried to make sure each commit was isolated and related to 1 extension). Would help to get PRs in 1 extension at a time. But would create ~26 PRs, so i opted against it. Would you like me to do that?

**Comment by kvchari** [comment]
closing in favor of: https://github.com/ampproject/amphtml/pull/37309

**Pull request closed without merging**
