### PR TITLE
Added a new variable called requestCount.

### LINKED ISSUE #1549: Expose a count of number of hits sent by amp-analytics tag.
a variable like this can be used to add sequence number to analytics hits.

### PR DESCRIPTION
**Pull request by avimehta**
Fixes #1549

### CODE REVIEW

**Comment by avimehta** [comment]
@dvoytenko This is ready for review...

**Comment by dvoytenko** [comment]
Looks good. Please rebase.

**Comment by avimehta** [comment]
done. Please merge.

**Comment by cramforce** [comment]
@dvoytenko just fixed that test failure. Merging.

**Pull request merged**
