### PR TITLE
✨ Add more query params to the Freestar rtc config.

### PR DESCRIPTION
**Pull request by vinnybod**
- Added additional parameters to the Freestar rtc config.

Note: Duplicate of https://github.com/ampproject/amphtml/pull/33713 which was closed due to the master->main change.

### CODE REVIEW

**Review by calebcordry — APPROVED** [review]

**Comment by calebcordry** [comment]
@rsimha do you think something weird happened to the tests here with the branch renaming? 

@vinnybod we can wait for Raghu to confirm, but you might want to try a rebase or merge or an additional commit. Let me know if you have any questions.

**Comment by rsimha** [comment]
> @rsimha do you think something weird happened to the tests here with the branch renaming?

Pretty sure this is an authentication problem due to which the CircleCI webhook wasn't triggered. @vinnybod Can you go to https://app.circleci.com/pipelines/github/ampproject/amphtml and make sure you are authenticated with your GitHub account? Once you do that, pushing an empty commit to this PR (or rebasing it) should trigger a build.

**Comment by vinnybod** [comment]
Pushed an empty commit, looks like the CircleCI Is building now. I hadn't authenticated before, I must have missed that in the PR docs.

**Comment by calebcordry** [comment]
Thanks for maintaining!

**Comment by rsimha** [comment]
> Pushed an empty commit, looks like the CircleCI Is building now. I hadn't authenticated before, I must have missed that in the PR docs.

Thanks for confirming. I'll take another look at our docs to make sure this is mentioned prominently.

**Comment by calebcordry** [comment]
Thanks @rsimha for always being so quick to investigate!

**Pull request merged**
