### PR TITLE
History migration to ampdoc

### PR DESCRIPTION
**Pull request by dvoytenko**

### CODE REVIEW

**Comment by aghassemi** [comment]
@dvoytenko LGTM on code, but does it make sense for history to be a doc service? This service's state is per window (it listens to window events like popstate and hashchange) and not scoped to a doc.

**Comment by dvoytenko** [comment]
@aghassemi Good point. This service kind of falls in-between. It's meaning is "history stack". And it's modeled as a per-doc history stack with parent history stack somehow managing possible conflicts. This is how currently iframe-based implementation works.

**Comment by dvoytenko** [comment]
@aghassemi @choumx Alright. I think I got a better approach to allow both: global scoping and per-document override. I will update this PR.

**Comment by dvoytenko** [comment]
@aghassemi This is ready to be re-reviewed. Basically I split history in two scopes: global and doc-level. We will continue maintaining history stack per document and we will continue to allow global history handler and doc-level override.

/cc @choumx

**Comment by aghassemi** [comment]
LGTM. If I understand this correctly, the VirtualBinding does not need to be a singleton since the viewer is really the global scope in that case?

**Comment by dvoytenko** [comment]
@aghassemi Correct. In this case the viewer is a gatekeeper for the global history stack, but it exposes is to each document as a per-document interface.

**Pull request merged**
