### PR TITLE
SSP-1224 - custom css support for capirs ads

### PR DESCRIPTION
**Pull request by CrazySquirrel**
Some of our sites want to be able to add additional styles for advertising amp blocks "capirs". So I added support for one more parameter.

### CODE REVIEW

**Comment by CrazySquirrel** [comment]
@jridgewell 
Hi.

I think that there are some problems with the validation. I already asked in slack, but without any particular result.

"Does anyone know why I get failed on ‘validator’ check here https://travis-ci.org/ampproject/amphtml/jobs/272894785 ?
I also try to run this check locally by ‘gulp validator’ but It doesn’t work either. It fails with an error ‘google.protobuf.descriptor not found. Try “apt-get install python-protobuf”‘.
I installed protobuf on mac with brew but it doesn’t get better."

If you look at console in my branch or in master on page http://localhost:8000/examples/ads.amp.html?type=capirs#development=1 you'll see some strange errors:

The attribute 'src' in tag 'amp-ad extension .js script' is set to the invalid value '/dist/v0/amp-ad-0.1.max.js'.
The attribute 'src' in tag 'amp-analytics extension .js script' is set to the invalid value '/dist/v0/amp-analytics-0.1.max.js'.
The attribute 'src' in tag 'amp-mustache extension .js script' is set to the invalid value '/dist/v0/amp-mustache-0.1.max.js'.
The attribute 'src' in tag 'amp-form extension .js script' is set to the invalid value '/dist/v0/amp-form-0.1.max.js'.
The tag 'script' is disallowed except in specific forms.
The mandatory tag 'amphtml engine v0.js script' is missing or incorrect.

Could you give me any clue what I can do with it?

**Comment by honeybadgerdontcare** [comment]
The first several errors are trying to inform the developer that they need to use the correct version of the script which are served from the AMP CDN. For instance `amp-ad` must be `<script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>` which is noted in the [documentation](https://www.ampproject.org/docs/reference/components/amp-ad).

The last error is stating the AMP Runtime script is missing: `<script async src="https://cdn.ampproject.org/v0.js"></script>`

**Comment by CrazySquirrel** [comment]
@honeybadgerdontcare 
I found why there are these errors. If you run gulp serve without parameters, it sets the build mode to default and all cdn.ampproject.org will be replaced by /dist/. If you run gulp serve --cdn --https everything will work fine.

And what do you think about an error in https://travis-ci.org/ampproject/amphtml/jobs/272894785 ? Does it related to this gulp serve mode problem or why it breaks inside this python validation?

**Comment by honeybadgerdontcare** [comment]
@CrazySquirrel  This is because there is indeed an error with this PR for validator but that error is being suppressed by Travis. To fix this you'll need to update feature_tests/ads.out to update that the amp-analytics error now appears on line 1334 instead of 1333.

I've submitted issue #11275 to deal with Travis.

**Comment by honeybadgerdontcare** [comment]
Validation issues are fixed. @jridgewell for triage of PR

**Pull request merged**
