### PR TITLE
VerizonMedia provider default publisher URL

### PR DESCRIPTION
**Pull request by radubarbos**

### CODE REVIEW

**Review by Samerrr22 — APPROVED** [review]
Hi--

**Review by calebcordry — APPROVED** [review]
Sorry for the delay, I think this one slipped through the cracks.

**Comment by calebcordry** [comment]
you might need to rebase to get all the checks to pass. Let me know if you have issues.

**Comment by radubarbos** [comment]
We'll add this change inside our js file that is loaded, this way we can add changes regarding this faster.

**Pull request closed without merging**
