### PR TITLE
📖 RTC Implementation Guide: Remove OpenWrap from PubMatic vendor entry

### PR DESCRIPTION
**Pull request by mike-chowla**

### CODE REVIEW

**Comment by mrjoro** [comment]
Hi @mike-chowla, sorry for the delay in reviewing this.

It looks like you aren't yet covered by a Contributor License Agreement.  Details are here:  https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#contributor-license-agreement

/cc @ampproject/wg-ads

**Comment by mrjoro** [comment]
@mike-chowla is this still a desired change?  Once you sign the CLA we should be able to get this in.

/cc @ampproject/wg-ads @lannka

**Comment by lannka** [comment]
also pls resolve the merge conflict

**Comment by lannka** [comment]
Feel free to reopen if this is still needed

**Pull request closed without merging**
