### PR TITLE
Fix inline code example

### PR DESCRIPTION
**Pull request by sebastianbenz**

### CODE REVIEW

**Review by caroqliu — APPROVED** [review]

**Comment by caroqliu** [comment]
pinging @ampproject/wg-infra any advice on hanging bundle size check? This PR was created from GH UI so I don't believe the rebase to master tip would make a difference here.

**Comment by sebastianbenz** [comment]
Closed in favor of https://github.com/ampproject/amphtml/pull/32285

**Comment by danielrozenberg** [comment]
lol 😅

I still think rebasing should've helped, why do you suspect it wouldn't have?

**Comment by rsimha** [comment]
Bundle-size failed because of this Travis VM blip. Normally, we'd expect @ampproject/build-cop to keep an eye on builds and restart them if needed. The good news is this should be much less of a problem once we actually stop using Travis.

image

**Comment by sebastianbenz** [comment]
I made the old mistake of thinking that a trivial change like this is OK to do via the Github UI...I (once again) was wrong. Rebasing is not possible via the Github UI (afaik).

**Comment by rsimha** [comment]
> I made the old mistake of thinking that a trivial change like this is OK to do via the Github UI...I (once again) was wrong. Rebasing is not possible via the Github UI (afaik).

I recognize the annoyance of not being able to rebase branches created from the Github UI. The good news is that once we move to CircleCI, we should automatically get the rebase behavior by simply re-running a CI build (without having to rebase the branch). Once the dust settle in the next couple weeks, feel free to ping me if you can think of other ways to make these workflows less onerous.

**Pull request closed without merging**
