### PR TITLE
🚀 Remove older performance info

### PR DESCRIPTION
**Pull request by kristoferbaxter**
There were several codepaths in `performance-impl` that supported behaviour for capturing data from Chromium user-agents older than version 77 (including for just 76).

Removing the older methods makes the implementation smaller, slightly more efficient, and easier to understand.

### CODE REVIEW

**Comment by samouri** [comment]
Code LGTM.

I don't have the context on why we had these special cases and why its okay to remove now, any chance you can either explain or point me to things to read?

**Comment by kristoferbaxter** [comment]
These branches handled older implementations in Chromium of the API solidified in Chromium 77.

Now that it's stable, and has been released for awhile we can stop collecting data on the older APIs.

**Comment by samouri** [comment]
Do we have stats on the % of users that are still on versions before 77, or is there some kind of heuristic/rule-of-thumb that is safe to use?

**Comment by kristoferbaxter** [comment]
https://amp.dev/support/faq/supported-browsers/

Chromium 76 just left the window for supported browsers, we support Chromium 78 and beyond as of today.

**Pull request merged**
