### PR TITLE
Remove internal only reference docs per issue #4965

### PR DESCRIPTION
**Pull request by bpaduch**
Removing .md files for "Internal only" APIs so they aren't included in the public reference docs on ampproject.org.

CC: @cramforce , @Meggin

### CODE REVIEW

**Comment by bpaduch** [comment]
Fixes #4965

**Comment by cramforce** [comment]
Could we instead label them as internal only but keep the files?

**Comment by bpaduch** [comment]
I'll look into that.  To clarify, when you mean "Internal Only", do you mean:

- keep  the md file and put some sort of **Internal Only** header/banner in the  file, 
- and still exclude it from being in the ampproject.org docs?

**Comment by cramforce** [comment]
The latter.

Just like eventually we'd want a label for "experimental" where it still goes into the docs, but hidden away under an "experimental" link

**Comment by bpaduch** [comment]
Appended "internal" to end of filenames so those files aren't pulled into the docset; tested it, and those files are excluded.  It's a workaround for now, 'til we figure out how to "label" docs and add capability to exclude/include based on the label.

**Pull request merged**
