### PR TITLE
wip: fix ios issue with sticky-ad

### PR DESCRIPTION
**Pull request by zhouyx**
#3599

### CODE REVIEW

**Comment by jridgewell** [comment]
Does it work? 😄

**Comment by zhouyx** [comment]
I thought it worked, it did work on an ios simulator, but not after I pushed to heroku and tested on iphone.  ; (

**Comment by jridgewell** [comment]
Either way, this is an improvement. Just doesn't fix #3599.

**Comment by zhouyx** [comment]
You are right, that's a nice catch ; )

**Pull request merged**
