### PR TITLE
Allows metadata string without quotes in tag.

### PR DESCRIPTION
**Pull request by glevitzky**
While in code freeze, this temporary solution allows us to parse the creative's metadata, which is erroneously being delimited with a string missing quotes.

### CODE REVIEW

**Comment by erwinmombay** [comment]
@dvoytenko sgtm

**Comment by tdrl** [comment]
Thanks for the quick work on this, @glevitzky and @taymonbeal .  It would be nice to have a couple of test cases, but otherwise LGTM.

**Comment by glevitzky** [comment]
Unit test added.

**Comment by erwinmombay** [comment]
please ping me when this is merged and ill do a new release

**Comment by glevitzky** [comment]
We're ready to have this merged whenever.

**Pull request merged**
