### PR TITLE
Update Mediavine script url

### PR DESCRIPTION
**Pull request by timtyrrell**
- Updates url to point to newer Mediavine assets

### CODE REVIEW

**Comment by timtyrrell** [comment]
Should be covered now: @googlebot I signed it!

**Comment by timtyrrell** [comment]
@googlebot The CLA has been signed.

**Comment by timtyrrell** [comment]
@googlebot please recheck! I signed it!

**Comment by timtyrrell** [comment]
@googlebot I signed it!

**Comment by erwinmombay** [comment]
@zhouyx @lannka please review

**Comment by lannka** [comment]
@timtyrrell Travis is not responding. Can you push an empty PR to re-trigger?

**Comment by timtyrrell** [comment]
@lannka I am pretty sure that I did as instructed, let me know if you have more guidance

**Comment by aghassemi** [comment]
@timtyrrell Could you please login to https://travis-ci.org/ with your GitHub account, sometimes PRs get flagged if author has never logged in to Travis.

**Comment by timtyrrell** [comment]
@aghassemi authenticated with travis-ci. Should I repush an empty commit to try to kick it off?

**Comment by aghassemi** [comment]
@timtyrrell still showing up as `abuse`, I will email Travis and report back here.

**Comment by timtyrrell** [comment]
@aghassemi thank you, I have no idea why all the checks are having trouble for this one

**Comment by timtyrrell** [comment]
@aghassemi Happy Monday! I would really love to get this resolved this week, is there anything I/we can do or is up to travis to not flag it as abuse? I can't even locate the PR here (https://travis-ci.org/ampproject/amphtml/pull_requests), do you have a link to it?

**Comment by aghassemi** [comment]
@timtyrrell , I pinged them again. It won't show up under pull requests since Travis does not create a job for it. They should up under: https://travis-ci.org/ampproject/amphtml/requests.

**Comment by timtyrrell** [comment]
@aghassemi I see it and thanks for pinging them again

**Comment by aghassemi** [comment]
@timtyrrell , this is the response I got back:

> I looked them up in our system and I think I can see why- their Github account hasn't been synced in a while. Most likely they last synced before the org the PR came from was created or they were granted access. If you have them log in and sync their Github account from their profile, I can go in and remove the abusive flag, and you'll be good to go from that point on!

**Comment by timtyrrell** [comment]
@aghassemi ok, I had to have a coworker sync, and I now see it in my org list. I believe the path is now cleared...

**Comment by aghassemi** [comment]
Thanks for your patience, should be good now.

**Comment by aghassemi** [comment]
@timtyrrell Merged.

**Pull request merged**
