### PR TITLE
Skip failing integration test

### PR DESCRIPTION
**Pull request by zhouyx**
Skip failing integration test from #11382. 
@rsimha-amp I don't understand. I added new integration test in #11382, travis should have already ran the integration test before merge, why would it only fail after been merged to master?

### CODE REVIEW

**Comment by rsimha-amp** [comment]
We run tests in compiled mode on master, but not on PRs. This is because of how much longer it takes to run `gulp dist`

**Comment by zhouyx** [comment]
Thanks @rsimha-amp. This explains why the test only fails on master. I am using `frame.max.html` and it doesn't exist when running test in compiled mode.

**Comment by rsimha-amp** [comment]
The `3p` tests still appear to be flaky on sauce labs. See https://github.com/ampproject/amphtml/pull/11469#issuecomment-333233166

**Comment by zhouyx** [comment]
hmmm. Seems like the old tests are failing as well.

**Pull request merged**
