### PR TITLE
Fix broken dist task in gulpfile

### PR DESCRIPTION
**Pull request by psyrendust**
* [f26d0eb] fix(gulpfile): fix broken dist task in gulpfile
* [3dd7aa3] chore(gulpfile): moved gulp tasks to bottom of file and alpha sorted
* [b65bed0] chore(gulpfile): update DEVELOPING.md so that it has all of the gulp tasks

### CODE REVIEW

**Comment by erwinmombay** [comment]
@cramforce you ok with renaming `minify` to `dist`?

**Comment by psyrendust** [comment]
FYI. I'm happy to change it all to minify if that's the decision.

**Comment by cramforce** [comment]
yeah, dist is a better name. Need to update our release script outside of this repo as well.

**Comment by erwinmombay** [comment]
thanks, LGTM.

i'd like to return the stream but i know a lot of our helper functions don't so `return compile()` here is moot.

I'll make the internal change. to reflect the change here.

**Comment by erwinmombay** [comment]
will merge when our internal release script is updated.

**Comment by erwinmombay** [comment]
@psyrendust can you rebase? will merge right after as we've made the update to our internal build system. sorry for the long wait!

**Comment by psyrendust** [comment]
@erwinmombay rebase complete.

**Comment by erwinmombay** [comment]
@psyrendust mind repushing, flakey test =/

**Comment by psyrendust** [comment]
@erwinmombay made a minor change and pushed again (3dd7aa3)

**Comment by erwinmombay** [comment]
@psyrendust merged. thanks for the patience!

**Pull request merged**
