### PR TITLE
Small fixes: Removed unnecessary Promise.resolve()s

### PR DESCRIPTION
**Pull request by tdrl**

### CODE REVIEW

**Comment by jridgewell** [comment]
LGTM.

**Comment by jridgewell** [comment]
@tdrl: You'll probably need to rebase off latest master to get Travis to report.

**Comment by tdrl** [comment]
@jridgewell I rebased off master and pushed, but now it seems to think that every commit from master is a new change on this branch.  Clearly, I have something messed up in my git process.  :-P  Does this break this PR or will it be okay once it merges?

**Comment by jridgewell** [comment]
Did another rebase, just waiting for Travis to report.

**Pull request merged**
