### PR TITLE
🐛 Snowplow extension 1.0.2

### PR DESCRIPTION
**Pull request by colmsnowplow**
Minor changes to the Snowplow Analytics amp-analytics extension.

Changes:

Fix bug where duid is not sent from pages on the AMP CDN
This was because we attempted to set a cookie and then retrieve the value from that cookie.

Fixed by prioritising the value from the querystring ahead of the cookie.

Rename _sp_id cookie
This was a poor naming choice as it's the same cookie name that a separate tracker uses, but a different ID. Very small chance of a conflict.

We avoid changing all AMP ID values, setting the new cookie to the value of the (old) _sp_id cookie when it's not found elsehwere. We can remove this part in a subsequent release to simplify things.

Rename 'linker' to 'sp_amp_linker'
Another poor naming choice - using the default opens the door for conflicts. Ripping off the plaster now while we're at it.

Rename aaVersion to trackerVersion
Just a nitpick.

### CODE REVIEW

**Review by micajuine-ho — COMMENTED** [review]
@colmsnowplow Please rebase--we recently switched to circleCI, so we need a rebase to ensure that the CircleCI config matches master for comparison tests.

**Comment by colmsnowplow** [comment]
Done - apologies, should've done it before creating the PR. :)

**Comment by colmsnowplow** [comment]
Just noticed I need to fix unit tests also - on it.

**Comment by colmsnowplow** [comment]
@micajuine-ho I believe I've addressed everything now - the visual diff test is still failing but I don't think it's down to anything I've done here. Please do let me know if I've missed anything. :)

**Comment by colmsnowplow** [comment]
👋  Hey @micajuine-ho - I don't mean to pester, just want to check before I communicate to stakeholders.

Do you think this can get reviewed in time for next week's beta release cycle?

**Review by micajuine-ho — APPROVED** [review]

**Pull request merged**
