### PR TITLE
✨Add Consent State Macro into Comscore's Vendor Script

### PR DESCRIPTION
**Pull request by wroberts-comscore**
# Description

- Adding the consentState Macro into Comscore's UDM Tag as 'cs_amp_consent' 
- Comscore Jira ticket: [TAG-4790]
- Note: Cannot find Comscore's CLA agreement. Sent two emails to cla-submissions@google.com and have not received a response. Please advise

### CODE REVIEW

**Comment by torch2424** [comment]
@wroberts-comscore 

Hello! So it seems you have not signed the CLA. Is this still an issue on your end, and want this merged?

If so, please follow the instructions given by the bot 😄 Unless you have a corporate CLA, which we can then try to figure out another way.

Triaging to @zhouyx , since you would be most familiar with this existing config 😄

**Comment by wroberts-comscore** [comment]
@torch2424 I've been in contact with taymonbeal from the AMP slack channel, he's been assisting us in getting the CLA figured out (We needed a new one as all the previous points of contact have left Comscore). 

Someone from Comscore's side will then be reviewing the previous CLA for comparing the terms and then they should be able to sign the new one. I am hopeful that will happen this week and we can move this PR along the chain. 

Please let me know if you need any further information.

**Comment by zhouyx** [comment]
Hello @wroberts-comscore. Thank you for submitting the change. There is one thing that I'd like to confirm with you. The request ping will wait for the consent_state to resolve when there's `<amp-consent>` element placed on the page, which means it's possible that the pageview never get sent. Is that something you're aware of and expect? Thank you

**Comment by wroberts-comscore** [comment]
Hi @zhouyx ... is there a way to send the pageview regardless of whether or not the {consentState} macro is resolved? I've attempted a couple of small things locally, (setting the macro into a separate variable, a few other triggers to send the pageview) but they all behave in the way you described above. 

If there is a way to send the pageview ping even if it is not resolved, or if you had any other suggestions, please let me know. Otherwise, I have informed my team and we're reviewing with a product manager. 

Thanks for taking the time to review!

**Comment by zhouyx** [comment]
Thanks for clarifying. 
Currently we only support blocking `CONSENT_STATE`. Instead of including the value to the pageview request, could you create a new request and then combine them on server end?

**Comment by wroberts-comscore** [comment]
@zhouyx so I signed the CLA.. can you confirm on your side? 

thanks.

**Comment by wroberts-comscore** [comment]
@zhouyx @googlebot we haved signed the CLA. Anything further needed on my side?

**Comment by zhouyx** [comment]
Hello @wroberts-comscore Looks like the @googlebot didn't pick up the CLA. Could you please let me know if you sign it as a company or as individual. And could you please also double check that the email you are using to commit match the email that you used to sign the CLA? Thank you very much.

**Comment by zhouyx** [comment]
Ha! CLA is all good now!

**Comment by zhouyx** [comment]
Let me know your decision on having the request blocked by consent state. And we can proceed with this PR. Thank you!

**Comment by wroberts-comscore** [comment]
@zhouyx We should be good to go. We are fine with the consent state blocking the request at this time. Thanks.

**Comment by wroberts-comscore** [comment]
@zhouyx Hey, wondering if there is an update here? Is there anything else required from my side?

**Comment by zhouyx** [comment]
Sorry about the delay here. The change looks goo to me. Could you please fix the unit test so that I can merge the PR. Thank you!

**Comment by wroberts-comscore** [comment]
Adding the new label into the vendor-requests.json file to fix unit tests

**Comment by zhouyx** [comment]
Thank you @wroberts-comscore , all test passed. PR merged.

**Pull request merged**
