### PR TITLE
✨ Added Admax to RTC callout-vendors for amp-ad

### PR DESCRIPTION
**Pull request by matganine**
Added Admax to the list of RTC callout-vendors in order to be able to add Admax in the rtc-config attribute of amp-ad tags.

### CODE REVIEW

**Comment by calebcordry** [comment]
@matganine could you please sign our CLA linked by the bot above? Thanks!

**Comment by matganine** [comment]
@calebcordry yes I have signed it :)

**Comment by calebcordry** [comment]
Hmm it seems the CLA bot still doesn't think you have signed? Let me know if you have issues. Also looks like you will need to rebase/merge now due to changes in the file.

**Review by calebcordry — APPROVED** [review]

**Comment by calebcordry** [comment]
Thanks for contributing!

**Pull request merged**
