### PR TITLE
Support new tag type for fluct SSP

### PR DESCRIPTION
**Pull request by saxsir**
We support new type of ad deliver tag and would like to add `amp-ad`.

This is non breaking changes.

Previous tag

```
  <amp-ad width="300" height="250"
      type="fluct"
      data-g="1000067784"
      data-u="1000101409">
  </amp-ad>
```

New tag

To use new ad tag,  `data-tagtype` have to be set `api`.

```
  <amp-ad width="300" height="250"
          type="fluct"
          data-g="1000128429"
          data-u="1000220560"
          data-tagtype="api">
  </amp-ad>
```

And also it had changed hostname of fluct, We would like to merge changes of the PR below.

refs. https://github.com/ampproject/amphtml/pull/26035

### CODE REVIEW

**Comment by saxsir** [comment]
@lannka Could you look at this ?

**Review by lannka — APPROVED** [review]

**Comment by saxsir** [comment]
@lannka Thank you for reviewing. 

But CI is still pending. Should we fix something? or could you tell us how to re-run circle-ci check

**Comment by lannka** [comment]
I also had trouble to restart the CI. Could you try to rebase?

**Comment by saxsir** [comment]
rebased but CI is still pending. We'll try to open new pull request.(same as this PR's diffs

**Comment by powerivq** [comment]
```
ads/_config.js
  517:16  error  Replace `⏎······'https://pdn.adingo.jp/p.js',⏎····` with `'https://pdn.adingo.jp/p.js'`  prettier/prettier

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

[02:16:34] 
ads/vendors/fluct.js
  17:36  error  Member 'loadScript' of the import declaration should be sorted alphabetically                    sort-imports-es6-autofix/sort-imports-es6
  34:24  error  Replace `"https://pdn.adingo.jp/p.js",·function` with `'https://pdn.adingo.jp/p.js',·function·`  prettier/prettier
  35:7   error  'fluctAdScript' is not defined                                                                   no-undef

✖ 3 problems (3 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.

[02:22:53] ERROR: Found 4 error(s) and 0 warning(s).
```

**Comment by saxsir** [comment]
Fixed lint errors and rebased.

**Comment by saxsir** [comment]
@powerivq @lannka CI has passed, thank you for a lot.

**Pull request merged**
