### PR TITLE
Keep same macro for A4A and inabox

### PR DESCRIPTION
**Pull request by zhouyx**
As agreed, it doesn't make sense to have special macro for A4a, because they cannot be reused for inabox ad. 

The solution is to override the existing macro resolver function. 

@lannka I didn't find a good testing solution. But I think this is a safe enough change. Let me know if you have any objection.

### CODE REVIEW

**Comment by jonkeller** [comment]
Would it be possible to let both sets of names (e.g. AD_NAV_TIMING and NAV_TIMING) exist together for a short time (~2 weeks)? This would help to get the creatives changed without breakage. Thanks!

**Comment by zhouyx** [comment]
@jonkeller I can put AD_NAV_TIMING back for sure, but I thought AD_NAV_TIMING is not used by any creative today?

**Comment by lannka** [comment]
I guess what @jonkeller meant in a time sequence:
- AMP supports AD_
- ad server puts AD_
- AMP supports both
- ad server change to non-AD_
- AMP removes support for AD_

In that way ad server change can go in without depending on this PR to land.

**Comment by jonkeller** [comment]
Right.
And, I meant no *external* parties use NAV_. But we do internally, since
very recently.

**Comment by zhouyx** [comment]
Ah I see. Let me change it back then.

**Comment by jonkeller** [comment]
Thanks!

**Comment by zhouyx** [comment]
added `AD_NAV_TIMING` back. I didn't change the integration test though given it's going to be removed pretty soon.

**Pull request merged**
