### PR TITLE
add support for piano analytics

### PR DESCRIPTION
**Pull request by nathangoulding**
Initial support for Piano (http://piano.io) AI analytics.

### CODE REVIEW

**Comment by dvoytenko** [comment]
assigning to @avimehta for an initial review.

**Comment by cramforce** [comment]
@nathangoulding Thank you!!!

**Comment by avimehta** [comment]
Almost there. mostly lgtm. only one small comment. Sorry for the delay.

Please rebase to HEAD after you address the one comment.

cc @rudygalfi

**Comment by rudygalfi** [comment]
FYI: I created a tracking intent to implement issue: #1769

**Comment by avimehta** [comment]
any updates on this? Please rebase and address the comment. We are almost there!

**Comment by nathangoulding** [comment]
Just rebased and believe I've addressed the comments. Thanks!

**Comment by rudygalfi** [comment]
FYI. New PR opened in #2075

**Pull request closed without merging**
