### PR TITLE
📖amp-consent: Add Didomi CMP documentation + example (rebase)

### PR DESCRIPTION
**Pull request by MaximePlancke**
Add Didomi documentation and example to AMP related to this comment: 
https://github.com/ampproject/amphtml/pull/22518

### CODE REVIEW

**Comment by MaximePlancke** [comment]
@zhouyx @torch2424 

Here is the correct PR. Sorry for the rebase issue.

**Comment by zhouyx** [comment]
Got approval from #22518, merged. Thank you @MaximePlancke!

**Comment by MaximePlancke** [comment]
Great! Thank you for your reactivity

**Comment by torch2424** [comment]
Thank you @MaximePlancke ! 😄

**Pull request merged**
