### PR TITLE
Move Google SafeFrame version to AMP_CONFIG variable

### LINKED ISSUE #9266: AMP_CONFIG variable for Google SafeFrame version
Under some circumstances, Fast Fetch renders creatives into a Google SafeFrame. When Google updates the SafeFrame version that it uses in GPT, then it becomes out of sync with the one used in Fast Fetch, which makes cache misses more likely (since the version used in GPT is likely to already be cached in users' browsers). Currently, the version number is a hardcoded constant in `amp-a4a.js`, which means that any change requires the full two-week runtime release cycle. It would be better to put it into `AMP_CONFIG`, since config-only changes are allowed to be released outside of the runtime release cycle. This would allow updates to propagate much more quickly.

@ampproject/a4a

### PR DESCRIPTION
**Pull request by taymonbeal**
Fixes #9266.

### CODE REVIEW

**Comment by lannka** [comment]
It's weird to me that all ad network have to use Google safeframe? How can they opt-out?

**Comment by taymonbeal** [comment]
That was only ever intended to be a temporary measure until we got NameFrame working.

**Comment by taymonbeal** [comment]
Networks can override the rendering behavior by sending the `X-AmpAdRender` response header, which can be `client_cache`, `safeframe`, or `nameframe`. The default behavior (if the header is absent) is `safeframe` on iOS (i.e., if the user agent string contains `iPhone` or `iPad` or `iPod`) and `client_cache` on all other platforms.

**Comment by taymonbeal** [comment]
None of this is directly affected by this PR, all we're doing is making it possible to update the Google SafeFrame version with a config change instead of a code change.

**Comment by lannka** [comment]
Understand, but I'm bit resistant on introducing a 3p config into AMP_CONFIG. If this door is open, we could start to receive requests for adding arbitrary 3P configs.

Also, the intention isn't that clear to me either. We can discuss in the original issue thread.

**Pull request closed without merging**
