### PR TITLE
🏗📖 Cap line length of Markdown files

### PR DESCRIPTION
**Pull request by DerekNonGeneric**
I am in the process of adding Markdown linting to the amp.dev repo (https://github.com/ampproject/amp.dev/pull/3346). During the last wg-outreach meeting I was informed that the same mechanism used in the amphtml repo should be used.

Nice to have: capping the line-length of Markdown files to 80 chars. It would greatly assist with revising proposed changes when looking at the diffs of typo/grammar PRs in GitHub. For example, [look at line 75 of this diff](https://github.com/ampproject/amp.dev/pull/3376/files#diff-2f42ddd4bbb26c5658d732a59fefde5dR75). It's difficult to find what was changed.

Problem: running `npx gulp prettify --fix` does not auto-format the max line-length of Markdown files. They should theoretically be maxing 80 chars if this task inherits the default print-width of prettier.

Solution: explicitly specify the line-length of Markdown files in `.prettierrc`.
- https://prettier.io/docs/en/options.html#print-width
- https://prettier.io/docs/en/options.html#prose-wrap

/cc @rsimha

### CODE REVIEW

**Comment by rsimha** [comment]
IIRC, we didn't initially enforce line width limits for `.md` files because of the sheer number of lines of diffs they would generate.

I've added @mrjoro and @CrystalOnScript to comment on whether this is desirable.

**Comment by mrjoro** [comment]
I'd lean towards not enforcing this line length limit.  md files often get modified in the web ui and there isn't a good way of knowing when a line goes past 80 chars.

**Comment by DerekNonGeneric** [comment]
I see what you're getting at. https://github.com/ampproject/amphtml/pull/21212 already had a 138,754 line diff. Including this would've been a bit much. I guess this can be seen as a continuation of that effort.

From a workflow perspective, [VS Code's `editor.formatOnSave` option](https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings), which is [already enabled in this project](https://github.com/ampproject/amphtml/blob/master/.vscode/settings.json#L28), makes composing in Markdown files while still following this rule so much nicer.

**Comment by DerekNonGeneric** [comment]
/to @mrjoro

> md files often get modified in the web ui and there isn't a good way of knowing when a line goes past 80 chars.

Would the CI check be insufficient? Maybe the CI can even auto-format the files and recommit? I'm not sure if that is already happening.

**Comment by rsimha** [comment]
> I see what you're getting at. #21212 already had a 138,754 line diff. Including this would've been a bit much. I guess this can be seen as a continuation of that effort.

- #21212 (138k lines) enabled `prettier` for `.js` files via the `gulp lint` check.
- #25182 (18k lines) enabled `prettier` for `.md` files via the `gulp prettify` check.

> Maybe the CI can even auto-format the files and recommit? I'm not sure if that is already happening.

This doesn't happen, and is not something we plan on supporting.

**Comment by DerekNonGeneric** [comment]
> We don't want to make it even more onerous for folks to edit `.md` files via GitHub's web UI.

It's a shame the GitHub web UI doesn't infer this based on a repo's `.editorconfig` file (or allow a user to set it themselves). A potential workaround exists via userscript until GitHub includes this feature themselves. There is some prior art with the [GitHub code guides userscript](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-code-guides).

**Comment by mrjoro** [comment]
Is this PR still active?

**Comment by DerekNonGeneric** [comment]
I guess I will close this. I still stand by it, but it seems like this project doesn't want to do this. I wonder if there was a change of mind since I opened this? Please do tell. :)

**Pull request closed without merging**
