### PR TITLE
✨ PubScale ad network registration

### PR DESCRIPTION
**Pull request by prabeen04**
pubscale logo

[PubScale](https://pubscale.com) is an all-in-one platform enabling fast monetization and user acquisition for apps, websites, and games while retaining positive user experiences. With PubScale, you can uplift revenue and analyze business growth all in a single place.

This PR integrates the PubScale ad network, using the <amp-ad> tag.

### CODE REVIEW

**Comment by prabeen04** [comment]
Hey guys, circli ci pipeline is not triggered after the latest commit, Is there any rate limit or any approval pending?
cc: @calebcordry

**Review by powerivq — APPROVED** [review]

**Comment by powerivq** [comment]
@prabeen04 Approved. Can you try rebasing against the latest main branch? That might help.

**Comment by powerivq** [comment]
@danielrozenberg CircleCI build is now showing up, but still not running. Do you have any idea?

**Comment by prabeen04** [comment]
HI @powerivq, Is there some change needed from my side ?

**Comment by danielrozenberg** [comment]
Not really sure what's going on here... It does look like the last successful trigger on CircleCI was commit e1d3717 (https://app.circleci.com/pipelines/github/ampproject/amphtml?branch=pull%2F39051)

You can try creating a new PR (clone the branch on your own fork and create a PR from that one), and if that doesn't work I can try to clone your branch onto my fork and try to create the PR myself. Want to try creating a new PR?

**Comment by prabeen04** [comment]
Hi @danielrozenberg, thanks for your input, I have created a new PR from a cloned branch,

https://github.com/ampproject/amphtml/pull/39100
Please let me know if any changes required.

**Comment by danielrozenberg** [comment]
btw, the End-to-End tests issue was fixed in a separate PR, so try rebasing on main again. I'm sorry about all this busy-work, we'll get there eventually!

**Comment by prabeen04** [comment]
I synced the PR, but it seems like it is stuck again at the bundle size check.

**Comment by danielrozenberg** [comment]
Looks like I have to sync my fork every time 😬

**Comment by powerivq** [comment]
We made some large changes yesterday so you probably need to rebase again.

```
Detected a merge conflict between pull/39110 and the main branch.
Please rebase your PR branch.
```

**Comment by GGprabeen** [comment]
I have rebased the PR, @danielrozenberg can you please sync your fork .

I hope this time it goes through.😅

@danielrozenberg and @powerivq , thanks for the help till now, I really appreciate it.

**Comment by prabeen04** [comment]
I have rebased the PR, @danielrozenberg can you please sync your fork .

I hope this time it goes through.😅

@danielrozenberg   and @powerivq, thanks for the help till now, I really appreciate it.

**Review by powerivq — APPROVED** [review]

**Review by powerivq — APPROVED** [review]

**Comment by powerivq** [comment]
Woohoo. Finally merged it.

**Comment by prabeen04** [comment]
Thank you @powerivq and @danielrozenberg, we did it !  🥳 🥳 🥳

**Comment by prabeen04** [comment]
Hi @powerivq, I have one question, when these changes will go live, on the official amp website

**Comment by powerivq** [comment]
@prabeen04 your message isn't complete. What's your question?

**Comment by prabeen04** [comment]
@powerivq ,  I wanted to know about the release cycle. Anyway  I have read it in the official website, which says incremental rollout starts every tuesday.

**Comment by prabeen04** [comment]
Hi @powerivq , I cant see the label [PR use: In Beta / Experimental](https://github.com/ampproject/amphtml/labels/PR%20use%3A%20In%20Beta%20%2F%20Experimental) for this PR, Other Ad vendors have the tags applied in the latest release cycle.

Is there something needs to be done from my side.

**Comment by prabeen04** [comment]
Hi @powerivq ,I am following up on my previous comment about the missing [PR use: In Beta / Experimental](https://github.com/ampproject/amphtml/labels/PR%20use%3A%20In%20Beta%20%2F%20Experimental) label for this PR. I've noticed that other Ad vendors have the tags applied in the latest release cycle, so I'm wondering if there's something that needs to be done from my side.

**Comment by powerivq** [comment]
There are nothing you need to do.  The delay in releasing is caused by a regression bug.

**Comment by lenasssas** [comment]
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7463749579933474"
     crossorigin="anonymous"></script>

**Pull request merged**
