### PR TITLE
🚮 Removing mediaimpact integration

### PR DESCRIPTION
**Pull request by renebaudisch**
- removing mediaimpact.js to avoid usage of not longer maintenanced and revised code

### CODE REVIEW

**Comment by renebaudisch** [comment]
@lannka: reviewer needed

**Comment by lannka** [comment]
@renebaudisch is this deprecation well communicated to the users? we will need to follow the [deprecation](https://github.com/ampproject/amphtml/blob/master/spec/amp-versioning-policy.md#deprecations) process to avoid any disruption at user side. 

Since this is a vendor integration, I think we can simplify the process a bit. For example, we could skip the I2D and the 2wks discussion since the vendor is the main stakeholder of this integration. Then directly jump to the announcement of the deprecation and start to print console errors. We expect the vendor to do the full communication with their customers about this deprecation.

@mrjoro @ampproject/wg-approvers @ampproject/wg-ads for comments.

**Comment by powerivq** [comment]
Is this integration currently working for users? If it is, I think we should do the deprecation notice. If it is not, is deprecation still valuable?

**Comment by renebaudisch** [comment]
No publisher is using this at the moment and it also wouldn't work anymore since the account behind has been deactivated, that's why we want to remove it.

**Comment by lannka** [comment]
@powerivq good point. However I still feel a bit nervous about removing it right away. It will be good to have a regular process to mitigate human errors. At least for example printing console errors for a week or two.

@ampproject/wg-approvers for feedback

**Comment by cathyxz** [comment]
I think our Deprecation Policy, as outlined [here](https://github.com/ampproject/amphtml/blob/master/spec/amp-versioning-policy.md#deprecations) may be relevant. 

We should probably start by filing an Intent to Deprecate and Remove, announcing this on slack, and logging a console warning for using this component in build callback.

**Comment by cramforce** [comment]
I think if a component is literally broken, because the backend is dead,
then that might be a special case.

The component could immediately be made inert while staying valid AMP (so
that docs don't break) and then get deleted after the deadline.

**Comment by lannka** [comment]
@cramforce I'm afraid of human mistakes for example the vendor think it is broken, or no one is using it, but it ends up with real usages. Or, in some other extreme scenarios, the proposed deletion is not from the authority.

We could make a special case for "if the backend service is dead" in the deprecation process, but is it AMP's responsibility to verify the dead backend? Or do we just need to be told from the same PR?

**Comment by cramforce** [comment]
I guess if the service owner tells us, that is fine for me.

**Comment by lannka** [comment]
> I guess if the service owner tells us, that is fine for me.

OK. How about revising our deprecation process as:

... As breaking an `amp-ad` `amp-analytics` integration is less user disruptive, an easier process can be applied. After verifying of no usages from the ads / analytics vendor side, the original contributor of the integration can directly send a PR to remove the integration.

**Comment by lannka** [comment]
@renebaudisch LGTMed. Please fix the travis failures so I can merge it for you. Thanks!

**Comment by renebaudisch** [comment]
But they don't rely on my changes, these are connected to other PRs/commits. I don't know what' wrong with it, and I didn't know how to fix those, so should I do that PR once again?

**Comment by lannka** [comment]
> If validator/testdata/feature_tests/ads.out is incorrect, please run `gulp validator --update_tests` to regenerate it based on its corresponding .html file.

you can follow this to fix the validator tests.

> ads/onead.js:54: ERROR - [JSC_POSSIBLE_INEXISTENT_PROPERTY] Property setup never defined on win.Guoshi.queryAd.amp
    win.Guoshi.queryAd.amp.setup({
                           ^^^^^

This type check failure is a side effect of removing lines from ads.externs.js. You might need to add fix `ads/onead.js` 

```js
win.Guoshi.queryAd.amp['setup']({
```

**Comment by renebaudisch** [comment]
I really don't think this is part of my PR, the check fails by ads/onead.js that is not connected to mediaimpact in any way, and the validator should be ok since we only remove code, so it has to validate less than before and that should already validate in a proper way.

**Comment by lannka** [comment]
as I mentioned before, the test failure was a side effect of your change via `ads.externs.js`, although logically `ads/onead.js` has nothing to do with `mediaimpact.js`. 

you removed lines from the example file which was used as a input to the validator tests.

**Comment by renebaudisch** [comment]
So, Travis only checks changed files, and since onead.js is not defined in the changed ads.extern.js because, I don't know, it was not necessary at time onead was implemented(?), but uses a property that seems to be defined externally, the check now fails. Did I got it? 
But then, adding their vars to ads.external feels much better for me since I do not change code that's not related to me/us and travis will be happy also...

**Comment by lannka** [comment]
@honeybadgerdontcare for approval on validator file changes.
@renebaudisch could you pls also resolve the merge conflict.

**Comment by renebaudisch** [comment]
I would like to resolve but "Only those with write access to this repository can merge pull requests." so I cannot.
The conflict is that mediaimpact.md that will be deleted hereby has been reformated on 24.10.2019 so it's base has changed, but in the end it shall be deleted, so I rebase my changes and force pushed it, but the conflict still exists here, I dopn't know what to do now.

**Pull request merged**
