### PR TITLE
🚀  [Story embeds] Remove support for expanded components like amp-twitter

### LINKED ISSUE #36353: [I2D&R] Tweet lightbox within Stories
### Summary

Within a Web Story, publishers can embed tweets using `amp-twitter`.
There are several ways to embed a tweet:

1. `amp-twitter[interactive]`
The tweet is (a) displayed inside a Story page, (b) opens a tooltip on tap, and (c) is expanded inside a lightbox: [example](https://www.industrialempathy.com/new-on-the-web/october-2021.html#page=id1436374668450177026).
We want to keep parts (a) and (b), but deprecate the lightbox (c) part, and replace it with a hard navigation to the URL of the tweet. This would be consistent with other links (`<a`) within Stories.

2. `amp-twitter`
No change: `amp-twitter` without the `interactive` attribute are unimpacted. The tweet loads and is visible but users can't interact with it.

3. No change: `amp-twitter` within a page-attachment
No change, tweets load within the page attachment and users can interact with them.

### Motivation

The feature brought a lot of complexity to the codebase, and was built to support more embeds like videos (e.g. YouTube) or music (e.g. Spotify or SoundCloud). We have no plans to build these new embeds as they present various UX and/or technical limitations, and have very little to no adoption for `amp-twitter[interactive]`.

Downgrading the lightbox to a hard navigation to the tweet would allow us to simplify a lot of code paths, and [reduce bundle size](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story/1.0/amp-story-embedded-component.js).

### Impact on Existing Users

Tweets configured with `[interactive]` will no longer open inside a lightbox in the Story, but will navigate to either the tweet web page, or the Twitter native app.

### Alternative Implementation

To allow users to interact with `amp-twitter` directly within a Web Story, publishers can embed the tweet within a page attachment.

### Additional Context

_No response_

### Notifications

/cc @ampproject/wg-approvers @ampproject/wg-stories

### PR DESCRIPTION
**Pull request by mszylkowski**
Closes #36353

Removes the expanded view used in amp-twitter. Uses linking instead (shows tooltip that links to the tweet).
This will allow us to get rid of a significant portion of unused code from `amp-story`, given that we will not be using the expanded view for other embedded components, and focusing on embedding interactive iframes in page attachments.

Removes 8kB of uncompressed, and 1.4kB compressed

The tweet URL is `https://twitter.com/_/status/<tweet_id>`. Where the `_` goes there should appear the username, but we don't want to make an API request to find that out, so we can "abuse" the fact that tweet_ids are unique and the website redirects to the correct username on load.

Reference: https://blog.twitter.com/developer/en_us/topics/tips/2020/getting-to-the-canonical-url-for-a-tweet

### CODE REVIEW

**Review by gmajoulet — APPROVED** [review]
There are still things that could be simplified further (e.g. we don't have embedded components anymore, just links) but that's an awesome first step, thank you!

**Comment by gmajoulet** [comment]
The Intent to deprecate and remove: https://github.com/ampproject/amphtml/issues/36353

Can you test a few real world Stories and make sure their layouts are good and unchanged (cf failing Percy tests)? recipe 538052

**Comment by mszylkowski** [comment]
> we don't have embedded components anymore

We still do, and we need to click shield them + add their tooltips. This PR removes the expanded states though.

> Can you test a few real world Stories and make sure their layouts are good and unchanged (cf failing Percy tests)? recipe 538052

Tested the most common stories / domains and they don't break the layout

**Comment by mszylkowski** [comment]
@gmajoulet in more detail, currently interactive (expandable) tweets are re-scaled so they have `scale=1` on the expanded view, which means that on the original view they don't meet exactly the layout values they were given. Non-interactive tweets do follow the layout values.

This means by removing this code, we can effectively make interactive and non-interactive tweets consistently behave, and without the weird scaling, the tweets still occupy the same space as before, but now using the `scale=1` always (aka, not scaled).

This is preferred and reduces the bundle size significantly, so we're moving forward with the merge.

**Pull request merged**
