### PR TITLE
Remove amp-scrollable-carousel experiment flag

### LINKED ISSUE #4232: remove `amp-scrollable-carousel` experiment
Remove `amp-scrollable-carousel` experiment and guard

### PR DESCRIPTION
**Pull request by muxin**
Fixes #4232

@erwinmombay The [PR](https://github.com/ampproject/amphtml/pull/6065) that always uses the new scrollable-carousel is not live yet. Do we have to wait for it to go live and then make this config change?

### CODE REVIEW

**Comment by erwinmombay** [comment]
@muxin should be fine to remove this now

**Comment by erwinmombay** [comment]
actually lets wait until that PR hits prod.

**Comment by muxin** [comment]
Yeah ok.

**Comment by muxin** [comment]
@erwinmombay Now that the PR is in prod, please take another look.

**Pull request merged**
