### PR TITLE
🐛 [amp story page attachment] min-height for drawers when in supports-landscape mode

### LINKED ISSUE #37234: Reduced area of amp-story-attachment
### Description

Prior to some time in September 2021 the `amp-story-attachment` opened to an area ~80% of the `amp-story` container.
The attachment borders were rounded and y-overflow enable scrolling.
The total area is important to us because, based on advice from Jon Newmuis @newmuis , we have moved iframes - featuring production applications - from a grid to an attachment (for amp-validation).
Then, as a preview, we use a screenshot of the production application in a grid.

Sometime during September 2021 the amp-story runtime changed to substantially compress the height and width of the attachment.
Currently, the attachment area is ~60% of the original area.

When viewed in desktop-landscape the "haircut" is significant.
Images that previously were completely "above the fold" are now bisected and require scrolling to see the image.
Text that previously was visible below an image is now only visible after scrolling.
And, of course, it is the text that is *most important* because, in many cases, it complements the image repeated from the grid.

When the same `amp-story` is presented using `amp-story-player`, the attachment - in effect - is unusable.
The screenshot illustrates the issue.

Our feature request is to provide the equivalent of an SVG viewBox inside an SVG viewPort.
There might be a default viewBox for an attachment (e.g. the current specification) with an option to specify a viewBox that could be up to 90% of the `amp-story` container (the equivalent of an SVG viewPort).

For CSS, the 'viewBox' might be some (maximum) percent of the `amp-story` container.
Such an approach might work well for both portrait and landscape.

Please consider the problem and proposed solution.
Currently, our desktop-landscape stories are significantly impacted, and our amps-story-player - on a single HTML page - is unusable.

### Alternatives Considered

Add a link to view an external HTML page

### Additional Context

image

### PR DESCRIPTION
**Pull request by processprocess**
Attachments in supports-landscape mode appear squished on small screens.
Screen Shot 2021-12-28 at 11 58 08 AM

This PR sets a min height on desktop mode attachments. 
The desktop attribute is currently only set [when in DESKTOP_FULLBLEED](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story/1.0/amp-story.js#L1682).
For a separate PR, this attribute should be renamed to desktop-fullbleed since it's specific to that UI type.

Implementation [screen recording](https://user-images.githubusercontent.com/3860311/147589789-56e25cf9-6e7d-462d-8a32-e8f8ff46a0cf.mp4).

This PR removes a calc in the drawer height that appears to be dead code.

Context / Fixes #37234

### CODE REVIEW

**Comment by mszylkowski** [comment]
One nit we should verify before merging: when the page attachment content is very short, does the modal expand it's height to the whole page or does it max-out at the height of the content? (I think the latter is the ideal behavior)

**Review by mszylkowski — APPROVED** [review]
Thanks for taking care of this!

**Comment by jaygray0919** [comment]
Is a solution here still on track?
Rather than using our instances, we check one of our model sites:
https://www.nationalgeographic.com/amp-stories/travel/best-trips-2020/?sf227538199=1
My recollection is that the attachment did not need overflow-y

Similarly, this target did not need overflow-y; on desktop landscape the attachment was 100% viewable:
https://www.washingtonpost.com/graphics/2019/lifestyle/travel/amp-stories/a-locals-guide-to-what-to-eat-and-do-in-new-york-city/
/j

**Comment by processprocess** [comment]
Thank you for the ping @jaygray0919 
This fix is ready, it will be merged shortly.

**Pull request merged**
