### PR TITLE
Support custom-delimiters attribute in mustache validator rules change

### PR DESCRIPTION
**Pull request by alabiaga**
Allow for usage of `#-` (beginning) and `-#` (ending) as delimiters to be specified in attribute `custom-delimiters`. Note that both versions will support the attribute but using it in mustache v1 will be a no-op and will just throw a warning to upgrade to v2 in order to use it.

Support for this change in the mustache v2 PR: https://github.com/ampproject/amphtml/pull/21460

### CODE REVIEW

**Comment by alabiaga** [comment]
@honeybadgerdontcare correct me I am wrong but no support for versions requirement in the rules yes? I think this would be nice to add in the future. I can make the change if need be. Thanks

**Comment by honeybadgerdontcare** [comment]
Extensions can be versioned and tags can require certain extensions. However, we have so far not have had to say A tag requires X extension at Y version and B tag requires X extension at Z version. Typically an extension (X) moves from a version (Y) to another version (Z). We can deprecate Y and start supporting Z.

If we need for an extension to do something different with versions then we should probably have an I2I or just an issue to discuss it and declare possibly implementations/solutions.

**Comment by alabiaga** [comment]
@honeybadgerdontcare Thanks David. As discussed offline, the already default no-op solution for handling this in the older version is a much simpler solution than having the ability to support this in the validator. I have to add the user warning in the extension itself but that's fine. Thanks again for the prompt response.

**Comment by mrjoro** [comment]
Is this PR still active?

**Pull request closed without merging**
