### PR TITLE
🐛 Bento Carousel: Fix auto advance bugs

### PR DESCRIPTION
**Pull request by caroqliu**
This PR fixes the following carousel autoadvance bugs
- imprecise `auto-advance-loops`: carousel autoadvance looked for an "end of slide" index marker to increment a counter representing "number of full carousel loops so far." This was buggy for looping carousels whenever `advanceCount / length` did not yield an integer. The fix increments the "carousel loops so far" by the `advanceCount / length` proportion on each `autoAdvance`, and uses that progress + the `visibleCount / length` to deduce if we have reached "at least the end" of a looping carousel. 
- thumbnail scrolling updating the overall carousel context `currentSlide`: This is so that end users can scroll inside and be scrolled inside the `Thumbnails` component without causing the primary carousel to jump in position. For things like autoadvance this can cause some buggy/jumpy content behavior.
- use of imperative api: Doing so should stop autoadvance altogether.

### CODE REVIEW

**Review by dvoytenko — COMMENTED** [review]
Looks great. But are any tests need to be updated?

**Comment by caroqliu** [comment]
> Looks great. But are any tests need to be updated?

Good point, the original build caused two tests to fail because of the new exit condition in `setRestingIndex` - fixed this and should be all set. As for introducing new tests, IMO the behaviors fixed here are better tested by e2e tests which don't have an existent counterpart in 0.1 for these features. Likewise the inline-gallery suite of carousels also do not have e2e tests period. I can add an open task for a fast follow up in Jan to make the carousel components go above and beyond the 0.1 testing suite if that is desirable?

**Comment by dvoytenko** [comment]
Do these have to be e2e tests? Is normal unit testing environment work at all for this?

**Review by dvoytenko — APPROVED** [review]

**Comment by caroqliu** [comment]
> Do these have to be e2e tests? Is normal unit testing environment work at all for this?

Given autoadvance is tied to a document and timer, I believe e2e testing is the best format since it would load a full page as the user's browser would. I'm worried with unit tests it could be prone to flakiness due to timing and measuring, which we have already seen somewhat with the basic imperative api in this component. I can, however, add to the existing auto-advance e2e test in this PR if that helps.

**Comment by dvoytenko** [comment]
> > Do these have to be e2e tests? Is normal unit testing environment work at all for this?
> 
> Given autoadvance is tied to a document and timer, I believe e2e testing is the best format since it would load a full page as the user's browser would. I'm worried with unit tests it could be prone to flakiness due to timing and measuring, which we have already seen somewhat with the basic imperative api in this component. I can, however, add to the existing auto-advance e2e test in this PR if that helps.

I see. Makes sense.

**Pull request merged**
