### PR TITLE
🐛 amp-ad type blade - fix bladeOnLoad callback

### PR DESCRIPTION
**Pull request by gershman**
- fix function: createContainer -  bug: global was undefined fix: move function to be under the main export function

### CODE REVIEW

**Comment by gershman** [comment]
@lannka Hi I see that the build didn't pass, I don't think it something related to my pull request. Can you help?

**Comment by lannka** [comment]
The test failure seems to be a flake. Restarted.

**Comment by gershman** [comment]
@lannka hi when will this be merge and deployed ?

**Comment by gershman** [comment]
@mrjoro @lannka Hi any updates when this will be merged and released, it is urgent for us. thx.

**Comment by gershman** [comment]
@lannka ?

**Comment by yonida** [comment]
@lannka @gmajoulet @erwinmombay 
 any update on this?

**Comment by gmajoulet** [comment]
I restarted the failing tests, if they still don't pass, could you please sync your PR with the master branch?

**Comment by gershman** [comment]
@gmajoulet  - Hi, I merged from master and rerun the tests, they still failed. So, I run gulp pr-check vs master branch and the same test fails there.
```
pr-check.js: Commit log since branch master was forked from master at 82cce82:
* 82cce8211 Matt Mower - (HEAD -> master, upstream/master, amp-ad--blade-fix-create-container-func-re-open-pr) custom-element: Minor test improvements (#26923) (10 hours ago)
```

**Comment by gmajoulet** [comment]
I restarted them ~5 times but they keep failing for different reasons. :(

Can someone from @ampproject/wg-infra chime in?

**Comment by rsimha** [comment]
> I restarted them ~5 times but they keep failing for different reasons. :(
> 
> Can someone from @ampproject/wg-infra chime in?

Do you have failure logs, or remember which tests failed? (Restarted build means I can't see the old ones.)

/cc @zhouyx who is build cop this week, and can help with skipping any obviously flaky tests.
/cc @rcebulko who is working on stabilizing our Sauce Labs infrastructure, in case the failures were due to VM disconnections.

**Comment by zhouyx** [comment]
Looks like all test passed. Happy to skip tests if flakiness continues.

**Comment by rcebulko** [comment]
If this occurs again, could you stick the logs in a Gist and comment? That will help us debug. There is a known issue where we're hitting Sauce Labs concurrency limits, which may have been the culprit here.

**Comment by gmajoulet** [comment]
Looks like cc'ing the infra people scared the flaky tests away, thanks all :))

**Pull request merged**
