### PR TITLE
Update amp-fit-text AMP4EMAIL tagspec

### PR DESCRIPTION
**Pull request by honeybadgerdontcare**
Follow up to #24854 

Restrict `amp-fit-text` AMP4EMAIL tagspec to only `html_format: AMP4EMAIL`.

### CODE REVIEW

**Comment by honeybadgerdontcare** [comment]
@choumx as an aside to this would it be okay to remove `requires_usage: GRANDFATHERED` and `deprecated_allow_duplicates: true` for these AMP4EMAIL specific tagspecs? This would affect `amp-accordion`, `amp-fit-text`, and `amp-form`. Can be done in a separate PR.

**Comment by choumx** [comment]
> as an aside to this would it be okay to remove requires_usage: GRANDFATHERED and deprecated_allow_duplicates: true for these AMP4EMAIL specific tagspecs?

I think that should be fine. Would you mind also creating a tracking issue so we can label and communicate it appropriately?

**Comment by honeybadgerdontcare** [comment]
@choumx by tracking issue...is that a `Release tracking issue` or `Intent-to-deprecate` or just an issue of some form? =D

**Comment by choumx** [comment]
Heh, yea I was thinking of an "intent-to-deprecate" issue.

**Pull request merged**
