### PR TITLE
Swap preact back in with race condition band-aided

### PR DESCRIPTION
**Pull request by cvializ**
There was some race-y behavior that react-dates implicitly relies on.

@rsimha-amp The warnings about React being an unmet peer dependency of react-dates will appear again. IS there anything we can do to avoid those, or is it ok to ignore?

/to @aghassemi 
/cc @cramforce @kristoferbaxter

### CODE REVIEW

**Comment by samccone** [comment]
🙇

**Comment by developit** [comment]
Can confirm, any ill-effects of the sync option should be negligible for all but benchmarks.

**Comment by rsimha-amp** [comment]
@cvializ You're right. Here are the warnings: 
```
warning " > react-dates@13.0.6" has unmet peer dependency "react@>=0.14".
warning " > react-dates@13.0.6" has unmet peer dependency "react-dom@>=0.14".
warning "react-dates > airbnb-prop-types@2.8.1" has unmet peer dependency "react@^0.14 || ^15.0.0 || ^16.0.0-alpha".
warning "react-dates > react-with-styles@2.3.0" has unmet peer dependency "react@>=0.14".
warning " > react-with-direction@1.1.0" has unmet peer dependency "react@^0.14 || ^15 || ^16".
warning " > react-with-direction@1.1.0" has unmet peer dependency "react-dom@^0.14 || ^15 || ^16".
```
I don't want to block this PR purely due to the warnings. We should see if there's a way to get rid of them to avoid problems down the line. I'll try to investigate.

**Comment by rsimha-amp** [comment]
@cvializ It's possible this might be due to https://github.com/yarnpkg/yarn/issues/2132. I think you can safely merge this PR. If there's a fix that can remove these warnings, I'll send it to you a separate PR.

**Pull request merged**
