### PR TITLE
Documentation fix: amp-pinterest uses data- attributes

### PR DESCRIPTION
**Pull request by powdercloud**
Fixing the documentation, probably leftovers from an earlier version; this tag is using data- attributes as opposed to custom ones.
@Gregable @dvoytenko

### CODE REVIEW

**Comment by powdercloud** [comment]
I signed it!

Why are you so forgetful, Googlebot? I thought you knew me. Are they not giving you enough quota to remember?

**Comment by powdercloud** [comment]
I signed it!

**Comment by erwinmombay** [comment]
@powdercloud do you mind squashing this into 1 commit?

**Comment by powdercloud** [comment]
@erwinmombay Will try this later, I did this in the web interface.
I'll assume you mean doing something like this, right?
https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by erwinmombay** [comment]
@powdercloud yep! exactly it.

**Comment by powdercloud** [comment]
@erwinmombay I think I need to start this over, unfortunately. My local disk was still setup from when the repo was private, so after deleting my messed up forks I don't think I can update this one any more. Will send a new one.

**Comment by erwinmombay** [comment]
@powdercloud yep, its no problem :+1:

**Comment by powdercloud** [comment]
@erwinmombay Thank you for the patience, I'm still a newbie with github.
New request is https://github.com/ampproject/amphtml/pull/660, closing this one.

**Pull request closed without merging**
