### PR TITLE
🏗 [WIP] Use Windows for local tests on Travis

### PR DESCRIPTION
**Pull request by estherkim**
Use Travis' early-release Windows build environment to run local tests on a Windows VM.

(TODO item in https://github.com/ampproject/amphtml/issues/20887)

### CODE REVIEW

**Comment by estherkim** [comment]
After some investigation, I'm leaning towards not using of Travis' early release Windows build environment for our local tests. Reasons being: 
- Windows start up time is much longer than Linux
- Installing node packages take an average of [5 min](https://travis-ci.org/ampproject/amphtml/jobs/497213242#L313)
- Actual test job starts 15 to 20 min into the run
- Storing cache during VM shutdown takes another [5 min](https://travis-ci.org/ampproject/amphtml/jobs/497213242#L1099)
- Chrome installation is verging on flaky

Given the benefits of building and testing on Windows, I'd like to revisit this either when this feature is stable on Travis, or explore other services. @ampproject/wg-infra - thoughts?

**Comment by danielrozenberg** [comment]
Those numbers don't bode well. Looks like this time Beta actually means Beta :)
I'm +1'ing pushing this for a few months from now, in the hopes that Windows support improves

**Comment by estherkim** [comment]
I'm +1'ing your +1

**Comment by rsimha** [comment]
+1ing both your +1s. Agree with revisiting this in future, once Windows VMs are out of beta.

**Comment by kristoferbaxter** [comment]
Have you compared this time to AppVeyor? Right now `WorkerDOM` uses AppVeyor for Windows, and I was considering consolidation on Travis until there was more opportunity to revisit the entire CI/CD pipeline.

**Comment by estherkim** [comment]
@kristoferbaxter I haven't looked beyond Travis but maybe using its Windows build is worth revisiting. Are you looking to move `WorkerDOM` off AppVeyor?

**Pull request closed without merging**
