### PR TITLE
Remove dead links in amp-access-analytics doc

### PR DESCRIPTION
**Pull request by plr108**
Remove links to ./amp-access-spec.md#login-page.  The related content has not yet been added to the Detailed Discussion section of amp-access.md.

### CODE REVIEW

**Comment by torch2424** [comment]
Triaging to @jridgewell as you were last in the commit history 😄 

Also, @plr108 Thank you very much for finding/fixing this! For future reference, could you remove the PR/Issue template when you submit the PR? It is there more for a guide than to keep in the PR. Either way, great work, and thanks again for the help! 👍

**Comment by jridgewell** [comment]
This goes to @dvoytenko.

**Comment by plr108** [comment]
Thanks @torch2424!  I removed the template as I needed to bring this pull request up to date with master anyway.

**Comment by dvoytenko** [comment]
LGTM on these changes, but it looks like Travis is still failing?

**Comment by plr108** [comment]
Yes I will try to bring my branch up to date with master (plus the doc
change) a little later today.

**Pull request merged**
