### PR TITLE
🏗 Insert a line break before the code wrappers.

### PR DESCRIPTION
**Pull request by cramforce**
This will make adding stuff to the first line in postprocessing invariant to sourcemaps.

Part of #17061

### CODE REVIEW

**Comment by rsimha** [comment]
@cramforce We insert the `prod` (or `canary`) config to the start of the runtime during `gulp build`, `gulp dist --fortesting`, and `gulp test`. Does this code also need to be modified to include a `\n` between the `AMP_CONFIG` and the runtime code (`fileString`)?

https://github.com/ampproject/amphtml/blob/dec2fc23fe1ddcae1abb2022bc8630d18d4998cf/build-system/tasks/prepend-global/index.js#L77-L85

**Comment by cramforce** [comment]
@rsimha The idea is that this is modifying the first line only.

Hence coordinates in the source maps for all but the first line are correct when prepending config.

**Comment by jridgewell** [comment]
> This will make adding stuff to the first line in postprocessing invariant to sourcemaps.

I don't think this will actually fix sourcemaps. We have to update the entire sourcemap bytes when adding any byte a first line (update all things that come later).

**Comment by cramforce** [comment]
@jridgewell Isn't it a line based format?

**Comment by jridgewell** [comment]
No, I'm like 99% sure it's byte based.

**Comment by cramforce** [comment]
See https://sourcemaps.info/spec.html#h.qz3o9nc69um5

> The “mappings” data is broken down as follows:
> 
> each group representing a line in the generated file is separated by a ”;”
> each segment is separated by a “,”
> each segment is made up of 1,4 or 5 variable length fields.

**Comment by jridgewell** [comment]
Mmk, this'll help then. We still have the issue of the generated lines not matching the sourcemap output though:

```js
// output.js
1: function test() {
2:   throw new Error('test');
3: }

// our v0.js:
1: AMP_CONFIG={};
2: function test() {
3:   throw new Error('test');
4: }
```

So when the error is thrown, it has the following stack:

```
Uncaught Error: test
    at test (<anonymous>:2:11)
```

The `:2` is the line number (which starts at 0, while column starts at 1) should be `:1`. We could just compensate for this in our Error Server.

**Comment by cramforce** [comment]
@jridgewell The whole point of this change it to avoid the problem you are describing!

Before this change we did

`$code` becomes `CONFIG$code`

Now we do

`\n$code` becomes `CONFIG\n$code`

Note, how all code stays on the same line and column.

**Comment by jridgewell** [comment]
> Note, how all code stays on the same line and column.

The code is now on the `n + 1` line when the code is running, because we add a newline. 😛

**Pull request merged**
