### PR TITLE
✨ Add more query params to the Freestar rtc config.

### PR DESCRIPTION
**Pull request by vinnybod**
- Added additional parameters to the Freestar rtc config.

### CODE REVIEW

**Comment by vinnybod** [comment]
@rsimha Can I get a reason this was closed?

**Comment by rsimha** [comment]
@vinnybod We recently renamed the `master` branch on `ampproject/amphtml` to `main`. It's possible that this PR was closed as a side effect of the rename because they happened at the exact same time. Definitely wasn't my intent to close this PR 😃 

Can you reopen it and target it to the `main` branch?

**Comment by vinnybod** [comment]
Will do, thanks!

**Comment by rsimha** [comment]
I see that the new PR is targeting the correct branch. Sorry about the extra work, but glad you're back on track!

**Pull request closed without merging**
