### PR TITLE
🐛 [amp-analytics] Pass the canonical url on every Parse.ly Analytics pageview request

### PR DESCRIPTION
**Pull request by cwisecarver**
Passing the canonical url on pageview requests will allow us to properly associate self-hosted (non-CDN hosted) AMP traffic with the canonical URL of the content. We have had a customer manually add this change to their AMP configuration and verified that the traffic post-change was being correctly associated. I also tested this locally using `gulp default` and the `analytics-vendors.amp.html` page to confirm the HTTP request sent by the pageview event was correct.

### CODE REVIEW

**Comment by zhouyx** [comment]
@cwisecarver Please also update the test file. Thanks

**Comment by cwisecarver** [comment]
Any update on this @zhouyx ? It's a pretty small configuration change and we have customers waiting on it.

**Comment by cwisecarver** [comment]
@zhouyx No worries about the delay. 

That does work. I'm expecting the JSON to be URL encoded. I just tested that exact snippet you posted and it parsed correctly on our side. 

Thanks!

**Comment by zhouyx** [comment]
@cwisecarver Thank you for confirming! PR merged.

**Comment by cwisecarver** [comment]
@zhouyx I imagine this will end up in the release on January 9th not December 18th, correct?

**Comment by zhouyx** [comment]
@cwisecarver The change will be in canary cut today. But since there will be no prod release next, the change will hit prod on January 2nd.

**Pull request merged**
