### PR TITLE
Delete yarn.lock and update package-lock.json

### LINKED ISSUE #11278: Use one package manager, not two
Now that NPM supports version locking in v5, it would be nice to only have a single package manager, e.g. replace yarn.lock with package-lock.json.

/to @danielrozenberg /cc @rsimha-amp @erwinmombay

### PR DESCRIPTION
**Pull request by rsimha-amp**
Cleans up the bad merge described in https://github.com/ampproject/amphtml/pull/9775#issuecomment-329675286

Follow up to #11279
Fixes #11278

### CODE REVIEW

**Comment by choumx** [comment]
Does package-lock.json need to be updated? The Babel 6 upgrade modified package.json.

**Comment by rsimha-amp** [comment]
@choumx Good point, but there were no changes when I blew away my `node_modules` directory and re-ran `npm prune && npm install --save-dev --save-exact` on my machine.

The documentation at https://docs.npmjs.com/files/package-lock.json says that the files would be changed if necessary, but I'm somehow not convinced. @erwinmombay @danielrozenberg Is this weird? Can one or both of you test this on your machines to make sure we're okay?

**Comment by rsimha-amp** [comment]
@choumx Scratch my earlier comment. I had an older version of `npm` on my machine (the one that comes with node 4 by default), and it's all good once I upgraded.

I'll update the instructions if necessary.

**Comment by rsimha-amp** [comment]
Can confirm that `yarn` is no longer run on Travis, and that `npm install` (with the correct version of `npm`) takes ~16 s on Travis.

Will merge this once Travis goes green.

**Pull request merged**
