### PR TITLE
🏗Allow wg-ads to approve new ad extensions

### PR DESCRIPTION
**Pull request by powerivq**
We want to be able to approve new ad extension creation. Does this OWNER file work? @rcebulko if you can review.

### CODE REVIEW

**Comment by powerivq** [comment]
@alanorozco for owner approval of this PR.

**Comment by rcebulko** [comment]
> We want to be able to approve new ad extension creation. Does this OWNER file work? @rcebulko if you can review.

At present, this will not work. Glob patterns are only supported for filenames, not for directories in OWNERS files. The idea behind this was to keep the complexity as low as possible. See https://github.com/ampproject/amp-github-apps/issues/613 for reasoning and workarounds, and feel free to re-open the discussion if this has become a more common/widespread need

**Comment by powerivq** [comment]
Thank you. Wasn't aware it has been discussed before

**Comment by rcebulko** [comment]
> Thank you. Wasn't aware it has been discussed before

Yeah, the gist is that it would potentially add a lot of complexity and possible ambiguity/weird interactions between rules, but it seems like new ad networks are infrequent enough to not be too burdensome. If that change, feel free to re-open.

**Pull request closed without merging**
