### PR TITLE
Group sorting amp-ad-network-valueimpression

### PR DESCRIPTION
**Pull request by powerivq**

### CODE REVIEW

**Review by rcebulko — APPROVED** [review]
Thanks for taking care of this!

**Review by calebcordry — APPROVED** [review]

**Comment by rcebulko** [comment]
@powerivq `@krdwan` is no longer working on AMP as far as I know; consider reassigning the review

**Comment by powerivq** [comment]
@rcebulko Gotcha. Can you add yourself to OWNER and own that specific file? I thought you already did but it appears that you do not.

**Comment by powerivq** [comment]
Adding @newmuis  for owner approval. This is a styling-only change so it should be safe.

**Review by newmuis — APPROVED** [review]

**Pull request merged**
