### PR TITLE
🐛 Remove the erroneous, trailing space in filename

### PR DESCRIPTION
**Pull request by zapthedingbat**
The `build-system\babel-plugins\babel-plugin-transform-function-declarations\test\fixtures\transform-assertions\arguments-identifier\options.json` had a trailing space in the file name that stopped the repo being cloned on a windows file system. This PR simply removes the space.

### CODE REVIEW

**Comment by zapthedingbat** [comment]
@googlebot I signed it!

**Comment by zapthedingbat** [comment]
@kristoferbaxter it looks like this might have happened in a recent refactor.

**Comment by jridgewell** [comment]
I kicked travis to restart.

**Comment by kristoferbaxter** [comment]
Apologies, just saw this.

@rsimha - Can we get a Windows build check added to the environment via Github Actions? This would be a nice additional gate for our development and prevent future issues like this one.

**Comment by rsimha** [comment]
> @rsimha - Can we get a Windows build check added to the environment via Github Actions? This would be a nice additional gate for our development and prevent future issues like this one.

It's something we've talked about, but I'm not sure if we ever got to the point of trying it out. Can you file a FR under `ampproject/amphtml` and tag `@wg-infra`?

**Pull request merged**
