### PR TITLE
Flush out the AMP dev-mode spec documentation

### PR DESCRIPTION
**Pull request by Gregable**
Flush out the AMP dev-mode spec documentation on methods for triggering development mode and the related warnings generated.

### CODE REVIEW

**Comment by Gregable** [comment]
I signed it!

**Comment by dvoytenko** [comment]
@Gregable LGTM. Is it ready to be merged or are you still changing it?

**Comment by Gregable** [comment]
Ready to be merged if you are OK with it.

**Comment by Gregable** [comment]
@dvoytenko, I don't have the rights to actually merge this, fyi.

**Pull request merged**
