### PR TITLE
[amp-sidebar] Split component files for NPM packaging

### PR DESCRIPTION
**Pull request by rcebulko**
Building on #32474

### CODE REVIEW

**Review by caroqliu — APPROVED** [review]
Thanks Ryan! @krdwan as FYI

**Comment by rcebulko** [comment]
Going to merge with Caroline's approval but Kevin if you have concerns I'll be happy to address

**Review by jridgewell — COMMENTED** [review]
LGTM

**Review by krdwan — COMMENTED** [review]
Thanks for headsup! @caroqliu LGTM!

No concerns @rcebulko Thanks!

**Pull request merged**
