### PR TITLE
Rename navigation service to clickhandler 

### PR DESCRIPTION
**Pull request by alabiaga**
The navigation service deals with the interception of the click event listener. This is a prereq to augmenting this service with a means of registering and managing all click listeners being added to an ampdoc.

### CODE REVIEW

**Comment by alabiaga** [comment]
@jridgewell thanks!

**Comment by alabiaga** [comment]
Oh interesting. I am not crazy about the name navigation though, as
majority of the logic in the class pertains to click intercepting. Perhaps
the navigation logic (navigateTo) should reside in an action class,
standard-actions-impl.js. I'll make that change and see if it makes sense.

**Comment by alabiaga** [comment]
@choumx actually it makes more sense to move to action-impl.js in class ActionService as that is an embeddableService like navigation.js . Let me know what you think and I can make that change in a seperate PR.

**Comment by choumx** [comment]
Well... I made the change to consolidate so naturally I think it's more readable to have a single place handle all navigation behaviors. Not all uses of `Navigation.navigateTo` are action-related. Check out #13300 to see the history.

**Comment by alabiaga** [comment]
@choumx ok that is fine. lets keep it with the same name then. I don't feel strongly about this, though I think the name is confusing for what it does. Thanks.

**Pull request closed without merging**
