### PR TITLE
🐛 Respect initial "slide" attribute in amp-base-carousel

### LINKED ISSUE #32908: [amp-base-carousel] the "slide" attribute is not working
## What's the issue?
the value set to the slide attribute seems to be ignored.
[see my playground code.](https://playground.amp.dev/?mode=Responsive#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5BdXRvIGFkdmFuY2Ugd2l0aCBncm91cGluZzwvdGl0bGU+CiAgPGxpbmsgcmVsPSJjYW5vbmljYWwiIGhyZWY9ImFtcHMuaHRtbCIgPgogIDxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsbWluaW11bS1zY2FsZT0xLGluaXRpYWwtc2NhbGU9MSI+CiAgPGxpbmsgaHJlZj0naHR0cHM6Ly9mb250cy5nb29nbGVhcGlzLmNvbS9jc3M/ZmFtaWx5PVF1ZXN0cmlhbCcgcmVsPSdzdHlsZXNoZWV0JyB0eXBlPSd0ZXh0L2Nzcyc+CiAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLWNhcm91c2VsIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1jYXJvdXNlbC0wLjIuanMiPjwvc2NyaXB0PgogIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1iYXNlLWNhcm91c2VsIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1iYXNlLWNhcm91c2VsLTAuMS5qcyI+PC9zY3JpcHQ+CiAgPHN0eWxlIGFtcC1jdXN0b20+CiAgICAuc2xpZGUgewogICAgICB3aWR0aDogMzAwcHg7CiAgICAgIGhlaWdodDogMTAwJTsKICAgICAgZm9udC1zaXplOiAyNHB4OwogICAgfQogICAgLnNsaWRlICsgLnNsaWRlIHsKICAgICAgcGFkZGluZy1sZWZ0OiAxNnB4OwogICAgfQogICAgLmlubmVyIHsKICAgICAgZGlzcGxheTogZmxleDsKICAgICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7CiAgICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7CiAgICAgIHdpZHRoOiAxMDAlOwogICAgICBoZWlnaHQ6IDEwMCU7CiAgICAgIHBhZGRpbmc6IDRweDsKICAgICAgYmFja2dyb3VuZDogI2NkY2RjZDsKICAgIH0KICA8L3N0eWxlPgogIDxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tb3otYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1zLWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoO2FuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RofUAtd2Via2l0LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tcy1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1vLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1Aa2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fTwvc3R5bGU+PG5vc2NyaXB0PjxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjpub25lOy1tb3otYW5pbWF0aW9uOm5vbmU7LW1zLWFuaW1hdGlvbjpub25lO2FuaW1hdGlvbjpub25lfTwvc3R5bGU+PC9ub3NjcmlwdD4KICA8c2NyaXB0IGFzeW5jIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAuanMiPjwvc2NyaXB0Pgo8L2hlYWQ+Cjxib2R5PgogIDxoMj4KICAgIHNsaWRlIGF0dHJpYnV0ZSBpcyBub3Qgd29ya2luZwogIDwvaDI+CiAgPGFtcC1iYXNlLWNhcm91c2VsCglpZD0iY2Fyb3VzZWwtMSIKCWhlaWdodD0iMjAwIgoJbGF5b3V0PSJmaXhlZC1oZWlnaHQiCglsb29wPSJmYWxzZSIKCW1peGVkLWxlbmd0aD0idHJ1ZSIKICAgIHNsaWRlPTMKICA+CiAgICAJPGRpdiBjbGFzcz0ic2xpZGUiID48ZGl2IGNsYXNzPSJpbm5lciI+MTwvZGl2PjwvZGl2PgogICAgICAgIDxkaXYgY2xhc3M9InNsaWRlIiA+PGRpdiBjbGFzcz0iaW5uZXIiPjI8L2Rpdj48L2Rpdj4KICAgICAgICA8ZGl2IGNsYXNzPSJzbGlkZSIgPjxkaXYgY2xhc3M9ImlubmVyIj4zPC9kaXY+PC9kaXY+CiAgICAgICAgPGRpdiBjbGFzcz0ic2xpZGUiID48ZGl2IGNsYXNzPSJpbm5lciI+NDwvZGl2PjwvZGl2PgogPC9hbXAtYmFzZS1jYXJvdXNlbD4KPC9ib2R5Pgo8L2h0bWw+)

## How do we reproduce the issue?

set the value to the slide attribute.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

- LTS version of amp
- amp-base-carousel 0.1

### PR DESCRIPTION
**Pull request by caroqliu**
Fixes #32908

The `initialIndex` is already passed in from `amp-base-carousel`, just hasn't been read by `Carousel`:
https://github.com/ampproject/amphtml/blob/476d99c927db659ffcf2ccde286552dbca7aeaef/extensions/amp-base-carousel/0.1/amp-base-carousel.js#L178

Note: 1.0 already does this.

### CODE REVIEW

**Comment by micajuine-ho** [comment]
Do we have to worry about negatives indices? Are they prohibited by validation?

**Comment by caroqliu** [comment]
> Do we have to worry about negatives indices? Are they prohibited by validation?

Negative indices are okay - didn't come up in testing, but I'll add a test case for this. It appears to break the arrow-showing logic if the given index is greater than the # of slides provided. Do you have a preference if we normalize it within range with modulus or just assert if it's out of bounds?

**Comment by micajuine-ho** [comment]
> Do you have a preference if we normalize it within range with modulus or just assert if it's out of bounds?

Probably modulus, since we've asserted that's allowed and we want everything else to work well too

**Comment by caroqliu** [comment]
> > Do you have a preference if we normalize it within range with modulus or just assert if it's out of bounds?
> 
> Probably modulus, since we've asserted that's allowed and we want everything else to work well too

Wanted to clarify - negative indices are "okay" as in using them with the current logic doesn't break anything and silently gets treated as `0`. I think in that case we will not do modulus? The question is more what to do with slide="4" if only three are given - should it normalize to index `1` (modulo), `2` (clamp to max)` or `0` (invalid => `0`)?

**Comment by micajuine-ho** [comment]
Gotcha, thanks for the clarification. I would say we treat it similar to how we do `advance()`--if we are looping then modulus, otherwise clamp.
https://github.com/ampproject/amphtml/blob/734d3058d992a22dcea7239b38adf0001582c6fd/extensions/amp-base-carousel/0.1/carousel.js#L415-L424

**Comment by caroqliu** [comment]
> Gotcha, thanks for the clarification. I would say we treat it similar to how we do `advance()`--if we are looping then modulus, otherwise clamp.
> https://github.com/ampproject/amphtml/blob/734d3058d992a22dcea7239b38adf0001582c6fd/extensions/amp-base-carousel/0.1/carousel.js#L415-L424

Great idea! Done in most recent change. One thing to note is that while this is respected in the `Carousel` implementation, the responsive attributes system used by `amp-base-carousel` appears to disregard string representations of negative numbers... That is, passing `slide="-1"` to the component will cause it to pass in an `initialIndex` of `0`. I would say diving further into this is out of scope for this PR/fix but we should figure out separately if it is intentional and document if so.

**Review by micajuine-ho — APPROVED** [review]

**Pull request merged**
