### PR TITLE
Added Nielsen support for EU

### PR DESCRIPTION
**Pull request by uniquelygeneric**
Added use of new subdomain for EU as well an enhancement to session ID generation.

### CODE REVIEW

**Comment by uniquelygeneric** [comment]
I've signed it!

**Comment by uniquelygeneric** [comment]
Tagging @bpaduch in case there's any issues with the CLA. I was not the actual signer, but Nielsen does have one in place.

**Comment by bpaduch** [comment]
Your CLA should be passing; I've contacted the CLA team to investigate.

**Comment by bpaduch** [comment]
@uniquelygeneric - Please check with your CLA administrator at Nielsen and ensure you are part of the required group.

**Pull request merged**
