### PR TITLE
✨ Add Gdpr Consent String to Yieldlab callout vendor

### PR DESCRIPTION
**Pull request by mirkorean**
We want to add the GDPR consent string to our callout url.

### CODE REVIEW

**Review by powerivq — APPROVED** [review]

**Review by powerivq — CHANGES_REQUESTED** [review]
Please fix the style issue!

**Comment by mirkorean** [comment]
Hey @powerivq. Thanks for checking this! Weirdly that styling issue didn't pop up while `gulp lint` here. Fixed this.

**Review by powerivq — APPROVED** [review]

**Comment by powerivq** [comment]
Could you try rebasing on the latest master? @mirkorean Something is wrong (not your change) with the build and a rebasing should fix it.

**Comment by mirkorean** [comment]
I rebased and force-pushed. Something else failed that i don't understand though :)

**Comment by powerivq** [comment]
@estherkim for bundle size approval. Rebased it already. This PR should be safe wrt. bundle size.

**Review by estherkim — APPROVED** [review]

**Pull request merged**
