### PR TITLE
Allow-lists clip-path css property

### PR DESCRIPTION
**Pull request by wassgha**
TODO:

- [ ] Confirm the change with @ampproject/wg-amp4email

### CODE REVIEW

**Comment by honeybadgerdontcare** [comment]
Before merging please confirm with amp4email team.

**Comment by nainar** [comment]
I will add it to the monthly agenda for the Email meeting. The next meeting is this Thursday.

**Comment by dvoytenko** [comment]
@honeybadgerdontcare So noted.

**Comment by nainar** [comment]
@ampproject/wg-amp4email doesn't use this allowlist to allow CSS attrs in the spec. So happy for this to go ahead. 

Generally don't want to allow SVGs or clip paths (which could be used to link to SVGs) as it could be used for fingerprinting users. 

@zhangsu as FYI

**Comment by zhangsu** [comment]
Just to add that `clip-path` may send a network request to an SVG resource when the value is a `url(...)`. The network request would leak user PII if not proxied, but some email clients (like Gmail) today don't have the infrastructure to proxy such requests, so we probably won't allow this in the short term.

As Naina mentioned, email clients are not currently relying on the CSS whitelist modified in this PR because they have their own CSS sanitizers enforcing only whitelisted CSS. We are working with @fstanis and others to define the email CSS whitelist in the spec, but it will most likely be a separately whitelist, not the one modified in this PR.

**Comment by dvoytenko** [comment]
To clarify: we'd want to use `clip-path: url()` just as we'd use `background-image: url()`. So our goal right now to reconcile the two from AMP spec point of view. I think, from AMP4Email point of view, we'd also be happy if `clip-path` was treated the same way as `background-image`. Would that work for you?

**Comment by fstanis** [comment]
Right now, I think only `background` (and `background-image`) can have a `url()` in emails. `filter` is [listed in the spec](https://amp.dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-css/?format=email#additional-restrictions), but `url()` is specifically not allowed. Another example I know that could use `url()` is `list-style`, but I believe Gmail removes it if it contains `url()`.

Worth mentioning that `clip-path` is slightly different from `background`: as @zhangsu mentioned, it only allows SVG, which itself is not allowed in emails. Email clients tend to proxy images and may transform SVG to a different format in the process (e.g. PNG) which would break this usage.

I suggest this is excluded from the validator for now. A potential solution would be if the validator could block `url()` usage based on a whitelist of CSS properties. @honeybadgerdontcare FYI.

**Comment by choumx** [comment]
Filip, aren't you on vacation?

**Comment by Gregable** [comment]
Let's just allow for non-email for now then.

If we wanted perfection, we could add code so that email could allow if not an `url()`, but I think the usage of this is likely small enough that this isn't worth that effort until there is a real need.

**Comment by wassgha** [comment]
@Gregable do you mind taking over this PR?

**Comment by Gregable** [comment]
@wassgha on it. Let's just close this PR. Is there an issue tracking this already?

**Comment by dvoytenko** [comment]
@Gregable I filed https://github.com/ampproject/amphtml/issues/27246. I took the liberty at filing it as P1. LMK if it's possible for a short turnaround.

**Pull request closed without merging**
