### PR TITLE
✨ Add Yieldlab to RTC callout vendors

### PR DESCRIPTION
**Pull request by mirkorean**
Add Yieldlab (https://www.yieldlab.com) to RTC callout vendors.

### CODE REVIEW

**Comment by mirkorean** [comment]
Can you help me with a review @keithwrightbos @bradfrizzell? You both seem to be most familiar with RTC / the callout vendors.

**Comment by lannka** [comment]
@mirkorean would you provide a working end point URL so we can take a look at the response format?

**Comment by mirkorean** [comment]
@lannka thanks for taking a look! I created a test placement (ADSLOT_ID: 8949329). Should currently always have targeting.

http://ad.yieldlab.net/yp/8949329?content=amp&t=amp%3D1

Keys are customizable by the publisher.

**Comment by BertiBauer** [comment]
Hello @keithwrightbos and @lannka, any news on when this request will be reviewed? Thanks for your feedback and help with this!

**Comment by mirkorean** [comment]
Closed, because Follow-up PR: https://github.com/ampproject/amphtml/pull/23595 is merged.

**Pull request closed without merging**
