### PR TITLE
✨ Intent To Implement: BeaverAds support for amp-ads

### PR DESCRIPTION
**Pull request by hamburger228**
Added support for BeaverAds widgets to amp-ad elements

### CODE REVIEW

**Comment by hamburger228** [comment]
I signed it!

**Comment by calebcordry** [comment]
Hello @hamburger228 thanks for contributing! When I load your ad locally I don't see any content. It appears your script is adding some elements but they all have height=0 Would it be possible to return an actual fake ad? It helps us with testing when making changes to the codebase.

**Comment by hamburger228** [comment]
Hello @calebcordry, that ad has global targeting installed now and it's content is showing.

**Comment by rsimha** [comment]
@calebcordry This broke `master` because it was tested before the prettier change landed, but merged after it. See https://travis-ci.org/ampproject/amphtml/jobs/535003595#L315

To fix, you can run `gulp lint --fix --files ads/beaverads.js` and send out the changes in a new PR :)

/cc @alanorozco

**Comment by calebcordry** [comment]
Thanks @alanorozco pinged me offline. Fixing now.

**Comment by Jouvan** [comment]
Is there any chance to implement ads from Ad Exchange to our AMP Page with JS, without hardcoding?

**Pull request merged**
