### PR TITLE
add shrinkwrap

### PR DESCRIPTION
**Pull request by erwinmombay**

### CODE REVIEW

**Comment by erwinmombay** [comment]
@cramforce PTAL

**Comment by cramforce** [comment]
Ah, wanna boost you line count again? :)

Did @greenkeeperio-bot do anything to work better with this?

**Comment by erwinmombay** [comment]
@cramforce yep lol, i dont think @greenkeeperio-bot has done anything to make this work any better.

what we could do though is add a webhook that submits a new shrinkwrap once we merge any changes to package.json.

**Comment by cramforce** [comment]
+1

Did you see https://greenkeeper.io/verify.html?

**Comment by erwinmombay** [comment]
@cramforce just read it, thanks for sharing.

i wonder how hard/easy it would be for greenkeeper themselves to add the shrinkwrap feature. the problem really with shrinkwrap is that there is no way to just "update" it like you would package.json, it has to rebuild one from your local node_modules/*

**Comment by cramforce** [comment]
@boennemann Do you happen to have any updates to share regarding greenkeeper and shrinkwrap?

**Comment by boennemann** [comment]
@cramforce We're building support for this, where we're using the PRs just like they're now, but we'll offer a script that handles shrinkwrap regeneration/updating on the user's CI. "Very soon" is all I can give you right now though.

**Comment by erwinmombay** [comment]
@thanks @boennemann , thats awesome to hear.

@cramforce closing this.

**Pull request closed without merging**
