### PR TITLE
🐛 [Story Preview] Wait until the story is visible before pausing for consent resolution

### PR DESCRIPTION
**Pull request by coreymasanto**
- Part of #37129

---

**Background**: Stories that include an `amp-consent` element are [paused](https://github.com/ampproject/amphtml/blob/0f6cdcebd462d3dcf580d8df0a7dfcdc02de9061/extensions/amp-story/1.0/amp-story.js#L1201) until the consent has been resolved.

**Issue**: The consent never resolves in preview mode because amp-consent doesn’t get built until the story is visible. This means that stories that contain `amp-consent` elements remain paused in preview mode until the story transitions to the visible state. 

**Fix**: Wait until the story is visible before calling `pauseStoryUntilConsentIsResolved_()`.

### CODE REVIEW

**Comment by coreymasanto** [comment]
@gmajoulet this PR results in a failure for the `'should pause the story if there is a consent'` [test](https://github.com/ampproject/amphtml/blob/9e920c549ea59f9626ed05522977808fe4de21ea/extensions/amp-story/1.0/test/test-amp-story.js#L497), due to `setStateStub` being called 3 times instead of once. Based on [this comment](https://github.com/ampproject/amphtml/blob/9e920c549ea59f9626ed05522977808fe4de21ea/extensions/amp-story/1.0/test/test-amp-story.js#L524-L526), we probably don't want that to occur. Is this PR acceptable, or should I find a different approach?

**Review by gmajoulet — APPROVED** [review]

**Comment by yizhaomtv** [comment]
The consent prevents story preview from autoplaying, shall we merge this change to unblock story preview? @coreymasanto @gmajoulet

**Review by newmuis — CHANGES_REQUESTED** [review]
This only applies to stories that utilize consent as a feature, right?

I have some additional questions about this, let's follow up before merging this.

**Comment by yizhaomtv** [comment]
Thanks for the update! Do we have a plan for resolving this issue? Otherwise we'll have to manually filter stories that have a consent dialog because they are not previewable.

**Comment by coreymasanto** [comment]
> Thanks for the update! Do we have a plan for resolving this issue? Otherwise we'll have to manually filter stories that have a consent dialog because they are not previewable.

There are ongoing talks around how `amp-consent` should be handled within story previews. The final decision has not yet been made, although it seems increasingly likely that we will need to prevent every story with a consent dialog from being previewed at all. I'll resolve the talks ASAP so that the next steps are clear

**Comment by coreymasanto** [comment]
Closing because we decided last October on two milestones:
  1. Prevent amp-consent stories from being previewed because allowing a preview would be circumventing the publisher-defined condition of needing to hit the **Accept** button
  2. IF previewing amp-consent stories becomes a high-priority, we can add a preview mode opt-in attribute for amp-consent stories

**Pull request closed without merging**
