### PR TITLE
🐛  Set `latestVersion` for `amp-story-audio-sticker`

### PR DESCRIPTION
**Pull request by swissspidy**
Tools like the AMP Optimizer require `latestVersion` to correctly import extensions with the correct version.

I thought https://github.com/ampproject/amp-toolbox/pull/1357 was enough to support `amp-story-audio-sticker` there, but turns out it wasn't.

All other extensions already have `latestVersion` set, so it makes sense for `amp-story-audio-sticker` to set it too.

Once this is merged, I'll submit a follow-up to https://github.com/ampproject/amp-toolbox/pull/1357 on the toolbox repo.

### CODE REVIEW

**Review by ychsieh — APPROVED** [review]

**Review by erwinmombay — APPROVED** [review]

**Comment by swissspidy** [comment]
Awesome, thanks. I just updated the branch so this should be ready for merge now.

Note that the failing Circle CI tests seem unrelated as they happen on `main` as well.

**Comment by swissspidy** [comment]
@erwinmombay @ychsieh Mind merging this one? :-)

**Comment by ychsieh** [comment]
Seems like Percy visual test is failing. Please re-run.

**Comment by swissspidy** [comment]
> Seems like Percy visual test is failing. Please re-run.

I just did, but to no avail. There's a snapshot that's missing on `main` but is not missing here 🤷 

Screenshot 2024-04-15 at 16 03 29

Maybe just approve the build on Percy?

**Comment by swissspidy** [comment]
@ychsieh OK, Percy is happy now 🤷  THis should be ready.

**Comment by ychsieh** [comment]
Could you sync and push to rerun the owners check(which also rerun everything tho)?

**Comment by ychsieh** [comment]
Could you sync and push to rerun owner check(would also rerun everything tho)?

**Comment by swissspidy** [comment]
That doesn't help with the owners check it seems

**Review by danielrozenberg — APPROVED** [review]

**Comment by danielrozenberg** [comment]
Looks like someone with OWNERS approval had to re-approve this, which I just did. Go ahead team and submit this when ready!

**Pull request merged**
