### PR TITLE
Publish c++ validator

### PR DESCRIPTION
**Pull request by amaltas**

### CODE REVIEW

**Review by Gregable — APPROVED** [review]

**Comment by amaltas** [comment]
@googlebot I fixed it.

**Comment by amaltas** [comment]
@googlebot I fixed it.

**Comment by amaltas** [comment]
Manually verified CLA for noreply@google.com

**Comment by amaltas** [comment]
Yes, I manually verify that noreply@google.com doesn't need CLA approval so I manually override the CLA label.

**Pull request merged**
