### PR TITLE
✨ Add inactive event types to amp-analytics

### PR DESCRIPTION
**Pull request by Galphimbl**
- Add inactive events.
It stops calculate "${totalEngagedTime}" when mouse leave document.

### CODE REVIEW

**Comment by zhouyx** [comment]
@rcebulko Do you know why the owner bot is requesting review from Avi with the following config? 
https://github.com/ampproject/amphtml/blob/bfc08c13166b530922beae728c3b1f9561726d75/extensions/amp-analytics/OWNERS#L4-L13

**Comment by rcebulko** [comment]
> @rcebulko Do you know why the owner bot is requesting review from Avi with the following config?
> https://github.com/ampproject/amphtml/blob/bfc08c13166b530922beae728c3b1f9561726d75/extensions/amp-analytics/OWNERS#L4-L13

@zhouyx Yes, though it took me a few minutes of looking around to figure it out. The `amphtml/test` directory has the wildcard owner `"name": "*"`, which would include Avi. The way the `requestReviews` modifier is generally used, it's desirable to have it apply only to the directory in which the modifier exists.

For example, imagine you're an owner of `/foo` with `requestReviews: false` and a regular owner of `/bar` where you've not been explicitly opted out. A PR *only* `/bar` would of course be relevant to you, and you could be requested. A PR touching both could still request you, and may determine that you're the most relevant reviewer since you own both (which is part of what happened here).

**Comment by zhouyx** [comment]
Thank you @rcebulko for the explanation. That makes a lot of sense. 

What's your suggestion to resolve the case.  To add the `requestReviews: false` setting to the global list?

**Comment by rcebulko** [comment]
> Thank you @rcebulko for the explanation. That makes a lot of sense.
> 
> What's your suggestion to resolve the case. To add the `requestReviews: false` setting to the global list?

I'd say there are a few approaches, depending on your goals. It's worth noting Avi won't always be added (he's just in the "reviewer pool" and was chosen this time). If Avi never wants to be added as a reviewer, he could exclude himself from the `/test` owners via `requestReviews: false`. With the current setup, on any PRs that don't touch a directory with a wildcard owner, he will never be added.

**Comment by zhouyx** [comment]
Got it. Thanks.

**Pull request merged**
