### PR TITLE
✨ New feature: Add amp-css-validator: a component that checks for unused css selectors

### PR DESCRIPTION
**Pull request by irenechang-ww**
Add a new component that checks for unused css selectors and reports them to the developer in the console. 

This should be stripped from cached AMP pages because this is development extension.

Co-authored-by: @cjdeleon62 @nickfalcone

### CODE REVIEW

**Comment by irenechang-ww** [comment]
@googlebot I signed it!

**Comment by Gregable** [comment]
Validator changes for @ampproject/wg-caching look good.

**Comment by irenechang-ww** [comment]
> I love the idea but I don't think this should be a component, we want to validate the CSS for everyone, not only pages that include the component. Let's find a better place for this?

Totally agree. We should not be showing this component to the page viewers but only to developers.
@jridgewell already pointed out we should remove this component in the cached version, but we can also explore how we can help developer remove this component before shipping? Any thoughts?

**Comment by honeybadgerdontcare** [comment]
Could it be something that is fetched and run when `#development=1` is present? The AMP Validator is fetched and run this way.

**Comment by wassgha** [comment]
We could most likely have this be part of the dev bundle of v0.js ?

**Comment by irenechang-ww** [comment]
Thanks for the suggestion!
Can I have some guidance on getting this in dev bundle? @wassgha 
Where does the logic of amp validator fetch and run live? @honeybadgerdontcare

**Comment by wassgha** [comment]
@irenechang-ww  here are a few code pointers on how validation is integrated:
https://github.com/ampproject/amphtml/blob/106d73eeabcdc6b7e732ed956f2500236f431ab9/src/amp.js#L134

and 

https://github.com/ampproject/amphtml/blob/c4a663d0ba13d0488c6fe73c55dc8c971ac6ec0d/src/validator-integration.js#L37

**Comment by jridgewell** [comment]
Development mode means the code is shipped to all users, though, unless we invest in some late loading logic (and infra). As an initial PR, I think this is still valuable.

**Comment by irenechang-ww** [comment]
I remember @jridgewell mentioned that validator does not understand css. 
That's why we decided to create a component for css validation. Do you think otherwise? @wassgha 

I added `getMode().development` as a check in the amp-css-validator so that the validation will only be invoked in development mode. https://github.com/ampproject/amphtml/pull/24974/commits/dbc6c8bc8f6aa3e6176f181ffb79207703b65e28
Hope that addressed the concern of validating css for everyone.

**Comment by wassgha** [comment]
> I remember @jridgewell mentioned that validator does not understand css.
> That's why we decided to create a component for css validation. Do you think otherwise? @wassgha
I wasn't suggesting we add this to the validator, I was only pointing at the way the validator is executed at a top level as opposed to as an extension, so essentially we can put the code in a file that lives next to `src/validator-integration`. However, as Justin mentioned that would cause the v0.js bundle size to increase. If my understanding is correct, we currently include the validator with v0.js (which we probably shouldn't anyway? @jridgewell  for comments on this, not sure how many people use the validator on a page in a production environment anyway).
My concern with an extension is that it's gonna be hard to deprecate it once people start using it, unless we invalidate amp pages that use the extension from the get-go.

**Comment by honeybadgerdontcare** [comment]
@jridgewell we include the validator.js in v0.js? That was not my understanding.

**Comment by jridgewell** [comment]
> If my understanding is correct, we currently include the validator with v0.js 

No, it's a separate binary. But it already has the infrastructure in place to build and serve it separate from everything else.

**Comment by wassgha** [comment]
> > If my understanding is correct, we currently include the validator with v0.js
> 
> No, it's a separate binary. But it already has the infrastructure in place to build and serve it separate from everything else.

so can't we use the same mechanism for this?

**Comment by jridgewell** [comment]
No, not likely. We'd have to include @ampproject/wg-infra, make this a new entrypoint file, and add the changes to runtime to include it in dev mode.

**Comment by mattwomple** [comment]
I'm interested in looking at this more closely in the coming days, but I wonder if you could let me know how well this supports CSS in `<template>` as is? For example, is this scenario covered?

`<amp-list>` has `src="/file1.json"` which renders content under `{{#test}}{{/test}}` and does not render content under `{{^test}}{{/test}}`. On tap with bind event, `<amp-list>` changes to `src="/file2.json"` which now renders content under `{{^test}}{{/test}}`, containing a bunch of CSS selectors that were not in `{{#test}}{{/test}}`.

**Comment by irenechang-ww** [comment]
> I'm interested in looking at this more closely in the coming days, but I wonder if you could let me know how well this supports CSS in `<template>` as is? For example, is this scenario covered?
> 
> `<amp-list>` has `src="/file1.json"` which renders content under `{{#test}}{{/test}}` and does not render content under `{{^test}}{{/test}}`. On tap with bind event, `<amp-list>` changes to `src="/file2.json"` which now renders content under `{{^test}}{{/test}}`, containing a bunch of CSS selectors that were not in `{{#test}}{{/test}}`.

Thanks for the interest! @mattwomple 
I believe this case is not covered.
That's why this is a warning not an error, also we used the wording `potentially unused css selector`.
Would love to be able to covered those dynamic loaded css but we are not able to do it to my knowledge. Any feedback is welcome!

**Comment by honeybadgerdontcare** [comment]
Naively, if this had a listener for certain components that may be dynamic, could it update the list of warnings based on what was loaded from the json files? IOW, reevaluate if the DOM has changed as a result of these other components.

**Comment by jridgewell** [comment]
Sure, that would work. Just up to us to create a UI to display what's currently unused and what has been used.

**Pull request closed without merging**
