### PR TITLE
🧪 Experimental Code: ✨ Sticky `gutter` and `sidebar` ad support

### LINKED ISSUE #18123: [Master Feature] Allow ads to be position fixed on desktop canoncial
We have a requirement to make an ad sticky in an article template for a publisher in the right hand column on desktop (AMP as canonical). If we add a position fixed the ad doesn't render.

In the same way the amp-sticky-ad has a height restriction, could amp-ads on desktop (or media query great than x pixels) that are position fixed have a max width. Our specific requirement is to render MPUs and double MPUs (300 wide).

### PR DESCRIPTION
**Pull request by AnuragVasanwala**
The goal of the PR is to provide sticky gutter and sidebar ad.

This is an experimental workaround just for the demonstration purpose with minor CSS modification in `amp-ad` (some JS) and `amp-sticky-ad`. AMP Ad core is left untouched.

> Please refer updated examples: https://github.com/ampproject/amphtml/pull/35216#issuecomment-885049411 and https://github.com/ampproject/amphtml/pull/35216#issuecomment-893544347

### Gutter Ads
Support for `sticky=left` and `sticky=right` are added for gutter-ads in `amp-ad`.
```html
<!-- Sticky Left Ad -->
<amp-sticky-ad>
  <amp-ad
    sticky="left"
    width="120"
    height="600"
    type="doubleclick"
    data-slot="/21730346048/test-skyscraper"
  >
    <div placeholder></div>
    <div fallback></div>
  </amp-ad>
</amp-sticky-ad>

<!-- Sticky Right Ad -->
<amp-sticky-ad>
  <amp-ad
    sticky="right"
    width="120"
    height="600"
    type="doubleclick"
    data-slot="/21730346048/test-skyscraper"
  >
    <div placeholder></div>
    <div fallback></div>
  </amp-ad>
</amp-sticky-ad>
```

### Sidebar Ad
Support for `sticky=sidebar` is added for sidebar-ad in `amp-ad` and `amp-sticky-ad`.
```html
<!-- Sticky Sidebar Ad -->
<amp-sticky-ad
  sticky="sidebar"
  style="padding: 10px; display: contents"
>
  <amp-ad
    sticky="sidebar"
    width="300"
    height="600"
    type="doubleclick"
    data-slot="/21730346048/test-skyscraper"
  >
    <div placeholder></div>
    <div fallback></div>
  </amp-ad>
</amp-sticky-ad>
```

### Examples
Two examples are added:
1. Sticky Gutter [with `position: fixed` inside `amp-sticky-ad`]
    - examples/sticky.ads.0.1.amp-gutter-ad.html
    - Gutter-Ad

2. Sticky Sidebar [with `position: sticky` inside 1amp-ad` and `amp-sticky-ad`]
    - examples/sticky.ads.0.1.amp-sidebar-ad.html
    - Sidebar-Ad

### Suggestions Required
- Determine desktop/mobile browser and disallow sticky gutter and sticky sidebar ad for mobile devices
  - How to check for desktop/mobile? By restricting window `innerWidth` or by checking `userAgent`?
- Ad size restriction so gutter ads do no encroach on the content space

Please feel free to provide correction/suggestions.

Fixes #18123

### CODE REVIEW

**Comment by kristoferbaxter** [comment]
Adding @lannka and @powerivq, can you take a look and discuss with UX?

**Comment by powerivq** [comment]
Hi @AnuragVasanwala

Thanks for this proposal.

1. `<amp-ad sticky=xx>` is designed to be a replacement of `<amp-sticky-ad>`, and we intend to deprecate amp-sticky-ad in the future. We are not expecting these two to appear simultaneously. Only having `<amp-ad sticky=left` should do the job.
2. Sticky sidebar appears closer to a traditional fixed size ads slot with `position: sticky`. It is not affixed to the viewport, but to a particular container. We can discuss relaxing that rule without having to introduce a different tag.

**Comment by powerivq** [comment]
@ampproject/wg-components for UX

**Comment by AnuragVasanwala** [comment]
Hi @powerivq  

Thank you so much for the quick response 🙂
Actually, I have to use `amp-sticky-ad` due to restriction in AMP core [`ad-helper`](https://github.com/ampproject/amphtml/blob/210cf84849f7dc7791ec05da0ba30d050a9ca0e3/src/ad-helper.js).

> Hi @AnuragVasanwala
> 
> Thanks for this proposal.
> 
> 1. `<amp-ad sticky=xx>` is designed to be a replacement of `<amp-sticky-ad>`, and we intend to deprecate amp-sticky-ad in the future. We are not expecting these two to appear simultaneously. Only having `<amp-ad sticky=left` should do the job.

Only following containers are allowed for `position: fixed` or `position: sticky`:
https://github.com/ampproject/amphtml/blob/210cf84849f7dc7791ec05da0ba30d050a9ca0e3/src/ad-helper.js#L23-L32

Here, anything other than `CONTAINERS` (as an ancestor) will not be rendered for `position: fixed` or `position: sticky`:
https://github.com/ampproject/amphtml/blob/210cf84849f7dc7791ec05da0ba30d050a9ca0e3/src/ad-helper.js#L47-L75

Due to above restriction, I have no option other than to use `amp-sticky-ad` as parent of `amp-ad` to allow for `position: fixed` or `position: sticky`. Would anyone guide me if I am missing something or how may I resolve it? 🤔

> 2. Sticky sidebar appears closer to a traditional fixed size ads slot with `position: sticky`. It is not affixed to the viewport, but to a particular container. We can discuss relaxing that rule without having to introduce a different tag.

Yes, it would be good if we can discuss and resolve.

**Comment by powerivq** [comment]
> Hi @powerivq
> 
> Thank you so much for the quick response 🙂
> Actually, I have to use `amp-sticky-ad` due to restriction in AMP core [`ad-helper`](https://github.com/ampproject/amphtml/blob/210cf84849f7dc7791ec05da0ba30d050a9ca0e3/src/ad-helper.js).
> 
> > Hi @AnuragVasanwala
> > Thanks for this proposal.
> > 
> > 1. `<amp-ad sticky=xx>` is designed to be a replacement of `<amp-sticky-ad>`, and we intend to deprecate amp-sticky-ad in the future. We are not expecting these two to appear simultaneously. Only having `<amp-ad sticky=left` should do the job.
> 
> Only following containers are allowed for `position: fixed` or `position: sticky`:
> https://github.com/ampproject/amphtml/blob/210cf84849f7dc7791ec05da0ba30d050a9ca0e3/src/ad-helper.js#L23-L32
> 
> Here, anything other than `CONTAINERS` (as an ancestor) will not be rendered for `position: fixed` or `position: sticky`:
> https://github.com/ampproject/amphtml/blob/210cf84849f7dc7791ec05da0ba30d050a9ca0e3/src/ad-helper.js#L47-L75
> 
> Due to above restriction, I have no option other than to use `amp-sticky-ad` as parent of `amp-ad` to allow for `position: fixed` or `position: sticky`. Would anyone guide me if I am missing something or how may I resolve it? 🤔
> 
> > 1. Sticky sidebar appears closer to a traditional fixed size ads slot with `position: sticky`. It is not affixed to the viewport, but to a particular container. We can discuss relaxing that rule without having to introduce a different tag.
> 
> Yes, it would be good if we can discuss and resolve.

That would mean to allowlist amp-ad for these `position` css. Changing it for amp-sticky-ad is futile anyways because it is to be deprecated.

**Comment by AnuragVasanwala** [comment]
> That would mean to allowlist amp-ad for these position css. Changing it for amp-sticky-ad is futile anyways because it is to be deprecated.

Hi @powerivq 

I have added `AMP-AD` into allowlist:
https://github.com/rtCamp/amphtml/blob/7d0e5118e0edd7e57795725d07eceabb9003eaf0/src/ad-helper.js#L23-L33

By adding `AMP-AD` into allowlist, following workaround is needed in order to render fixed bottom and top ad that are using `<amp-sticky-ad>` as parent of `<amp-ad>`:
https://github.com/rtCamp/amphtml/blob/7d0e5118e0edd7e57795725d07eceabb9003eaf0/src/ad-helper.js#L66-L70

### Updated Examples
#### Sticky SideBar
```html
<!-- Sticky Sidebar Ad -->
<amp-ad
  sticky="sidebar"
  width="300"
  height="600"
  type="doubleclick"
  data-slot="/21730346048/test-skyscraper"
>
  <div placeholder></div>
  <div fallback></div>
</amp-ad>
```

#### Sticky Gutter
```html
<!-- Sticky Left Ad -->
<amp-ad
  sticky="left"
  width="120"
  height="600"
  type="doubleclick"
  data-slot="/21730346048/test-skyscraper"
>
  <div placeholder></div>
  <div fallback></div>
</amp-ad>

<!-- Sticky Right Ad -->
<amp-ad
  sticky="right"
  width="120"
  height="600"
  type="doubleclick"
  data-slot="/21730346048/test-skyscraper"
  sticky="right"
>
  <div placeholder></div>
  <div fallback></div>
</amp-ad>
```

**Comment by AnuragVasanwala** [comment]
### ✨ New Feature

- Added support for userDefined padding for `gutter` ad

#### Example
```diff
<!-- Sticky Left Ad -->
<amp-ad
  sticky="left"
  width="120"
  height="600"
+  top="50"
+  left="25"
  type="doubleclick"
  data-slot="/21730346048/test-skyscraper"
>
  <div placeholder></div>
  <div fallback></div>
</amp-ad>

<!-- Sticky Right Ad -->
<amp-ad
  sticky="right"
  width="120"
  height="600"
+  top="50"
+  right="25"
  type="doubleclick"
  data-slot="/21730346048/test-skyscraper"
>
  <div placeholder></div>
  <div fallback></div>
</amp-ad>
```

**Comment by AnuragVasanwala** [comment]
Hey, whenever time permits, would you please review the latest updates:
1. `amp-ad` into `allowlist`
    - https://github.com/ampproject/amphtml/pull/35216#issuecomment-885049411
2. Support for user defined padding (for `gutter` ad)
    - https://github.com/ampproject/amphtml/pull/35216#issuecomment-893544347

@powerivq @lannka @dvoytenko

**Comment by powerivq** [comment]
This PR can be closed. `sticky=left` and `sticky=right` should work now.

**Comment by AnuragVasanwala** [comment]
> > This PR can be closed. `sticky=left` and `sticky=right` should work now. LMK if you find a problem.
> 
> Is there documentation for this?

Hi @powerivq & @raja-anbazhagan,
As per PR https://github.com/ampproject/amphtml/pull/36135, `sticky=left` and `sticky=right` works well 👍🏻

But, this PR(https://github.com/ampproject/amphtml/pull/35216) was intended to implement following features:
1. Sticky `gutter` Ad
   - with autoload on page load (instead of user scroll) (https://github.com/ampproject/amphtml/pull/35216/commits/07116f3427908f51e08bb92a748af61c2350fd79)
2. Sticky `sidebar` Ad

The PR https://github.com/ampproject/amphtml/pull/36135 solves following features:
- [x] Sticky `gutter` Ad
   - [ ] with autoload on page load (instead of user scroll)
- [ ] Sticky `sidebar` Ad

I would like to know whether the rest of the features mentioned in this PR are feasible or not. If feasible, please guide/correct wherever required or else I can close this PR.

**Comment by powerivq** [comment]
This sidebar example looks fine to me and should not raise any substantial usability problem. Is there a way to use css `position=sticky` to reach the same effect?

**Comment by AnuragVasanwala** [comment]
> This sidebar example looks fine to me and should not raise any substantial usability problem. Is there a way to use css `position=sticky` to reach the same effect?

Yes, it is possible to use `position=sticky`, refer:
https://github.com/ampproject/amphtml/blob/7d0e5118e0edd7e57795725d07eceabb9003eaf0/extensions/amp-ad/0.1/amp-ad.css#L185-L188

Also, working example (without `amp-sticky-ad`):
https://github.com/ampproject/amphtml/blob/7d0e5118e0edd7e57795725d07eceabb9003eaf0/examples/sticky.ads.0.1.amp-sidebar-ad.html#L428-L443

**Comment by powerivq** [comment]
@AnuragVasanwala If you can use `position=sticky`, great. It would be unnecessary to have a `sticky=sidebar` type. You should simply use a regular amp-ad slot and set its container to be `position=sticky`. If it was blocked by the runtime, we can discuss relaxing that.

**Comment by AnuragVasanwala** [comment]
> @AnuragVasanwala If you can use `position=sticky`, great. It would be unnecessary to have a `sticky=sidebar` type. You should simply use a regular amp-ad slot and set its container to be `position=sticky`.

@powerivq Absolutely, a regular `amp-ad` slot with its container to be `position=sticky` seems perfect!

> If it was blocked by the runtime, we can discuss relaxing that.

Actually, container holding `amp-ad` will be blocked if it is set to `position=fixed` or `position=sticky`. It is required to relax this rule for `amp-ad`.

These are the containers allowed for `fixed` and `sticky` position:
https://github.com/ampproject/amphtml/blob/4479ce52a8fb8c5bf3d3447763202b8036dffe0d/src/ad-helper.js#L9-L18

At following code, container having `position=fixed` or `position=sticky` that are not mentioned in [`CONTAINERS`](https://github.com/ampproject/amphtml/blob/4479ce52a8fb8c5bf3d3447763202b8036dffe0d/src/ad-helper.js#L9-L18) will be blocked:
https://github.com/ampproject/amphtml/blob/4479ce52a8fb8c5bf3d3447763202b8036dffe0d/src/ad-helper.js#L52-L57

It would be helpful if you can relax this rule for `amp-ad`.

**Pull request closed without merging**
