### PR TITLE
Enable text/javascript header type.

### PR DESCRIPTION
**Pull request by adamsilverstein**
🐛 Bug fix: Enable `text/javascript` content type for scripts loaded via `amp-script`.

Addresses https://github.com/ampproject/amphtml/issues/26259.

### CODE REVIEW

**Comment by erwinmombay** [comment]
@choumx for final review

**Comment by erwinmombay** [comment]
@adamsilverstein howdy, theres just a minor lint issue that needs to be fixed then I will merge this right away. Thanks!

I believe you just need to run `gulp lint --local_changes --fix`

**Comment by adamsilverstein** [comment]
@erwinmombay thanks for the tip: applied and pushed.

**Comment by adamsilverstein** [comment]
Trying a rebase to see if I can get what appears to be a flakey test to pass in Travis.

**Comment by adamsilverstein** [comment]
@erwinmombay This should be ready for re-review/merge.

**Pull request merged**
