### PR TITLE
✨#CA aja

### PR DESCRIPTION
**Pull request by matsuda-takehiro**
# Instructions:

- Pick a meaningful title for your pull request. (Use sentence case.)
  - Prefix the title with an emoji to identify what is being done. (Copy-paste the emoji itself (not the :code:) from the list below.)
  - Do not overuse punctuation in the title (like `(chore):`).
  - If it is helpful, use a simple prefix (like `ProjectX: Implement some feature`).
- Enter a succinct description that says why the PR is necessary, and what it does.
  - Mention the GitHub issue that is being addressed by the pull request.
  - The keywords `Fixes`, `Closes`, or `Resolves` followed the issue number will automatically close the issue.

# Example of a good description:

- Implement aspect X
- Leave out feature Y because of A
- Improve performance by B
- Improve accessibility by C

# Emojis for categorizing pull requests:

✨ New feature (`:sparkles:`)  
🐛 Bug fix (`:bug:`)  
🔥 P0 fix (`:fire:`)  
✅ Tests (`:white_check_mark:`)  
🚀 Performance improvements (`:rocket:`)  
🖍 CSS / Styling (`:crayon:`)  
♿ Accessibility (`:wheelchair:`)  
🌐 Internationalization (`:globe_with_meridians:`)  
📖 Documentation (`:book:`)  
🏗 Infrastructure / Tooling / Builds / CI (`:building_construction:`)  
⏪ Reverting a previous change (`:rewind:`)  
♻️ Refactoring (like moving around code w/o any changes) (`:recycle:`)  
🚮 Deleting code (`:put_litter_in_its_place:`)

### CODE REVIEW

**Comment by torch2424** [comment]
Hello! Thank you for your contribution! 😄 

If you have the chance:

1. Could you add a description about the PR, and give us some background on your vendor? 👍 

2. Seems like the Travis Unit tests are failing, Thus, these need to be fixed.

3. You may have to do another commit to get the CLA check to happen. As contributing to AMP requires a CLA.

Thanks again! I can do a review once this has been sorted out 😄

**Comment by matsuda-takehiro** [comment]
I'm sorry
Please wait a little 😭

I will try hard and fix it.

**Comment by matsuda-takehiro** [comment]
Hello.
We are A.J.A., a subsidiary of CyberAgent which provides ad-network service in Japan. (https://www.cyberagent.co.jp/) CA
(https://aja-kk.co.jp/) AJA
We'd like to add support to amp-embed.
Can you check if this pull request can be merged?
Thanks.

**Comment by torch2424** [comment]
No worries! Thank you for giving some context on what you are trying to accomplish.

Please take your time, and feel free to reach out and mention me ( @ ) when you are ready.

Thank you! 😄

**Pull request closed without merging**
