### PR TITLE
🐛Remove string.trimStart() from expander

### LINKED ISSUE #23432: Error: r.trimStart is not a function
```
Error: r.trimStart is not a function
at trimStart (https://raw.githubusercontent.com/ampproject/amphtml/1907152257550/src/service/url-expander/expander.js:153)
at (https://raw.githubusercontent.com/ampproject/amphtml/1907152257550/src/service/url-expander/expander.js:188)
at (https://raw.githubusercontent.com/ampproject/amphtml/1907152257550/src/service/url-expander/expander.js:280)
at parseUrlRecursively_ (https://raw.githubusercontent.com/ampproject/amphtml/1907152257550/src/service/url-expander/expander.js:88)
at expand (https://raw.githubusercontent.com/ampproject/amphtml/1907152257550/src/service/url-replacements-impl.js:972)
at expandStringAsync (https://raw.githubusercontent.com/ampproject/amphtml/1907152257550/extensions/amp-analytics/0.1/cookie-writer.js:210)
at expandAndWrite_ (https://raw.githubusercontent.com/ampproject/amphtml/1907152257550/extensions/amp-analytics/0.1/cookie-writer.js:123)
at init_ (https://raw.githubusercontent.com/ampproject/amphtml/1907152257550/extensions/amp-analytics/0.1/cookie-writer.js:68)
at write (https://raw.githubusercontent.com/ampproject/amphtml/1907152257550/extensions/amp-analytics/0.1/amp-analytics.js:230)
```

https://github.com/ampproject/amphtml/blob/4fa2a3fff693161112ce1d0d3731413a22702f71/src/service/url-expander/expander.js#L153

go/ampe/CPX3kej5m92CswE

### PR DESCRIPTION
**Pull request by calebcordry**
And introduce new trimStart helper in its place.

Closes #23432

### CODE REVIEW

**Comment by lannka** [comment]
I'm wondering why it was not failing any integration tests. @calebcordry could you take a look?

**Comment by calebcordry** [comment]
@lannka not sure about edge, but looks like `trimStart` works on Safari even though it is `compatibility unknown` on mdn.

**Comment by lannka** [comment]
Could you add an integration test that will cover this code in `test/integration/test-amp-pixel.js`?

**Comment by jridgewell** [comment]
https://kangax.github.io/compat-table/es2016plus/#test-string_trimming

Edge doesn't have it, FF got it in 60, and Safari got it in 12.

**Comment by calebcordry** [comment]
Introduced test in #23466

**Pull request merged**
