### PR TITLE
✨ Add support for Marfeel amp-ad

### PR DESCRIPTION
**Pull request by oscarmarimrf**
add support to amp-ad for the Marfeel type.
````
<amp-ad width="300" height="250"
    type="marfeel"
    data-tenant="demo.marfeel.com">
</amp-ad>
````

### CODE REVIEW

**Comment by oscarmarimrf** [comment]
@googlebot I signed it!

**Comment by oscarmarimrf** [comment]
@ampproject/build-cop Travis is failing on [End to End](https://travis-ci.org/github/ampproject/amphtml/jobs/689182714) and [Remote (SauceLabs)](https://travis-ci.org/github/ampproject/amphtml/jobs/689182715) tests, but it doesn't seem to be caused by this PR, I'm seeing the same error in other recent PRs.

How should I proceed?
Many thanks!

**Comment by oscarmarimrf** [comment]
Hi @calebcordry ,

Sure, we've updated our service to return always a sample ad for the demo account that is configured in the example. You should be able to see it now.

Thanks!

**Comment by calebcordry** [comment]
Thanks for contributing!

**Pull request merged**
