### PR TITLE
Remove unused attribute controls from <amp-anim>

### LINKED ISSUE #16936: amp-anim controls attribute not documented
The `controls` attribute is valid for `amp-anim` but it is not documented in [amp-anim.md](https://github.com/ampproject/amphtml/blob/master/extensions/amp-anim/amp-anim.md)

### PR DESCRIPTION
**Pull request by nainar**
Fixes #16936

### CODE REVIEW

**Comment by honeybadgerdontcare** [comment]
@nainar let me run some regression across docs to make this wont invalidate any.

**Comment by nainar** [comment]
@honeybadgerdontcare thank you! @aghassemi had the same idea.

**Comment by honeybadgerdontcare** [comment]
@nainar this appears to be fine.

**Comment by nainar** [comment]
@aghassemi - have @honeybadgerdontcare's go ahead. PTAL? Thanks!

**Pull request merged**
