### PR TITLE
Minify esbuild outputs in order

### PR DESCRIPTION
**Pull request by jridgewell**
Hopefully fixes https://github.com/ampproject/amphtml/issues/37014

### CODE REVIEW

**Comment by samouri** [comment]
Will want to manually verify this. I probably couldn't initially repro the issue while investigating https://github.com/ampproject/amphtml/issues/37014 because I was using custom modifications that reduced what I was building. Will likely need to do a full dist build to repro and verify this fixes it.

**Comment by jridgewell** [comment]
>  I probably couldn't initially repro the issue while investigating #37014 because I was using custom modifications that reduced what I was building.

I've been using this:

```diff
diff --git a/build-system/tasks/dist.js b/build-system/tasks/dist.js
index f1600b97ce..f62d57e7ed 100644
--- a/build-system/tasks/dist.js
+++ b/build-system/tasks/dist.js
@@ -117,34 +117,34 @@ async function dist() {
   await runPreDistSteps(options);
 
   // These steps use closure compiler. Small ones before large (parallel) ones.
-  if (argv.core_runtime_only) {
-    await compileCoreRuntime(options);
-  } else {
-    await Promise.all([
-      writeVersionFiles(),
-      buildExperiments(),
-      buildLoginDone('0.1'),
-      buildWebPushPublisherFiles(),
-      buildCompiler(),
-      compileAllJs(options),
-    ]);
-  }
+  // if (argv.core_runtime_only) {
+    // await compileCoreRuntime(options);
+  // } else {
+    // await Promise.all([
+      // writeVersionFiles(),
+      // buildExperiments(),
+      // buildLoginDone('0.1'),
+      // buildWebPushPublisherFiles(),
+      // buildCompiler(),
+      // compileAllJs(options),
+    // ]);
+  // }
 
   // This step internally parses the various extension* flags.
-  await buildExtensions(options);
+  // await buildExtensions(options);
 
   // This step is to be run only during a full `amp dist`.
-  if (
-    !argv.core_runtime_only &&
-    !argv.extensions &&
-    !argv.extensions_from &&
-    !argv.noextensions
-  ) {
+  // if (
+    // !argv.core_runtime_only &&
+    // !argv.extensions &&
+    // !argv.extensions_from &&
+    // !argv.noextensions
+  // ) {
     await buildVendorConfigs(options);
-  }
+  // }
 
   // This step is required no matter which binaries are built.
-  await formatExtractedMessages();
+  // await formatExtractedMessages();
 
   if (!argv.watch) {
     exitCtrlcHandler(handlerProcess);
```

However, because my computer is sooooo old, I don't have any race conditions because I don't have any threads! If you want to take this, it's trying to just generate the 3p vendor files in `dist.3p/*`, which seem to be very parallelized.

> If it works, we can also likely revert our custom id generation.

No, that needs to stay I think. If I'm changing a single char in string, I don't want to see a huge size change just because the frequency analysis decided some other char is now best to use for minification.

**Comment by jridgewell** [comment]
Bundle times don't seem to be hit, compare [A](https://app.circleci.com/pipelines/github/ampproject/amphtml/19966/workflows/32518bd8-ae51-49d8-b15d-5e626c9393a0) with [B](https://app.circleci.com/pipelines/github/ampproject/amphtml/19965/workflows/6c84c825-e640-4f29-9221-82c20bb8488f) (10min for both). But the file sizes still aren't consistent: [A](https://app.circleci.com/pipelines/github/ampproject/amphtml/19965/workflows/abff6107-c39c-4987-aa5a-9004c8a4a805/jobs/381738/parallel-runs/0/steps/0-113) with [B](https://app.circleci.com/pipelines/github/ampproject/amphtml/19965/workflows/6c84c825-e640-4f29-9221-82c20bb8488f/jobs/381876/parallel-runs/0/steps/0-113)

**Comment by samouri** [comment]
> No, that needs to stay I think. If I'm changing a single char in string, I don't want to see a huge size change just because the frequency analysis decided some other char is now best to use for minification.

I can imagine how this _could_ happen, but seeing as it was never a problem until we landed https://github.com/ampproject/amphtml/pull/36143, I don't think its a problem in practice.

**Comment by jridgewell** [comment]
Closing for #37043

**Pull request closed without merging**
