### PR TITLE
🐛 Accept layout attribute in amp-story-bookend tag

### LINKED ISSUE #15589: amp-story-bookend - error with "layout" attribute present/not present
I was testing the bookend for 1.0 and I found errors relating to the layout attribute.

If you **don't** specify a layout on amp-story-bookend (like the docs show), you get a Console error:

`Uncaught Error: Layout not supported: container. The element did not specify a layout attribute.` 

If you **do** put "layout=nodisplay" on amp-story-bookend you get a validation error:

`The attribute 'layout' may not appear in tag 'amp-story-bookend'.` 

(Tested with my [pets story](https://bpaduch.github.io/stamp/amp-pets-story-1-0/pets-completed.html) and the [ampconf story demo](https://github.com/ampproject/amphtml/blob/master/examples/amp-story/ampconf.html)).

### PR DESCRIPTION
**Pull request by Enriqe**
Fixes #15589

Accepts layout attribute for amp-story-bookend tag.

### CODE REVIEW

**Comment by Enriqe** [comment]
ready to merge @newmuis

**Comment by honeybadgerdontcare** [comment]
Please test a negative instance of this, such as setting the layout to responsive.

**Comment by Enriqe** [comment]
@honeybadgerdontcare ok will do in a follow up

**Comment by honeybadgerdontcare** [comment]
Please @ me as a reviewer on it, ty!

**Comment by Gregable** [comment]
Sorry if I'm late here, but this *requires* the layout attribute, which will break any existing usage. Is that intended?

**Pull request merged**
