### PR TITLE
✨ Yieldbot RTC

### PR DESCRIPTION
**Pull request by elljoh**
✨ 
- Add Yieldbot as an `a4a` callout vendor
  - Update respective Yieldbot doc
  - Remove outdated manual test for previous non-RTC impl
  - Refactor Yieldbot example to integrate via RTC

### CODE REVIEW

**Comment by elljoh** [comment]
Heya @bradfrizzell , I realize that there is always lot going on in this project.

However, since the _doubleclick.js_ deprecation change is deployed:
```
f.js:3 Error: The use of doubleclick.js has been deprecated. Please switch to Fast Fetch. See documentation here: https://github.com/ampproject/amphtml/issues/11834
    at la (f.js:7)
    at ja.g.H (f.js:2)
    at ja.g.error (f.js:3)
    at G (f.js:57)
    at Object.<anonymous> (f.js:263)
    at kt (yieldbot.intent.amp.js:formatted:800)
    at St (yieldbot.intent.amp.js:formatted:817)
    at It (yieldbot.intent.amp.js:formatted:822)
    at jt (yieldbot.intent.amp.js:formatted:842)
    at Object.updateState (yieldbot.intent.amp.js:formatted:44)
```
...if you have a chance, would you mind taking a look to see if this pull request can make it into someone's review pipeline.

**Comment by elljoh** [comment]
Thanks @bradfrizzell . Much appreciated!

**Comment by bradfrizzell** [comment]
FYI, this change will not get into canary until next week, and not into prod until the week after.

**Comment by elljoh** [comment]
@bradfrizzell understood.

I'd rather hoped we'd make the cut given your informal comment "[Tuesday the 20th](https://github.com/ampproject/amphtml/pull/12985#issuecomment-373835074)" when we were bantering about the _doubleclick.js_ deprecation process: a general and informal guideline comment I realize so I certainly don't have an axe to grind.

For my future reference, apart from (***me***) getting a pull request in with more timeliness, is there an emoji/label or a mention I should have made.

Thanks... merged so this is goodness. We/I believe in what the project is doing and want to be efficient and effective contributor members :)

**Pull request merged**
