### PR TITLE
🚀Use machine executor for validator tests

### PR DESCRIPTION
**Pull request by antiphoton**
Migrate CircleCI executor of validator tests from [docker](https://circleci.com/docs/2.0/configuration-reference/#docker-executor) to [machine](https://circleci.com/docs/2.0/configuration-reference/#machine-executor-linux), because `machine` executors offer twice the RAM, making it possible to build the new WebAssembly validator.

* [Example](https://app.circleci.com/pipelines/github/ampproject/amphtml/22688/workflows/74239346-5270-4626-a9e8-91cf5bb81c0d/jobs/451620/resources) WASM validator build fails in 16GB `docker` X-large.
* [Example](https://app.circleci.com/pipelines/github/ampproject/amphtml/22793/workflows/e623de8c-28af-493b-9bac-f6243edca4cd/jobs/454257) WASM validator build succeeds in 32GB `machine` X-large.

### CODE REVIEW

**Comment by danielrozenberg** [comment]
I see in CircleCI's docs that there _are_ Docker containers with 32GB (2xlarge), but they [require a review by their team](https://circleci.com/docs/2.0/configuration-reference/#:~:text=(2)%20This%20resource%20requires%20review%20by%20our%20support%20team). How about we try this approach first? //cc @rileyajones

**Comment by antiphoton** [comment]
| | docker x-large (16GB) | machine x-large (32GB) | 
| --- | --- | --- |
| C++ Validator |  [4m 27s](https://app.circleci.com/pipelines/github/ampproject/amphtml/22871/workflows/42dfb4fe-e34e-4fa1-9b28-ff00483b9ab6/jobs/456418) | [7m 12s](https://app.circleci.com/pipelines/github/ampproject/amphtml/22874/workflows/fbfe648e-98dc-4fef-85b9-3a2ee737c394/jobs/456472) |
| WASM Validator | [Out of Memory](https://app.circleci.com/pipelines/github/ampproject/amphtml/22688/workflows/74239346-5270-4626-a9e8-91cf5bb81c0d/jobs/451620/resources) | [19m 18s](https://app.circleci.com/pipelines/github/ampproject/amphtml/22793/workflows/e623de8c-28af-493b-9bac-f6243edca4cd/jobs/454257) |

Although `machine` offers twice RAW, the drawback will be an increased job duration. I agree that a 2x-large docker executor would be better.

**Comment by rileyajones** [comment]
I've got a meeting with CircleCI scheduled for tomorrow morning and I will ask them about access to larger docker containers.

**Comment by rileyajones** [comment]
We've had to reschedule until Thursday, I'll update this thread once I know more.

**Comment by rileyajones** [comment]
CircleCI said it was essentially a toggle to give us access to the 2xlarge resource so we should be getting it soon.

**Comment by antiphoton** [comment]
@rileyajones The 2x-large job is still getting [rejected](https://app.circleci.com/pipelines/github/ampproject/amphtml/23488/workflows/036eab85-7ee2-45cb-b54b-9a7cc1b20a31/jobs/472845).
```
Resource class 2xlarge for docker is not available for your project. This message will often appear if the pricing plan for this project does not support 2xlarge use. Default class medium will be used. Please contact your CSM person or our support team to whitelist your project.
```

**Comment by rileyajones** [comment]
@antiphoton I just reached out to them again, I'll keep you updated.

**Comment by rileyajones** [comment]
@antiphoton I just heard back from CircleCI they say it should work now

**Pull request closed without merging**
