### PR TITLE
Fix AMPHTML ads integration tests under FF & Edge

### PR DESCRIPTION
**Pull request by lannka**
This PR introduce no logic change to the tests. The indentation caused all the big blocks of code diff, you can just ignore.
- catch & ignore exceptions during iframe unregistration (tearDown), this fixes Edge tests
- FF tests just work
- Re-organized test descriptions to follow a same pattern.

/cc @zombifier

### CODE REVIEW

**Comment by alanorozco** [comment]
✌️😇👌

**Comment by lannka** [comment]
All tests passed.

Retry 1 ...

**Comment by lannka** [comment]
All tests passed again.

Retry 2 ...

**Comment by lannka** [comment]
All tests passed the third time!

**Pull request merged**
