### PR TITLE
Revcontent, support render-start (#5234)

### PR DESCRIPTION
**Pull request by e2corporation**
Add configuration support for accessing renderStart() API. See https://github.com/ampproject/amphtml/issues/5234 for additional details.

### CODE REVIEW

**Comment by lannka** [comment]
@e2corporation could you fix the broken example under `/examples/ads.amp.html`? See error in console:

screenshot from 2016-10-10 11 26 05

**Comment by e2corporation** [comment]
@lannka The GET error referenced in the console screenshot appears to be Network I/O related, is there an example URL where I can replay that error real-time? Thank you.

**Comment by lannka** [comment]
@e2corporation please follow the [guideline](https://github.com/ampproject/amphtml/blob/master/ads/README.md#developer-guidelines-for-a-pull-request) and try out your example locally.

**Comment by e2corporation** [comment]
@lannka This error does not occur locally or in production, can you verify that you are able to access that GET url directly?

**Comment by lannka** [comment]
@e2corporation loading the URL https://trends.revcontent.com/serve.js.php?w=203&t=rc_847&c=1476210280545&width=320 gives me this in my Chrome browser:

"This request has been denied. For more information please contact support@revcontent.com. (d31f795c-bfe2-4d08-aed2-67675908)"

**Comment by e2corporation** [comment]
@lannka After discussing with OPs this error is normal if accessed from behind specific firewalls or other private networks. Our fill endpoint defaults to production which is restricted by security policies. For internal development we override this setting with a data attribute.  

This PR will be closed and re-issued to flatten commits.

**Pull request closed without merging**
