### PR TITLE
♻️ Restructure viewport offset animation for performance

### PR DESCRIPTION
**Pull request by alanorozco**

### CODE REVIEW

**Comment by alanorozco** [comment]
@jridgewell PTAL. Happy to explore ways to extract `transformMutate`. It has a few dependencies on `FixedLayer` state, unfortunately.

**Comment by jridgewell** [comment]
Continuing discussion from https://github.com/ampproject/amphtml/pull/21083#discussion_r262683017:

> Hmm, transformMutate still has knowledge of transforms to apply the translate on top. It also knows which elements should be offset.

Can't get get this from the `el.style.transform`?

> It also serves as the single-source for elements that are mutated. 

I think this is actually a negative. I hate how complicated `FixedLayer` is, being able to split out animation code seems like a win.

`FixedLayer`'s tracking of transform is specifically to support offsetting the viewer header.  Nothing will break in FL if we remove transform support, but viewer's hide/show header won't be smooth. FL doesn't _need_ transform logic, the viewer needs FL's list of currently fixed elements. I think that means we put this logic in the wrong spot.

On top of this, we've now created arbitrary animation support. But for these arbitrary animations, we're taking complete ownership of the element from FL. I'm not 100% clear if the animation needs to information about the viewer header when it's doing it's thing, though. If it does, we could provide this as a `getHeaderTransform` method on viewer, and let the animation own its responsibilities. That should be a big code size win.

**Comment by alanorozco** [comment]
Some aspects are still unclear to me. Fixed-layer has some logic to:

- resolve the top (`mutateElement_`)
- determine whether an element is fixed at one point
- some lightbox logic I'm not sure about

So yeah, not entirely sure which parts should be encapsulated by fixed-layer? I also don't follow in giving the viewer transform responsibilities, so far `paddingTop` is tracked by viewport?

**Comment by alanorozco** [comment]
Superceded by #21417 due to revert.

**Pull request closed without merging**
