### PR TITLE
Force AMP pages to always paint once before installing extensions.

### PR DESCRIPTION
**Pull request by cramforce**
This makes AMP draw roughly half way into the JS initialization which is quite significant perceptual speedup. This comes at

- overall larger CPU usage (due to extra paint and more style recalc)
- and overall slightly longer start up (since waiting for frames to pass by).

### CODE REVIEW

**Comment by cramforce** [comment]
screen shot 2017-03-17 at 3 14 46 pm

Screenshot showing how a frame is pumped while JS is still super busy.

**Comment by cramforce** [comment]
PTAL. Added handling for extensions coming in while waiting on a frame and added tests.

**Comment by cramforce** [comment]
Added presence of render delaying services as a bailout condition, since we need them to run ASAP.

**Comment by dvoytenko** [comment]
LGTM

**Pull request merged**
