### PR TITLE
Removing CSS custom property content, and adding proper amp-custom to…

### PR DESCRIPTION
**Pull request by Meggin**
… style tag.

### CODE REVIEW

**Comment by cramforce** [comment]
Looks good! Please rebase the branch!

**Comment by cramforce** [comment]
@dvoytenko @Meggin Was faster than #1041 :)

**Comment by dvoytenko** [comment]
Do we still want #1041 to go through though? I will rebase and let's take a look.

**Comment by cramforce** [comment]
Please work it out :)

**Comment by dvoytenko** [comment]
@Meggin could you please rebase on master?

**Comment by Meggin** [comment]
Just rebased my branch with master. Sorry if this is a silly question, but
do you need me to do anything else? I've got the lastest.

**Comment by dvoytenko** [comment]
Did you push the new version?

**Comment by Meggin** [comment]
Yep. Pushed now. I think we are good to go?

**Pull request merged**
