### PR TITLE
🐛 Allow target=_self navigation on non validating amp documents

### PR DESCRIPTION
**Pull request by wille**
As I understand we can't allow target=_self navigation when on amp cached pages because amp cached pages serves the page in an iframe. Had some issues with this where I had to serve pages using the AMP runtime to users that embeds us in iframe elements, and any `AMP.navigateTo` action would escape the iframe and navigate in the top window.

A suggestion from @choumx https://github.com/ampproject/amphtml/issues/17943#issuecomment-509410681 was to disable this on obviously invalid amp pages.

### CODE REVIEW

**Comment by choumx** [comment]
Thanks for taking a stab at this! 

We should also make this opt-in behavior to avoid surprises to existing "dirty" (invalid) AMP pages. One way to do this is via an invalid attribute on the `<html>` tag, e.g.

```html
<!-- [allow-self-navigation] is invalid. -->
<html amp allow-self-navigation>
```

Are you looking to use this in a PWA (with AMP's `shadow-v0.js`) mode?

**Comment by wille** [comment]
Intending to use this so I can embed the document inside an iframe and have navigation working. The pages does not need to have a :zap: in the html opening tag.

Haven't looked into shadow-v0.js but that is definitely something I will do. I'll get some time to sort out the remaining tests ASAP.

Do you still think a attribute in the html opening tag is necessary? _self will need to be explicitly set on the target and it will not work if :zap: is present in the html.

**Comment by wille** [comment]
You'll have to opt in to use _self, it's not set by default. https://github.com/ampproject/amphtml/pull/25008/files#diff-99e54f471e8ece20f6b76271c9f59ac3R274-R280

**Comment by choumx** [comment]
Right, my point was that `allow-self-navigation` is a stronger signal than the absence of `amp` in the `<html>` tag. IMO this is useful because:

- Avoids potential surprising behavior for pages hosted from `foo.example` but use `amp-list` that fetches data from `bar.example`.
- It's more future-proof e.g. can allow toggling on/off other cache behaviors granularly.

**Comment by wille** [comment]
I say we default target _self to users that sets the <html> attribute. This will fit our use case the most and make most sense.

**Comment by choumx** [comment]
I think that's fine.

**Comment by mrjoro** [comment]
Is this PR still active?

**Pull request closed without merging**
